### ISSUE TITLE
SSH using public Keys - What am I missing?

### ISSUE THREAD

**Issue by maheshkudva** [ktbyers/netmiko#1000]
Here is my code to connect to the linux box using pvt/pub keys. What am I missing since it works perfectly when i use putty. I check issue #322 but that too did not help much.

The code->
 device = {'device_type': 'linux', 'ip': '192.168.219.145', 'username': 'mahesh', 'allow_agent': 'True', 'use_keys': 'True', 'key_file': 'C:/Users/mahesh/Desktop/mahesh.ppk', 'global_delay_factor': 10, 'timeout': 10}
net_connect = netmiko.ConnectHandler(**device)

Below is the auth error.

`
Traceback (most recent call last):
  File "C:\Users\mahesh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\netmiko\base_connection.py", line 689, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "C:\Users\mahesh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\paramiko\client.py", line 424, in connect
    passphrase,
  File "C:\Users\mahesh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\paramiko\client.py", line 714, in _auth
    raise saved_exception
  File "C:\Users\mahesh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\paramiko\client.py", line 701, in _auth
    self._transport.auth_password(username, password)
  File "C:\Users\mahesh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\paramiko\transport.py", line 1381, in auth_password
    return self.auth_handler.wait_for_response(my_event)
  File "C:\Users\mahesh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\paramiko\auth_handler.py", line 226, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mahesh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\netmiko\ssh_dispatcher.py", line 178, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\mahesh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\netmiko\base_connection.py", line 207, in __init__
    self.establish_connection()
  File "C:\Users\mahesh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\netmiko\base_connection.py", line 698, in establish_connection
    raise NetMikoAuthenticationException(msg)
netmiko.ssh_exception.NetMikoAuthenticationException: Authentication failure: unable to connect linux 192.168.219.145:22
Authentication failed.
>>>
`

Python==3.6.5
Netmiko==2.1.1
Paramiko==2.4.1

**Comment by ktbyers** [comment]
PPK files are putty specific; you need to convert these to the standard openSSH key file format:

http://blog.danyll.com/ssh-and-transfer-files-using-putty-private-key-ppk/

Also please upgrade to the most recent version of Netmiko.



Kirk

**Comment by maheshkudva** [comment]
Thanks Kirk. Your maintaining of the script and constant updates has helped the networking community
