### ISSUE TITLE
unable to connect to - aruba 2920 - syntax - python3 and netmiko 2.3.0

### ISSUE THREAD

**Issue by ezilg** [ktbyers/netmiko#1005]

**Comment by ezilg** [comment]
Hello, I am using python3 and netmiko 2.3.0
I try to send a command to a aruba 2920-switch, which has WB.16.05.0011
and get a message back :  Timed-out reading channel, data not available.
The same py-script sends the same command to a HP 2910-switch with W.15.14.0016
and get a message back  with the result which I expected.
What am I missing ?

**Comment by ezilg** [comment]
The command which I send to both is : show version

**Comment by ktbyers** [comment]
@ezilg Can you post your exception stack trace?

**Comment by ezilg** [comment]
`root@rzlapftp01:/home/zilg/scriptsonly/netmiko_scripts$ python3 show_version-3.py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/paramiko/channel.py", line 613, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/lib/python3/dist-packages/paramiko/buffered_pipe.py", line 151, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/netmiko/base_connection.py", line 147, in _read_channel_expect
    output += self.remote_conn.recv(MAX_BUFFER).decode('utf-8', 'ignore')
  File "/usr/lib/python3/dist-packages/paramiko/channel.py", line 615, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "show_version-3.py", line 12, in <module>
    net_connect = ConnectHandler(**A2920_1)
  File "/usr/lib/python3/dist-packages/netmiko/ssh_dispatcher.py", line 96, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/netmiko/base_connection.py", line 90, in __init__
    self.session_preparation()
  File "/usr/lib/python3/dist-packages/netmiko/hp/hp_procurve_ssh.py", line 24, in session_preparation
    self.disable_paging(command="\nno page\n")
  File "/usr/lib/python3/dist-packages/netmiko/base_connection.py", line 462, in disable_paging
    output = self.read_until_prompt()
  File "/usr/lib/python3/dist-packages/netmiko/base_connection.py", line 192, in read_until_prompt
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/netmiko/base_connection.py", line 149, in _read_channel_expect
    raise NetMikoTimeoutException("Timed-out reading channel, data not available.")
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.`

**Comment by ezilg** [comment]
In the meanwhile, I set up a new server by installing netmiko 2.3.0 right from the beginning without installing version 1.1 as I did with the first server.
Result : I can now place show-commands and config-commands on the 2nd server for HP 2910 and 2920 switches via python3 and netmiko 2.3.0
Any idea on how I can get this to to work on the 1st server without having to start from scratch ?

**Comment by ktbyers** [comment]
So you are saying your fresh install works fine, but the installation you upgraded doesn't work?

I would start with a clean Python virtual environment (i.e. create a new virtual environment on the failing server) and see if it works in the new virtual environment.

**Comment by ezilg** [comment]
OK, I did this and it worked.
But what can I do, if I don't want to create the 1st server once more, because other services
are running on it as well ?

**Comment by ktbyers** [comment]
Is there some reason, you can't create a new Python virtual environment on your `1st server` and run Netmiko from your new virtual environment and leave the other services as-is?

Another option is you can do a `pip freeze` from the working environment and compare it to the pip freeze from the failing environment and see if you can work out what is different between the two environments.

**Comment by ezilg** [comment]
Well, I left it as it is.
Thanks, this issue can be closed
