### ISSUE TITLE
unable to tftp firmware to HP 2920 

### ISSUE THREAD

**Issue by ezilg** [ktbyers/netmiko#1007]
Hello,
trying to update the firmware of a HP 2920 Switch via tftp fails.
I am able to configure the switch via Python. (enabling the tftp-client)
The final step, getting the software via a TFTP-Server results in an error message.

**### My script :**
```
`from netmiko import ConnectHandler

import netmiko
import sys

ip_list = sys.argv[1]                   
fobj = open(ip_list
lines = fobj.readlines()
fobj.close()

print (sys.argv)
print (ip_list)
print (lines)
for line in lines:
    ip = line.strip()                   # gelesene IP-Adresse
    if ip != "":
        print  ([ip])
        A2920_1 = {  
        'device_type':'hp_procurve',
        'ip':ip,   
        'username':'manager',
        'password':'secret',
        }
        net_connect = ConnectHandler(**A2920_1) 
        output = ip   
        print (output)   
        output = net_connect.send_command("show flash")
        print (output)
        config_commands=['no ip ssh filetransfer']
        output = net_connect.send_config_set(config_commands)
        print (output)
        config_commands=['tftp client']
        output = net_connect.send_config_set(config_commands)
        print (output)
        output = net_connect.send_command("ping 172.30.2.1")
        print (output)
        output = net_connect.send_command("copy tftp flash 172.30.2.1 J9729A/WB_16_05_0011.swi secondary")
        print (output)`

```
**### results in :**
```
172.30.1.16
mage             Size (bytes) Date     Version
----------------- ------------ -------- --------------
Primary Image    :    16738553 09/01/18 WB.16.05.0011
Secondary Image  :    16734354 06/20/18 WB.16.05.0009

Boot ROM Version
----------------
Primary Boot ROM Version   : WB.16.03
Secondary Boot ROM Version : WB.16.03

Default Boot Image   : Primary
Default Boot ROM     : Primary

config termC1-SW-20-212-2920-24G-01
(config)# no ip ssh filetransferC1-SW-20-212-2920-24G-01
(config)# endC1-SW-20-212-2920-24G-01#
config termC1-SW-20-212-2920-24G-01
(config)# tftp clientC1-SW-20-212-2920-24G-01
(config)# endC1-SW-20-212-2920-24G-01#
```

> instead of 172 the ping-answer misses the 1
> instead it shows :

`72.30.2.1 is alive, time = 4 ms`

> the copy tftp - command results in :
```
Traceback (most recent call last):
  File "cp_tftptoprim_of-2920list-3.py", line 42, in <module>
    output = net_connect.send_command("copy tftp flash 172.30.2.1 J9729A/WB_16_05_0011.swi secondary")
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 1188, in send_command
    search_pattern))
OSError: Search pattern never detected in send_command_expect: C1\-SW\-20\-212\-2920\-24G\-01\#

```
Note, the command executed on the switch shows :+1: 

```
C1-SW-20-212-2920-24G-01(config)# copy tftp flash 172.30.2.1 J9729A/WB_16_05_0011.swi secondary
The secondary image will be deleted.

Continue (y/n)? y
016M

Validating and Writing System Software to the Filesystem ...
```

Any ideas ?

**Comment by ktbyers** [comment]
Try:

```
    # note the expect_string argument
    output = net_connect.send_command("copy tftp flash 172.30.2.1 J9729A/WB_16_05_0011.swi secondary", expect_string=r"Continue")
    if "Continue" in output:
        # depending on how long the command takes, you might need to adjust delay_factor
        # delay_factor=4 should wait about 400 seconds maximum
        output += net_connect.send_command("y", expect_string=r"#", delay_factor=4)
```

**Comment by ezilg** [comment]
Great, that worked.
Thank you very much for your support, I appreciate it very much.
