### ISSUE TITLE
issue while using while doing jump server

### ISSUE THREAD

**Issue by ochougule** [ktbyers/netmiko#1009]
Hi

I need help to do ssh while i have jump sever. Please let me know how to do it.

**Comment by ochougule** [comment]
ERRors i am getting

Traceback (most recent call last):
  File "C:\Users\omkar\Desktop\ios\main1.py", line 26, in <module>
    net_connect = ConnectHandler(**device)                     ##connect the ssh connection
  File "C:\Python27\lib\site-packages\netmiko\ssh_dispatcher.py", line 218, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 270, in __init__
    self.establish_connection()
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 777, in establish_connection
    ssh_connect_params = self._connect_params_dict()
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 733, in _connect_params_dict
    conn_dict = self._use_ssh_config(conn_dict)
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 697, in _use_ssh_config
    proxy = paramiko.ProxyCommand(source['proxycommand'])
  File "C:\Python27\lib\site-packages\paramiko\proxy.py", line 57, in __init__
    self.cmd, stdin=PIPE, stdout=PIPE, stderr=PIPE, bufsize=0
  File "C:\Python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
