### ISSUE TITLE
SSH Proxy Configuration  exception

### ISSUE THREAD

**Issue by daHoerb** [ktbyers/netmiko#1015]
Hi Guys,
do you have any idea what this exception does mean?

```
Exception: ('ssh jumphost nc 10.10.0.198 22', 'Ein Vorgang bezog sich auf ein Objekt, das kein Socket ist')
Traceback (most recent call last):
  File "C:\Users\hdinnobl\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\proxy.py", line 97, in recv
    r, w, x = select([self.process.stdout], [], [], select_timeout)
OSError: [WinError 10038] Ein Vorgang bezog sich auf ein Objekt, das kein Socket ist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hdinnobl\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\transport.py", line 1966, in run
    self._check_banner()
  File "C:\Users\hdinnobl\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\transport.py", line 2138, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "C:\Users\hdinnobl\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\packet.py", line 367, in readline
    buf += self._read_timeout(timeout)
  File "C:\Users\hdinnobl\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\packet.py", line 561, in _read_timeout
    x = self.__socket.recv(128)
  File "C:\Users\hdinnobl\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\proxy.py", line 109, in recv
    raise ProxyCommandFailure(" ".join(self.cmd), e.strerror)
paramiko.ssh_exception.ProxyCommandFailure: ('ssh jumphost nc 10.10.0.198 22', 'Ein Vorgang bezog sich auf ein Objekt, das kein Socket ist')

Traceback (most recent call last):
  File "C:\Users\hdinnobl\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\proxy.py", line 97, in recv
    r, w, x = select([self.process.stdout], [], [], select_timeout)
OSError: [WinError 10038] Ein Vorgang bezog sich auf ein Objekt, das kein Socket ist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\hdinnobl\eclipse-workspace\PyNet\proxy_stiegl.py", line 12, in <module>
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\hdinnobl\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\hdinnobl\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\transport.py", line 2093, in run
    self.sock.close()
  File "C:\Users\hdinnobl\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\proxy.py", line 112, in close
    os.kill(self.process.pid, signal.SIGTERM)
PermissionError: [WinError 5] Zugriff verweigert

    net_connect = ConnectHandler(**device)
  File "C:\Users\hdinnobl\AppData\Local\Programs\Python\Python36\lib\site-packages\netmiko\ssh_dispatcher.py", line 218, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\hdinnobl\AppData\Local\Programs\Python\Python36\lib\site-packages\netmiko\base_connection.py", line 270, in __init__
    self.establish_connection()
  File "C:\Users\hdinnobl\AppData\Local\Programs\Python\Python36\lib\site-packages\netmiko\base_connection.py", line 782, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "C:\Users\hdinnobl\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\client.py", line 397, in connect
    t.start_client(timeout=timeout)
  File "C:\Users\hdinnobl\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\transport.py", line 587, in start_client
    raise e
  File "C:\Users\hdinnobl\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\transport.py", line 1966, in run
    self._check_banner()
  File "C:\Users\hdinnobl\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\transport.py", line 2138, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "C:\Users\hdinnobl\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\packet.py", line 367, in readline
    buf += self._read_timeout(timeout)
  File "C:\Users\hdinnobl\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\packet.py", line 561, in _read_timeout
    x = self.__socket.recv(128)
  File "C:\Users\hdinnobl\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\proxy.py", line 109, in recv
    raise ProxyCommandFailure(" ".join(self.cmd), e.strerror)
paramiko.ssh_exception.ProxyCommandFailure: ('ssh jumphost nc 10.10.0.198 22', 'Ein Vorgang bezog sich auf ein Objekt, das kein Socket ist')
```
Here is the code of the script:
`#!/usr/bin/env python
from netmiko import ConnectHandler

device = {
    'device_type': 'cisco_ios',
    'host': '10.10.0.198',
    'username': 'ntsadmin',
    'password': '********',
    'ssh_config_file': './config_stiegl'
}

net_connect = ConnectHandler(**device)
print(net_connect.find_prompt())
output = net_connect.send_command("show users")
print(output)`

Here is the ssh_config_file:
`host jumphost                   
  IdentityFile ~/.ssh/id_rsa    
  IdentitiesOnly yes               
  user hdinnobl
  hostname 10.10.0.145

host * !jumphost                
  ProxyCommand ssh jumphost nc %h %p`

ssh_config _file from cli does work.

**Comment by ktbyers** [comment]
SSH Proxy generally doesn't work from Windows. You would probably need the Linux subsystem on windows for it to work.

**Comment by carlniger** [comment]
Going to close as this is pretty old, but feel free to reopen if further discussion is needed. 

Feel free to join the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTQ5MjExNGNlNWIzMmRhOTZmNmZkNDA2Nzk4Y2Q1Y2RkMWNhZGEzM2Y5MjI0NDYxODkzM2M0ODIwYzFkMzVmZGY) where you can find a dedicated netmiko channel for questions/comments/etc!
