### ISSUE TITLE
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.

### ISSUE THREAD

**Issue by mohamedseleem11** [ktbyers/netmiko#1017]
I faced this problem while sending configuration, please help!

I am using netmiko and  paramiko last version, Cisco switch 2960, no secret password, ssh ver2, show command works well with (.send_command) tried with {.send_config_from_file() and .send_config_set()}

the cmd_file includes two lines for creating interface loopbacks just (interface lo 1999)
----------------------------------------------------code---------------------------------------------
    from datetime import datetime
    from netmiko import ConnectHandler
    
    host = '172.'
    platform = 'cisco_ios'
    device = ConnectHandler(device_type=platform, ip=host, username='admin', password='password')

    Tstart = datetime.now()
    print("\nLoading configuration..........")
    nip = device.send_config_from_file('cmd_file.txt')
    print(nip)
    Tend = datetime.now()
    Tdiff = Tend - Tstart
    print("\n Configuration loaded")
----------------------------------------------------issue---------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Mohamed-BTC\PycharmProjects\netmiko-final\venv\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Users\Mohamed-BTC\PycharmProjects\netmiko-final\venv\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mohamed-BTC\PycharmProjects\netmiko-final\venv\lib\site-packages\netmiko\base_connection.py", line 470, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\Users\Mohamed-BTC\PycharmProjects\netmiko-final\venv\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Mohamed-BTC/PycharmProjects/netmiko-final/netmico-1.py", line 49, in <module>
    nip = device.send_config_from_file('cmd_file.txt')
  File "C:\Users\Mohamed-BTC\PycharmProjects\netmiko-final\venv\lib\site-packages\netmiko\base_connection.py", line 1384, in send_config_from_file
    return self.send_config_set(cfg_file, **kwargs)
  File "C:\Users\Mohamed-BTC\PycharmProjects\netmiko-final\venv\lib\site-packages\netmiko\base_connection.py", line 1429, in send_config_set
    output = self.config_mode(*cfg_mode_args)
  File "C:\Users\Mohamed-BTC\PycharmProjects\netmiko-final\venv\lib\site-packages\netmiko\cisco_base_connection.py", line 42, in config_mode
    pattern=pattern)
  File "C:\Users\Mohamed-BTC\PycharmProjects\netmiko-final\venv\lib\site-packages\netmiko\base_connection.py", line 1345, in config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "C:\Users\Mohamed-BTC\PycharmProjects\netmiko-final\venv\lib\site-packages\netmiko\base_connection.py", line 542, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "C:\Users\Mohamed-BTC\PycharmProjects\netmiko-final\venv\lib\site-packages\netmiko\base_connection.py", line 478, in _read_channel_expect
    raise NetMikoTimeoutException("Timed-out reading channel, data not available.")
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.

**Comment by mohamedseleem11** [comment]
[test.log](https://github.com/ktbyers/netmiko/files/2619628/test.log)


I add:

logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

the result attached

**Comment by ktbyers** [comment]
@mohamedseleem11 What is in your config file?

cmd_file.txt


Note, don't put 'config term' in your config file, also don't put show commands in this file.  It should only be configuration changes.

**Comment by ktbyers** [comment]
What is executing `show hosts` that is in the log file?

**Comment by mohamedseleem11** [comment]
Before i execute the interface loopback 1999 and loopback1998 
I'm using (.send_command) to  (show hosts), not related to (.send_config_from_file)

**Comment by ktbyers** [comment]
Okay, please post the Python code that actually corresponds to the logging output.

**Comment by mohamedseleem11** [comment]
from datetime import datetime
from netmiko import ConnectHandler
import sys
import time
import select
import paramiko
import re
import logging


def oprint(toprint):
    print(toprint)
    fd.write(toprint)
    return;


logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")


# connect to the remote device
host = '172.16.7.17'
platform = 'cisco_ios'
device = ConnectHandler(device_type=platform, ip=host, username='admin', password='password')
# gets the device hostname
Hostname = device.send_command('show run | in hostname')
Host = Hostname[9:].splitlines()[0]

# creates the log file
fd = open(Host + '-log.txt', 'w+')
oprint('##############################################################\n')
oprint('..................' + Host + '...................\n')
output = device.send_command('terminal length 0')
output = device.send_command('enable')

# connect and run the show commands file
show_file = open('show.txt', 'r')
show_file.seek(0)
for each_line_show in show_file.readlines():
    oprint('##############################################################\n')
    oprint('..............CISCO COMMAND ' + each_line_show.rstrip() + ' OUTPUT.............\n')
    oprint('##############################################################\n')
    output = device.send_command(each_line_show)
    oprint(output + '\n')

# connect and run the cmd file
yes = {'', 'yes', 'y', 'ye'}
no = {'no', 'n'}
choise = input("Do you have commands to run? [y/n]").lower()
if choise in yes:
    Tstart = datetime.now()
    print("\nLoading configuration..........")
    nip = device.send_config_from_file("cmd_file.txt")
    print(nip)
    Tend = datetime.now()
    Tdiff = Tend - Tstart
    print("\n Configuration loaded")
    print("Time taken to push the configuration = " + str(Tdiff))

# close the connections
try:
    device.disconnect()
    show_file.close()
    fd.close()
except:
    exit()

**Comment by ktbyers** [comment]
And can you post your current exception.

**Comment by mohamedseleem11** [comment]
Traceback (most recent call last):
  File "C:\Users\Mohamed-BTC\PycharmProjects\netmiko-final\venv\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Users\Mohamed-BTC\PycharmProjects\netmiko-final\venv\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mohamed-BTC\PycharmProjects\netmiko-final\venv\lib\site-packages\netmiko\base_connection.py", line 470, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\Users\Mohamed-BTC\PycharmProjects\netmiko-final\venv\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Mohamed-BTC/PycharmProjects/netmiko-final/netmico-1.py", line 53, in <module>
    nip = device.send_config_from_file("cmd_file.txt")
  File "C:\Users\Mohamed-BTC\PycharmProjects\netmiko-final\venv\lib\site-packages\netmiko\base_connection.py", line 1384, in send_config_from_file
    return self.send_config_set(cfg_file, **kwargs)
  File "C:\Users\Mohamed-BTC\PycharmProjects\netmiko-final\venv\lib\site-packages\netmiko\base_connection.py", line 1429, in send_config_set
    output = self.config_mode(*cfg_mode_args)
  File "C:\Users\Mohamed-BTC\PycharmProjects\netmiko-final\venv\lib\site-packages\netmiko\cisco_base_connection.py", line 42, in config_mode
    pattern=pattern)
  File "C:\Users\Mohamed-BTC\PycharmProjects\netmiko-final\venv\lib\site-packages\netmiko\base_connection.py", line 1345, in config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "C:\Users\Mohamed-BTC\PycharmProjects\netmiko-final\venv\lib\site-packages\netmiko\base_connection.py", line 542, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "C:\Users\Mohamed-BTC\PycharmProjects\netmiko-final\venv\lib\site-packages\netmiko\base_connection.py", line 478, in _read_channel_expect
    raise NetMikoTimeoutException("Timed-out reading channel, data not available.")
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.

Process finished with exit code 1

**Comment by ktbyers** [comment]
Does you script finish properly if you don't do any configuration?

**Comment by mohamedseleem11** [comment]
Yes, its finished properly without configuration

**Comment by ktbyers** [comment]
Strange, the log file doesn't really give me any clues.

Does anything unusual happen if you execute your configuration changes manually on the device?

**Comment by mohamedseleem11** [comment]
Nothing i try the same configuration many times

**Comment by mohamedseleem11** [comment]
I thought that may be the hostname of my device causes this problem it contains many dashes inside it 
(CR-R-111-sa) like this

**Comment by ktbyers** [comment]
I am going to close this issue. If you still have an issue, then we can re-open it.

**Comment by AuthenticAMD** [comment]
I am seeing something like this as well. If I convert from using the send_config_set to just handling it with send_command then it doesn't happen. I'll have to update on what I'm doing with a later post.

**Comment by ktbyers** [comment]
@AuthenticAMD Please open a separate issue on this, you can link/reference this issue to the new issue.

**Comment by gozarrojas** [comment]
I could solve it by configuring on my network device: 
username gozarrojas privilege 15 gozarrojas secret

**Comment by russel73** [comment]
I faced the same issue, but adding the following line seems to solve it

#Add the following after you connect to switch
capture = net_connect.enable(cmd='enable 15')

hope this helps.
Russel

**Comment by kasar10** [comment]
> I faced the same issue, but adding the following line seems to solve it
> 
> #Add the following after you connect to switch
> capture = net_connect.enable(cmd='enable 15')
> 
> hope this helps.
> Russel

What does this command does?

**Comment by ktbyers** [comment]
That command elevates your privileges to level 15 and handles the password login required to do that.

**Comment by pavansam11** [comment]
> I faced the same issue, but adding the following line seems to solve it
> 
> #Add the following after you connect to switch
> capture = net_connect.enable(cmd='enable 15')
> 
> hope this helps.
> Russel

it worked for me thanks a lot...
