### ISSUE TITLE
Cisco ASA Simple Backup Configs with datetime

### ISSUE THREAD

**Issue by joseluisquisan** [ktbyers/netmiko#1042]
Hello,

Im newbie with python and netmiko,

Writing asking if you could help me with a python script.

I got this error:
(base) C:\Users\soc5-itq\Documents\LAB>python pruebassh.1.py
Traceback (most recent call last):
  File "pruebassh.1.py", line 19, in <module>
    output = net_connect.send_command("copy startup-config tftp:\n")
  File "build\bdist.win-amd64\egg\netmiko\cisco\cisco_asa_ssh.py", line 61, in s
end_command
  File "build\bdist.win-amd64\egg\netmiko\base_connection.py", line 1285, in sen
d_command
KeyboardInterrupt

(base) C:\Users\soc5-itq\Documents\LAB>

mycode
`
#!/usr/bin/env python

import datetime
from netmiko import ConnectHandler

cisco_asa = {
    'device_type': 'cisco_asa',
    'ip': '10.251.11.11',
    'username': 'username',
    'password': 'pa$$word',
    'secret': 'pa$$word',
    'verbose': False,
}

net_connect = ConnectHandler(**cisco_asa)
#net_connect.find_prompt()
output = net_connect.enable()
output = net_connect.send_command("copy startup-config tftp:\n")
output = net_connect.send_command("10.250.2.73\n")
output = net_connect.send_command("'thw-asa-01--' + '{0:%Y-%m-%d-%H-%M-%S}'.format(datetime.datetime.now()) + '.txt'", delay_factor=2)
output = net_connect.exit_enable_mode()
print output`

**Comment by joseluisquisan** [comment]
Done!

`#!/usr/bin/env python

from netmiko import ConnectHandler
from datetime import datetime
from datetime import date

today = str(date.today())
hostname = (today +"_FW.txt")

#Datos del Dispositivo
cisco_asa = {
    'device_type': 'cisco_asa',
    'ip': '10.251.11.11',
    'username': 'username',
    'password': 'pa$$word',
    'secret': 'pa$$word'
    'verbose': False,
}

#Listado de Comandos a ejecutar
commands = [
    'copy startup-config tftp:',
    '10.250.2.73',
    hostname,
]

#Toma del tiempo inicial del Script
start_time = datetime.now()
#Inicio del Script
net_connect = ConnectHandler(**cisco_asa)
net_connect.enable()
output = net_connect.send_config_set(commands)

print output
end_time = datetime.now()
total_time = end_time - start_time
print ("Tiempo total del Script " + str(total_time))
print ("La Fecha de hoy es " + today)`

**Comment by joseluisquisan** [comment]
But now, I have to do it with 5 Cisco ASA Firewalls more and 1 Cisco WLC.

I admit , this is not a "efficient code" but works. Is There any another way to optimize this?
