### ISSUE TITLE
Huawei vrpv8 commit func issue

### ISSUE THREAD

**Issue by kafooo** [ktbyers/netmiko#1072]
After commiting changes on huawei vrpv8, cli on devices look like this: 
```
[~HUAWEI]dot1x enable
[*HUAWEI]snmp-agent sys-info version all
Warning: SNMPv1/SNMPv2c is not secure, and SNMPv3 in either authentication or privacy mode is recommended.
[*HUAWEI]commit
[~HUAWEI]
```

with following code: 

```
from netmiko import Netmiko

device = {
    "host": "10.0.0.3",
    "username": "yyy",
    "password": "xxx",
    "device_type": "huawei_vrpv8",
    "session_log": "log_file2.txt"
}
config_commands = ['dot1x enable','snmp-agent sys-info version all']
net_connect = Netmiko(**device)

output = net_connect.send_config_set(config_commands,exit_config_mode=False)
output += net_connect.commit()
print(output)
```

i got this error: 

```
Traceback (most recent call last):
  File "/home/kafooo/PycharmProjects/nornir_scripts/venv/huawei_netmiko_test.py", line 18, in <module>
    output2 = net_connect.commit()
  File "/home/kafooo/PycharmProjects/nornir_scripts/venv/lib/python3.6/site-packages/netmiko/huawei/huawei_ssh.py", line 114, in commit
    strip_command=False, delay_factor=delay_factor)
  File "/home/kafooo/PycharmProjects/nornir_scripts/venv/lib/python3.6/site-packages/netmiko/base_connection.py", line 1206, in send_command_expect
    return self.send_command(*args, **kwargs)
  File "/home/kafooo/PycharmProjects/nornir_scripts/venv/lib/python3.6/site-packages/netmiko/base_connection.py", line 1188, in send_command
    search_pattern))
OSError: Search pattern never detected in send_command_expect: \[\*HUAWEI\]
```

looks like netmiko is expecting [*hostname] after commit, but in reality there is [~hostname] after commit

**Comment by ktbyers** [comment]
Fixed by #1073
