### ISSUE TITLE
Support connect esxi

### ISSUE THREAD

**Issue by Etuloser** [ktbyers/netmiko#1137]
When I try to connect esxi host use netmiko raise this error:

```python
def test_esxi_cli(self):
    from netmiko import ConnectHandler
    esxi = {
        'device_type': 'linux',
        'ip': '192.168.1.105',
        'username': 'root',
        'password': 'password',
    }
    net_connect = ConnectHandler(**esxi)
    output = net_connect.send_command('ls')
    print(output)


Error
Traceback (most recent call last):
  File "d:\develop\environment\Python\Python3.6.3\Lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "d:\develop\environment\Python\Python3.6.3\Lib\unittest\case.py", line 605, in run
    testMethod()
  File "D:\develop\project\cmb-vmop-demo\test\test_base.py", line 41, in test_esxi_cli
    net_connect = ConnectHandler(**esxi)
  File "D:\develop\project\cmb-vmop-demo\venv\lib\site-packages\netmiko\ssh_dispatcher.py", line 228, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "D:\develop\project\cmb-vmop-demo\venv\lib\site-packages\netmiko\base_connection.py", line 313, in __init__
    self._try_session_preparation()
  File "D:\develop\project\cmb-vmop-demo\venv\lib\site-packages\netmiko\base_connection.py", line 723, in _try_session_preparation
    self.session_preparation()
  File "D:\develop\project\cmb-vmop-demo\venv\lib\site-packages\netmiko\linux\linux_ssh.py", line 16, in session_preparation
    return super(LinuxSSH, self).session_preparation()
  File "D:\develop\project\cmb-vmop-demo\venv\lib\site-packages\netmiko\base_connection.py", line 743, in session_preparation
    self.set_base_prompt()
  File "D:\develop\project\cmb-vmop-demo\venv\lib\site-packages\netmiko\linux\linux_ssh.py", line 37, in set_base_prompt
    delay_factor=delay_factor,
  File "D:\develop\project\cmb-vmop-demo\venv\lib\site-packages\netmiko\base_connection.py", line 1042, in set_base_prompt
    raise ValueError("Router prompt not found: {0}".format(repr(prompt)))
ValueError: Router prompt not found: '[root@esx2f01j04u16pqh:~]'
```
then I see the source code in `base_connection.py` and modify it like this:
```python
 def set_base_prompt(
        self, pri_prompt_terminator="#", alt_prompt_terminator=">", delay_factor=1
    ):
        prompt = self.find_prompt(delay_factor=delay_factor)
        # if not prompt[-1] in (pri_prompt_terminator, alt_prompt_terminator):
        #     raise ValueError("Router prompt not found: {0}".format(repr(prompt)))
        # Strip off trailing terminator
        self.base_prompt = prompt[:-1]
        return self.base_prompt
```
```diff
- if not prompt[-1] in (pri_prompt_terminator, alt_prompt_terminator):
-     raise ValueError("Router prompt not found: {0}".format(repr(prompt)))
+ # if not prompt[-1] in (pri_prompt_terminator, alt_prompt_terminator):
+ #     raise ValueError("Router prompt not found: {0}".format(repr(prompt)))   
```
so how can I solve this problem better? or make a pull request to let netmiko support esxi host?

**Comment by ktbyers** [comment]
Does the prompt on ESXI not end in a `$` or a `#`?. Someone could submit a PR to accept an argument stating the prompt terminating character and then incorporate that into the Linux driver.

Note, however, Netmiko is not really intended for Linux support (in general). In other words, Linux support is very much a secondary use-case.

**Comment by Etuloser** [comment]
Thank you for your reply, its helpful for me.
