### ISSUE TITLE
Mellanox - error when disconnecting 

### ISSUE THREAD

**Issue by govind-rathod1987** [ktbyers/netmiko#1138]
I am using windows2016 with Python 2.7.13, Netmiko 2.3.0 and Paramiko 2.4.2
I  want to perform Mellanox switch reboot remotely with python script.  when i am trying to execute the code, I'm getting error as below:

C:\Python27\python.exe C:/Users/Administrator/PycharmProjects/NVMeoF/Modules/temp1.py
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/NVMeoF/Modules/temp1.py", line 57, in <module>
    if mellanox_switch_reboot(switch_json):
  File "C:/Users/Administrator/PycharmProjects/NVMeoF/Modules/temp1.py", line 34, in mellanox_switch_reboot
    output = net_connect.send_config_set(config_commands)
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 1440, in send_config_set
    output += self.exit_config_mode()
  File "C:\Python27\lib\site-packages\netmiko\mellanox\mellanox_ssh.py", line 45, in exit_config_mode
    if self.check_config_mode():
  File "C:\Python27\lib\site-packages\netmiko\mellanox\mellanox_ssh.py", line 24, in check_config_mode
    pattern=pattern)
  File "C:\Python27\lib\site-packages\netmiko\cisco_base_connection.py", line 31, in check_config_mode
    pattern=pattern)
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 1325, in check_config_mode
    self.write_channel(self.RETURN)
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 360, in write_channel
    self._write_channel(out_data)
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 331, in _write_channel
    self.remote_conn.sendall(write_bytes(out_data, encoding=self.encoding))
  File "C:\Python27\lib\site-packages\paramiko\channel.py", line 846, in sendall
    sent = self.send(s)
  File "C:\Python27\lib\site-packages\paramiko\channel.py", line 801, in send
    return self._send(s, m)
  File "C:\Python27\lib\site-packages\paramiko\channel.py", line 1180, in _send
    raise socket.error("Socket is closed")
socket.error: Socket is closed

Here is my code:
mlnx_sw = {
            'device_type': 'mellanox',
            'ip': 'x.x.x.x',
            'username': 'xx',
            'password': 'xx',
            'port': 22,  # optional, defaults to 22
            'secret': '',  # optional, defaults to ''
            'verbose': False  # optional, defaults to False
        }
net_connect = ConnectHandler(**mlnx_sw)
config_commands = ["reload"]
output = net_connect.send_config_set(config_commands)
print output
time.sleep(60)
 net_connect = ConnectHandler(**mlnx_sw)
 conn_status = net_connect.find_prompt()
if conn_status:
      print "Switch is up after reboot"

Note: I am able to run other config terminal commands and get the expected output, no issues there.

**Comment by daanvdsanden** [comment]
send_config_send wants to exit config mode. However since the switch is reloading the ssh connection is probabbly closed, so you have make sure that you don't send commands after the reload command.

You can use:
```python
net_connect.config_mode()
net_connect.send_command_timing("reload")
net_connect.disconnect()
```
Or disable exiting from config mode should also work:
```python
config_commands = ["reload"]
output = net_connect.send_config_set(config_commands,exit_config_mode=false)
print(output)
net_connect.disconnect()
```

**Comment by ktbyers** [comment]
Solutions recommended by @daanvdsanden are what you need to do here. The other option is to just send the `reload` and gracefully catch the exception that happens (since the SSH session just went away).
