### ISSUE TITLE
 netmiko.ssh_exception.NetMikoTimeoutException

### ISSUE THREAD

**Issue by nonioAtoz** [ktbyers/netmiko#1151]
I HAVE A SIMPLE SCRIPT USING NETMIKO MODULE, THAT FROM A FILE WITH CONFIGS, TRY TO CONFIGURE A CISCO SWITCH. THE PROBLEM IS THAT IT ONLY WORKS SOMETIMES IN A RANDOM WAY, LIKE I RUN THE SCRIPT ONE TIME , IT RAISES THIS ERROR, THEN I RUN AGAIN AND IT WILL CONFIGURE THE SWITCH. i ALSO DID A GOOGLE SEARCH AND THE BEST I COULD FIND WAS THIS : https://github.com/ktbyers/netmiko/issues/212 

**the ERROR :**  File "/usr/local/lib/python3.5/dist-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 519, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "compara_Configura.py", line 73, in <module>
    output = net_connect.send_config_from_file(ficheiro)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 1502, in send_config_from_file
    return self.send_config_set(cfg_file, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 1567, in send_config_set
    output += self.exit_config_mode()
  File "/usr/local/lib/python3.5/dist-packages/netmiko/cisco_base_connection.py", line 56, in exit_config_mode
    exit_config=exit_config, pattern=pattern
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 1478, in exit_config_mode
    if self.check_config_mode():
  File "/usr/local/lib/python3.5/dist-packages/netmiko/cisco/cisco_ios.py", line 32, in check_config_mode
    check_string=check_string, pattern=pattern
  File "/usr/local/lib/python3.5/dist-packages/netmiko/cisco_base_connection.py", line 38, in check_config_mode
    check_string=check_string, pattern=pattern
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 1448, in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 594, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 528, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.

****the sCRIPT** :**

!/usr/bin/env python3
# -*- encoding: utf-8 -*-
"""
This script read the running config from a network device , and read previous known running config
from a file , and it compares it . if both are equal it does not  do nothing .
if they are diferents try to configure the switch
"""
from netmiko import ConnectHandler
from netmiko.ssh_exception import NetMikoTimeoutException
from paramiko.ssh_exception import SSHException
from netmiko.ssh_exception import AuthenticationException
from show_run import show_run

iosv_l2 = {
        'device_type': 'cisco_ios',
        'ip' : '192.168.134.81',
        'username' : 'nuno',
        'password' : 'cisco'
#        'blocking_timeout':16,
#        'timeout': 60,
#        'session_timeout':60
}

# Call fucntion to get running config of cisco network device and store in
# a list " device_running_config"
device_running_config  = show_run(iosv_l2)
for line in device_running_config:
        line.splitlines()
print( device_running_config)

### open a configuration file from the equipment that we know that is correct
ficheiro = open("backup_s1","r")
linhas = ficheiro.read().splitlines()
ficheiro.close()
print("################################################################")
print(linhas)
print("################################################################")

# Compare 2 running configs - if they are equal do nothing . if they are
# diferent config the network device from a file

# file with the configuration commands of the network device
ficheiro = 's1_config'
if linhas == device_running_config:

    print( "###########################################################")
    print ("They are equal - do nothing")
    print ("############################################################")
else:
    print( "###########################################################")
    print ("they are diferent \n Preparing to config")
    print ("############################################################")
    try:
        net_connect = ConnectHandler(**iosv_l2)
    except (AuthenticationException):
        print ('Authentication failure: ' + ip_address_of_device)

    except (NetMikoTimeoutException):
        print ('Timeout to device: ' + ip_address_of_device)
        #continue
    except (EOFError):
        print ('End of file while attempting device ' + ip_address_of_device)
        #continue
    except (SSHException):
        print ('SSH Issue. Are you sure SSH is enabled? ' + ip_address_of_device)
        #continue
    except Exception as unknown_error:
output = net_connect.send_config_from_file(ficheiro)
    print (output)

Thanks you all !

**Comment by carlniger** [comment]
Are you changing the hostname by any chance? Also can you enable logging and post that here, see this link: https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by nonioAtoz** [comment]
Im running python on a network automation machine inside GNS3.
I found a file  /usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py that as the method refered. Its diferent from the example in the forum .
Nevertheless a put the line :

debug = True
  
 def read_until_pattern(self, *args, **kwargs):
        """Read channel until pattern detected. Return ALL data available."""
        return self._read_channel_expect(*args, **kwargs)


I run again de script to configure equipment and :

Preparing to config
############################################################
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 519, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "compara_Configura.py", line 74, in <module>
    output = net_connect.send_config_from_file(ficheiro)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 1504, in send_config_from_file
    return self.send_config_set(cfg_file, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 1569, in send_config_set
    output += self.exit_config_mode()
  File "/usr/local/lib/python3.5/dist-packages/netmiko/cisco_base_connection.py", line 56, in exit_config_mode
    exit_config=exit_config, pattern=pattern
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 1480, in exit_config_mode
    if self.check_config_mode():
  File "/usr/local/lib/python3.5/dist-packages/netmiko/cisco/cisco_ios.py", line 32, in check_config_mode
    check_string=check_string, pattern=pattern
  File "/usr/local/lib/python3.5/dist-packages/netmiko/cisco_base_connection.py", line 38, in check_config_mode
    check_string=check_string, pattern=pattern
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 1450, in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 595, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 528, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.


Run the script on a second try and it goes fine!

**Comment by ktbyers** [comment]
@nonioAtoz Try setting `global_delay_factor=4` in your device dictionary (that you pass to Netmiko):

```python
iosv_l2 = {
'device_type': 'cisco_ios',
'ip' : '192.168.134.81',
'username' : 'nuno',
'password' : 'cisco',
'global_delay_factor': 4,
}
```

Does that help?

**Comment by nonioAtoz** [comment]
It did nt work , 
'global_delay_factor': 4, nor 'global_delay_factor': 8 , nor 'global_delay_factor': 16.

but i ithink i have found the problem ( im also new to network devices and protocols and make a lot of mistakes):
I was changing the interface of the swicth ( changing encapsulation from isl to dot1q) that is  connected to the Linux network automation tool .
i removeed that configuration from the commands list and now  its working .
Thanks s 

![carambar](https://user-images.githubusercontent.com/48878285/55419933-c1a31f00-556d-11e9-99fc-0b676378a8a0.PNG)

**Comment by ktbyers** [comment]
@nonioAtoz Okay, so I am assuming that means that your change was disconnecting the Linux automation server where Netmiko was running--thus causing the connection to break?

**Comment by nonioAtoz** [comment]
i was perfoming this commands on switch 
interface range ethernet 0/0 - 2
switchport trunk encapsulation dot1q
switchport mode trunk
switchport trunk native vlan 1

and this ports were configured and the the connection breaks .
I have to run the script again so that all the configurations and this ports and all others to be configured.

I also run the same problem when reseting switch configuration to defaults .
