### ISSUE TITLE
Will TextFSM-Netmiko break on the next TextFSM release

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#1190]
Textfsm converted to a real package; concerned this will break the TextFSM netmiko integration.

**Comment by ChiShLy** [comment]
Hi @ktbyers ,
I recently upgraded textfsm in my environment to the new version (1.0.0).

textfsm is presented as a package for this version, and it seems to have broken 'netmiko/ textfsm' relationship in our environment....
Also, my other scripts were having issues importing "_terminal".

Traceback (most recent call last):
  File "/usr/bin/rdntool", line 23, in <module>
    rdntool.main()
  File "/usr/lib/python2.7/dist-packages/rdntools/helper/rdntool.py", line 288, in main
    from rdntools.discovery.discovery import DeviceDiscovery
  File "/usr/lib/python2.7/dist-packages/rdntools/discovery/discovery.py", line 25, in <module>
    from rdntools.discovery.driver.iosxr import IOSXRDeviceDiscovery
  File "/usr/lib/python2.7/dist-packages/rdntools/discovery/driver/iosxr.py", line 25, in <module>
    from rdntools.transport.driver.iosxr import IOSXRDeviceDriver
  File "/usr/lib/python2.7/dist-packages/rdntools/transport/driver/iosxr/__init__.py", line 20, in <module>
    from rdntools.transport.driver.iosxr.iosxr import IOSXRDeviceDriver
  File "/usr/lib/python2.7/dist-packages/rdntools/transport/driver/iosxr/iosxr.py", line 24, in <module>
    from napalm.iosxr import IOSXRDriver
  File "/usr/lib/python2.7/dist-packages/napalm/iosxr/__init__.py", line 22, in <module>
    from napalm.iosxr.iosxr import IOSXRDriver  # noqa
  File "/usr/lib/python2.7/dist-packages/napalm/iosxr/iosxr.py", line 29, in <module>
    from netmiko import __version__ as netmiko_version
  File "/usr/lib/python2.7/dist-packages/netmiko/__init__.py", line 8, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "/usr/lib/python2.7/dist-packages/netmiko/ssh_dispatcher.py", line 4, in <module>
    from netmiko.a10 import A10SSH
  File "/usr/lib/python2.7/dist-packages/netmiko/a10/__init__.py", line 2, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "/usr/lib/python2.7/dist-packages/netmiko/a10/a10_ssh.py", line 4, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "/usr/lib/python2.7/dist-packages/netmiko/cisco_base_connection.py", line 3, in <module>
    from netmiko.base_connection import BaseConnection
  File "/usr/lib/python2.7/dist-packages/netmiko/base_connection.py", line 24, in <module>
    from netmiko.utilities import write_bytes, check_serial_port, get_structured_data
  File "/usr/lib/python2.7/dist-packages/netmiko/utilities.py", line 9, in <module>
    from netmiko._textfsm import _clitable as clitable
  File "/usr/lib/python2.7/dist-packages/netmiko/_textfsm/__init__.py", line 3, in <module>
    from netmiko._textfsm import _clitable
  File "/usr/lib/python2.7/dist-packages/netmiko/_textfsm/_clitable.py", line 34, in <module>
    import copyable_regex_object
ImportError: No module named copyable_regex_object

**Comment by ktbyers** [comment]
@ChiShLy It doesn't look like this version of TextFSM is actually released--correct? I.E. you had to manually install that TextFSM version.

@carlniger This would probably be a good issue to work on as time comes up.

**Comment by ChiShLy** [comment]
@ktbyers That is correct. I packaged textfsm 0.4.1 using the latest commit (2a32ff6edf4915e5477c229c83196dfb81d44f89) in our environment.

**Comment by ktbyers** [comment]
Yes, it would be good to fix this prior to it getting released--of course it might be a bit hard as we might have to check/old new which is a bit challenging. Or alternatively, we just stage the fix and whenever they release the next version--we then pin to it.

**Comment by ChiShLy** [comment]
That sounds good. Thank you.

**Comment by carlniger** [comment]
#1292 for first draft, closing
