### ISSUE TITLE
Getting AttributeError 

### ISSUE THREAD

**Issue by girishb401** [ktbyers/netmiko#1211]
Traceback (most recent call last):
  File ".\NAT-LookupEXT-test.py", line 184, in <module>
    polcyID,SRCZoneSG,DSTZoneSG = ZONEfind(k,srcip[k],dstip[k],srcport[k],i,protocol[k],srczon,dstzon,net_connect)
  File "C:\Python27\Automation-FWchange\ZONEfind.py", line 25, in ZONEfind
    poly_out = net_connect.send_command("show security match-policies from-zone "+ str(srczon) + " to-zone " + str(dstzon) + " source-ip " + str(SRCIP) + " destination-ip " + str(DSTIP) + " source-port " + str(SRCPORT) + " des
tination-port " +  str(DSTPORT) + " protocol " + str(Protocol) + " | display xml | no-more ")
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 1068, in send_command
    prompt = self.find_prompt(delay_factor=delay_factor)
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 927, in find_prompt
    self.clear_buffer()
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 961, in clear_buffer
    self.read_channel()
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 395, in read_channel
    output = self._read_channel()
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 373, in _read_channel
    if self.remote_conn.recv_ready():
AttributeError: 'NoneType' object has no attribute 'recv_ready'

**Comment by OzNetNerd** [comment]
Can you please post your code? And, can you put it in a code block so it's easier to read?

**Comment by carlniger** [comment]
I'm going to close this now. If its still an issue please reformat your output and reopen with your script, version of netmiko you're using, and some more description about what you're trying to achieve. 

Also, feel free to join the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTQ5MjExNGNlNWIzMmRhOTZmNmZkNDA2Nzk4Y2Q1Y2RkMWNhZGEzM2Y5MjI0NDYxODkzM2M0ODIwYzFkMzVmZGY) where you can find a dedicated netmiko channel for questions/comments/etc if you're still having any issues.
