### ISSUE TITLE
Beginner to Netmiko - Cannot send configure commands

### ISSUE THREAD

**Issue by slogo-heinzy** [ktbyers/netmiko#1256]
Hi All.
First timer to this group and newbie to Netmiko

Ive successfully written a script to receive a show command from a  Cisco ASR 1001, but unable to enter conf t mode and run any commands in enable mode

would really appreciate help. Many thanks

****eg : working script****

#!/usr/bin/env python
from __future__ import absolute_import, division, print_function
from netmiko import ConnectHandler
import netmiko
import json
iosv_l2 = {
    'device_type': 'cisco_ios',
    'ip': 'x.x.x.x',            # removed
    'username': '',        # removed
    'password': ''         # removed
}
print('-'*79)
net_connect = ConnectHandler(**iosv_l2)
output = net_connect.send_command('show ip int brief | inc 0/0/3')
print (output)

OUTPUT:
$ python37 cmdrunner4txt.py
-------------------------------------------------------------------------------
GigabitEthernet0/0/3   unassigned      YES NVRAM  administratively down down

****failing script****

#!/usr/bin/env python
from __future__ import absolute_import, division, print_function
from netmiko import ConnectHandler
import netmiko
import json

iosv_l2 = {
    'device_type': 'cisco_ios',
    'ip': 'x.x.x.x',            # removed
    'username': '',        # removed
    'password': ''         # removed
}
print('-'*79)
net_connect = ConnectHandler(**iosv_l2)
output = net_connect.send_command('show run int gi0/0/3')
print(output)

ERROR RECEIVED:

$ python37 cmdrunner4txt.py
-------------------------------------------------------------------------------
                          ^
% Invalid input detected at '^' marker.

**The first password and ENABLE password are the same btw**

**Comment by carlniger** [comment]
@slogo-heinzy looks like you pasted the same code twice so not sure what the issue is, but you can check out this simple example which will maybe get you going: [config changes](https://github.com/ktbyers/netmiko/blob/develop/examples/configuration_changes/config_changes.py)

Basically you need to send a list of configs using `send_config_set` -- it handles getting into/out of configure mode and all that for you.

**Comment by slogo-heinzy** [comment]
@carlniger 
Thanks. The difference is that the commands are different. 
In the first script, the command is  a 'show 'command in cisco exec mode.( which is successful )
In the second script, the command is a 'show run' command in cisco privilege mode

I used your suggestion:

net_connect = ConnectHandler(**iosv_l2)
output = net_connect.send_config_set('show run int gi0/0/3')
print (output)

and recieved the lengthy  error below :


$ python37 cmdrunner4txt.py
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 519, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\Users\\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cmdrunner4txt.py", line 24, in <module>
    output = net_connect.send_config_set('show run int gi0/0/3')
  File "C:\Users\\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 1554, in send_config_set
    output = self.config_mode(*cfg_mode_args)
  File "C:\Users\\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\cisco_base_connection.py", line 50, in config_mode
    config_command=config_command, pattern=pattern
  File "C:\Users\\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 1461, in config_mode
    if not self.check_config_mode():
  File "C:\Users\\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\cisco\cisco_ios.py", line 32, in check_config_mode
    check_string=check_string, pattern=pattern
  File "C:\Users\\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\cisco_base_connection.py", line 38, in check_config_mode
    check_string=check_string, pattern=pattern
  File "C:\Users\\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 1448, in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "C:\Users\\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 594, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "C:\Users\\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 528, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.

**Comment by carlniger** [comment]
Ah I missed the "show" vs "show RUN" part :) The `send_config_set` is just for configuration commands. Looks like you're stuck on getting into global exec (or whatever the "#" prompt is called) and you probably need to just `enable` -- see [this example](https://github.com/ktbyers/netmiko/blob/develop/examples/enable/enable.py) and let us know if that helps. You'll want to pass the argument `secret` (for the enable pass) to the connection object, so something like this:

```
iosv_l2 = {
    'device_type': 'cisco_ios',
    'ip': 'x.x.x.x', # removed
    'username': '', # removed
    'password': '' # removed
    'secret': 'whatever'
}

conn = ConnectHandler(**ios_l2)
conn.enable()
conn.send_command("show run int blah")
```

**Comment by slogo-heinzy** [comment]
that worked - cheers for all your help  carlniger
