### ISSUE TITLE
delay_factor for connection initialization

### ISSUE THREAD

**Issue by mzbenami** [ktbyers/netmiko#126]
Hi Kirk,

We intermittently get this stack trace when connecting to Nexus devices:

```
SSH connection established to X.X.X.X:22
Interactive SSH session established
Traceback (most recent call last):
  File "/Users/mzb/.ansible/tmp/ansible-tmp-1447101573.0-35515167451694/ntc_show_command", line 1843, in <module>
    main()
  File "/Users/mzb/.ansible/tmp/ansible-tmp-1447101573.0-35515167451694/ntc_show_command", line 211, in main
    password=password
  File "/Library/Python/2.7/site-packages/netmiko/ssh_dispatcher.py", line 54, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/netmiko/base_connection.py", line 45, in __init__
    self.session_preparation()
  File "/Library/Python/2.7/site-packages/netmiko/base_connection.py", line 61, in session_preparation
    self.set_base_prompt()
  File "/Library/Python/2.7/site-packages/netmiko/base_connection.py", line 187, in set_base_prompt
    raise ValueError("Router prompt not found: {0}".format(prompt))
ValueError: Router prompt not found:
```

Our belief is that increasing the ``delay_factor`` in ``set_base_prompt()`` would solve this to account for the latency within the switch itself and whatever network latency there may be. Another option would be pushing the ``delay_factor`` param up the stack to ``ConnectHandler()``. If you like either of those options, we'd be happy to submit a PR.

Thanks,
Michael

**Comment by ktbyers** [comment]
@mzbenami We should probably put in a while loop and a check for recv_ready (something somewhat similar to the following). This is inside the set_base_prompt method.

            i = 0
            while i <= 10:
                time.sleep(1 * delay_factor)
                if self.remote_conn.recv_ready():
                    prompt = self.remote_conn.recv(MAX_BUFFER).decode('utf-8')
                else:
                    i += 1


I think I have documented on a separate issue converting delay_factor to a variable that gets initialized when the object is created, but this is a lot more work and has a lot more implications.

**Comment by ktbyers** [comment]
I will try to work on this today or tomorrow.
