### ISSUE TITLE
Multrithreading or Paramiko Error

### ISSUE THREAD

**Issue by Abed1985** [ktbyers/netmiko#1287]
Hi , 
I am running a working script on a 80 juniper junos devices. The script breaks after device number 60 . The below error is thrown. Its not related to multithreading pools , as I have 4 used , and when I even use 1 , the same thing occurs. I noticed in another script that uses legacy screen os paramiko the script runs fine on 50 devices but found that the result comes from only 30 deviecs . Before I debug the netmiko ( I havent done that before will check how) , what do you think the issue could be :

`Traceback (most recent call last):
  File "junos-getinterfaces.py", line 50, in <module>
    results = threads.map ( get_prompt , dev_list )
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "junos-getinterfaces.py", line 30, in get_prompt
    net_conn = Netmiko(**dev)
  File "/home/abooda/.local/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 242, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/abooda/.local/lib/python3.6/site-packages/netmiko/base_connection.py", line 312, in __init__
    self._open()
  File "/home/abooda/.local/lib/python3.6/site-packages/netmiko/base_connection.py", line 317, in _open
    self.establish_connection()
  File "/home/abooda/.local/lib/python3.6/site-packages/netmiko/base_connection.py", line 864, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/abooda/.local/lib/python3.6/site-packages/paramiko/client.py", line 406, in connect
    t.start_client(timeout=timeout)
  File "/home/abooda/.local/lib/python3.6/site-packages/paramiko/transport.py", line 660, in start_client
    raise e
  File "/home/abooda/.local/lib/python3.6/site-packages/paramiko/transport.py", line 2055, in run
    ptype, m = self.packetizer.read_message()
  File "/home/abooda/.local/lib/python3.6/site-packages/paramiko/packet.py", line 459, in read_message
    header = self.read_all(self.__block_size_in, check_rekey=True)
  File "/home/abooda/.local/lib/python3.6/site-packages/paramiko/packet.py", line 299, in read_all
    raise EOFError()
EOFError`

**Comment by carlniger** [comment]
Hard to guess with out any more context and obviously there are tons of variables at play here! Couple places to start that may or may not help...

- What version fo netmiko / paramiko are you using? Paramiko has had some recent releases I believe as well as netmiko
- Seems unlikely to be the issue, but have you tried to ratchet up delay factors?
- What is your AAA situation like? It seems reasonably common for "weird" things to happen w/ netmiko and lots of devices/threads/processes when AAA denies logins/authorizations

From the output it seems that the connection to whatever device isn't getting setup (failing in establish connection), so I would focus troubleshooting around there (again AAA seems to be a common theme in cases like this). Its probably worth trying to get session logs to see if there is anything useful there ([link](https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel))

**Comment by carlniger** [comment]
Going to go ahead and close this for now. Feel free to reopen if you've got more info and we can try to discuss. Also feel free to join the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTQ5MjExNGNlNWIzMmRhOTZmNmZkNDA2Nzk4Y2Q1Y2RkMWNhZGEzM2Y5MjI0NDYxODkzM2M0ODIwYzFkMzVmZGY) where you can find a dedicated netmiko channel for questions/comments/etc if you're still having any issues/want to chat real time with more folks!
