### ISSUE TITLE
textfsm.parser.TextFSMError: State Error raised.

### ISSUE THREAD

**Issue by varnumd** [ktbyers/netmiko#1312]
Simple script to show vlans on an HP switch using Netmiko with TextFSM.

```
from netmiko import Netmiko
from netmiko import ConnectHandler
from getpass import getpass

password = getpass("Enter password: ")
net_conn = ConnectHandler(device_type='hp_procurve', ip='172.16.1.1', username='admin', password=password)

output = net_conn.send_command("show vlans", use_textfsm=True)
print(output)
```

When I run this I get the following output

```
(arubatest) [16:19:45] dvarnum:arubaos $ python aruba-ipv6-fhs.py
Traceback (most recent call last):
  File "aruba-ipv6-fhs.py", line 21, in <module>
    output = net_conn.send_command("show vlans", use_textfsm=True)
  File "/Users/dvarnum/.virtualenvs/arubatest/lib/python3.7/site-packages/netmiko/base_connection.py", line 1340, in send_command
    output, platform=self.device_type, command=command_string.strip()
  File "/Users/dvarnum/.virtualenvs/arubatest/lib/python3.7/site-packages/netmiko/utilities.py", line 268, in get_structured_data
    textfsm_obj.ParseCmd(raw_output, attrs)
  File "/Users/dvarnum/.virtualenvs/arubatest/lib/python3.7/site-packages/netmiko/_textfsm/_clitable.py", line 272, in ParseCmd
    self.table = self._ParseCmdItem(self.raw, template_file=template_files[0])
  File "/Users/dvarnum/.virtualenvs/arubatest/lib/python3.7/site-packages/netmiko/_textfsm/_clitable.py", line 303, in _ParseCmdItem
    for record in fsm.ParseText(cmd_input):
  File "/Users/dvarnum/.virtualenvs/arubatest/lib/python3.7/site-packages/textfsm/parser.py", line 895, in ParseText
    self._CheckLine(line)
  File "/Users/dvarnum/.virtualenvs/arubatest/lib/python3.7/site-packages/textfsm/parser.py", line 944, in _CheckLine
    if self._Operations(rule, line):
  File "/Users/dvarnum/.virtualenvs/arubatest/lib/python3.7/site-packages/textfsm/parser.py", line 1025, in _Operations
    % (rule.line_num, line))
textfsm.parser.TextFSMError: State Error raised. Rule Line: 13. Input Line:  
```

If I execute _without_ using TextFSM I get the correct data back from the device:

```
(arubatest) [16:52:59] dvarnum:arubaos $ python aruba-ipv6-fhs.py     

 Status and Counters - VLAN Information

  Maximum VLANs to support : 256                  
  Primary VLAN : DEFAULT_VLAN    
  Management VLAN :                 

  VLAN ID Name                             | Status     Voice Jumbo
  ------- -------------------------------- + ---------- ----- -----
  1       DEFAULT_VLAN                     | Port-based No    No   
  198      internet-transit                 | Port-based No    No   
  199      oob-mgmt-new                     | Port-based No    No   
  1300     vlan300                          | Port-based No    No   
  1999     testing                          | Port-based No    No   
  2100    mgmt                             | Port-based No    Yes  
  3018    p2p_ln_ipv6                      | Port-based No    Yes  
 
```

Here is the ntc-template:

```
Value VLAN_ID (\d+)
Value NAME (.*?)
Value STATUS (\S+)
Value VOICE (Yes|No)
Value JUMBO (Yes|No)

Start
  ^.*VLAN ID -> VLAN

VLAN
  ^\s+${VLAN_ID}\s+${NAME}\s+(\|\s+|)${STATUS}\s+${VOICE}(\s+${JUMBO}|)\s*$$ -> Record
  ^\s+-+\s+-+\s+(\+\s+|)-+\s+-+(\s+-+|)\s*$$
  ^.*$$ -> Error
```

If I use this template in a separate textfsm file without Netmiko, it works:

```
import io
import textfsm

template = io.StringIO("""\
Value VLAN_ID (\d+)
Value NAME (.*?)
Value STATUS (\S+)
Value VOICE (Yes|No)
Value JUMBO (Yes|No)

Start
  ^.*VLAN ID -> VLAN

VLAN
  ^\s+${VLAN_ID}\s+${NAME}\s+(\|\s+|)${STATUS}\s+${VOICE}(\s+${JUMBO}|)\s*$$ -> Record
  ^\s+-+\s+-+\s+(\+\s+|)-+\s+-+(\s+-+|)\s*$$
  ^.*$$ -> Error
""")

fsm = textfsm.TextFSM(template)
result = fsm.ParseText("""\
 Status and Counters - VLAN Information

  Maximum VLANs to support : 256                  
  Primary VLAN : DEFAULT_VLAN    
  Management VLAN :                 

  VLAN ID Name                             | Status     Voice Jumbo
  ------- -------------------------------- + ---------- ----- -----
  1       DEFAULT_VLAN                     | Port-based No    No   
  198      internet-transit                 | Port-based No    No   
  199      oob-mgmt-new                     | Port-based No    No   
  1999     testing                          | Port-based No    No   
  2100    mgmt                             | Port-based No    Yes  
  3018    p2p_ln_ipv6                      | Port-based No    Yes  
""")

print(result)
```

Output:

```
(arubatest) [16:57:47] dvarnum:arubaos $ python textfsm_testing.py
['1', 'DEFAULT_VLAN', 'Port-based', 'No', 'No']
['198', 'internet-transit', 'Port-based', 'No', 'No']
['199', 'oob-mgmt-new', 'Port-based', 'No', 'No']
['1999', 'testing', 'Port-based', 'No', 'No']
['2100', 'mgmt', 'Port-based', 'No', 'Yes']
['2018', 'p2p_ln_ipv6', 'Port-based', 'No', 'Yes']
```

Note that Netmiko with TextFSM indeed works for other commands on hp_procurve, just failing with this one and I can't figure out why, especially since it works with using textfsm directly. Any ideas if this is a Netmiko-related issue or something else?

```
(arubatest) [16:58:15] dvarnum:arubaos $ pip freeze
asn1crypto==0.24.0
bcrypt==3.1.7
cffi==1.12.3
cryptography==2.7
future==0.17.1
Jinja2==2.10.1
MarkupSafe==1.1.1
netmiko==2.4.1
paramiko==2.6.0
pycparser==2.19
PyNaCl==1.3.0
pyserial==3.4
scp==0.13.2
six==1.12.0
textfsm==1.1.0
```

**Comment by ktbyers** [comment]
Looks like an ntc-templates issue with respect to your HP output i.e. it looks like you have data in the output that they are not expecting.

You probably should look to open up an issue on the ntc-templates repository.

**Comment by ktbyers** [comment]
@varnumd One other question does it work if you strip the trailing whitespace from the output

```
output = """
 Status and Counters - VLAN Information

  Maximum VLANs to support : 256                  
  Primary VLAN : DEFAULT_VLAN    
  Management VLAN :                 

  VLAN ID Name                             | Status     Voice Jumbo
  ------- -------------------------------- + ---------- ----- -----
  1       DEFAULT_VLAN                     | Port-based No    No   
  198      internet-transit                 | Port-based No    No   
  199      oob-mgmt-new                     | Port-based No    No   
  1999     testing                          | Port-based No    No   
  2100    mgmt                             | Port-based No    Yes  
  3018    p2p_ln_ipv6                      | Port-based No    Yes  
"""
output = output.strip()
```

**Comment by ktbyers** [comment]
@varnumd Ignore my earlier comments...

**Comment by ktbyers** [comment]
Can you print out the following:

```
output = net_conn.send_command("show vlans")
print(repr(output))
```

Thanks, Kirk

**Comment by varnumd** [comment]
Here's the output

```
>>> print(repr(output))
'\n Status and Counters - VLAN Information\n\n  Maximum VLANs to support : 256                  \n  Primary VLAN : DEFAULT_VLAN    \n  Management VLAN :                 \n\n  VLAN ID Name                             | Status     Voice Jumbo\n  ------- -------------------------------- + ---------- ----- -----\n  1       DEFAULT_VLAN                     | Port-based No    No   \n  198      internet-transit                 | Port-based No    No   \n  199      oob-mgmt-new                     | Port-based No    No   \n  1300     vlan300                          | Port-based No    No   \n  1999     testing                          | Port-based No    No   \n  2100    mgmt                             | Port-based No    Yes  \n  1124    VLAN1124                         | Port-based No    No   \n  3018    p2p_ln_ipv6                      | Port-based No    Yes  \n \n'
```

**Comment by varnumd** [comment]
I modified the template and got it to work.  Here is the original template:

```
Value VLAN_ID (\d+)
Value NAME (.*?)
Value STATUS (\S+)
Value VOICE (Yes|No)
Value JUMBO (Yes|No)

Start
  ^.*VLAN ID -> VLAN

VLAN
  ^\s+${VLAN_ID}\s+${NAME}\s+(\|\s+|)${STATUS}\s+${VOICE}(\s+${JUMBO}|)\s*$$ -> Record
  ^\s+-+\s+-+\s+(\+\s+|)-+\s+-+(\s+-+|)\s*$$
  ^.*$$ -> Error
```

And here is the modified template:

```
Value VLAN_ID (\d+)
Value NAME (.*?)
Value STATUS (\S+)
Value VOICE (Yes|No)
Value JUMBO (Yes|No)

Start
  ^.*VLAN ID -> VLAN

VLAN
  ^\s+${VLAN_ID}\s+${NAME}\s+(\|\s+|)${STATUS}\s+${VOICE}(\s+${JUMBO}|)\s*$$ -> Record
  ^\s+-+\s+-+\s+(\+\s+|)-+\s+-+(\s+-+|)\s*$$
```

It seems like something was getting caught with the `^.*$$ -> Error` syntax. Still not exactly sure why that would be but I'm sorry for opening the issue here as it seems to have been an issue with ntc-templates.

**Comment by ktbyers** [comment]
I wonder if it just doesn't like the trailing whitespace (the TextFSM template):

```
| Port-based No    Yes  \n \n'
```

It is erroring out on this: (just now saw your comment also confirming this)

```
  ^.*$$ -> Error
```

So I wonder if you had a whitespace catching line to the template if it works

So add this:

```
  ^\s+-+\s+-+\s+(\+\s+|)-+\s+-+(\s+-+|)\s*$$
  ^\s+$$
  ^.*$$ -> Error
```

I think ntc-templates added the error line to catch any lines that they missed. But they should probably be excluding whitespace from this (if that is what is causing it).

**Comment by varnumd** [comment]
Wow, you were spot-on - that did the trick! Thank you for taking the time to help me on this.

**Comment by ktbyers** [comment]
Probably should feed that back into ntc-templates if you can.

**Comment by carlniger** [comment]
Bam! Looks all sorted, closing!

**Comment by nethelp-traversa** [comment]
Hello guys,

Read this, tried this, configured the ntc_template hp_procurve_sh vlan with
"
Value VLAN_ID (\d+)
Value NAME (.*?)
Value STATUS (\S+)
Value VOICE (Yes|No)
Value JUMBO (Yes|No)

Start
  ^.*VLAN ID -> VLAN

VLAN
  ^\s+${VLAN_ID}\s+${NAME}\s+(\|\s+|)${STATUS}\s+${VOICE}(\s+${JUMBO}|)\s*$$ -> Record
  ^\s+-+\s+-+\s+(\+\s+|)-+\s+-+(\s+-+|)\s*$$
  ^\s+-+\s+-+\s+(\+\s+|)-+\s+-+(\s+-+|)\s*$$
  ^\s+$$
  ^.*$$ -> Error
"
It worked for a 2930 HP switch, but not for a 5412 HP.
