### ISSUE TITLE
Error with Netmiko program to find ARP on Comware router

### ISSUE THREAD

**Issue by fritzah** [ktbyers/netmiko#1313]
I am trying to create a program that will allow users to run this Netmiko script and find ARP information on a Comware device:

```
#!/usr/bin/env python

from netmiko import ConnectHandler
from datetime import datetime
import time
import sys

ip = input("\nEnter IP address to locate: ")
arp_command = ( 'dis arp' + ip )

comware = {
    'device_type': 'hp_comware',
    'ip': 'x.x.x.x',
    'username': 'test',
    'password': 'test',
    }
start_time = datetime.now()
print start_time

net_connect = ConnectHandler(**comware)
output = net_connect.send_command('arp_command')

time.sleep(3)
filename="comware-ip-arp.txt"

saveconfig=open(filename, 'w+')
saveconfig.write(output)
saveconfig.close()
time.sleep(2)
net_connect.disconnect()
```

When code is run I receive the following error:

```
Traceback (most recent call last):
  File "./20190730-find-mac.py", line 8, in <module>
    ip = input("\nEnter IP address to locate: ")
  File "<string>", line 1
    10.2.0.2
         ^
SyntaxError: invalid syntax
```

Any help would be greatly appreciated.

**Comment by fritzah** [comment]
Found issue, changed "input" to "raw_input" and removed the line:
arp_command = ( 'dis arp' + ip )
and change the net_connect line to the following:
output = net_connect.send_command('dis arp ' + ip )

I am now receiving the desired output. Thank you.
