### ISSUE TITLE
Issue with motd on Cisco IOS

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#134]

**Comment by ktbyers** [comment]
Was able to get this working as follows:

>>> motd = '''^
... *****************************************************************************
... * Big ugly banner with lots of text     *
... *****************************************************************************
... ^
... '''
>>> 
>>> cfg_str = 'banner motd {}'.format(motd)
>>> 
>>> output = net_connect.send_config_set([cfg_str])
>>> print output
config term
Enter configuration commands, one per line.  End with CNTL/Z.
pynet-rtr1(config)#banner motd ^
Enter TEXT message.  End with the character '^'.
*****************************************************************************
* Big ugly banner with lots of text     *
*****************************************************************************
^
pynet-rtr1(config)#end

**Comment by rupeshdaga** [comment]
While we are setting it in above style, I am getting lots of error as below

['banner motd ^\n *****************************************************************************\n * Big ugly banner with lots of text                                         *\n ****************************************************
*************************\n ^\n ']
Traceback (most recent call last):
  File "C:\Users\IXQ3852\AppData\Local\Continuum\anaconda3\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Users\IXQ3852\AppData\Local\Continuum\anaconda3\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\IXQ3852\AppData\Local\Continuum\anaconda3\lib\site-packages\netmiko\base_connection.py", line 569, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\Users\IXQ3852\AppData\Local\Continuum\anaconda3\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Rupesh/untitled/test.py", line 36, in <module>
    output = connect.send_config_set(banner_cmd)
  File "C:\Users\IXQ3852\AppData\Local\Continuum\anaconda3\lib\site-packages\netmiko\base_connection.py", line 1875, in send_config_set
    new_output = self.read_until_pattern(pattern=re.escape(cmd.strip()))
  File "C:\Users\IXQ3852\AppData\Local\Continuum\anaconda3\lib\site-packages\netmiko\base_connection.py", line 651, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "C:\Users\IXQ3852\AppData\Local\Continuum\anaconda3\lib\site-packages\netmiko\base_connection.py", line 580, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

**Comment by ktbyers** [comment]
@rupeshdaga Please open a new issue. Don't comment on already closed issues (a lot of times it is a different issue or just gets lost since the issue is closed).
