### ISSUE TITLE
Import of netmiko fails on Windows / Python 2.7.16

### ISSUE THREAD

**Issue by juggah** [ktbyers/netmiko#1358]
Hi,
when trying to import the netmiko module on a windows machine I encountered the following error:

-------
C:\Python27>python
Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:37:19) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import netmiko
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build\bdist.win-amd64\egg\netmiko\__init__.py", line 7, in <module>
  File "build\bdist.win-amd64\egg\netmiko\ssh_dispatcher.py", line 2, in <module>
  File "build\bdist.win-amd64\egg\netmiko\a10\__init__.py", line 1, in <module>
  File "build\bdist.win-amd64\egg\netmiko\a10\a10_ssh.py", line 3, in <module>
  File "C:\Python27\lib\site-packages\netmiko-3.0.0-py2.7.egg\netmiko\cisco_base_connection.py", line 155
    msg = f"Login failed: {self.host}"
                                     ^
SyntaxError: invalid syntax
>>>
-----

**Comment by carlmontanari** [comment]
You're trying to use the develop branch of netmiko (it looks like) which has dropped support for python 2.7. Use modern python or install netmiko from PyPI (current PyPI version should still support 2.7, but next release will not, so pin requirements if you need to).

**Comment by juggah** [comment]
Alright, thank you.
