### ISSUE TITLE
cant make connection with ubiquiti edge router

### ISSUE THREAD

**Issue by kroshira** [ktbyers/netmiko#1363]
Python version- 3.5.2
Netmiko version- 2.4.2
Paramiko version- 2.6.0

When attempting to make a connection with ubiquiti edgerouter lite i am receiving  error
```
ValueError: Router prompt not found: 'jmc@McgigglesEPR:~$'
```

python script is:

```
#!/usr/bin/env python3

import json
from os import mkdir
from netmiko import *

with open('network.json', 'r') as f:
    boxes = json.load(f)


def get_configs():
    for k, v in boxes.items():
        nested_device = [v]
        for data in nested_device:
            device = nested_device[0]['device_type']
            if device == 'corertr' or device == 'epr':
                category = 'routers'
            else:
                category = 'switches'
            if device == 'cisco_ios':
                config = 'show run\n'
            else:
                config = 'show configuration\n'
            output_file = nested_device[0]['host'] + ' output.txt'
            full_dir = (category + '/' + output_file)
            try:
                with open(full_dir, 'w') as file:
                    command_list = ['terminal length 0\n', config]
                    for i in command_list:
                        connect = ConnectHandler(**data)
                        output = connect.send_command(i)
                        file.write(output + '\n')
            except FileNotFoundError:
                mkdir(category)
                with open(full_dir, 'w') as file:
                    command_list = ['terminal length 0\n', config]
                    for i in command_list:
                        connect = ConnectHandler(**data)
                        output = connect.send_command(i)
                        file.write(output + '\n')

        print(nested_device[0]['host'] + ' complete')


get_configs()
```

json is 
```
{
 "epr":{
  "device_type": "ubiquiti_edge",
  "host": "epr",
  "username": "jmc",
  "password": "REDACTED",
  "verbose": "true"
 }

}
```

I found this issue (https://github.com/ktbyers/netmiko/issues/499) where it seems like the issue was resolved but i still cannot make it work.

**Comment by ktbyers** [comment]
Please post the full exception stack trace so we can see where the exception originated.

**Comment by kroshira** [comment]
```
Traceback (most recent call last):
  File "./config_pull.py", line 45, in <module>
    get_configs()
  File "./config_pull.py", line 30, in get_configs
    connect = ConnectHandler(**data)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/ssh_dispatcher.py", line 246, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 317, in __init__
    self._open()
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 323, in _open
    self._try_session_preparation()
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 738, in _try_session_preparation
    self.session_preparation()
  File "/usr/local/lib/python3.5/dist-packages/netmiko/ubiquiti/edge_ssh.py", line 17, in session_preparation
    self.set_base_prompt()
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 1068, in set_base_prompt
    raise ValueError("Router prompt not found: {0}".format(repr(prompt)))
ValueError: Router prompt not found: 'jmc@McgigglesEPR:~$'
```

**Comment by ktbyers** [comment]
That PR you referenced #499 was reverted.

Ubiquity Edge is for Edge Switch only. There is not currently any Ubiquity Edge Router support (as far as I am aware):

```
class UbiquitiEdgeSSH(CiscoSSHConnection):
    """
    Implements support for Ubiquity EdgeSwitch devices.
    Mostly conforms to Cisco IOS style syntax with a few minor changes.
    This is NOT for EdgeRouter devices.
    """
```

**Comment by kroshira** [comment]
ah. that would do it. thanks. what a shame.

**Comment by dmwyatt** [comment]
@kroshira Did you ever work on this?

**Comment by aungee** [comment]
`from netmiko import ConnectHandler

ubnt = {
    'device_type' : 'vyatta_vyos',
    'ip' : '192.168.0.1',
    'username' : 'ubnt',
    'password' : 'ubnt',
}
`
Works fine if you change the device_type to vyatta_vyos
