### ISSUE TITLE
Gettting this error while run the python script, but if i run it on interpreter then it works. 

### ISSUE THREAD

**Issue by abhibilwankar** [ktbyers/netmiko#1406]
File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\base_connection.py", line 884, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\paramiko\client.py", line 340, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\paramiko\client.py", line 204, in _families_and_addresses
    hostname, port, socket.AF_UNSPEC, socket.SOCK_STREAM
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\program_cisco_router.py", line 15, in <module>
    net_connect = ConnectHandler(ip=router['host'], username=router['user'],password=router['pass'],device_type=router['device_type'])
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\ssh_dispatcher.py", line 246, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\base_connection.py", line 317, in __init__
    self._open()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\base_connection.py", line 322, in _open
    self.establish_connection()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\base_connection.py", line 890, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios get_ip:22

**Comment by carlmontanari** [comment]
Without your code its not easy to help you. Also please format your post appropriately so it is easier to read.

Given that the error is `Connection to device timed-out` but you say it works in the interpreter I would wager you have an incorrect IP or port.

**Comment by ktbyers** [comment]
Duplicate with other thread you created.
