### ISSUE TITLE
OError: Search pattern never detected in send_command_expect

### ISSUE THREAD

**Issue by TechDawg** [ktbyers/netmiko#1429]
The issue I am facing occurs when running the following code : 

import netmiko 

connection = netmiko.ConnectHandler(ip="***.**.**.**", device_type="linux", 
                                    username="admin", password="admin")
output = (connection.send_command("admin display-config"))
print(output)
connection.disconnect() 

When I change "connection.send_command(admin display-config") to "connection.send_command (ping 8.8.8.8)", it runs fine and returns the ping results.
When I enter the code line by line in python cli, it returns the correct output of the command "display admin-config".

**Comment by TechDawg** [comment]
![image](https://user-images.githubusercontent.com/56436561/67304861-62e2ca00-f4ec-11e9-89c8-aeed8958f623.png)

**Comment by ktbyers** [comment]
Is `admin display-config` a very slow to execute command?

Make sure you are testing against the Netmiko `develop` branch as we have been doing a lot of work on Netmiko's reliability recently.

**Comment by TechDawg** [comment]
![image](https://user-images.githubusercontent.com/56436561/67304950-83ab1f80-f4ec-11e9-8b58-b99817e082b3.png)
![image](https://user-images.githubusercontent.com/56436561/67305045-ab01ec80-f4ec-11e9-84ad-1fd49c486a7c.png)

**Comment by TechDawg** [comment]
Wow! Thank you for a very fast response! Not particularly, the command executes within 5 seconds when executing manually. And yes is in develop branch.

**Comment by ktbyers** [comment]
You sure your branch is up to date? I say that as line '1337' is a comment in Netmiko's `develop` branch.

**Comment by TechDawg** [comment]
I installed netmiko through PIP and have just run an update command. With no update available, I have cloned netmiko git repo and still facing the same issue. I am fairly new to development, so I apologise if my terms are slightly ambiguous.

**Comment by ktbyers** [comment]
@TechDawg Okay, can you print `pip list | grep netmiko`?

**Comment by TechDawg** [comment]
![image](https://user-images.githubusercontent.com/56436561/67307127-e7831780-f4ef-11e9-9acd-21ca679ee433.png)

**Comment by ktbyers** [comment]
Okay, you need to `cd` to your directory where you did `git clone` and then `pip install -e`

```
git clone https://github.com/ktbyers/netmiko
cd netmiko
pip install -e .
```

Then `pip list | grep netmiko` again (should be 3.0.0 if it worked).

Then re-test

**Comment by TechDawg** [comment]
lachlan@lachlan-VirtualBox:~/Desktop/virtualenvironment/venv/lib/python3.7/site-packages/netmiko$ pip install -e

Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

**Comment by ktbyers** [comment]
You need the period at the end...

`pip install -e .`

**Comment by TechDawg** [comment]
Oops.... 
![image](https://user-images.githubusercontent.com/56436561/67308401-f2d74280-f4f1-11e9-96ca-c6bc680bb4dd.png)

**Comment by ktbyers** [comment]
No screenshots please...looking at screenshots is very unpleasant.

You probably need to move your code out of that directory--i.e. it doesn't like that `netmiko` folder being in the same directory as your code (which is causing the import to fail).

**Comment by TechDawg** [comment]
Sorry, noted. 
That netmiko was an accidental clone... I have deleted it and grep netmiko returns :

netmiko    3.0.0   /home/lachlan/Desktop/virtualenvironment/venv/lib/python3.7/site-packages/netmiko

When running the script, I still receive the error 

File "/home/lachlan/.local/lib/python3.7/site-packages/netmiko/base_connection.py", line 1337, in send_command
    search_pattern
OSError: Search pattern never detected in send_command_expect: A:I51\-SRc12\#

**Comment by ktbyers** [comment]
Okay, code still doesn't look like the `develop` branch...i.e. you are still running Netmiko 2.4.2. I say this as line 1337 is a comment.

But anyways try setting `global_delay_factor = 4` and see if it works. This is an argument to ConnectHandler.

**Comment by TechDawg** [comment]
`import netmiko 
connection = netmiko.ConnectHandler(ip="...", device_type="linux", 
                                    username="admin", password="admin", global_delay_factor = 4)`
returns the same issue

Is there an easy way I can remove netmiko 2.4.2?

**Comment by ktbyers** [comment]
`pip uninstall netmiko`

Then try to `import netmiko` and it should fail (hopefully).

**Comment by TechDawg** [comment]
Uninstalled `sudo pip uninstall netmiko
Uninstalling netmiko-3.0.0:
  Would remove:
    /usr/local/lib/python2.7/dist-packages/netmiko.egg-link
Proceed (y/n)? y
  Successfully uninstalled netmiko-3.0.0
`

However I can still import

**Comment by TechDawg** [comment]
from python terminal

**Comment by TechDawg** [comment]
should I manually remove netmiko folder from site-packages?

**Comment by ktbyers** [comment]
You have a Python path issue going on:

`/usr/local/lib/python2.7`

Start using `python -m pip` so that you ensure your Python and Pip are coupled together.

First, make sure your `python` is the `python3.7` python...though.

**Comment by TechDawg** [comment]
I see... I must have multiple versions of python installed...
grep netmiko is returning 2.4.2...

**Comment by TechDawg** [comment]
in my dir `~/Desktop/virtualenvironment/venv/lib/python3.7/site-packages/netmiko`

**Comment by TechDawg** [comment]
okay, I was not in my virtual environment, causing a load of issues. 
`Uninstalling netmiko-2.4.2:
  Would remove:
    /home/lachlan/Desktop/virtualenvironment/venv/lib/python3.7/site-packages/netmiko-2.4.2.dist-info/*
Proceed (y/n)? y
  Successfully uninstalled netmiko-2.4.2
`
Is the correct uninstall

**Comment by ktbyers** [comment]
Yep...looks right.

2.4.2 is the current version on pypi, but you need the `develop` branch which is `3.0.0`

**Comment by TechDawg** [comment]
reinstalled netmiko, but now `pip list |  net miko ` returns nothing..

**Comment by TechDawg** [comment]
but when I am outside of virtual env, it returns  3.0.0?

**Comment by TechDawg** [comment]
Going to give up for today... I am so frustrated... and stupid...and the last person in the office... I have uninstalled netmiko on all versions of python.  Sorry for wasting your valuable time, but thanks for the support.

**Comment by ktbyers** [comment]
You mentioned this above:

`reinstalled netmiko`

How did you do your `reinstall`? i.e. what command did you execute?

**Comment by TechDawg** [comment]
Hi, thanks for your patience...

After removing all occurrences of netmiko, I reinstalled into  `~/Desktop/virtualenvironment/venv/lib64/python3.7/site-packages` using `sudo git clone https://github.com/ktbyers/netmiko.git`
and then executing  `python3 -m pip install .` (all of this was in my venv terminal)

The install partially returned  `requirements already satisfied`... and pip list | net miko returned nothing in both my venv and normal env. 

I am now going to delete and reinstall my venv and try to run through steps : 
`git clone https://github.com/ktbyers/netmiko
cd netmiko
pip install -e .`

and report how it goes. 

Thanks

**Comment by TechDawg** [comment]
Okay... so... 
In my new venv, `python --version` returns  `Python 3.7.5rc1`

I then executed `/Desktop/virtualenvironment/venv/lib/python3.7/site-packages/netmiko$ sudo python -m pip install .`

This returned `requirement already satisfied: paramiko>=2.4.3 in /usr/local/lib/python2.7/dist-packages (from netmiko==3.0.0) (2.6.0)`

I had to manually remove netmiko and dependencies from `/usr/local/lib/python3.7/dist-packages`

and I am now going to try and execute `python -m pip install .` from netmiko dir... one more time..

**Comment by TechDawg** [comment]
It is still trying to isntall into `/usr/local/lib/python2.7/dist-packages`

`python -m pip --version`
returns 
`pip 18.1 from /home/lachlan/Desktop/virtualenvironment/venv/lib/python3.7/site-packages/pip (python 3.7)`
I have no idea why it isn't installing in the right place...

**Comment by TechDawg** [comment]
okay... I realised that the majority of the problems were due to using sudo before executing some of the commands... 

after deleting and re-creating my venv, git cloning, and python -m pip install, `pip list | grep netmiko` now returns the correct output from my venv. 

I am now getting a new error when trying to run the original script (complaining about line 1379): 
finally, I think I am using the develop branch
`python 2.py
Traceback (most recent call last):
  File "2.py", line 5, in <module>
    print(connection.send_command("admin display-config"))
  File "/home/lachlan/Desktop/virtualenvironment/venv/lib/python3.7/site-packages/netmiko/base_connection.py", line 1379, in send_command
    search_pattern
OSError: Search pattern never detected in send_command_expect: A:I51\-SRc12\#`

**Comment by TechDawg** [comment]
Success! 
The reason it wasn't returning anything is  because the router terminal requires the user to press space bar to scroll to the bottom of the config output. adding the line `connection.send_command("environment no more")`
fixed the issue. 

Once again, thanks for all the help :)

**Comment by ktbyers** [comment]
@TechDawg What platform are you connecting to?

Your ConnectHandler call is using Linux?

```
connection = netmiko.ConnectHandler(ip="...*", device_type="linux",
username="admin", password="admin")
```

**Comment by ktbyers** [comment]
The device_type in your code is `linux`, you probably should be using the `alcatel_sros`. Netmiko should automatically handle the disabling of output paging (for a given device_type).

**Comment by TechDawg** [comment]
Ahh I see, that's a nice feature :). I had copied `connection = netmiko.ConnectHandler(ip="...*", device_type="linux",` from another script and must have forgotten to change the device_type. 
Just amended `linux` to `alcatel_sros` and removed  `connection.send_command("environment no more")` and everything is working just fine :).

once more, thanks for your help and fast response :)
