### ISSUE TITLE
i got this error :netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: huawei_vrpv8 'ip' :22

### ISSUE THREAD

**Issue by poyantu** [ktbyers/netmiko#1467]
hi guys
im begginer for netmiko
please help me 

igot this error

◆error
```
----
Traceback (most recent call last):
  File "C:\Users\aaa\anaconda3\lib\site-packages\netmiko\base_connection.py", line 884, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "C:\Users\aaa\anaconda3\lib\site-packages\paramiko\client.py", line 349, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "C:\Users\aaa\anaconda3\lib\site-packages\paramiko\util.py", line 280, in retry_on_signal
    return function()
  File "C:\Users\aaa\anaconda3\lib\site-packages\paramiko\client.py", line 349, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
TimeoutError: [WinError 10060] 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/aaa/PycharmProjects/python_bupj/backup_main.py", line 33, in <module>
    net_connect = ConnectHandler(**device)
  File "C:\Users\aaa\anaconda3\lib\site-packages\netmiko\ssh_dispatcher.py", line 246, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\aaa\anaconda3\lib\site-packages\netmiko\base_connection.py", line 317, in __init__
    self._open()
  File "C:\Users\aaa\anaconda3\lib\site-packages\netmiko\base_connection.py", line 322, in _open
    self.establish_connection()
  File "C:\Users\aaa\anaconda3\lib\site-packages\netmiko\base_connection.py", line 890, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: huawei_vrpv8 XX.XX.XX.XX:22
```

◆my code is this
```
---
from netmiko import ConnectHandler
device = {
    'device_type': 'huawei_vrpv8',
    'host': 'XX.XX.XX.XX',
    'username': 'username',
    'password': 'password',
    'ssh_config_file': './ssh_config',
    'verbose' : False,
    'global_delay_factor': 8,
}

net_connect = ConnectHandler(**device)
output1 = net_connect.send_command("display current-configuration")

print(output1)
net_connect.disconnect()
```

◆ssh_config
```
---
host XX.XX.XX.XX:22                  # The intermediate server
  IdentityFile ~/.ssh/id_rsa    # The SSH key to use to the intermediate server
  user otherusername for server
  hostname XX.XX.XX.XX
  Port 22
  ProxyCommand ssh otherusername@server nc %h %p
```

◆comment
---
i want to connect Huawei device via a server used to access other devices like a router.

**Comment by carlmontanari** [comment]
Please format your posts.

Does ssh'ing to the host while using that config file work (meaning the proxy jump works)? I don't know that ive ever done a proxy jump without using keys, so not sure if that works or not.

**Comment by poyantu** [comment]
@carlmontanari 

im sorry
i have formated main

hmm...
sorry i dont understand you
so, do i make ssh'ing run without using keys?

**Comment by ktbyers** [comment]
@poyantu Your SSH config file doesn't look right. I would review this document here:

https://pynet.twb-tech.com/blog/automation/netmiko-proxy.html

I would expect at least two entries--one to reach the "jumpserver" and one for all other devices.

**Comment by ktbyers** [comment]
I am going to close this as it doesn't look like a Netmiko issue?

I would review the above netmiko-proxy document. If you are still having issues, just let us know.
