### ISSUE TITLE
netmiko.ConnectHandler not passing port information when ssh config file loaded

### ISSUE THREAD

**Issue by dcorbe** [ktbyers/netmiko#1479]
Given the following script:

```
import netmiko
import time

if __name__ == "__main__":
    device = {
        "device_type": 'terminal_server',
        "ip": '192.168.128.18',
        "port": 3002,
        "username": 'root',
        "password": 'XXX',
        "ssh_config_file": '/root/.ssh/config'
    }

    ssh = netmiko.ConnectHandler(**device)
    ssh.write_channel("\n")
    time.sleep(1)
    ssh.write_channel("\n")
    time.sleep(1)
    output = ssh.read_channel()
    print(output)

```

And the following SSH config:

```
Host jumphost
     hostname jumpserver.netops.corbe.net
     User = "daniel"
     IdentityFile ~/.ssh/id_rsa

host * !jumphost
    ProxyCommand ssh jumphost nc %h %p

```
I would expect to be connected to 192.168.128.18 on port 3002.   Instead I'm being connected to port 22.   Can someone help me find a workaround?

**Comment by ktbyers** [comment]
It works with ProxyJump of this form:

```
host jumphost
  IdentitiesOnly yes 
  IdentityFile ~/.ssh/test_rsa
  user admin
  hostname jump.domain.com

host * !jumphost
  user pyclass
  ProxyJump jumphost
```

I order to use `ProxyCommand` I had to do something like:

```
host jumphost
  IdentitiesOnly yes 
  IdentityFile ~/.ssh/test_rsa
  User gituser
  HostName jump.domain.com

host rtr1.domain.com
  User pyclass
  Port 3022
  # Force usage of this SSH config file
  ProxyCommand ssh -F ~/.ssh/ssh_config -W %h:%p jumphost
```

**Comment by dcorbe** [comment]
Is there any way to not have to specify the port in the SSH config but rather with netmiko instead?  The main issue is that ALL my devices are connected via serial to one or two inside hosts on multiple ports.

**Comment by ktbyers** [comment]
Did you try the `ProxyJump` format that I posted above? That looked like it worked and would pass the port.

**Comment by dcorbe** [comment]
Now I get this:

Exception: Error reading SSH protocol banner
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/usr/lib/python3.8/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/usr/lib/python3.8/site-packages/paramiko/packet.py", line 622, in _read_timeout
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/paramiko/transport.py", line 2039, in run
    self._check_banner()
  File "/usr/lib/python3.8/site-packages/paramiko/transport.py", line 2215, in _check_banner
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/usr/lib/python3.8/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/usr/lib/python3.8/site-packages/paramiko/packet.py", line 622, in _read_timeout
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/testing/scrape.py", line 40, in <module>
    ssh = netmiko.ConnectHandler(**device)
  File "/usr/lib/python3.8/site-packages/netmiko/ssh_dispatcher.py", line 246, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/netmiko/base_connection.py", line 317, in __init__
    self._open()
  File "/usr/lib/python3.8/site-packages/netmiko/base_connection.py", line 322, in _open
    self.establish_connection()
  File "/usr/lib/python3.8/site-packages/netmiko/base_connection.py", line 884, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/lib/python3.8/site-packages/paramiko/client.py", line 406, in connect
    t.start_client(timeout=timeout)
  File "/usr/lib/python3.8/site-packages/paramiko/transport.py", line 660, in start_client
    raise e
  File "/usr/lib/python3.8/site-packages/paramiko/transport.py", line 2039, in run
    self._check_banner()
  File "/usr/lib/python3.8/site-packages/paramiko/transport.py", line 2215, in _check_banner
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

Process finished with exit code 1

**Comment by dcorbe** [comment]
And I do get an SSH banner when I connect to that port on that host from the jump server:

$ telnet 192.168.128.18 3002
SSH-2.0-OpenSSH_7.7

**Comment by dcorbe** [comment]
Sorry for the noise, but adding IdentitiesOnly yes to my ssh config fixed the issue.   Thank you for your assistance.
