### ISSUE TITLE
Netmiko 3.0 failing on cmd echo verification for F5 LTM

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#1485]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ccaro/nornir/venv/lib64/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 248, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/ccaro/nornir/venv/lib64/python3.6/site-packages/netmiko/base_connection.py", line 312, in __init__
    self._open()
  File "/home/ccaro/nornir/venv/lib64/python3.6/site-packages/netmiko/base_connection.py", line 318, in _open
    self._try_session_preparation()
  File "/home/ccaro/nornir/venv/lib64/python3.6/site-packages/netmiko/base_connection.py", line 741, in _try_session_preparation
    self.session_preparation()
  File "/home/ccaro/nornir/venv/lib64/python3.6/site-packages/netmiko/f5/f5_tmsh_ssh.py", line 13, in session_preparation
    command="modify cli preference pager disabled display-threshold 0"
  File "/home/ccaro/nornir/venv/lib64/python3.6/site-packages/netmiko/base_connection.py", line 1015, in disable_paging
    output = self.read_until_pattern(pattern=re.escape(command.strip()))
  File "/home/ccaro/nornir/venv/lib64/python3.6/site-packages/netmiko/base_connection.py", line 612, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/home/ccaro/nornir/venv/lib64/python3.6/site-packages/netmiko/base_connection.py", line 546, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.
```

**Comment by llogs** [comment]
I have same socket.timeout problem with F5 LTM.

Python 3.7.6
netmiko      3.0.0
paramiko     2.7.1
scp          0.13.2
pyserial     3.4
textfsm      1.1.0

Traceback (most recent call last):
  File "/Users/lay.kim/work/dev/recoder/.venv/lib/python3.7/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/Users/lay.kim/work/dev/recoder/.venv/lib/python3.7/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lay.kim/work/dev/recoder/.venv/lib/python3.7/site-packages/netmiko/base_connection.py", line 541, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/Users/lay.kim/work/dev/recoder/.venv/lib/python3.7/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "getter.py", line 69, in <module>
    net_connect = ConnectHandler(**f5_ltm)
  File "/Users/lay.kim/work/dev/recoder/.venv/lib/python3.7/site-packages/netmiko/ssh_dispatcher.py", line 252, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/Users/lay.kim/work/dev/recoder/.venv/lib/python3.7/site-packages/netmiko/base_connection.py", line 318, in __init__
    self._open()
  File "/Users/lay.kim/work/dev/recoder/.venv/lib/python3.7/site-packages/netmiko/base_connection.py", line 324, in _open
    self._try_session_preparation()
  File "/Users/lay.kim/work/dev/recoder/.venv/lib/python3.7/site-packages/netmiko/base_connection.py", line 747, in _try_session_preparation
    self.session_preparation()
  File "/Users/lay.kim/work/dev/recoder/.venv/lib/python3.7/site-packages/netmiko/f5/f5_tmsh_ssh.py", line 13, in session_preparation
    command="modify cli preference pager disabled display-threshold 0"
  File "/Users/lay.kim/work/dev/recoder/.venv/lib/python3.7/site-packages/netmiko/base_connection.py", line 1022, in disable_paging
    output = self.read_until_pattern(pattern=re.escape(command.strip()))
  File "/Users/lay.kim/work/dev/recoder/.venv/lib/python3.7/site-packages/netmiko/base_connection.py", line 618, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/Users/lay.kim/work/dev/recoder/.venv/lib/python3.7/site-packages/netmiko/base_connection.py", line 552, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

**Comment by MitchellMahan** [comment]
I believe I have the same issue.
It appears that find_prompt() does not like the F5s prompt changes to "Changes Pending":

********@(primary)(cfg-sync In Sync)(Active)(/Common)(tmos)#   some modify/create/etc. command
********@(primary)(cfg-sync Changes Pending)(Active)(/Common)(tmos)# <---

Is there an easy way to adjust the find_prompt() to ignore (cfg-sync .*)? I could not find an easy way to do this myself after digging around and have switched to using send_command_timing but for a massive library it results in some wonky reads.

Best,
Mitch

**Comment by ktbyers** [comment]
@MitchellMahan I missed this earlier, are you still running into an issue here?

Can you show me the Netmiko code that is failing and which exception you receive?

**Comment by ktbyers** [comment]
I am going to close this issue due to it being very old. If someone wants to work on F5 LTM issues, just ping me (or open a new issue). I don't have a device I can easily test on...so I need someone that is willing to work on it.
