### ISSUE TITLE
TypeError: establish_connection() got an unexpected keyword argument 'key_file'

### ISSUE THREAD

**Issue by diLLec** [ktbyers/netmiko#149]
Hi,

when using the fortinet connection class the following error occurs:
`
Traceback (most recent call last):
  File "upload_config.py", line 20, in <module>
    device_type='fortinet', use_keys=False, key_file=None)
  File "/usr/lib/python2.6/site-packages/netmiko-0.2.7-py2.6.egg/netmiko/ssh_dispatcher.py", line 63, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/netmiko-0.2.7-py2.6.egg/netmiko/base_connection.py", line 62, in __init__
    self.establish_connection(verbose=verbose, use_keys=use_keys, key_file=key_file)
TypeError: establish_connection() got an unexpected keyword argument 'key_file'
`
The reason why is that establish_connection in netmiko/fortinet/fortinet_ssh.py does not contain
a key_file parameter. Changing it to

`def establish_connection(self, sleep_time=3, verbose=True, timeout=8, use_keys=False,
                             width=None, height=None, key_file=None):`
works.

**Comment by ktbyers** [comment]
@diLLec Please test the new fix. I think it should work now.
