### ISSUE TITLE
ValueError: Failed to enter configuration mode. error is thrown while configuring remote device using netmiko

### ISSUE THREAD

**Issue by Giri-ctrl** [ktbyers/netmiko#1509]
please find the code below
#! /usr/bin/env python
from netmiko import ConnectHandler
import getpass,sys,time,os
import logging
logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

device = {
'device_type': 'aruba_os',
'ip': '11.1.1.2',
'username': 'admin',
'password': '',
}

print("Script for SSH to device")
configfile_shut = open("configfile.txt")
configset = configfile_shut.read()
configfile_shut.close()
configfile_noshut = open("configfile_noshut.txt")
configset1 = configfile_noshut.read()
configfile_noshut.close()
print("\n\nConnecting Device ")
net_connect = ConnectHandler(**device)
time.sleep(2)
for i in range(1,40):
        print("Passing configuration set, shutting down the lag interface\n")
        net_connect.enable()
        net_connect.send_config_set(configset)
        print("Sleeping for 120 seconds")
        time.sleep(float(120))
        print("Passing configuration set, bringing up the lag interface\n")
        net_connect.send_config_set(configset1)
        print("Completed lag shut down cycle: %d" %i)
print("Complted lag shut and no shut saga")

config_file is output is as shown below:
configure terminal
interface lag 2
shut
end

As suggested in another thread, the problem is solved by adding net_connect.enable  before config operation but its not working with this node.

Please do the needful

**Comment by Giri-ctrl** [comment]
please find the log below
DEBUG:paramiko.transport:starting thread (client mode): 0x6ea4f610L
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.6.0
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-OpenSSH_7.8 PKIX[Portable FIPS]
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_7.8)
DEBUG:paramiko.transport:kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-256', u'rsa-sha2-512', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com'] client mac:[u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: curve25519-sha256@libssh.org
DEBUG:paramiko.transport:HostKey agreed: ssh-ed25519
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-ed25519 host key for 11.1.1.2: ce9b85c8d4947a1289278105dea3d99e
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Auth banner:
 (C) Copyright 2017-2019 Hewlett Packard Enterprise Development LP

                      RESTRICTED RIGHTS LEGEND
 Confidential computer software. Valid license from Hewlett Packard Enterprise
 Development LP required for possession, use or copying. Consistent with FAR
 12.211 and 12.212, Commercial Computer Software, Computer Software
 Documentation, and Technical Data for Commercial Items are licensed to the
 U.S. Government under vendor's standard commercial license.

We'd like to keep you up to date about:
  * Software feature updates
  * New product announcements
  * Special events
Please register your products now at: https://asp.arubanetworks.com



INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:Received global request "hostkeys-00@openssh.com"
DEBUG:paramiko.transport:Rejecting "hostkeys-00@openssh.com" global request from server.
DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:read_channel:

DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel: Last login: 2020-01-10 13:14:54 from 11.1.1.1
User "admin" has logged in 44 times in the past 30 days
6300#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel:
DEBUG:netmiko:read_channel:
6300#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel:
DEBUG:netmiko:Pattern is: 6300
DEBUG:netmiko:_read_channel_expect read_data:
6300#
DEBUG:netmiko:Pattern found: 6300
6300#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:In disable_paging
DEBUG:netmiko:Command: no paging
DEBUG:netmiko:write_channel: no paging
DEBUG:netmiko:Pattern is: 6300
DEBUG:netmiko:_read_channel_expect read_data: no
DEBUG:netmiko:_read_channel_expect read_data: paging
Invalid input: paging
6300#
DEBUG:netmiko:Pattern found: 6300 no paging
Invalid input: paging
6300#
DEBUG:netmiko:no paging
Invalid input: paging
6300#
DEBUG:netmiko:Exiting disable_paging
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel:
DEBUG:netmiko:Pattern is: 6300
DEBUG:netmiko:_read_channel_expect read_data:
6300#
DEBUG:netmiko:Pattern found: 6300
6300#
DEBUG:netmiko:write_channel:
DEBUG:netmiko:Pattern is: 6300
DEBUG:netmiko:_read_channel_expect read_data:
6300#
DEBUG:netmiko:Pattern found: 6300
6300#
DEBUG:netmiko:write_channel: config term
DEBUG:netmiko:Pattern is: 6300
DEBUG:netmiko:_read_channel_expect read_data: confi
DEBUG:netmiko:_read_channel_expect read_data: g term
6300(config)#
DEBUG:netmiko:Pattern found: 6300 config term
6300(config)#
DEBUG:netmiko:write_channel:
DEBUG:netmiko:Pattern is: 6300
DEBUG:netmiko:_read_channel_expect read_data:
6300(config)#
DEBUG:netmiko:Pattern found: 6300
6300(config)#
DEBUG:paramiko.transport:EOF in transport thread

**Comment by daanvdsanden** [comment]
The `send_config_set()` method open the config mode. You're file with instructions `config_file` also tries to enter config mode (which you are already in). If you remove the line `configure terminal` from the file `config_file` it should work.

**Comment by carlmontanari** [comment]
Going to close this. In the future please format your posts so they are easier to read.

Feel free to join us in the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTIyZDdhMTBlOWNmNDJhNjkxZTEyMDg3NTRkOWIxMTUwOTAzYmQ0ZjMwMGMyNTM4N2E1YzA3YWQ1MWFiOWM1YzU) where you can find a dedicated netmiko channel for general questions/comments/etc -- generally a better place for questions (GitHub is generally better for bugs/feature work).

**Comment by Giri-ctrl** [comment]
I'm still getting the same error even after removing configure terminal command from configfile.txt.

Running the script:
root@hpniuser-virtual-machine:~/script# ./lag_shut.py
Script for SSH to device


Connecting Device
Passing configuration set, shutting down the lag interface

Traceback (most recent call last):
  File "./lag_shut.py", line 28, in <module>
    net_connect.send_config_set(configset)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 1607, in send_config_set
    output = self.config_mode(*cfg_mode_args)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/cisco_base_connection.py", line 50, in config_mode
    config_command=config_command, pattern=pattern
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 1518, in config_mode
    raise ValueError("Failed to enter configuration mode.")
ValueError: Failed to enter configuration mode. >>>>>>>>>>>>>.same error has been returned
root@hpniuser-virtual-machine:~/script# cat configfile.txt
interface lag 2
shut
end

root@hpniuser-virtual-machine:~/script# cat configfile.txt >>>>>>>>>>>file contents
interface lag 2
shut
end

root@hpniuser-virtual-machine:~/script#
PLease do the needful

**Comment by ktbyers** [comment]
You should get rid of the `end` in your configuration file. Netmiko automatically enters/exits config mode.

Can you re-post your Python script?

**Comment by ktbyers** [comment]
Please format the markdown correctly (for your Python script).

**Comment by Giri-ctrl** [comment]
#!/usr/bin/env python

from  netmiko import ConnectHandler
from getpass import getpass
from datetime import datetime
import time
import sys
import logging
logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

aruba6300 = {
        "device_type": "aruba_os",
        "ip": "200.1.1.1",
        "username": "admin",
        "password": "",
}


n = len(sys.argv)
print("Total arguments passed:", n)

iteration = sys.argv[1]
value = 1

start_time = datetime.now()
net_connect = ConnectHandler(**aruba6300)
print(net_connect.find_prompt())
shut = "lag_shut.txt"
noshut = "lag_noshut.txt"
while value < int(iteration):
        print("Perfoming uplink LAG interface shut %d" % value)
        print(net_connect.find_prompt())
        output = net_connect.send_config_from_file(shut)
        print("\nWaiting for 30min\n")
        time.sleep(1800)
        print("Performing uplink LAG interface no shut %d" % value)
        output1 = net_connect.send_config_from_file(noshut)
        value  += 1

net_connect.disconnect()



Error:
===
root@hpniuser-virtual-machine:~/python# python3.5 lag.py 30
/usr/local/lib/python3.5/dist-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
  from cryptography.hazmat.backends import default_backend
Total arguments passed: 2
MASTER#
Perfoming uplink LAG interface shut 1
MASTER#
Traceback (most recent call last):
  File "lag.py", line 36, in <module>
    output = net_connect.send_config_from_file(shut)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 1555, in send_config_from_file
    return self.send_config_set(cfg_file, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 1607, in send_config_set
    output = self.config_mode(*cfg_mode_args)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/cisco_base_connection.py", line 50, in config_mode
    config_command=config_command, pattern=pattern
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 1518, in config_mode
    raise ValueError("Failed to enter configuration mode.")
ValueError: Failed to enter configuration mode.
root@hpniuser-virtual-machine:~/python#

**Comment by Giri-ctrl** [comment]
Can u please point me what is wrong in the code?

**Comment by Giri-ctrl** [comment]
I was able to find the solution for the problem. The fix is to change the match pattern for funtion ""check_config_mode" /usr/local/lib/python3.5/dist-packages/netmiko/aruba/aruba_ssh.py" from "check_string="(config) #" to check_string="(config)#".
There should not be any space between config and #.

**Comment by ktbyers** [comment]
This likely implies some Aruba devices have a space and some don't.

Flagging this as a bug that can possibly be fixed via a regex.
