### ISSUE TITLE
enable secret password TypeError with fernet symmetric encryption

### ISSUE THREAD

**Issue by adraf82** [ktbyers/netmiko#1511]
Hi,

I am receiving the error below when my python program tries to convert my encrypted password string for the enable secret password into a byte string. When I add the secret password as a plain text password in the JSON file, the program works just fine. Also, the same encrypted password string gets converted to a byte string without any problems for the password key.

Please could you take a look and advise what the problem is?

I am pulling the key value information for the Dell n2024 switch from a JSON file. Please see the attachment below.
[delljson.txt](https://github.com/ktbyers/netmiko/files/4050037/delljson.txt)

``from netmiko import ConnectHandler
import subprocess
import json
from cryptography.fernet import Fernet

file = open('key2.txt', 'rb')
key = file.read()
file.close()

frn = Fernet(key)

with open('delltest.json', 'rb') as f:
    dell_test = json.load(f)

for device in dell_test:
    b=bytes(device["password"], 'utf8')
    (device["password"]) = (frn.decrypt(b))
    s=bytes(device["secret"], 'utf8')
    (device["secret"]) = (frn.decrypt(s))
    net_connect = ConnectHandler(**device)
    net_connect.enable()
    configcmds = 'show running-config'
    output = net_connect.send_command(configcmds)
    print(output)

The error produced when I run this program is here;

Traceback (most recent call last):
  File "dtest.py", line 26, in <module>
    net_connect = ConnectHandler(**device)
  File "/home/brb/.local/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 246, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/brb/.local/lib/python3.6/site-packages/netmiko/base_connection.py", line 317, in __init__
    self._open()
  File "/home/brb/.local/lib/python3.6/site-packages/netmiko/base_connection.py", line 323, in _open
    self._try_session_preparation()
  File "/home/brb/.local/lib/python3.6/site-packages/netmiko/base_connection.py", line 738, in _try_session_preparation
    self.session_preparation()
  File "/home/brb/.local/lib/python3.6/site-packages/netmiko/dell/dell_dnos6.py", line 13, in session_preparation

    self.enable()
  File "/home/brb/.local/lib/python3.6/site-packages/netmiko/cisco_base_connection.py", line 22, in enable
    cmd=cmd, pattern=pattern, re_flags=re_flags
  File "/home/brb/.local/lib/python3.6/site-packages/netmiko/base_connection.py", line 1465, in enable
    self.write_channel(self.normalize_cmd(self.secret))
  File "/home/brb/.local/lib/python3.6/site-packages/netmiko/base_connection.py", line 1429, in normalize_cmd
    command += self.RETURN
TypeError: can't concat str to bytes

Thanks

**Comment by ktbyers** [comment]
This:

```python
device["secret"] = frn.decrypt(s)
```

would need to be a unicode string at this point.

So probably just need to do:

```
my_secret = frn.decrypt(s)
my_secret = my_secret.decode()
device["secret"] = my_secret
```

**Comment by adraf82** [comment]
That worked! Many thanks for your help. Much appreciated. 

Adeel

**Comment by carlmontanari** [comment]
Looks sorted, closing!
