### ISSUE TITLE
OSError: Search pattern never detected in send_command_expect

### ISSUE THREAD

**Issue by lutfisan** [ktbyers/netmiko#1513]
```
Traceback (most recent call last):
  File "/home/cacti/miniconda3/envs/ipam/lib/python3.7/site-packages/nornir/core/task.py", line 85, in start
    r = self.task(self, **self.params)
  File "/home/cacti/miniconda3/envs/ipam/lib/python3.7/site-packages/nornir/plugins/tasks/networking/netmiko_send_command.py", line 32, in netmiko_send_command
    result = net_connect.send_command(command_string, **kwargs)
  File "/home/cacti/miniconda3/envs/ipam/lib/python3.7/site-packages/netmiko/base_connection.py", line 1337, in send_command
    search_pattern
OSError: Search pattern never detected in send_command_expect: set\ cli\ screen\-width\ 511
```

how to solve this error?

**Comment by carlmontanari** [comment]
Need more information, but I'd wager wrong device type as it looks like netmiko is trying to disable paging and never getting the expected prompt back. Going to close this but feel free to reopen with your script (and session log would be nice) if you feel this is a bug/issue.

**Comment by lutfisan** [comment]
I think it because I choose device_type='juniper'. It no error after I change to device_type='juniper_junos'
can you explain the difference between juniper and juniper_junos?

and I have another error with Huawei router.
This is my code:
```
from netmiko import ConnectHandler

router = ConnectHandler(device_type='huawei', host='10.10.10.10', username='user', password='pass')
ipTable = router.send_command("display current-configuration")
print(ipTable)
```
This the error:
```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-13-ddb69ffc8782> in <module>
----> 1 ipTable = router.send_command("display current-configuration")
      2 print(ipTable)

~/miniconda3/envs/ipam/lib/python3.7/site-packages/netmiko/base_connection.py in send_command(self, command_string, expect_string, delay_factor, max_loops, auto_find_prompt, strip_prompt, strip_command, normalize, use_textfsm, use_genie)
   1335             raise IOError(
   1336                 "Search pattern never detected in send_command_expect: {}".format(
-> 1337                     search_pattern
   1338                 )
   1339             )

OSError: Search pattern never detected in send_command_expect: <MA\-YGSMN0325\-01H>
```

**Comment by ktbyers** [comment]
@lutfisan Your output indicates the router prompt never came back (or didn't come back in the allocated time).

How long does this `display current-configuration` take to complete (roughly)?

Can you post what the end of that command looks like (if you execute that command in the CLI)?

**Comment by lutfisan** [comment]
> @lutfisan Your output indicates the router prompt never came back (or didn't come back in the allocated time).
> 
> How long does this `display current-configuration` take to complete (roughly)?
> 
> Can you post what the end of that command looks like (if you execute that command in the CLI)?


This result from CLI
```
[server@mpls ~]$ ssh user@10.10.10.10
User Authentication
Enter password:

Info: The max number of VTY users is 21, the number of current VTY users online is 1, and total number of terminal users online is 1.
      The current login time is 2020-01-14 07:54:51+07:00.
      The last login time is 2020-01-14 07:54:14+07:00 from 10.17.6.80 through SSH.
<MA-XXXX-01H>display current-configuration
!Software Version V300R003C00SPC200
!Last configuration was updated at 2020-01-03 13:33:00+07:00 by admin_local
!Last configuration was saved at 2020-01-14 00:14:12+07:00 by admin_local
#
load-balance hash-arithmetic arithmetic2
#
loop-detect trigger enable
#
 
#
clock timezone WIB add 07:00:00
#
sysname MA-XXXX-01H
#
set neid abb4be
#
command-privilege level rearrange
#
FTP server enable
#
info-center loghost source LoopBack0
info-center loghost 10.x.x.x level informational
info-center loghost 10.x.x.x level informational
  ---- More ----
```

I think `display current-configuration` take 1 until 3 seconds
