### ISSUE TITLE
ValueError: Failed to enter configuration mode

### ISSUE THREAD

**Issue by alexkoganov** [ktbyers/netmiko#1515]
hi all

this is my code :

```python
def checkparallel(ip):
    HP = {
        'device_type': 'hp_procurve',
        'host':   ip,
        'username': 'alexkog',
        'password': '9137AnnA4$',
        #'blocking_timeout': 12,
    }
    try:
        net_connect = ConnectHandler(**HP)

    except NetMikoTimeoutException:
        print(f'{Fore.RED}{ip}{Style.RESET_ALL} is not reachable')
        sys.exit()
        #continue
    except NetMikoAuthenticationException:
        print(f'{Fore.BLUE}{ip}{Style.RESET_ALL} cant authenticate')
        sys.exit()
        #continue
    config_commands = ['conf t','vlan 94','tagged 47-48','exit','vlan 95','tagged 47-48','exit','vlan 96','tagged 47-48','exit','vlan 97','tagged 47-48','exit','wr me']
    net_connect.send_config_set(config_commands,delay_factor=4,exit_config_mode=False)
    print(f'{Fore.GREEN}{ip}{Style.RESET_ALL}' ,"is done")

for n in list_of_ips:
    ip = n
    t = Thread(target=checkparallel, args= (ip,))
    t.start()
    threads.append(t)

for t in threads:
    t.join()
```

everything works as expected till i am trying ssh to switch that is a different vendor and i am getting :

Traceback (most recent call last):
  File "C:\Users\alexkog\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\alexkog\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File ".\ssh_no_threding.py", line 71, in checkparallel
    net_connect.send_config_set(config_commands,delay_factor=4)
  File "C:\Users\alexkog\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\base_connection.py", line 1607, in send_config_set
    output = self.config_mode(*cfg_mode_args)
  File "C:\Users\alexkog\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\cisco_base_connection.py", line 50, in config_mode
    config_command=config_command, pattern=pattern
  File "C:\Users\alexkog\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\base_connection.py", line 1518, in config_mode
    raise ValueError("Failed to enter configuration mode.")
ValueError: Failed to enter configuration mode.

is there any exception for this value error ?

tnx

**Comment by ktbyers** [comment]
Meaning you are trying to use `hp_procurve` device_type with something that is not an HP ProCurve.

The exception type is `ValueError`, but it is probably better to fix the device_type so the error doesn't occur (assuming I understood the issue correctly).

**Comment by alexkoganov** [comment]
even if Valueerror exist as exception its still erroring :

threads = []

def checkparallel(ip):
    HP = {
        'device_type': 'hp_procurve',
        'host':   ip,
        'username': 'alexkog',
        'password': '9137AnnA4$',
        #'blocking_timeout': 12,
    }
    try:
        net_connect = ConnectHandler(**HP)

    except NetMikoTimeoutException:
        print(f'{Fore.RED}{ip}{Style.RESET_ALL} is not reachable')
        sys.exit()
        #continue
    except NetMikoAuthenticationException:
        print(f'{Fore.BLUE}{ip}{Style.RESET_ALL} cant authenticate')
        sys.exit()
        #continue
    **except ValueError:
        print(f'{Fore.BLUE}{ip}{Style.RESET_ALL} this is not an HP switch')
        sys.exit()**

    config_commands = ['conf t','vlan 94','tagged 47-48','exit','vlan 95','tagged 47-48','exit','vlan 96','tagged 47-48','exit','vlan 97','tagged 47-48','exit','wr me']
    net_connect.send_config_set(config_commands,delay_factor=4,exit_config_mode=False)
    print(f'{Fore.GREEN}{ip}{Style.RESET_ALL}' ,"is done")

for n in list_of_ips:
    ip = n
    t = Thread(target=checkparallel, args= (ip,))
    t.start()
    threads.append(t)

for t in threads:
    t.join()



**the output:**


Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\alexkog\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\alexkog\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File ".\ssh_no_threding.py", line 74, in checkparallel
    net_connect.send_config_set(config_commands,delay_factor=4,exit_config_mode=False)
  File "C:\Users\alexkog\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\base_connection.py", line 1607, in send_config_set
    output = self.config_mode(*cfg_mode_args)
  File "C:\Users\alexkog\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\cisco_base_connection.py", line 50, in config_mode
    config_command=config_command, pattern=pattern
  File "C:\Users\alexkog\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\base_connection.py", line 1518, in config_mode
    raise ValueError("Failed to enter configuration mode.")
**ValueError: Failed to enter configuration mode.**


whats i am doing wrong ?

> but it is probably better to fix the device_type so the error doesn't occur (assuming I understood the issue correctly).

i am usually scanning back bone devices with snmp to get all hosts connected to it so i cant really know whats hp and whats not so i am preferring to work with exceptions.


tnx

**Comment by ktbyers** [comment]
Closing as this issue is not being actively worked on.
