### ISSUE TITLE
Huawei repaints line twice for long lines breaking command echo verification in Netmiko 3.0

### ISSUE THREAD

**Issue by thatguyjoshua** [ktbyers/netmiko#1530]
Netmiko is hanging despite the data it's expecting being present. Debug and Traceback below. The device type is huawei

```
<Huawei>
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel:
<Huawei>
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'system-view\n'
DEBUG:netmiko:Pattern is: system\-view
DEBUG:netmiko:_read_channel_expect read_data: system-view
Enter system view, return user view with Ctrl+Z.
[Huawei]
DEBUG:netmiko:Pattern found: system\-view system-view
Enter system view, return user view with Ctrl+Z.
[Huawei]
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel:
[Huawei]
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'ip route-static 0.0.0.0 0.0.0.0 10.161.206.148 permanent\n'
DEBUG:netmiko:Pattern is: ip\ route\-static\ 0\.0\.0\.0\ 0\.0\.0\.0\ 10\.161\.206\.148\ permanent
DEBUG:netmiko:_read_channel_expect read_data: ip route-static 0.0.0.0 0.0.0.0 10.161.206.148 permanent
DEBUG:netmiko:Pattern found: ip\ route\-static\ 0\.0\.0\.0\ 0\.0\.0\.0\ 10\.161\.206\.148\ permanent ip route-static 0.0.0.0 0.0.0.0 10.161.206.148 permanent
DEBUG:netmiko:Pattern is: (?:Huawei|#)
DEBUG:netmiko:_read_channel_expect read_data:
[Huawei]
DEBUG:netmiko:Pattern found: (?:Huawei|#)
[Huawei]
DEBUG:netmiko:write_channel: b'interface Vlanif1\n'
DEBUG:netmiko:Pattern is: interface\ Vlanif1
DEBUG:netmiko:_read_channel_expect read_data: interface Vlanif
Jan 23 2020 06:09:58+00:00 Huawei %%01RM/4/IPV4_DEFT_RT_CHG(l)[0]:IPV4 default Rou
DEBUG:netmiko:_read_channel_expect read_data: te is changed. (ChangeType=Add, InstanceId=0, Protocol=Static, ExitIf=NULL0, Nexthop=0.0.0.0, Neighb
DEBUG:netmiko:_read_channel_expect read_data: our=0.0.0.0, Preference=60, Label=NULL, Metric=0)
[Huawei]interface Vlanif1
[Huawei-Vlanif1]
DEBUG:netmiko:Pattern found: interface\ Vlanif1 interface Vlanif
Jan 23 2020 06:09:58+00:00 Huawei %%01RM/4/IPV4_DEFT_RT_CHG(l)[0]:IPV4 default Route is changed. (ChangeType=Add, InstanceId=0, Protocol=Static, ExitIf=NULL0, Nexthop=0.0.0.0, Neighbour=0.0.0.0, Preference=60, Label=NULL, Metric=0)
[Huawei]interface Vlanif1
[Huawei-Vlanif1]
DEBUG:netmiko:write_channel: b'ip address 10.161.206.149 255.255.255.111\n'
DEBUG:netmiko:Pattern is: ip\ address\ 10\.161\.206\.149\ 255\.255\.255\.111
DEBUG:netmiko:_read_channel_expect read_data: ip address 10.161.206.149 255.255.255.111
DEBUG:netmiko:Pattern found: ip\ address\ 10\.161\.206\.149\ 255\.255\.255\.111 ip address 10.161.206.149 255.255.255.111
DEBUG:netmiko:Pattern is: (?:Huawei|#)
DEBUG:netmiko:_read_channel_expect read_data:
Info: IP pool on this interface has been deleted.
DEBUG:netmiko:_read_channel_expect read_data:
Warning: Please be cautious when using the IP address with 31-bit mask on non-P2P interfaces.
[Hu
DEBUG:netmiko:_read_channel_expect read_data: awei-Vlanif1]

Assert at File: adp_ipv4_arp_io.c, Line: 2268. CallStack:
 <-- 0x2fa78d8(0x2fa78d8
DEBUG:netmiko:Pattern found: (?:Huawei|#)
Info: IP pool on this interface has been deleted.
Warning: Please be cautious when using the IP address with 31-bit mask on non-P2P interfaces.
[Huawei-Vlanif1]

Assert at File: adp_ipv4_arp_io.c, Line: 2268. CallStack:
 <-- 0x2fa78d8(0x2fa78d8
DEBUG:netmiko:write_channel: b'interface range GigabitEthernet0/0/0 to GigabitEthernet0/0/3\n'
DEBUG:netmiko:Pattern is: interface\ range\ GigabitEthernet0/0/0\ to\ GigabitEthernet0/0/3
DEBUG:netmiko:_read_channel_expect read_data: ) <-- 0x5dcde18(0x5dcde18)
 <-- 0x5d1b9c4(0x5d1b9c4) <-- 0x5d1bb3c(0x5d1bb3c)
 <-- 0x5d1be68(0x5d1
DEBUG:netmiko:_read_channel_expect read_data: be68) <-- 0x5d2b660(0x5d2b660)
 <-- 0x301eab4(0x301eab4) <-- 0x2fa4604(0x2fa4604)
 <-- 0xb465fdbc(
DEBUG:netmiko:_read_channel_expect read_data: 0xb465fdbc) <-- 0xb4643080(0xb4643080)
 <-- 0xa6d1b644(0xa6d1b644) <-- 0xb30ac320(0xb30ac320)
<Tas
DEBUG:netmiko:_read_channel_expect read_data: kID: 88> [2020.01.23 06:09:58.975]


Assert at File: adp_ipv4_fib_mb.c, Line: 3349. CallStack:

DEBUG:netmiko:_read_channel_expect read_data: <-- 0x2fa78d8(0x2fa78d8) <-- 0x5d1ba00(0x5d1ba00)
 <-- 0x5d1bb3c(0x5d1bb3c) <-- 0x5d1be68(0x5d1be68
DEBUG:netmiko:_read_channel_expect read_data: )
 <-- 0x5d2b660(0x5d2b660) <-- 0x301eab4(0x301eab4)
 <-- 0x2fa4604(0x2fa4604) <-- 0xb465fdbc(0xb4
DEBUG:netmiko:_read_channel_expect read_data: 65fdbc)
 <-- 0xb4643080(0xb4643080) <-- 0xa6d1b644(0xa6d1b644)
 <-- 0xb30ac320(0xb30ac320)
<TaskI
DEBUG:netmiko:_read_channel_expect read_data: D: 88> [2020.01.23 06:09:58.975]


Assert at File: adp_ipv4_fib_mb.c, Line: 3406. CallStack:
 <-
DEBUG:netmiko:_read_channel_expect read_data: - 0x2fa78d8(0x2fa78d8) <-- 0x5d1bb58(0x5d1bb58)
 <-- 0x5d1be68(0x5d1be68) <-- 0x5d2b660(0x5d2b660)
DEBUG:netmiko:_read_channel_expect read_data:
 <-- 0x301eab4(0x301eab4) <-- 0x2fa4604(0x2fa4604)
 <-- 0xb465fdbc(0xb465fdbc) <-- 0xb4643080(0xb4
DEBUG:netmiko:_read_channel_expect read_data: 643080)
 <-- 0xa6d1b644(0xa6d1b644) <-- 0xb30ac320(0xb30ac320)
<TaskID: 88> [2020.01.23 06:09:58.9
DEBUG:netmiko:_read_channel_expect read_data: 75]

Jan 23 2020 06:09:58+00:00 Huawei %%01RM/4/ROUTERID_CHANGE(l)[1]:The router ID is 0.0.0.0. (I
DEBUG:netmiko:_read_channel_expect read_data: nstanceID=0)
[Huawei-Vlanif1]interface range GigabitEthernet0
Jan 23 2020 06:09:58+00:00 Huawei %
DEBUG:netmiko:_read_channel_expect read_data: %01RM/4/ROUTERID_CHANGE(l)[2]:The router ID is 10.161.206.149. (InstanceID=0)
[Huawei-Vlanif1]inte
DEBUG:netmiko:_read_channel_expect read_data: rface range GigabitEthernet0/0/0 to GigabitEthernet0/0/3
[Huawei-port-group]
DEBUG:netmiko:Pattern found: interface\ range\ GigabitEthernet0/0/0\ to\ GigabitEthernet0/0/3 ) <-- 0x5dcde18(0x5dcde18)
 <-- 0x5d1b9c4(0x5d1b9c4) <-- 0x5d1bb3c(0x5d1bb3c)
 <-- 0x5d1be68(0x5d1be68) <-- 0x5d2b660(0x5d2b660)
 <-- 0x301eab4(0x301eab4) <-- 0x2fa4604(0x2fa4604)
 <-- 0xb465fdbc(0xb465fdbc) <-- 0xb4643080(0xb4643080)
 <-- 0xa6d1b644(0xa6d1b644) <-- 0xb30ac320(0xb30ac320)
<TaskID: 88> [2020.01.23 06:09:58.975]


Assert at File: adp_ipv4_fib_mb.c, Line: 3349. CallStack:
 <-- 0x2fa78d8(0x2fa78d8) <-- 0x5d1ba00(0x5d1ba00)
 <-- 0x5d1bb3c(0x5d1bb3c) <-- 0x5d1be68(0x5d1be68)
 <-- 0x5d2b660(0x5d2b660) <-- 0x301eab4(0x301eab4)
 <-- 0x2fa4604(0x2fa4604) <-- 0xb465fdbc(0xb465fdbc)
 <-- 0xb4643080(0xb4643080) <-- 0xa6d1b644(0xa6d1b644)
 <-- 0xb30ac320(0xb30ac320)
<TaskID: 88> [2020.01.23 06:09:58.975]


Assert at File: adp_ipv4_fib_mb.c, Line: 3406. CallStack:
 <-- 0x2fa78d8(0x2fa78d8) <-- 0x5d1bb58(0x5d1bb58)
 <-- 0x5d1be68(0x5d1be68) <-- 0x5d2b660(0x5d2b660)
 <-- 0x301eab4(0x301eab4) <-- 0x2fa4604(0x2fa4604)
 <-- 0xb465fdbc(0xb465fdbc) <-- 0xb4643080(0xb4643080)
 <-- 0xa6d1b644(0xa6d1b644) <-- 0xb30ac320(0xb30ac320)
<TaskID: 88> [2020.01.23 06:09:58.975]

Jan 23 2020 06:09:58+00:00 Huawei %%01RM/4/ROUTERID_CHANGE(l)[1]:The router ID is 0.0.0.0. (InstanceID=0)
[Huawei-Vlanif1]interface range GigabitEthernet0
Jan 23 2020 06:09:58+00:00 Huawei %%01RM/4/ROUTERID_CHANGE(l)[2]:The router ID is 10.161.206.149. (InstanceID=0)
[Huawei-Vlanif1]interface range GigabitEthernet0/0/0 to GigabitEthernet0/0/3
[Huawei-port-group]
DEBUG:netmiko:write_channel: b'port link-type access\n'
DEBUG:netmiko:Pattern is: port\ link\-type\ access
DEBUG:netmiko:_read_channel_expect read_data: port link-type access
[Huawei-GigabitEthernet0/0/0]port link-type access
DEBUG:netmiko:Pattern found: port\ link\-type\ access port link-type access
[Huawei-GigabitEthernet0/0/0]port link-type access
DEBUG:netmiko:write_channel: b'port default vlan 1\n'
DEBUG:netmiko:Pattern is: port\ default\ vlan\ 1
DEBUG:netmiko:_read_channel_expect read_data:
[Huawei-GigabitEthernet0/0/1]port link-type access
[Huawei-GigabitEthernet0/0/2]port link-type ac
DEBUG:netmiko:_read_channel_expect read_data: cess
[Huawei-GigabitEthernet0/0/3]port link-type access
[Huawei-port-group]port default vlan 1
[H
DEBUG:netmiko:Pattern found: port\ default\ vlan\ 1
[Huawei-GigabitEthernet0/0/1]port link-type access
[Huawei-GigabitEthernet0/0/2]port link-type access
[Huawei-GigabitEthernet0/0/3]port link-type access
[Huawei-port-group]port default vlan 1
[H
DEBUG:netmiko:write_channel: b'quit\n'
DEBUG:netmiko:Pattern is: quit
DEBUG:netmiko:_read_channel_expect read_data: uawei-GigabitEthernet0/0/0]port default vlan 1
[Huawei-GigabitEthernet0/0/1]port default vlan 1
[H
DEBUG:netmiko:_read_channel_expect read_data: uawei-GigabitEthernet0/0/2]port default vlan 1
[Huawei-GigabitEthernet0/0/3]port default vlan 1
[H
DEBUG:netmiko:_read_channel_expect read_data: uawei-port-group]quit
[Huawei]
[Huawei]
DEBUG:netmiko:Pattern found: quit uawei-GigabitEthernet0/0/0]port default vlan 1
[Huawei-GigabitEthernet0/0/1]port default vlan 1
[Huawei-GigabitEthernet0/0/2]port default vlan 1
[Huawei-GigabitEthernet0/0/3]port default vlan 1
[Huawei-port-group]quit
[Huawei]
[Huawei]
DEBUG:netmiko:write_channel: b'hwtacacs-server template company\n'
DEBUG:netmiko:Pattern is: hwtacacs\-server\ template\ company
DEBUG:netmiko:_read_channel_expect read_data: hwtacacs-server template company
DEBUG:netmiko:Pattern found: hwtacacs\-server\ template\ company hwtacacs-server template company
DEBUG:netmiko:Pattern is: (?:Huawei|#)
DEBUG:netmiko:_read_channel_expect read_data:
Info: Create a new HWTACACS-server template.
[Huawei-hwtacacs-company]
DEBUG:netmiko:Pattern found: (?:Huawei|#)
Info: Create a new HWTACACS-server template.
[Huawei-hwtacacs-company]
DEBUG:netmiko:write_channel: b'hwtacacs-server authentication 10.111.111.112\n'
DEBUG:netmiko:Pattern is: hwtacacs\-server\ authentication\ 10\.111\.111\.112
DEBUG:netmiko:_read_channel_expect read_data: hwtacacs-server authentication 10.111.111.112
DEBUG:netmiko:Pattern found: hwtacacs\-server\ authentication\ 10\.111\.111\.112 hwtacacs-server authentication 10.111.111.112
DEBUG:netmiko:Pattern is: (?:Huawei|#)
DEBUG:netmiko:_read_channel_expect read_data:
[Huawei-hwtacacs-company]
DEBUG:netmiko:Pattern found: (?:Huawei|#)
[Huawei-hwtacacs-company]
DEBUG:netmiko:write_channel: b'hwtacacs-server authentication 10.111.128.112 secondary\n'
DEBUG:netmiko:Pattern is: hwtacacs\-server\ authentication\ 10\.111\.128\.112\ secondary
DEBUG:netmiko:_read_channel_expect read_data: hwtacacs-server authentication 10.111.128.112 secondary
[Huawei-hwtacacs-company]
`


`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.8/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 541, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.8/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "router_build_loop.py", line 124, in <module>
    main(terminal_server_ip, terminal_server_line, db_output)
  File "/root/building_devices/enable_mgmnt.py", line 476, in main
    huawei_enable_mgmnt(net_connect, db_output)
  File "/root/building_devices/enable_mgmnt.py", line 111, in huawei_enable_mgmnt
    net_connect.send_config_set(config_commands=command_list)
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 1726, in send_config_set
    new_output = self.read_until_pattern(pattern=re.escape(cmd.strip()))
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 618, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 551, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.
```

**Comment by ktbyers** [comment]
Can you post your Python code and the configuration commands that you are making?

@thatguyjoshua

**Comment by thatguyjoshua** [comment]
@ktbyers below

```
    if model == "AR169":
        print("Adding Huawei AR169 management configuration.")
        commands = f"""ip route-static 0.0.0.0 0.0.0.0 {default_gateway} permanent
interface Vlanif1
ip address {ip_address} {subnet_mask}
interface range GigabitEthernet0/0/0 to GigabitEthernet0/0/3
port link-type access
port default vlan 1
quit
hwtacacs-server template company
hwtacacs-server authentication 10.111.251.112
hwtacacs-server authentication 10.111.128.112 secondary
hwtacacs-server authorization 10.111.251.112
hwtacacs-server authorization 10.111.128.112 secondary
hwtacacs-server accounting 10.111.251.112
hwtacacs-server accounting 10.111.128.112 secondary
hwtacacs-server source-ip {ip_address}
hwtacacs-server shared-key cipher 
quit
aaa
authentication-scheme default
authentication-mode hwtacacs local
authentication-scheme radius
authentication-mode radius
authentication-scheme company
authentication-mode hwtacacs local
authentication-super hwtacacs
authorization-scheme default
authorization-scheme company
authorization-mode hwtacacs local
accounting-scheme default
accounting-scheme company
accounting-mode hwtacacs
accounting start-fail online
domain default
authentication-scheme default
domain default_admin
authentication-scheme company
accounting-scheme company
authorization-scheme company
hwtacacs-server company
quit
user-interface vty 0 4
idle-timeout 60
authentication-mode aaa
user privilege level 15
protocol inbound all
stelnet server enable
quit"""
    command_list = commands.strip().splitlines()
    print(f"Management configuration:\n")
    for line in command_list:
        print(line)
    net_connect.send_config_set(config_commands=command_list)
```

**Comment by ktbyers** [comment]
So the above is a bit weird (the most likely cause that I can see is there is some other hidden character present)...so can you print out a `repr()` of the following:

```
repr("hwtacacs-server authentication 10.111.128.112 secondary")
```

By that I mean the actual configuration command that you are sending corresponding to the above.

Or better yet would be to log a repr() of the following two items:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/base_connection.py#L547
https://github.com/ktbyers/netmiko/blob/develop/netmiko/base_connection.py#L1715

So add a line 1716 with the following:

log.debug(repr(self.normalize_cmd(cmd)))

And add a line at 548 with the following:

log.debug(f"_read_channel_expect read_data: {repr(new_data)}")

**Comment by thatguyjoshua** [comment]
Below is the logging with the two additions into BaseConnection

```
DEBUG:netmiko:write_channel: b'hwtacacs-server authentication 10.254.128.112 secondary\n'
DEBUG:netmiko:Pattern is: hwtacacs\-server\ authentication\ 10\.254\.128\.112\ secondary
DEBUG:netmiko:_read_channel_expect read_data: hwtacacs-server authentication 10.254.128.112 secon
DEBUG:netmiko:_read_channel_expect read_data: 'hwtacacs-server authentication 10.254.128.112 secon'
DEBUG:netmiko:_read_channel_expect read_data: dary
[Huawei-hwtacacs-redcentric]
DEBUG:netmiko:_read_channel_expect read_data: 'd \x1b[1Dary\r\n[Huawei-hwtacacs-redcentric]'

```

**Comment by thatguyjoshua** [comment]
Below is the logging with the two additions into BaseConnection

```
DEBUG:netmiko:write_channel: b'hwtacacs-server authentication 10.111.128.112 secondary\n'
DEBUG:netmiko:Pattern is: hwtacacs\-server\ authentication\ 10\.111\.128\.112\ secondary
DEBUG:netmiko:_read_channel_expect read_data: hwtacacs-server authentication 10.111.128.112 secon
DEBUG:netmiko:_read_channel_expect read_data: 'hwtacacs-server authentication 10.111.128.112 secon'
DEBUG:netmiko:_read_channel_expect read_data: dary
[Huawei-hwtacacs-company]
DEBUG:netmiko:_read_channel_expect read_data: 'd \x1b[1Dary\r\n[Huawei-hwtacacs-company]'

```

**Comment by pdice** [comment]
I'm seeing a very similar issue with 3.0.  I was doing a simple show run on a cisco ios router, and with debugs on I could see the prompt return, but netmiko would time out still looking for the prompt.  I uninstalled 3.0 and moved back to 2.4.2, and it worked as expected.

**Comment by ktbyers** [comment]
@thatguyjoshua Okay, that looks like a Huawei issue where it repaints the line for what it thinks are long-lines:

```
DEBUG:netmiko:_read_channel_expect read_data: hwtacacs-server authentication 10.111.128.112 secon
DEBUG:netmiko:_read_channel_expect read_data: 'hwtacacs-server authentication 10.111.128.112 secon'
DEBUG:netmiko:_read_channel_expect read_data: dary
```

Note, the first entry is listed twice.

We'll need to fix this in Netmiko. Probably in the Huawei driver.

**Comment by ktbyers** [comment]
@pdice Please open a separate issue. The above is Huawei specific issue.

**Comment by ktbyers** [comment]
I am going to close this as we have made quite a few changes with the Huawei driver. If anyone is still seeing this issue please either comment here or re-open a new issue (probably opening a new issue would be better).
