### ISSUE TITLE
Cisco IOS-XR 64 bit now named eXR

### ISSUE THREAD

**Issue by Alan-R** [ktbyers/netmiko#1533]
It seems to be a good idea to add support for the name "ios-exr" as an alias for 64 bit IOS-XR - since that's how Cisco calls it nowadays...

Would be happy to provide the patch if you want it.

**Comment by clingamg** [comment]
Hi, 
I am trying to use ConnectHJandler of Netmiko to connect to XR 64 (via telnet) and get the following error. If it is to do with device type, could you please help me to have the new device type available?
Thanks
Chandra

>>> device = {'device_type': 'cisco_xr_telnet', 'ip': '198.18.1.32', 'username': "cisco1", 'password': "cisco1", 'verbose' : 'true'}
>>> netmiko.ConnectHandler(**device)
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\cisco_base_connection.py", line 89, in telnet_login
    output = self.read_channel()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 494, in read_channel
    output = self._read_channel()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 476, in _read_channel
    output = self.remote_conn.read_very_eager().decode("utf-8", "ignore")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\telnetlib.py", line 366, in read_very_eager
    return self.read_very_lazy()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\telnetlib.py", line 403, in read_very_lazy
    raise EOFError('telnet connection closed')
EOFError: telnet connection closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#61>", line 1, in <module>
    netmiko.ConnectHandler(**device)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\ssh_dispatcher.py", line 252, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 318, in __init__
    self._open()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 323, in _open
    self.establish_connection()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 882, in establish_connection
    self.telnet_login()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\cisco_base_connection.py", line 144, in telnet_login
    raise NetmikoAuthenticationException(msg)
netmiko.ssh_exception.NetmikoAuthenticationException: Login failed: 198.18.1.32

**Comment by ktbyers** [comment]
@clingamg You failed the `telnet_login` process--you will need to enable Netmiko session_log to see what happened during your failed login.

Please open a separate issue for that (it is very unlikely related to this item).

**Comment by clingamg** [comment]
Thanks Kirk for the quick response, I will enable the session log and try to debug what is happening.
