### ISSUE TITLE
handling Authentication error on netmiko

### ISSUE THREAD

**Issue by onyourmarks7** [ktbyers/netmiko#1537]
i am trying to handle the exception while wrong rsa token entered.
but still it is throwing errors.

`def nm_connection():
    
    try:
        rsa_NM = input("enter RSA")
        node_mngr = dict(device_type='autodetect', ip='<Removed', username='<Removed>', password=rsa_NM)
        connect = ConnectHandler(**node_mngr)
    except (NetMikoAuthenticationException, NetMikoTimeoutException):
        print("RSA authentication failed , please enter RSA again")
        nm_connection()
    #print(connect.read_channel())
nm_connection()`

`enter RSA123
Traceback (most recent call last):
  File "C:\Users\<Removed>\AppData\Roaming\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 884, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "C:\Users\<Removed>\AppData\Roaming\Programs\Python\Python38-32\lib\site-packages\paramiko\client.py", line 435, in connect
    self._auth(
  File "C:\Users\<Removed>\AppData\Roaming\Programs\Python\Python38-32\lib\site-packages\paramiko\client.py", line 764, in _auth
    raise saved_exception
  File "C:\Users\<Removed>\AppData\Roaming\Programs\Python\Python38-32\lib\site-packages\paramiko\client.py", line 751, in _auth
    self._transport.auth_password(username, password)
  File "C:\Users\<Removed>\AppData\Roaming\Programs\Python\Python38-32\lib\site-packages\paramiko\transport.py", line 1509, in auth_password
    return self.auth_handler.wait_for_response(my_event)
  File "C:\Users\<Removed>\AppData\Roaming\Programs\Python\Python38-32\lib\site-packages\paramiko\auth_handler.py", line 250, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:/Python/Install/Arunproj/venv/test_1.py", line 9, in nm_connection
    connect = ConnectHandler(**node_mngr)
  File "C:\Users\<Removed>\AppData\Roaming\Programs\Python\Python38-32\lib\site-packages\netmiko\ssh_dispatcher.py", line 246, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\<Removed>\AppData\Roaming\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 317, in __init__
    self._open()
  File "C:\Users\<Removed>\AppData\Roaming\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 322, in _open
    self.establish_connection()
  File "C:\Users\<Removed>\AppData\Roaming\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 897, in establish_connection
    raise NetMikoAuthenticationException(msg)
netmiko.ssh_exception.NetMikoAuthenticationException: Authentication failure: unable to connect autodetect <Removed>
Authentication failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:/Python/Install/Arunproj/venv/test_1.py", line 14, in <module>
    nm_connection()
  File "H:/Python/Install/Arunproj/venv/test_1.py", line 10, in nm_connection
    except (NetMikoAuthenticationException, NetMikoTimeoutException):
NameError: name 'NetMikoAuthenticationException' is not defined

Process finished with exit code 1
`

**Comment by ktbyers** [comment]
It looks like you didn't import the Netmiko exception?

```
NameError: name 'NetMikoAuthenticationException' is not defined
```

**Comment by onyourmarks7** [comment]
@ktbyers    ah.. my bad , yes it seems i missed it  , thank you .
its working now
