### ISSUE TITLE
Netmiko Issue in GNS3

### ISSUE THREAD

**Issue by arighosh** [ktbyers/netmiko#1543]
I am running the below script - 
#!/usr/bin/env python

from netmiko import ConnectHandler

iosv_l2 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.72',
    'username': 'auritro',
    'password': 'auritro',
}

net_connect = ConnectHandler(**iosv_l2)
#net_connect.find_prompt()
output = net_connect.send_command('show ip int brief')
print output

config_commands = ['int loop 0', 'ip address 1.1.1.1 255.255.255.0']
output = net_connect.send_config_set(config_commands)
print output

for n in range (2,26):
    print "Creating VLAN " + str(n)
    config_commands = ['vlan ' + str(n), 'name Python_VLAN ' + str(n)]
    output = net_connect.send_config_set(config_commands)
    print output
---------------------------------------------------------------------------
And getting the following Error - 
auritro@auritro-python:~$ python netmiko1.py
Traceback (most recent call last):
  File "netmiko1.py", line 3, in <module>
    from netmiko import ConnectHandler
  File "/home/auritro/.local/lib/python2.7/site-packages/netmiko/__init__.py", line 7, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "/home/auritro/.local/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 2, in <module>
    from netmiko.a10 import A10SSH
  File "/home/auritro/.local/lib/python2.7/site-packages/netmiko/a10/__init__.py", line 1, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "/home/auritro/.local/lib/python2.7/site-packages/netmiko/a10/a10_ssh.py", line 3, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "/home/auritro/.local/lib/python2.7/site-packages/netmiko/cisco_base_connection.py", line 143
    msg = f"Login failed: {self.host}"
                                     ^
Can anyone please guide me here what is going wrong.

**Comment by ktbyers** [comment]
Netmiko 3.0.0 doesn't support Python 2.7. You would either need to convert to Python 3.6+ or downgrade to Netmiko 2.4.2

**Comment by arighosh** [comment]
ok thanks for the pointer Sir! will run on 3.6
