### ISSUE TITLE
cmd_verify issues on Palo Alto devices

### ISSUE THREAD

**Issue by JoshuaSmeda** [ktbyers/netmiko#1550]
Hi there,

netmiko version: `3.0.0`
python version: `3.6.9`
PanOS Model: `PA-220`
PanOS Version: `9.1`

I have a weird issue where netmiko doesn't output the response from the Palo Alto firewall but debugging contains the correct response. Really hope I can get some assistance with this - seems like `netmiko` is not realizing there is output and fails saying there is no data available.

Smaller commands such as `show system info` work perfectly. 

I've already tried increasing the `delay_factor` and `blocking_timeout` setting but was not successful.

Debug info below:

```
DEBUG:paramiko.transport:starting thread (client mode): 0xab143da0
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.7.1
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-OpenSSH_12.1
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_12.1)
DEBUG:paramiko.transport:kex algos:['ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group14-sha1', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group1-sha1'] server key:['ssh-rsa'] client encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'arcfour256', 'arcfour128', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com', 'aes128-cbc', '3des-cbc', 'blowfish-cbc', 'cast128-cbc', 'aes192-cbc', 'aes256-cbc', 'arcfour', 'rijndael-cbc@lysator.liu.se'] server encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'arcfour256', 'arcfour128', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com', 'aes128-cbc', '3des-cbc', 'blowfish-cbc', 'cast128-cbc', 'aes192-cbc', 'aes256-cbc', 'arcfour', 'rijndael-cbc@lysator.liu.se'] client mac:['hmac-md5-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-ripemd160-etm@openssh.com', 'hmac-sha1-96-etm@openssh.com', 'hmac-md5-96-etm@openssh.com', 'hmac-md5', 'hmac-sha1', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-ripemd160', 'hmac-ripemd160@openssh.com', 'hmac-sha1-96', 'hmac-md5-96'] server mac:['hmac-md5-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-ripemd160-etm@openssh.com', 'hmac-sha1-96-etm@openssh.com', 'hmac-md5-96-etm@openssh.com', 'hmac-md5', 'hmac-sha1', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-ripemd160', 'hmac-ripemd160@openssh.com', 'hmac-sha1-96', 'hmac-md5-96'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: ecdh-sha2-nistp256
DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for 10.11.12.254: b'136b4119f704eabed1fc35d74c6509af'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:read_channel: Last login: Mon Feb  3 09:11:50 2020 from 10.11.12.105



Number of failed attempts since last successful login: 0



DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: admin@R2D2> 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
admin@R2D2> 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is admin@R2D2>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:In disable_paging
DEBUG:netmiko:Command: set cli pager off

DEBUG:netmiko:write_channel: b'set cli pager off\n'
DEBUG:netmiko:Pattern is: set\ cli\ pager\ off
DEBUG:netmiko:_read_channel_expect read_data: set
admin@R2D2> set cli pager off
admin@R2D2> 
admin@R2D2> set cli pager off
admin@R2D2> 
admin@R2D2> set cli pager off
admin@R2D2> 
DEBUG:netmiko:Exiting disable_paging
DEBUG:netmiko:read_channel: 
Executing test security-policy-match protocol 6 from Trusted-L3 to Untrusted-L3 source 172.16.11.22 destination 8.8.8.8 destination-port 80
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
admin@R2D2> 
3 source 172.16.11.22 destination 8.8.8.8 destination-port 80d-L3 to Untrusted-L 


DEBUG:netmiko:_read_channel_expect read_data: "Block Bad Traffic; index: 1" {
        from any;
        source any;
        source-region none;
        to Untrusted-L3;
        destination any;
        destination-region none;
        user any;
        category any;
        application/service [0:kazaa/tcp/any/1214 1:kazaa/tcp/any/1903 2:gnutella/tcp/any/any 3:gnutella/udp/any/any 4:soulseek/tcp/any/2230-2250 5:direct-connect/tcp/any/any 6:ares/tcp/any/any 7:ares/udp/any/any 8:warez-p2p/tcp/any/6000 9:warez-p2p/tcp/any/6346-6351 10:warez-p2p/tcp/any/32285 11:warez-p2p/udp/any/6346-6351 12:emule/tcp/any/any 13:emule/udp/any/any 14:imesh/tcp/any/80 15:imesh/tcp/any/443 16:imesh/tcp/any/1863 17:imesh/tcp/any/4000-4999 18:imesh/tcp/any/4661 19:imesh/tcp/any/4662 20:imesh/tcp/any/4671 21:imesh/tcp/any/6346-6351 22:imesh/udp/any/4665 23:imesh/udp/any/4672 24:imesh/udp/any/6346-6351 25:bittorrent/tcp/any/any 26:bittorrent/udp/any/any 27:unknown-p2p/udp/any/any 28:peerenabler/tcp/any/3529-3533 29:peerenabler/udp/any/3529-3533 30:100bao/tcp/any/3468 31:100bao/tcp/any/6346 32:100bao/tcp/any/11300 33:fasttrack/tcp/any/1214 34:fasttrack/udp/any/1214 35:goboogy/tcp/any/5325 36:goboogy/udp/any/5325 ... ];
        application/service(implicit) [0:ssl/tcp/any/80 1:ssl/tcp/any/443 2:ssl/udp/any/any 3:web-browsing/tcp/any/80 4:web-browsing/tcp/any/443 5:web-browsing/udp/any/any ];
        action drop;
        icmp-unreachable: no
        terminal no;
}



admin@R2D2> 
Traceback (most recent call last):
  File "/home/joshua/palo_webapp/env/lib/python3.6/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/home/joshua/palo_webapp/env/lib/python3.6/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joshua/palo_webapp/env/lib/python3.6/site-packages/netmiko/base_connection.py", line 541, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/home/joshua/palo_webapp/env/lib/python3.6/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "a.py", line 42, in <module>
    out += net_connect.send_command(cmd)
  File "/home/joshua/palo_webapp/env/lib/python3.6/site-packages/netmiko/paloalto/paloalto_panos.py", line 160, in send_command
    return super().send_command(*args, **kwargs)
  File "/home/joshua/palo_webapp/env/lib/python3.6/site-packages/netmiko/base_connection.py", line 1366, in send_command
    new_data = self.read_until_pattern(pattern=re.escape(cmd))
  File "/home/joshua/palo_webapp/env/lib/python3.6/site-packages/netmiko/base_connection.py", line 618, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/home/joshua/palo_webapp/env/lib/python3.6/site-packages/netmiko/base_connection.py", line 552, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.
```

Sample Script

```
from netmiko import ConnectHandler
import time
import logging
import sys

logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)

panos_connection = {
    'device_type': 'paloalto_panos',
    'ip':          '10.11.12.254',
    'username':    'redacted',
    'password':    'redacted',
    'global_delay_factor' : 4,
    'blocking_timeout' : 8
}

config_commands = [
     'test security-policy-match protocol 6 from Trusted-L3 to Untrusted-L3 source 172.16.11.22 destination 8.8.8.8 destination-port 80',
#    'show interface hardware',
#    #'show system resources', # next command after this will hang
#    'show system services',
#    #'show system software status', # next command after this will hang
#    'show system state'
]



net_connect = ConnectHandler(**panos_connection)

out = ""
for cmd in config_commands:
    print("Executing %s" % cmd)
    out += "-------------"
    out += net_connect.send_command(cmd)

print(out)

net_connect.disconnect()


```

**Comment by JoshuaSmeda** [comment]
I ended up using Paramiko and pasting sample code here so other people that get stuck, can find a solution.

```
# Python 3

import paramiko
paramiko.common.logging.basicConfig(level=paramiko.common.DEBUG)

ssh_client = paramiko.SSHClient()
ssh_client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh_client.connect(self.host, self.port, self.username, self.password)
ssh_stdin, ssh_stdout, ssh_stderr = ssh_client.exec_command(' ')
ssh_stdin.channel.send("show system info")
ssh_stdin.channel.shutdown_write()
resp = ssh_stdout.read().decode('utf_8') 
resp = resp.replace('Number of failed attempts since last successful login: 0', '') # Remove this nonsense returned from Palo
resp = resp.rstrip() # Remove trailing chars
print(resp)
ssh_client.close()
```

**Comment by ktbyers** [comment]
Issue is due to Palo Alto not echoing the command that was sent properly and Netmiko 3.0.0 intentionally verifies the command is echoed.

Temporary solution is to use Netmiko 2.4.2

In the near term, I will add an argument to send_command to disable this command echo behavior. The default will still have it enabled however.

Most likely cause is the very long command length is causing Palo Alto to do something that makes it more readable for humans using the CLI, but breaks the actual command echo being returned.

It is possible we just need to find a way to adjust the terminal width in Palo Alto so this doesn't happen.

**Comment by ktbyers** [comment]
This PR here should fix the issue:

https://github.com/ktbyers/netmiko/pull/1566

You will need to add the argument `cmd_verify=False` to the send_command() call

**Comment by JoshuaSmeda** [comment]
Thanks, I will test and report back.

**Comment by AnkitDeshwal89** [comment]
Thanks it worked
root@DESKTOP-L85FFCG:/home/ankit/ansible-palo/library# python3 test_ansible.py
Password:
test


"Turst-to-Untrust; index: 1" {
        from Trust;
        source any;
        source-region none;
        to Untrust;
        destination any;
        destination-region none;
        user any;
        category any;
        application/service 0:any/any/any/any;
        action allow;
        icmp-unreachable: no
        terminal yes;
}

**Comment by genadmin-atm** [comment]
I am having a similar issue on a Juniper SRX 340 - printing the variable contains only partial output from "show configuration | no-more" in the terminal - debug console shows complete config being printed - same behavior in both netmiko 2.4.2 and 3.1. Other SRX devices with smaller configs output fine.

Python version 3.8.3
Netmiko version 2.4.2
Junos version: 18.2R3-S2.9

Script below:

```
import netmiko
from netmiko import ConnectHandler
from getpass import getpass

firewalls = ['10.10.10.1']

username = input('Username: ')
password = getpass()

for device_ip in firewalls:
    print('Connecting to ' + device_ip)
    device = ConnectHandler(device_type='juniper_junos', ip=device_ip, username=username, password=password)
    config_pull = device.send_command('show configuration | no-more')
    print('config pull finished')
    print(config_pull)
    print (len(config_pull))
    print('disconnecting now')
    device.disconnect()
    print('device disconnected')
print('Script Complete!')
```

Sanitized Output below:

```
Username: user
Password: pass
Connecting to 10.10.10.1
config pull finished

## Last commit: 2020-06-16 18:19:53 UTC by <omitted>
version 18.2R3-S2.9;
...<omitted config (~15,000 chars)>...
            policy ALLOW_THING {
                match {
                    source-address THING; <<<---this is not the last line in the config

30063
disconnecting now
device disconnected
Script Complete!
```

Debug Console Shows:

```
## Last commit: 2020-06-16 18:19:53 UTC by <omitted>
version 18.2R3-S2.9;
...<omitted config (~31,000 chars)...
    Expected end of config is shown

30063
disconnecting now
device disconnected
Script Complete!
```
