### ISSUE TITLE
Netmiko login exception

### ISSUE THREAD

**Issue by robi1975** [ktbyers/netmiko#1551]
Hello,

I'm new to python networking, and when I try to run a script in GNS3 I receive login exception listed below:
**exception:**
root@NetworkAutomation-1:~# python3 robi.py
Traceback (most recent call last):
  File "robi.py", line 1, in <module>
    from netmiko import ConnectHandler
  File "/usr/local/lib/python3.5/dist-packages/netmiko/__init__.py", line 7, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "/usr/local/lib/python3.5/dist-packages/netmiko/ssh_dispatcher.py", line 2, in <module>
    from netmiko.a10 import A10SSH
  File "/usr/local/lib/python3.5/dist-packages/netmiko/a10/__init__.py", line 1, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "/usr/local/lib/python3.5/dist-packages/netmiko/a10/a10_ssh.py", line 3, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "/usr/local/lib/python3.5/dist-packages/netmiko/cisco_base_connection.py", line 143
    **msg = f"Login failed: {self.host}"**
                                     ^
**script:**
`from netmiko import ConnectHandler

iosv_l2 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.33',
    'username': 'robert',
    'password': 'cisco'
}

net_connect = ConnectHandler(**iosv_l2)
output = net_connect.send_command('show ip int brief')
print (output)

config_commands = ['int loop 0', 'ip address 1.1.1.1 255.255.255.0']
output = net_connect.send_config_set(config_commands)
print (output)

for n in range (2,10):
    print ("Creating VLAN " + str(n))
    config_commands = ['vlan ' + str(n), 'name Python_VLAN ' + str(n)]
    output = net_connect.send_config_set(config_commands)
    print (output)`

Does anyone know how to fix this issue?
Thanks

**Comment by robi1975** [comment]
I just realize that I was using python3 to call a script. When I use just python everything works fine.

root@NetworkAutomation-1:~# python robi.py
