### ISSUE TITLE
import error 

### ISSUE THREAD

**Issue by tristaneniyan** [ktbyers/netmiko#1554]
>>> import netmiko
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/netmiko/__init__.py", line 7, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "/usr/local/lib/python3.5/dist-packages/netmiko/ssh_dispatcher.py", line 2, in <module>
    from netmiko.a10 import A10SSH
  File "/usr/local/lib/python3.5/dist-packages/netmiko/a10/__init__.py", line 1, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "/usr/local/lib/python3.5/dist-packages/netmiko/a10/a10_ssh.py", line 3, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "/usr/local/lib/python3.5/dist-packages/netmiko/cisco_base_connection.py", line 143
    msg = f"Login failed: {self.host}"
                                     ^

Note:
I have pip version 20. something
and python 3.5.
I have installed netmiko through pip.

**Comment by ktbyers** [comment]
Netmiko 3.0.0 requires Python 3.6 or greater as we are using f-strings.

So you would either need to downgrade to Netmiko 2.4.2 or upgrade to a newer version of Python3.
