### ISSUE TITLE
Netmiko error

### ISSUE THREAD

**Issue by ersanche** [ktbyers/netmiko#1571]
Hi, I have installed Python 3.5.2 as well as Netmiko and cryptography libraries. However, when attempting 

from netmiko import ConnectHandler

I get the following trace:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/netmiko/__init__.py", line 7, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "/usr/local/lib/python3.5/dist-packages/netmiko/ssh_dispatcher.py", line 2, in <module>
    from netmiko.a10 import A10SSH
  File "/usr/local/lib/python3.5/dist-packages/netmiko/a10/__init__.py", line 1, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "/usr/local/lib/python3.5/dist-packages/netmiko/a10/a10_ssh.py", line 3, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "/usr/local/lib/python3.5/dist-packages/netmiko/cisco_base_connection.py", line 143
    msg = f"Login failed: {self.host}"

SyntaxError: invalid syntax

The syntax error points to the end of the msg = f"Login failed: {self.host}" message

 Any thoughts on how to solve this?

**Comment by carlmontanari** [comment]
Netmiko is python3.6+ (we use f-strings as you see in the error)
