### ISSUE TITLE
Error message when running script for continuous execution

### ISSUE THREAD

**Issue by jkartheek999** [ktbyers/netmiko#1573]
I am very new to python and trying to learn for network automation. i am trying to execute a script for running a show command for 60 minutes. It is running for around 4 times and then comes out with the error message. My intention is to have the ability to run script every x seconds/minutes for a period of time. Thank you

Connecting Device 10.0.0.145
2020-02-12 12:31:54.876626Script Starting
2020-02-12 12:31:54.876626Script Completed

Connecting Device 10.0.0.145
2020-02-12 12:32:54.877592Script Starting
2020-02-12 12:32:54.877592Script Completed

Connecting Device 10.0.0.145
2020-02-12 12:33:54.878704Script Starting
2020-02-12 12:33:54.878704Script Completed

Connecting Device 10.0.0.145
2020-02-12 12:34:54.878623Script Starting
2020-02-12 12:34:54.878623Script Completed

Connecting Device 10.0.0.145
2020-02-12 12:35:54.878388Script Starting
2020-02-12 12:35:54.878388Script Completed

Connecting Device 10.0.0.145
2020-02-12 12:36:54.878364Script Starting
Traceback (most recent call last):
  File "E:\Python3.8\lib\site-packages\netmiko\base_connection.py", line 892, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "E:\Python3.8\lib\site-packages\paramiko\client.py", line 368, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 10.0.0.145

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "batchfile.py", line 22, in <module>
    net_connect = ConnectHandler(**access1)
  File "E:\Python3.8\lib\site-packages\netmiko\ssh_dispatcher.py", line 252, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "E:\Python3.8\lib\site-packages\netmiko\base_connection.py", line 318, in __init__
    self._open()
  File "E:\Python3.8\lib\site-packages\netmiko\base_connection.py", line 323, in _open
    self.establish_connection()
  File "E:\Python3.8\lib\site-packages\netmiko\base_connection.py", line 898, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.ssh_exception.NetmikoTimeoutException: Connection to device timed-out: cisco_ios 10.0.0.145:22

The Script is
```python
#!/usr/bin/env/python
from netmiko import ConnectHandler
import netmiko
import time
import schedule
import datetime
exceptions = (netmiko.ssh_exception.NetMikoTimeoutException, netmiko.ssh_exception.NetMikoAuthenticationException)



access1 = {
    'device_type': 'cisco_ios',
    'ip': '10.0.0.145',
    'username': 'cisco',
    'password': 'cisco',
}
starttime = time.time()
while True:
    TNOW = datetime.datetime.now()
    print("\n\nConnecting Device",access1['ip'])
    print(str(TNOW) + "Script Starting")
    net_connect = ConnectHandler(**access1)
    output = net_connect.send_command("show interface eth0/0 | in input", delay_factor=8)
    time.sleep(120 ((time.time() - starttime
    myfile = access1['ip'] + "eth0" ".txt"
    log_file = open(myfile, 'a+',)
    log_file.write(output)
    print(str(TNOW) + "Script Completed")
log_file.close()
```

**Comment by ktbyers** [comment]
You are continually opening new SSH connections to the device and you aren't calling the .disconnect() method so eventually you will run out of available VTY interfaces on the device and the SSH connection will fail.

So two possible solutions:
1. Keep the SSH connection open and execute `send_command` in the while loop (i.e. the ConnectHandler call outside of the while loop, but `send_command` inside the while loop).
2. Gracefully close the SSH connection using disconnect() each time through the while loop.

**Comment by jkartheek999** [comment]
Hello Kirk Byers,

  Thanks so much for your help. Since i did not know how to create a while
loop i tried the option 2 and it worked. If i want to run only for a time
period ( ex, 60 mins) and then stop the script, how can i do that.

Regards

Karthik
