### ISSUE TITLE
Error with net_connect.send_config_from_file

### ISSUE THREAD

**Issue by rome22** [ktbyers/netmiko#1598]
Hi,

Getting this error when doing a command  "net_connect.send_config_from_file". Could someone help me please?

C:\Users\XXX\XXXXX>py user-access.py
Connecting to the device 10.6.213.20
SW#

Traceback (most recent call last):
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\roman\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 541, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\Users\roman\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "user-access.py", line 38, in <module>
    output = net_connect.send_config_from_file(config_file='user-access.txt')
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 1642, in send_config_from_file
    return self.send_config_set(cfg_file, **kwargs)
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 1735, in send_config_set
    new_output = self.read_until_pattern(pattern=pattern)
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python37\lib\site-packages\XXXX\base_connection.py", line 618, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "C:\Users\roman\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 552, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

**Comment by ktbyers** [comment]
Which version of Netmiko are you using?

Which device_type are you using?

Also can you post your configuration commands you are sending from the file?

**Comment by rome22** [comment]
hi ktbyers,

Thanks for the quick reply

Name: netmiko
Version: 3.0.0
Summary: Multi-vendor library to simplify Paramiko SSH connections to network devices
Home-page: https://github.com/ktbyers/netmiko
Author: Kirk Byers
Author-email: ktbyers@twb-tech.com
License: MIT
Location: c:\users\roman\appdata\local\programs\python\python37\lib\site-packages
Requires: paramiko, pyserial, setuptools, scp, textfsm
Required-by:

also here are the commands i send


[user-access.txt](https://github.com/ktbyers/netmiko/files/4282994/user-access.txt)

**Comment by rome22** [comment]
Hi Kirk,

Device type is CISCO IOS

**Comment by ktbyers** [comment]
This command usually prompts you at the Cisco IOS level:

```
no username XXXXXX privilege 15 secret 5 XXXXXXXXXXX
```

i.e. you would need to use special code to handle this.

**Comment by ktbyers** [comment]
See the very end of this issue:

https://github.com/ktbyers/netmiko/issues/1596

I am going to close this as I think this is probably the issue.

**Comment by rome22** [comment]
i tried to run the script in netmiko 2.4.1 and it worked. Username was removed 

Thank you again
