### ISSUE TITLE
timeout issue with a simple send_config_set()

### ISSUE THREAD

**Issue by the-wolfox** [ktbyers/netmiko#1604]
Hello , 

I just tried to write my first netmiko code, but I'm having this error : 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.8/dist-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 541, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.8/dist-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "netmiko1.py", line 21, in <module>
    ssh_cnx.send_config_set("int loopb 0")
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 1704, in send_config_set
    output = self.config_mode(*cfg_mode_args)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/cisco_base_connection.py", line 40, in config_mode
    return super().config_mode(config_command=config_command, pattern=pattern)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 1595, in config_mode
    if not self.check_config_mode():
  File "/usr/local/lib/python3.8/dist-packages/netmiko/cisco/cisco_ios.py", line 29, in check_config_mode
    return super().check_config_mode(check_string=check_string, pattern=pattern)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/cisco_base_connection.py", line 30, in check_config_mode
    return super().check_config_mode(check_string=check_string, pattern=pattern)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 1582, in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 618, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 551, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.
```

and this is the python code : 

```python
import netmiko
from netmiko import ConnectHandler
#import pdb;pdb.set_trace()

R1 = {
    "device_type":"cisco_ios",
    "host":   "192.168.160.151",
    "username": "omar",
    "password": "omar",
    "port" : 22,
    "secret": "cisco"}

ssh_cnx = ConnectHandler(**R1)

sh_brief = ssh_cnx.send_command("show ip int brief")
print(sh_brief)
sh_route = ssh_cnx.send_command("show ip route")
print(sh_route)

ssh_cnx.send_config_set("int loopb 0")
```

**Comment by ktbyers** [comment]
Have you tried calling the `enable()` method?

```python
ssh_cnx = ConnectHandler(**R1)
ssh_cnx.enable()

sh_brief = ssh_cnx.send_command("show ip int brief")
print(sh_brief)
sh_route = ssh_cnx.send_command("show ip route")
print(sh_route)

ssh_cnx.send_config_set("int loopb 0")
```

**Comment by the-wolfox** [comment]
it worked. Thank you for helping,

but I don't get it , the show commands work fine without passing by the enable mode, however any send_config doesn't ? can you elaborat on that , because I didn't see say it on the documentation examples

**Comment by ktbyers** [comment]
Show commands don't require higher privileges. Configuration commands generally do (and Netmiko doesn't know which privileges you currently have).

Netmiko should probably provide a better error message than this, however.
