### ISSUE TITLE
with Netmiko can't connect router / Authentication failure: unable to connect cisco_ios

### ISSUE THREAD

**Issue by YMont** [ktbyers/netmiko#1621]
#!/usr/bin/env python
import netmiko
from netmiko import ConnectHandler 

my_device = {"device_type": "cisco_ios",
                      "host": "192.168.xxx.xxx",
                      "username": "xxxxxxxxxxx",
                      "password": "xxxxxxxxxxx"}

net_connect = ConnectHandler(**my_device)
output = net_connect.send_command("show ip int brief")
print(output)

net_connect.disconnect()
============================================
error code

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 502, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\paramiko\client.py", line 435, in connect
    self._auth(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\paramiko\client.py", line 764, in _auth
    raise saved_exception
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\paramiko\client.py", line 751, in _auth
    self._transport.auth_password(username, password)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\paramiko\transport.py", line 1509, in auth_password
    return self.auth_handler.wait_for_response(my_event)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\paramiko\auth_handler.py", line 250, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\test_code\examples\simple_conn.py", line 10, in <module>
    net_connect = ConnectHandler(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\ssh_dispatcher.py", line 131, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 150, in __init__
    self.establish_connection()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 511, in establish_connection
    raise NetMikoAuthenticationException(msg)
netmiko.ssh_exception.NetMikoAuthenticationException: Authentication failure: unable to connect cisco_ios 192.168.xxx.xxx:22
Authentication failed.
============================================
I try linux ssh to connect router that it is success.
but I run python script is failed.
I try a lot of method,but it always doesn't work.

Please help about my question. Thanks

**Comment by tars01** [comment]
Enable debugging, it might help you to see where it's going wrong:
https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by ktbyers** [comment]
@YMont Please format your markdown correctly...

Use triple backticks ```python wrapped around the code

And triple backticks wrapped around errors.

**Comment by ktbyers** [comment]
Are you sure your username and password are correct in your code. You might want to actually completely delete those two lines (username and password) and re-add them.

**Comment by YMont** [comment]
@ktbyers It works after I change my username. Thanks your remind. 
@tars01  Thanks for your good advise,next time I meet some error that I will try enable debugging and read the log.

netmiko is a magic module.
===========================================
share about my lab and method-

learn web(lunux connect router)(I think it very helpful for learning auto network):
https://networklessons.com/uncategorized/ssh-public-key-authentication-cisco-ios

note:
I make a mistake is use ssh_linux's username($ ssh username@hostname)
Actually, I change username(router setting username), it works.

by YMont
