### ISSUE TITLE
How to figure out "OSError: Socket is closed." is about "send_config_set(config_commands=)"

### ISSUE THREAD

**Issue by YMont** [ktbyers/netmiko#1639]
Question describe:
I got some problem,it's about "config_commands".
I want to change some router's parameter.
I gave two order is "duplex full" and "speed10(before speed 100)",but just first order work.
And when python run the second order,IDLE show "OSError: Socket is closed".
But the first parameter be changed already. (duplex half->full)

I don't know how fix it

Thanks for your help
appreciate
------------------------------
python code:
#!/usr/bin/env python
from __future__ import print_function, unicode_literals

import netmiko
from netmiko import ConnectHandler

my_device = {
    "host": "xxx.xxx.xxx.xxx",
    "username": "xxx",
    "password": "xxx",
    "device_type": "xxx",
}
net_connect = ConnectHandler(**my_device)
output = net_connect.send_config_set(config_commands=["interface fastEthernet 0/1",
                                                      "duplex full",
                                                      "speed 10"])
print(output)
net_connect.disconnect()
------------------------------
Error Code:
Traceback (most recent call last):
  File "C:\Users\Desktop\config_changes_modify_2.py", line 74, in <module>
    output = net_connect.send_config_set(config_commands=["interface fastEthernet 0/1",
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 959, in send_config_set
    self.write_channel(self.normalize_cmd(cmd))
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 218, in write_channel
    self._write_channel(out_data)
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 207, in _write_channel
    self.remote_conn.sendall(write_bytes(out_data))
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\paramiko\channel.py", line 846, in sendall
    sent = self.send(s)
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\paramiko\channel.py", line 801, in send
    return self._send(s, m)
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\paramiko\channel.py", line 1198, in _send
    raise socket.error("Socket is closed")
OSError: Socket is closed

**Comment by YMont** [comment]
I find that if I change interface fastEthernet 0/0 port (I use 0/1 port). It works normal.
I wonder that if use 0/1 and change 0/1 is possible success ?

Thanks

**Comment by ktbyers** [comment]
Is your change causing your connection to be dropped.

Anyways something external to your Netmiko program is causing the SSH connection to be dropped. You will have to determine what is causing that.

**Comment by prajaktamogare** [comment]
Hi @YMont ...The exact same issue is being faced by me. Same error and even for that fastEthernet 0/0 it is working fine and for 0/1 it is giving socket is closed ....Have you found the solution?

**Comment by ktbyers** [comment]
@prajaktamogare Can you post the netmiko log file? That might provide more information about what is happening?

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel
