### ISSUE TITLE
SCP EOFError when getting file from Cisco ASA

### ISSUE THREAD

**Issue by mrkcmo** [ktbyers/netmiko#1640]
I am seeing the following traceback when using the SCPCon module in Netmiko. 

```
            scp_conn = SCPConn(device)
            scp_conn.establish_scp_conn()
            scp_conn.scp_get_file("disk0:/%s" % dut, dest_acl_file)
            scp_conn.close()
```

I get the following traceback on the scp_get_file operation:
```
Traceback (most recent call last):
  File "facl_azure_sql.py", line 269, in <module>
    scp_conn.scp_get_file("disk0:/%s" % dut, dest_acl_file)
  File "E:\Python37\lib\site-packages\netmiko\scp_handler.py", line 45, in scp_get_file
    self.scp_client.get(source_file, dest_file)
  File "E:\Python37\lib\site-packages\scp.py", line 239, in get
    self.close()
  File "E:\Python37\lib\site-packages\scp.py", line 251, in close
    self.channel.close()
  File "E:\Python37\lib\site-packages\paramiko\channel.py", line 671, in close
    self.transport._send_user_message(m)
  File "E:\Python37\lib\site-packages\paramiko\transport.py", line 1863, in _send_user_message
    self._send_message(data)
  File "E:\Python37\lib\site-packages\paramiko\transport.py", line 1839, in _send_message
    self.packetizer.send_message(data)
  File "E:\Python37\lib\site-packages\paramiko\packet.py", line 431, in send_message
    self.write_all(out)
  File "E:\Python37\lib\site-packages\paramiko\packet.py", line 367, in write_all
    raise EOFError()
EOFError
```
The file gets downloaded and sometimes it will works without the error. But most times I get the error. 

Any thoughts?

**Comment by mrkcmo** [comment]
It only appears on Windows platform and normally seems to only happen if you have an open ssh session to the device in another window. Not sure why but working without issue in Linux. Will close out due to work around and limited environment specific impact.
