### ISSUE TITLE
syntax error under cisco_base_connection.py, line 143

### ISSUE THREAD

**Issue by archhorde** [ktbyers/netmiko#1646]
When trying to run a script calling this library I get the following traceback.

Traceback (most recent call last):
  File "change_main.py", line 1, in <module>
    from netmiko import ConnectHandler
  File "C:\Python27\lib\site-packages\netmiko\__init__.py", line 7, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "C:\Python27\lib\site-packages\netmiko\ssh_dispatcher.py", line 2, in <module>
    from netmiko.a10 import A10SSH
  File "C:\Python27\lib\site-packages\netmiko\a10\__init__.py", line 1, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "C:\Python27\lib\site-packages\netmiko\a10\a10_ssh.py", line 3, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "C:\Python27\lib\site-packages\netmiko\cisco_base_connection.py", line 143
    msg = f"Login failed: {self.host}"
                                     ^
SyntaxError: invalid syntax

**Comment by archhorde** [comment]
Verified the error is still there and I do have the latest version installed.

**Comment by ktbyers** [comment]
Netmiko no longer supports Python 2.7. In order to use Python 2.7, you would need to downgrade to Netmiko 2.4.2.
