### ISSUE TITLE
Not able to connect DELL OS 10 switches 

### ISSUE THREAD

**Issue by kakollu007** [ktbyers/netmiko#1647]
Error :

Traceback (most recent call last):
  File "C:/Users/kkumar/AppData/Local/Programs/Python/Python37-32/test.py", line 46, in <module>
    net_connect = Netmiko(**my_device)
  File "C:\Users\kkumar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\ssh_dispatcher.py", line 218, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\kkumar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\base_connection.py", line 271, in __init__
    self._try_session_preparation()
  File "C:\Users\kkumar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\base_connection.py", line 650, in _try_session_preparation
    self.session_preparation()
  File "C:\Users\kkumar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\base_connection.py", line 670, in session_preparation
    self.set_base_prompt()
  File "C:\Users\kkumar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\base_connection.py", line 957, in set_base_prompt
    prompt = self.find_prompt(delay_factor=delay_factor)
  File "C:\Users\kkumar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\base_connection.py", line 998, in find_prompt
    raise ValueError("Unable to find prompt: {}".format(prompt))
ValueError: Unable to find prompt:

**Comment by ktbyers** [comment]
@kakollu007 Did you ever get this working?

Which version of Netmiko are you using.

Also can you post your code?

**Comment by kakollu007** [comment]
Hi Ktbyers/Netmiko,

Yes its working now . could you please help me with this ?

Can i run this below commands to configure radius on multiple DELL switches
using python script?

configure terminal

radius-server host 100.** key ***

radius-server retransmit 3

radius-server timeout 5

exit


Regards,

Kakollu Kumar

**Comment by ktbyers** [comment]
Yes, you can run that...just use `send_config_set` (get rid of the configure terminal and exit as Netmiko should do that automatically).

**Comment by kakollu007** [comment]
Hi Ktbyers/Netmiko,

Please review the below code.does this work?

for devices in switches:
net_connect = ConnectHandler(**devices)
config = [‘radius-server host‘ + str(100.112.1.100), ‘radius-server key
keyname’, ‘radius-server retransmit‘ + str(3), ‘radius-server timeout‘ +
str(5),]
output = net_connect.send_config_set(config)
print(output)


Regards,
Kakollu Kumar

**Comment by ktbyers** [comment]
Have you tested it?

Have you looked at all your `config` lines and made sure they are correct?

I would use f-strings and not string concatenation (as string-concatenation is much harder to read).

**Comment by kakollu007** [comment]
can you can the line as per your suggestion. then I will test and come to
you with output.

config = [‘radius-server host‘ + str(100.112.1.100), ‘radius-server key
keyname’, ‘radius-server retransmit‘ + str(3), ‘radius-server timeout‘ +
str(5),]

**Comment by kakollu007** [comment]
can you change the line as per your suggestion? then I will test and come
to you with output.

config = [‘radius-server host‘ + str(100.112.1.100), ‘radius-server key
keyname’, ‘radius-server retransmit‘ + str(3), ‘radius-server timeout‘ +
str(5),]
