### ISSUE TITLE
Error when sending command for Huawei device

### ISSUE THREAD

**Issue by vineeth122** [ktbyers/netmiko#1650]
The script is generating an error when sending the command to the Huawei device through telnet

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/netmiko/utilities.py", line 347, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 1430, in send_command
    search_pattern
OSError: Search pattern never detected in send_command_expect: \<TAAEEL\-MANAGEDNOC_2019021274\>

```

@ktbyers please assist me on this.

**Comment by vineeth122** [comment]
Was able to resolve by enabling logging in netmiko
