### ISSUE TITLE
IOS Device doesn't disable paging or set the terminal width properly when user privilege is 0

### ISSUE THREAD

**Issue by msartuche** [ktbyers/netmiko#1662]
### IOS Device doesn't disable paging or set the terminal width properly when user privilege is 0
1. If you login with a user that has a privilege level of 0 Netmiko isn't making sure the terminal length and terminal width commands are sent without any errors. Discovered while using Napalm Automation.
   * Could look at adding a method to verify that the settings are in place and if not, then use the disable_paging() and set_terminal_width(command="terminal width 511") netmiko methods AFTER the enable() method or if the disable paging and set terminal settings fail but theres a secret set, try to enter enable mode then try again.
   #### Example of what the terminal settings output should look like.
   ```
   test881#show terminal | inc ength
   Length: 0 lines, Width: 512 columns
   ``` 
2. I enabled the following netmiko optional arguments to see what was happening:
   * verbose: True  
   * session_log_record_writes: True  
3. Looking at the output I can see that during the setup, netmiko establishes a connection without issue, then immediately performs a session preparation which disables paging and sets terminal width which both fail
#### Failure example output:
```
test881>
test881>terminal length 0
terminal length 0
                   ^
% Invalid input detected at '^' marker.

test881>terminal width 511
terminal width 511
                   ^
% Invalid input detected at '^' marker.

test881>

test881>enable
enable
Password: ********

test881#
```

### Setup
Cisco 881

### netmiko version
(Paste verbatim output from `pip freeze | grep netmiko` between quotes below)

```
C:\Users\msartuche>python -m pip freeze | grep netmiko
netmiko==2.4.2
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
Cisco IOS Software, C800 Software (C800-UNIVERSALK9-M), Version 15.4(3)M10, RELEASE SOFTWARE (fc1)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2018 by Cisco Systems, Inc.
Compiled Wed 08-Aug-18 06:30 by prod_rel_team

ROM: System Bootstrap, Version 15.4(1r)T1, RELEASE SOFTWARE (fc1)

test881 uptime is 3 days, 6 hours, 52 minutes
System returned to ROM by reload at 01:14:50 EDT Mon Apr 6 2020
System restarted at 01:17:24 EDT Mon Apr 6 2020
System image file is "flash:c800-universalk9-mz.SPA.154-3.M10.bin"
Last reload type: Normal Reload
Last reload reason: Embedded Event Manager action



This product contains cryptographic features and is subject to United
States and local country laws governing import, export, transfer and
use. Delivery of Cisco cryptographic products does not imply
third-party authority to import, export, distribute or use encryption.
Importers, exporters, distributors and users are responsible for
compliance with U.S. and local country laws. By using this product you
agree to comply with applicable laws and regulations. If you are unable
to comply with U.S. and local laws, return this product immediately.

A summary of U.S. laws governing Cisco cryptographic products may be found at:
http://www.cisco.com/wwl/export/crypto/tool/stqrg.html

If you require further assistance please contact us by sending email to
export@cisco.com.

Cisco C881-K9 (revision 1.0) with 488524K/35763K bytes of memory.
Processor board ID FJC2046L0DN
5 FastEthernet interfaces
1 Virtual Private Network (VPN) Module
DRAM configuration is 32 bits wide
255K bytes of non-volatile configuration memory.
250880K bytes of ATA System CompactFlash (Read/Write)


License Info:

License UDI:

-------------------------------------------------
Device#   PID                   SN
-------------------------------------------------
*1        C881-K9               FJC2046L0DN     



License Information for 'c800'
    License Level: advipservices   Type: Permanent
    Next reboot license Level: advipservices


Configuration register is 0x102
```

### Steps to Reproduce the Issue
Create a local user with a privilege level 0 setting.
```
username test-user privilege 0 secret blahblahPassword
```
### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
2020-04-09 07:42:17,656 - nornir.core.task -    ERROR -      start() - Host 'test881': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "C:\Users\msartuche\AppData\Local\Programs\Python\Python37\lib\site-packages\napalm\ios\ios.py", line 204, in _send_command
    output = self.device.send_command(command)
  File "C:\Users\msartuche\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 1337, in send_command
    search_pattern
OSError: Search pattern never detected in send_command_expect: test881\#

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\msartuche\AppData\Local\Programs\Python\Python37\lib\site-packages\nornir\core\task.py", line 85, in start
    r = self.task(self, **self.params)
  File "C:\Users\msartuche\AppData\Local\Programs\Python\Python37\lib\site-packages\nornir\plugins\tasks\networking\napalm_get.py", line 61, in napalm_get
    result[g] = method(**options)
  File "C:\Users\msartuche\AppData\Local\Programs\Python\Python37\lib\site-packages\napalm\ios\ios.py", line 3367, in get_config
    output = self._send_command(command)
  File "C:\Users\msartuche\AppData\Local\Programs\Python\Python37\lib\site-packages\napalm\ios\ios.py", line 207, in _send_command
    raise ConnectionClosedException(str(e))
napalm.base.exceptions.ConnectionClosedException: Search pattern never detected in send_command_expect: test881\#
```

**Comment by ktbyers** [comment]
Raise exception in this case when this condition is encountered.

**Comment by nullbitzero** [comment]
Hi @msartuche ,

The key factor is the privilege assigned to the user.
In cisco there are 3 types of levels in privilege (*):
+ level 0 includes the disable, enable, exit, help, and logout commands.
+ level 1 Normal level on Telnet; includes all user-level commands at the router> prompt.
+ level15 includes all enable-level commands at the router# prompt.

In conclusion you should consider an exception as indicated in the subject or otherwise change privilege, within the range of 1 to 15, the user to allow paging and width from user mode on the router or switch.
(*)https://community.cisco.com/t5/switching/cisco-user-privilege/td-p/2016519

Good Luck!
nullbit0

**Comment by msartuche** [comment]
I know I could set the privilege to 1 but it’s a requirement per company policy that all local accounts have level 0 privilege upon login and requires the user to enter enable mode and the enable password. Once the user is in enable mode you can run these commands without issue. So changing it to level 1 is not an option. It should be that we can have the Enable password sent first then we can run these commands. I was able to make a work around in napalm to work around the issue and have the enable password sent then re-run the terminal commands.

**Comment by msartuche** [comment]
I think raising exception may be the appropriate approach IF we can send an enable command then retry disabling paging etc.

**Comment by nullbitzero** [comment]
@msartuche ,
for the commented scenario the most appropriate thing is that if you use the conditionals; This way it detects the enable secret or password and then execute terminal commands.
as additional data in netmiko within your programming code you can use the session_preparation () method once you are in the privileged mode of the device.
the method contains:
+ set_base_prompt
+ disable_paging
+ set_terminal_width

**Comment by msartuche** [comment]
@nullbitzero 
I discovered the problem in the napalm_automation python package and added a patch to the ios driver for it to overcome this issue. I actually pull the current terminal settings AFTER napalm sends a enable() method to the device and if the length and width isn't correct I call the session_preparation AFTER verifying that enable mode is True. I check the terminal settings again and if good, I return the netmiko object, if not I raise an exception.

I brought up the issue on the napalm github but moved it here since it's more of a netmiko bug per se and not napalm, since netmiko is sending the disable_paging and set_terminal_width without verifying they actually happened, this is fine when your privilege level is 1 or higher but not when 0.

This is what I added to the napalm base.py file, it's not the prettiest but it works for now, the Exception would definitely cut down this line of code because we could easily use a try/except and if the Exception is an error because of disabling_paging or set_terminal_width we could do an enable() method and try again.

I appreciate the help and suggestions.

```
self._netmiko_device.enable()
term_settings = self._netmiko_device.send_command('show terminal | inc ength')
if term_settings != 'Length: 0 lines, Width: 511 columns':
    self._netmiko_device.session_preparation()
    terminal_settings = self._netmiko_device.send_command('show terminal | inc ength')
    if terminal_settings != 'Length: 0 lines, Width: 511 columns':
         raise ConnectionException("Problem with disabling paging and/or setting terminal width on {}".format(self.hostname))
```

**Comment by ktbyers** [comment]
I am going to close this. 

Netmiko pretty much always assumes you are allowed to disable paging (and generally that you are allowed to set the terminal width). It is the end-user's responsibility to ensure the account they use allows for this.

There are workarounds to this in Netmiko, but they are generally harder to accomplish (for example things like use the generic driver to connect, get the device state to the proper state for privileges, and then `redispatch`).

I am open to a PR that would indicate clearer that disable_paging() failed, but the privilege problem would still exist and would still need to be worked around.
