### ISSUE TITLE
getting error while sending command to router using netmiko

### ISSUE THREAD

**Issue by kingakii** [ktbyers/netmiko#1666]
here the command i am executing
`from netmiko import ConnectHandler

cisco_L2S = {
    'device_type': 'cisco_ios',
    'host':   '192.168.100.93',
    'username': 'admin',
    'password': 'cisco',
}
net_connect = ConnectHandler(**cisco_L2S)
output = net_connect.send_command('show ip int brief')
print(output)
config_commands = [ 'logging buffered 20000',
                    'logging buffered 20010',
                    'no logging console' ]
output = net_connect.send_config_set(config_commands)
print(output)
`
here is the output i am getting
`======== RESTART: C:\Users\king\OneDrive\Documents\network commands.py ========
Interface              IP-Address      OK? Method Status                Protocol
Ethernet0/0            192.168.10.2    YES manual up                    up      
Ethernet0/1            192.168.100.93  YES DHCP   up                    up      
Ethernet0/2            unassigned      YES unset  up                    up      
Ethernet0/3            unassigned      YES unset  up                    up      
Traceback (most recent call last):
  File "C:\Python\Python38-32\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Python\Python38-32\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 550, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\Python\Python38-32\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\akbar\OneDrive\Documents\network commands.py", line 15, in <module>
    output = net_connect.send_config_set(config_commands)
  File "C:\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 1728, in send_config_set
    output += self.config_mode(*cfg_mode_args)
  File "C:\Python\Python38-32\lib\site-packages\netmiko\cisco_base_connection.py", line 40, in config_mode
    return super().config_mode(config_command=config_command, pattern=pattern)
  File "C:\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 1618, in config_mode
    if not self.check_config_mode():
  File "C:\Python\Python38-32\lib\site-packages\netmiko\cisco\cisco_ios.py", line 29, in check_config_mode
    return super().check_config_mode(check_string=check_string, pattern=pattern)
  File "C:\Python\Python38-32\lib\site-packages\netmiko\cisco_base_connection.py", line 30, in check_config_mode
    return super().check_config_mode(check_string=check_string, pattern=pattern)
  File "C:\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 1605, in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "C:\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 627, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "C:\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 560, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.
>>> `

**Comment by ktbyers** [comment]
What privileges does your user have? Do you have privilege 15 i.e. sufficient privileges to make a configure change?

If not, you will need to add a `secret` argument and also call the `enable` method.

**Comment by kingakii** [comment]
Thanks its working now, actually i was following online video where he did not use secret command and did no use 'net_connect.enable()' command
