### ISSUE TITLE
Changing hostname on juniper devices fails on commit

### ISSUE THREAD

**Issue by alistairmackenzie** [ktbyers/netmiko#1667]
Relevant code:

```
jconn = ConnectHandler(**juniper_junos)

print ('Logged into {} ------------'.format(juniper_junos['ip']))

cmds = ['set system host-name sw01-lon.example.com']

output = jconn.send_config_set(cmds, exit_config_mode=False)
print(output)

output = jconn.commit(and_quit=True)
print(output)
```

Output:

```
Logged into 172.20.5.10 ------------
configureset system host-name sw01-lon.example.com 

{master:0}[edit]
alistair@test2# 



Traceback (most recent call last):
  File "change-host.py", line 35, in <module>
    output = jconn.commit(and_quit=True)
  File "/usr/local/lib/python3.7/dist-packages/netmiko/juniper/juniper.py", line 183, in commit
    delay_factor=delay_factor,
  File "/usr/local/lib/python3.7/dist-packages/netmiko/base_connection.py", line 1470, in send_command_expect
    return self.send_command(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/netmiko/utilities.py", line 347, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/netmiko/base_connection.py", line 1430, in send_command
    search_pattern
OSError: Search pattern never detected in send_command_expect: alistair@test2
```

Debug log output:

```
DEBUG:paramiko.transport:starting thread (client mode): 0xfb3399b0
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.7.1
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-OpenSSH_6.0
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_6.0)
DEBUG:paramiko.transport:kex algos:['ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group14-sha1', 'diffie-hellman-group1-sha1'] server key:['ssh-rsa', 'ssh-dss', 'ecdsa-sha2-nistp256'] client encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'arcfour256', 'arcfour128', 'aes128-cbc', '3des-cbc', 'blowfish-cbc', 'cast128-cbc', 'aes192-cbc', 'aes256-cbc', 'arcfour', 'rijndael-cbc@lysator.liu.se'] server encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'arcfour256', 'arcfour128', 'aes128-cbc', '3des-cbc', 'blowfish-cbc', 'cast128-cbc', 'aes192-cbc', 'aes256-cbc', 'arcfour', 'rijndael-cbc@lysator.liu.se'] client mac:['hmac-md5', 'hmac-sha1', 'umac-64@openssh.com', 'hmac-sha2-256', 'hmac-sha2-256-96', 'hmac-sha2-512', 'hmac-sha2-512-96', 'hmac-ripemd160', 'hmac-ripemd160@openssh.com', 'hmac-sha1-96', 'hmac-md5-96'] server mac:['hmac-md5', 'hmac-sha1', 'umac-64@openssh.com', 'hmac-sha2-256', 'hmac-sha2-256-96', 'hmac-sha2-512', 'hmac-sha2-512-96', 'hmac-ripemd160', 'hmac-ripemd160@openssh.com', 'hmac-sha1-96', 'hmac-md5-96'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: ecdh-sha2-nistp256
DEBUG:paramiko.transport:HostKey agreed: ecdsa-sha2-nistp256
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ecdsa-sha2-nistp256 host key for 172.20.5.10: b'0587fff71c0fd96a4c0dadc09ff705c6'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:read_channel: --- JUNOS 12.3R12-S12 built 2018-12-28 12:54:45 UTC
{master:0}
alistair@test2> 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 

{master:0}
alistair@test2> 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 

{master:0}
alistair@test2> 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is alistair@test2>
DEBUG:netmiko:write_channel: b'set cli complete-on-space off\n'
DEBUG:netmiko:read_channel: set cli complete-on-space off 
Disabling complete-on-space

{master:0}
alistair@test2> 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:In disable_paging
DEBUG:netmiko:Command: set cli screen-length 0

DEBUG:netmiko:write_channel: b'set cli screen-length 0\n'
DEBUG:netmiko:Pattern is: set\ cli\ screen\-length\ 0
DEBUG:netmiko:_read_channel_expect read_data: set
DEBUG:netmiko:_read_channel_expect read_data:  cli screen-length 0 
Screen length set to 0

{master:0}
alistair@test2> 
DEBUG:netmiko:Pattern found: set\ cli\ screen\-length\ 0 set cli screen-length 0 
Screen length set to 0

{master:0}
alistair@test2> 
DEBUG:netmiko:set cli screen-length 0 
Screen length set to 0

{master:0}
alistair@test2> 
DEBUG:netmiko:Exiting disable_paging
DEBUG:netmiko:write_channel: b'set cli screen-width 511\n'
DEBUG:netmiko:Pattern is: set\ cli\ screen\-width\ 511
DEBUG:netmiko:_read_channel_expect read_data: set
DEBUG:netmiko:_read_channel_expect read_data:  cli screen-width 511 
Screen width set to 511

{master:0}
alistair@test2> 
DEBUG:netmiko:Pattern found: set\ cli\ screen\-width\ 511 set cli screen-width 511 
Screen width set to 511

{master:0}
alistair@test2> 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 

{master:0}
alistair@test2> 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'configure\n'
DEBUG:netmiko:Pattern is: configure
DEBUG:netmiko:_read_channel_expect read_data: configure
DEBUG:netmiko:Pattern found: configure configure
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel:  

Entering configuration mode

{master:0}[edit]
alistair@test2# 

{master:0}[edit]
alistair@test2# 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'set system host-name sw01-lon.example.com \n'
DEBUG:netmiko:Pattern is: set\ system\ host\-name\ sw01\-lon\.example\.com 
DEBUG:netmiko:_read_channel_expect read_data: set
DEBUG:netmiko:_read_channel_expect read_data:  system host-name sw01-lon.example.com  

{master:0}[edit]
alistair@test2# 
DEBUG:netmiko:Pattern found: set\ system\ host\-name\ sw01\-lon\.example\.com  set system host-name sw01-lon.example.com  

{master:0}[edit]
alistair@test2# 
DEBUG:netmiko:configureset system host-name sw01-lon.example.com  

{master:0}[edit]
alistair@test2# 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 

{master:0}[edit]
alistair@test2# 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'commit and-quit\n'
DEBUG:netmiko:Pattern is: commit\ and\-quit
DEBUG:netmiko:_read_channel_expect read_data: c
DEBUG:netmiko:_read_channel_expect read_data: ommit and-quit 

DEBUG:netmiko:Pattern found: commit\ and\-quit commit and-quit 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: configuration check succeeds

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: commit complete
Exiting configuration mode

DEBUG:netmiko:read_channel: 
{master:0}
alistair@sw01-lon.example.com > 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
```

**Comment by ktbyers** [comment]
Yeah, it is failing because of the hostname change (which is causing it to not recognize the trailing prompt...since it has now changed).

**Comment by alistairmackenzie** [comment]
Yep, that was the conclusion I came to too.

Is there a way to have it repoll the prompt after commit to avoid this?

**Comment by siddeshpawar** [comment]
Can we try doing the following in a very secure environment
1. Import os                                   #first import os 
2. take the command in a varaible and then send the variable as an argument 
eg: statement : "sw01-lon.example.com"
output = jconn.send_config_set("set system host-name" +str(statement), exit_config_mode=False)
2. even after this hostname remains the same, does rebooting the device check is the last go. 

you always have a rollback for juniper to revert any changes.

**Comment by alistairmackenzie** [comment]
> Can we try doing the following in a very secure environment
> 
> 1. Import os                                   #first import os
> 2. take the command in a varaible and then send the variable as an argument
>    eg: statement : "sw01-lon.example.com"
>    output = jconn.send_config_set("set system host-name" +str(statement), exit_config_mode=False)
> 3. even after this hostname remains the same, does rebooting the device check is the last go.
> 
> you always have a rollback for juniper to revert any changes.


I'm not sure what this solves exactly. The issue is with the parsing of the prompt as it changes.

You can see in the log that it does commit the config fine but can't find the prompt it expects.

**Comment by ktbyers** [comment]
Fixed here:

https://github.com/ktbyers/netmiko/pull/3180
