### ISSUE TITLE
3.x appears broken for Linux systems: timeout with very simple usage.

### ISSUE THREAD

**Issue by Alan-R** [ktbyers/netmiko#1668]
Here's my test program with netmiko==3.1.0, paramiko==2.7.1:

```
import sys
import logging
from netmiko import ConnectHandler
logging.getLogger("netmiko").setLevel(logging.DEBUG)
netmiko = logging.getLogger("netmiko")
netmiko.setLevel(logging.DEBUG)
netmiko.handlers.clear()
stream = logging.StreamHandler(stream=sys.stderr)
message_format = "%(asctime)s %(name)s %(levelname)s: %(message)s"
stream.setFormatter(logging.Formatter(message_format))
netmiko.addHandler(stream)
logging.getLogger("paramiko").setLevel(logging.DEBUG)
paramiko = logging.getLogger("paramiko")
paramiko.setLevel(logging.DEBUG)
paramiko.handlers.clear()
stream = logging.StreamHandler(stream=sys.stderr)
message_format = "%(asctime)s %(name)s %(levelname)s: %(message)s"
stream.setFormatter(logging.Formatter(message_format))
paramiko.addHandler(stream)

connection = ConnectHandler(host="127.0.0.1", port=10001, username="operator", password="****", device_type="linux")

result = connection.send_command('echo "cable modem deny 0015.f2fe.ba11"; echo "cable modem deny 0015.f2fe.ba12"; echo "cable modem deny 0015.f2fe.ba13"')
print(result)
````
This program worked before (on 2.4.2 IIRC), but fails now with a timeout. Will attach log output. For what it's worth, I'm using panubo/sshd:1.0.2 for my test Linux sshd box. It's pretty handy.
`docker run -d -p 10001:22 panubo/sshd:1.0.2`. You'll have to set the password on operator with docker exec before you can ssh into the container.

**Comment by Alan-R** [comment]
The test output is below:
```
2020-04-15 15:11:25,726 netmiko DEBUG: In strip_ansi_escape_codes
2020-04-15 15:11:25,726 netmiko DEBUG: repr = 'Welcome to Alpine!\r\n\r\nThe Alpine Wiki contains a large amount of how-to guides and general\r\ninformation about administrating Alpine systems.\r\nSee <http://wiki.alpinelinux.org>.\r\n\r\nYou can setup the system with the command: setup-alpine\r\n\r\nYou may change this message by editing /etc/motd.\r\n\r\nCould not chdir to home directory /root: Permission denied\r\na0bea31c60bd:/$ \x1b[6n'
2020-04-15 15:11:25,728 netmiko DEBUG: Stripping ANSI escape codes
2020-04-15 15:11:25,728 netmiko DEBUG: new_output = Welcome to Alpine!

The Alpine Wiki contains a large amount of how-to guides and general
information about administrating Alpine systems.
See <http://wiki.alpinelinux.org>.

You can setup the system with the command: setup-alpine

You may change this message by editing /etc/motd.

Could not chdir to home directory /root: Permission denied
a0bea31c60bd:/$ 
2020-04-15 15:11:25,728 netmiko DEBUG: repr = 'Welcome to Alpine!\r\n\r\nThe Alpine Wiki contains a large amount of how-to guides and general\r\ninformation about administrating Alpine systems.\r\nSee <http://wiki.alpinelinux.org>.\r\n\r\nYou can setup the system with the command: setup-alpine\r\n\r\nYou may change this message by editing /etc/motd.\r\n\r\nCould not chdir to home directory /root: Permission denied\r\na0bea31c60bd:/$ '
2020-04-15 15:11:25,728 netmiko DEBUG: read_channel: Welcome to Alpine!

The Alpine Wiki contains a large amount of how-to guides and general
information about administrating Alpine systems.
See <http://wiki.alpinelinux.org>.

You can setup the system with the command: setup-alpine

You may change this message by editing /etc/motd.

Could not chdir to home directory /root: Permission denied
a0bea31c60bd:/$ 
2020-04-15 15:11:25,833 netmiko DEBUG: In strip_ansi_escape_codes
2020-04-15 15:11:25,834 netmiko DEBUG: repr = ''
2020-04-15 15:11:25,834 netmiko DEBUG: Stripping ANSI escape codes
2020-04-15 15:11:25,834 netmiko DEBUG: new_output = 
2020-04-15 15:11:25,834 netmiko DEBUG: repr = ''
2020-04-15 15:11:25,834 netmiko DEBUG: read_channel: 
2020-04-15 15:11:27,838 netmiko DEBUG: In strip_ansi_escape_codes
2020-04-15 15:11:27,839 netmiko DEBUG: repr = ''
2020-04-15 15:11:27,839 netmiko DEBUG: Stripping ANSI escape codes
2020-04-15 15:11:27,839 netmiko DEBUG: new_output = 
2020-04-15 15:11:27,839 netmiko DEBUG: repr = ''
2020-04-15 15:11:27,839 netmiko DEBUG: read_channel: 
2020-04-15 15:11:27,944 netmiko DEBUG: In strip_ansi_escape_codes
2020-04-15 15:11:27,945 netmiko DEBUG: repr = ''
2020-04-15 15:11:27,945 netmiko DEBUG: Stripping ANSI escape codes
2020-04-15 15:11:27,945 netmiko DEBUG: new_output = 
2020-04-15 15:11:27,945 netmiko DEBUG: repr = ''
2020-04-15 15:11:27,945 netmiko DEBUG: read_channel: 
2020-04-15 15:11:27,946 netmiko DEBUG: write_channel: b'\n'
2020-04-15 15:11:28,050 netmiko DEBUG: In strip_ansi_escape_codes
2020-04-15 15:11:28,050 netmiko DEBUG: repr = '\r\na0bea31c60bd:/$ \x1b[6n'
2020-04-15 15:11:28,050 netmiko DEBUG: Stripping ANSI escape codes
2020-04-15 15:11:28,051 netmiko DEBUG: new_output = 
a0bea31c60bd:/$ 
2020-04-15 15:11:28,051 netmiko DEBUG: repr = '\r\na0bea31c60bd:/$ '
2020-04-15 15:11:28,051 netmiko DEBUG: read_channel: 
a0bea31c60bd:/$ 
2020-04-15 15:11:28,257 netmiko DEBUG: In strip_ansi_escape_codes
2020-04-15 15:11:28,257 netmiko DEBUG: repr = ''
2020-04-15 15:11:28,257 netmiko DEBUG: Stripping ANSI escape codes
2020-04-15 15:11:28,257 netmiko DEBUG: new_output = 
2020-04-15 15:11:28,257 netmiko DEBUG: repr = ''
2020-04-15 15:11:28,257 netmiko DEBUG: read_channel: 
2020-04-15 15:11:28,257 netmiko DEBUG: [find_prompt()]: prompt is a0bea31c60bd:/$
2020-04-15 15:11:28,663 netmiko DEBUG: In strip_ansi_escape_codes
2020-04-15 15:11:28,663 netmiko DEBUG: repr = ''
2020-04-15 15:11:28,664 netmiko DEBUG: Stripping ANSI escape codes
2020-04-15 15:11:28,664 netmiko DEBUG: new_output = 
2020-04-15 15:11:28,664 netmiko DEBUG: repr = ''
2020-04-15 15:11:28,664 netmiko DEBUG: read_channel: 
2020-04-15 15:11:28,765 netmiko DEBUG: In strip_ansi_escape_codes
2020-04-15 15:11:28,765 netmiko DEBUG: repr = ''
2020-04-15 15:11:28,765 netmiko DEBUG: Stripping ANSI escape codes
2020-04-15 15:11:28,765 netmiko DEBUG: new_output = 
2020-04-15 15:11:28,765 netmiko DEBUG: repr = ''
2020-04-15 15:11:28,765 netmiko DEBUG: read_channel: 
2020-04-15 15:11:28,765 netmiko DEBUG: write_channel: b'\n'
2020-04-15 15:11:28,867 netmiko DEBUG: In strip_ansi_escape_codes
2020-04-15 15:11:28,868 netmiko DEBUG: repr = '\r\na0bea31c60bd:/$ \x1b[6n'
2020-04-15 15:11:28,868 netmiko DEBUG: Stripping ANSI escape codes
2020-04-15 15:11:28,868 netmiko DEBUG: new_output = 
a0bea31c60bd:/$ 
2020-04-15 15:11:28,868 netmiko DEBUG: repr = '\r\na0bea31c60bd:/$ '
2020-04-15 15:11:28,868 netmiko DEBUG: read_channel: 
a0bea31c60bd:/$ 
2020-04-15 15:11:29,074 netmiko DEBUG: In strip_ansi_escape_codes
2020-04-15 15:11:29,074 netmiko DEBUG: repr = ''
2020-04-15 15:11:29,074 netmiko DEBUG: Stripping ANSI escape codes
2020-04-15 15:11:29,074 netmiko DEBUG: new_output = 
2020-04-15 15:11:29,074 netmiko DEBUG: repr = ''
2020-04-15 15:11:29,075 netmiko DEBUG: read_channel: 
2020-04-15 15:11:29,075 netmiko DEBUG: [find_prompt()]: prompt is a0bea31c60bd:/$
2020-04-15 15:11:29,379 netmiko DEBUG: In strip_ansi_escape_codes
2020-04-15 15:11:29,379 netmiko DEBUG: repr = ''
2020-04-15 15:11:29,379 netmiko DEBUG: Stripping ANSI escape codes
2020-04-15 15:11:29,379 netmiko DEBUG: new_output = 
2020-04-15 15:11:29,379 netmiko DEBUG: repr = ''
2020-04-15 15:11:29,380 netmiko DEBUG: read_channel: 
2020-04-15 15:11:29,380 netmiko DEBUG: write_channel: b'echo "cable modem deny 0015.f2fe.ba11"; echo "cable modem deny 0015.f2fe.ba12"; echo "cable modem deny 0015.f2fe.ba13"\n'
2020-04-15 15:11:29,380 netmiko DEBUG: Pattern is: echo\ "cable\ modem\ deny\ 0015\.f2fe\.ba11";\ echo\ "cable\ modem\ deny\ 0015\.f2fe\.ba12";\ echo\ "cable\ modem\ deny\ 0015\.f2fe\.ba13"
2020-04-15 15:11:29,384 netmiko DEBUG: In strip_ansi_escape_codes
2020-04-15 15:11:29,384 netmiko DEBUG: repr = 'echo "cable modem deny 0015.f2fe.ba1'
2020-04-15 15:11:29,384 netmiko DEBUG: Stripping ANSI escape codes
2020-04-15 15:11:29,384 netmiko DEBUG: new_output = echo "cable modem deny 0015.f2fe.ba1
2020-04-15 15:11:29,384 netmiko DEBUG: repr = 'echo "cable modem deny 0015.f2fe.ba1'
2020-04-15 15:11:29,384 netmiko DEBUG: _read_channel_expect read_data: echo "cable modem deny 0015.f2fe.ba1
2020-04-15 15:11:29,485 netmiko DEBUG: In strip_ansi_escape_codes
2020-04-15 15:11:29,485 netmiko DEBUG: repr = '1"; echo "cable modem deny 0\r\r\n015.f2fe.ba12"; echo "cable modem deny 0015.f2fe.ba13"\r\ncable modem deny 0015.f2fe.ba11\r\ncable modem deny 0015.f2fe.ba12\r\ncable modem deny 0015.f2fe.ba13\r\na0bea31c60bd:/$ \x1b[6n'
2020-04-15 15:11:29,485 netmiko DEBUG: Stripping ANSI escape codes
2020-04-15 15:11:29,485 netmiko DEBUG: new_output = 1"; echo "cable modem deny 0

015.f2fe.ba12"; echo "cable modem deny 0015.f2fe.ba13"
cable modem deny 0015.f2fe.ba11
cable modem deny 0015.f2fe.ba12
cable modem deny 0015.f2fe.ba13
a0bea31c60bd:/$ 
2020-04-15 15:11:29,485 netmiko DEBUG: repr = '1"; echo "cable modem deny 0\r\r\n015.f2fe.ba12"; echo "cable modem deny 0015.f2fe.ba13"\r\ncable modem deny 0015.f2fe.ba11\r\ncable modem deny 0015.f2fe.ba12\r\ncable modem deny 0015.f2fe.ba13\r\na0bea31c60bd:/$ '
2020-04-15 15:11:29,485 netmiko DEBUG: _read_channel_expect read_data: 1"; echo "cable modem deny 0

015.f2fe.ba12"; echo "cable modem deny 0015.f2fe.ba13"
cable modem deny 0015.f2fe.ba11
cable modem deny 0015.f2fe.ba12
cable modem deny 0015.f2fe.ba13
a0bea31c60bd:/$ 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.7/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/netmiko/base_connection.py", line 550, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.7/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testme.py", line 23, in <module>
    result = connection.send_command('echo "cable modem deny 0015.f2fe.ba11"; echo "cable modem deny 0015.f2fe.ba12"; echo "cable modem deny 0015.f2fe.ba13"')
  File "/usr/local/lib/python3.7/site-packages/netmiko/utilities.py", line 347, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/netmiko/base_connection.py", line 1389, in send_command
    new_data = self.read_until_pattern(pattern=re.escape(cmd))
  File "/usr/local/lib/python3.7/site-packages/netmiko/base_connection.py", line 627, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/netmiko/base_connection.py", line 561, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

```

**Comment by Alan-R** [comment]
I retested with 2.4.2, and it definitely works. No timeouts.

**Comment by ktbyers** [comment]
I think it is the same issue as this:

https://github.com/ktbyers/netmiko/issues/1544

Should be an easy fix i.e. we need to set the terminal width after logging in for Linux.

**Comment by Alan-R** [comment]
he said his happened on 2.4.2. Mine doesn't. But I can try that and see...

**Comment by ktbyers** [comment]
Yeah, I don't know if I believe the 2.4.2 part as that should have only happened on Netmiko >=3.x.

Anyways somewhat moot as the fix would only be applied on the Netmiko `develop` branch (i.e. on the Netmiko 3.x code).

I am pretty sure that is the issue you are running into. And the characteristics you describe are what I would expect (i.e. works on Netmiko 2.4.2; fails on Netmiko 3.x).


Regards,

Kirk

**Comment by Alan-R** [comment]
Here's what stty -a returns:
```
$ stty -a
speed 9600 baud; rows 55; columns 301; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = M-^?; eol2 = M-^?; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; flush = ^O; min = 1; time = 0;
-parenb -parodd cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc ixany imaxbel -iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe -echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke
```
I know for sure I didn't have any lines over 301 columns. I seriously doubt that the other problem is the same as the one I'm seeing. But I'll add the recommended stty command to the driver and try again.

**Comment by Alan-R** [comment]
It's been my experience that rows and columns only affect curses-based programs (which ask the driver, and changes the behavior of curses programs) . The normal Linux/UNIX tty driver ignores them. They're there for the reference those who care.

**Comment by Alan-R** [comment]
OK. I have no idea why this helps, but it does. I'll close this and leave the other one open.
