### ISSUE TITLE
Netmiko, ntc-templates, textfsm: ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by alepodj** [ktbyers/netmiko#1679]
Hi

i have an issue with the new version of textfsm as follows:

####OS

```
Windows 10 
```

####pip freeze

```
...
netmiko==3.1.0
ntc-templates==1.4.0
textfsm==1.1.0
...
```

####Script

```
import os, json
import ntc_templates
from ntc_templates.parse import parse_output
from netmiko import Netmiko
from netmiko import NetMikoAuthenticationException

switch = {'device_type': 'cisco_ios',
            'ip': '192.168.0.20',
            'username': 'cisco',
            'password': 'cisco',
            'secret': 'cisco',
            'timeout': 10000,
            'session_timeout': 10000}

try:
    c = Netmiko(**switch)
    c.enable()
    show_ip_arp = c.send_command('show ip arp')
    show_ip_arp_parsed = parse_output(platform="cisco_ios", command="show ip arp", data=show_ip_arp)
    print(show_ip_arp_parsed)
except Exception as e:
    print(e)
```

####Error

```
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\ntc_templates\parse.py", line 5, in <module>
    from textfsm import clitable
  File "C:\Python37\lib\site-packages\textfsm\clitable.py", line 41, in <module>
    from textfsm import texttable
  File "C:\Python37\lib\site-packages\textfsm\texttable.py", line 42, in <module>
    from textfsm import terminal
  File "C:\Python37\lib\site-packages\textfsm\terminal.py", line 25, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/projects/IT-Tools-Dash/dev/netmiko/netmiko_test.py", line 3, in <module>
    from ntc_templates.parse import parse_output
  File "C:\Python37\lib\site-packages\ntc_templates\parse.py", line 7, in <module>
    import clitable
ModuleNotFoundError: No module named 'clitable'
```

...but if i forcefully downgrade textfsm to 0.4.1 then everything just works. I looked around and found other people issues related to `fcntl` not working in windows systems and such.

_Originally posted by @alepodj in https://github.com/ktbyers/netmiko/issues/1664#issuecomment-614975258_

**Comment by ktbyers** [comment]
I think you probably need to get rid of this:

```
from ntc_templates.parse import parse_output
```

TextFSM library has some issues working with windows (namely it won't without a workaround). Netmiko has one workaround for this that is built into Netmiko.

So the proper Netmiko solution would be:

```
    show_ip_arp = c.send_command('show ip arp', use_textfsm=True
```

This implies you have ntc-templates installed into the proper place or have an environment variable set to point to it. See:

https://pynet.twb-tech.com/blog/automation/netmiko-textfsm.html

Note, your above error is an ntc-templates exception (i.e. the exception is generated from their code) so if you want to use that pattern then you would need to raise an issue on that repository.

**Comment by alepodj** [comment]
Excellent that was it, thanks a lot.
