### ISSUE TITLE
PipeTimeout on script while same command works on nexus device

### ISSUE THREAD

**Issue by lazhao123** [ktbyers/netmiko#1682]
Hello,

I need to send the following commands to cisco nexus, using netmiko in python 3.7.4 on windows, I got pipe timeout exception on "peer-keepalive" command. I can enter these commands to nexus switch without error. What I should look at?
Logging error included. netmiko code that trigger exception included.

thanks in advance

=========== nexus commands:
vpc domain 10
peer-switch
role priority 10
peer-keepalive destination 192.168.0.51 source 192.168.0.50 vrf management

R1-93180LC-EX-A(config)# vpc domain 10
R1-93180LC-EX-A(config-vpc-domain)#   peer-switch
R1-93180LC-EX-A(config-vpc-domain)#   role priority 10
Note:
 Change will take effect after user has:
   1. Triggered "vpc role preempt" (non-disruptive - no traffic loss on STP root switch)
OR 2. Re-initd the vPC peer-link (disruptive)
Warning:
 !!:: vPCs will be flapped on current primary vPC switch while attempting option 2 ::!!
R1-93180LC-EX-A(config-vpc-domain)# peer-keepalive destination 192.168.0.51 source 192.168.0.50  <== netmiko fail on this
R1-93180LC-EX-A(config-vpc-domain)#

=========== my python code:
                net_connect = ConnectHandler(device_type=self.deviceType, ip=self.host, username=self.username, password=self.password)
                output = net_connect.send_config_set(commands)

--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\lzhao\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Users\lzhao\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\lzhao\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 541, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\Users\lzhao\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Switch\WinPython-64bit-3.6.3.0Zero\scripts\switches.py", line 42, in runconfig
    output = net_connect.send_config_set(commands)
  File "C:\Users\lzhao\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 1726, in send_config_set
    new_output = self.read_until_pattern(pattern=re.escape(cmd.strip()))
  File "C:\Users\lzhao\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 618, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "C:\Users\lzhao\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 552, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\lzhao\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 1025, in emit
    msg = self.format(record)
  File "C:\Users\lzhao\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "C:\Users\lzhao\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "C:\Users\lzhao\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
ValueError: unsupported format character 'O' (0x4f) at index 27
Call stack:
  File "C:\Users\lzhao\PyCharm Community Edition 2019.1.3\helpers\pydev\pydevd.py", line 1758, in <module>
    main()
  File "C:\Users\lzhao\PyCharm Community Edition 2019.1.3\helpers\pydev\pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Users\lzhao\PyCharm Community Edition 2019.1.3\helpers\pydev\pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\lzhao\PyCharm Community Edition 2019.1.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Switch/WinPython-64bit-3.6.3.0Zero/scripts/networkconfig.py", line 829, in <module>
    main()
  File "C:/Switch/WinPython-64bit-3.6.3.0Zero/scripts/networkconfig.py", line 816, in main
    UCPCINet.configureVendorPeering()
  File "C:/Switch/WinPython-64bit-3.6.3.0Zero/scripts/networkconfig.py", line 561, in configureVendorPeering
    peerlinkportchannel=1, peerlinkinterfaces=interfaces)
  File "C:\Switch\WinPython-64bit-3.6.3.0Zero\scripts\cisconexus.py", line 160, in setVPC
    self.runconfig(config_commands)
  File "C:\Switch\WinPython-64bit-3.6.3.0Zero\scripts\switches.py", line 48, in runconfig
    logger.info(self.host + "Oops!", sys.exc_info()[0], "occured.")
Message: 'fe80::a653:eff:fe9d:3fc0%16Oops!'
Arguments: (<class 'netmiko.ssh_exception.NetmikoTimeoutException'>, 'occured.')
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\lzhao\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Users\lzhao\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\lzhao\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 541, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\Users\lzhao\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Switch\WinPython-64bit-3.6.3.0Zero\scripts\switches.py", line 42, in runconfig
    output = net_connect.send_config_set(commands)
  File "C:\Users\lzhao\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 1726, in send_config_set
    new_output = self.read_until_pattern(pattern=re.escape(cmd.strip()))
  File "C:\Users\lzhao\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 618, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "C:\Users\lzhao\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 552, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\lzhao\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 1025, in emit
    msg = self.format(record)
  File "C:\Users\lzhao\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "C:\Users\lzhao\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "C:\Users\lzhao\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
ValueError: unsupported format character 'O' (0x4f) at index 27
Call stack:
  File "C:\Users\lzhao\PyCharm Community Edition 2019.1.3\helpers\pydev\pydevd.py", line 1758, in <module>
    main()
  File "C:\Users\lzhao\PyCharm Community Edition 2019.1.3\helpers\pydev\pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Users\lzhao\PyCharm Community Edition 2019.1.3\helpers\pydev\pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\lzhao\PyCharm Community Edition 2019.1.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Switch/WinPython-64bit-3.6.3.0Zero/scripts/networkconfig.py", line 829, in <module>
    main()
  File "C:/Switch/WinPython-64bit-3.6.3.0Zero/scripts/networkconfig.py", line 816, in main
    UCPCINet.configureVendorPeering()
  File "C:/Switch/WinPython-64bit-3.6.3.0Zero/scripts/networkconfig.py", line 561, in configureVendorPeering
    peerlinkportchannel=1, peerlinkinterfaces=interfaces)
  File "C:\Switch\WinPython-64bit-3.6.3.0Zero\scripts\cisconexus.py", line 160, in setVPC
    self.runconfig(config_commands)
  File "C:\Switch\WinPython-64bit-3.6.3.0Zero\scripts\switches.py", line 48, in runconfig
    logger.info(self.host + "Oops!", sys.exc_info()[0], "occured.")
Message: 'fe80::a653:eff:fe9d:3fc0%16Oops!'
Arguments: (<class 'netmiko.ssh_exception.NetmikoTimeoutException'>, 'occured.')

======= netmiko code that trigger exception, paramiko\buffered_pipe.py", line 164
    def read(self, nbytes, timeout=None):
        """
        Read data from the pipe.  The return value is a string representing
        the data received.  The maximum amount of data to be received at once
        is specified by ``nbytes``.  If a string of length zero is returned,
        the pipe has been closed.
	........... omit 
         """
        out = bytes()
        self._lock.acquire()
        try:
            if len(self._buffer) == 0:
                if self._closed:
                    return out
                # should we block?
                if timeout == 0.0:
                    raise PipeTimeout()
                # loop here in case we get woken up but a different thread has
                # grabbed everything in the buffer.
                while (len(self._buffer) == 0) and not self._closed:
                    then = time.time()
                    self._cv.wait(timeout)
                    if timeout is not None:
                        timeout -= time.time() - then
                        if timeout <= 0.0:
                            raise PipeTimeout()       <=== failed here

**Comment by tars01** [comment]
Turn on logging and tail the log, it should give you an idea of what is happening:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by ktbyers** [comment]
@lazhao123 You probably need to turn cmd_verify off here:

```python
output = net_connect.send_config_set(commands, cmd_verify=False)
```

Let me know if that works.

**Comment by lazhao123** [comment]
yes. It works now. Thank you for the help.
