### ISSUE TITLE
Can we use Attributes between cisco statements?

### ISSUE THREAD

**Issue by Arpanet86** [ktbyers/netmiko#1689]
Hi Ktbyers,

Am trying something out here and doesnt seem to work. Maybe am doing something wrong or its simply not possible. What am trying to do is when a user select a vlan from the "vlans" list. That vlan name will be put in the cisco statements:

con = net_connect.send_command_expect('show interfaces status | count'**, vlan,** '* connected')

**vlan** Will be the vlan selected by the user from the list.

```
`from netmiko import ConnectHandler
from getpass import getpass
from netmiko.ssh_exception import NetMikoTimeoutException
from netmiko.ssh_exception import NetMikoAuthenticationException
from netmiko.ssh_exception import SSHException

vlans = ['CHEESE', 'HAM', 'COOKIE', 'CANDY', 'WATER', 'COLA']
print(vlans)
number = input('Select VLAN [0-6]: ')

if number =='0':
    vlan = print(vlans[0])
elif vlan =='1':
    vlan = print(vlans[1])
elif vlan =='2':
    vlan = print(vlans[2])
elif vlan =='3':
    vlan = print(vlans[3])
elif vlan =='4':
    vlan = print(vlans[4])
elif vlan =='5':
    vlan = print(vlans[5])
else:
    print('That option is not available!')

def vlan_stats():
    con = net_connect.send_command_expect('show interfaces status | count', vlan, '* connected')
    notcon = net_connect.send_command_expect('show interfaces status | count', vlan, '* notconnect')
    ports = net_connect.send_command_expect('show interfaces status | count ', vlan)

    print('CON / NOTCON / SIZE:', con.strip(',Number of lines which match regexp =  '), 
    notcon.strip(',Number of lines which match regexp = '), 
    ports.strip(',Number of lines which match regexp = '))`

```
Hope to hear from you!

Best regards
Arpanet86

**Comment by ktbyers** [comment]
This `vlan = print(vlans[5]) doesn't do what you intend. That will assign None to vlan as it assigns the return value from print() which is None. The printing still happens to standard output.

```
>>> vlan = print(vlans[5])
COLA
>>> vlan
>>> print(vlan)
None
```

You should also print out your strings prior to using them as it is very easy to mess up the spacing on them. Also I would f-strings or string concatenation (I think your string formatting above is incorrect).

You also need to ensure your string is 100% correct from the CLI perspective so printing it out and testing it will help with that.

**Comment by Arpanet86** [comment]
Hi, 

Didn't expected such a swift reply! Thanks for pointing me out to the right direction. I will try to get this working. Awesome!

Arpanet86

**Comment by Arpanet86** [comment]
Hi Ktbyers,

I cant seem to figure this out and am stuck... Been reading and watching some online tutorials but cant get it to work. When i use the cli and print out the vlan attribute it shows me the correct value but still it comes back with errors i dont understand.

I updated the code as you pointed out... hopefully the way you meant :) Am a rookie Pthon programmer:

```
`#!/usr/bin/env python
from netmiko import ConnectHandler
from getpass import getpass
from netmiko.ssh_exception import NetMikoTimeoutException
from netmiko.ssh_exception import NetMikoAuthenticationException
from netmiko.ssh_exception import SSHException

vlans = {'0': 'CHEESE', '1': 'HAM', '2': 'COOKIE', '3': 'CANDY', '4': 'WATER', '5': 'COLA'}
print('Choos one of the following VLANS: ')

print('''
0:CHEESE | 1:HAM | 2:COOKIE 

3:CANDY | 4:WATER | 5:COLA 
''')

number = input('Select VLAN [0-5]: ')

while True:
    if number =='0':
        vlan = f'{vlans["0"]}'
        break
    if number =='1':
        vlan = f"{vlans['1']}"
        break 
    if number =='2':
        vlan = f"{vlans['2']}"
        break 
    if number =='3':
        vlan = f"{vlans['3']}"
        break 
    if number =='4':
        vlan = f"{vlans['4']}"
        break 
    if number =='5':
        vlan = f"{vlans['5']}" 
        break
    else:
        print('That option is not available. Try again!')
        exit()

def vlan_stats():
    con = net_connect.send_command_expect('show interfaces status | count', vlan ,'* connected')
    not_con = net_connect.send_command_expect('show interfaces status | count', vlan, '* notconnect')
    vlan_ports = net_connect.send_command_expect('show interfaces status | count', vlan)
    
    print('CON / NOTCON / SIZE:', con.strip(',Number of lines which match regexp =  '), 
    not_con.strip(',Number of lines which match regexp = '), 
    vlan_ports.strip(',Number of lines which match regexp = '))


IP_LIST = open('host_file.txt')
for IP in IP_LIST:
    HOSTS = {
        'device_type': 'cisco_ios',
        'ip': IP,
        'username': 'nverwe',
        'password': '********',
    }

    print('VLAN', vlan, 'STATS for Host: ' + IP.strip() + '')
    try:
        net_connect = ConnectHandler(**HOSTS)
    except NetMikoTimeoutException:
        print ('!ERROR - Device not reachable' )
        continue

    except NetMikoAuthenticationException:
        print ('!ERROR - Authentication Failure' )
        continue

    except SSHException:
        print ('!ERROR - Make sure SSH is enabled' )
        continue

    vlan_stats()`
```

This comes back with the following error:

````
VLAN CHEESE STATS for Host: 10.42.173.35
Traceback (most recent call last):
  File "vlan_stats2.py", line 76, in <module>
    vlan_stats()
  File "vlan_stats2.py", line 43, in vlan_stats
    con = net_connect.send_command_expect('show interfaces status | count',vlan ,'* connected')
  File "/home/nverwe/applications/netmiko/lib/python3.6/site-packages/netmiko/base_connection.py", line
1470, in send_command_expect
    return self.send_command(*args, **kwargs)
  File "/home/nverwe/applications/netmiko/lib/python3.6/site-packages/netmiko/utilities.py", line 347, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/home/nverwe/applications/netmiko/lib/python3.6/site-packages/netmiko/base_connection.py", line
1359, in send_command
    delay_factor = self.select_delay_factor(delay_factor)
  File "/home/nverwe/applications/netmiko/lib/python3.6/site-packages/netmiko/base_connection.py", line
1005, in select_delay_factor
    if delay_factor >= self.global_delay_factor:
TypeError: '>=' not supported between instances of 'str' and 'int'`
```

Hope your able to help out.

Gr,
Arpanet86

**Comment by daanvdsanden** [comment]
```python
con = net_connect.send_command_expect('show interfaces status | count', vlan ,'* connected')
```
a comma is not used for concatenating strings. you are now doing this:
```python
con = net_connect.send_command_expect(command_string='show interfaces status | count', expect_string=vlan, delay_factor='* connected')
```
replace it with:
```python
con = net_connect.send_command_expect('show interfaces status | count '+ vlan +'* connected')
# or
con = net_connect.send_command_expect(f"show interfaces status | count {vlan}* connected")
```

**Comment by ktbyers** [comment]
f-strings as @daanvdsanden showed in the last example...make getting this right/correct a lot easier.

**Comment by Arpanet86** [comment]
Yeah got that figured out. I really like the F string method.

Thanks for the help guys! Am closing this ticket.
