### ISSUE TITLE
ArubaOS8 Config Commands fail

### ISSUE THREAD

**Issue by vjtr** [ktbyers/netmiko#1700]
I'm doing the testing against an ArubaOS 8.6 MM.

I find there is no issues with running show commands however config fails. 

This is the script I was executing

```
`#!/usr/bin/env python3

from netmiko import Netmiko
import logging

logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

# Create device dictionary

wlc01 = {
    "host": "10.9.3.93",
    "username": "admin",
    "password": "admins",
    "device_type": "aruba_os",
}


net_connect = Netmiko(**wlc01)
print()
cfg_commands = ["logging 10.9.3.63"]
output = net_connect.send_config_set(cfg_commands)
print(output)
net_connect.disconnect()
```
`
If replace the  net_connect.send_config_set with  net_connect.send_command and do a "show command" things work. I have enabled logging and have attached logging of working scenario (show command) and non-working scenario(config command). I have also tried to different configs to rule out any specific config causing issues.

Below is the traceback

```

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.7/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/netmiko/base_connection.py", line 550, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.7/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./flashbackup_netmiko.py", line 23, in <module>
    output = net_connect.send_config_set(cfg_commands)
  File "/usr/local/lib/python3.7/site-packages/netmiko/base_connection.py", line 1728, in send_config_set
    output += self.config_mode(*cfg_mode_args)
  File "/usr/local/lib/python3.7/site-packages/netmiko/cisco_base_connection.py", line 40, in config_mode
    return super().config_mode(config_command=config_command, pattern=pattern)
  File "/usr/local/lib/python3.7/site-packages/netmiko/base_connection.py", line 1621, in config_mode
    output += self.read_until_pattern(pattern=re.escape(config_command.strip()))
  File "/usr/local/lib/python3.7/site-packages/netmiko/base_connection.py", line 627, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/netmiko/base_connection.py", line 561, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

```
[configmode_test.log](https://github.com/ktbyers/netmiko/files/4543504/configmode_test.log)
[showcommand_test.log](https://github.com/ktbyers/netmiko/files/4543505/showcommand_test.log)

**Comment by ktbyers** [comment]
This issue should have been fixed here:

https://github.com/ktbyers/netmiko/commit/3000ce33107ff3498600d40e842f4eee77b96edb
