### ISSUE TITLE
Eltex device config_set failed

### ISSUE THREAD

**Issue by srqjan** [ktbyers/netmiko#1701]
Hi , i can't configure eltex device trough netmiko , i am getting error like this 
python3 timezone_set_olt.py 
Traceback (most recent call last):
  File "timezone_set_olt.py", line 45, in <module>
    command_output = net_conn.send_config_set(cmd_leto)
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 1620, in send_config_set
    output += self.exit_config_mode()
  File "/usr/local/lib/python3.6/dist-packages/netmiko/cisco_base_connection.py", line 56, in exit_config_mode
    exit_config=exit_config, pattern=pattern
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 1535, in exit_config_mode
    raise ValueError("Failed to exit configuration mode")
ValueError: Failed to exit configuration mode

script 
import sys
from netmiko import Netmiko
import paramiko
import readline
import re
import os

olt_list = ["olt"
#    "satt-srb-turija-gpon-olt-1",
#    "satt-srb-moravica-olt-1",
#    "satt-srb-orom-olt-1",
#    "satt-srb-temerin-olt-1",
#    "satt-srb-subotica-olt-1",
#    "satt-srb-subotica-olt-2",
#    "satt-srb-budisava-olt-1",
#    "satt-srb-zabalj-olt-1",
#    "satt-srb-btopola-olt-1",
#    "satt-srb-apatin-olt-1"
]

cmd = "sh run"
cmd_leto = "clock timezone hours 01 minutes 00"   # leto posle marta
cmd_zima = "clock timezone hours 02 minutes 00"   #zima 
commit = "do commit"
confirm = "do confirm"
conf = "configure terminal"

for olt in olt_list:
        try:
            olt_device = {
                "host": olt,
                "username": 'srdjan',
                "password": 'Srdjan84',
                "device_type": "eltex",
            }
            net_conn = Netmiko(**olt_device)

        except (NetMikoAuthenticationException, NetMikoTimeoutException):
              continue
#             
             # Get command output for data collection
        command_output = net_conn.send_config_set(cmd_leto)
        print(command_output)

**Comment by ktbyers** [comment]
@srqjan When you do this change manually and then try to exit configuration mode, does it allow you?

Or does it prompt you `commit` the change first?

**Comment by ktbyers** [comment]
Not enough information here on what the issue is (i.e. why the exit_config_mode() fails)
