### ISSUE TITLE
Sudden NetMikoAuthenticationException appeared 

### ISSUE THREAD

**Issue by jogindergur** [ktbyers/netmiko#1715]
Hello Everyone,

I was using Netmiko for Huawei and it was working fine. Suddenly working code raising NetmikoAuthenticationException but same code was working fine some days ago. One change I have made in setup was I changed the IP of device but with new IP it is working fine with Putty.

```
device = {
    'device_type': 'huawei_smartax',
    'ip': 'XX.XX.XX.XX',
    'port': 'XX',
    'username': 'user',
    'password': 'pass'
}

def connect_olt():
    print('Connecting...')
    try:
        SSH = ConnectHandler(**device)
        print(SSH)
        return True
    except NetMikoTimeoutException:
        print('Time Out.')
        return False
    except NetMikoAuthenticationException:
        print('Unable to authenticate')
        return False

```

@ktbyers Please help me, without connection nothing can be done.

**Comment by jogindergur** [comment]
Hi @Fikirsiz I have posted it week ago but no response from anyone. Can you please help me? Why it is happening now?

**Comment by ktbyers** [comment]
@jogindergur Can you post your full exception stack?

Remove the try/except code above that hides the exception.

Also which version of Netmiko are you using?


Regards, Kirk

**Comment by jogindergur** [comment]
netmiko 3.1.0
Connecting...
Traceback (most recent call last):
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 899, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\paramiko\client.py", line 435, in connect
    self._auth(
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\paramiko\client.py", line 764, in _auth
    raise saved_exception
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\paramiko\client.py", line 751, in _auth
    self._transport.auth_password(username, password)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\paramiko\transport.py", line 1509, in auth_password
    return self.auth_handler.wait_for_response(my_event)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\paramiko\auth_handler.py", line 236, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/Hexanet/Happy/work/python/SafeOLT/hello.py", line 57, in <module>
    isSSH = connect_olt()
  File "F:/Hexanet/Happy/work/python/SafeOLT/hello.py", line 25, in connect_olt
    SSH = ConnectHandler(**device)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\ssh_dispatcher.py", line 265, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 327, in __init__
    self._open()
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 332, in _open
    self.establish_connection()
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 912, in establish_connection
    raise NetmikoAuthenticationException(msg)
netmiko.ssh_exception.NetmikoAuthenticationException: Authentication failure: unable to connect huawei_smartax XX.XX.XX.XX:XX
Authentication failed.

**Comment by jogindergur** [comment]
@ktbyers I have posted full stack trace with netmiko version. Please have a look.

**Comment by ktbyers** [comment]
@jogindergur And your IP address and port that you X'd out there are correct?

Besides that I would probably triple check your username and password including re-entering them (to make sure there are no hidden characters embedded in them). I also would probably print them out using python `repr` to inspect them.

You could also try looking at the Paramiko log to see if anything funky is going on under-the-hood, but it doesn't really look like it (given your exception stack).

**Comment by jogindergur** [comment]
Yes @ktbyers have checked IP, Port, username and password many times. They are all correct because I also use them in Putty so I'm damn sure they all are correct. I will check with Paramiko and revert with result as well.

**Comment by ktbyers** [comment]
You mentioned above you are using Netmiko 3.1.0? Is that pip installed or are you using the `develop` branch?

Netmiko 3.1.0 doesn't have Huawei Smart AX support? That was added after that was released?

**Comment by jogindergur** [comment]
Yes, I'm using develop branch because I need Netmiko for Huawei SmartAX.
I have also tried my hands with Paramiko and I found paramiko refused connection by saying unknown host then I add a line

`client.set_missing_host_key_policy(AutoAddPolicy())`

After this line paramiko code works fine.

**Comment by ktbyers** [comment]
Netmiko is just using Paramiko for SSH and automatically does the `AutoAddPolicy`.

**Comment by ktbyers** [comment]
@jogindergur Did you get this working or resolve this?

You could include the Netmiko log file and I can see if I can see anything odd:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel


The only odd cases that I can remember on this topic were:
1. Network device does something odd during the authentication process that we are not handling.
2. SSH keys are being used when you intended to use username/password.
3. A hidden character is embedded in the user's username or password.


Kirk

**Comment by jogindergur** [comment]
I change my venv and everything came back to normal

**Comment by TheoOui** [comment]
Hello, what did you change on the the venv ?

**Comment by jogindergur** [comment]
either activate new venv or create another project with same.
