### ISSUE TITLE
Getting exception error while executing simple netmiko script

### ISSUE THREAD

**Issue by vvishnu04** [ktbyers/netmiko#1726]
I am in the process of learning netmiko. When trying to run simple script from my jumpserver was getting the below exceptions. I was able to run only 'send_command' properly without any exceptions. However when i run 'send_config_from_file' & 'send_config_set', i am getting the exceptions. Not sure what is the issue. 

from netmiko import ConnectHandler

juniper_device = {
        'device_type': 'juniper',
        'ip': '192.168.1.10',
        'username': 'test',
        'password': 'test',
        'port': 22,
        'verbose':True
        }
connection = ConnectHandler(**juniper_device)
commands = ['show route 4.2.2.2', 'ping 4.2.2.2 rapid']
output = connection.send_config_set(commands)
print(output)

connection.disconnect()

SSH connection established to 192.168.1.10:22
Interactive SSH session established
Running commands from file...
Traceback (most recent call last):
  File "/home/xxxx/python36/lib64/python3.6/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/home/xxxx/python36/lib64/python3.6/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xxxx/python36/lib64/python3.6/site-packages/netmiko/base_connection.py", line 550, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/home/xxxx/python36/lib64/python3.6/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "vish.py", line 13, in <module>
    output = connection.send_config_from_file('junipercmds.txt')
  File "/home/xxxx/python36/lib64/python3.6/site-packages/netmiko/base_connection.py", line 1665, in send_config_from_file
    return self.send_config_set(cfg_file, **kwargs)
  File "/home/xxxx/python36/lib64/python3.6/site-packages/netmiko/base_connection.py", line 1750, in send_config_set
    new_output = self.read_until_pattern(pattern=re.escape(cmd.strip()))
  File "/home/xxxx/python36/lib64/python3.6/site-packages/netmiko/base_connection.py", line 627, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/home/xxxx/python36/lib64/python3.6/site-packages/netmiko/base_connection.py", line 561, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available

**Comment by ktbyers** [comment]
You shouldn't really be using `send_config_set` to send show commands. Instead use send_command or send_command_timing method.

**Comment by vvishnu04** [comment]
My bad. Thanks Kirk. Just one more query. Is there some method i can leverage to send multiple show commands from file or set just like how we do for config instead of using multiple send_command lines in the script. Gone through documentation but looks like none.

**Comment by vvishnu04** [comment]
Anyways I modified the script by calling a file with set of show commands and reiterate with for loop using send_command.

**Comment by ktbyers** [comment]
Yes, general process is to just use a `for-loop` with send_command.
