### ISSUE TITLE
Recent versions of Netmiko require Python 3.6 to support f-strings

### ISSUE THREAD

**Issue by 4nishanth** [ktbyers/netmiko#1728]
i am having issues to run a netmiko code, not sure on what i am missing 

root@eve-ng:~/python3-practise# python3 netmiko1.py 
Traceback (most recent call last):
  File "netmiko1.py", line 1, in <module>
    from netmiko import ConnectHandler
  File "/usr/local/lib/python3.5/dist-packages/netmiko/__init__.py", line 7, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "/usr/local/lib/python3.5/dist-packages/netmiko/ssh_dispatcher.py", line 2, in <module>
    from netmiko.a10 import A10SSH
  File "/usr/local/lib/python3.5/dist-packages/netmiko/a10/__init__.py", line 1, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "/usr/local/lib/python3.5/dist-packages/netmiko/a10/a10_ssh.py", line 3, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "/usr/local/lib/python3.5/dist-packages/netmiko/cisco_base_connection.py", line 143
    msg = f"Login failed: {self.host}"
                                     ^
SyntaxError: invalid syntax
root@eve-ng:~/python3-practise# cat netmiko1.py 
from netmiko import ConnectHandler

iosv_l2 = {
    'device_type': 'cisco_ios',
    'ip': '10.0.0.166',
    'username': 'nish',
    'password': 'cisco',
}

net_connect = ConnectHandler(**iosv_l2)
output = net_connect.send_command('show ip int brief')
print (output)

config_commands = ['int loop 0', 'ip address 1.1.1.1 255.255.255.0']
output = net_connect.send_config_set(config_commands)
print (output)

for n in range (2,21):
    print ("Creating VLAN " + str(n))
    config_commands = ['vlan ' + str(n), 'name Python_VLAN ' + str(n)]
    output = net_connect.send_config_set(config_commands)
    print (output) 

root@eve-ng:~/python3-practise#

**Comment by nullbitzero** [comment]
@4nishanth
After the connecthandle consider net_connet.enable () then exit = net_connect.send_command ('show ip int brief')
For the loop you are trying to make you must modify it so that each process sends the command with net_connet.send_command (config_commands) or use the append so that you create a list and then send it with send_config_set (config_commands)

Luck

**Comment by daanvdsanden** [comment]
> i am having issues to run a netmiko code, not sure on what i am missing

```
root@eve-ng:~/python3-practise# python3 netmiko1.py
Traceback (most recent call last):
  File "netmiko1.py", line 1, in 
    from netmiko import ConnectHandler
  File "/usr/local/lib/python3.5/dist-packages/netmiko/**init**.py", line 7, in
    from netmiko.ssh_dispatcher import ConnectHandler
  File "/usr/local/lib/python3.5/dist-packages/netmiko/ssh_dispatcher.py", line 2, in
    from netmiko.a10 import A10SSH File "/usr/local/lib/python3.5/dist-packages/netmiko/a10/**init**.py", line 1, in
    from netmiko.a10.a10_ssh import A10SSH
  File "/usr/local/lib/python3.5/dist-packages/netmiko/a10/a10_ssh.py", line 3, in
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "/usr/local/lib/python3.5/dist-packages/netmiko/cisco_base_connection.py", line 143
    msg = f"Login failed: {self.host}"
                ^ SyntaxError: invalid syntax
```
You need python 3.6 fstring were introduced in python 3.6 (https://www.python.org/dev/peps/pep-0498/)

And based on your traceback you are running python 3.5...
