### ISSUE TITLE
Timed-out reading channel, data not available Error

### ISSUE THREAD

**Issue by jayspalma** [ktbyers/netmiko#1732]
I am experiencing this error,  netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

Here is my code:
from netmiko import ConnectHandler                                                                                                         

cisco = { 
'device_type': 'cisco_ios', 
'host': '192.168.1.1', 
'username': 'cisco', 
'password': '12345678',
'secret': 'cisco' 
}

net_connect = ConnectHandler(**cisco)
configs = ['int loopback 0']
output = net_connect.send_command("show ip int brief")
print(output)
output = net_connect.send_config_set(configs)
print(output)

Here is the output:

Interface                  IP-Address      OK? Method Status                Protocol
GigabitEthernet0/0         192.168.1.1     YES NVRAM  up                    up
GigabitEthernet0/1         unassigned      YES NVRAM  administratively down down
GigabitEthernet0/2         unassigned      YES NVRAM  administratively down down
GigabitEthernet0/3         unassigned      YES NVRAM  administratively down down
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.8/dist-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 550, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.8/dist-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "netmiko_base.py", line 15, in <module>
    output = net_connect.send_config_set(configs)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 1728, in send_config_set
    output += self.config_mode(*cfg_mode_args)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/cisco_base_connection.py", line 40, in config_mode
    return super().config_mode(config_command=config_command, pattern=pattern)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 1618, in config_mode
    if not self.check_config_mode():
  File "/usr/local/lib/python3.8/dist-packages/netmiko/cisco/cisco_ios.py", line 29, in check_config_mode
    return super().check_config_mode(check_string=check_string, pattern=pattern)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/cisco_base_connection.py", line 30, in check_config_mode
    return super().check_config_mode(check_string=check_string, pattern=pattern)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 1605, in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 627, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 560, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

As you can see, the ssh connection to the device is successful because the result of "show ip int brief" command was returned.

The problem happens in the send_config_set command. I also tried to change the cmd_verify=False, but still the same result?..Can you please help me to sort this out..thanks

**Comment by ktbyers** [comment]
Are you in enable mode (privilege 15) i.e. does your user have permission to enter config mode.

Probably should call the `enable()` method in your code:

```python
net_connect = ConnectHandler(**cisco)
net_connect.enable
...
```

Also which version of Netmiko?

**Comment by jayspalma** [comment]
the privilege level fixed it. Thanks you for the quick reply.
