### ISSUE TITLE
Connection to device timed-out

### ISSUE THREAD

**Issue by Amit276** [ktbyers/netmiko#1739]
Hi am a beginner here 
So am getting this timeout error in this prog.
I have already changed the privilege level of the password on the switch.
Can anyone help me?
 

from netmiko import ConnectHandler

switch1 = {
    'device_type': 'cisco_ios',
    'ip': '172.168.122.175',
    'username': 'admin',
    'password': 'admin'
}

net_connect = ConnectHandler(**switch1)
output = net_connect.send_command('sh ip int br')
print(output)

config_commands = ['int loop 0', 'ip address 10.1.1.1 255.255.255.0']
output = net_connect.send_config_set(config_commands)
print(output)

Output error - 

Traceback (most recent call last):
  File "t.py", line 10, in <module>
    net_connect = ConnectHandler(**switch1)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/ssh_dispatcher.py", line 246, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 317, in __init__
    self._open()
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 322, in _open
    self.establish_connection()
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 890, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios 172.168.122.175:22

**Comment by ktbyers** [comment]
It looks like Netmiko can't reach this IP address and port:

```
Connection to device timed-out: cisco_ios 172.168.122.175:22
```
