### ISSUE TITLE
jump remote server doesnt work with netmiko

### ISSUE THREAD

**Issue by josht8716** [ktbyers/netmiko#1754]
Hi im new in netmiko, im trying to connect to jum server, which is connected to end devices in the office, its a redhat, this is the configuration in python.

import netmiko
from netmiko import ConnectHandler        

cisco_ios = {
    'device_type': 'cisco_ios',
    'ip': 'A.B.C.D',
    'username': 'user',
    'password': 'XXXXX',
    'session_log': 'output_server2.txt',
    'ssh_config_file': '~/.ssh/config',
    'global_delay_factor': 4
}
net_connect = ConnectHandler(**cisco_ios)
output = net_connect.send_command('show ip interface brief')
print (output)
net_connect.disconnect()

-Previous work: 
Confirm that the config works with a local server 
Confirm  ssh jump host works with the new remote server (E.F.G.H)

host jumphost                   
  IdentityFile ~/.ssh/id_rsa    
  IdentitiesOnly yes            
  user user
  hostname E.F.G.H

host * !jumphost
  ProxyCommand ssh jumphost nc %h %p

-error message:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 899, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/local/lib/python3.8/dist-packages/paramiko/client.py", line 368, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 10.15.1.1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "prueba_proxy_cisco_real.py", line 13, in <module>
    net_connect = ConnectHandler(**cisco_ios)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/ssh_dispatcher.py", line 266, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 327, in __init__
    self._open()
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 332, in _open
    self.establish_connection()
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 905, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.ssh_exception.NetmikoTimeoutException: Connection to device timed-out: cisco_ios A.B.C.D:22 

-Versions
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0] on linux
>>> paramiko.__version__
'2.7.1'
>>> netmiko.__version__
'3.1.1'

thanks in advance

**Comment by josht8716** [comment]
i found the fix, its different when we execute sudo and without sudo, so after give the permission to the folder it works with the local user.
