### ISSUE TITLE
import napalm error (No module named 'fcntl' / No module named 'clitable')

### ISSUE THREAD

**Issue by YMont** [ktbyers/netmiko#1757]
Hi , All
### import napalm
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 22:39:24) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

>>> import napalm

### Error
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ntc_templates\parse.py", line 5, in <module>
    from textfsm import clitable
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\textfsm\clitable.py", line 41, in <module>
    from textfsm import texttable
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\textfsm\texttable.py", line 42, in <module>
    from textfsm import terminal
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\textfsm\terminal.py", line 25, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import napalm
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\napalm\__init__.py", line 12, in <module>
    import napalm.junos
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\napalm\junos\__init__.py", line 18, in <module>
    from napalm.junos.junos import JunOSDriver  # noqa
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\napalm\junos\junos.py", line 30, in <module>
    from jnpr.junos import Device
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jnpr\junos\__init__.py", line 3, in <module>
    from jnpr.junos.factory.to_json import PyEzJSONEncoder
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jnpr\junos\factory\__init__.py", line 4, in <module>
    from jnpr.junos.factory.factory_loader import FactoryLoader
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jnpr\junos\factory\factory_loader.py", line 14, in <module>
    from jnpr.junos.factory.factory_cls import *
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jnpr\junos\factory\factory_cls.py", line 7, in <module>
    from jnpr.junos.factory.cmdtable import CMDTable
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jnpr\junos\factory\cmdtable.py", line 18, in <module>
    from ntc_templates import parse as ntc_parse
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ntc_templates\parse.py", line 7, in <module>
    import clitable
ModuleNotFoundError: No module named 'clitable'

### pip list (pip version 20.1.1)
napalm                3.0.1
netmiko               3.1.1

Very thanks.

**Comment by BapRx** [comment]
Hello,

As far as I know the module **fcntl** is not available on Windows.

If you're running Windows 10 you can install a linux shell with WSL else you can try this workaround: 
https://github.com/ktbyers/netmiko/issues/1679#issuecomment-616619818

**Comment by ktbyers** [comment]
@YMont This is a textfsm issue (i.e. they break windows support and now PyEz is importing TextFSM). So PyEZ is breaking Windows support because the import this.

The easy fix is:

```
pip install textfsm==0.4.1
pip install terminal
```

I think that should work.

**Comment by ktbyers** [comment]
This PR should fix the issue also:

https://github.com/google/textfsm/pull/82
