### ISSUE TITLE
i have made a program to get backup of multiple huawei devices but issue is that if one device is down or not responding it ends the progrma and not proceed to other devices.

### ISSUE THREAD

**Issue by musamakhalid88** [ktbyers/netmiko#1762]
i have made a program to get backup of multiple huawei devices but issue is that if one device is down or not responding it ends the program and not proceed to other devices.

below 192.168.56.5 device is offline or not connected , for 56.2 it shows the output but on 56.5 it gives error and end the program and not go to other device 56.3.

i have searched for solution but not find any.

from netmiko import ConnectHandler

ips = ["192.168.56.2" , "192.168.56.5", "192.168.56.3"]

for ip in ips:
    devices = {
    'device_type': 'huawei',
    'ip': ip,
    'username': 'admin',
    'password': '1111',
}
    print("SSH to " ,ip)
    net_connect = ConnectHandler(**devices)
    print(net_connect.find_prompt())
    output = net_connect.send_command('disp ip inter bri')
    print(output)
    

error :

Traceback (most recent call last):
  File "C:\Users\M.USAMA\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 899, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "C:\Users\M.USAMA\AppData\Local\Programs\Python\Python38-32\lib\site-packages\paramiko\client.py", line 349, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "C:\Users\M.USAMA\AppData\Local\Programs\Python\Python38-32\lib\site-packages\paramiko\util.py", line 283, in retry_on_signal
    return function()
  File "C:\Users\M.USAMA\AppData\Local\Programs\Python\Python38-32\lib\site-packages\paramiko\client.py", line 349, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/M.USAMA/Downloads/Compressed/original_5/netmiko_config_backup2.py", line 14, in <module>
    net_connect = ConnectHandler(**devices)
  File "C:\Users\M.USAMA\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\ssh_dispatcher.py", line 266, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\M.USAMA\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 327, in __init__
    self._open()
  File "C:\Users\M.USAMA\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 332, in _open
    self.establish_connection()
  File "C:\Users\M.USAMA\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 905, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.ssh_exception.NetmikoTimeoutException: Connection to device timed-out: huawei 192.168.56.5:22

**Comment by musamakhalid88** [comment]
i have tried this also but still same issue

from netmiko import ConnectHandler
from netmiko.ssh_exception import NetMikoTimeoutException


ips = ["192.168.56.2" , "192.168.56.5", "192.168.56.3"]

for ip in ips:
    devices = {
    'device_type': 'huawei',
    'ip': ip,
    'username': 'netadmin',
    'password': '1111',
}
    print("SSH to " ,ip)
    try:
        net_connect = ConnectHandler(**devices)
    except (NetmikoTimeoutException):
        print('Timeout to device: ' + ip)
        continue
    except Exception as unknown_error:
        print("some other error")
        continue
    net_connect = ConnectHandler(**devices)
    print(net_connect.find_prompt())
    output = net_connect.send_command('disp ip inter bri')
    print(output)
    #saveoutput = open(ip +".txt" , 'w+')
    #saveoutput.write(output)
    #saveoutput.close()

**Comment by musamakhalid88** [comment]
i was calling exceptions wrongly below metion i have edit on my script  and now exceptions are working fine.


from netmiko import ConnectHandler
from netmiko.ssh_exception import NetMikoTimeoutException
from paramiko.ssh_exception import SSHException
from netmiko.ssh_exception import AuthenticationException
