### ISSUE TITLE
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available

### ISSUE THREAD

**Issue by diptajeet** [ktbyers/netmiko#1768]
Facing issues with Netmiko v3.1.1, the same piece of code works fine on Netmiko v2.4.2 for Catalyst device using ntc_config_command. Is this something to do with the terminal width setup?

Below is the traceback:

  module_stderr: |-
    Traceback (most recent call last):
      File "/usr/lib/python3.8/site-packages/paramiko/channel.py", line 699, in recv
        out = self.in_buffer.read(nbytes, self.timeout)
      File "/usr/lib/python3.8/site-packages/paramiko/buffered_pipe.py", line 164, in read
        raise PipeTimeout()
    paramiko.buffered_pipe.PipeTimeout

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3.8/site-packages/netmiko/base_connection.py", line 550, in _read_channel_expect
        new_data = self.remote_conn.recv(MAX_BUFFER)
      File "/usr/lib/python3.8/site-packages/paramiko/channel.py", line 701, in recv
        raise socket.timeout()
    socket.timeout

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<stdin>", line 102, in <module>
      File "<stdin>", line 94, in _ansiballz_main
      File "<stdin>", line 40, in invoke_module
      File "/usr/lib/python3.8/runpy.py", line 207, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_ntc_config_command_payload_3zpm2o86/ansible_ntc_config_command_payload.zip/ansible/modules/ntc_config_command.py", line 273, in <module>
      File "/tmp/ansible_ntc_config_command_payload_3zpm2o86/ansible_ntc_config_command_payload.zip/ansible/modules/ntc_config_command.py", line 257, in main
      File "/usr/lib/python3.8/site-packages/netmiko/base_connection.py", line 1766, in send_config_set
        new_output = self.read_until_pattern(pattern=pattern)
      File "/usr/lib/python3.8/site-packages/netmiko/base_connection.py", line 627, in read_until_pattern
        return self._read_channel_expect(*args, **kwargs)
      File "/usr/lib/python3.8/site-packages/netmiko/base_connection.py", line 560, in _read_channel_expect
        raise NetmikoTimeoutException(
    netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

**Comment by ktbyers** [comment]
You need to test it outside of Ansible and create a Python exception directly from that. Please post your Python code.

Also I will probably need your Netmiko log file.

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by diptajeet** [comment]
I was able to fix it by updating the ntc_config_command, thanks for your reply!

**Comment by ktbyers** [comment]
@diptajeet And the fix was?
