### ISSUE TITLE
Cannot Seem to get this code working!!  Please help!!

### ISSUE THREAD

**Issue by reuben3010** [ktbyers/netmiko#1801]
Code:

from netmiko import ConnectHandler
from getpass import getpass
import time
from datetime import datetime
start_time = datetime.now()
start = time.time()
host = input('Enter ip address: ')
device = {'device_type': 'cisco_asa',
          'host': host,
          'username':'reuben',
          'password':'cisco',
          'port': '22',
          'secret': 'cisco',
          'verbose': True}

net_connect = ConnectHandler(**device)
cmd = 'copy disk0:ospf7.txt disk0:ospf12.txt'
#expect_string = (r'Source filename', r'Destination filename')
output = net_connect.send_command(cmd)
if 'Source filename' in output:
    output += net_connect.send_command('\n')
if 'Destination filename' in output:
    output += net_connect.send_command('\n')

#output += net_connect.send_command('\n', '\n', expect_string=r'#', delay_factor=2)
print(output)
#output = net_connect.send_command('show int ip brie')
print(output)

error:
C:\network_automation_2\venv\Scripts\python.exe C:/network_automation_2/testing_commands_netmiko.py
Enter ip address: 10.7.250.54
SSH connection established to 10.7.250.54:22
Interactive SSH session established
Traceback (most recent call last):
  File "C:/network_automation_2/testing_commands_netmiko.py", line 19, in <module>
    output = net_connect.send_command(cmd)
  File "C:\network_automation_2\venv\lib\site-packages\netmiko\cisco\cisco_asa_ssh.py", line 61, in send_command
    output = super(CiscoAsaSSH, self).send_command(*args, **kwargs)
  File "C:\network_automation_2\venv\lib\site-packages\netmiko\base_connection.py", line 1337, in send_command
    search_pattern
OSError: Search pattern never detected in send_command_expect: LABASA1\#

Process finished with exit code 1

**Comment by reuben3010** [comment]
I solved the issue. All is working now. Thanks Kirk for the knowledge. Let me know when you are having specials for your classes!! :)
