### ISSUE TITLE
Netmiko - commands from config_set only executing on first device in list

### ISSUE THREAD

**Issue by cclark0831** [ktbyers/netmiko#1814]
Commands in file getting sent to first device in list and printing to scree fine, but not executing against other devices in list.

```
#!/usr/bin/env python3

from netmiko import ConnectHandler

iosv_l2_core1 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.166',
    'username': 'chris',
    'password': 'cisco',
}

iosv_l2_core2 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.167',
    'username': 'chris',
    'password': 'cisco',
}

iosv_l2_s1 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.168',
    'username': 'chris',
    'password': 'cisco',
}

iosv_l2_s2 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.169',
    'username': 'chris',
    'password': 'cisco',
}

iosv_l2_s3 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.170',
    'username': 'chris',
    'password': 'cisco',
}

with open('iosv_l2_config') as f:
	lines = f.read().splitlines()
        print(lines)

all_devices = [iosv_l2_s3, iosv_l2_s2, iosv_l2_s1, iosv_l2_core2, iosv_l2_core1]

for devices in all_devices:
	net_connect = ConnectHandler(**devices)
	output = net_connect.send_config_set(lines)
	print(output)

```
Contents of the file called.

```
vlan 2
int range g2/0 - 3
switchport mode access
switchport access vlan 2
int range g0/0 - 3
switchport trunk encapsulation dot1q
switchport mode trunk
switchport nonegotiate
switchport trunk allowed vlan 1,2
int range g1/0 - 3
switchport trunk encapsulation dot1q
switchport mode trunk
switchport nonegotiate
switchport trunk allowed vlan 1,2
```
I'm sure that I'm missing something simple (hopefully).  In advance, thanks for your assistance.

**Comment by ktbyers** [comment]
What does execution of your script show?

**Comment by cclark0831** [comment]
I'm not entirely sure if I've integrated what you emailed me correctly, but now the script is failing at the "_except NetmikoAuthenticationException_" line.  

Here is the updated code:
```
#!/usr/bin/env python3

from netmiko import ConnectHandler
from netmiko import NetmikoAuthenticationException

iosv_l2_core1 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.166',
    'username': 'chris',
    'password': 'cisco',
}

iosv_l2_core2 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.167',
    'username': 'chris',
    'password': 'cisco',
}

iosv_l2_s1 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.168',
    'username': 'chris',
    'password': 'cisco',
}

iosv_l2_s2 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.169',
    'username': 'chris',
    'password': 'cisco',
}

iosv_l2_s3 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.170',
    'username': 'chris',
    'password': 'cisco',
}

with open('iosv_l2_config') as f:
	lines = f.read().splitlines()
print(lines)

all_devices = [iosv_l2_s3, iosv_l2_s2, iosv_l2_s1, iosv_l2_core2, iosv_l2_core1]

for devices in all_devices:
	net_connect = ConnectHandler(**devices)
	output = net_connect.send_config_set(lines)
except NetmikoAuthenticationException:
	print("Exception handled")
$ python foo.py 
Exception Handled 

print(output)
```
I received this feedback from you earlier:

```
It looks like you are getting this exception:

netmiko.ssh_exception.NetmikoAuthenticationException

So you should be importing/using that from Netmiko.

from netmiko import ConnectHandler

from netmiko import NetmikoAuthenticationException

 

device = {

    "device_type": "cisco_ios",

    "host": "cisco1.lasthop.io",

    "username": "pyclass",

    "password": "bogus",

}

 

try:

    net_connect = ConnectHandler(**device)

except NetmikoAuthenticationException:

    print("Exception handled")

$ python foo.py 

Exception handled
```
I'm guessing that I've not integrated your code recommendation into my code correctly.

**Comment by ktbyers** [comment]
```
for devices in all_devices:
    try:
	net_connect = ConnectHandler(**devices)
	output = net_connect.send_config_set(lines)
    except NetmikoAuthenticationException:
	print("Exception handled")
```

**Comment by cclark0831** [comment]
Still stopping on the except statement.
```
root@ubuntu18:~# ./netssh4.py
  File "./netssh4.py", line 51
    except NetmikoAuthenticationException:
         ^
SyntaxError: invalid syntax
root@ubuntu18:~#
```

**Comment by cclark0831** [comment]
The new code looks like this:
```
with open('iosv_l2_config') as f:
	lines = f.read().splitlines()
print(lines)

all_devices = [iosv_l2_s3, iosv_l2_s2, iosv_l2_s1, iosv_l2_core2, iosv_l2_core1]

for devices in all_devices:
	net_connect = ConnectHandler(**devices)
	output = net_connect.send_config_set(lines)
	print(output)
except NetmikoAuthenticationException:
	print("Exception handled")
 
```

**Comment by ktbyers** [comment]
Okay, you are not putting what I put above i.e. you are dropping the `try` statement.

**Comment by cclark0831** [comment]
Ok, for some reason I thought that "try" was a note and not part of the code :)

I added that in and it works for switch 3 and 2 now.  It timed out again.  Thanks for taking the extra time on this.

Below you can see that it's getting further than switch 3 now, but still dying.

```
root@ubuntu18:~# ./netssh4.py
['vlan 2', 'int range g2/0 - 3', 'switchport mode access', 'switchport access vlan 2', 'int range g0/0 - 3', 'switchport trunk encapsulation dot1q', 'switchport mode trunk', 'switchport nonegotiate', 'switchport trunk allowed vlan 1,2', 'int range g1/0 - 3', 'switchport trunk encapsulation dot1q', 'switchport mode trunk', 'switchport nonegotiate', 'switchport trunk allowed vlan 1,2', '']
config term
Enter configuration commands, one per line.  End with CNTL/Z.
S3(config)#vlan 2
S3(config-vlan)#int range g2/0 - 3
S3(config-if-range)#switchport mode access
S3(config-if-range)#switchport access vlan 2
S3(config-if-range)#int range g0/0 - 3
S3(config-if-range)#switchport trunk encapsulation dot1q
S3(config-if-range)#switchport mode trunk
S3(config-if-range)#switchport nonegotiate
S3(config-if-range)#switchport trunk allowed vlan 1,2
S3(config-if-range)#int range g1/0 - 3
S3(config-if-range)#switchport trunk encapsulation dot1q
S3(config-if-range)#switchport mode trunk
S3(config-if-range)#switchport nonegotiate
S3(config-if-range)#switchport trunk allowed vlan 1,2
S3(config-if-range)#
S3(config-if-range)#end
S3#
config term
Enter configuration commands, one per line.  End with CNTL/Z.
S2(config)#vlan 2
S2(config-vlan)#int range g2/0 - 3
S2(config-if-range)#switchport mode access
S2(config-if-range)#switchport access vlan 2
S2(config-if-range)#int range g0/0 - 3
S2(config-if-range)#switchport trunk encapsulation dot1q
S2(config-if-range)#switchport mode trunk
S2(config-if-range)#switchport nonegotiate
S2(config-if-range)#switchport trunk allowed vlan 1,2
S2(config-if-range)#int range g1/0 - 3
S2(config-if-range)#switchport trunk encapsulation dot1q
S2(config-if-range)#switchport mode trunk
S2(config-if-range)#switchport nonegotiate
S2(config-if-range)#switchport trunk allowed vlan 1,2
S2(config-if-range)#
S2(config-if-range)#end
S2#
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 550, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./netssh4.py", line 50, in <module>
    output = net_connect.send_config_set(lines)
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 1766, in send_config_set
    new_output = self.read_until_pattern(pattern=pattern)
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 627, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 561, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.
root@ubuntu18:~#
```

**Comment by ktbyers** [comment]
Probably set `global_delay_factor` on the devices:

```python
iosv_l2_s3 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.170',
    'username': 'chris',
    'password': 'cisco',
    'global_delay_factor': 2,     # or 4 if 2 doesn't work
}
```
