### ISSUE TITLE
NetmikoTimeoutException: Connection to device timed-out

### ISSUE THREAD

**Issue by klbnet** [ktbyers/netmiko#1820]
Script: 
from netmiko import ConnectHandler
from getpass import getpass

net_connect = ConnectHandler(
    device_type="cisco_ios",
    host="ed4.nyc2.cs",
    username="ipengineering",
    password=getpass(),
)

print(net_connect.find_prompt())
net_connect.disconnect()

Errors: 
$ python3 sshnetmiko.py
Password:
Traceback (most recent call last):
  File "/home/klobue/.local/lib/python3.6/site-packages/netmiko/base_connection.py", line 899, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/klobue/.local/lib/python3.6/site-packages/paramiko/client.py", line 368, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 172.22.111.24

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sshnetmiko.py", line 8, in <module>
    password=getpass(),
  File "/home/klobue/.local/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 266, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/klobue/.local/lib/python3.6/site-packages/netmiko/base_connection.py", line 327, in __init__
    self._open()
  File "/home/klobue/.local/lib/python3.6/site-packages/netmiko/base_connection.py", line 332, in _open
    self.establish_connection()
  File "/home/klobue/.local/lib/python3.6/site-packages/netmiko/base_connection.py", line 905, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.ssh_exception.NetmikoTimeoutException: Connection to device timed-out: cisco_ios ed4.nyc2.cs:22

**Comment by ktbyers** [comment]
It looks like nothing is listening on `ed4.nyc2.cs` port 22 (i.e. there is nothing responding on SSH at that host).
