### ISSUE TITLE
SSH connection to Extreme network switch with Python 

### ISSUE THREAD

**Issue by inotehp** [ktbyers/netmiko#1825]
Hi, 

I am a network admin, and I would like to write a script to connect to extreme network switches and send a command.
I have tried this to test the first step (SSH connection) : 

from netmiko import ConnectHandler
from getpass import getpass

password = getpass()

extreme = {
    "device_type": "extreme",
    "host": "X.X.X.X",
    "username": "XXXX",
    "password": "XXXX",
}

net_connect = ConnectHandler(*extreme)
print(net_connect.find_prompt())
net_connect.disconnect()

Can you help me please ? I am new in python

Thanks a lot

**Comment by ktbyers** [comment]
Yes, and what happened when you try to execute that?

**Comment by ktbyers** [comment]
This line would need to be double start i.e.:

```python
net_connect = ConnectHandler(**extreme)
```

**Comment by inotehp** [comment]
Hi, 

I have done the change for **extreme. When I execute the script, this is what happens : 

[root@****** tftpboot]# python3 test.py
Password:
Exception: Error reading SSH protocol banner
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 609, in _read_timeout
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 2039, in run
    self._check_banner()
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 2216, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 609, in _read_timeout
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 13, in <module>
    net_connect = ConnectHandler(**extreme)
  File "/usr/local/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 266, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 327, in __init__
    self._open()
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 332, in _open
    self.establish_connection()
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 899, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 406, in connect
    t.start_client(timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 660, in start_client
    raise e
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 2039, in run
    self._check_banner()
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 2216, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner


Thanks for your help

**Comment by ktbyers** [comment]
Did you search on that error and look for "Netmiko Error reading SSH protocol banner"

For example:

https://github.com/ktbyers/netmiko/issues/1507
