### ISSUE TITLE
Return Telnet test result to Python from a Cisco device

### ISSUE THREAD

**Issue by neaco1134t** [ktbyers/netmiko#1836]
Hi Folks! Seeking help from Netmiko experts.
 
I'm quite new to Python and Netmiko and I'm encountering an issue. I'm trying to return a telnet result to Python but it's not doing it successfully. Below is the result I'd like to return.

![image](https://user-images.githubusercontent.com/64463159/87007695-3f37ef00-c1f5-11ea-9f60-e13f2a080519.png)

I suspect that it's with the termination of the telnet that's not working since it's returning the search pattern detected error. I've tried doing write_channel() with several ASCII combinations but to no avail. Actual termination happens when doing several ```ctrl-c``` and then hitting ```Enter``` once or twice. Script and error are shown below. I already tried following the solutions in #1316 and #1317.
Appreciating all your help on this. Thanks

``` 
device = ConnectHandler(device_type=platform, ip=switch-a, username=username, password=password, secret=password)
                        output = device.send_command('terminal length 0')
                        output = device.send_command('enable')
                        sw_telnet_output = device.send_command('telnet ' + ip_add + ' ' + telnet_port + ' ' + '/source-interface vlan ' + row[1], delay_factor=1)
                        device.write_channel('\x03' + '\x03' + '\x03' + '\x03' + '\n' + '\n')
                        # ---- Tried multiple write channels as well. Also tried '\x1d', '\x036' etc.
                        device.write_channel('\x03')
                        device.write_channel('\x03')
                        device.write_channel('\x03')
                        device.write_channel('\x03')
                        device.write_channel('\n')
                        device.write_channel('\n')'''
                        time.sleep(0.1)
                        sw_telnet_output = device.read_channel()
                        device.clear_buffer()
                        print(sw_telnet_output) 
```

Error message:
````
Traceback (most recent call last):
  File "tshoot.py", line 169, in <module>
    sw_telnet_output = device.send_command('telnet ' + ip_add + ' ' + telnet_por
t + ' ' + '/source-interface vlan ' + row[1], delay_factor=1)
  File "D:\python\chatbot\lib\site-packages\netmiko\base_connection.py", line 129
5, in send_command
    search_pattern
OSError: Search pattern never detected in send_command_expect: switch\-a\#
```

**Comment by neaco1134t** [comment]
Still looking forward to get past this issue..

**Comment by neaco1134t** [comment]
Found the resolution for this! Below code resolved it. Closing the issue now.

```
from netmiko import ConnectHandler
import csv
import os
import sys
import netmiko


connection = netmiko.ConnectHandler(ip="10.1.115.146", device_type="cisco_ios", username="admin", password="cisco")
output = connection.send_command("telnet 8.8.8.8 443 /source-interface vlan 7", expect_string=r"Trying")
connection.disconnect()
print(output)
```
