### ISSUE TITLE
Too many open files in .ssh/config

### ISSUE THREAD

**Issue by keeganb2000** [ktbyers/netmiko#1840]
I'm getting facts on 2587 devices(ios) and at a certain point the whole thing just blows up and all queries fail. It looks as if netmiko is opening .ssh/config for every connection it's making and after 1024 the whole thing just bombs out.  I'm guessing it's after 1024 as ulimit -n  show that value as my limit. The stack trace from one device is below, this is the same for all failures. Any help on how I can get around this. I'd rather not have to up the limit of open files on my server if possible.

I'm getting facts on 2587 devices(ios) and at a certain point the whole thing just blows up and all queries fail. #nornir helped me narrow it down and it looks as if netmiko is opening .ssh/config for every connection it's making and after 1024 the whole thing just bombs out.  I'm guessing it's after 1024 as ulimit -n  show that value as my limit. The stack trace from one device is below, this is the same for all failures. Any help on how I can get around this. I'd rather not have to up the limit of open files on my server if possible.

>
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/nornir/core/task.py", line 85, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.6/dist-packages/nornir/plugins/tasks/networking/napalm_get.py", line 49, in napalm_get
    device = task.host.get_connection("napalm", task.nornir.config)
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/inventory.py", line 302, in get_connection
    extras=conn.extras,
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/inventory.py", line 352, in open_connection
    configuration=configuration,
  File "/usr/local/lib/python3.6/dist-packages/nornir/plugins/connections/napalm.py", line 51, in open
    connection.open()
  File "/usr/local/lib/python3.6/dist-packages/napalm/ios/ios.py", line 169, in open
    device_type, netmiko_optional_args=self.netmiko_optional_args
  File "/usr/local/lib/python3.6/dist-packages/napalm/base/base.py", line 96, in _netmiko_open
    **netmiko_optional_args
  File "/usr/local/lib/python3.6/dist-packages/netmiko/ssh_dispatcher.py", line 246, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 318, in __init__
    self._open()
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 323, in _open
    self.establish_connection()
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 880, in establish_connection
    ssh_connect_params = self._connect_params_dict()
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 833, in _connect_params_dict
    conn_dict = self._use_ssh_config(conn_dict)
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 779, in _use_ssh_config
    with io.open(full_path, "rt", encoding="utf-8") as f:
OSError: [Errno 24] Too many open files: '/home/bkeegan/.ssh/config'
>

**Comment by ktbyers** [comment]
Was fixed by closing the TCP connections in Nornir.

Note, both files and TCP-connections count as "file references" and Nornir by default keeps the SSH-connections open so there would be a build-up of TCP-connections.

The solution was to close the TCP connections.

```python
def get_facts(self, task):
        """
        Method definition: get facts and return multi result.
        """
        try:
            facts = task.run(task=napalm_get, getters=["facts"])
            print('{}\tFacts grabbed'.format(task.host))
            task.host.close_connection("napalm")
            return facts
       ...
```
