### ISSUE TITLE
Error while staging code on ASA

### ISSUE THREAD

**Issue by coolblue7007** [ktbyers/netmiko#1845]
Hi,

This is my first ever post, sorry if this question is a dumb one. I am able to upload a txt file to disk0: on ASA using your one touch script. But when I try to stage or upload the actual code. I get the below error related to scp_connection. Can you please help here? 

Below is the error:
Traceback (most recent call last):
  File "102.py", line 80, in main
    scp_transfer.transfer_file()
  File "/usr/local/lib/python3.6/site-packages/netmiko/scp_handler.py", line 339, in transfer_file
    self.put_file()
  File "/usr/local/lib/python3.6/site-packages/netmiko/scp_handler.py", line 352, in put_file
    self.scp_conn.scp_transfer_file(self.source_file, destination)
  File "/usr/local/lib/python3.6/site-packages/netmiko/scp_handler.py", line 41, in scp_transfer_file
    self.scp_client.put(source_file, dest_file)
  File "/usr/local/lib/python3.6/site-packages/scp.py", line 166, in put
    self._send_files(files)
  File "/usr/local/lib/python3.6/site-packages/scp.py", line 271, in _send_files
    self._send_file(fl, name, mode, size)
  File "/usr/local/lib/python3.6/site-packages/scp.py", line 297, in _send_file
    self._recv_confirm()
  File "/usr/local/lib/python3.6/site-packages/scp.py", line 370, in _recv_confirm
    raise SCPException('Invalid response from server', msg)
scp.SCPException: ('Invalid response from server', b'!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\x00')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "102.py", line 125, in <module>
    main()
  File "102.py", line 115, in main
    except (SSHException):
NameError: name 'SSHException' is not defined

Code:
Attached
[102.txt](https://github.com/ktbyers/netmiko/files/4916870/102.txt)

**Comment by ktbyers** [comment]
@coolblue7007 You are not importing SSHException so your code fails with a name error.
