### ISSUE TITLE
Make privilege failure errors clearer (trying to go into configuration mode with insufficient privileges)

### ISSUE THREAD

**Issue by gururajansrao** [ktbyers/netmiko#1850]
I am getting below error message while running my code in python3/Netmiko2.4.2. Please help as I am new to python. Its a Cisco CSR1000v device running 16.6.6 code.

```python
from netmiko import ConnectHandler

csr_python1 = {
    'device_type': 'cisco_ios',
    'ip': '2.2.1.51',
    'username': 'cisco',
    'password': 'cisco',
    'secret': 'cisco'
}

csr_python2 = {
    'device_type': 'cisco_ios',
    'ip': '2.2.1.52',
    'username': 'cisco',
    'password': 'cisco',
    'secret': 'cisco',
    'global_delay_factor': 4
}

csr_python3 = {
    'device_type': 'cisco_ios',
    'ip': '2.2.1.53',
    'username': 'cisco',
    'password': 'cisco',
    'secret': 'cisco',
    'global_delay_factor': 4
}

with open('config') as f:
    lines = f.read().splitlines()
print (lines)

all_devices = [csr_python1, csr_python2, csr_python3]

for devices in all_devices:
    print("#################################")
    print ("Configuring Router ")
    net_connect = ConnectHandler(**devices)
    output = net_connect.send_config_set(lines)
    print (output)
```

!!!!!!!!!!!!!!!!!!! Error as below
```
root@Root-CA:~/Guru-Python# python3 net_config_from_file.py
['snmp-server community python1 RO', 'snmp-server community python2 RW', '', 'ntp server 2.2.1.100', '', 'clock timezone IST -5 30', '', 'service timestamps debug datetime msec localtime ', 'service timestamps log datetime msec localtime']
#################################
Configuring Router 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 534, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "net_config_from_file.py", line 41, in <module>
    output = net_connect.send_config_set(lines)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 1607, in send_config_set
    output = self.config_mode(*cfg_mode_args)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/cisco_base_connection.py", line 50, in config_mode
    config_command=config_command, pattern=pattern
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 1514, in config_mode
    if not self.check_config_mode():
  File "/usr/local/lib/python3.5/dist-packages/netmiko/cisco/cisco_ios.py", line 32, in check_config_mode
    check_string=check_string, pattern=pattern
  File "/usr/local/lib/python3.5/dist-packages/netmiko/cisco_base_connection.py", line 38, in check_config_mode
    check_string=check_string, pattern=pattern
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 1501, in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 609, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 543, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.
root@Root-CA:~/Guru-Python#

**Comment by gururajansrao** [comment]
Looked at similar issue #1245 and Priv 15 is not an issue in my case.
```
CSR-Python-1#sh running-config | in user
username cisco privilege 15 password 0 cisco
CSR-Python-1#

**Comment by ktbyers** [comment]
@gururajansrao Can you include the log file of what happens when it fails?

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by gururajansrao** [comment]
Thank you @ktbyers 

After enabling debug more, understood that "enable" mode was missing. My bad! it works fine now. 

Please find the logs.

```
root@Root-CA:~/Guru-Python# cat test.log
DEBUG:paramiko.transport:starting thread (client mode): 0x40806a58
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.7.1
DEBUG:paramiko.transport:Remote version/idstring: SSH-1.99-Cisco-1.25
INFO:paramiko.transport:Connected (version 1.99, client Cisco-1.25)
DEBUG:paramiko.transport:kex algos:['diffie-hellman-group-exchange-sha1', 'diffie-hellman-group14-sha1'] server key:['ssh-rsa'] client encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr'] server encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr'] client mac:['hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1', 'hmac-sha1-96'] server mac:['hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1', 'hmac-sha1-96'] client compress:['none'] server compress:['none'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group-exchange-sha1
DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:Got server p (2048 bits)
DEBUG:paramiko.transport:kex engine KexGex specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for 2.2.1.51: b'8d4831556c1aabb03d213f624611ac67'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 4096 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:read_channel: 


CSR-Python-1>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
CSR-Python-1>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:In disable_paging
DEBUG:netmiko:Command: terminal length 0

DEBUG:netmiko:write_channel: b'terminal length 0\n'
DEBUG:netmiko:Pattern is: CSR\-Python\-1
DEBUG:netmiko:_read_channel_expect read_data: t
DEBUG:netmiko:_read_channel_expect read_data: erminal length 0
CSR-Python-1>
DEBUG:netmiko:Pattern found: CSR\-Python\-1 terminal length 0
CSR-Python-1>
DEBUG:netmiko:terminal length 0
CSR-Python-1>
DEBUG:netmiko:Exiting disable_paging
DEBUG:netmiko:write_channel: b'terminal width 511\n'
DEBUG:netmiko:Pattern is: CSR\-Python\-1
DEBUG:netmiko:_read_channel_expect read_data: term
DEBUG:netmiko:_read_channel_expect read_data: inal width 511
CSR-Python-1>
DEBUG:netmiko:Pattern found: CSR\-Python\-1 terminal width 511
CSR-Python-1>
DEBUG:netmiko:read_channel: 
DEBUG:paramiko.transport:starting thread (client mode): 0x7ef6da58
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.7.1
DEBUG:paramiko.transport:Remote version/idstring: SSH-1.99-Cisco-1.25
INFO:paramiko.transport:Connected (version 1.99, client Cisco-1.25)
DEBUG:paramiko.transport:kex algos:['diffie-hellman-group-exchange-sha1', 'diffie-hellman-group14-sha1'] server key:['ssh-rsa'] client encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr'] server encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr'] client mac:['hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1', 'hmac-sha1-96'] server mac:['hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1', 'hmac-sha1-96'] client compress:['none'] server compress:['none'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group-exchange-sha1
DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:Got server p (2048 bits)
DEBUG:paramiko.transport:kex engine KexGex specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for 2.2.1.51: b'8d4831556c1aabb03d213f624611ac67'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 4096 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:read_channel: 


CSR-Python-1>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
CSR-Python-1>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:In disable_paging
DEBUG:netmiko:Command: terminal length 0

DEBUG:netmiko:write_channel: b'terminal length 0\n'
DEBUG:netmiko:Pattern is: CSR\-Python\-1
DEBUG:netmiko:_read_channel_expect read_data: ter
DEBUG:netmiko:_read_channel_expect read_data: minal length 0
CSR-Python-1>
DEBUG:netmiko:Pattern found: CSR\-Python\-1 terminal length 0
CSR-Python-1>
DEBUG:netmiko:terminal length 0
CSR-Python-1>
DEBUG:netmiko:Exiting disable_paging
DEBUG:netmiko:write_channel: b'terminal width 511\n'
DEBUG:netmiko:Pattern is: CSR\-Python\-1
DEBUG:netmiko:_read_channel_expect read_data: term
DEBUG:netmiko:_read_channel_expect read_data: inal width 511
CSR-Python-1>
DEBUG:netmiko:Pattern found: CSR\-Python\-1 terminal width 511
CSR-Python-1>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:Pattern is: #
DEBUG:netmiko:_read_channel_expect read_data: 
CSR-Python-1>
root@Root-CA:~/Guru-Python#

**Comment by ktbyers** [comment]
Leave this issue open...I need to make the error message clearer here.
