### ISSUE TITLE
Nemiko failed to enter enable or configuration mode when TACACS connection takes time to fall back to local authorization

### ISSUE THREAD

**Issue by chriseizus** [ktbyers/netmiko#1857]
All our network devices are using cisco tacacs authentication and authorization.
Every command will need to go to tacacs server for authentication and authorization verification before apply on the device
Whenever the tacacs server is not available, there will be a "hostname#" showing delay, and the original local credential will be used as fallback credential.
however, the default hidden "enable" or "config t" command doesn't accept this delay and just simply failed the script no matter if the delay_factor or global_delay_factor is set.

Steps to reproduce:
1. config the local login username
2. config a dummy tacacs entry for AAA to simulate failing of the tacacs as following

aaa new-model

aaa group server tacacs+ TACACS_SERVERS
server-private 100.100.100.100 key dummy_key

aaa authentication login default group TACACS_SERVERS local
aaa authentication enable default group TACACS_SERVERS enable
aaa authorization exec default group TACACS_SERVERS if-authenticated
aaa authorization commands 15 default group TACACS_SERVERS if-authenticated

3. try using netmiko to use local username/password to login to device and apply some command. It will fail to enter "enable" mode.
4. try using CLI ssh login manually, slow and delayed but works.

**Comment by ktbyers** [comment]
Can you include a log of a failure:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel


Kirk

**Comment by chriseizus** [comment]
As it shows in the log, due to the delay of entering enable mode and config mode, the device stuck at the > mode.
I have tested using manual ssh login, without any issue.

import logging
logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

from netmiko import ConnectHandler

net_connect = ConnectHandler(
    device_type='cisco_ios_ssh',
    ip='1.1.1.1', 
    username='admin', 
    password='cisco', 
    secret='cisco')

output = net_connect.send_config_set(["ip scp server enable"])
print(output)


DEBUG:paramiko.transport:starting thread (client mode): 0x569597c0
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.7.1
DEBUG:paramiko.transport:Remote version/idstring: SSH-1.99-Cisco-1.25
INFO:paramiko.transport:Connected (version 1.99, client Cisco-1.25)
DEBUG:paramiko.transport:kex algos:['diffie-hellman-group-exchange-sha1', 'diffie-hellman-group14-sha1'] server key:['ssh-rsa'] client encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr'] server encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr'] client mac:['hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1', 'hmac-sha1-96'] server mac:['hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1', 'hmac-sha1-96'] client compress:['none'] server compress:['none'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group-exchange-sha1
DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:Got server p (2048 bits)
DEBUG:paramiko.transport:kex engine KexGex specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for 1.1.1.1: b'0628c90a65ca0bd49724f55a74e25b41'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 4096 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 


Switch>
Switch>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
Switch>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is Switch>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:In disable_paging
DEBUG:netmiko:Command: terminal length 0

DEBUG:netmiko:write_channel: b'terminal length 0\n'
DEBUG:netmiko:Pattern is: terminal\ length\ 0
DEBUG:netmiko:_read_channel_expect read_data: t
DEBUG:netmiko:_read_channel_expect read_data: erminal length 0
Switch>
DEBUG:netmiko:Pattern found: terminal\ length\ 0 terminal length 0
Switch>
DEBUG:netmiko:terminal length 0
Switch>
DEBUG:netmiko:Exiting disable_paging
DEBUG:netmiko:write_channel: b'terminal width 511\n'
DEBUG:netmiko:Pattern is: terminal\ width\ 511
DEBUG:netmiko:_read_channel_expect read_data: t
DEBUG:netmiko:_read_channel_expect read_data: erminal width 511
Switch>
DEBUG:netmiko:Pattern found: terminal\ width\ 511 terminal width 511
Switch>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:Pattern is: #
DEBUG:netmiko:_read_channel_expect read_data: 

DEBUG:netmiko:_read_channel_expect read_data: Switch>

**Comment by ktbyers** [comment]
Which version of Netmiko are you using?

Also, can you post the full exception stack trace that you receive.

Thanks, Kirk

**Comment by chriseizus** [comment]
I'm using python3.8 with netmiko 3.1.1

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/netmiko/base_connection.py", line 550, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "netmiko_test.py", line 16, in <module>
    output = net_connect.send_config_set(["ip scp server enable"])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/netmiko/base_connection.py", line 1735, in send_config_set
    output += self.config_mode(*cfg_mode_args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/netmiko/cisco_base_connection.py", line 40, in config_mode
    return super().config_mode(config_command=config_command, pattern=pattern)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/netmiko/base_connection.py", line 1619, in config_mode
    if not self.check_config_mode():
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/netmiko/cisco/cisco_ios.py", line 29, in check_config_mode
    return super().check_config_mode(check_string=check_string, pattern=pattern)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/netmiko/cisco_base_connection.py", line 30, in check_config_mode
    return super().check_config_mode(check_string=check_string, pattern=pattern)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/netmiko/base_connection.py", line 1606, in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/netmiko/base_connection.py", line 627, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/netmiko/base_connection.py", line 560, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

**Comment by ktbyers** [comment]
Your code is not calling the `enable()` method.

You need to do this before you call `send_config_set()`

**Comment by chriseizus** [comment]
I tried your suggestion and it works.
So now question is why if there is no delaying, I don't need enable() at all and send_config_set automatically enter the enable mode?

Thanks

**Comment by ktbyers** [comment]
It will enter `config_mode()` automatically. It will not automatically elevate your privileges; you need to call `enable()` method for this.


Regards,

Kirk
