### ISSUE TITLE
Cisco ASA access-list issue

### ISSUE THREAD

**Issue by vkazimov** [ktbyers/netmiko#1874]
Hi.
I want to write access-list to Cisco ASA Firewall with send_config_set command.

**acl** = ["access-list inside_access_in line 1 extended permit ip 192.168.1.0 255.255.255.0 host 172.16.1.100", "access-list inside_access_in line 2 extended permit ip 192.168.1.0 255.255.255.0 host **172.16.2.100"]**

output = net_connect.send_config_set(acl)
print(output)

The following problem occur when i running script : 

Traceback (most recent call last):
  File "C:\Python\lib\site-packages\paramiko-2.7.1-py3.8.egg\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Python\lib\site-packages\paramiko-2.7.1-py3.8.egg\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\lib\site-packages\netmiko-3.1.0-py3.8.egg\netmiko\base_connection.py", line 550, in _read_channel_expect
  File "C:\Python\lib\site-packages\paramiko-2.7.1-py3.8.egg\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/Python/MyScripts/learning/test.py", line 57, in <module>
    output = net_connect.send_config_set(a)
  File "C:\Python\lib\site-packages\netmiko-3.1.0-py3.8.egg\netmiko\base_connection.py", line 1750, in send_config_set
  File "C:\Python\lib\site-packages\netmiko-3.1.0-py3.8.egg\netmiko\base_connection.py", line 627, in read_until_pattern
  File "C:\Python\lib\site-packages\netmiko-3.1.0-py3.8.egg\netmiko\base_connection.py", line 560, in _read_channel_expect
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

Process finished with exit code 1

-----------------------------------------

Debug code : 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'access-list inside_access_in line 1 extended permit ip 192.168.1.0 255.255.255.0 host 172.16.1.100\n'
DEBUG:netmiko:Pattern is: access\-list\ inside_access_in\ line\ 1\ extended\ permit\ ip\ 192\.168\.1\.0\ 255\.255\.255\.0\ host\ 172\.16\.1\.100
DEBUG:netmiko:_read_channel_expect read_data: a
DEBUG:netmiko:_read_channel_expect read_data: ccess-list inside_access_in line 1 extended permit ip 192.1<0x08><0x08><0x08><0x08><0x08><0x08><0x08><0x08><0x08><0x08><0x08><0x08><0x08><0x08><0x08><0x08><0x08><0x08><0x08>$n line 1 extended permit ip 192.16                         <0x08><0x08><0x08><0x08><0x08><0x08><0x08><0x08>8.1.0 255.255.255.0 host <0x08><0x08><0x08><0x08><0x08><0x08><0x08><0x08><0x08><0x08><0x08><0x08>$p 192.168.1.0 255.255.255.0 host 1                         <0x08><0x08><0x08><0x08><0x08><0x08><0x08><0x08><0x08>72.16.1.100<0x08><0x08><0x08><0x08><0x08><0x08><0x08><0x08><0x08><0x08><0x08><0x08><0x08><0x08>access-list inside_access_in line 1 extended permit ip 192.$<0x08><0x08><0x08><0x08>

Cisco-ASA(config)# 
DEBUG:paramiko.transport:EOF in transport thread

**Comment by vkazimov** [comment]
In Cisco ASA :
conf t
teminal width 300 (default is 80)
 
Problem solved

**Comment by ktbyers** [comment]
@vkazimov Yes, set the following argument in your Netmiko object creation:

`allow_auto_change=True`

```
        if self.allow_auto_change:
            try:
                self.send_config_set("terminal width 511")
            except ValueError:
                # Don't fail for the terminal width
                pass
```

Basically, Cisco ASA has the terminal width as a configuration command and some people didn't want this changed automatically so you say it is okay.
