### ISSUE TITLE
Connection to Cisco WLC 3504 failed

### ISSUE THREAD

**Issue by jifox** [ktbyers/netmiko#1887]
Hi,

There is a traceback when trying to connect to the Cisco WLC 3504.
Manual login is working from the same machine as expected.

```bash
$ ssh cisco@192.168.0.10


(Cisco Controller)
User: cisco
Password:*****
(Cisco Controller) show inventory

Burned-in MAC Address............................ 00:08:00:00:00:01
Maximum number of APs supported.................. 150
NAME: "Chassis"    , DESCR: "Cisco 3500 Series Wireless LAN Controller"
PID: AIR-CT3504-K9,  VID: V02,  SN: XXXXXXXXXXXX
```

## Source test.py

```python
from netmiko import ConnectHandler
import logging
logging.basicConfig(filename='logg.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

cisco_wlc_ssh = {
   'device_type': 'cisco_wlc_ssh',
   'host': '192.168.0.10',
   'username': 'cisco',
   'password': 'cisco',
   'banner_timeout': 30,
}

net_connect = ConnectHandler(**cisco_wlc_ssh)
net_connect.find_prompt()
```

## Program output

```bash
$ python test.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ansible/.vscode-server/extensions/ms-python.python-2020.7.96456/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/ansible/.vscode-server/extensions/ms-python.python-2020.7.96456/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/ansible/.vscode-server/extensions/ms-python.python-2020.7.96456/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "/usr/local/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/local/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ansible/devel/develop/nornir/test.py", line 14, in <module>
    net_connect = ConnectHandler(**cisco_wlc_ssh)
  File "/home/ansible/devel/develop/nornir/lib/python3.7/site-packages/netmiko/ssh_dispatcher.py", line 298, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/ansible/devel/develop/nornir/lib/python3.7/site-packages/netmiko/base_connection.py", line 341, in __init__
    self._open()
  File "/home/ansible/devel/develop/nornir/lib/python3.7/site-packages/netmiko/base_connection.py", line 346, in _open
    self.establish_connection()
  File "/home/ansible/devel/develop/nornir/lib/python3.7/site-packages/netmiko/base_connection.py", line 915, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/ansible/devel/develop/nornir/lib/python3.7/site-packages/paramiko/client.py", line 412, in connect
    server_key = t.get_remote_server_key()
  File "/home/ansible/devel/develop/nornir/lib/python3.7/site-packages/paramiko/transport.py", line 834, in get_remote_server_key
    raise SSHException("No existing session")
paramiko.ssh_exception.SSHException: No existing session

```

```log
DEBUG:paramiko.transport:starting thread (client mode): 0x3cd2c550
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.7.1
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-CISCO_WLC
INFO:paramiko.transport:Connected (version 2.0, client CISCO_WLC)
DEBUG:paramiko.transport:kex algos:['curve25519-sha256@libssh.org', 'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group14-sha1'] server key:['ssh-rsa', 'rsa-sha2-512', 'rsa-sha2-256', 'ecdsa-sha2-nistp256'] client encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] server encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] client mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] server mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] client compress:['none', 'zlib@openssh.com', 'zlib'] server compress:['none', 'zlib@openssh.com', 'zlib'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: curve25519-sha256@libssh.org
DEBUG:paramiko.transport:HostKey agreed: ecdsa-sha2-nistp256
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
DEBUG:paramiko.transport:Switch to new keys ...
```

## Environment Info

```bash
$ python --version
Python 3.7.4

 $ cat /etc/redhat-release 
CentOS Linux release 7.7.1908 (Core)

$ uname -a
Linux centos.local 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

```bash
$ pip install --upgrade netmiko
Requirement already up-to-date: netmiko in ./lib/python3.7/site-packages (3.2.0)
Requirement already satisfied, skipping upgrade: setuptools>=38.4.0 in ./lib/python3.7/site-packages (from netmiko) (49.2.1)
Requirement already satisfied, skipping upgrade: pyserial in ./lib/python3.7/site-packages (from netmiko) (3.4)
Requirement already satisfied, skipping upgrade: scp>=0.13.2 in ./lib/python3.7/site-packages (from netmiko) (0.13.2)
Requirement already satisfied, skipping upgrade: textfsm in ./lib/python3.7/site-packages (from netmiko) (1.1.0)
Requirement already satisfied, skipping upgrade: paramiko>=2.4.3 in ./lib/python3.7/site-packages (from netmiko) (2.7.1)
Requirement already satisfied, skipping upgrade: future in ./lib/python3.7/site-packages (from textfsm->netmiko) (0.18.2)
Requirement already satisfied, skipping upgrade: six in ./lib/python3.7/site-packages (from textfsm->netmiko) (1.15.0)
Requirement already satisfied, skipping upgrade: pynacl>=1.0.1 in ./lib/python3.7/site-packages (from paramiko>=2.4.3->netmiko) (1.4.0)
Requirement already satisfied, skipping upgrade: cryptography>=2.5 in ./lib/python3.7/site-packages (from paramiko>=2.4.3->netmiko) (3.0)
Requirement already satisfied, skipping upgrade: bcrypt>=3.1.3 in ./lib/python3.7/site-packages (from paramiko>=2.4.3->netmiko) (3.1.7)
Requirement already satisfied, skipping upgrade: cffi>=1.4.1 in ./lib/python3.7/site-packages (from pynacl>=1.0.1->paramiko>=2.4.3->netmiko) (1.14.1)
Requirement already satisfied, skipping upgrade: pycparser in ./lib/python3.7/site-packages (from cffi>=1.4.1->pynacl>=1.0.1->paramiko>=2.4.3->netmiko) (2.20)
```

**Comment by OzNetNerd** [comment]
This might have nothing to do with your issue, but filenames with the word `test` in them should be avoided. These filenames are used by testing tools like `pytest` so may confuse your IDE.

**Comment by jifox** [comment]
I just renamed the test.py to netmiko_wlc.py and executed the script with same results

**Comment by jifox** [comment]
I've added the output of ssh -v. Maybe something useful for further analyzing there?

```bash
$ ssh -v cisco@192.168.0.10
OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 58: Applying options for *
debug1: Connecting to 192.168.0.10 [192.168.0.10] port 22.
debug1: Connection established.
debug1: identity file /home/ansible/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /home/ansible/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/ansible/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/ansible/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/ansible/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/ansible/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/ansible/.ssh/id_ed25519 type 4
debug1: key_load_public: No such file or directory
debug1: identity file /home/ansible/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.4
debug1: Remote protocol version 2.0, remote software version CISCO_WLC
debug1: no match: CISCO_WLC
debug1: Authenticating to 192.168.0.10:22 as 'cisco'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: curve25519-sha256@libssh.org need=64 dh_need=64
debug1: kex: curve25519-sha256@libssh.org need=64 dh_need=64
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:KntFZjvMXzFeVdarGOSVtU5G7wHFNhnIpnrXwilTBM0
debug1: Host '192.168.0.10' is known and matches the ECDSA host key.
debug1: Found key in /home/ansible/.ssh/known_hosts:114
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentication succeeded (none).
Authenticated to 192.168.0.10 ([192.168.0.10]:22).
debug1: channel 0: new [client-session]
debug1: Entering interactive session.
debug1: pledge: network
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: Sending environment.
debug1: Sending env LANG = de_AT.UTF-8


(Cisco Controller) 
User: cisco
Password:*******
(Cisco Controller) >debug1: client_input_channel_req: channel 0 rtype keepalive@openssh.com reply 1
debug1: client_input_channel_req: channel 0 rtype keepalive@openssh.com reply 1
debug1: client_input_channel_req: channel 0 rtype keepalive@openssh.com reply 1
debug1: client_input_channel_req: channel 0 rtype keepalive@openssh.com reply 1
debug1: client_input_channel_req: channel 0 rtype keepalive@openssh.com reply 1
debug1: client_input_channel_req: channel 0 rtype keepalive@openssh.com reply 1
```

**Comment by jifox** [comment]
```text
Manufacturer's Name.............................. Cisco Systems Inc.
Product Name..................................... Cisco Controller
Product Version.................................. 8.5.161.6
RTOS Version..................................... 8.5.161.6
Bootloader Version............................... 8.5.103.0
Emergency Image Version.......................... 8.5.103.0

OUI File Last Update Time........................ N/A
Build Type....................................... DATA + WPS
```

Josef

**Comment by jifox** [comment]
$ pip install --upgrade netmiko
Requirement already up-to-date: netmiko in ./lib/python3.7/site-packages **(3.2.0)**

**Comment by ktbyers** [comment]
Does debugging SSH on the WLC when the Netmiko connection fails provide any clues?

Not really enough information here as to why it is failing...it is failing at the underlying Paramiko connection, but I don't see why your WLC would fail whereas other WLCs generally work.

I guess you could try to revert back to earlier versions of both the `cryptography` library and of the `paramiko` library and see if it just works.

**Comment by m6461** [comment]
Check show version in the WLC and use the corresponding device_type value in stead of 'cisco_wlc_ssh'. I got in to a similar problem (do not know the exact reason) and tried with 'cisco_xe' since the WLC was running cisco IOS XE software. It worked!

**Comment by jifox** [comment]
Hello

I've succeeded with downgrading to netmiko==2.4.2

Thanks for help

**Comment by ktbyers** [comment]
Hopefully, this PR fixes the underlying issue:

https://github.com/ktbyers/netmiko/pull/1897
