### ISSUE TITLE
Wipe and start over didn't help!

### ISSUE THREAD

**Issue by libaax** [ktbyers/netmiko#1891]
with only "inport netmiko" I get this! amazing!
Traceback (most recent call last):
  File "C:/Users/libaa/PycharmProjects/NewProject/netmiko_test.py", line 1, in <module>
    import netmiko
  File "C:\Users\libaa\PycharmProjects\NewProject\venv\lib\site-packages\netmiko\__init__.py", line 7, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "C:\Users\libaa\PycharmProjects\NewProject\venv\lib\site-packages\netmiko\ssh_dispatcher.py", line 2, in <module>
    from netmiko.a10 import A10SSH
  File "C:\Users\libaa\PycharmProjects\NewProject\venv\lib\site-packages\netmiko\a10\__init__.py", line 1, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "C:\Users\libaa\PycharmProjects\NewProject\venv\lib\site-packages\netmiko\a10\a10_ssh.py", line 3, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "C:\Users\libaa\PycharmProjects\NewProject\venv\lib\site-packages\netmiko\cisco_base_connection.py", line 2, in <module>
    from netmiko.base_connection import BaseConnection
  File "C:\Users\libaa\PycharmProjects\NewProject\venv\lib\site-packages\netmiko\base_connection.py", line 27, in <module>
    from netmiko.utilities import (
  File "C:\Users\libaa\PycharmProjects\NewProject\venv\lib\site-packages\netmiko\utilities.py", line 8, in <module>
    import serial.tools.list_ports
ModuleNotFoundError: No module named 'serial.tools'; 'serial' is not a package

**Comment by ktbyers** [comment]
Just comment on the original issue.
