### ISSUE TITLE
OSError: Socket is closed

### ISSUE THREAD

**Issue by RichardMichael** [ktbyers/netmiko#1893]
I have already tried increasing the line vty to 0 0 to not to timeout on the switch. 

  File "/Users/Blahblah/opt/anaconda3/lib/python3.7/site-packages/paramiko/channel.py", line 1198, in _send
    raise socket.error("Socket is closed")
OSError: Socket is closed

Do i need to include any timeout parameter when i need to do:

     output = net_connect.send_command(cmd)
     output0 = net_connect.send_config_set(config_command1)

**Comment by ktbyers** [comment]
@RichardMichael I need the full exception stack trace. Also please post the version of Netmiko that you are using.

Regards, Kirk

**Comment by RichardMichael** [comment]
i ran a debug and got the below exception which i believe is due to the session limit that NXOS has which is total of 32. i think i need to close the socket everytime i open the SSH else i will easily run out of the SSH session limit which is why the socket error comes.

CLI session limit 32 reached. Exiting.

DEBUG:netmiko:read_channel: 
DEBUG:paramiko.transport:[chan 0] EOF received (0)
DEBUG:paramiko.transport:[chan 0] EOF sent (0)
DEBUG:netmiko:read_channel: 

********NO# OF TIMES SCRIPT RAN IN TOTAL**********: 33
Traceback (most recent call last):
  File "/Users/blah/Desktop/EDMA.py", line 26, in <module>
    net_connect = ConnectHandler(**devices)
  File "/Users/blah/opt/anaconda3/lib/python3.7/site-packages/netmiko/ssh_dispatcher.py", line 298, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/Users/blah/opt/anaconda3/lib/python3.7/site-packages/netmiko/base_connection.py", line 341, in __init__
    self._open()
  File "/Users/blah/opt/anaconda3/lib/python3.7/site-packages/netmiko/base_connection.py", line 347, in _open
    self._try_session_preparation()
  File "/Users/blah/opt/anaconda3/lib/python3.7/site-packages/netmiko/base_connection.py", line 772, in _try_session_preparation
    self.session_preparation()
  File "/Users/blah/opt/anaconda3/lib/python3.7/site-packages/netmiko/cisco/cisco_nxos_ssh.py", line 13, in session_preparation
    self.set_base_prompt()
  File "/Users/blah/opt/anaconda3/lib/python3.7/site-packages/netmiko/base_connection.py", line 1106, in set_base_prompt
    prompt = self.find_prompt(delay_factor=delay_factor)
  File "/Users/blah/opt/anaconda3/lib/python3.7/site-packages/netmiko/base_connection.py", line 1121, in find_prompt
    self.write_channel(self.RETURN)
  File "/Users/blah/opt/anaconda3/lib/python3.7/site-packages/netmiko/base_connection.py", line 450, in write_channel
    self._write_channel(out_data)
  File "/Users/blah/opt/anaconda3/lib/python3.7/site-packages/netmiko/base_connection.py", line 408, in _write_channel
    self.remote_conn.sendall(write_bytes(out_data, encoding=self.encoding))
  File "/Users/blah/opt/anaconda3/lib/python3.7/site-packages/paramiko/channel.py", line 846, in sendall
    sent = self.send(s)
  File "/Users/blah/opt/anaconda3/lib/python3.7/site-packages/paramiko/channel.py", line 801, in send
    return self._send(s, m)
  File "/Users/blah/opt/anaconda3/lib/python3.7/site-packages/paramiko/channel.py", line 1198, in _send
    raise socket.error("Socket is closed")
OSError: Socket is closed

**Comment by ktbyers** [comment]
Basically all the exception says is that Netmiko tried to send an <enter> and that it couldn't because the SSH connection was closed.

**Comment by ktbyers** [comment]
Let's look at the Netmiko log file and see if this gives us any clues:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

Also which version of Netmiko are you using?
