### ISSUE TITLE
Unable to connect to AireOS Device with 3.2.0 Release

### ISSUE THREAD

**Issue by jmcgill298** [ktbyers/netmiko#1896]
I am able to connect to device fine using netmiko==3.1.1

```
>>> from netmiko import ConnectHandler
>>> dev = ConnectHandler(device_type="cisco_wlc", ip=ip, username=username, password=password, port=22, global_delay_factor=1, secret="", verbose=False)
>>> dev.find_prompt()
'(wlc_host)'
>>>
```

I get a paramiko SSHException when attempting the same thing on netmiko==3.2.0

```
>>> from netmiko import ConnectHandler
>>> dev = ConnectHandler(device_type="cisco_wlc", ip=ip, username=username, password=password, port=22, global_delay_factor=1, secret="", verbose=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/users/user/venv/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 298, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/users/user/venv/lib/python3.6/site-packages/netmiko/base_connection.py", line 341, in __init__
    self._open()
  File "/home/users/user/venv/lib/python3.6/site-packages/netmiko/base_connection.py", line 346, in _open
    self.establish_connection()
  File "/home/users/user/venv/lib/python3.6/site-packages/netmiko/base_connection.py", line 915, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/users/user/venv/lib/python3.6/site-packages/paramiko/client.py", line 412, in connect
    server_key = t.get_remote_server_key()
  File "/home/users/user/venv/lib/python3.6/site-packages/paramiko/transport.py", line 834, in get_remote_server_key
    raise SSHException("No existing session")
paramiko.ssh_exception.SSHException: No existing session
>>> 
```

I did a pip freeze between 3.1.1 and 3.2.0 and compared and the only difference was netmiko

**Comment by ktbyers** [comment]
Seems like same issue as this:

https://github.com/ktbyers/netmiko/issues/1887

**Comment by jmcgill298** [comment]
seems similar. The device is not running IOS-XE software though, so that should not be the resolution

**Comment by ktbyers** [comment]
That was someone else...not the person that originally reported it. The person that originally reported it fixed it by downgrading to Netmiko 2.4.2

**Comment by jmcgill298** [comment]
Yes, 3.1.1 works fine, it is only observed in 3.2.0

**Comment by jmcgill298** [comment]
@ktbyers I am going to unfollow this issue now that a resolution is decided upon; feel free to close as you wish

**Comment by ktbyers** [comment]
Sounds good. I will leave it open until I create the PR so that I track the issue.

**Comment by ktbyers** [comment]
PR fixing this is here:

https://github.com/ktbyers/netmiko/pull/1897
