### ISSUE TITLE
Recommended way to send reload command 

### ISSUE THREAD

**Issue by allan-silverstein** [ktbyers/netmiko#1917]
I'm trying to reload a router (Drivenet) box using the "request system_restart" command.  This is an interactive type command.  I have no problem getting the reload to happen but Netmiko throws and Exception as the SSH session terminates upon entering "yes" to the restart command.

raise socket.error("Socket is closed")
OSError: Socket is closed

What is the recommended way to handle sending commands that you know are going to cause the SSH session to terminate. Is it to just do a Try and Except and catch the OSError... I'm hoping many people have done this and there is a "standard" way or feature built in to handle this.  Below is a partial code snippet.  Note, I know I"m using the "expect_string" variable in the code below.  It was left over because previously I was using not using the send_command_timing..

    cmd_list = [
        {"request system restart"  : 'yes/no'},
        {"yes" : "NA"},
    ] 
for item in cmd_list:
        cmd = list(item.keys())[0]
        expect_string = list(item.values())[0]

        output = connectionObj.send_command_timing(cmd, strip_command=False,
                                                        strip_prompt=False)
        combined_output += output
Thx
Al

Traceback (most recent call last):
  File "/opt/python-3.7.4/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/python-3.7.4/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/as2863/pythonProjects/p1-automation/lib/dnet_generic.py", line 427, in dnet_send_config_cmds
    connectionObj.send_command('unset cli-timestamp')
  File "/home/as2863/python-venv/p1_netmiko_exper4/lib/python3.7/site-packages/netmiko/utilities.py", line 347, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/home/as2863/python-venv/p1_netmiko_exper4/lib/python3.7/site-packages/netmiko/base_connection.py", line 1369, in send_command
    prompt = self.find_prompt(delay_factor=delay_factor)
  File "/home/as2863/python-venv/p1_netmiko_exper4/lib/python3.7/site-packages/netmiko/base_connection.py", line 1095, in find_prompt
    self.write_channel(self.RETURN)
  File "/home/as2863/python-venv/p1_netmiko_exper4/lib/python3.7/site-packages/netmiko/base_connection.py", line 436, in write_channel
    self._write_channel(out_data)
  File "/home/as2863/python-venv/p1_netmiko_exper4/lib/python3.7/site-packages/netmiko/base_connection.py", line 394, in _write_channel
    self.remote_conn.sendall(write_bytes(out_data, encoding=self.encoding))
  File "/home/as2863/python-venv/p1_netmiko_exper4/lib/python3.7/site-packages/paramiko/channel.py", line 846, in sendall
    sent = self.send(s)
  File "/home/as2863/python-venv/p1_netmiko_exper4/lib/python3.7/site-packages/paramiko/channel.py", line 801, in send
    return self._send(s, m)
  File "/home/as2863/python-venv/p1_netmiko_exper4/lib/python3.7/site-packages/paramiko/channel.py", line 1198, in _send
    raise socket.error("Socket is closed")
OSError: Socket is closed

**Comment by allan-silverstein** [comment]
I'm closing this out.  My mistake. send_command_timing does not return an error.  The script was trying to access the device, later in the script, and I missed that.  At that point, the OSError was generated.  I'm assuming then, that send_command_timing is the preferred method to reload a device??
Thx
