### ISSUE TITLE
UnicodeEncodeError | Cisco WLC & HPE COMWARE 5

### ISSUE THREAD

**Issue by rb3123** [ktbyers/netmiko#1931]
Hi @ktbyers 

Not sure why but some or my older scripts are running into UnicodeEncodeError : "'ascii' codec can't encode character '\xe3' in position 45774: ordinal not in range(128)". Snippet of code below

`deviceinfo = {'device_type': 'cisco_wlc', 'ip': wlcipadd, 'username': username, 'password': password, 'banner_timeout': 16, 'global_delay_factor': 4, 'session_log':filename}

device = netmiko.ConnectHandler(**deviceinfo)

op = device.send_command_timing("show ap summary", use_textfsm=False)`

**Comment by rb3123** [comment]
Looks like I found the issue. Session logs were incomplete which couldn't be written properly.

**Comment by ktbyers** [comment]
@rb3123 Can you expand on this a bit (i.e. what the underlying issue is)?


Regards, Kirk

**Comment by rb3123** [comment]
Hi @ktbyers 

It seems our jump server was moved to a different data center pushing latency towards some WLC into 180 - 230ms zone. As netmiko has to fetch data over multiple iterations, some characters get malformed and fail to write into session logs on Windows (haven't tested yet on Linux). This failure to write session log also causes entire driver to crash, terminating connection to WLC/switch. I have disabled session_log on driver level which has fixed the issue for us.

**Comment by sohalevi** [comment]
Hi,

is there a way to solve this in a way to not just disable session logging? Randomly I experience this issue, with newer Cisco IOS XE 17.x

10.213.57.6 - - [04/Dec/2020 13:05:41] "POST /test HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/acat/.local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/acat/.local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/acat/.local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/acat/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/acat/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/acat/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/acat/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/acat/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/acat/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/acat/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/acat/python/Main_Combined_v4.py", line 191, in upload_file
    session["device"].rs_akzeptanztest = module_akzeptanztest_post.akzeptanztest(session["device"], request, flash)
  File "/home/acat/python/_akzeptanztest_py/module_akzeptanztest_post.py", line 82, in akzeptanztest
    acceptance_iosload(device)
  File "/home/acat/python/_akzeptanztest_py/module_akzeptanztest_post.py", line 295, in acceptance_iosload
    do_ios_load_akz(device, error_trace=section_name)
  File "/home/acat/python/_akzeptanztest_py/ios_load_starter.py", line 204, in do_ios_load_akz
    do_ios_load_access_router(device, akz=True, error_trace=error_trace)
  File "/home/acat/python/_akzeptanztest_py/ios_load_starter.py", line 226, in do_ios_load_access_router
    device.proceed_akz = ios_load_access_router(device)
  File "/home/acat/python/_iosload_py/execute_on_router_start.py", line 129, in ios_load_access_router
    rdc = my_defs2.reachable_router(device.mgmt_ip, (device.username, device.password, device.file_name_up),
  File "/home/acat/python/_iosload_py/my_defs2.py", line 2993, in reachable_router
    ini_output = login_to_log_console(log_file_param[0], log_file_param[1], log_file_param[2])
  File "/home/acat/python/_iosload_py/my_defs2.py", line 867, in login_to_log_console
    reload_output += net_connect.read_channel()
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 522, in read_channel
    output = self._read_channel()
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 514, in _read_channel
    self._write_session_log(output)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 444, in _write_session_log
    self.session_log.write(self.normalize_linefeeds(data))
UnicodeEncodeError: 'ascii' codec can't encode character '\u056e' in position 53: ordinal not in range(128)

reload_output = ''
    jumpserver = login_parameters(username, password, log_file='reload_' + log_file)
    if login(jumpserver, jump=jump):
        time.sleep(1)
        net_connect.write_channel('\r')
        time.sleep(1)
        reload_output += net_connect.read_channel()
        net_connect.write_channel('\r')
        time.sleep(1)
        reload_output += net_connect.read_channel()
        print('Login back was successful!')
    else:
        print('Failed to login back!')

Error received at the first: reload_output += net_connect.read_channel()

Looking at the code it might seem it has nothing to do with session logging, the problem occured at read_channel already.

Can you take a look? - I see this is already closed, should I open a new topic?

Thank you,
Levente

**Comment by ktbyers** [comment]
Naah, it clearly looks like a unicode write error:

```
File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 444, in _write_session_log
self.session_log.write(self.normalize_linefeeds(data))
UnicodeEncodeError: 'ascii' codec can't encode character '\u056e' in position 53: ordinal not in range(128)
```

i.e. there is unicode in the output of what is read back in and we are trying to write that out to the session_log. You probably could modify that behavior such that it writes out unicode (or strips unicode).
