### ISSUE TITLE
OSError: Search pattern never detected in send_command_expect: \[\~xxx\-xxxddd\-x\-xx\-dd\-diagnose\]

### ISSUE THREAD

**Issue by stvnkem** [ktbyers/netmiko#1936]
Hello Dear,

**UPDATE: for some reason the device exits diag mode when the command is run... (thx to debug method)
I have successfully executed the command after running it from system-view. The user-view does not support the command...
I will talk to our R&D to eliminate such a behavior.**

```
pip3 list
netmiko            3.3.0
```

After the successful connection I send the following command. I can successfully enter to diag mode, but afterwards I receive an OSError, with or without using TextFSM. I think the `'~' `sign is causing this problem. Could you please help me to confirm?
In the meantime I will try to debug as you suggested in other topics.

```
diag_mode = connection.send_config_set(['diag'], exit_config_mode=False)
print(diag_mode)
output = connection.send_command('display fei fe dram error all')
```

```
Traceback (most recent call last):
  File "test_custom_textfsm.py", line 61, in <module>
    output = connection.send_command('display fei fe dram error all')
  File "/home/taakeis1/bfd_fix/lib64/python3.6/site-packages/netmiko/utilities.py", line 363, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/home/taakeis1/bfd_fix/lib64/python3.6/site-packages/netmiko/base_connection.py", line 1488, in send_command
    search_pattern
OSError: Search pattern never detected in send_command_expect: \[\~xxx\-xxxddd\-x\-xx\-dd\-diagnose\]
```

The output I am looking for in plain text:

```
[~xxx-xxxddd-x-xx-dd-diagnose]display fei fe dram error all
2020-09-12 10:22:02.107 +02:00 DST
Slot: 1 Chip: 0  
------------------------------------------
Dram Bank                Crc Error Count  
------------------------------------------
0~3                                     0
4~7                                     0
8~11                                    0
12~15                                   0
16~19                                   0
20~23                                   0
24~27                                   0
28~31                                   0
32~35                                   0
36~39                                   0
40~43                                   0
44~47                                   0
48~51                                   0
52~55                                   0
56~59                                   0
60~63                                   0

Slot: 5 Chip: 0  
------------------------------------------
Dram Bank                Crc Error Count  
------------------------------------------
0~3                                     0
4~7                                     0
8~11                                    0
12~15                                   0
16~19                                   0
20~23                                   0
24~27                                   0
28~31                                   0
32~35                                   0
36~39                                   0
40~43                                   0
44~47                                   0
48~51                                   0
52~55                                   0
56~59                                   0
60~63                                   0

Slot: 5 Chip: 1  
------------------------------------------
Dram Bank                Crc Error Count  
------------------------------------------
0~3                                     0
4~7                                     0
8~11                                    0
12~15                                   0
16~19                                   0
20~23                                   0
24~27                                   0
28~31                                   0
32~35                                   0
36~39                                   0
40~43                                   0
44~47                                   0
48~51                                   0
52~55                                   0
56~59                                   0
60~63                                   0

Slot: 5 Chip: 2  
------------------------------------------
Dram Bank                Crc Error Count  
------------------------------------------
0~3                                     0
4~7                                     0
8~11                                    0
12~15                                   0
16~19                                   0
20~23                                   0
24~27                                   0
28~31                                   0
32~35                                   0
36~39                                   0
40~43                                   0
44~47                                   0
48~51                                   0
52~55                                   0
56~59                                   0
60~63                                   0

Slot: 5 Chip: 3  
------------------------------------------
Dram Bank                Crc Error Count  
------------------------------------------
0~3                                     0
4~7                                     0
8~11                                    0
12~15                                   0
16~19                                   0
20~23                                   0
24~27                                   0
28~31                                   0
32~35                                   0
36~39                                   0
40~43                                   0
44~47                                   0
48~51                                   0
52~55                                   0
56~59                                   0
60~63                                   0

Slot: 6 Chip: 0  
------------------------------------------
Dram Bank                Crc Error Count  
------------------------------------------
0~3                                     0
4~7                                     0
8~11                                    0
12~15                                   0
16~19                                   0
20~23                                   0
24~27                                   0
28~31                                   0
32~35                                   0
36~39                                   0
40~43                                   0
44~47                                   0
48~51                                   0
52~55                                   0
56~59                                   0
60~63                                   0

Slot: 6 Chip: 1  
------------------------------------------
Dram Bank                Crc Error Count  
------------------------------------------
0~3                                     0
4~7                                     0
8~11                                    0
12~15                                   0
16~19                                   0
20~23                                   0
24~27                                   0
28~31                                   0
32~35                                   0
36~39                                   0
40~43                                   0
44~47                                   0
48~51                                   0
52~55                                   0
56~59                                   0
60~63                                   0

Slot: 6 Chip: 2  
------------------------------------------
Dram Bank                Crc Error Count  
------------------------------------------
0~3                                     0
4~7                                     0
8~11                                    0
12~15                                   0
16~19                                   0
20~23                                   0
24~27                                   0
28~31                                   0
32~35                                   0
36~39                                   0
40~43                                   0
44~47                                   0
48~51                                   0
52~55                                   0
56~59                                   0
60~63                                   0

Slot: 6 Chip: 3  
------------------------------------------
Dram Bank                Crc Error Count  
------------------------------------------
0~3                                     0
4~7                                     0
8~11                                    0
12~15                                   0
16~19                                   0
20~23                                   0
24~27                                   0
28~31                                   0
32~35                                   0
36~39                                   0
40~43                                   0
44~47                                   0
48~51                                   0
52~55                                   0
56~59                                   0
60~63                                   0

Slot: 8 Chip: 0  
------------------------------------------
Dram Bank                Crc Error Count  
------------------------------------------
0~3                                     0
4~7                                     0
8~11                                    0
12~15                                   0
16~19                                   0
20~23                                   0
24~27                                   0
28~31                                   0
32~35                                   0
36~39                                   0
40~43                                   0
44~47                                   0
48~51                                   0
52~55                                   0
56~59                                   0
60~63                                   0

Slot: 8 Chip: 1  
------------------------------------------
Dram Bank                Crc Error Count  
------------------------------------------
0~3                                     0
4~7                                     0
8~11                                    0
12~15                                   0
16~19                                   0
20~23                                   0
24~27                                   0
28~31                                   0
32~35                                   0
36~39                                   0
40~43                                   0
44~47                                   0
48~51                                   0
52~55                                   0
56~59                                   0
60~63                                   0
```

[~xxx-xxxddd-x-xx-dd]

**Comment by ktbyers** [comment]
What does the log file look like?

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel
