### ISSUE TITLE
Issues with  "device_type" : "cisco_ios_telnet" in 3.3.0

### ISSUE THREAD

**Issue by sa6kad** [ktbyers/netmiko#1945]
There is a problem with  "device_type" : "cisco_ios_telnet" when using version 3.3.0. Netmiko fails with either error `ValueError: Router prompt not found: 'Route'` 
or with
 `netmiko.ssh_exception.NetmikoAuthenticationException: Login failed: 10.254.254.254`.
Exactly the same script fails once with one of the above errors and the next time with the second one, which seems pretty confusing. I tested python 3.6, 3.7 and 3.8 all with the same result. 
Netmiko 3.2.0 and 3.1.1 work normally, tested on 3.6 and 3.8

**Comment by ktbyers** [comment]
Can you post the full exception stack trace for both exceptions? I can't do much without those.


Regards,

Kirk

**Comment by sa6kad** [comment]
The script that i run look like this
```
from netmiko import ConnectHandler
my_device = {
    "device_type" : "cisco_ios_telnet",
    "ip": "10.254.254.254",
    "username": "",
    "password": "",
    "port": 5025
}
print(my_device)
net_connect =  ConnectHandler(**my_device)
print(net_connect.enable())
print(net_connect.send_command('show run'))
```

Every time a run the script the result is different, I either get this error:
```
Traceback (most recent call last):
  File "/home/ald/Documents/Python/GNS3Auto/Test-netmiko.py", line 12, in <module>
    net_connect =  ConnectHandler(**my_device)
  File "/home/ald/.local/lib/python3.8/site-packages/netmiko/ssh_dispatcher.py", line 302, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/ald/.local/lib/python3.8/site-packages/netmiko/cisco/cisco_ios.py", line 17, in __init__
    return super().__init__(*args, **kwargs)
  File "/home/ald/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 344, in __init__
    self._open()
  File "/home/ald/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 350, in _open
    self._try_session_preparation()
  File "/home/ald/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 775, in _try_session_preparation
    self.session_preparation()
  File "/home/ald/.local/lib/python3.8/site-packages/netmiko/cisco/cisco_ios.py", line 24, in session_preparation
    self.set_base_prompt()
  File "/home/ald/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 1141, in set_base_prompt
    raise ValueError(f"Router prompt not found: {repr(prompt)}")
ValueError: Router prompt not found: 'Route'
```

Or this one.
```
Traceback (most recent call last):
  File "/home/ald/Documents/Python/GNS3Auto/Test-netmiko.py", line 12, in <module>
    net_connect =  ConnectHandler(**my_device)
  File "/home/ald/.local/lib/python3.8/site-packages/netmiko/ssh_dispatcher.py", line 302, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/ald/.local/lib/python3.8/site-packages/netmiko/cisco/cisco_ios.py", line 17, in __init__
    return super().__init__(*args, **kwargs)
  File "/home/ald/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 344, in __init__
    self._open()
  File "/home/ald/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 349, in _open
    self.establish_connection()
  File "/home/ald/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 908, in establish_connection
    self.telnet_login()
  File "/home/ald/.local/lib/python3.8/site-packages/netmiko/cisco_base_connection.py", line 169, in telnet_login
    raise NetmikoAuthenticationException(msg)
netmiko.ssh_exception.NetmikoAuthenticationException: Login failed: 10.254.254.254
```

Less often there is no error, but i get only very short part of the `show run` command.

**Comment by zkiroel** [comment]
Hello folks
the same thing with example (but with _cisco_ios_telnet_):
```
#!/usr/bin/env python
from netmiko import Netmiko
from getpass import getpass

net_connect = Netmiko(
    "x.x.x.x",
    username="username",
    password=getpass(),
    device_type="**cisco_ios_telnet**",
)

print(net_connect.find_prompt())
net_connect.disconnect()
```

output:
```
Password:
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    net_connect = Netmiko(
  File "/home/magos/.local/lib/python3.8/site-packages/netmiko/ssh_dispatcher.py", line 302, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/magos/.local/lib/python3.8/site-packages/netmiko/cisco/cisco_ios.py", line 17, in __init__
    return super().__init__(*args, **kwargs)
  File "/home/magos/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 344, in __init__
    self._open()
  File "/home/magos/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 349, in _open
    self.establish_connection()
  File "/home/magos/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 908, in establish_connection
    self.telnet_login()
  File "/home/magos/.local/lib/python3.8/site-packages/netmiko/cisco_base_connection.py", line 169, in telnet_login
    raise NetmikoAuthenticationException(msg)
netmiko.ssh_exception.NetmikoAuthenticationException: Login failed: x.x.x.x
```
