### ISSUE TITLE
Cisco ASA exception --> self.remote_conn.recv(MAX_BUFFER)

### ISSUE THREAD

**Issue by zimbres** [ktbyers/netmiko#1951]
I'm updating a VPN Ipsec tunnel config and got this error:

**Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 567, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout**

I had to split the commands to be sent to device like this:

_device = {
        "device_type": "cisco_asa",
        "host": os.getenv('DEVICE'),
        "username": os.getenv('USER'),
        "password": os.getenv('PASSWORD'),
    }

commands_new_1 = [
	f'tunnel-group {new_ip} type ipsec-l2l',
	f'tunnel-group {new_ip} general-attributes',
	'default-group-policy "DfltGrpPolicy"'
]

commands_new_2 = [
	f'tunnel-group {new_ip} ipsec-attributes',
	f'ikev1 pre-shared-key {os.getenv("PSK")}',
	'isakmp keepalive threshold 10 retry 2'
]

commands_new_3 = [
	f'crypto map outside_map1 66 set peer {new_ip}'
]

commands_old = [
	f'no crypto map outside_map1 66 set peer {old_ip}',
	f'clear config tunnel-group {old_ip}'
]

with ConnectHandler(**device) as net_connect:
	net_connect.send_config_set(commands_new_1)
	net_connect.send_config_set(commands_new_2)
	net_connect.send_config_set(commands_new_3)
	net_connect.send_config_set(commands_old)
	net_connect.save_config()_

This way I could make it work, but without split the commands, specifically this one: _f'crypto map outside_map1 66 set peer {new_ip}'_ the above error is generated.

Strangely if I use an IP like 1.1.1.1 or 2.2.2.2 to test, even without split the command it works, but, with a long IP like 177.123.192.180 the error happens if try to run without splinting.

Do I missing something?

**Comment by ktbyers** [comment]
The error basically says, Netmiko tried to read for N-seconds and there wasn't any data there:

```
File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 567, in _read_channel_expect
new_data = self.remote_conn.recv(MAX_BUFFER)
File "/usr/local/lib/python3.6/dist-packages/paramiko/channel.py", line 701, in recv
raise socket.timeout()
socket.timeout
```

Make sure you set this at the beginning of your SSH session:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/cisco/cisco_asa_ssh.py#L23

Or set the `allow_auto_change=True` argument as an argument to ConnectHandler.

Let me know if that helps or not.

Also which version of Netmiko are you using.

**Comment by zimbres** [comment]
Hi,

netmiko (3.3.0)

allow_auto_change=True, definitely helped.

Thanks a lot
