### ISSUE TITLE
django view import netmiko issue

### ISSUE THREAD

**Issue by chenxiaolu520** [ktbyers/netmiko#1955]
**centos failure,but in windows normal**

python manage.py runserver 0.0.0.0:8000
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 61, in execute
    super().execute(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 96, in handle
    self.run(**options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 103, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 613, in run_with_reloader
    start_django(reloader, main_func, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 598, in start_django
    reloader.run(django_main_thread)
  File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 313, in run
    self.run_loop()
  File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 319, in run_loop
    next(ticker)
  File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 359, in tick
    for filepath, mtime in self.snapshot_files():
  File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 375, in snapshot_files
    for file in self.watched_files():
  File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 274, in watched_files
    yield from iter_all_python_module_files()
  File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 105, in iter_all_python_module_files
    return iter_modules_and_files(modules, frozenset(_error_files))
TypeError: unhashable type: 'Configuration'

**Comment by ktbyers** [comment]
Don't see any Netmiko issues there.

**Comment by Jtown0011** [comment]
I had this exact same django error. My issue was that I had a file name called sshHandler.py in my django project and I believe that overlaps with an existing package so I renamed it to something else and afterwards I was able to run the django server. 

This is not an issue with netmiko.

django_1        | Traceback (most recent call last):
django_1        |   File "manage.py", line 30, in <module>
django_1        |     execute_from_command_line(sys.argv)
django_1        |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
django_1        |     utility.execute()
django_1        |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
django_1        |     self.fetch_command(subcommand).run_from_argv(self.argv)
django_1        |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
django_1        |     self.execute(*args, **cmd_options)
django_1        |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
django_1        |     output = self.handle(*args, **options)
django_1        |   File "/usr/local/lib/python3.7/site-packages/django_extensions/management/utils.py", line 62, in inner
django_1        |     ret = func(self, *args, **kwargs)
django_1        |   File "/usr/local/lib/python3.7/site-packages/django_extensions/management/commands/runserver_plus.py", line 262, in handle
django_1        |     self.inner_run(options)
django_1        |   File "/usr/local/lib/python3.7/site-packages/django_extensions/management/commands/runserver_plus.py", line 362, in inner_run
django_1        |     extra_files.extend(filter(lambda filename: str(filename).endswith('.mo'), gen_filenames()))
django_1        |   File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 262, in watched_files
django_1        |     yield from iter_all_python_module_files()
django_1        |   File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 103, in iter_all_python_module_files
django_1        |     return iter_modules_and_files(modules, frozenset(_error_files))
django_1        | TypeError: unhashable type: 'Configuration'

**Comment by ktbyers** [comment]
@Jtown0011 Was there a question here or is this just a comment?


Kirk

**Comment by Jtown0011** [comment]
@ktbyers Just a comment hoping to help others if they run into the same issue when attempting to run netmiko inside a Django view.

I realize this isn’t a netmiko problem but rather a Django problem and this issue #1955 can be closed.
