### ISSUE TITLE
How to send 2 commands to Juniper in 1 python code ?

### ISSUE THREAD

**Issue by gkangkang** [ktbyers/netmiko#1969]
Hi,
I have the requirement that set 2 ip-address to Juniper FW at one time. I try 2 way to achieve that, but all failed.
1, a list with two commands. 
2, use the for-loop.

 
First code:

```
from netmiko import ConnectHandler

def set_address(dev, cmd):
    net_connect = ConnectHandler(**dev)
    output = net_connect.send_config_set(cmd, exit_config_mode=False)
    print(output)
    output = net_connect.commit(and_quit=True)
    print(output)
    net_connect.disconnect()


fw = {'host': '172.17.3.18',
      'username': '****',
      'password': '****',
      'device_type': 'juniper_junos'}

cmds = ['set security address-book global address 172.17.248.1 172.17.248.1',
        'set security address-book global address 172.17.248.2 172.17.248.2']


set_address(fw, cmds)
```

-----------------------------------------------------
error:

Traceback (most recent call last):
  File "C:\Apps\Python36\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Apps\Python36\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Apps\Python36\lib\site-packages\netmiko\base_connection.py", line 567, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\Apps\Python36\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/gengjk/PycharmProjects/auto_acl/netmiko-juniper.py", line 22, in <module>
    set_address(fw, cmds)
  File "C:/Users/gengjk/PycharmProjects/auto_acl/netmiko-juniper.py", line 5, in set_address
    output = net_connect.send_config_set(cmd, exit_config_mode=False)
  File "C:\Apps\Python36\lib\site-packages\netmiko\base_connection.py", line 1814, in send_config_set
    new_output = self.read_until_pattern(pattern=re.escape(cmd.strip()))
  File "C:\Apps\Python36\lib\site-packages\netmiko\base_connection.py", line 644, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "C:\Apps\Python36\lib\site-packages\netmiko\base_connection.py", line 578, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

=======================================
Second code:

```
from netmiko import ConnectHandler

def set_address(dev, cmd):
    net_connect = ConnectHandler(**dev)
    output = net_connect.send_config_set(cmd, exit_config_mode=False)
    print(output)
    output = net_connect.commit(and_quit=True)
    print(output)
    net_connect.disconnect()



fw = {'host': '172.17.3.18',
      'username': '****',
      'password': '****',
      'device_type': 'juniper_junos'}

cmds = ['set security address-book global address 172.17.248.1 172.17.248.1',
        'set security address-book global address 172.17.248.2 172.17.248.2']


for each in cmds:
    set_address(fw, each)
```
-----------------------------------------------------
output and error:

configure 
warning: Clustering enabled; using private edit
warning: uncommitted changes will be discarded on exit
set security address-book global address 172.17.248.1 172.17.248.1 

{primary:node0}[edit]
****@S1_2E07_BRA_I_FW_03# 
commit and-quit
node0: 
configuration check succeeds
node1: 
commit complete
node0: 
commit complete
Exiting configuration mode

{primary:node0}
****@S1_2E07_BRA_I_FW_03> 
Traceback (most recent call last):
  File "C:\Apps\Python36\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Apps\Python36\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Apps\Python36\lib\site-packages\netmiko\base_connection.py", line 567, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\Apps\Python36\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/gengjk/PycharmProjects/auto_acl/netmiko-juniper.py", line 23, in <module>
    set_address(fw, each)
  File "C:/Users/gengjk/PycharmProjects/auto_acl/netmiko-juniper.py", line 5, in set_address
    output = net_connect.send_config_set(cmd, exit_config_mode=False)
  File "C:\Apps\Python36\lib\site-packages\netmiko\base_connection.py", line 1814, in send_config_set
    new_output = self.read_until_pattern(pattern=re.escape(cmd.strip()))
  File "C:\Apps\Python36\lib\site-packages\netmiko\base_connection.py", line 644, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "C:\Apps\Python36\lib\site-packages\netmiko\base_connection.py", line 578, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

==========================================

By using the second code, the first ip-address '172.17.248.1' is set successfully, but the second ip-address is set failed.

And another question, what is the difference between 'from netmiko import ConnectHandler' and 'from netmiko import Netmiko' ?

**Comment by Zuquim** [comment]
Have you tried it without the `exit_config_mode=False` option set?

**Comment by ktbyers** [comment]
The first way should be the correct way.

The first error indicates something is going wrong with cmd_verify so I would try:

```python
def set_address(dev, cmd):
    net_connect = ConnectHandler(**dev)
    output = net_connect.send_config_set(cmd, exit_config_mode=False, cmd_verify=False)
    print(output)
    output = net_connect.commit(and_quit=True)
    print(output)
    net_connect.disconnect()
```
