### ISSUE TITLE
Intermittent "Router prompt not found" on vSRX platform (cluster)

### ISSUE THREAD

**Issue by superloopnetworks** [ktbyers/netmiko#1971]
Hi @ktbyers . I'm facing an issue where it's intermittent. Sometimes when I connect, I receive the below ValueError. I wish the raised error showed which host(s) so I can narrow it down to the culprit. However, sometimes it works without throwing the error.. *shurgs*.. I would figure the error to be consistent. The platform I'm connecting to is a Juniper vSRX and based on the output of the ValueError: ```ValueError: Router prompt not found: '{primary:node0}'``` it looks like it's hitting a SRX cluster as it displays ```{primary:node0}```...  How do I fix this? Thanks!
  
```
Traceback (most recent call last):
  File "/home/username/opt/python-3.7.1/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/username/opt/python-3.7.1/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/username/superloop/lib/objects/basenode.py", line 94, in pull_cfgs
    self.connect()
  File "/home/username/superloop/lib/objects/basenode.py", line 22, in connect
    self.net_connect = ConnectHandler(self.ip,self.hostname,self.username,self.password,self.password,device_type=self.get_device_type())
  File "/home/username/venv/lib/python3.7/site-packages/netmiko/ssh_dispatcher.py", line 266, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/username/venv/lib/python3.7/site-packages/netmiko/base_connection.py", line 327, in __init__
    self._open()
  File "/home/username/venv/lib/python3.7/site-packages/netmiko/base_connection.py", line 333, in _open
    self._try_session_preparation()
  File "/home/username/venv/lib/python3.7/site-packages/netmiko/base_connection.py", line 756, in _try_session_preparation
    self.session_preparation()
  File "/home/username/venv/lib/python3.7/site-packages/netmiko/juniper/juniper.py", line 25, in session_preparation
    self.set_base_prompt()
  File "/home/username/venv/lib/python3.7/site-packages/netmiko/base_connection.py", line 1082, in set_base_prompt
    raise ValueError(f"Router prompt not found: {repr(prompt)}")
ValueError: Router prompt not found: '{primary:node0}'
```

**Comment by ktbyers** [comment]
Probably try setting `global_delay_factor=2` as an argument to ConnectHandler and see if that helps.

Basically, Netmiko sends an enter and needs to see either `>` or `#` at the end and here it only got `{primary:node0}` (i.e. the trailing prompt character wasn't there so it raised an error).

**Comment by ktbyers** [comment]
I implemented a retry for set_base_prompt() in this PR.

https://github.com/ktbyers/netmiko/pull/1977

Can you test your code against the `develop` branch and see if your problem goes away?

**Comment by superloopnetworks** [comment]
> Probably try setting `global_delay_factor=2` as an argument to ConnectHandler and see if that helps.
> 
> Basically, Netmiko sends an enter and needs to see either `>` or `#` at the end and here it only got `{primary:node0}` (i.e. the trailing prompt character wasn't there so it raised an error).

Increasing the ```global_delay_factor``` by 2 definitely fixed it... When I manually SSH'ed to the offending device (was able put locate "Router prompt not found" and include the self.host so I can see which is giving problems), I noticed at times, there are huge delays (up to 8 seconds) before the prompts appears. At other times, the prompt appeared instantly. I noticed I also get ```Authentication Failure``` too because it timesout when the device tries to reach TACACs... Slowing down netmiko definitely helped the process.. Thank you so much!.
