### ISSUE TITLE
Unable to connect to ASA 5505

### ISSUE THREAD

**Issue by lowescott** [ktbyers/netmiko#199]
I'm currently unable to connect to an ASA 5505 running version 8.2(1). Here's the Python code I'm using:

``` python
#!/usr/bin/env python

from netmiko import ConnectHandler
from getpass import getpass

ip_address = raw_input("Enter IP address: ")
username = raw_input("Enter username: ")

device = {
    'device_type': 'cisco_asa',
    'ip': ip_address,
    'username': username,
    'password': getpass(),
    'port': 22,
}

net_connect = ConnectHandler(**device)
output = net_connect.send_command_expect('show version')
print output
```

I'm running this on a Debian 8 ("Jessie") system with Python 2.7.9 inside a virtualenv. Inside the virtualenv, I installed netmiko using `pip install netmiko`.

Here's the output of the script when `device_type` is set to `cisco_asa`:

``` text
Traceback (most recent call last):
  File "asa_test.py", line 17, in <module>
    net_connect = ConnectHandler(**device)
  File "/home/slowe/Public/VEnvs/pynet/local/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 88, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/slowe/Public/VEnvs/pynet/local/lib/python2.7/site-packages/netmiko/base_connection.py", line 69, in __init__
    self.session_preparation()
  File "/home/slowe/Public/VEnvs/pynet/local/lib/python2.7/site-packages/netmiko/cisco/cisco_asa_ssh.py", line 13, in session_preparation
    self.enable()
  File "/home/slowe/Public/VEnvs/pynet/local/lib/python2.7/site-packages/netmiko/ssh_connection.py", line 15, in enable
    return super(SSHConnection, self).enable(cmd=cmd, pattern=pattern, re_flags=re_flags)
  File "/home/slowe/Public/VEnvs/pynet/local/lib/python2.7/site-packages/netmiko/base_connection.py", line 517, in enable
    output += self.read_until_prompt()
  File "/home/slowe/Public/VEnvs/pynet/local/lib/python2.7/site-packages/netmiko/base_connection.py", line 354, in read_until_prompt
    return self.read_until_pattern()
  File "/home/slowe/Public/VEnvs/pynet/local/lib/python2.7/site-packages/netmiko/base_connection.py", line 368, in read_until_pattern
    raise NetMikoTimeoutException("Timed-out reading channel, data not available.")
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.
```

If I change the `device_type` to `cisco_ios`, then the output changes to this:

``` text
Traceback (most recent call last):
  File "asa_test.py", line 18, in <module>
    output = net_connect.send_command_expect('show version')
  File "/home/slowe/Public/VEnvs/pynet/local/lib/python2.7/site-packages/netmiko/base_connection.py", line 454, in send_command_expect
    search_pattern))
IOError: Search pattern never detected in send_command_expect: asa5505\>
```

I am able to manually connect to the ASA using the same username and password supplied to the script. I've also tried hard-coding the IP address, username, and password in the script, but the results remain the same.

**Comment by ktbyers** [comment]
@lowescott Add a secret arguments to your dictionary.

```python
device = {
    'device_type': 'cisco_asa',
    'ip': ip_address,
    'username': username,
    'password': getpass(),
    'secret': 'my_secret',
    'port': 22,
}
```

ASA needs to go into enable mode to really do anything so part of the connection assumes you go into enable mode.

Let me know if this fixes it or not.

**Comment by lowescott** [comment]
@ktbyers That did it. I modified the code to look like this:

``` python
#!/usr/bin/env python

from netmiko import ConnectHandler
from getpass import getpass

ip_address = raw_input("Enter IP address: ")
username = raw_input("Enter username: ")

device = {
    'device_type': 'cisco_asa',
    'ip': ip_address,
    'username': username,
    'password': getpass('Enter SSH password: '),
    'secret': getpass('Enter enable password: '),
    'port': 22,
}

net_connect = ConnectHandler(**device)
output = net_connect.send_command_expect('show version')
print output
```

It now works as expected. Thanks for the rapid response!

**Comment by ktbyers** [comment]
Improve error message on failed entry into enable() mode. Make this self-evident that secret is messing.

**Comment by ktbyers** [comment]
https://github.com/ktbyers/netmiko/issues/200
