### ISSUE TITLE
net_connect.send_config_set is not working as expected

### ISSUE THREAD

**Issue by shailendra285** [ktbyers/netmiko#2009]
from netmiko import ConnectHandler

WWSWA = {
	'device_type':'cisco_ios',
	'ip': '172.30.0.13',
	'username': 'cadmin',
	'password': 'College!947',
        'secret' : 'College!947',
}
net_connect =ConnectHandler(**WWSWA)
output = net_connect.send_command ('show clock')
print (output)

config_commands = ['int loop 0', 'ip address 1.1.1.1 255.255.255.0']
output = net_connect.send_config_set(config_commands)
print (output)

**Output:** 
ubuntu:~$ python3 Netmiko1.py
*16:10:53.471 Central Sat Oct 17 2020
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/lib/python3/dist-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

**Comment by ktbyers** [comment]
Is there anything more in the exception stack trace? There should be more than the above?



Kirk

**Comment by shailendra285** [comment]
Here is completed output of the script: 

PS C:\python\python37-32> python3 netmiko1.py
11:21:00.347 Central Mon Oct 19 2020
Traceback (most recent call last):
  File "C:\Users\sharink\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packa
ges\Python38\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Users\sharink\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packa
ges\Python38\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sharink\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packa
ges\Python38\site-packages\netmiko\base_connection.py", line 569, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\Users\sharink\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packa
ges\Python38\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "netmiko1.py", line 16, in <module>
    output1 = net_connect.send_config_set(config_commands)
  File "C:\Users\sharink\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packa
ges\Python38\site-packages\netmiko\base_connection.py", line 1837, in send_config_set
    output += self.config_mode(*cfg_mode_args)
  File "C:\Users\sharink\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packa
ges\Python38\site-packages\netmiko\cisco_base_connection.py", line 40, in config_mode
    return super().config_mode(
  File "C:\Users\sharink\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packa
ges\Python38\site-packages\netmiko\base_connection.py", line 1721, in config_mode
    if not self.check_config_mode():
  File "C:\Users\sharink\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packa
ges\Python38\site-packages\netmiko\cisco\cisco_ios.py", line 32, in check_config_mode
    return super().check_config_mode(check_string=check_string, pattern=pattern)
  File "C:\Users\sharink\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packa
ges\Python38\site-packages\netmiko\cisco_base_connection.py", line 30, in check_config_mode
    return super().check_config_mode(check_string=check_string, pattern=pattern)
  File "C:\Users\sharink\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packa
ges\Python38\site-packages\netmiko\base_connection.py", line 1705, in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "C:\Users\sharink\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packa
ges\Python38\site-packages\netmiko\base_connection.py", line 646, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "C:\Users\sharink\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packa
ges\Python38\site-packages\netmiko\base_connection.py", line 579, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

**Comment by ktbyers** [comment]
Can you enable Netmiko logging for this issue?

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

Also please make sure you are using the latest released version of Netmiko i.e. Netmiko 3.3.2

**Comment by aliturunc** [comment]
ı have this issue in latest netmiko version try  netmiko 2.4.2  , also you need to change the code like this  when you use send config set .
output = net_connect.send_config_set(config_commands ,  delay_factor=1, exit_config_mode=False)
