### ISSUE TITLE
Dell powerconnect 410S config-mode issue

### ISSUE THREAD

**Issue by kafooo** [ktbyers/netmiko#2023]
relevant debug log: 
```swb29a2.twr#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
swb29a2.twr#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
swb29a2.twr#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is swb29a2.twr#
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:Pattern is: swb29a2\.twr
DEBUG:netmiko:_read_channel_expect read_data: 

DEBUG:netmiko:_read_channel_expect read_data: swb29a2.twr#
DEBUG:netmiko:Pattern found: swb29a2\.twr 
swb29a2.twr#
DEBUG:netmiko:In disable_paging
DEBUG:netmiko:Command: terminal datadump

DEBUG:netmiko:write_channel: b'terminal datadump\n'
DEBUG:netmiko:Pattern is: terminal\ datadump
DEBUG:netmiko:_read_channel_expect read_data: terminal datadump

DEBUG:netmiko:Pattern found: terminal\ datadump terminal datadump

DEBUG:netmiko:terminal datadump

DEBUG:netmiko:Exiting disable_paging
DEBUG:netmiko:read_channel:                      ^
% Error: Invalid input at "^" marker.
swb29a2.twr#
DEBUG:netmiko:Clear buffer detects data in the channel
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
swb29a2.twr#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'config\n'
DEBUG:netmiko:Pattern is: config
DEBUG:netmiko:_read_channel_expect read_data: config

DEBUG:netmiko:Pattern found: config config

DEBUG:netmiko:Pattern is: swb29a2\.twr
DEBUG:netmiko:_read_channel_expect read_data: swb29a2.twr(conf)#
DEBUG:netmiko:Pattern found: swb29a2\.twr swb29a2.twr(conf)#
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
swb29a2.twr(conf)#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel:
```

running pretty simple code:
```
def ssh_session(**kwargs):
    # Creates ssh session to network devices, sends commands and print output

    device = {
        "host": kwargs["host"],
        "device_type": kwargs["device_type"],
    }
    # Assign key or username/password combination based on arguments
    if "key" in kwargs:
        device["username"] = "xxx"
        device["allow_agent"] = "True"
        device["use_keys"] = "True"
        device["key_file"] = "xxx"
    else:
        device["username"] = kwargs["username"]
        device["password"] = kwargs["password"]
    try:
        ssh_session = ConnectHandler(**device)
        print(f'Connection to {device["host"]} succesfull!')
        print(ssh_session.send_config_set(kwargs["commands"]))
        print("\n\n\n")
        ssh_session.disconnect()

    except NetMikoTimeoutException:
        print(f"=========== TIMEOUT ERROR WITH {device['host']} ============")

    except AuthenticationException:
        print(f"======== AUTHENTICATION ERROR WITH {device['host']} =========")

    except Exception:
        print(f"=========== UNKNOWN ERROR WITH {device['host']} ============")
```

from cli point of view, it looks like this:
```
swb29a2.twr#
swb29a2.twr#config
swb29a2.twr(conf)#
```

i can run show command in user mode just fine. 
Same issue happens if i use ssh_session.config_mode()

**Comment by ktbyers** [comment]
Which Netmiko device_type are you using? Dell PowerConnect driver has the following:

```
    def check_config_mode(self, check_string="(config)#"):
        """Checks if the device is in configuration mode"""
        return super().check_config_mode(check_string=check_string)
```

So that doesn't work with your model/device.

Also I saw that the `terminal datadump` command failed above.

It looks like this is a different platform than what the current Dell PowerConnect is built for.

**Comment by kafooo** [comment]
i am using dell_powerconnect, sorry, forgot to add func call 
```
ssh_session(
    host="swb29a2",
    device_type="dell_powerconnect",
    key="true",
    commands=cmds,
)
```

also, i removed my expetion stack as advised in netmiko slack:
```
Traceback (most recent call last):
  File "/home/users/karel.svoboda/test_hua_commit.py", line 58, in <module>
    commands=cmds,
  File "/home/users/karel.svoboda/test_hua_commit.py", line 30, in ssh_session
    print(ssh_session.send_config_set(kwargs["commands"]))
  File "/home/users/karel.svoboda/.local/lib/python3.7/site-packages/netmiko/base_connection.py", line 1837, in send_config_set
    output += self.config_mode(*cfg_mode_args)
  File "/home/users/karel.svoboda/.local/lib/python3.7/site-packages/netmiko/dell/dell_powerconnect.py", line 47, in config_mode
    return super().config_mode(config_command=config_command)
  File "/home/users/karel.svoboda/.local/lib/python3.7/site-packages/netmiko/cisco_base_connection.py", line 41, in config_mode
    config_command=config_command, pattern=pattern, re_flags=re_flags
  File "/home/users/karel.svoboda/.local/lib/python3.7/site-packages/netmiko/base_connection.py", line 1731, in config_mode
    raise ValueError("Failed to enter configuration mode.")
ValueError: Failed to enter configuration mode.
```

after that, i tried connection with dell_force10 and altough its officially powerconnect, it behaves like force10 and it works with force10 func. 

Anyway, solved from my point of view, thnaks for assistance!
