### ISSUE TITLE
Nornir/Netmiko - "Timed-out reading channel, data not available" after update to Netmiko 3.0

### ISSUE THREAD

**Issue by jasonhaominglo** [ktbyers/netmiko#2046]
Similar vein to issue 1656, I am seeing time out issues running netmiko ssh polls to arista devices that do not support the setting of terminal width in a non enabled context. This used to work in the previous version of netmiko as it did not enforce the searching and successful return of running the term width command.

the previous iteration had the below:
```
delay_factor = self.select_delay_factor(delay_factor)
command = self.normalize_cmd(command)
self.write_channel(command)
**output = self.read_until_prompt()** 
```

but the new version tries looking for it regardless of cmd_verify being explicity let to false:
```
# Avoid cmd_verify here as terminal width must be set before doing cmd_verify
if cmd_verify and self.global_cmd_verify is not False:
    output = self.read_until_pattern(pattern=re.escape(command.strip()))
elif pattern:
    output = self.read_until_pattern(pattern=pattern) <---
else:
    output = self.read_until_prompt()

```

**Comment by ktbyers** [comment]
@jasonhaominglo Can you show me the full exception stack trace you get on a failure?

Also, which version of Netmiko are you using?


Regards,

Kirk

**Comment by jasonhaominglo** [comment]
Hi Kirk, 

Please see below:

`DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:Received global request "hostkeys-00@openssh.com"
DEBUG:paramiko.transport:Rejecting "hostkeys-00@openssh.com" global request from server.
DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:write_channel: b'terminal width 511\n'
DEBUG:netmiko:Pattern is: Width set to
DEBUG:netmiko:_read_channel_expect read_data: Last login: Thu Nov 19 05:29:02 AEDT 2020 from 10.68.129.223 on pts/0

DEBUG:netmiko:_read_channel_expect read_data: terminal width 511

DEBUG:netmiko:_read_channel_expect read_data: hunauslabs10>terminal width 511

DEBUG:netmiko:_read_channel_expect read_data: % There is a command like "terminal width 511" in Privileged EXEC (enable) mode.
hunauslabs10>
DEBUG:paramiko.transport:[chan 0] Unhandled channel request "keepalive@openssh.com"
DEBUG:paramiko.transport:[chan 0] Unhandled channel request "keepalive@openssh.com"
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel:
hunauslabs10>
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'exit\n'
DEBUG:paramiko.transport:EOF in transport thread
ERROR:nornir.core.task:Host 'hunauslabs10': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/opt/venvs/nornir/lib/python3.6/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/opt/venvs/nornir/lib/python3.6/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venvs/nornir/lib/python3.6/site-packages/netmiko/base_connection.py", line 569, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/opt/venvs/nornir/lib/python3.6/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venvs/nornir/lib/python3.6/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/opt/venvs/nornir/lib/python3.6/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "/opt/venvs/nornir/lib/python3.6/site-packages/nornir/core/inventory.py", line 448, in get_connection
    extras=conn.extras,
  File "/opt/venvs/nornir/lib/python3.6/site-packages/nornir/core/inventory.py", line 499, in open_connection
    configuration=configuration,
  File "/opt/venvs/nornir/lib/python3.6/site-packages/nornir_netmiko/connections/netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
  File "/opt/venvs/nornir/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 312, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/opt/venvs/nornir/lib/python3.6/site-packages/netmiko/arista/arista.py", line 10, in __init__
    return super().__init__(*args, **kwargs)
  File "/opt/venvs/nornir/lib/python3.6/site-packages/netmiko/base_connection.py", line 346, in __init__
    self._open()
  File "/opt/venvs/nornir/lib/python3.6/site-packages/netmiko/base_connection.py", line 352, in _open
    self._try_session_preparation()
  File "/opt/venvs/nornir/lib/python3.6/site-packages/netmiko/base_connection.py", line 777, in _try_session_preparation
    self.session_preparation()
  File "/opt/venvs/nornir/lib/python3.6/site-packages/netmiko/arista/arista.py", line 16, in session_preparation
    self.set_terminal_width(command=cmd, pattern=r"Width set to")
  File "/opt/venvs/nornir/lib/python3.6/site-packages/netmiko/base_connection.py", line 1116, in set_terminal_width
    output = self.read_until_pattern(pattern=pattern)
  File "/opt/venvs/nornir/lib/python3.6/site-packages/netmiko/base_connection.py", line 646, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/opt/venvs/nornir/lib/python3.6/site-packages/netmiko/base_connection.py", line 580, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

INFO:__main__:
Failed getting config from this device hunauslabs10`

**Comment by jasonhaominglo** [comment]
am running version:
nornir-netmiko (0.1.1)

**Comment by ktbyers** [comment]
@jasonhaominglo I need the Netmiko version, not the nornir-netmiko version.

**Comment by ktbyers** [comment]
@jasonhaominglo Which version of Arista EOS are you connecting to (that is failing).

**Comment by ktbyers** [comment]
Also what do you see if you manually do the following?

```
arista5#terminal width 511
Width set to 511 columns.
```

**Comment by jasonhaominglo** [comment]
Hi Kirk, the device is not running EOS per se, its an arista device running MOS - for the most part, in the previous version it looked to take most basic commands that I was concerned about.
hunauslabs10>terminal width 511
% There is a command like "terminal width 511" in Privileged EXEC (enable) mode.

hunauslabs10#terminal width 511
Could not change terminal settings

hunauslabs10#show ver
Device: Metamako MetaConnect 48

Anyway that I can massage it to not enforce the searching and returning of "Width set to" or "Pagination disabled"?

**Comment by ktbyers** [comment]
Does it work if you try `device_type="cisco_ios"`?

**Comment by jasonhaominglo** [comment]
Hi Kirk - thanks for the tip - just reporting back that that seems to work. Haven't had much time to mull over the code by will do soon. Might have more questions to add to this thread.

**Comment by jasonhaominglo** [comment]
suggested fix working
