### ISSUE TITLE
Netmiko does not like the command 'load sys config merge from-terminal' on the F5 platform

### ISSUE THREAD

**Issue by superloopnetwork** [ktbyers/netmiko#2054]
Hi @ktbyers,
I'm able to do a send_command (single command ex. list 'ltm one-line') and send_config_set (series of config commands) to the F5. However, if I include 'load sys config merge from-terminal' as the first element in the list to pass into send_config_set(), Netmiko doesn't like that and eventually times out:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/netmiko/base_connection.py", line 550, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/wailitloi/superloop/lib/objects/basenode.py", line 85, in push_cfgs
    output = self.net_connect.send_config_set(commands,enter_config_mode=False,exit_config_mode=False)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/netmiko/base_connection.py", line 1766, in send_config_set
    new_output = self.read_until_pattern(pattern=pattern)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/netmiko/base_connection.py", line 627, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/netmiko/base_connection.py", line 561, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.
```
Here is the list I'm sending down send_config_set():
```
['load /sys config merge from-terminal', 'ltm node test1kentik1.prod.skytap.com { address 88.129.0.29 session monitor-enabled state down }', 'ltm node test1netgauge2.prod.skytap.com { address 88.129.3.203 session monitor-enabled state down }', 'ltm node test1r1ftp3.mgt.prod.skytap.com { address 88.129.17.888 session monitor-enabled state down }', 'ltm node test1r1logger2.mgt.prod.skytap.com { address 88.129.16.73 session monitor-enabled state down }', 'ltm node black-web { address 88.2.0.55 session monitor-enabled state down }', 'ltm node blue-web { address 88.2.0.33 session monitor-enabled state down }', 'ltm node green-web { address 88.2.0.22 session monitor-enabled state up }', 'ltm node red-web { address 88.2.0.11 session monitor-enabled state up }', '\x04']
```
If I remove 'load /sys config merge from-terminal' and just a regular list of configs:
```
['ltm node test1kentik1.prod.skytap.com { address 88.129.0.29 session monitor-enabled state down }', 'ltm node test1netgauge2.prod.skytap.com { address 88.129.3.203 session monitor-enabled state down }', 'ltm node test1r1ftp3.mgt.prod.skytap.com { address 88.129.17.888 session monitor-enabled state down }', 'ltm node test1r1logger2.mgt.prod.skytap.com { address 88.129.16.73 session monitor-enabled state down }', 'ltm node black-web { address 88.2.0.55 session monitor-enabled state down }', 'ltm node blue-web { address 88.2.0.33 session monitor-enabled state down }', 'ltm node green-web { address 88.2.0.22 session monitor-enabled state up }', 'ltm node red-web { address 88.2.0.11 session monitor-enabled state up }']
```
It works.. It sends the commands down the channel. (even though it's the wrong syntax, but just showing it works)
```
Syntax Error: unexpected argument "dal1kentik1.prod.skytap.com"
admin@(f5-big-ip2)(cfg-sync Sync Failed)(Active)(/Common)(tmos)# ltm node test1netgauge2.prod.skytap.com { address 88.129.3.203 session monitor-enabled state down }
Syntax Error: unexpected argument "test1netgauge2.prod.skytap.com"
admin@(f5-big-ip2)(cfg-sync Sync Failed)(Active)(/Common)(tmos)# ltm node test1r1ftp3.mgt.prod.skytap.com { address 88.129.17.108 session monitor-enabled state down }
Syntax Error: unexpected argument "test1r1ftp3.mgt.prod.skytap.com"
```
It's strange because when I do this on the Juniper platform 'load replace terminal' - it works just fine. I'm able to include 'load replace terminal' in a list followed by the list of commands I want to send, and it works perfectly with send_config_set().

I'm not sure if Netmiko is expecting a response or something and not getting any, thus timing out...

**Comment by superloopnetwork** [comment]
Here is also the block of code I use to send configs in:
```
        elif self.platform == 'f5':
            output = self.net_connect.send_config_set(commands,enter_config_mode=False,exit_config_mode=False)
            save = self.net_connect.send_command('save sys config')
            print(output)
            print(save)
```
I used this on the Junipers and it's working fine:
```
        elif self.platform == 'juniper':
            output = self.net_connect.send_config_set(commands,exit_config_mode=False)
            self.net_connect.commit(and_quit=True)
            print(output)
```

**Comment by superloopnetwork** [comment]
This is is the same issue with https://github.com/ktbyers/netmiko/issues/1526. 

I set the ```cmd_verify=False``` and that fixed it!

Thank you so much @ktbyers !
