### ISSUE TITLE
Panorama send command timeout

### ISSUE THREAD

**Issue by rapowell** [ktbyers/netmiko#2070]
I have a python script that I've written that logs into a Cisco switch, gets the IP and description of an interface and then takes that information and creates a sub-interface in the appropriate Panorama template and pushes the config to the firewalls.  I was recently asked to enhance the script to include getting any DHCP helpers and adding them to the Panorama config. I'm able to retrieve the information I need, but when I try to send the command to Panorama, the connection times out.  When I look on my Panorama, I see the command was sent successfully.

Here a snippet of the code.

```

uname = 'admin'
pano = '192.168.43.98'
template = 'my_template'
helpers = ['192.168.130.89', '192.168.130.90', '192.168.200.23', '192.168.34.14']
hlp_svr = 'set template ' + template + ' config  network dhcp interface ae2.' + vlanid + ' relay ip server [ ' + ' '.join(helpers) + ' ] enabled yes'
print (hlp_svr)
#'set template my_template config  network dhcp interface ae2.710 relay ip server [ 192.168.130.89 192.168.130.90 192.168.200.23 192.168.34.14 ] enabled yes'
device = ConnectHandler(device_type='paloalto_panos', ip=pano, username=uname, password='admin')
device.config_mode()
device.send_command(hlp_svr)

```

When I run this, I get the following:

```

Traceback (most recent call last):
  File "C:\Users\Robert\AppData\Local\Programs\Python\Python38\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Users\Robert\AppData\Local\Programs\Python\Python38\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Robert\AppData\Local\Programs\Python\Python38\lib\site-packages\netmiko\base_connection.py", line 564, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\Users\Robert\AppData\Local\Programs\Python\Python38\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Robert\AppData\Local\Programs\Python\Python38\lib\site-packages\netmiko\paloalto\paloalto_panos.py", line 160, in send_command
    return super().send_command(*args, **kwargs)
  File "C:\Users\Robert\AppData\Local\Programs\Python\Python38\lib\site-packages\netmiko\utilities.py", line 347, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "C:\Users\Robert\AppData\Local\Programs\Python\Python38\lib\site-packages\netmiko\base_connection.py", line 1415, in send_command
    new_data = self.read_until_pattern(pattern=re.escape(cmd))
  File "C:\Users\Robert\AppData\Local\Programs\Python\Python38\lib\site-packages\netmiko\base_connection.py", line 641, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "C:\Users\Robert\AppData\Local\Programs\Python\Python38\lib\site-packages\netmiko\base_connection.py", line 574, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

```

When I look in Panorama I can see the command was executed

```

admin@LabPanorama1(primary-active)# show template my_template config network dhcp | match ae2.
set template my_template config  network dhcp interface ae2.710 relay ip server [ 192.168.130.89 192.168.130.90 192.168.200.23 192.168.34.14 ]
set template my_template config  network dhcp interface ae2.710 relay ip enabled yes
```

I thought that maybe there was too much info being sent, so I broke the command down by IP.  But the result is the same

```
for hlpr in helpers:
           hlp_svr = 'set template ' + template + ' config  network dhcp interface ae2.' + vlanid + ' relay ip server ' + hlpr + ' enabled yes'
           device.send_command(hlp_svr)

Traceback (most recent call last):
  File "C:\Users\Robert\AppData\Local\Programs\Python\Python38\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Users\Robert\AppData\Local\Programs\Python\Python38\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Robert\AppData\Local\Programs\Python\Python38\lib\site-packages\netmiko\base_connection.py", line 564, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\Users\Robert\AppData\Local\Programs\Python\Python38\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "C:\Users\Robert\AppData\Local\Programs\Python\Python38\lib\site-packages\netmiko\paloalto\paloalto_panos.py", line 160, in send_command
    return super().send_command(*args, **kwargs)
  File "C:\Users\Robert\AppData\Local\Programs\Python\Python38\lib\site-packages\netmiko\utilities.py", line 347, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "C:\Users\Robert\AppData\Local\Programs\Python\Python38\lib\site-packages\netmiko\base_connection.py", line 1415, in send_command
    new_data = self.read_until_pattern(pattern=re.escape(cmd))
  File "C:\Users\Robert\AppData\Local\Programs\Python\Python38\lib\site-packages\netmiko\base_connection.py", line 641, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "C:\Users\Robert\AppData\Local\Programs\Python\Python38\lib\site-packages\netmiko\base_connection.py", line 574, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

```

In Panorama:

```
admin@LabPanorama1(primary-active)# show template my_template config network dhcp | match ae2.
set template my_template config  network dhcp interface ae2.710 relay ip server 192.168.130.89
set template my_template config  network dhcp interface ae2.710 relay ip enabled yes

```

I thought that maybe it was a bug in the version of netmiko I was using, so I upgraded from netmiko-3.2.0 to netmiko-3.3.2 with no change in behavior.  Any thoughts on how to fix this?  Thanks.

Robert

**Comment by ktbyers** [comment]
Purging old issues...
