### ISSUE TITLE
ValueError Exception Handling

### ISSUE THREAD

**Issue by Gatorjosh14** [ktbyers/netmiko#2078]
Hello ktbyers,

It's been awhile!  I'm running into a unique issue which is breaking my Application.  I'm using the latest Netmiko library and I have built in exception handling.  In particular my exception handling is catching some ValueError's, but apparently not all and I'm not sure why.

For example, I can catch a Failed Secret to go into privilege mode ValueError (enable method), but not able to handle "Router Prompt Not Found" ValueError (set_base_prompt method triggered by redispatch > try_session_preparation methods).  As a result, this is breaking my multiprocessing instance for those set of devices.  The best I can do is a generic "except Exception as e:" clause which captures the RetryError, but my concern is if other major errors occur I'm not sure how that will work out long term.

**Here's more details, so I'm catching this ValueError:**

10.249.129.5 | ValueError("Failed to enter enable mode.   Please ensure you pass the 'secret' argument to ConnectHandler.")
-- | --

**But this one breaks the script and is not being handled properly...**

Process Process-1:
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\tenacity\__init__.py", line 426, in __call__
    result = fn(*args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\netmiko\base_connection.py", line 1149, in set_base_prompt
    raise ValueError(f"Router prompt not found: {repr(prompt)}")
ValueError: Router prompt not found: '[Test-Router ~]$'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Program Files\Python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\P2149451.CHTR\Documents\Python Master Script\PYNDIT_secondary.py", line 316, in __init__
    self.main_process()
  File "c:\Users\P2149451.CHTR\Documents\Python Master Script\PYNDIT_secondary.py", line 567, in main_process
    self.device_main()
  File "c:\Users\P2149451.CHTR\Documents\Python Master Script\PYNDIT_secondary.py", line 717, in device_main
    netmiko.redispatch(self.net_connect, device_type=self.device_type)
  File "C:\Program Files\Python38\lib\site-packages\netmiko\ssh_dispatcher.py", line 335, in redispatch
    obj._try_session_preparation()
  File "C:\Program Files\Python38\lib\site-packages\netmiko\base_connection.py", line 777, in _try_session_preparation
    self.session_preparation()
  File "C:\Program Files\Python38\lib\site-packages\netmiko\cisco\cisco_ios.py", line 24, in session_preparation
    self.set_base_prompt()
    do = self.iter(retry_state=retry_state)
  File "C:\Program Files\Python38\lib\site-packages\tenacity\__init__.py", line 373, in iter
    six.raise_from(retry_exc, fut.exception())
  File "<string>", line 3, in raise_from
tenacity.RetryError: RetryError[<Future at 0x1887cc7edc0 state=finished raised ValueError>]

Thanks for the assistance as always!

**Comment by ktbyers** [comment]
So it looks like it is not finding the device prompt in a context when it expects to find it.

One possibility is try to `fast_cli=False` as an argument to ConnectHandler. It is possible it just is not allocating enough time for your device to respond back.

**Comment by Gatorjosh14** [comment]
Thanks for the response.  Yes, I'm aware what's causing the error to begin with, I'm just trying to figure out why I'm unable to grab the error and handle it directly.  Per my investigation here's what I know.

The original ValueError is caused because some network devices have a bad banner which has the words "username" and "password" referenced which triggers the script incorrectly to think it's logged into the device.  As a result, Netmiko gets lost and can't find the correct Router prompt.

I guess what I'm looking for is a better way to handle the error.  If the ValueError was raised directly, my "try/except" portion could handle it, but it seems raised within Tenacity so my script doesn't recognize the error.  I guess I could import Tenacity and then handle the RetryError, but was hoping for a better solution than that.  For the meantime, just adding "except Exception as e" to the end of my "try/except" script captures the error and no longer breaks my script.

**Comment by ktbyers** [comment]
@Gatorjosh14 You would need to post your code for that. 

The most likely cause is you are using concurrency and the exception is happening in a child process, but you are trying to catch the exception in the main process...and that won't work.


Regards, Kirk

**Comment by ktbyers** [comment]
Closing as this issue looks like it is no longer active.
