### ISSUE TITLE
netmiko not working on Mac Big Sur

### ISSUE THREAD

**Issue by 4ndersson** [ktbyers/netmiko#2081]
VERSIONS
python-3.8.5

Seems to be some issue with pyserial and Mac Big Sur, which breaks netmiko functionality.

When removing `import serial.tools.list_ports` from `netmiko/utilities.py` netmiko seems to be working as expected.

ERROR MESSAGE
``` ******************************************************************************************************************************************************
task path: /Users/andersson/.ansible/collections/ansible_collections/miradot/nxos/roles/parser/tasks/parser.yml:2
<demo-nxos-01> attempting to start connection
<demo-nxos-01> using connection plugin ansible.netcommon.httpapi
<demo-nxos-01> local domain socket does not exist, starting it
<demo-nxos-01> control socket path is /Users/andersson/.ansible/pc/77d8b0ef2c
<demo-nxos-01> local domain socket listeners started successfully
<demo-nxos-01> loaded API plugin ansible_collections.cisco.nxos.plugins.httpapi.nxos from path /Users/andersson/.ansible/collections/ansible_collections/cisco/nxos/plugins/httpapi/nxos.py for network_os cisco.nxos.nxos
<demo-nxos-01>
<demo-nxos-01> local domain socket path is /Users/andersson/.ansible/pc/77d8b0ef2c
<demo-nxos-01> ESTABLISH LOCAL CONNECTION FOR USER: andersson
<demo-nxos-01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/andersson/.ansible/tmp/ansible-local-60465jo4bacoa `"&& mkdir "` echo /Users/andersson/.ansible/tmp/ansible-local-60465jo4bacoa/ansible-tmp-1608666091.392672-60469-59841412560375 `" && echo ansible-tmp-1608666091.392672-60469-59841412560375="` echo /Users/andersson/.ansible/tmp/ansible-local-60465jo4bacoa/ansible-tmp-1608666091.392672-60469-59841412560375 `" ) && sleep 0'
Using module_utils file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible/module_utils/basic.py
Using module_utils file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible/module_utils/parsing/__init__.py
Using module_utils file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible/module_utils/common/text/formatters.py
Using module_utils file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible/module_utils/common/_collections_compat.py
Using module_utils file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible/module_utils/common/_json_compat.py
Using module_utils file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible/module_utils/common/_utils.py
Using module_utils file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible/module_utils/common/parameters.py
Using module_utils file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible/module_utils/common/text/__init__.py
Using module_utils file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible/module_utils/common/__init__.py
Using module_utils file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible/module_utils/_text.py
Using module_utils file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible/module_utils/common/file.py
Using module_utils file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible/module_utils/six/__init__.py
Using module_utils file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible/module_utils/pycompat24.py
Using module_utils file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible/module_utils/common/process.py
Using module_utils file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible/module_utils/compat/selectors.py
Using module_utils file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible/module_utils/common/validation.py
Using module_utils file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible/module_utils/common/text/converters.py
Using module_utils file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible/module_utils/common/sys_info.py
Using module_utils file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible/module_utils/compat/__init__.py
Using module_utils file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible/module_utils/common/collections.py
Using module_utils file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible/module_utils/compat/_selectors2.py
Using module_utils file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible/module_utils/distro/__init__.py
Using module_utils file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible/module_utils/distro/_distro.py
Using module file /Users/andersson/.ansible/collections/ansible_collections/miradot/nxos/plugins/modules/parser.py
<demo-nxos-01> PUT /Users/andersson/.ansible/tmp/ansible-local-60465jo4bacoa/tmpi5qasr73 TO /Users/andersson/.ansible/tmp/ansible-local-60465jo4bacoa/ansible-tmp-1608666091.392672-60469-59841412560375/AnsiballZ_parser.py
<demo-nxos-01> EXEC /bin/sh -c 'chmod u+x /Users/andersson/.ansible/tmp/ansible-local-60465jo4bacoa/ansible-tmp-1608666091.392672-60469-59841412560375/ /Users/andersson/.ansible/tmp/ansible-local-60465jo4bacoa/ansible-tmp-1608666091.392672-60469-59841412560375/AnsiballZ_parser.py && sleep 0'
<demo-nxos-01> EXEC /bin/sh -c '/usr/bin/python3 /Users/andersson/.ansible/tmp/ansible-local-60465jo4bacoa/ansible-tmp-1608666091.392672-60469-59841412560375/AnsiballZ_parser.py && sleep 0'
<demo-nxos-01> EXEC /bin/sh -c 'rm -f -r /Users/andersson/.ansible/tmp/ansible-local-60465jo4bacoa/ansible-tmp-1608666091.392672-60469-59841412560375/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/Users/andersson/.ansible/tmp/ansible-local-60465jo4bacoa/ansible-tmp-1608666091.392672-60469-59841412560375/AnsiballZ_parser.py", line 102, in <module>
    _ansiballz_main()
  File "/Users/andersson/.ansible/tmp/ansible-local-60465jo4bacoa/ansible-tmp-1608666091.392672-60469-59841412560375/AnsiballZ_parser.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/andersson/.ansible/tmp/ansible-local-60465jo4bacoa/ansible-tmp-1608666091.392672-60469-59841412560375/AnsiballZ_parser.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.miradot.nxos.plugins.modules.parser', init_globals=None, run_name='__main__', alter_sys=True)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/folders/ys/c8j8l1ms5x94nc82klphsk7w0000gn/T/ansible_miradot.nxos.parser_payload_lhosn7ha/ansible_miradot.nxos.parser_payload.zip/ansible_collections/miradot/nxos/plugins/modules/parser.py", line 5, in <module>
  File "/Users/andersson/Library/Python/3.7/lib/python/site-packages/napalm/__init__.py", line 5, in <module>
    from napalm.base import get_network_driver
  File "/Users/andersson/Library/Python/3.7/lib/python/site-packages/napalm/base/__init__.py", line 22, in <module>
    from napalm.base.base import NetworkDriver
  File "/Users/andersson/Library/Python/3.7/lib/python/site-packages/napalm/base/base.py", line 17, in <module>
    from netmiko import ConnectHandler, NetMikoTimeoutException
  File "/Users/andersson/Library/Python/3.7/lib/python/site-packages/netmiko/__init__.py", line 7, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "/Users/andersson/Library/Python/3.7/lib/python/site-packages/netmiko/ssh_dispatcher.py", line 2, in <module>
    from netmiko.a10 import A10SSH
  File "/Users/andersson/Library/Python/3.7/lib/python/site-packages/netmiko/a10/__init__.py", line 1, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "/Users/andersson/Library/Python/3.7/lib/python/site-packages/netmiko/a10/a10_ssh.py", line 3, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "/Users/andersson/Library/Python/3.7/lib/python/site-packages/netmiko/cisco_base_connection.py", line 2, in <module>
    from netmiko.base_connection import BaseConnection
  File "/Users/andersson/Library/Python/3.7/lib/python/site-packages/netmiko/base_connection.py", line 27, in <module>
    from netmiko.utilities import (
  File "/Users/andersson/Library/Python/3.7/lib/python/site-packages/netmiko/utilities.py", line 8, in <module>
    import serial.tools.list_ports
  File "/Users/andersson/Library/Python/3.7/lib/python/site-packages/serial/tools/list_ports.py", line 29, in <module>
    from serial.tools.list_ports_posix import comports
  File "/Users/andersson/Library/Python/3.7/lib/python/site-packages/serial/tools/list_ports_posix.py", line 31, in <module>
    from serial.tools.list_ports_osx import comports
  File "/Users/andersson/Library/Python/3.7/lib/python/site-packages/serial/tools/list_ports_osx.py", line 33, in <module>
    kIOMasterPortDefault = ctypes.c_void_p.in_dll(iokit, "kIOMasterPortDefault")
ValueError: dlsym(RTLD_DEFAULT, kIOMasterPortDefault): symbol not found
fatal: [demo-nxos-01]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/Users/andersson/.ansible/tmp/ansible-local-60465jo4bacoa/ansible-tmp-1608666091.392672-60469-59841412560375/AnsiballZ_parser.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/Users/andersson/.ansible/tmp/ansible-local-60465jo4bacoa/ansible-tmp-1608666091.392672-60469-59841412560375/AnsiballZ_parser.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/andersson/.ansible/tmp/ansible-local-60465jo4bacoa/ansible-tmp-1608666091.392672-60469-59841412560375/AnsiballZ_parser.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.miradot.nxos.plugins.modules.parser', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/ys/c8j8l1ms5x94nc82klphsk7w0000gn/T/ansible_miradot.nxos.parser_payload_lhosn7ha/ansible_miradot.nxos.parser_payload.zip/ansible_collections/miradot/nxos/plugins/modules/parser.py\", line 5, in <module>\n  File \"/Users/andersson/Library/Python/3.7/lib/python/site-packages/napalm/__init__.py\", line 5, in <module>\n    from napalm.base import get_network_driver\n  File \"/Users/andersson/Library/Python/3.7/lib/python/site-packages/napalm/base/__init__.py\", line 22, in <module>\n    from napalm.base.base import NetworkDriver\n  File \"/Users/andersson/Library/Python/3.7/lib/python/site-packages/napalm/base/base.py\", line 17, in <module>\n    from netmiko import ConnectHandler, NetMikoTimeoutException\n  File \"/Users/andersson/Library/Python/3.7/lib/python/site-packages/netmiko/__init__.py\", line 7, in <module>\n    from netmiko.ssh_dispatcher import ConnectHandler\n  File \"/Users/andersson/Library/Python/3.7/lib/python/site-packages/netmiko/ssh_dispatcher.py\", line 2, in <module>\n    from netmiko.a10 import A10SSH\n  File \"/Users/andersson/Library/Python/3.7/lib/python/site-packages/netmiko/a10/__init__.py\", line 1, in <module>\n    from netmiko.a10.a10_ssh import A10SSH\n  File \"/Users/andersson/Library/Python/3.7/lib/python/site-packages/netmiko/a10/a10_ssh.py\", line 3, in <module>\n    from netmiko.cisco_base_connection import CiscoSSHConnection\n  File \"/Users/andersson/Library/Python/3.7/lib/python/site-packages/netmiko/cisco_base_connection.py\", line 2, in <module>\n    from netmiko.base_connection import BaseConnection\n  File \"/Users/andersson/Library/Python/3.7/lib/python/site-packages/netmiko/base_connection.py\", line 27, in <module>\n    from netmiko.utilities import (\n  File \"/Users/andersson/Library/Python/3.7/lib/python/site-packages/netmiko/utilities.py\", line 8, in <module>\n    import serial.tools.list_ports\n  File \"/Users/andersson/Library/Python/3.7/lib/python/site-packages/serial/tools/list_ports.py\", line 29, in <module>\n    from serial.tools.list_ports_posix import comports\n  File \"/Users/andersson/Library/Python/3.7/lib/python/site-packages/serial/tools/list_ports_posix.py\", line 31, in <module>\n    from serial.tools.list_ports_osx import comports\n  File \"/Users/andersson/Library/Python/3.7/lib/python/site-packages/serial/tools/list_ports_osx.py\", line 33, in <module>\n    kIOMasterPortDefault = ctypes.c_void_p.in_dll(iokit, \"kIOMasterPortDefault\")\nValueError: dlsym(RTLD_DEFAULT, kIOMasterPortDefault): symbol not found\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP *************************************************************************************************************************************************************************************************
demo-nxos-01               : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```

**Comment by ktbyers** [comment]
I would try to reinstall `pyserial` and see if it works?

**Comment by applericky** [comment]
I can verify this worked for me.

https://github.com/ktbyers/netmiko/issues/2081#issuecomment-749828904
