### ISSUE TITLE
Connect to console after SSH

### ISSUE THREAD

**Issue by brentr678** [ktbyers/netmiko#2107]
Hello all, i'm trying to write a python script that will perform various Cisco IOS commands after logging in. Where things get tricky is to access the switch, i first SSH to a console server, then interact with the console port. As of now, the script connects to the console server fine, but it fails to interact with the switch. From what I can tell, its waiting for a prompt that will never come. My hope was to send individual commands after logging into the console server that would then get me into the switch prompt. Specifically those commands are; _enter_, Username:, Password:, _enter_. 

The problem is the send_command string doesn't seem to execute. It looks like its waiting for a switch prompt before sending the command. But the switch wont show a username prompt until enter is pressed. So the command gets stuck in an endless loop. Is there a way to force a new line or enter command regardless of what netmiko is seeing for a router prompt? For those of you unfamiliar with Cisco console, the screen looks like this below until the enter key is pressed. Notice the large space after each line of text. 

hostname con0 is now available

Press RETURN to get started.

The lines of code i'm trying to use to accomplish this right now are:
        c = ConnectHandler(**switch,fast_cli=False,verbose=True,auto_connect=False)
        c.establish_connection()
        c.send_command("")

Any thoughts would be greatly appreciated!

**Comment by ktbyers** [comment]
Look at the expect_string argument to `send_command` or alternatively look at send_command_timing:

https://github.com/ktbyers/netmiko/blob/develop/EXAMPLES.md#handling-commands-that-prompt-expect_string

And:

https://github.com/ktbyers/netmiko/blob/develop/EXAMPLES.md#handling-commands-that-prompt-timing


Regards, Kirk

**Comment by brentr678** [comment]
Neither of those two arguments help in this situation. I can't put in an expect string when there is no string to expect. And timing just sits and doesn't process. Looking further through the threads its a very similar setup to this issue:
https://github.com/ktbyers/netmiko/issues/383
However, in my case its still not processing the character return.

**Comment by ktbyers** [comment]
What happens if you do this:

```python
import time

c = ConnectHandler(**switch,fast_cli=False,verbose=True,auto_connect=False)
c.write_channel("\n")
time.sleep(1)
output = c.read_channel()
print(output)
```

**Comment by brentr678** [comment]
I think i've sorted it. I used what you have above, but ended up adding a while condition to keep writing \n until it received a response from read_channel(). There doesn't seem to be any consistency on the number of "enter" commands given to a console connection before it wakes up the device so the loop helps with that. But thats not a netmiko problem obviously. Appreciate the help!

**Comment by mewpeh** [comment]
Hi!
I have this issue atm.
We have a console-hub by airconsole.

And I struggle hard to get from the ssh connection to the console-connection.
As you have mentioned it wants me to press "Enter" and then insert the "Username" and "Password" for the serial connection.

Any Idea how to make this work?
also not sure what 'device_type' to use for the airconsole

code:
```
from netmiko import ConnectHandler
import time

Fack1 = {
    'device_type': 'cisco_ios',
    'host':   '10.12.5.67',
    'username': 'admin',
    'password': '*******',
    'port' : 4001,
}


c = ConnectHandler(**Fack1,fast_cli=False,verbose=True,auto_connect=False)
c.write_channel("\n")
time.sleep(1)
output = c.read_channel()
print(output)
```
Error:
`C:****\python\TPO-testing\FE-ISP\Scripts\python.exe C:/Users/Anton/IdeaProjects/FE-ISP/Testing/conf-hub.py
Traceback (most recent call last):
  File "C:****\IdeaProjects\FE-ISP\Testing\conf-hub.py", line 15, in <module>
    c.write_channel("\n")
  File "C:****\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\base_connection.py", line 459, in write_channel
    self._write_channel(out_data)
  File "C****\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\base_connection.py", line 417, in _write_channel
    self.remote_conn.sendall(write_bytes(out_data, encoding=self.encoding))
AttributeError: 'NoneType' object has no attribute 'sendall'`

I'm a complete newb to this.

Regards,
mewpeh

**Comment by brentr678** [comment]
Hello,
Interacting with the console can be tricky. And full disclosure the method I use i've still seen failures on from time to time, but I attribute that to our console server (Opengear) not necessarily the script. That said here is the code i've adapted:

connection = ConnectHandler(**switch,fast_cli=False,auto_connect=False)
connection.establish_connection()
screen = ""   
while not (("Username:") in screen):
    c.write_channel('\r')       
    time.sleep(2)
    screen = c.read_channel()



In my switch statement i'm using the 'cisco_ios' device type for no other reason then it seemed to work fine and the device connected behind the Opengear was a cisco IOS. Hope that helps.
