### ISSUE TITLE
SSH0: Session disconnected - error 0x07 [I am running Python39]

### ISSUE THREAD

**Issue by gomens** [ktbyers/netmiko#2157]
Python code connect to device then disconnect automatically:
Here is an excerpt of my code.  Any help fixing this issue?
Thank you in advance.

    ios_device = {
        'device_type': 'cisco_ios',
        'ip': ip_address_of_device, 
        'username': username,
        'password': password,
        'port': 22,
        'verbose': True 
    }
        net_connect = ConnectHandler(**ios_device)
        print (net_connect.find_prompt())
        print (net_connect.find_prompt())

Some lines of debug
---------------------------------
*Feb 13 05:39:15.793: SSH2 0: authentication successful for <username>
*Feb 13 05:39:15.793: %SEC_LOGIN-5-LOGIN_SUCCESS: Login Success [user: <username>] [Source: xxx.xxx.xxx.xxx] [localport: 22] at 23:39:15 CST Fri Feb 12 2021
*Feb 13 05:39:15.831: SSH2 0: channel open request
*Feb 13 05:39:15.873: SSH2 0: pty-req request
*Feb 13 05:39:15.873: SSH2 0: setting TTY - requested: height 1000, width 511; set: height 1000, width 511
*Feb 13 05:39:15.931: SSH2 0: shell request
*Feb 13 05:39:15.931: SSH2 0: shell message received
*Feb 13 05:39:15.931: SSH2 0: starting shell for vty
*Feb 13 05:39:36.321: %SYS-6-LOGOUT: User <username> has exited tty session 2(10.48.46.3)
*Feb 13 05:39:36.421: SSH0: Session disconnected - error 0x07

Some traceback of VS Code
---------------------------------
Interactive SSH session established
Traceback (most recent call last):
  File "...\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\channel.py", line 699, in recv      
    out = self.in_buffer.read(nbytes, self.timeout)
  File "...\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\base_connection.py", line 569, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "...\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\base_connection.py", line 1837, in send_config_set
    output += self.config_mode(*cfg_mode_args)
  File "...\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\cisco_base_connection.py", line 40, in config_mode
    return super().config_mode(
  File "...\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\base_connection.py", line 1721, in config_mode   
    if not self.check_config_mode():
  File "...\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\cisco\cisco_ios.py", line 32, in check_config_mode
    return super().check_config_mode(check_string=check_string, pattern=pattern)
  File "...\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\cisco_base_connection.py", line 30, in check_config_mode
    return super().check_config_mode(check_string=check_string, pattern=pattern)
  File "...\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\base_connection.py", line 1705, in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "...\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\base_connection.py", line 646, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "...\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\base_connection.py", line 579, in _read_channel_expect
  File "...\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\base_connection.py", line 579, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

**Comment by ktbyers** [comment]
Can you see if you can capture the Netmiko logging information?

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

I can't really see from the above what is causing it to fail.

**Comment by gomens** [comment]
HiKirk Byers, 
After I called enable() method and specified secret at login as you suggested in a separate post, my script worked great. You are the man!
