### ISSUE TITLE
Entering config mode with long hostname fails.

### ISSUE THREAD

**Issue by baileytj3** [ktbyers/netmiko#216]
I was unsure whether this was related to #212. When entering config mode with an exceptionally long hostname on a Cisco switch, the switch truncates the prompt and appends the '(config)' text. This causes the following stack trace when config_mode() is called.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/netmiko/ssh_connection.py", line 27, in config_mode
    return super(SSHConnection, self).config_mode(config_command=config_command)
  File "/usr/lib/python2.6/site-packages/netmiko/base_connection.py", line 541, in config_mode
    if not self.check_config_mode():
  File "/usr/lib/python2.6/site-packages/netmiko/ssh_connection.py", line 23, in check_config_mode
    return super(SSHConnection, self).check_config_mode(check_string=check_string)
  File "/usr/lib/python2.6/site-packages/netmiko/base_connection.py", line 535, in check_config_mode
    output = self.read_until_prompt()
  File "/usr/lib/python2.6/site-packages/netmiko/base_connection.py", line 354, in read_until_prompt
    return self.read_until_pattern()
  File "/usr/lib/python2.6/site-packages/netmiko/base_connection.py", line 368, in read_until_pattern
    raise NetMikoTimeoutException("Timed-out reading channel, data not available.")
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.
```
Prompt as seen from manual ssh session to the switch.
```
012345678901234567890123456789#config t
Enter configuration commands, one per line.  End with CNTL/Z.
01234567890123456789(config)#
```
The prompt changes and the original prompt is never found. I would suspect that the calling self.set_base_prompt() after self.remote_conn.sendall() in the following method would correct this issue, but I have yet to test it.

```
def config_mode(self, config_command=''):                                   
    """Enter into config_mode."""                                           
    output = ''                                                             
    if not self.check_config_mode():                                        
        self.remote_conn.sendall(self.normalize_cmd(config_command))        
        output = self.read_until_prompt()                                   
        if not self.check_config_mode():                                    
            raise ValueError("Failed to enter configuration mode.")         
    return output
```

**Comment by baileytj3** [comment]
I'm sure you can come up with a more elegant solution but this is what I cooked up being unfamiliar with most of the code base. This issue also presents itself in config_mode_exit().
```
    def config_mode(self, config_command=''):
        """Enter into config_mode."""
        output = ''
        if not self.check_config_mode():
            self.remote_conn.sendall(self.normalize_cmd(config_command))  
            for tmp_output in self.receive_data_generator():
                output += tmp_output
            self.set_base_prompt()
            if not self.check_config_mode():
                raise ValueError("Failed to enter configuration mode.")
        return output
```

**Comment by ktbyers** [comment]
@baileytj3 This should be fixed in this issue https://github.com/ktbyers/netmiko/issues/210

What version of Netmiko are you using? Make sure you are using Netmiko >=0.5.1

If you are still having this issue just re-open this.

**Comment by baileytj3** [comment]
Ah, thanks. I looked through open Bugs but not closed ones. I was on 0.4.3, I'll upgrade and see if I have any issues. Thanks!
