### ISSUE TITLE
cisco_ios get_remote_file_size does not properly handle remote files that are in subdirectories

### ISSUE THREAD

**Issue by anitrajpurohit28** [ktbyers/netmiko#2168]
**what am I trying to achieve?**
>Copy a file from the cisco ios router to the Linux server, where I am running this script

I've hardcoded the source_file and dest_file to ease of understanding
the file does exist in the specified path and appropriate permission are given

**script file**
```
from netmiko import ConnectHandler, file_transfer

cisco_ios_details = {'device_type': 'cisco_ios',
                     'host': 'xx.xx.xx.xx',
                     'username': '*****',
                     'password': '*****',
                     'fast_cli': False}

def transfer_file_from_ios_current_directory():
    device_connector = ConnectHandler(**cisco_ios_details)
    try:
        return_dict = file_transfer(device_connector,
                                    source_file="guest-share/example_ios.json",
                                    dest_file='./example_linux.json',
                                    direction='get',
                                    file_system='flash:',
                                    overwrite_file=True)
        print(return_dict)
    except Exception as e:
        print('Unable to transfer.\nReason: {}'.format(e))

    device_connector.disconnect()


transfer_file_from_ios_current_directory()
```
**Output:**
```
Unable to transfer.
Reason: local variable 'file_size' referenced before assignment
```

**The file is present in router**
```
CSR#dir flash:guest-share/example_ios.json
Directory of bootflash:guest-share/example_ios.json

431424  -rw-             7115  Feb 27 2021 06:44:17 +00:00  example_ios.json
```

**Comment by ktbyers** [comment]
Can you remove your try/except and post the full stack trace so I can see where the error is occurring?


Kirk

**Comment by anitrajpurohit28** [comment]
After getting rid of try/except, following is the traceback


```
/Users/anbabula/.pyenv/shims/python "/Users/anbabula/Library/Application Support/JetBrains/PyCharmCE2020.3/scratches/scratch_10.py"
Traceback (most recent call last):
  File "/Users/anbabula/Library/Application Support/JetBrains/PyCharmCE2020.3/scratches/scratch_10.py", line 29, in <module>
    transfer_file_from_ios_current_directory()
  File "/Users/anbabula/Library/Application Support/JetBrains/PyCharmCE2020.3/scratches/scratch_10.py", line 23, in transfer_file_from_ios_current_directory
    overwrite_file=True)
  File "/Users/anbabula/.pyenv/versions/3.6.12/lib/python3.6/site-packages/netmiko/scp_functions.py", line 107, in file_transfer
    with TransferClass(**scp_args) as scp_transfer:
  File "/Users/anbabula/.pyenv/versions/3.6.12/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 347, in FileTransfer
    return FileTransferClass(*args, **kwargs)
  File "/Users/anbabula/.pyenv/versions/3.6.12/lib/python3.6/site-packages/netmiko/scp_handler.py", line 111, in __init__
    self.file_size = self.remote_file_size(remote_file=source_file)
  File "/Users/anbabula/.pyenv/versions/3.6.12/lib/python3.6/site-packages/netmiko/scp_handler.py", line 263, in remote_file_size
    return int(file_size)
UnboundLocalError: local variable 'file_size' referenced before assignment

Process finished with exit code 1

```

**Version:**

```
% pip freeze | grep netmiko
netmiko==3.3.3
```

**Comment by ktbyers** [comment]
What does `dir` show on the remote network device?

**Comment by anitrajpurohit28** [comment]
With the following function, I'm able to see the file we are trying to transfer
```
def directory_contents():
    device_connector = ConnectHandler(**cisco_ios_details)
    exec_command = "dir flash:guest-share/"
    out = device_connector.send_command(exec_command, expect_string=device_connector.find_prompt())
    print(out)
    device_connector.disconnect()
    
directory_contents()
```

Snip of Output:

```
Output of command dir flash:guest-share/:
Directory of bootflash:guest-share/

....
430787  drwx             4096   Mar 1 2021 00:36:06 +00:00  logs
431424  -rw-             7115  Feb 27 2021 06:44:17 +00:00  example_ios.json
431423  -rwx             7117  Feb 25 2021 19:44:32 +00:00  cubeMgmtDB.json
....

7897796608 bytes total (3257065472 bytes free)
```

**Comment by ktbyers** [comment]
I think it is probably failing on the subdirectory part of this:

```
source_file="guest-share/example_ios.json",
```

I suspect the `get_remote_file_size` is not properly handling that.

**Comment by ktbyers** [comment]
Fixed in associated PR.
