### ISSUE TITLE
Unable to Log into Ciena through a Jump Server

### ISSUE THREAD

**Issue by adrjoy** [ktbyers/netmiko#2174]
jumpserver_details = {
'device_type': 'terminal_server',
'ip': 'xx.xx.xx.xx',
'username': xxxxx,
'password': xxxxx,
'global_delay_factor':5}

net_connect = ConnectHandler(**jumpserver_details)
output = net_connect.send_command("telnet %s" % switch, expect_string='login:')
output += net_connect.send_command(jumpserver_details['username'], expect_string='password:')
output += net_connect.send_command_timing(jumpserver_details['password'])

redispatch(net_connect, device_type="ciena_saos")

I am getting the following error at redispatch

RetryError[<Future at 0x3e3e5e0 state=finished raised ValueError>]

Any idea what may be wrong as the code works with Cisco  with the expected_String changes to cisco strings

**Comment by ktbyers** [comment]
Can you show what this full login process looks like when you do it manually.

Also can you post the full exception stack trace.

**Comment by adrjoy** [comment]
The login process is below

switch ='xx.xx.xx.xx'

jumpserver_details = {
'device_type': 'terminal_server',
'ip': 'xx.xx.xx.xx',
'username': input("Username:"),
'password': getpass.getpass(),
'global_delay_factor':5}

try:      
    net_connect = ConnectHandler(**jumpserver_details)
except Exception as error:
    traceback.print_exc()
 
try:
    logging.warning("Telnet into %s" % switch)
    output = net_connect.send_command("telnet %s" % switch, expect_string='login:')
    time.sleep(9)
    logging.warning("Sending Username")
    output = net_connect.send_command(jumpserver_details['username'], expect_string='Password:')
    time.sleep(9)
    logging.warning("Sending Password")
    output = net_connect.send_command_timing(jumpserver_details['password'])
    logging.warning("Logged in!")

except Exception as error:
    traceback.print_exc()

try:
   redispatch(net_connect, device_type="ciena_saos")
except Exception as error:
   traceback.print_exc()


logging.warning("Exiting from %s" % switch)
try:
   ciena_exit(net_connect)
  
except Exception as error:
      traceback.print_exc()

**Comment by adrjoy** [comment]
the full exception stack trace.

Traceback (most recent call last):
  File "C:\..\Programs\Python\Python38-32\lib\site-packages\tenacity\__init__.py", line 426, in __call__
    result = fn(*args, **kwargs)
  File "C:\..\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 1149, in set_base_prompt
    raise ValueError(f"Router prompt not found: {repr(prompt)}")
ValueError: Router prompt not found: 'xx-ciena-test login:'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\..\Python/Ciena_test/ciena_login.py", line 46, in <module>
    redispatch(net_connect, device_type="ciena_saos")
  File "C:\..\Programs\Python\Python38-32\lib\site-packages\netmiko\ssh_dispatcher.py", line 329, in redispatch
    obj._try_session_preparation()
  File "C:\..\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 777, in _try_session_preparation
    self.session_preparation()
  File "C:\..\Programs\Python\Python38-32\lib\site-packages\netmiko\ciena\ciena_saos.py", line 21, in session_preparation
    self.set_base_prompt()
  File "C:\..\Programs\Python\Python38-32\lib\site-packages\tenacity\__init__.py", line 333, in wrapped_f
    return self(f, *args, **kw)
  File "C:\..\Programs\Python\Python38-32\lib\site-packages\tenacity\__init__.py", line 423, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\..\Programs\Python\Python38-32\lib\site-packages\tenacity\__init__.py", line 373, in iter
    six.raise_from(retry_exc, fut.exception())
  File "<string>", line 3, in raise_from
tenacity.RetryError: RetryError[<Future at 0x45cd358 state=finished raised ValueError>]

2021-03-04 11:28:02.457 WARNING ciena_login - <module>: Sending commands to xx.xx.xx.xx
Traceback (most recent call last):
  File "c:\..\Python/Ciena_test/ciena_login.py", line 52, in <module>
    output=net_connect.send_command('config show brief')
  File "C:\..\Programs\Python\Python38-32\lib\site-packages\netmiko\utilities.py", line 429, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "C:\..\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 1463, in send_command
    prompt = self.find_prompt(delay_factor=delay_factor)
  File "C:\..\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 1161, in find_prompt
    self.clear_buffer()
  File "C:\..\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 1199, in clear_buffer
    data = self.read_channel()
  File "C:\..\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 522, in read_channel
    output = self._read_channel()
  File "C:\..\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 496, in _read_channel
    if self.remote_conn.recv_ready():
AttributeError: 'NoneType' object has no attribute 'recv_ready'

**Comment by ktbyers** [comment]
Yeah, I was interested in seeing what the login process looked like when you do it manually outside of Netmiko.

**Comment by ktbyers** [comment]
You should also update your code so that it does NOT keep going when you get an exception. Your code is hiding where the original error happens.

So add a `raise` statement in each one of the try/excepts (or just completely get rid of the try/excepts and let the exception happen.

**Comment by ktbyers** [comment]
Yeah, I think you are probably failing to actually login with your code here. You might want to enable the Netmiko session_log so you can see better what is happening.

```
    logging.warning("Telnet into %s" % switch)
    output = net_connect.send_command("telnet %s" % switch, expect_string="login:")
    time.sleep(9)
    logging.warning("Sending Username")
    output = net_connect.send_command(
        jumpserver_details["username"], expect_string="Password:"
    )
    time.sleep(9)
    logging.warning("Sending Password")
    output = net_connect.send_command_timing(jumpserver_details["password"])
    logging.warning("Logged in!")
```


Regards, Kirk

**Comment by adrjoy** [comment]
Strange thing is , it works every now and again ,Probably 5% of the time.I'll enable the Netmiko sessions and see what is happening

**Comment by adrjoy** [comment]
Hi Ktbyers
Iooks like as you said ,that the ciena is getting the incorrect login details, I am wondering how you would approach it.
 Thanks

**Comment by ktbyers** [comment]
@adrjoy Did you look at the Netmiko session_log to get a better understanding of why it was failing?

**Comment by ktbyers** [comment]
@adrjoy Any update here on looking at the Netmiko session_log?

I am going to close this. Let me know if you have other questions here.

**Comment by adrjoy** [comment]
Still having no success , I'll work though it to see if I can figure it
out
