### ISSUE TITLE
ValueError: Router prompt not found: '-bash-4.2$'

### ISSUE THREAD

**Issue by narasimha928** [ktbyers/netmiko#2176]
Hi Kirk,

when i use netmiko library file for connecting the Linux server i see below exception.
could you please let me know work around.

Traceback (most recent call last):
  File "/Users/nnelluri/python3-proj/lib/python3.8/site-packages/tenacity/__init__.py", line 433, in __call__
    result = fn(*args, **kwargs)
  File "/Users/nnelluri/python3-proj/lib/python3.8/site-packages/netmiko/base_connection.py", line 1160, in set_base_prompt
    raise ValueError(f"Router prompt not found: {repr(prompt)}")
ValueError: Router prompt not found: '-bash-4.2$'

Thanks
Narasimha

**Comment by ktbyers** [comment]
You probably need to look at the Netmiko session_log or Netmiko logging to get more details about why it isn't seeing a given prompt.
