### ISSUE TITLE
import netmiko not working in IDLE

### ISSUE THREAD

**Issue by kp-time** [ktbyers/netmiko#2216]
HI All,

getting below erro while trying to run python code through IDLE.. Started after installing Textfasm..  Please help me to fix

IDLE:
>>> import netmiko
Traceback (most recent call last):
  File "C:\Users\krish\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko-3.3.3-py3.9.egg\netmiko\_textfsm\_clitable.py", line 37, in <module>
    from textfsm import copyable_regex_object
  File "C:\Users\krish\OneDrive\Desktop\aft-gap\krik_python\textfsm.py", line 1, in <module>
    from netmiko import Netmiko
ImportError: cannot import name 'Netmiko' from 'netmiko' (C:\Users\krish\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko-3.3.3-py3.9.egg\netmiko\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    import netmiko
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\krish\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko-3.3.3-py3.9.egg\netmiko\__init__.py", line 7, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\krish\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko-3.3.3-py3.9.egg\netmiko\ssh_dispatcher.py", line 2, in <module>
    from netmiko.a10 import A10SSH
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\krish\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko-3.3.3-py3.9.egg\netmiko\a10\__init__.py", line 1, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\krish\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko-3.3.3-py3.9.egg\netmiko\a10\a10_ssh.py", line 3, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\krish\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko-3.3.3-py3.9.egg\netmiko\cisco_base_connection.py", line 2, in <module>
    from netmiko.base_connection import BaseConnection
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\krish\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko-3.3.3-py3.9.egg\netmiko\base_connection.py", line 28, in <module>
    from netmiko.utilities import (
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\krish\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko-3.3.3-py3.9.egg\netmiko\utilities.py", line 9, in <module>
    from netmiko._textfsm import _clitable as clitable
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\krish\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko-3.3.3-py3.9.egg\netmiko\_textfsm\__init__.py", line 3, in <module>
    from netmiko._textfsm import _clitable
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\krish\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko-3.3.3-py3.9.egg\netmiko\_textfsm\_clitable.py", line 40, in <module>
    import copyable_regex_object
ModuleNotFoundError: No module named 'copyable_regex_object'
>>> 

CMD:
C:\Users\krish>py
Python 3.9.4 (tags/v3.9.4:1f2e308, Apr  4 2021, 13:27:16) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import netmiko
>>>

bcrypt==3.2.0
cffi==1.14.5
cryptography==3.4.7
future==0.18.2
netmiko==3.3.3
ntc-templates==2.0.0
numpy==1.20.2
paramiko==2.7.2
pycparser==2.20
pynacl==1.4.0
pyserial==3.5
scp==0.13.3
six==1.15.0
tenacity==7.0.0
textfsm==1.1.0

**Comment by ktbyers** [comment]
You have a file named `textfsm.py`. You can't name the file that as it is conflicting with the `textfsm` library (which netmiko uses). You need to rename this file and remove any textfsm.pyc files.


Regards, Kirk

**Comment by kp-time** [comment]
> You have a file named `textfsm.py`. You can't name the file that as it is conflicting with the `textfsm` library (which netmiko uses). You need to rename this file and remove any textfsm.pyc files.
> 
> Regards, Kirk

Thank you so much Ktbyers.. able to run now
