### ISSUE TITLE
Dell Force10 s60 login issue 

### ISSUE THREAD

**Issue by Damon92** [ktbyers/netmiko#2267]
```python
from netmiko import ConnectHandler

connection_info = {
        'device_type': 'dell_force10',
        'host': '10.116.0.101',
        'username': 'list',
        'password': "list.com"
}
with ConnectHandler(**connection_info) as conn1:
    out = conn1.send_command("show mac-address-table ")
    print(out)
```

ouput issue
Oops, unhandled type 3 ('unimplemented')
Traceback (most recent call last):
  File "dell.py", line 9, in <module>
    with ConnectHandler(**connection_info) as conn1:
  File "/usr/local/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 326, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 350, in __init__
    self._open()
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 355, in _open
    self.establish_connection()
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 989, in establish_connection
    term="vt100", width=width, height=height
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 545, in invoke_shell
    chan = self._transport.open_session()
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 879, in open_session
    timeout=timeout,
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 1006, in open_channel
    raise e
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 2055, in run
    ptype, m = self.packetizer.read_message()
  File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 459, in read_message
    header = self.read_all(self.__block_size_in, check_rekey=True)
  File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 303, in read_all
    raise EOFError()
EOFError

**Comment by vivekvashist** [comment]
There is a typo in your code conn1 vs conni1.

**Comment by Damon92** [comment]
> There is a typo in your code conn1 vs conni1.
Sorry, the editor is to press i more.

**Comment by ktbyers** [comment]
Yeah, don't know on this...this is a bit of a weird error.

It fails on the opening of the SSH connection.

You probably need to grab the Netmiko log file to see if that gives us any more clues:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by ktbyers** [comment]
Not enough information here
