### ISSUE TITLE
ConnectHandler() Fails to Return Instance if Setup Commands Fail

### ISSUE THREAD

**Issue by Suterusu1337** [ktbyers/netmiko#2273]
I have a telnet session with limited command access.  It appears the 'terminal width 511' is failing due to command authorization and the ConnectHandler() call returns None.

Is there a way to avoid this behavior/startup sequence?  I may not be able to have access to the terminal commands in this environment.

```python
net_connect = ConnectHandler(device_type=device_type,
                                    host=dev['ip_address'],
                                    username=credentials['username'],
                                    password=credentials['password'],
                                    secret=credentials['secret'],
                                    port=3001,
                                    timeout=timeout_value)
```

```
Timed-out reading channel, pattern not found in output: terminal\ length\ 0
Traceback (most recent call last):
  File "xxxxxxxx_sh_ip_route.py", line 65, in <module>
    update(xxxxxx)
  File "xxxxxxxxxx_sh_ip_route.py", line 48, in update
    if not dev['conn'].is_alive():
AttributeError: 'NoneType' object has no attribute 'is_alive'
```

```
Username: 
DEBUG:netmiko:write_channel: b'xxxxxxxxx\r'
DEBUG:netmiko:read_channel: xxxxxxxxx
Password: 
DEBUG:netmiko:write_channel: b'xxxxxxxxx\r'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
C
xxxxxxxxxxxxxxxxxx 

xxxxxxx#
xxxxxxx#
DEBUG:netmiko:write_channel: b'terminal width 511\r\n'
DEBUG:netmiko:Pattern is: terminal width 511
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: termi
DEBUG:netmiko:read_channel: nal wi
DEBUG:netmiko:read_channel: dth 51
DEBUG:netmiko:read_channel: 1

DEBUG:netmiko:Pattern found: terminal width 511 terminal width 511

DEBUG:netmiko:In disable_paging
DEBUG:netmiko:Command: terminal length 0

DEBUG:netmiko:write_channel: b'terminal length 0\r\n'
DEBUG:netmiko:Pattern is: terminal\ length\ 0
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: Command authorization failed.

xxxxxxxx#te
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: rminal length 0

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: xxxxxxxxx#
xxxxxxxxx#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'exit\r\n'
DEBUG:netmiko:read_channel: CC
```

**Comment by ktbyers** [comment]
Can you post the full exception stack trace?

Also can you post the fuller section of code? Where is the `is_alive()` call coming from?

**Comment by Suterusu1337** [comment]
```python
def connect(dev: dict):
    credentials = {
        'username': 'xxxxx',
        'password': 'xxxxx',
        'secret': 'xxxxx'
    }
    device_type = 'cisco_ios_telnet'
    timeout_value = 3
    print(f"{datetime.datetime.now()}  Connecting to {dev['hostname']} at IP {dev['ip_address']}")
    try:
        net_connect = ConnectHandler(device_type=device_type,
                                    host=dev['ip_address'],
                                    username=credentials['username'],
                                    password=credentials['password'],
                                    secret=credentials['secret'],
                                    port=3001,
                                    timeout=timeout_value)
        dev['conn'] = net_connect
    except Exception as e:
        print(str(e))

def update(dev: dict):
    if not dev['conn'].is_alive():
        connect(dev)
    try:
        output = dev['conn'].send_command("show ip route")
    except Exception as e:
        print(str(e))
    ...

if __name__ == '__main__':
    connect(xxxx)
    update(xxxx)
```

If there is a fuller traceback, I am either not seeing it, or some how inadvertently suppressing it.

```
xxxx@xxxx:~/testing$ python3 xxxx_sh_ip_route.py 
2021-05-13 13:05:49.265084  Connecting to xxxx at IP x.x.x.x
Timed-out reading channel, pattern not found in output: terminal\ length\ 0
Traceback (most recent call last):
  File "xxxx_sh_ip_route.py", line 65, in <module>
    update(xxxx)
  File "xxxx_sh_ip_route.py", line 48, in update
    if not dev['conn'].is_alive():
AttributeError: 'NoneType' object has no attribute 'is_alive'
```

My assumption here is ConnectHandler() is returning None verse throwing an error.

**Comment by ktbyers** [comment]
@Suterusu1337 Get rid of your try/except in your connect function that will hide errors at least for this debugging.

Also your code pattern there is a bit dangerous (i.e. you are very likely going to try to use the last value dev['conn'] any time you get an exception. It probably would be a better pattern to have your `connect` function return the Netmiko connection or return None and then do the assignment of that Netmiko connection outside of the function.

So if you can temporarily get rid of that try/except and show me the full exception stack trace...

**Comment by Suterusu1337** [comment]
```python
import redis
import json
import datetime
import textfsm
from netmiko import ConnectHandler

conn = redis.Redis('localhost')

xxxxx = {
    'hostname': 'xxxxx',
    'ip_address': 'xxxxx',
    'conn': None
}

def connect(dev: dict):
    credentials = {
        'username': 'xxxxx',
        'password': 'xxxxx',
        'secret': 'xxxxx'
    }
    device_type = 'cisco_ios_telnet'
    timeout_value = 3
    print(f"{datetime.datetime.now()}  Connecting to {dev['hostname']} at IP {dev['ip_address']}")
    # try:
    net_connect = ConnectHandler(device_type=device_type,
                                host=dev['ip_address'],
                                username=credentials['username'],
                                password=credentials['password'],
                                secret=credentials['secret'],
                                port=3001,
                                timeout=timeout_value)
    return net_connect
    # except Exception as e:
        # print(str(e))

def update(dev: dict):
    TEMPLATE = "xxxxx/cisco_ios_show_ip_route.textfsm"
    if not dev['conn'].is_alive():
        dev['conn'] = connect(dev)
    # try:
    output = dev['conn'].send_command("show ip route")
    # except Exception as e:
    #     print(str(e))
    if output:
        template = open(TEMPLATE)
        re_table = textfsm.TextFSM(template)
        template.close()
        fsm_results = re_table.ParseText(output)
        data = json.dumps(fsm_results)
        r = redis.Redis(host='localhost', port=6379, db=0)
        r.set('xxxxx:show_ip_route', data)
    
if __name__ == '__main__':
    xxxxx['conn'] = connect(xxxxx)
    update(xxxxx)
```

```
xxxxx:~/testing$ python3 xxxxx_sh_ip_route.py 
2021-05-13 15:43:06.641778  Connecting to xxxxx at IP xxxxx
Traceback (most recent call last):
  File "xxxxx_sh_ip_route.py", line 54, in <module>
    xxxxx['conn'] = connect(xxxxx)
  File "xxxxx_sh_ip_route.py", line 25, in connect
    net_connect = ConnectHandler(device_type=device_type,
  File "/home/xxxxx/.local/lib/python3.8/site-packages/netmiko/ssh_dispatcher.py", line 326, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/xxxxx/.local/lib/python3.8/site-packages/netmiko/cisco/cisco_ios.py", line 17, in __init__
    return super().__init__(*args, **kwargs)
  File "/home/xxxxx/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 350, in __init__
    self._open()
  File "/home/xxxxx/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 356, in _open
    self._try_session_preparation()
  File "/home/xxxxx/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 792, in _try_session_preparation
    self.session_preparation()
  File "/home/xxxxx/.local/lib/python3.8/site-packages/netmiko/cisco/cisco_ios.py", line 23, in session_preparation
    self.disable_paging()
  File "/home/xxxxx/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 1099, in disable_paging
    output = self.read_until_pattern(pattern=re.escape(command.strip()))
  File "/home/xxxxx/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 655, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/home/xxxxx/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 595, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, pattern not found in output: terminal\ length\ 0
```

**Comment by ktbyers** [comment]
Try setting the following argument in your ConnectHandler call

global_cmd_verify = False

Let me know if that fixes your issue.

Note, you are likely going to have significant issues if you cannot disable output paging i.e. execute `terminal length 0`

**Comment by Suterusu1337** [comment]
`global_cmd_verify = False`

This worked.  Also to note, the router was taking `terminal length 0` just fine, it was not failing on that part per say, but netmiko was stating not found even though it was the `terminal width 511` that was actually having the problem.  I had the ability to run `terminal length 0` without any AAA issues from the router (when tested manually).
