### ISSUE TITLE
BaseFileTransfer.remote_md5 - This method intermittently fails to compute the remote md5 hash

### ISSUE THREAD

**Issue by chet-space** [ktbyers/netmiko#2277]
I'm trying to use the remote_md5 method to confirm the hash on a remote device's filesystem is correct. 
``` 
try:
    timer.start()
    print(f"\nverifying hash for {software_image_dst}")
    remote_md5 = dev_scp.remote_md5(remote_file=software_image_dst)
    if software_image_md5 != remote_md5:
        logger.info('hash doesn\'t match')
        pre_upgrade_facts['continue'] = False
        timer.stop()

    elif software_image_md5 == remote_md5:
        print('hash matches')
        timer.stop()

except Exception as error:
    print('sometimes this does not work??')
    logger.error(error, exc_info=True)
    timer.stop()```

```
remote_md5 = dev_scp.remote_md5(remote_file=software_image_dst) <--- This is randomly failing with the below error. This exact code block ran multiple times will have different results when ran against the same device and file on that device. socket_timeout is set to 120.

```
__main__       :upload                        :ERROR  :Search pattern never detected in send_command: lab\-9200\#
Traceback (most recent call last):
  File "main.py", line 101, in upload
    remote_md5 = dev_scp.remote_md5(remote_file=software_image_dst)
  File "/home/cheti/.local/lib/python3.6/site-packages/netmiko/scp_handler.py", line 353, in remote_md5
    dest_md5 = self.ssh_ctl_chan.send_command(remote_md5_cmd, max_loops=1500)
  File "/home/cheti/.local/lib/python3.6/site-packages/netmiko/utilities.py", line 429, in wrapper_decorator     
    return func(self, *args, **kwargs)
  File "/home/cheti/.local/lib/python3.6/site-packages/netmiko/base_connection.py", line 1525, in send_command   
    search_pattern
OSError: Search pattern never detected in send_command: lab\-9200\#
(Time elapsed: 31.4 seconds)
```

**Comment by ktbyers** [comment]
Probably try making sure you have the following two setting set (these are arguments to the SSH connection and ConnectHandler):

```python
fast_cli=False
global_delay_factor=2
```

**Comment by ktbyers** [comment]
Let me know if that helps.

**Comment by chet-space** [comment]
> 
> 
> Probably try making sure you have the following two setting set (these are arguments to the SSH connection and ConnectHandler):
> 
> ```python
> fast_cli=False
> global_delay_factor=2
> ```

T

**Comment by chet-space** [comment]
@ktbyers Your suggestion appears to have worked! I've ran the script several times without issues. Thank you.
