### ISSUE TITLE
Handling exception when SSH is not enabled on Cisco devices.

### ISSUE THREAD

**Issue by TheOtherGuy** [ktbyers/netmiko#228]
My code:

	try:
	    net_connect = ConnectHandler(**cisco_1)
	except SSHException:
	    print('SSH is not enabled for this device.')
	    sys.exit()

When a Cisco device does not have SSH enabled, a `SSHException` exception will be thrown by `Paramiko` as shown in the stacktrace below.

    Exception: Error reading SSH protocol banner
    Traceback (most recent call last):
      File "C:\Users\UserAdm\AppData\Local\Programs\Python\Python35\lib\site-packages\paramiko\transport.py", line 1867, in _check_banner
        buf = self.packetizer.readline(timeout)
      File "C:\Users\UserAdm\AppData\Local\Programs\Python\Python35\lib\site-packages\paramiko\packet.py", line 327, in readline
        buf += self._read_timeout(timeout)
      File "C:\Users\UserAdm\AppData\Local\Programs\Python\Python35\lib\site-packages\paramiko\packet.py", line 483, in _read_timeout
        raise EOFError()
    EOFError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\UserAdm\AppData\Local\Programs\Python\Python35\lib\site-packages\paramiko\transport.py", line 1723, in run
        self._check_banner()
      File "C:\Users\UserAdm\AppData\Local\Programs\Python\Python35\lib\site-packages\paramiko\transport.py", line 1871, in _check_banner
        raise SSHException('Error reading SSH protocol banner' + str(e))
    paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

    Traceback (most recent call last):
      File "C:\Users\UserAdm\AppData\Local\Programs\Python\Python35\lib\site-packages\paramiko\transport.py", line 1867, in _check_banner
        buf = self.packetizer.readline(timeout)
      File "C:\Users\UserAdm\AppData\Local\Programs\Python\Python35\lib\site-packages\paramiko\packet.py", line 327, in readline
        buf += self._read_timeout(timeout)
      File "C:\Users\UserAdm\AppData\Local\Programs\Python\Python35\lib\site-packages\paramiko\packet.py", line 483, in _read_timeout
        raise EOFError()
    EOFError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\UserAdm\PycharmProjects\CiscoPL2\dirconnect.py", line 18, in <module>
        net_connect = ConnectHandler(**cisco_1)
      File "C:\Users\UserAdm\AppData\Local\Programs\Python\Python35\lib\site-packages\netmiko\ssh_dispatcher.py", line 88, in ConnectHandler
        return ConnectionClass(*args, **kwargs)
      File "C:\Users\UserAdm\AppData\Local\Programs\Python\Python35\lib\site-packages\netmiko\base_connection.py", line 68, in __init__
        self.establish_connection(verbose=verbose, use_keys=use_keys, key_file=key_file)
      File "C:\Users\UserAdm\AppData\Local\Programs\Python\Python35\lib\site-packages\netmiko\base_connection.py", line 165, in establish_connection
        self.remote_conn_pre.connect(**ssh_connect_params)
      File "C:\Users\UserAdm\AppData\Local\Programs\Python\Python35\lib\site-packages\paramiko\client.py", line 338, in connect
        t.start_client()
      File "C:\Users\UserAdm\AppData\Local\Programs\Python\Python35\lib\site-packages\paramiko\transport.py", line 493, in start_client
        raise e
      File "C:\Users\UserAdm\AppData\Local\Programs\Python\Python35\lib\site-packages\paramiko\transport.py", line 1723, in run
        self._check_banner()
      File "C:\Users\UserAdm\AppData\Local\Programs\Python\Python35\lib\site-packages\paramiko\transport.py", line 1871, in _check_banner
        raise SSHException('Error reading SSH protocol banner' + str(e))
    paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

I tried catching the `SSHException`, but it will not catch all the exceptions, which I think is not the expected behavior ? Stacktrace below.

    Exception: Error reading SSH protocol banner
    Traceback (most recent call last):
      File "C:\Users\UserAdm\AppData\Local\Programs\Python\Python35\lib\site-packages\paramiko\transport.py", line 1867, in _check_banner
        buf = self.packetizer.readline(timeout)
      File "C:\Users\UserAdm\AppData\Local\Programs\Python\Python35\lib\site-packages\paramiko\packet.py", line 327, in readline
        buf += self._read_timeout(timeout)
      File "C:\Users\UserAdm\AppData\Local\Programs\Python\Python35\lib\site-packages\paramiko\packet.py", line 483, in _read_timeout
        raise EOFError()
    EOFError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\UserAdm\AppData\Local\Programs\Python\Python35\lib\site-packages\paramiko\transport.py", line 1723, in run
        self._check_banner()
      File "C:\Users\UserAdm\AppData\Local\Programs\Python\Python35\lib\site-packages\paramiko\transport.py", line 1871, in _check_banner
        raise SSHException('Error reading SSH protocol banner' + str(e))
    paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

    SSH is not enabled for this device.

**Comment by TheOtherGuy** [comment]
@ktbyers , I tried catching the `EOFError` exception as well, but the end result is the same as if I only caught the `SSHException` exception.

	try:
		net_connect = ConnectHandler(**cisco_1)
	except (EOFEerror, SSHException):
		print('SSH is not enabled for this device.')
		sys.exit()

**Comment by ktbyers** [comment]
You misspelled EOFError in your except statement.

>>>
except (EOFEerror, SSHException): # One too many 'Ee' >>>


Kirk


On Wed, Jun 22, 2016 at 11:01 AM, TheOtherGuy <notifications@github.com>
wrote:

> @ktbyers <https://github.com/ktbyers> , I tried catching the EOFError
> exception as well, but the end result is the same as if I only caught the
> SSHException exception.
>
> try:
>     net_connect = ConnectHandler(**cisco_1)
> except (EOFEerror, SSHException):
>     print('SSH is not enabled for this device.')
>     sys.exit()
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ktbyers/netmiko/issues/228#issuecomment-227826737>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA26hJnkmzxJTxL8iYY_foo-_qeZAfXHks5qOXhegaJpZM4I5HXQ>
> .
>



-- 
Kirk Byers
CCIE #6243 emeritus
ktbyers@twb-tech.com
*http://pynet.twb-tech.com <http://pynet.twb-tech.com/blog>*
(415) 264-6270
Simplify your network management through automation

**Comment by TheOtherGuy** [comment]
Oops that was a typo on my part, my actual code has the correct spelling.

	try:
	    net_connect = ConnectHandler(**cisco_1)
	except (EOFError, SSHException):
	    print('SSH is not enabled for this device.')
	    sys.exit()

**Comment by ktbyers** [comment]
@TheOtherGuy Can you show me the stack trace you get when using the above code?

**Comment by TheOtherGuy** [comment]
Exception: Error reading SSH protocol banner
	Traceback (most recent call last):
	  File "C:\Users\UserAdm\AppData\Local\Programs\Python\Python35\lib\site-packages\paramiko\transport.py", line 1867, in _check_banner
	    buf = self.packetizer.readline(timeout)
	  File "C:\Users\UserAdm\AppData\Local\Programs\Python\Python35\lib\site-packages\paramiko\packet.py", line 327, in readline
	    buf += self._read_timeout(timeout)
	  File "C:\Users\UserAdm\AppData\Local\Programs\Python\Python35\lib\site-packages\paramiko\packet.py", line 483, in _read_timeout
	    raise EOFError()
	EOFError

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "C:\Users\UserAdm\AppData\Local\Programs\Python\Python35\lib\site-packages\paramiko\transport.py", line 1723, in run
	    self._check_banner()
	  File "C:\Users\UserAdm\AppData\Local\Programs\Python\Python35\lib\site-packages\paramiko\transport.py", line 1871, in _check_banner
	    raise SSHException('Error reading SSH protocol banner' + str(e))
	paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

	SSH is not enabled for this device.

**Comment by TheOtherGuy** [comment]
@ktbyers , Apologies, are there any updates on this ? Cheers.

**Comment by ktbyers** [comment]
@TheOtherGuy Here is what I see to SSH to an IP address that is not listening on SSH.

```
Password: 
Traceback (most recent call last):
  File "./test_cisco.py", line 22, in <module>
    net_connect = ConnectHandler(**device)
  File "build/bdist.linux-i686/egg/netmiko/ssh_dispatcher.py", line 84, in ConnectHandler
  File "build/bdist.linux-i686/egg/netmiko/base_connection.py", line 68, in __init__
  File "build/bdist.linux-i686/egg/netmiko/base_connection.py", line 181, in establish_connection
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios 50.76.53.27:22
```

Here is how I handled the exception:

```
try:
    net_connect = ConnectHandler(**device)
except NetMikoTimeoutException:
    sys.exit("Handled timeout exception")
```

What happens when you:

```
telnet router_ip 22
```

What is the output you get back?

This is probably a bug in your code (i.e. not handling the exception correctly).

You will also need to post your full code stripped of any password/IP.
 
Kirk

**Comment by TheOtherGuy** [comment]
@ktbyers 

This is my exact code which I use for testing:

	#! python3
	from netmiko import ConnectHandler
	from netmiko.ssh_exception import NetMikoTimeoutException

	def sshconn(user_ip, user_pwd, en_pwd, usrn):
	    cisco_1 = {'device_type': 'cisco_ios', 'ip': user_ip, 'password': user_pwd, 'secret': en_pwd, 'username': usrn}

	    net_connect = ConnectHandler(**cisco_1)

	try:
	    sshconn('192.168.1.1','cisco2','cisco2','Admin')
	except NetMikoTimeoutException:
	    print('SSH not enabled.')

I did actually get the expected behavior as described (handled successfully by NetmikoTimeoutException), but it is not consistent. Out of the 10 times I tried running the same code, I got the expected behavior 4/10 times. The other 6 times resulted in the error I posted in https://github.com/ktbyers/netmiko/issues/228#issuecomment-228330622

**Comment by ktbyers** [comment]
@TheOtherGuy This maybe should be in Netmiko, but you should be able to work around it pretty easily.

Something like the following:

```
from paramiko.ssh_exception import SSHException 

try:
    net_connect = ConnectHandler(**cisco_1)
except (EOFError, SSHException, NetMikoTimeoutException):
    print('SSH is not enabled for this device.')
    sys.exit()
```

If your code doesn't actually catch the exception, then there is very very likely something wrong with your exception handling code.

You could also do this, but it is not a very good practice in general.

```
try:
    net_connect = ConnectHandler(**cisco_1)
except Exception:
    print('SSH is not enabled for this device.')
    sys.exit()
```


Kirk

**Comment by TheOtherGuy** [comment]
@ktbyers , I tried `except (EOFError, SSHException, NetMikoTimeoutException):` and `except:` , but both strangely results in the same set of error messages https://github.com/ktbyers/netmiko/issues/228#issuecomment-228330622.

Could it be due to the cisco device configuration ? I simply did a `transport input telnet` on `vty 0 15` to simulate a restriction of ssh connections.

**Comment by ktbyers** [comment]
@TheOtherGuy No it is not a Cisco issue (at least as far as why you are unable to handle the exception). There could be a Cisco issue on why you can't login.

Can you post your entire code when using the bare 'except:' statement? You can remove passwords, but don't change any line numbers.

Also post the current exception you get while running that code.

**Comment by TheOtherGuy** [comment]
@ktbyers 

[This](http://pastebin.com/XLbqqSw2) is the list of exceptions I get under different circumstances as described in the comments in the code. The python script was executed in command prompt.

My entire code for the above test:

    #! python3
    import sys
    from netmiko import ConnectHandler
    from netmiko.ssh_exception import NetMikoTimeoutException
    from paramiko.ssh_exception import SSHException


    try:
        cisco_1 = {'device_type': 'cisco_ios', 'ip': '192.168.1.1', 'password': 'ciscox', 'secret': 'ciscox', 'username': 'Admin'}

        net_connect = ConnectHandler(**cisco_1)
    except:
        print('ssh not enabled.')


    # def sshconnection(user_ip, user_pwd, en_pwd, usrn):
    #     cisco_1 = {'device_type': 'cisco_ios', 'ip': user_ip, 'password': user_pwd, 'secret': en_pwd, 'username': usrn}
    #
    #     net_connect = ConnectHandler(**cisco_1)

    # try:
    #     sshconnection('192.168.1.1', 'ciscox', 'ciscox', 'Admin')
    # except (EOFError, SSHException, NetMikoTimeoutException):
    # except Exception:
        # print('SSH not enabled.')
        # sys.exit()


Really appreciate the replies so far, thanks for the effort :)

**Comment by ktbyers** [comment]
@TheOtherGuy It looks like it is probably this issue:

https://github.com/paramiko/paramiko/issues/643

Basically a background thread is encountering an exception and printed out the exception message (which it sounds like it is hard to prevent the exception message). In the main thread the exception is handled (see the printing of 'ssh not enabled message').

So at a high level what are you trying to do. In other words, can you give me a broader context on what you are trying to accomplish.

Also what version of Paramiko are you using?

```
$ python
Python 2.7.10 (default, Dec  8 2015, 18:25:05) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import paramiko
>>> paramiko.__version__
'2.0.1'
```

Kirk

**Comment by TheOtherGuy** [comment]
@ktbyers The referenced issue is strikingly similar to what I have faced so far. 

What I am trying to accomplish is to gracefully handle the scenario when SSH isn't enabled for the Cisco device. However, it seems like from what was said in the referenced issue, there doesn't seem to be a good way to gracefully handle the scenario without printing any tracebacks.

I guess I will try to work around this by suppressing the output stream and see if it works. At least the tracebacks will be hidden from the user.

I am using Paramiko 2.0.0. I will update it and report my results :)

**Comment by ktbyers** [comment]
@TheOtherGuy Yes, I think we can handle the exception, but perhaps not suppress the exception message. I assume the exception message is probably on standard error and not on standard output. Have you tried just redirecting standard error to a file?

**Comment by a-v-popov** [comment]
Could it be a logger output? What would be the output if you add the following before your code:
```
import logging
logging.basicConfig(format='%(name)s %(filename)s %(lineno)s %(levelname)s %(message)s')
```

**Comment by ktbyers** [comment]
I don't think there is any action to take here on Netmiko...so I am going to close this.

**Comment by devopsnetworks** [comment]
@TheOtherGuy
if you want to eliminate the Traceback out put. just set the **tracebacklimit** to 0
import sys
sys.tracebacklimit = 0

Normal Output
---------------------------------------------------------------------------------------------------------
Connecting to device" 192.168.200.201
Exception: Error reading SSH protocol banner
Traceback (most recent call last):
  File "/home/dev/devnet/lib/python3.8/site-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/home/dev/devnet/lib/python3.8/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/home/dev/devnet/lib/python3.8/site-packages/paramiko/packet.py", line 609, in _read_timeout
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dev/devnet/lib/python3.8/site-packages/paramiko/transport.py", line 2039, in run
    self._check_banner()
  File "/home/dev/devnet/lib/python3.8/site-packages/paramiko/transport.py", line 2215, in _check_banner
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

SSH Issue. Are you sure SSH is enabled? 192.168.200.201
Connecting to device" 192.168.200.202
configure terminal
Enter configuration commands, one per line.  End with CNTL/Z.
vios2(config)#ntp server 10.10.10.10
vios2(config)#ntp server 10.10.100.110
vios2(config)#end
vios2#

**after the tracebacklimit to 0** 
-----------------------------------------------------------------------
Connecting to device" 192.168.200.201
Exception: Error reading SSH protocol banner
Traceback (most recent call last):
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

SSH Issue. Are you sure SSH is enabled? 192.168.200.201
Connecting to device" 192.168.200.202
configure terminal
Enter configuration commands, one per line.  End with CNTL/Z.
vios2(config)#ntp server 10.10.10.10
vios2(config)#ntp server 10.10.100.110
vios2(config)#end
vios2#
