### ISSUE TITLE
CISCO_ASA scp.SCPException: ('Invalid response from server', b'Computed Hash   SHA2: 1111e7f8c12814d019e35fe2a9b2e527\r\n')

### ISSUE THREAD

**Issue by networkjourney** [ktbyers/netmiko#2284]
Hi Kirk
I am trying to copy asa-rest plugin to CISCO ASA DISK0:
It is getting copied but same also giving error.

**### SCRIPT:**
from netmiko import ConnectHandler, file_transfer #function
import logging
logging.basicConfig(filename="packetinspectionasa.log", level=logging.DEBUG)
logger = logging.getLogger("netmiko")
dstfilename = sourcefiletobecopied = "asa-restapi-132346-lfbff-k8.SPA"
originalmd5 = "e73792f367a60ced5c6b998b258f355a"

cisco123 = {
        'device_type': 'cisco_asa',
        'ip': ' 192.168.29.146',
        'username': 'admin',
        'password': 'cisco',
        'port': 22,
        }

connection123 = ConnectHandler(**cisco123) #cisco123 here called as dictionary
output123 = connection123.send_command("show int ip br")

fil123 =  file_transfer(connection123,
                            source_file=sourcefiletobecopied,
                            dest_file=dstfilename,
                            file_system="disk0:",
                            direction="put",
                            disable_md5=True,
                            overwrite_file=True,
                            verify_file=False,
                            socket_timeout=600,)
if 'Invalid response from server' in fil123:
    print("ignore these messages")
else:
    cmd123 = "verify /md5 disk0:/asa-restapi-132346-lfbff-k8.SPA"
    md5check = connection123.send_command_timing(cmd123)
    print(md5check)
    if originalmd5 in md5check:
            print("MD5 MATCH FOUND !")
    else:
            print("MD5 MATCH FAILED ")

### **ERROR BELOW:**
C:\Users\SAGAR\PycharmProjects\NetworkAutomation\venv\Scripts\python.exe C:/Users/SAGAR/PycharmProjects/NetworkAutomation/class1napalm.py
Traceback (most recent call last):
  File "C:\Users\SAGAR\PycharmProjects\NetworkAutomation\class1napalm.py", line 19, in <module>
    fil123 =  file_transfer(connection123,
  File "C:\Users\SAGAR\PycharmProjects\NetworkAutomation\venv\lib\site-packages\netmiko\scp_functions.py", line 124, in file_transfer
    verifyspace_and_transferfile(scp_transfer)
  File "C:\Users\SAGAR\PycharmProjects\NetworkAutomation\venv\lib\site-packages\netmiko\scp_functions.py", line 39, in verifyspace_and_transferfile
    scp_transfer.transfer_file()
  File "C:\Users\SAGAR\PycharmProjects\NetworkAutomation\venv\lib\site-packages\netmiko\scp_handler.py", line 363, in transfer_file
    self.put_file()
  File "C:\Users\SAGAR\PycharmProjects\NetworkAutomation\venv\lib\site-packages\netmiko\scp_handler.py", line 376, in put_file
    self.scp_conn.scp_transfer_file(self.source_file, destination)
  File "C:\Users\SAGAR\PycharmProjects\NetworkAutomation\venv\lib\site-packages\netmiko\scp_handler.py", line 46, in scp_transfer_file
    self.scp_client.put(source_file, dest_file)
  File "C:\Users\SAGAR\PycharmProjects\NetworkAutomation\venv\lib\site-packages\scp.py", line 166, in put
    self._send_files(files)
  File "C:\Users\SAGAR\PycharmProjects\NetworkAutomation\venv\lib\site-packages\scp.py", line 271, in _send_files
    self._send_file(fl, name, mode, size)
  File "C:\Users\SAGAR\PycharmProjects\NetworkAutomation\venv\lib\site-packages\scp.py", line 297, in _send_file
    self._recv_confirm()
  **File "C:\Users\SAGAR\PycharmProjects\NetworkAutomation\venv\lib\site-packages\scp.py", line 370, in _recv_confirm
    raise SCPException('Invalid response from server', msg)
scp.SCPException: ('Invalid response from server', b'Computed Hash   SHA2: 1111e7f8c12814d019e35fe2a9b2e527\r\n')**

Process finished with exit code 1

**Comment by ktbyers** [comment]
What privilege level does this user have?

```
'username': 'admin',
'password': 'cisco',
```

i.e. right when you login (with no enable call) what is the privilege level of that user?

**Comment by networkjourney** [comment]
Its priv 15
Copy happens
but inspite file_verify=False, disable_md5=false, the ASA still performs auto compute checks and gives ugly looking error

What is the workaround

**Comment by ktbyers** [comment]
Looking at your above stack trace, the exception happens on the SCP put_file() operation?

Can you post what it looks like if you do an SCP transfer manually from your system (if that is possible)?

**Comment by ktbyers** [comment]
Looks like the same issue as this:

https://github.com/ktbyers/netmiko/issues/1268

**Comment by networkjourney** [comment]
Thanks for redirecting
I read you are gonna add PR.
Any ETA?
That would definitely help this or something in FILE_TRANSFER { disable_file_check: True } kind of option is good as well.

**Comment by ktbyers** [comment]
Unfortunately, it fails on the actual SCP transfer and is embedded in a lower library than Netmiko so I don't think there is any way to directly fix it in Netmiko.

I think my statement was `possibly do a fix in the SCP library` (just don't want to overcommit on what I am doing), but you are welcome to do a PR there directly. That project is not super active so definitely would not expect a fix rapidly. You might have to do a custom fork of that library and manage it (if you want a quick fix).


Regards, Kirk

**Comment by ktbyers** [comment]
Yeah, it is not actually netmiko doing the file verification on this error. Cisco adds a message after the file transfer and that causes the file transfer itself to break.

You can add `verify_file=False` to file_transfer, but I don't think it will help here.
