### ISSUE TITLE
issue with netmiko on mac

### ISSUE THREAD

**Issue by s2105** [ktbyers/netmiko#2286]
Hello,

I am having following error after installing netmiko.

551-:$ python

WARNING: Python 2.7 is not recommended. 
This version is included in macOS for compatibility with legacy software. 
Future versions of macOS will not include Python 2.7. 
Instead, it is recommended that you transition to using 'python3' from within Terminal.

Python 2.7.16 (default, May  8 2021, 11:48:02) 
[GCC Apple LLVM 12.0.5 (clang-1205.0.19.59.6) [+internal-os, ptrauth-isa=deploy on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from netmiko import juniper
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/netmiko/__init__.py", line 7, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "/Library/Python/2.7/site-packages/netmiko/ssh_dispatcher.py", line 2, in <module>
    from netmiko.a10 import A10SSH
  File "/Library/Python/2.7/site-packages/netmiko/a10/__init__.py", line 1, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "/Library/Python/2.7/site-packages/netmiko/a10/a10_ssh.py", line 3, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "/Library/Python/2.7/site-packages/netmiko/cisco_base_connection.py", line 165
    msg = f"Login failed: {self.host}"
                                     ^
SyntaxError: invalid syntax

Any suggestion?

**Comment by ktbyers** [comment]
Python2.7 id dead. You need to use Python3.6 or greater to use Netmiko.
