### ISSUE TITLE
Netmiko Timeout Error for Python / Automating Devices

### ISSUE THREAD

**Issue by NetCure** [ktbyers/netmiko#2291]
I am following David Bombal's videos for network automation: https://www.youtube.com/watch?v=gEVFRBnjpS4

Here is my code:

```
from netmiko import ConnectHandler

iosv_l2_s2 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.102',
    'username': 'b',
    'password': 'cisco',
}

iosv_l2_s3 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.103',
    'username': 'b',
    'password': 'cisco',
}

iosv_l2_s4 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.104',
    'username': 'b',
    'password': 'cisco',
}

iosv_l2_s5 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.105',
    'username': 'b',
    'password': 'cisco',
}

iosv_l2_s6 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.106',
    'username': 'b',
    'password': 'cisco',
}

with open('iosv_l2_config') as f:
    lines = f.read().splitlines()
print (lines)


all_devices = [iosv_l2_s6, iosv_l2_s5, iosv_l2_s4, iosv_l2_s3, iosv_l2_s2]

for devices in all_devices:
    net_connect = ConnectHandler(**devices)
    output = net_connect.send_config_set(lines)
    print (output)

f.closed()
```

Here is the error I am receiving:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 931, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/local/lib/python3.8/dist-packages/paramiko/client.py", line 412, in connect
    server_key = t.get_remote_server_key()
  File "/usr/local/lib/python3.8/dist-packages/paramiko/transport.py", line 834, in get_remote_server_key
    raise SSHException("No existing session")
paramiko.ssh_exception.SSHException: No existing session
```
During handling of the above exception, another exception occurred:
```
Traceback (most recent call last):
  File "netmiko1.py", line 46, in <module>
    net_connect = ConnectHandler(**devices)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/ssh_dispatcher.py", line 315, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/cisco/cisco_ios.py", line 17, in __init__
Exception: Error reading SSH protocol banner[Errno 9] Bad file descriptor
    return super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 346, in __init__
    self._open()
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 351, in _open
    self.establish_connection()
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 976, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.ssh_exception.NetmikoTimeoutException: Paramiko: 'No existing session' error: try increasing 'conn_timeout' to 10 seconds or larger.
```
So the first device configures fine, but then errors out with the above.

Kind of strange how the error includes 'paramiko' but I did not use or import the paramiko library here. Just netmiko. Any idea how to correct this? Thank you!

**Comment by ktbyers** [comment]
Did you try doing what the exception message recommended to do?

```
netmiko.ssh_exception.NetmikoTimeoutException: Paramiko: 'No existing session' error: try increasing 'conn_timeout' to 10 seconds or larger.
```


Kirk

**Comment by NetCure** [comment]
Thanks for the reply. Part of this issue was actually due to Spanning Tree Protocol converging during the configurations.

I don't have any code that specifies a connection timeout, but assuming there is a default set. I will look into this, thank you!

**Comment by ktbyers** [comment]
Try adding this argument to each of your devices:

"conn_timeout": 10


Also maybe try a value of 20 (if it still fails using a value of 10)
