### ISSUE TITLE
textfsm.parser.TextFSMError: State Error raised, cisco_ios_show_interfaces_status.textfsm

### ISSUE THREAD

**Issue by FredTourn** [ktbyers/netmiko#2306]
Simple script to show interfaces status on an cisco switch using Netmiko with TextFSM.

````
from netmiko import Netmiko
from netmiko import ConnectHandler
from getpass import getpass

password = getpass("Enter password: ")
net_conn = ConnectHandler(device_type='cisco_ios', ip='10.129.16.1', username='admin', password=password)

output = net_conn.send_command("show interfaces status", use_textfsm=True)
print(output)
````

When I run this I get the following output, i have 

````
Traceback (most recent call last):
  File "c:/Users/anonyme/Documents/code/git_local/nac_ports/_test.py", line 8, in <module>
    output = net_conn.send_command("show interfaces status", use_textfsm=True)
  File "C:\Users\anonyme\Documents\code\git_local\nac_ports\env\lib\site-packages\netmiko\utilities.py", line 500, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "C:\Users\anonyme\Documents\code\git_local\nac_ports\env\lib\site-packages\netmiko\base_connection.py", line 1550, in send_command
    structured_output = get_structured_data(
  File "C:\Users\anonyme\Documents\code\git_local\nac_ports\env\lib\site-packages\netmiko\utilities.py", line 347, in get_structured_data
    return _textfsm_parse(textfsm_obj, raw_output, attrs)
  File "C:\Users\anonyme\Documents\code\git_local\nac_ports\env\lib\site-packages\netmiko\utilities.py", line 319, in _textfsm_parse
    textfsm_obj.ParseCmd(raw_output, attrs)
  File "C:\Users\anonyme\Documents\code\git_local\nac_ports\env\lib\site-packages\netmiko\_textfsm\_clitable.py", line 272, in ParseCmd
    self.table = self._ParseCmdItem(self.raw, template_file=template_files[0])
  File "C:\Users\anonyme\Documents\code\git_local\nac_ports\env\lib\site-packages\netmiko\_textfsm\_clitable.py", line 303, in _ParseCmdItem
    for record in fsm.ParseText(cmd_input):
  File "C:\Users\anonyme\Documents\code\git_local\nac_ports\env\lib\site-packages\textfsm\parser.py", line 895, in ParseText
    self._CheckLine(line)
  File "C:\Users\anonyme\Documents\code\git_local\nac_ports\env\lib\site-packages\textfsm\parser.py", line 944, in _CheckLine
    if self._Operations(rule, line):
  File "C:\Users\anonyme\Documents\code\git_local\nac_ports\env\lib\site-packages\textfsm\parser.py", line 1024, in _Operations
    raise TextFSMError('State Error raised. Rule Line: %s. Input Line: %s'
textfsm.parser.TextFSMError: State Error raised. Rule Line: 27. Input Line: Gi2/0/49  Lien vers EF-Z1PU- suspended    trunk      a-full a-1000 1000BaseLX SFP
````

In the cisco_ios_show_interfaces_status.textfsm file, could you add **suspended** in the **Value STATUS** regex ? 

````
Value PORT (\S+)
Value NAME (.+?)
Value STATUS (err-disabled|disabled|connected|notconnect|inactive|up|down)
Value VLAN (\S+)
Value DUPLEX (\S+)
Value SPEED (\S+)
Value TYPE (.*)
Value FC_MODE (\S+)

Start
  ^Load\s+for\s+
  # Capture time-stamp if vty line has command time-stamping turned on
  ^Time\s+source\s+is
  ^-+\s*$$
  ^Port\s+Name\s+Status\s+Vlan\s+Duplex\s+Speed\s+Type -> Interfaces
  ^\s*$$
  ^. -> Error

Interfaces
  #Match fc...
  ^\s*${PORT}\s+is\s+${STATUS}\s+Port\s+mode\s+is\s+${FC_MODE}\s*$$ -> Record
  ^\s*${PORT}\s+is\s+${STATUS}\s+\(${TYPE}\)\s*$$ -> Record
  ^\s*${PORT}\s+${STATUS}\s+${VLAN}\s+${DUPLEX}\s+${SPEED}\s*${TYPE}$$ -> Record
  ^\s*${PORT}\s+${NAME}\s+${STATUS}\s+${VLAN}\s+${DUPLEX}\s+${SPEED}\s*${TYPE}$$ -> Record
  ^-+
  ^\s*$$
  ^. -> Error
````

**Comment by ktbyers** [comment]
@FredTourn You probably need to submit a pull request against the ntc-templates repository. The TextFSM templates are not maintained in Netmiko itself.


Kirk

**Comment by logosg** [comment]
@FredTourn hello, were you able to fix this? I'm having the same issue, I have hundreds of devices in script, not all of the return the same error
