### ISSUE TITLE
Cisco ios device - Unable to Send config from file with multi spaces

### ISSUE THREAD

**Issue by spyroskanel** [ktbyers/netmiko#2310]
Cisco ios device type sends a huge configuration file (197 lines) via SSH connection, python script has the following structure: 

```
connect_device = Netmiko(host='192.168.30.100', username='admin', password='admin', device_type='cisco_ios',secret='admin') 
connect_device.send_command('terminal length 0')
connect_device.enable()
output = connect_device.send_config_from_file(config_file='CE1.txt',cmd_verify=True)
connect_device.disconnect()
print(output)
```

Default cmd_verify is true on send_config_from_file command. As a result, i get the following timeout error: 

```
Others# python3 file_configuration.py 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.8/dist-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 573, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.8/dist-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "file_configuration.py", line 22, in <module>
    output = connect_device.send_config_from_file(config_file='CE1.txt',max_loops=150,cmd_verify=True,delay_factor=4)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 1809, in send_config_from_file
    return self.send_config_set(cfg_file, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 1912, in send_config_set
    new_output = self.read_until_pattern(pattern=re.escape(cmd.strip()))
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 655, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 583, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.
```

After debugging this error, the root cause of this issue is cmd_verify setting. when i changed cmd_verify to false, it seems that time-out error isn't presented. 

Also, i would like to mention that Cisco device is running the following release version:

```
CE1#sh version
Cisco IOS Software, IOSv Software (VIOS-ADVENTERPRISEK9-M), Version 15.6(2)T, RELEASE SOFTWARE (fc2)
```
I don't know if this reference helps you to understand this case, but this issue didn't reproduced on python 2.7.

**Comment by spyroskanel** [comment]
Ι think that this issue is with number of spaces between cli command, second router-id command has more than one space:

```
router ospf 1
 router-id 5.5.5.5
 network 5.5.5.5 0.0.0.0 area 0
 network 192.168.1.0 0.0.0.255 area 0
!
router ospf 2	
 router-id 	192.168.2.5
 network 192.168.2.0 0.0.0.255 area 0
```
 
 
```
DEBUG:netmiko:Pattern is: (?:CE1|#)
DEBUG:netmiko:_read_channel_expect read_data: CE1(config-router)#
DEBUG:netmiko:Pattern found: (?:CE1|#) CE1(config-router)#
DEBUG:netmiko:write_channel: b' router-id 5.5.5.5\n'
DEBUG:netmiko:Pattern is: router\-id\ 5\.5\.5\.5
DEBUG:netmiko:_read_channel_expect read_data:  
DEBUG:netmiko:_read_channel_expect read_data: router-id 5.5.5.5
CE1(config-router)#
DEBUG:netmiko:Pattern found: router\-id\ 5\.5\.5\.5  router-id 5.5.5.5
CE1(config-router)#
DEBUG:netmiko:write_channel: b' network 5.5.5.5 0.0.0.0 area 0\n'
DEBUG:netmiko:Pattern is: network\ 5\.5\.5\.5\ 0\.0\.0\.0\ area\ 0
DEBUG:netmiko:_read_channel_expect read_data:  
DEBUG:netmiko:_read_channel_expect read_data: network 5.5.5.5 0.0.
DEBUG:netmiko:_read_channel_expect read_data: 0.0 area 0
CE1(config-router)#
DEBUG:netmiko:Pattern found: network\ 5\.5\.5\.5\ 0\.0\.0\.0\ area\ 0  network 5.5.5.5 0.0.0.0 area 0
CE1(config-router)#
DEBUG:netmiko:write_channel: b' network 192.168.1.0 0.0.0.255 area 0\n'
DEBUG:netmiko:Pattern is: network\ 192\.168\.1\.0\ 0\.0\.0\.255\ area\ 0
DEBUG:netmiko:_read_channel_expect read_data:  
DEBUG:netmiko:_read_channel_expect read_data: network 192.16
DEBUG:netmiko:_read_channel_expect read_data: 8.1.0 0.0.0.255 ar
DEBUG:netmiko:_read_channel_expect read_data: ea 0
CE1(config-router)#
DEBUG:netmiko:Pattern found: network\ 192\.168\.1\.0\ 0\.0\.0\.255\ area\ 0  network 192.168.1.0 0.0.0.255 area 0
CE1(config-router)#
DEBUG:netmiko:write_channel: b'!\n'
DEBUG:netmiko:Pattern is: !
DEBUG:netmiko:_read_channel_expect read_data: !
DEBUG:netmiko:Pattern found: ! !
DEBUG:netmiko:Pattern is: (?:CE1|#)
DEBUG:netmiko:_read_channel_expect read_data: 

DEBUG:netmiko:_read_channel_expect read_data: CE1(config-router)#
DEBUG:netmiko:Pattern found: (?:CE1|#) 
CE1(config-router)#
DEBUG:netmiko:write_channel: b'router ospf 2\n'
DEBUG:netmiko:Pattern is: router\ ospf\ 2
DEBUG:netmiko:_read_channel_expect read_data: r
DEBUG:netmiko:_read_channel_expect read_data: outer ospf 2
CE1(config-router)#
DEBUG:netmiko:Pattern found: router\ ospf\ 2 router ospf 2
CE1(config-router)#
DEBUG:netmiko:write_channel: b' router-id \t192.168.2.5\n'
DEBUG:netmiko:Pattern is: router\-id\ \	192\.168\.2\.5
DEBUG:netmiko:_read_channel_expect read_data:  
DEBUG:netmiko:_read_channel_expect read_data: router-id 
CE1(config-router)# router-id 192.168.2.5
DEBUG:netmiko:_read_channel_expect read_data: 
CE1(config-router)#
 
```

**Comment by ktbyers** [comment]
Looks like you have a `tab` in your configuration that you are sending

```
DEBUG:netmiko:write_channel: b' router-id \t192.168.2.5\n'
```

The network device looks like it converts this tab in some way (i.e. it doesn't echo back the tab character).

This causes cmd_verify to break (i.e. Netmiko is looking for the echo of what you sent and that never happens here).

You could do one of the following two items to fix the issue:
1. Don't use a tab (i.e. you should always send the literal strings the network device expects/uses)
2. Set cmd_verify=False in your calls to `send_config_set()` i.e. tell Netmiko to not care about the command echo.


cmd_verify is very helpful in making sure that Netmiko does not get out of sync with the network device i.e. Netmiko will send commands much faster than the network device can process them so doing verification of the echo greatly helps with this.


Regards, Kirk

**Comment by spyroskanel** [comment]
Hello Kirk, 

Thank you for your analysis about cmd_verify function, it is really helpful.

I verify that configuration without tabs is working properly. 
Also, i would like to contribute on code debugging, if i could find any similar issue, the project is very promising and helpful in daily tasks. 

Best regards,
Spyros
