### ISSUE TITLE
OSError: Search pattern never detected in send_command:

### ISSUE THREAD

**Issue by utami1511** [ktbyers/netmiko#2328]
I am trying to run 'show interface' command on nexus switch with 'send_command' and getting this error:

Total time: 0:00:28.715978
Traceback (most recent call last):
  File "C:\Users\xxxx\PycharmProjects\switch audit\switch_audit.py", line 86, in <module>
    sw_intf = ssh.send_command("show interface")
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\utilities.py", line 500, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\base_connection.py", line 1535, in send_command
    raise IOError(
OSError: Search pattern never detected in send_command: SW01\#

I suspect maybe the prompt didn't come back when it was expected to? how do you solve this issue please?

**Comment by utami1511** [comment]
I got rid of the error by using 'send_command_timing' instead.
Although the output of this command is only showing a subset of the whole output?

**Comment by ktbyers** [comment]
Which Netmiko device_type are you using?

Probably try setting the argument to ConnectHandler of delay_factor=False and use `send_command`. Did this fix the issue?

**Comment by ktbyers** [comment]
Closing as there was no response. Just re-open if you are still working on this.
