### ISSUE TITLE
netmiko with proxyjump can't connect device(Paramiko.ssh_exception.ProxyCommandFailure: ProxyCommand)

### ISSUE THREAD

**Issue by apple0001** [ktbyers/netmiko#2415]
Hi everyone.

I want to use netmiko with ssh_config file(proxyjump) to connect to device. but I can't connect to device in this way , error message as below. however i can use this ssh_config file to ssh to device on local windows terminal.  is there anyone encountered this issue before and  may i know how to fixed this issue?  thanks very much.

**error message**:
"""
paramiko.ssh_exception.ProxyCommandFailure: ProxyCommand("ssh -F C:nirsshssh_config -W y.y.y.y jumphost") returned nonzero exit status: An operation was attempted on something that is not a socket
"""

**ssh_config file:**
```
Host jumphost
        IdentitiesOnly yes
        IdentityFile ./ssh/id_rsa
        HostName x.x.x.x
        User test
        Port xx
        StrictHostKeyChecking no
        UserKnownHostsFile ./ssh/knownhostsfile
Host host1
        HostName y.y.y.y
        ProxyJump jumphost
```

`

**netmiko**
```
from netmiko import ConnectHandler

device = {
    'device_type': 'cisco_ios',
    'host': 'host1',  
    'username': 'host1_test',
    'password':'host1_test',
    'ssh_config_file': './ssh/ssh_config',
}

net_connect = ConnectHandler(**device)
net_connect.disconnect()

**Comment by apple0001** [comment]
**ssh_config file**

```
Host jumphost
        IdentitiesOnly yes
        IdentityFile ./ssh/id_rsa
        HostName x.x.x.x
        User test
        Port xx
        StrictHostKeyChecking no
        UserKnownHostsFile ./ssh/knownhostsfile
Host host1
        HostName y.y.y.y
        ProxyJump jumphost

**Comment by ktbyers** [comment]
Your error doesn't match your SSH config file?

```
ProxyCommand("ssh -F C:nirsshssh_config -W y.y.y.y jumphost")
```

Where is the `-F C:nirsshssh_config` coming from?

Also what is the operating system of your local computer and also of the jumphost?

**Comment by apple0001** [comment]
Thanks @ktbyers   


my local computer  : win10
jumphost:  centos 7.9
target device: cisco IOS

the file path of ssh_config is no problem 

**you can see the file structure as below:** 
```
C:/nir
  -> ssh
     -> id_rsa
     -> ssh_config
  -> test_script 
```

**Comment by ktbyers** [comment]
I assume you have WSL--correct?

Can you show me the output of manually using your SSH config file using the command-line? I.E. I want to see it all working properly outside of Netmiko.


Regards, Kirk

**Comment by SeglaSamaty** [comment]
Hi @ktbyers 
I'm hitting on a similar issue.

```
from netmiko import ConnectHandler
from getpass import getpass

device = {
    'device_type': 'cisco_ios',
    'host': input('hostname: '),
    'username': 'gituser',
    'password': getpass(),
    'ssh_config_file': '/home/gituser/.ssh/config',
}

import logging
logging.basicConfig(filename='test.log', level=logging.DEBUG)


net_connect = ConnectHandler(**device)
output = net_connect.send_command("show users")
print(output)
```
$cat /home/gituser/.ssh/config

```
host  jumpserver
  IdentityFile  /home/gituser/.ssh/id_rsa
  IdentitiesOnly  yes
  user  gituser
  hostname  10.10.10.77
  Port  22
  Protocol 2
  StrictHostKeyChecking  no

host  *  !jumpserver
  ProxyCommand  ssh  jumpserver  nc  %h  %p
  StrictHostKeyChecking  no
```

The code works fine with the following setup

 Locale Host--------<ssh 2>-----------Jumpserver--------<ssh 1.99>------------remote host(10.10.10.10)

But with ssh 2 between Jumpserver and the remote host, 

Locale Host---------<ssh 2>-----------Jumpserver-----------<ssh 2>------------remote host(10.10.10.11)

```
Traceback (most recent call last):
  File "/home/gituser/.pyenv/versions/3.8.5/lib/python3.8/site-packages/netmiko/base_connection.py", line 999, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/gituser/.pyenv/versions/3.8.5/lib/python3.8/site-packages/paramiko/client.py", line 412, in connect
    server_key = t.get_remote_server_key()
  File "/home/gituser/.pyenv/versions/3.8.5/lib/python3.8/site-packages/paramiko/transport.py", line 837, in get_remote_server_key
    raise SSHException("No existing session")
paramiko.ssh_exception.SSHException: No existing session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yo2.py", line 19, in <module>
    net_connect = ConnectHandler(**device)
  File "/home/gituser/.pyenv/versions/3.8.5/lib/python3.8/site-packages/netmiko/ssh_dispatcher.py", line 339, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/gituser/.pyenv/versions/3.8.5/lib/python3.8/site-packages/netmiko/base_connection.py", line 413, in __init__
    self._open()
  File "/home/gituser/.pyenv/versions/3.8.5/lib/python3.8/site-packages/netmiko/base_connection.py", line 418, in _open
    self.establish_connection()
  File "/home/gituser/.pyenv/versions/3.8.5/lib/python3.8/site-packages/netmiko/base_connection.py", line 1044, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.exceptions.NetmikoTimeoutException: Paramiko: 'No existing session' error: try increasing 'conn_timeout' to 10 seconds or larger.
```
$cat test.log

```
DEBUG:paramiko.transport:starting thread (client mode): 0x2c9bb400
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.7.2
```
Running netmiko==3.4.0  paramiko==2.7.2
What have I done wrong? do I need a special config in Netmiko for SSH 2 with proxycommand?
