### ISSUE TITLE
NAPALM ACL config failed

### ISSUE THREAD

**Issue by spgghosh** [ktbyers/netmiko#2436]
import json
from napalm import get_network_drive
driver = get_network_driver("ios")
iosvl2 = driver("20.20.20.2","cisco","cisco")
iosvl2.open()

print("Accessing 20.20.20.2")
iosvl2.load_merge_candidate(filename ="acl")
iosvl2.commit_config()
iosvl2.close()

Getting below error 

Traceback (most recent call last):
  File "C:\Users\Ghosh\AppData\Local\Programs\Python\Python39\lib\site-packages\napalm\ios\ios.py", line 175, in _discover_file_system
    return self.device._autodetect_fs()
  File "C:\Users\Ghosh\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\cisco_base_connection.py", line 218, in _autodetect_fs
    raise ValueError(
ValueError: An error occurred in dynamically determining remote file system: dir 
%Error opening flash:/ (No device available)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ghosh\Documents\python\naplam_ACL.py", line 8, in <module>
    iosvl2.load_merge_candidate(filename ="acl")
  File "C:\Users\Ghosh\AppData\Local\Programs\Python\Python39\lib\site-packages\napalm\ios\ios.py", line 320, in load_merge_candidate
    file_system=self.dest_file_system,
  File "C:\Users\Ghosh\AppData\Local\Programs\Python\Python39\lib\site-packages\napalm\ios\ios.py", line 3559, in dest_file_system
    self._dest_file_system = self._discover_file_system()
  File "C:\Users\Ghosh\AppData\Local\Programs\Python\Python39\lib\site-packages\napalm\ios\ios.py", line 181, in _discover_file_system
    raise CommandErrorException(msg)
napalm.base.exceptions.CommandErrorException: Netmiko _autodetect_fs failed (to workaround specify dest_file_system in optional_args.)
>>>

**Comment by ktbyers** [comment]
Is this a real device or a fake IOS device?

```
%Error opening flash:/ (No device available)
```

It looks like a `dir` command is not showing any file systems?

**Comment by spgghosh** [comment]
its not real device.. its GNS 3 device.

**Comment by ktbyers** [comment]
You need a file-system i.e. NAPALM transfers a file onto a file system. So `dir` needs to report a file-system that can be used to store that file (or alternatively, you can set the file-system via an argument into NAPALM).
