### ISSUE TITLE
Aruba Switch: send_command() is failing due to find_prompt() returning double prompt

### ISSUE THREAD

**Issue by searching12** [ktbyers/netmiko#2447]
Hi, I'm having issue running a script to Aruba switches with model of JL262A. From the error message I'm seeing that it due to "OSError: Search pattern never detected in send_command_expect: Site1\-1881\-B1\#\ Site1\-1881\-B1\#" and I'm seeing my device hostname but somehow it is duplicate ? Is it normal? When I tried manually accessing the device I can see that it is accessible and responsive. 
I'm running this script for almost 100 devices - aruba sw same  model and this issue is not happening on a specific device only but on multiple devices randomly. Is there something wrong with my code? I'm using the same code/flow in cisco switches but able to run the script without issue only for these aruba switches. 

```
#==========================================
# Version: 1
# Author: 
# Lastupdate:   3 Aug 3 2021
# Last changes:
#==========================================
import netmiko
from netmiko import ConnectHandler
from netmiko.ssh_exception import NetMikoTimeoutException
from netmiko.ssh_exception import SSHException
from netmiko.ssh_exception import AuthenticationException
from netmiko import SCPConn
from datetime import datetime
from getpass import getpass
from pprint import pprint
import time, re
import pandas as pd
import threading
from queue import Queue
import sys, os, logging

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

failed_devlist = []
numfailed_devlist = len(failed_devlist)

def reformat_devices(devices):
    devices = devices.read()
    devices = devices.strip().splitlines()
    return devices

def get_user_pw():
##    username = input('Enter TACACS+ Username: ')
##    password = define_password()
    username = "unametest"
    password = "passxxxxx"
    ena = "dummy"
    return username, password, ena

def connect_now(ip_d,username, password, ena, tvalue):
    global failed_devlist
    try:
        datecheck = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
##        print ("%s [STATUS] Starting remote connection to %s thread value %s" % (datcheck,ip_d,tvalue))
        connection = ConnectHandler(ip=ip_d, device_type=device_type, username=username, password=password, secret=ena, session_log="netsvulogs.txt", session_log_file_mode="append")
        dev_assmnt(connection, ip_d)
    except exceptions as exception_type:
        exception_str = datetime.now().strftime('%Y-%m-%d %H:%M:%S')+' - '+str(exception_type)
        #print(exception_str[:79])
        datecheck = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        print ("%s [ERROR] Issue connecting to %s thread value %s" % (datecheck,ip_d,tvalue))
        failed_devlist.append(ip_d)

def dev_assmnt(connection, dev_ip):
    global hostname
    hostname = connection.find_prompt()[:-1]
    print (hostname,":\n")
    t_dev[hostname] = {}
    t_dev[hostname]['MGMT_IP'] = dev_ip
    datecheck = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
##    print ("%s [STATUS] checking the WLC %s %s" % (datecheck,t_dev[dev_ip],dev_ip))
##    connection.send_command('terminal length 0')      
    ver_cmd = "show vlan 2"
    ver_cmdres = connection.send_command(ver_cmd, delay_factor=2)
    print ("Result:",ver_cmdres)
    try:
        if "not found" in ver_cmdres:
            t_dev[hostname]['VLAN_2'] = "Not Found"
        elif "VLAN ID : 2" in ver_cmdres:
            t_dev[hostname]['VLAN_2'] = "Configured"
        else:
            t_dev[hostname]['VLAN_2'] = "NA"

        if re.findall(r'1\/4.*Tagged',ver_cmdres):
            t_dev[hostname]['Port_1/4'] = "Allowed"
        else:
            t_dev[hostname]['Port_1/4'] = "Not Allowed"

        if re.findall(r'2\/1.*Tagged',ver_cmdres):
            t_dev[hostname]['Port_2/1'] = "Allowed"
        else:
            t_dev[hostname]['Port_2/1'] = "Not Allowed"
    except:
        print ("%s [ERROR] Issue assessing the device %s %s" % (hostname,dev_ip))
        t_dev[hostname]['VLAN_2'] = "NA"
        t_dev[hostname]['Port_1/4'] = "NA"
        t_dev[hostname]['Port_2/1'] = "NA" 
    
##    print ("**************** Accessing ", dev_ip, "****************")
##    print (ver_output)
##    try:
##        if "mic" in ver_output:
##            t_dev[dev_ip]['MIC'] = "Enabled"
##        else:
##            t_dev[dev_ip]['MIC'] = "Disabled"
##        if "ssc" in ver_output:
##            t_dev[dev_ip]['SSC'] = "Enabled"
##        else:
##            t_dev[dev_ip]['SCC'] = "Disabled"
##    except:
##        t_dev[dev_ip]['MIC'] = "NA"
##        t_dev[dev_ip]['SCC'] = "NA"
##        print ("%s [ERROR] Unable to assess for %s %s" % (datecheck,t_dev[dev_ip],dev_ip))
    
#~~~~~~~~~~~~~~
#MAIN
#~~~~~~~~~~~~~~
os.remove("netsvulogs.txt")
logging.basicConfig(filename='netmiko_global.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

starttime = datetime.now()
start = "\033[1m"
end = "\033[0;0m"
os.system("clear")
username, password, ena = get_user_pw()

f = open("logs.txt", "w+")
f.close()
now = datetime.now()
logs_time = now.strftime("%H:%M:%S")

devices = open('4aruba_dev.txt','r')
devices = reformat_devices(devices)
device_type = 'hp_procurve'
##device_type = 'aruba_os'
logfilename = datetime.now().strftime('%m%d%Y-%H.%M.%S-')+username+'.log'
logfileloc = '/home/xxxxx/'+logfilename
logfile = open(logfileloc,'w')
print('~'*79)
logfile.write('~'*79+'\n')
print("""
XXXXXXXXXXXXXXXX
""")
logfile.write('~'*25+' Starting Cisco WLC change request '+'~'*25+'\n')
print('~'*79)
logfile.write('~'*79+'\n')
''' Common exceptions that could cause issues '''
exceptions = (netmiko.ssh_exception.NetMikoTimeoutException,
              netmiko.ssh_exception.NetMikoAuthenticationException)

t_dev = {}


##devices = get_devinfo()
total_devices = len(devices)
##q = queue.Queue()
##count_duration(total_devices, argv_dict["maxth"], starttime)
output_q = Queue()
threads = []
x = 0

# Start thread for each router in routers list
print("\n" + start + "SCRIPT STARTED:" + end)
SubDevices = []
AllDevices = []
## Threading
##for device in devices:
##    SubDevices.append(device)
##    AllDevices.append(device)
##    if (len(SubDevices) == 10) or (AllDevices == devices):
##        threads = []
##        tval = 0
##        for subdevice in SubDevices:
##                tval += 1
##                t = threading.Thread(target=connect_now, args=(subdevice,username,password,ena, tval))
##                threads.append(t)
##                t.start()
##                time.sleep(3)
##
##        for t in threads:
##                t.join()
##        
##        SubDevices = []

## SEQUENTIAL
tval = 0
for device in devices:
    tval += 1
    connect_now(device,username,password,ena,tval)
    time.sleep(3)
duration = datetime.now() - starttime


print("\n" + start + "SUMMARY RESULT:" + end)
##print (t_dev)
##print ("\n")
df = pd.DataFrame(t_dev).T
print(df)
##for row in zip(*([key] + (value) for key, value in sorted(t_dev.items()))):
##    print(*row)

print()
print("-------------------------------------------------------------------------------------------------------")
print(f"total device number: {total_devices}")
print(f"failed connection: {failed_devlist}  num_failed: {numfailed_devlist}")
print(f"elapsed time: {duration}")
print("-------------------------------------------------------------------------------------------------------\n")
```

```
Traceback (most recent call last):
  File "./3aruba_vlan2.py", line 190, in <module>
    connect_now(device,username,password,ena,tval)
  File "./3aruba_vlan2.py", line 50, in connect_now
    dev_assmnt(connection, ip_d)
  File "./3aruba_vlan2.py", line 68, in dev_assmnt
    ver_cmdres = connection.send_command(ver_cmd, delay_factor=2)
  File "/home/repos/public/Python/lib/python3.6/site-packages/netmiko/base_connection.py", line 1112, in send_command
    search_pattern))
OSError: Search pattern never detected in send_command_expect: Site1\-1881\-B1\#\ Site1\-1881\-B1\#
```

Thank you

**Comment by searching12** [comment]
From the loggings.. I'm seeing there is percentage on its hostname..  is this the issue? Not sure why there's % there while I'm not seeing this king of behavior on other device. Possible that we  have error on expect because of this. 

`
cat netsvulogs.txt
Site1-1881-B1# show vlan 2


 Status and Counters - VLAN Information - VLAN 2

  VLAN ID : 2      
  Name : PHOTO                           
  Status : Port-based
  Voice : No 
  Jumbo : No 
  Private VLAN : none     
  Associated Primary VID : none      
  Associated Secondary VIDs : none                                

  Port Information Mode     Unknown VLAN Status    
  ---------------- -------- ------------ ----------
  1/1              Tagged   Learn        Up        
  1/4              Tagged   Learn        Up        
  2/1              Tagged   Learn        Up        
  2/8              Untagged Learn        Down      
  2/9              Untagged Learn        Up        
  2/10             Untagged Learn        Up        
  2/11             Untagged Learn        Up        
  2/12             Untagged Learn        Up        
 


ST-19380-S1# %
`

**Comment by ktbyers** [comment]
Can you post this log file:  `netmiko_global.log` (at least the last few hundred lines). 

You also need to only run it in a single failing device (i.e. the threading will make the shared log file unusable so only run it on a single failing device).

**Comment by ktbyers** [comment]
From the exception output above:

```
Site1\-1881\-B1\#\ Site1\-1881\-B1\#
```

It looks like the device was slow to respond at some point.

Does adding an `expect_string=r"#"` to your relevant `send_command()` call fix the issue?

**Comment by ktbyers** [comment]
Could also be an issue with ANSI escape codes in some way (causing the double prompt).
