### ISSUE TITLE
NETMIKO CONNECTION TO PALO ALTO ISSUE

### ISSUE THREAD

**Issue by okyereoseirabbi** [ktbyers/netmiko#2468]
I have been trying to connect to Palo Alto firewall using netmiko to pull running configuration. Whenever i try, i get authentication error even though the credentials are correct. The Palo has the banner acknowledgement enabled. 

======================================================================
**Please see the script below**

import getpass
from netmiko import ConnectHandler

    username = input('Username: ')
    password = getpass.getpass('Password: ')
    
    ip = input('Enter device ip: ')
    ips = str(ip)
    test = {
            'device_type': 'paloalto_panos', 
            'host': ips,
            'username': username, 
            'password': password,
            
        }
    tcon = ConnectHandler(**test)
   
    print('CONNECTED: ', ip)
       
    palo_cmds = ['set cli pager off', 'show config running']
    
    for show_cmd in palo_cmds:
        time.sleep(5)
        int_stat_result = tcon.send_command(show_cmd, cli_verify=False)
    time.sleep(5)

   print(int_stat_result)

==========================================================
**RESULTS WHEN I RUN THE SCRIPT**

            Enter device ip: 10.8.250.88
           Authentication to device failed.

Common causes of this problem are:
1. Invalid username and password
2. Incorrect SSH-key file
3. Connecting to the wrong device

Device settings: paloalto_panos 10.8.250.88:22

Authentication failed.

===========================================================

@ktbyers and team, please help me here.

**Comment by ktbyers** [comment]
Have you tested it with just hard-coding the IP address and not doing the `input` section?

Also please make sure you are testing with the `develop` branch as we have made a lot of changes to the Palo Alto driver in the last couple of weeks.

Let me know if you are still seeing issues with the `develop` branch.

Also note, you shouldn't need to disable output paging--Netmiko will do that automatically on login.

**Comment by okyereoseirabbi** [comment]
How do I install the developer branch please?
 
Also, by output paging, do you mean the 'CLI_VERIFY' ?

**Comment by ktbyers** [comment]
```
git clone https://github.com/ktbyers/netmiko
cd netmiko
pip install -e .
```

There are also ways to directly install it with `pip` from GitHub which you should be able to find online.

**Comment by ktbyers** [comment]
On the output paging, I mean that you should not need to execute this command: `set cli pager off`

Netmiko will execute that automatically.

**Comment by okyereoseirabbi** [comment]
I am running on a windows management server (git is not whitelisted for installation). So what i did was to issue :

pip uninstall netmiko 

then

pip install netmiko (hoping it will pull the recent updates).


After i ran the test, I got the same error....thus authentication failure.

**Comment by ktbyers** [comment]
Yeah, that won't work as that will only install the latest released Netmiko (Netmiko 3.4.0) and I would need you to test the Netmiko develop branch.

Your error looks like a pretty standard authentication failure i.e. this is generally due to an incorrect username and password.

I would simplify your program and hard-code the username, password, and ip address into your test program (as a temporary test).

**Comment by okyereoseirabbi** [comment]
I am certain is not the credentials. My challenge is to get the Netmiko develop branch. Let me try to get that one installed and test with it. I will update you once done please

**Comment by ktbyers** [comment]
Yes, there should also be some GitHub clients for windows.

You could also capture the Netmiko log file which might provide more clues as to what is happening:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by okyereoseirabbi** [comment]
I believe i should be able to download the zip file. But how do i point python to the new develop branch of netmiko folder?
How do i ensure it is still not running with the old netmiko installed with "pip install netmiko" ?

**Comment by okyereoseirabbi** [comment]
Hello @ktbyers ,

So I created a test lab in GNS3 and  followed the below procedure to install the Netmiko Develop Branch:

          git clone https://github.com/ktbyers/netmiko
          cd netmiko
          git fetch origin
          git checkout -b panos_prompting origin/panos_prompting
          # Install current directory as active code
          pip install -e .

The first test raised *netmiko.exceptions.ReadTimeout* exception error. However, the second test was successful.

I would test in our production environment and feedback soon

**Comment by okyereoseirabbi** [comment]
@ktbyers,

When I tested in our production environment, I keep getting below traceback:

    Traceback (most recent call last):
      File "C:\Users\produser\Desktop\PythonProjects\test.py", line 79, in <module>
        tcon = ConnectHandler(**test)
      File "c:\users\produser\desktop\pythonprojects\netmiko\netmiko\ssh_dispatcher.py", line 339, in ConnectHandler
        return ConnectionClass(*args, **kwargs)
      File "c:\users\produser\desktop\pythonprojects\netmiko\netmiko\base_connection.py", line 413, in __init__
        self._open()
      File "c:\users\produser\desktop\pythonprojects\netmiko\netmiko\base_connection.py", line 419, in _open
        self._try_session_preparation()
      File "c:\users\produser\desktop\pythonprojects\netmiko\netmiko\base_connection.py", line 858, in _try_session_preparation
        self.session_preparation()
      File "c:\users\produser\desktop\pythonprojects\netmiko\netmiko\paloalto\paloalto_panos.py", line 70, in 
         session_preparation
        self.set_terminal_width(
      File "c:\users\produser\desktop\pythonprojects\netmiko\netmiko\base_connection.py", line 1213, in set_terminal_width
        output = self.read_until_pattern(pattern=pattern)
      File "c:\users\produser\desktop\pythonprojects\netmiko\netmiko\base_connection.py", line 630, in read_until_pattern
        raise ReadTimeout(msg)
    netmiko.exceptions.ReadTimeout:
    
    Pattern not detected: 'set cli terminal width 500' in output.
    
    Things you might try to fix this:
    1. Adjust the regex pattern to better identify the terminating string. Note, in
    many situations the pattern is automatically based on the network device's prompt.
    2. Increase the read_timeout to a larger value.
    
    You can also look at the Netmiko session_log or debug log for more information.

**Comment by ktbyers** [comment]
Have you enabled the Netmiko session_log to see why this terminal width command is failing?


Regards, Kirk

**Comment by mcfone** [comment]
I also get the "Pattern not detected: 'set cli terminal width 500' in output." traceback. I do not have the banner acknowledgement set. My PA model is PS-5260 and it is quite fast hardware. When I log on to it and manually run "set cli terminal width 500" it returns instantly - there is no waiting. Reverting to the previous version of paloalto_panos.py works.

I've enabled Netmiko logging, and the relevant extract (I think) is:

user@fw(active)>
DEBUG:netmiko:In disable_paging
DEBUG:netmiko:Command: set cli scripting-mode on

DEBUG:netmiko:write_channel: b'set cli scripting-mode on\n'
DEBUG:netmiko:read_channel:
DEBUG:netmiko:Pattern found: ()
DEBUG:netmiko:
DEBUG:netmiko:Exiting disable_paging
DEBUG:netmiko:write_channel: b'set cli terminal width 500\n'
DEBUG:netmiko:read_channel: set
DEBUG:netmiko:read_channel:
user@fw(active)> set cli
user@fw(active)> set cli scripting-mode
user@fw(active)> set cli scripting-mode on

DEBUG:netmiko:read_channel: user@fw(active)>
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:  (which then goes on until it times out.)

If I log in to the PA and run the session preparation commands manually, I get:

user@fw(active)> set cli scripting-mode on
user@fw(active)> set cli terminal width 500
user@fw(active)> set cli pager off
user@fw(active)> 

Regards, Mark

**Comment by okyereoseirabbi** [comment]
In my case, if i enable the session logging, i encounter a UnicodeEncodeError.


      Traceback (most recent call last):
        File "C:\Users\produser\Desktop\PythonProjects\test.py", line 89, in <module>
          int_stat_result = tcon.send_command(show_cmd, read_timeout= 1800)
        File "c:\users\produser\desktop\pythonprojects\netmiko\netmiko\utilities.py", line 600, in wrapper_decorator
          return func(self, *args, **kwargs)
        File "c:\users\produser\desktop\pythonprojects\netmiko\netmiko\base_connection.py", line 1622, in send_command
          new_data = self.read_channel()
        File "c:\users\produser\desktop\pythonprojects\netmiko\netmiko\base_connection.py", line 79, in wrapper_decorator
          return_val = func(self, *args, **kwargs)
        File "c:\users\produser\desktop\pythonprojects\netmiko\netmiko\base_connection.py", line 543, in read_channel
          self.session_log.write(new_data)
        File "c:\users\produser\desktop\pythonprojects\netmiko\netmiko\session_log.py", line 65, in write
          self.session_log.write(data)
      UnicodeEncodeError: 'ascii' codec can't encode character '\xa0' in position 327: ordinal not in range(128)
      PS C:\Users\produser\Desktop\PythonProjects> python .\test.py

**Comment by okyereoseirabbi** [comment]
But I have identified something interesting, if I send a command (say 'show clock') which returns a very small output it works. However, if i try to get the whole config on the box I get the ReadTimeout exception. Over the weekend I realized that passing the *'read_timeout'* parameter with a value of 1800 worked in my case. 

But this morning, with that same value it is not working (still results in ReadTimeout exception). So i have increased it to 5400 as in below:

    int_stat_result = tcon.send_command(show_cmd, read_timeout= 5400)


So I have two issues regarding this:

1. Getting to know the value to pass to _read_timeout_ so it does not raise _netmiko.exceptions.ReadTimeout_
2. In the documentation, correct me if I am wrong but i read that setting a read_timeout value of 0 will keep reading indefinitely until pattern is detected. But in my case, that doesn't seem to resolve my issue. Is there something I am missing please?

**Comment by ktbyers** [comment]
@mcfone Which Netmiko code are you testing with?

**Comment by okyereoseirabbi** [comment]
I am using the develop branch

**Comment by ktbyers** [comment]
@okyereoseirabbi What does `show_cmd` contain i.e. what command are you sending and how long does that command typically take to execute?

Yes, setting `read_timeout=0` will cause reading to continue indefinitely

**Comment by okyereoseirabbi** [comment]
It contains the commands in the palo_cmds list. Please refer to the config shared above.

**Comment by ktbyers** [comment]
@okyereoseirabbi So this?

```python
palo_cmds = ['set cli pager off', 'show config running']

for show_cmd in palo_cmds:
    time.sleep(5)
    int_stat_result = tcon.send_command(show_cmd, read_timeout= 5400)
```

**Comment by okyereoseirabbi** [comment]
Yes correct

**Comment by ktbyers** [comment]
Okay get rid of `set cli pager off` (i.e. Netmiko does that automatically).

How long roughly "show config running" take to execute? When you execute it manually.

**Comment by okyereoseirabbi** [comment]
A moment...let me get that for you now

**Comment by okyereoseirabbi** [comment]
Roughly about 25sec

**Comment by ktbyers** [comment]
Okay, so what is the full exception stack trace for when "show config running" fails?

**Comment by ktbyers** [comment]
Set your read timeout to a couple of minutes...so something like:

```python
output = tcon.send_command("show config running", read_timeout=120)
```

**Comment by okyereoseirabbi** [comment]
At the moment,

> Okay, so what is the full exception stack trace for when "show config running" fails?

It was same as below:

      Traceback (most recent call last):
        File "C:\Users\produser\Desktop\PythonProjects\test.py", line 79, in <module>
          tcon = ConnectHandler(**test)
        File "c:\users\produser\desktop\pythonprojects\netmiko\netmiko\ssh_dispatcher.py", line 339, in ConnectHandler
          return ConnectionClass(*args, **kwargs)
        File "c:\users\produser\desktop\pythonprojects\netmiko\netmiko\base_connection.py", line 413, in __init__
          self._open()
        File "c:\users\produser\desktop\pythonprojects\netmiko\netmiko\base_connection.py", line 419, in _open
          self._try_session_preparation()
        File "c:\users\produser\desktop\pythonprojects\netmiko\netmiko\base_connection.py", line 858, in _try_session_preparation
          self.session_preparation()
        File "c:\users\produser\desktop\pythonprojects\netmiko\netmiko\paloalto\paloalto_panos.py", line 70, in 
           session_preparation
          self.set_terminal_width(
        File "c:\users\produser\desktop\pythonprojects\netmiko\netmiko\base_connection.py", line 1213, in set_terminal_width
          output = self.read_until_pattern(pattern=pattern)
        File "c:\users\produser\desktop\pythonprojects\netmiko\netmiko\base_connection.py", line 630, in read_until_pattern
          raise ReadTimeout(msg)
      netmiko.exceptions.ReadTimeout:
      
      Pattern not detected: 'set cli terminal width 500' in output.
      
      Things you might try to fix this:
      1. Adjust the regex pattern to better identify the terminating string. Note, in
      many situations the pattern is automatically based on the network device's prompt.
      2. Increase the read_timeout to a larger value.
      
      You can also look at the Netmiko session_log or debug log for more information.

**Comment by okyereoseirabbi** [comment]
> Okay, so what is the full exception stack trace for when "show config running" fails?

It was same as below:


      Traceback (most recent call last):
        File "C:\Users\produser\Desktop\PythonProjects\test.py", line 79, in <module>
          tcon = ConnectHandler(**test)
        File "c:\users\produser\desktop\pythonprojects\netmiko\netmiko\ssh_dispatcher.py", line 339, in ConnectHandler
          return ConnectionClass(*args, **kwargs)
        File "c:\users\produser\desktop\pythonprojects\netmiko\netmiko\base_connection.py", line 413, in __init__
          self._open()
        File "c:\users\produser\desktop\pythonprojects\netmiko\netmiko\base_connection.py", line 419, in _open
          self._try_session_preparation()
        File "c:\users\produser\desktop\pythonprojects\netmiko\netmiko\base_connection.py", line 858, in _try_session_preparation
          self.session_preparation()
        File "c:\users\produser\desktop\pythonprojects\netmiko\netmiko\paloalto\paloalto_panos.py", line 70, in 
           session_preparation
          self.set_terminal_width(
        File "c:\users\produser\desktop\pythonprojects\netmiko\netmiko\base_connection.py", line 1213, in set_terminal_width
          output = self.read_until_pattern(pattern=pattern)
        File "c:\users\produser\desktop\pythonprojects\netmiko\netmiko\base_connection.py", line 630, in read_until_pattern
          raise ReadTimeout(msg)
      netmiko.exceptions.ReadTimeout:
      
      Pattern not detected: 'set cli terminal width 500' in output.
      
      Things you might try to fix this:
      1. Adjust the regex pattern to better identify the terminating string. Note, in
      many situations the pattern is automatically based on the network device's prompt.
      2. Increase the read_timeout to a larger value.
      
      You can also look at the Netmiko session_log or debug log for more information.

**Comment by ktbyers** [comment]
Okay, so it is failing on the `set terminal width` command:

```
   File "c:\users\produser\desktop\pythonprojects\netmiko\netmiko\paloalto\paloalto_panos.py", line 70, in 
       session_preparation
      self.set_terminal_width(
```

**Comment by mcfone** [comment]
In paloalto_panos.py, the current development code contains:
```
    def session_preparation(self) -> None:
        """
        Prepare the session after the connection has been established.

        Disable paging (the '--more--' prompts).
        Set the base prompt for interaction ('>').
        """
        self.ansi_escape_codes = True
        self._test_channel_read(pattern=r"[>#]")
        self.disable_paging(command="set cli scripting-mode on", cmd_verify=False)
        self.set_terminal_width(
            command="set cli terminal width 500", pattern=r"set cli terminal width 500"
        )
        self.disable_paging(command="set cli pager off")
        self.set_base_prompt()
```

and fails with the "Pattern not detected: 'set cli terminal width 500' in output." traceback.
If I move the self.set_base_prompt() line to just after the self._test_channel_read line, it works without error or traceback.:
```
    def session_preparation(self) -> None:
        """
        Prepare the session after the connection has been established.

        Disable paging (the '--more--' prompts).
        Set the base prompt for interaction ('>').
        """
        self.ansi_escape_codes = True
        self._test_channel_read(pattern=r"[>#]")
        self.set_base_prompt()
        self.disable_paging(command="set cli scripting-mode on", cmd_verify=False)
        self.set_terminal_width(
            command="set cli terminal width 500", pattern=r"set cli terminal width 500"
        )
        self.disable_paging(command="set cli pager off")
```

**Comment by okyereoseirabbi** [comment]
> Set your read timeout to a couple of minutes...so something like:
> 
> ```python
> output = tcon.send_command("show config running", read_timeout=120)
> ```
Right now this one works. 

Any specific reason for setting it `read_timeout=120`  ??

**Comment by ktbyers** [comment]
The default is 10 seconds and your command takes longer than 10 seconds (i.e. you posted above it takes 25 seconds).

But I also wanted to see the exception so I didn't want to sit waiting for 5400 seconds to get the exception.

So I just set it to 120 seconds...i.e. something that should be long enough that it should always complete successfully in that time.  Realistically you could have went shorter i.e. 60 seconds should have been also fine.

**Comment by okyereoseirabbi** [comment]
Yes, that's the part I did not understand. Because, I started with 20sec ==>30==>60==>120==>180==>300==>900==>then 1800secs (which worked for a while but stopped after 2 days). So I decided to just give it enough timeout to see.

**Comment by ktbyers** [comment]
@mcfone Yes, test with this branch:

https://github.com/ktbyers/netmiko/pull/2455

I just made a change to it, but it should have previously had a fix for the set_base_prompt() you mentioned above. Let me know if that works or not.

**Comment by ktbyers** [comment]
@okyereoseirabbi You should open a second issue on that (if you can reproduce the behavior). 

This issue should only be the `set cli terminal width` issue.

**Comment by okyereoseirabbi** [comment]
Alright. Thanks a lot
