### ISSUE TITLE
Errors when using expect_string

### ISSUE THREAD

**Issue by cslayton65** [ktbyers/netmiko#2509]
I'm using the following commands to transfer a file from a Palo Alto to an SCP server:

net_connect = ConnectHandler(**usbth1fw001)
output = net_connect.send_command(
    command_string=cmd3,
    expect_string=r"root@10.243.80.80's password:",
    strip_prompt=False,
    strip_command=False
)
output += net_connect.send_command(
    command_string=command2,
    expect_string=r">",
    strip_prompt=False,
    strip_command=False
)

The script works (it is transferring the file).  However, I get traceback messages.

Traceback (most recent call last):
  File "C:\Users\slaycha\PycharmProjects\paloalto\venv\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Users\slaycha\PycharmProjects\paloalto\venv\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slaycha\PycharmProjects\paloalto\venv\lib\site-packages\netmiko\base_connection.py", line 573, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\Users\slaycha\PycharmProjects\paloalto\venv\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/slaycha/PycharmProjects/paloalto/netmiko_palo_scp.py", line 50, in <module>
    strip_command=False
  File "C:\Users\slaycha\PycharmProjects\paloalto\venv\lib\site-packages\netmiko\paloalto\paloalto_panos.py", line 165, in send_command
    return super().send_command(*args, **kwargs)
  File "C:\Users\slaycha\PycharmProjects\paloalto\venv\lib\site-packages\netmiko\utilities.py", line 500, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "C:\Users\slaycha\PycharmProjects\paloalto\venv\lib\site-packages\netmiko\base_connection.py", line 1496, in send_command
    new_data = self.read_until_pattern(pattern=re.escape(cmd))
  File "C:\Users\slaycha\PycharmProjects\paloalto\venv\lib\site-packages\netmiko\base_connection.py", line 655, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "C:\Users\slaycha\PycharmProjects\paloalto\venv\lib\site-packages\netmiko\base_connection.py", line 584, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

Process finished with exit code 1

**Comment by cslayton65** [comment]
Here is the log fil
[test.log](https://github.com/ktbyers/netmiko/files/7232117/test.log)
e.

**Comment by cslayton65** [comment]
I resolved the issue by using this example:
cmd1 = "copy running-config flash:test1.txt
output = net_connect.send_command_timing(cmd1)
if 'Destination filename' in output:
    output += net_connect.send_command_timing("\n")
print(output)
