### ISSUE TITLE
netmiko-develop branch: HP procurve: "Pattern not detected:" Failure to write command?

### ISSUE THREAD

**Issue by ntaken** [ktbyers/netmiko#2535]
Error occurs randomly. I runned the same script again without any error

> 172.20.100.104  =  hp_procurve 
> 
> Traceback (most recent call last):
>
>  File "/opt/netautoscripts/telnetprocurve.py", line 146, in <module>
>    check = net_connect.send_command(cmd3)
>  File "/home/itservice/.local/share/virtualenvs/netautoscripts-Ad84lSuf/src/netmiko/netmiko/utilities.py", line 600, in > >wrapper_decorator
>    return func(self, *args, **kwargs)
>  File "/home/itservice/.local/share/virtualenvs/netautoscripts-Ad84lSuf/src/netmiko/netmiko/base_connection.py", line 1597, in send_command
    new_data = self.command_echo_read(cmd=cmd, read_timeout=10)
  File "/home/itservice/.local/share/virtualenvs/netautoscripts-Ad84lSuf/src/netmiko/netmiko/base_connection.py", line 1325, in command_echo_read
    new_data = self.read_until_pattern(
  File "/home/itservice/.local/share/virtualenvs/netautoscripts-Ad84lSuf/src/netmiko/netmiko/base_connection.py", line 631, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 
>
> Pattern not detected: 'show\\ flash' in output.
>
> Things you might try to fix this:
> 1. Adjust the regex pattern to better identify the terminating string. Note, in
> many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.
>
>You can also look at the Netmiko session_log or debug log for more information.

Debug log include two successful attempt and one failure.
[netmiko_global.log](https://github.com/ktbyers/netmiko/files/7344924/netmiko_global.log)

Code:
````python
cmd2 = 'copy tftp flash 10.68.254.66 /HP/A_15_16_0023.swi primary'
cmd3 = 'show flash'
logging.basicConfig(filename='netmiko_global.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")
output = None
for key, values in hpswitches.items():
    device_type = values.get('device_type', {})
    ip_address = values.get('ip', {})
    username = values.get('username', {})
    password = values.get('password', {})
    print(f'\n{ip_address}  =  {device_type} \n')
    start_time = datetime.now()
    try:
        net_connect = ConnectHandler(device_type=device_type, host=ip_address,
                        username=username, password=password, conn_timeout=60, auth_timeout=60)
    except Exception as e:
        print(e)
        end_time = datetime.now()
        print(f"Execution time: {end_time - start_time}")
        continue
    #output = net_connect.config_mode()
    check = net_connect.send_command(cmd3)
    if "Primary Image    :     7855944 01/03/14 A.15.13.0005" in check:
        output = net_connect.send_command_timing(cmd2)
        #output = net_connect.send_command_timing(cmd)
        if "[y/n]?" in output:
            print("Starting copy...")
            output += net_connect.send_command_timing('y', delay_factor=10) #Sidenote I also have trouble making netmiko wait for download to finish.
        #output = net_connect.send_command_timing(cmd4)
        #output = net_connect.send_command_timing(cmd)
        #if "[y/n]?" in output:
            #output += net_connect.send_command_timing('y')
    #net_connect.disconnect()
    #output += net_connect.save_config()
    #output = net_connect.send_command(cmd3)
    #
    #output += net_connect.send_command(cmd3, delay_factor=4)
    #net_connect.disconnect()
    end_time = datetime.now()
    if output is not None:
        print(output)
    print("\n")
    print(f"Execution time: {end_time - start_time}")
    print("\n")
````

**Comment by ntaken** [comment]
I failed today to reproduce the error both in a new virtual environment (the old one had nornir and some of it's plugin in it.) and the old one. Tried both the simplified and the old script. So everything seems fine now.

````python
from datetime import datetime
import logging
from netmiko import ConnectHandler

hpswitches = {
    'switch548' : {
        'device_type': 'hp_procurve',
        'ip': '172.20.100.111',
        'username': 'itmaro523',
        'password': 'Lastb#Nf0rneed',
    },
    'switch551' : {
        'device_type': 'hp_procurve',
        'ip': '172.20.100.113',
        'username': 'itmaro523',
        'password': 'Lastb#Nf0rneed',
    },
    'switch561' : {
        'device_type': 'hp_procurve',
        'ip': '172.20.100.130',
        'username': 'itmaro523',
        'password': 'Lastb#Nf0rneed',
    },
    'switch667' : {
        'device_type': 'hp_procurve',
        'ip': '172.20.100.77',
        'username': 'itmaro523',
        'password': 'Lastb#Nf0rneed',
    },
    'switch686' : {
        'device_type': 'hp_procurve',
        'ip': '172.20.100.78',
        'username': 'itmaro523',
        'password': 'Lastb#Nf0rneed',
    },
    'switch523' : {
        'device_type': 'hp_procurve',
        'ip': '172.20.100.79',
        'username': 'itmaro523',
        'password': 'Lastb#Nf0rneed',
    },
    'switch524' : {
        'device_type': 'hp_procurve',
        'ip': '172.20.100.80',
        'username': 'itmaro523',
        'password': 'Lastb#Nf0rneed',
    },
    'switch539' : {
        'device_type': 'hp_procurve',
        'ip': '172.20.100.89',
        'username': 'itmaro523',
        'password': 'Lastb#Nf0rneed',
    },
    'switch536' : {
        'device_type': 'hp_procurve',
        'ip': '172.20.100.110',
        'username': 'itmaro523',
        'password': 'Lastb#Nf0rneed',
    }
}
cmd = 'show flash'
logging.basicConfig(filename='netmiko_global.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")
for key, values in hpswitches.items():
    device_type = values.get('device_type', {})
    ip_address = values.get('ip', {})
    username = values.get('username', {})
    password = values.get('password', {})
    print(f'\n{ip_address}  =  {device_type} \n')
    start_time = datetime.now()
    try:
        net_connect = ConnectHandler(device_type=device_type, host=ip_address,
                        username=username, password=password, conn_timeout=60, auth_timeout=60)
    except Exception as e:
        print(e)
        end_time = datetime.now()
        print(f"Execution time: {end_time - start_time}")
        continue
    check = net_connect.send_command(cmd)
    end_time = datetime.now()
    print(check)
    print("\n")
    print(f"Execution time: {end_time - start_time}")
    print("\n")
````
