### ISSUE TITLE
OSError: Search pattern never detected in send_command_expect: RP\/0\/RP0\/CPU0\:

### ISSUE THREAD

**Issue by kvishu17** [ktbyers/netmiko#2540]
When trying to execute 'admin' commands for Cisco NCS5500 IOS XR device, getting below error

```
import paramiko
from netmiko import ConnectHandler
from getpass import getpass

conn_data = {
    'device_type': 'cisco_xr',
    'host': '192.168.0.8',
    'username': 'cisco',
    'password': getpass(),
    
} 
nc = ConnectHandler(**conn_data)
ad_mode = nc.send_command('admin')
ad_config = nc.send_command('config terminal')


Traceback (most recent call last):
  File "DRFU_Auto_Part1.py" in <module>
    user_std_pass()
  File "DRFU_Auto_Part1.py" in user_std_pass
    ad_mode = nc.send_command('admin')
  File "/data/env/lib/python3.5/site-packages/netmiko/base_connection.py", line 1337, in send_command
    search_pattern
OSError: Search pattern never detected in send_command_expect: RP\/0\/RP0\/CPU0\:ios#
```

**Comment by ktbyers** [comment]
What does the CLI like when you send the `admin` command i.e. if you do this manually what do you see?

**Comment by ktbyers** [comment]
Okay, try:

```python
ad_mode = nc.send_command('admin', expect_string=r"#")
nc.set_base_prompt()
```

Note, you should be using `send_config_set()` and not using `send_command()` to enter into config_mode().


Regards, Kirk

**Comment by tu-pm** [comment]
I'm experimenting the same issue:

```python
>>> from netmiko import ConnectHandler
>>> 
>>> client = ConnectHandler(
...     device_type='cisco_xr_telnet',
...     host=HOSTNAME,
...     username=USERNAME,
...     password=PASSWORD',
... )
>>> print(client.send_command('show interfaces'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/netmiko/utilities.py", line 500, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/netmiko/base_connection.py", line 1537, in send_command
    search_pattern
OSError: Search pattern never detected in send_command: RP/0/RP0/CPU0:HHT9402CRT10\.CKV\.CRS16\.01\#
```

For show commands like this, netmiko suggests using `send_command_timing`, but it gives an even stranger result:

```python
>>> print(client.send_command_timing('show interfaces'))

RP/0/RP0/CPU0:HHT9402CRT10.CKV.CRS16.01#

RP/0/RP0/CPU0:HHT9402CRT10.CKV.CRS16.01#

RP/0/RP0/CPU0:HHT9402CRT10.CKV.CRS16.01#show interfaces

Mon Dec 13 16:33:38.483 HANOI

>>> print(client.send_command_timing('show interfaces'))

<<<ACTUAL INTERFACE DATA>>>

RP/0/RP0/CPU0:HHT9402CRT10.CKV.CRS16.01#show interfaces

Mon Dec 13 16:34:34.326 HANOI
```

It looks like the prompt is being held up somewhere until the next `send_command_timing` is triggered.

Other information:
- Python version: 3.7
- Netmiko version: 3.4
- IOS version: Various versions from 4.3.1 to 6.1.4. It looks like the error is more related to the device than the OS version, since some devices do have this error and some don't, regardless of version.
- Errored command: 'show interfaces' (I checked with some other show commands but none of them has this error)

@ktbyers Can you take a look at this, please?

**Comment by kvishu17** [comment]
> ```python
> nc.send_command('admin', expect_string=r"#")
> ```

Thanks Kirk.
It worked for me to enter into sysadmin mode.
