### ISSUE TITLE
auth_timeout should be made to work with telnet_login

### ISSUE THREAD

**Issue by jalbai** [ktbyers/netmiko#2563]
Hi 
I tried to connect via telnet on a cisco device (cisco_ios_telnet) and it did not worked using version 3.4.0 

DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: User Access Verification
login: 

Password: 
DEBUG:netmiko:write_channel: b'<username>\r'
DEBUG:netmiko:read_channel: 

However if I downgraded to 3.1.1 it works just fine

DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
Login incorrect

User Access Verification
login: 
DEBUG:netmiko:write_channel: b'<username>\r\n'
DEBUG:netmiko:read_channel: netauto
Password: 
DEBUG:netmiko:write_channel: b'<password>\r\n'
DEBUG:netmiko:read_channel: 

It looks like the issue started with 3.2.0

**Comment by ktbyers** [comment]
Have you tried the Netmiko `develop` branch? I think there is something we fixed not too long ago.

If that doesn't work, I would try setting fast_cli=False as an argument to ConnectHandler and see if that fixes the problem.

**Comment by jalbai** [comment]
fast_cli=False is not fixing the issue.

**Comment by przemoz** [comment]
I have tried all versions from 3.1.1 to develop, last working version is 3.1.1.
example script:
`from netmiko import ConnectHandler
import logging

logging.basicConfig(filename='netmiko_debug_output.log', level=logging.DEBUG,format='%(asctime)s %(levelname)-8s %(message)s')
logger = logging.getLogger('netmiko')


router = {
	'device_type': 'cisco_ios_telnet',
	'ip': "x.x.x.x",
	'username': "automaton",
	'password': "testpass",
	'auth_timeout' : 45,
	'global_delay_factor': 10,
	}
device = ConnectHandler(**router)
device.disable_paging()
find_hostname = device.find_prompt()
command = device.send_command('show ver')
print(command)
device.disconnect()`

,
in netmiko > 3.1.1 after about 2 seconds it throws an exception:
`Traceback (most recent call last):
  File "./for_gitgub.py", line 19, in <module>
    device = ConnectHandler(**router)
  File "/cisco_netmiko_3/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 326, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/cisco_netmiko_3/lib/python3.6/site-packages/netmiko/cisco/cisco_ios.py", line 17, in __init__
    return super().__init__(*args, **kwargs)
  File "/cisco_netmiko_3/lib/python3.6/site-packages/netmiko/base_connection.py", line 350, in __init__
    self._open()
  File "/cisco_netmiko_3/lib/python3.6/site-packages/netmiko/base_connection.py", line 355, in _open
    self.establish_connection()
  File "/cisco_netmiko_3/lib/python3.6/site-packages/netmiko/base_connection.py", line 925, in establish_connection
    self.telnet_login()
  File "/cisco_netmiko_3/lib/python3.6/site-packages/netmiko/cisco_base_connection.py", line 185, in telnet_login
    raise NetmikoAuthenticationException(msg)
netmiko.ssh_exception.NetmikoAuthenticationException: Login failed: x.x.x.x
`
debug:
`2021-11-04 16:46:12,548 DEBUG    read_channel: 

User Access Verification

Username: 
2021-11-04 16:46:12,549 DEBUG    write_channel: b'automaton\r'
2021-11-04 16:46:13,550 DEBUG    read_channel: automaton
Password: 
2021-11-04 16:46:13,550 DEBUG    write_channel: b'testpass\r'
2021-11-04 16:46:14,051 DEBUG    read_channel: 
2021-11-04 16:46:14,052 DEBUG    read_channel: 
2021-11-04 16:46:14,052 DEBUG    read_channel: 
2021-11-04 16:46:14,052 DEBUG    read_channel: 
2021-11-04 16:46:14,052 DEBUG    read_channel: 
2021-11-04 16:46:14,052 DEBUG    read_channel: 
2021-11-04 16:46:14,052 DEBUG    write_channel: b'\r\n'
2021-11-04 16:46:14,553 DEBUG    read_channel: 
2021-11-04 16:46:14,553 DEBUG    read_channel: 
2021-11-04 16:46:14,553 DEBUG    read_channel: 
2021-11-04 16:46:14,553 DEBUG    read_channel: 
2021-11-04 16:46:14,553 DEBUG    read_channel: 
2021-11-04 16:46:14,553 DEBUG    read_channel: 
2021-11-04 16:46:14,553 DEBUG    write_channel: b'\r\n'
2021-11-04 16:46:15,054 DEBUG    read_channel: 
2021-11-04 16:46:15,054 DEBUG    read_channel: 
2021-11-04 16:46:15,054 DEBUG    read_channel: 
2021-11-04 16:46:15,054 DEBUG    read_channel: 
2021-11-04 16:46:15,054 DEBUG    read_channel: 
2021-11-04 16:46:15,054 DEBUG    read_channel: 
2021-11-04 16:46:15,054 DEBUG    write_channel: b'\r\n'
2021-11-04 16:46:15,555 DEBUG    write_channel: b'\r\n'
2021-11-04 16:46:16,056 DEBUG    read_channel: `

same script in netmiko 3.1.1 works ok:
`2021-11-04 16:36:06,008 DEBUG    read_channel: 

User Access Verification

Username: 
2021-11-04 16:36:06,008 DEBUG    write_channel: b'automaton\r\n'
2021-11-04 16:36:16,011 DEBUG    read_channel: automaton
Password: 
2021-11-04 16:36:16,011 DEBUG    write_channel: b'testpass\r\n'
2021-11-04 16:36:21,017 DEBUG    read_channel: 
2021-11-04 16:36:21,017 DEBUG    write_channel: b'\r\n'
2021-11-04 16:36:26,023 DEBUG    read_channel: 

TESTRT11#
TESTRT11#
2021-11-04 16:36:37,034 DEBUG    read_channel: 
2021-11-04 16:36:57,052 DEBUG    read_channel: 
2021-11-04 16:36:57,052 DEBUG    write_channel: b'\r\n'
2021-11-04 16:36:59,154 DEBUG    read_channel: 
TESTRT11#
2021-11-04 16:37:00,155 DEBUG    read_channel: 
2021-11-04 16:37:20,175 DEBUG    read_channel: 
2021-11-04 16:37:21,176 DEBUG    read_channel: 
2021-11-04 16:37:21,177 DEBUG    write_channel: b'\r\n'
2021-11-04 16:37:22,177 DEBUG    read_channel: 
TESTRT11#
2021-11-04 16:37:24,180 DEBUG    read_channel: 
2021-11-04 16:37:24,180 DEBUG    [find_prompt()]: prompt is TESTRT11#
2021-11-04 16:37:26,182 DEBUG    read_channel: 
2021-11-04 16:37:26,182 DEBUG    In disable_paging
2021-11-04 16:37:26,183 DEBUG    Command: terminal length 0`

this problem occurs when waitng for prompt after password takes more than  about 2 seconds, as if ignoring "auth_timeout"

**Comment by ktbyers** [comment]
Try:

```python
router = {
'device_type': 'cisco_ios_telnet',
'ip': "x.x.x.x",
'username': "automaton",
'password': "testpass",
'fast_cli': False,
}
```

Use Netmiko 3.4.0 or the `develop` branch.

What happens with this?

Obviously, cisco_ios_telnet works for me on both Netmiko 3.4.0 and on the `develop` branch. So we have to figure out why it is failing for you.

**Comment by przemoz** [comment]
This error is from 3.4.0, i tested this in all versions from 3.1.1 to develop (last working is 3.1.1). "'fast_cli':False" makes no differences. As I mention before problem occours only if waiting for router prompt after password takes more than about 2 seconds. If prompt appears faster then there is no problem (tested on other router, same model and firmware), so it looks like "auth_timeout" makes no differences?

**Comment by przemoz** [comment]
debug from 3.4.0 with 'fast_cli': False   :
`2021-11-04 17:09:29,237 DEBUG    read_channel: 

User Access Verification

Username: 
2021-11-04 17:09:29,237 DEBUG    write_channel: b'automaton\r'
2021-11-04 17:09:30,239 DEBUG    read_channel: automaton
Password: 
2021-11-04 17:09:30,240 DEBUG    write_channel: b'testpass\r'
2021-11-04 17:09:30,740 DEBUG    read_channel: 
2021-11-04 17:09:30,741 DEBUG    read_channel: 
2021-11-04 17:09:30,741 DEBUG    read_channel: 
2021-11-04 17:09:30,741 DEBUG    read_channel: 
2021-11-04 17:09:30,741 DEBUG    read_channel: 
2021-11-04 17:09:30,741 DEBUG    read_channel: 
2021-11-04 17:09:30,742 DEBUG    write_channel: b'\r\n'
2021-11-04 17:09:31,242 DEBUG    read_channel: 
2021-11-04 17:09:31,242 DEBUG    read_channel: 
2021-11-04 17:09:31,242 DEBUG    read_channel: 
2021-11-04 17:09:31,242 DEBUG    read_channel: 
2021-11-04 17:09:31,242 DEBUG    read_channel: 
2021-11-04 17:09:31,242 DEBUG    read_channel: 
2021-11-04 17:09:31,243 DEBUG    write_channel: b'\r\n'
2021-11-04 17:09:31,743 DEBUG    read_channel: 
2021-11-04 17:09:31,743 DEBUG    read_channel: 
2021-11-04 17:09:31,744 DEBUG    read_channel: 
2021-11-04 17:09:31,744 DEBUG    read_channel: 
2021-11-04 17:09:31,744 DEBUG    read_channel: 
2021-11-04 17:09:31,744 DEBUG    read_channel: 
2021-11-04 17:09:31,744 DEBUG    write_channel: b'\r\n'
2021-11-04 17:09:32,245 DEBUG    write_channel: b'\r\n'
2021-11-04 17:09:32,746 DEBUG    read_channel: `

**Comment by ktbyers** [comment]
Okay, try the following:

```python
router = {
'device_type': 'cisco_ios_telnet',
'ip': "x.x.x.x",
'username': "automaton",
'password': "testpass",
'fast_cli': False,
'global_delay_factor': 4,
}
```

Yes, auth_timeout is SSH only so won't work for telnet.

Code is here:

https://github.com/ktbyers/netmiko/blob/v3.4.0/netmiko/cisco_base_connection.py#L81

**Comment by przemoz** [comment]
'fast_cli': False,
'global_delay_factor': 4, 

this combo works
```2021-11-04 17:50:52,747 DEBUG    read_channel: 


User Access Verification

Username: 
2021-11-04 17:50:52,747 DEBUG    write_channel: b'automaton\r'
2021-11-04 17:50:56,752 DEBUG    read_channel: automaton
Password: 
2021-11-04 17:50:56,752 DEBUG    write_channel: b'testpass\r'
2021-11-04 17:50:58,754 DEBUG    read_channel: 
2021-11-04 17:50:58,755 DEBUG    read_channel: 
2021-11-04 17:50:58,755 DEBUG    read_channel: 
2021-11-04 17:50:58,755 DEBUG    read_channel: 
2021-11-04 17:50:58,755 DEBUG    read_channel: 
2021-11-04 17:50:58,755 DEBUG    read_channel: 
2021-11-04 17:50:58,755 DEBUG    write_channel: b'\r\n'
2021-11-04 17:51:00,757 DEBUG    read_channel: 
2021-11-04 17:51:00,757 DEBUG    read_channel: 
2021-11-04 17:51:00,757 DEBUG    read_channel: 
2021-11-04 17:51:00,757 DEBUG    read_channel: 
2021-11-04 17:51:00,757 DEBUG    read_channel: 
2021-11-04 17:51:00,757 DEBUG    read_channel: 
2021-11-04 17:51:00,758 DEBUG    write_channel: b'\r\n'
2021-11-04 17:51:02,759 DEBUG    read_channel: 

TESTRT11#
TESTRT11#
TESTRT11#
2021-11-04 17:51:02,759 DEBUG    write_channel: b'terminal width 511\r\n'
2021-11-04 17:51:02,759 DEBUG    Pattern is: terminal width 511
```

Thank You :)

**Comment by ktbyers** [comment]
I am going to keep this open as auth_timeout should be wired in such that it works with telnet in the future.


Kirk

**Comment by clawtonnc** [comment]
> 'fast_cli': False, 'global_delay_factor': 4,
> 
> this combo works
> 
> ```
> 
> 
> User Access Verification
> 
> Username: 
> 2021-11-04 17:50:52,747 DEBUG    write_channel: b'automaton\r'
> 2021-11-04 17:50:56,752 DEBUG    read_channel: automaton
> Password: 
> 2021-11-04 17:50:56,752 DEBUG    write_channel: b'testpass\r'
> 2021-11-04 17:50:58,754 DEBUG    read_channel: 
> 2021-11-04 17:50:58,755 DEBUG    read_channel: 
> 2021-11-04 17:50:58,755 DEBUG    read_channel: 
> 2021-11-04 17:50:58,755 DEBUG    read_channel: 
> 2021-11-04 17:50:58,755 DEBUG    read_channel: 
> 2021-11-04 17:50:58,755 DEBUG    read_channel: 
> 2021-11-04 17:50:58,755 DEBUG    write_channel: b'\r\n'
> 2021-11-04 17:51:00,757 DEBUG    read_channel: 
> 2021-11-04 17:51:00,757 DEBUG    read_channel: 
> 2021-11-04 17:51:00,757 DEBUG    read_channel: 
> 2021-11-04 17:51:00,757 DEBUG    read_channel: 
> 2021-11-04 17:51:00,757 DEBUG    read_channel: 
> 2021-11-04 17:51:00,757 DEBUG    read_channel: 
> 2021-11-04 17:51:00,758 DEBUG    write_channel: b'\r\n'
> 2021-11-04 17:51:02,759 DEBUG    read_channel: 
> 
> TESTRT11#
> TESTRT11#
> TESTRT11#
> 2021-11-04 17:51:02,759 DEBUG    write_channel: b'terminal width 511\r\n'
> 2021-11-04 17:51:02,759 DEBUG    Pattern is: terminal width 511
> ```
> 
> Thank You :)

**Comment by clawtonnc** [comment]
Have had a similar issue for the past few weeks.  Been playing with the timers but didn't work.  @ktbyers  thanks for the comment about adding fast_cli and global_delay_factor.   This is on a few Cisco 2950 switches.  I had to go all the way to 8.  Do you believe this a Netmiko timing issue or an issue on the device?

'fast_cli': False,
'global_delay_factor':  8

**Comment by ktbyers** [comment]
@clawtonnc Are you just using straight telnet or is it telnet + a terminal server?

Is there any reason these devices are particularly slow? 

Telnet login is prone to breaking so it is pretty easy to run into timing issues.

**Comment by clawtonnc** [comment]
@ktbyers   Straight Telnet.  These devices are cascaded (switch to switch).  Trying to figure out why it is slow.  It's even slow when using telnet from SecureCRT and directly from one switch to the other.  Looking at them to understand as we are replacing these with new devices soon.  Thanks for what you do with Netmiko!

**Comment by tu-pm** [comment]
I think a know the reason why netmiko fails to login to slow cisco devices: There's a problem with the `telnet_login` method of `CiscoBaseConnection` class.

As you can see [here](https://github.com/ktbyers/netmiko/blob/4c3732346eea1a4a608abd9e09d65eeb2f577810/netmiko/cisco_base_connection.py#L103), the logic breaks down the `max_loops` params in two loops: `outer_loops` and `inner_loops`.

But inside both loops, when no data is detected (indicating that the switch is processing the authentication request), there's no `sleep` calls, meaning the loops immediately proceed to the next iteration.

=> All loops pass by instantly while the switch is still proccessing the request.

Increasing `delay_factor` makes [the first `sleep`](https://github.com/ktbyers/netmiko/blob/4c3732346eea1a4a608abd9e09d65eeb2f577810/netmiko/cisco_base_connection.py#L96) wait longer, thus gives the switch more time to response. But that also means that if we use the same configuration for every switch we have, all of them must take the same amount of time to login as the slowest one.

To resolve this, I think we should add a new sleep on each loop, just like [the default base connection does](https://github.com/ktbyers/netmiko/blob/4c3732346eea1a4a608abd9e09d65eeb2f577810/netmiko/base_connection.py#L827).

**Comment by przemoz** [comment]
Maybe we can use :
`time.sleep(0.5 * auth_timeout)`
in that loop instead of : 
`time.sleep(0.5 * delay_factor)`

Also in last version which works ok with this specific problem (3.11), there was:
```
  # Check if proper data received
  if re.search(pri_prompt_terminator, output, flags=re.M) or re.search(
       alt_prompt_terminator, output, flags=re.M
  ):
       return return_msg
  self.write_channel(self.TELNET_RETURN)
  time.sleep(0.5 * delay_factor)
  i += 1
```
and in 3.4.0 release there is:
``` 
  # Check if proper data received
  if re.search(pri_prompt_terminator, output, flags=re.M) or re.search(
       alt_prompt_terminator, output, flags=re.M
  ):
       return return_msg

  i += 1
```

regression?

**Comment by ktbyers** [comment]
Didn't implement the auth_timeout for telnet, but did make the fix/improvement that @tu-pm pointed out.

https://github.com/ktbyers/netmiko/pull/3635
