### ISSUE TITLE
Nokia OLT--SSH--ValueError: p must be exactly 1024, 2048, 3072, or 4096 bits long

### ISSUE THREAD

**Issue by ghost** [ktbyers/netmiko#2577]
Hello, GitHub community, 
I am having trouble with netmiko.
ValueError: p must be exactly 1024, 2048, 3072, or 4096 bits long.

Device I am trying to log into: Nokia OLT 
I have a couple of Nokia OLTs and this script works in some and gives an error in some. I did a diff on the configs and they are the exact same. so I am pretty sure this is not an OLT config issue.

Can someone please help me on this? 
(admins can you please not close this ticket)

netmiko         3.4.0

Unknown exception: p must be exactly 1024, 2048, 3072, or 4096 bits long
Traceback (most recent call last):
  File "C:\Users\biz\PycharmProjects\pythonProject\venv\lib\site-packages\paramiko\transport.py", line 2075, in run
    self.kex_engine.parse_next(ptype, m)
  File "C:\Users\biz\PycharmProjects\pythonProject\venv\lib\site-packages\paramiko\kex_group1.py", line 75, in parse_next
    return self._parse_kexdh_reply(m)
  File "C:\Users\biz\PycharmProjects\pythonProject\venv\lib\site-packages\paramiko\kex_group1.py", line 120, in _parse_kexdh_reply
    self.transport._verify_key(host_key, sig)
  File "C:\Users\biz\PycharmProjects\pythonProject\venv\lib\site-packages\paramiko\transport.py", line 1886, in _verify_key
    if not key.verify_ssh_sig(self.H, Message(sig)):
  File "C:\Users\biz\PycharmProjects\pythonProject\venv\lib\site-packages\paramiko\dsskey.py", line 148, in verify_ssh_sig
    key = dsa.DSAPublicNumbers(
  File "C:\Users\biz\PycharmProjects\pythonProject\venv\lib\site-packages\cryptography\hazmat\primitives\asymmetric\dsa.py", line 206, in public_key
    return backend.load_dsa_public_numbers(self)
  File "C:\Users\biz\PycharmProjects\pythonProject\venv\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 845, in load_dsa_public_numbers
    dsa._check_dsa_parameters(numbers.parameter_numbers)
  File "C:\Users\biz\PycharmProjects\pythonProject\venv\lib\site-packages\cryptography\hazmat\primitives\asymmetric\dsa.py", line 270, in _check_dsa_parameters
    raise ValueError(
ValueError: p must be exactly 1024, 2048, 3072, or 4096 bits long

Traceback (most recent call last):
  File "C:\Users\biz\PycharmProjects\pythonProject\chassis-build\connect.py", line 42, in <module>
    conn()
  File "C:\Users\biz\PycharmProjects\pythonProject\chassis-build\connect.py", line 18, in conn
    net_connect = ConnectHandler(**CSR)
  File "C:\Users\biz\PycharmProjects\pythonProject\venv\lib\site-packages\netmiko\ssh_dispatcher.py", line 326, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\biz\PycharmProjects\pythonProject\venv\lib\site-packages\netmiko\cisco\cisco_ios.py", line 17, in __init__
    return super().__init__(*args, **kwargs)
  File "C:\Users\biz\PycharmProjects\pythonProject\venv\lib\site-packages\netmiko\base_connection.py", line 350, in __init__
    self._open()
  File "C:\Users\biz\PycharmProjects\pythonProject\venv\lib\site-packages\netmiko\base_connection.py", line 355, in _open
    self.establish_connection()
  File "C:\Users\biz\PycharmProjects\pythonProject\venv\lib\site-packages\netmiko\base_connection.py", line 935, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "C:\Users\biz\PycharmProjects\pythonProject\venv\lib\site-packages\paramiko\client.py", line 406, in connect
    t.start_client(timeout=timeout)
  File "C:\Users\biz\PycharmProjects\pythonProject\venv\lib\site-packages\paramiko\transport.py", line 660, in start_client
    raise e
  File "C:\Users\biz\PycharmProjects\pythonProject\venv\lib\site-packages\paramiko\transport.py", line 2075, in run
    self.kex_engine.parse_next(ptype, m)
  File "C:\Users\biz\PycharmProjects\pythonProject\venv\lib\site-packages\paramiko\kex_group1.py", line 75, in parse_next
    return self._parse_kexdh_reply(m)
  File "C:\Users\biz\PycharmProjects\pythonProject\venv\lib\site-packages\paramiko\kex_group1.py", line 120, in _parse_kexdh_reply
    self.transport._verify_key(host_key, sig)
  File "C:\Users\biz\PycharmProjects\pythonProject\venv\lib\site-packages\paramiko\transport.py", line 1886, in _verify_key
    if not key.verify_ssh_sig(self.H, Message(sig)):
  File "C:\Users\biz\PycharmProjects\pythonProject\venv\lib\site-packages\paramiko\dsskey.py", line 148, in verify_ssh_sig
    key = dsa.DSAPublicNumbers(
  File "C:\Users\biz\PycharmProjects\pythonProject\venv\lib\site-packages\cryptography\hazmat\primitives\asymmetric\dsa.py", line 206, in public_key
    return backend.load_dsa_public_numbers(self)
  File "C:\Users\biz\PycharmProjects\pythonProject\venv\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 845, in load_dsa_public_numbers
    dsa._check_dsa_parameters(numbers.parameter_numbers)
  File "C:\Users\biz\PycharmProjects\pythonProject\venv\lib\site-packages\cryptography\hazmat\primitives\asymmetric\dsa.py", line 270, in _check_dsa_parameters
    raise ValueError(
ValueError: p must be exactly 1024, 2048, 3072, or 4096 bits long

Process finished with exit code 1

**Comment by ktbyers** [comment]
@Bizzo1990 A common fix for this is to regenerate your SSH keys and to use one of the above allowed key lengths.

```
ValueError: p must be exactly 1024, 2048, 3072, or 4096 bits long
```

Can you try that on one device and see if it works?

**Comment by Bizzo1990** [comment]
@ktbyers  thank you for the reply, I apologize for my lack of knowledge on this topic. 
 I am using windows 10 / pycharm.  

would this still be a troubleshooting step?

**Comment by ktbyers** [comment]
You regenerate the SSH keys on the network device and then see if that fixes the problem.

There also might be a way to fix in Netmiko, but the regenerate keys is one solution that people have done in the past.

**Comment by ram-i** [comment]
Hi @ktbyers 
I'm using Netmiko to connect to OneAcces devices and am facing a similar issue where I am unable to connect to some network devices, returns error:
`ValueError: p must be exactly 1024, 2048, 3072, or 4096 bits long`

I am able to successfully SSH to the above device using Secure CRT, just not via Netmiko.

Are there any other suggestions other than regenerating SSH keys on the network device?  Thanks

**Comment by ktbyers** [comment]
Yeah, I think the fix is to regenerate the key on the network device. I guess you can try to dig into Paramiko and see if there is an alternate fix, but the easy fix is to create a new key.

**Comment by ktbyers** [comment]
Adding link to fix that we implemented on TP Link. We could possibly implement this elsewhere though probably would need to better understand the security implications:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/tplink/tplink_jetstream.py#L146-L168

**Comment by ram-i** [comment]
Hi @ktbyers 
Thanks for your response. Based on the above fix that you have done for TP Link, would it be possible for a similar fix on OneAccess?

**Comment by ktbyers** [comment]
@ram-i Have you tested it and seen if it fixes your problem or not?

Why can't you change the SSH keys on the device?

**Comment by robin-gllt** [comment]
As indicated by the error message the issue is indeed linked to the DSA key size. 
In my case my oneaccess routers were using 512 dsa key size. 
Depending of the context it's not always possible to regenerate the DSA keys on devices (notably if there is a large install base to manage)

To fix this I directly edited the _check_dsa_parameters function in dsa.py file in my environment (e.g \site-packages\cryptography\hazmat\primitives\asymmetric\dsa.py)  as below:

`def _check_dsa_parameters(parameters):
    if parameters.p.bit_length() not in [**512**, 1024, 2048, 3072, 4096]:
        raise ValueError(
            "p must be exactly **512**, 1024, 2048, 3072, or 4096 bits long. **Size now is: " + str(parameters.p.bit_length()**)
        )`

But it's a quick and dirty way. The recommended way would be to do like @ktbyers and only overwrite this dsa function for the specific device brand profile

Note that if you are not sure of your devices key size you can add a print of it in the dsa function error message (c.f str(parameters.p.bit_length())

**Comment by py-noob-01** [comment]
> As indicated by the error message the issue is indeed linked to the DSA key size. In my case my oneaccess routers were using 512 dsa key size. Depending of the context it's not always possible to regenerate the DSA keys on devices (notably if there is a large install base to manage)
> 
> To fix this I directly edited the _check_dsa_parameters function in dsa.py file in my environment (e.g \site-packages\cryptography\hazmat\primitives\asymmetric\dsa.py). I added the size 512 in the list of supported size, as below:
> 
> > def _check_dsa_parameters(parameters):
> > if parameters.p.bit_length() not in [**_512_**, 1024, 2048, 3072, 4096]:
> > raise ValueError(
> > "p must be exactly **_512_**, 1024, 2048, 3072, or 4096 bits long. _**Size now is: " + str(parameters.p.bit_length()**_)
> > )
> 
> But it's a quick and dirty way. The recommended way would be to do like @ktbyers and only overwrite this dsa function for the specific device brand profile
> 
> Note that if you are not sure of your devices key size you can add a print of it in the dsa function error message to get it (c.f str(parameters.p.bit_length())

thanks!! robin-gllt

**Comment by ktbyers** [comment]
I am going to close this as it is old and it doesn't look like anyone is actively working on it.

**Comment by humbertogaliza** [comment]
For future reference, in case anyone else encounters this issue and finds the above discussion: I experienced this limitation while testing Netmiko 4.5.0 with a TP-Link OLT (Deltastream DS7001-P). I discovered that the netmiko patch mentioned here ( `_override_check_dsa_parameters()` ) no longer works because the `_check_dsa_parameters()` function that was previously in the `dsa.py` module of the Cryptography package has been moved to Rust backend, as indicated by this commit in their package.https://github.com/pyca/cryptography/commit/df3c75955bc40be52ddbb1b620ba350b3ae62b32#diff-9af4852fa621a78a1a4372391c794a44dfaeffadf7ffb685e36b62d54a3f4a53

new check_dsa_parameters() --> https://github.com/pyca/cryptography/blob/main/src/rust/src/backend/dsa.rs#L255

Unfortunately, upgrading the testing OLT to use more secure SSH algorithms is not an option, so I will continue to explore other possibilities.
