### ISSUE TITLE
ssh timeout exception not working 

### ISSUE THREAD

**Issue by Birajan2019** [ktbyers/netmiko#2606]
Hello,

Even though I have the netmiko timeout exception defined on my script, it doesn't seem to be handling errors. Here is the error, I get went trying to change config on my network switch. Any help would be highly appreciated:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\raga\AppData\Local\Programs\Python\Python38\lib\site-packages\netmiko\base_connection.py", line 550, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\Users\raga\AppData\Local\Programs\Python\Python38\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\lwc-change-config-1.py", line 42, in <module>
    output1 = net_connect.send_config_from_file(config_file = 'lwc-set-config.txt')
  File "C:\Users\raga\AppData\Local\Programs\Python\Python38\lib\site-packages\netmiko\base_connection.py", line 1665, in send_config_from_file
    return self.send_config_set(cfg_file, **kwargs)
  File "C:\Users\raga\AppData\Local\Programs\Python\Python38\lib\site-packages\netmiko\base_connection.py", line 1759, in send_config_set
    new_output = self.read_until_pattern(pattern=pattern)
  File "C:\Users\raga\AppData\Local\Programs\Python\Python38\lib\site-packages\netmiko\base_connection.py", line 627, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "C:\Users\raga\AppData\Local\Programs\Python\Python38\lib\site-packages\netmiko\base_connection.py", line 560, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

**Comment by applericky** [comment]
This looks like it's failing to connect to the device? Have you tried to walk your code with the REPL or using a debugger like PDB/IPDB? 

Some things you can also provide for us. 
- Your code where the script stops.
- Your version on Netmiko.
- Your version on Python.

Thanks.
