### ISSUE TITLE
huawei_vrpv8 driver uses exit_config_mode=True

### ISSUE THREAD

**Issue by dmulyalin** [ktbyers/netmiko#2625]
Hi,

Huawei huawei_vrpv8 driver uses `exit_config_mode=True` for `send_config_set` method, which is not the very intuitive and appropriate, due to the fact that vrpv8 platform need configuration commit to apply it, trying to exit config mode without commiting or discarding changes results in unusable session, as device prompt stuck with commit question and Netmiko exits with below error:

```
2022-01-10 11:28:49,295 [DEBUG   ] read_channel: 
<Huawei-Box-1>
2022-01-10 11:28:49,395 [DEBUG   ] read_channel: 
2022-01-10 11:28:51,398 [DEBUG   ] read_channel: 
2022-01-10 11:28:51,398 [DEBUG   ] write_channel: b'system-view\n'
2022-01-10 11:28:51,398 [DEBUG   ] Pattern is: system\-view
2022-01-10 11:28:51,415 [DEBUG   ] _read_channel_expect read_data: system-view
2022-01-10 11:28:51,415 [DEBUG   ] Pattern found: system\-view system-view
2022-01-10 11:28:51,415 [DEBUG   ] Pattern is: Huawei\-Box\-1
2022-01-10 11:28:51,463 [DEBUG   ] _read_channel_expect read_data: Enter system view, return user view with return command.
2022-01-10 11:28:51,564 [DEBUG   ] _read_channel_expect read_data: 
[~Huawei-Box-1]
2022-01-10 11:28:51,564 [DEBUG   ] Pattern found: Huawei\-Box\-1 Enter system view, return user view with return command.
[~Huawei-Box-1]
2022-01-10 11:28:51,564 [DEBUG   ] write_channel: b'\n'
2022-01-10 11:28:51,665 [DEBUG   ] read_channel: 
[~Huawei-Box-1]
2022-01-10 11:28:51,765 [DEBUG   ] read_channel: 
2022-01-10 11:28:53,767 [DEBUG   ] read_channel: 
2022-01-10 11:28:53,768 [DEBUG   ] write_channel: b'interface LoopBack777\n'
2022-01-10 11:28:53,918 [DEBUG   ] read_channel: interface LoopBack777
[*Huawei-Box-1-LoopBack777]
2022-01-10 11:28:54,019 [DEBUG   ] read_channel: 
2022-01-10 11:28:56,021 [DEBUG   ] read_channel: 
2022-01-10 11:28:56,022 [DEBUG   ] write_channel: b'\n'
2022-01-10 11:28:56,122 [DEBUG   ] read_channel: 
[*Huawei-Box-1-LoopBack777]
2022-01-10 11:28:56,223 [DEBUG   ] read_channel: 
2022-01-10 11:28:58,225 [DEBUG   ] read_channel: 
2022-01-10 11:28:58,225 [DEBUG   ] write_channel: b'return\n'
2022-01-10 11:28:58,225 [DEBUG   ] Pattern is: return
2022-01-10 11:28:58,242 [DEBUG   ] _read_channel_expect read_data: return
2022-01-10 11:28:58,242 [DEBUG   ] Pattern found: return return
2022-01-10 11:28:58,242 [DEBUG   ] Pattern is: >
2022-01-10 11:28:58,287 [DEBUG   ] _read_channel_expect read_data: Warning: Uncommitted configurations found, commit them before exiting? [Y(yes)/N(no)/C(cancel)]:
2022-01-10 11:29:18,388 [ERROR   ] Host 'Huawei-Box-1': task 'netmiko_send_config' failed with traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.6/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 573, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.6/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.6/site-packages/nornir_salt/plugins/tasks/netmiko_send_config.py", line 146, in netmiko_send_config
    task_result.result = conn.send_config_set(config_commands=config, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 1930, in send_config_set
    output += self.exit_config_mode()
  File "/usr/local/lib/python3.6/site-packages/netmiko/huawei/huawei.py", line 39, in exit_config_mode
    return super().exit_config_mode(exit_config=exit_config, pattern=pattern)
  File "/usr/local/lib/python3.6/site-packages/netmiko/cisco_base_connection.py", line 54, in exit_config_mode
    return super().exit_config_mode(exit_config=exit_config, pattern=pattern)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 1787, in exit_config_mode
    output += self.read_until_pattern(pattern=pattern)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 655, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 584, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.
```
Please note `2022-01-10 11:28:58,287` timestamp with message from device regarding what to do with uncommited changes.

Would it make sense tooverride `send_config_set` method for [HuaweiVrpv8SSH class](https://github.com/ktbyers/netmiko/blob/4c3732346eea1a4a608abd9e09d65eeb2f577810/netmiko/huawei/huawei.py#L200) similar how its done for [cisco_xr driver](https://github.com/ktbyers/netmiko/blob/4c3732346eea1a4a608abd9e09d65eeb2f577810/netmiko/cisco/cisco_xr.py#L23) and set `exit_config_mode` to False.

As of now as a workaround supplying `exit_config_mode=False` to `send_config_set` call fixes the issue.

Would be glad to help with PR but would like to hear people thoughts on it.

**Comment by ktbyers** [comment]
@dmulyalin Sounds good on switching the default on `exit_config_mode` for VRPV8 to False. Do you want to send the PR on this?

**Comment by dmulyalin** [comment]
Thank you @ktbyers for merging the pull request, feel free to close this ticket if there is nothing else left to do.

The fix merged - to give some confidence - tested it with a number of physical Huawei devices before submitting pull request, it was working as expected in my tests.
