### ISSUE TITLE
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

### ISSUE THREAD

**Issue by kakollu007** [ktbyers/netmiko#2626]
Code : 
import os
import time
import sys
from datetime import date
from netmiko import Netmiko
from getpass import getpass
from netmiko import ConnectHandler

my_device1 = {
    "host": "10.60.38.67",
    "username": "admin",
    "password": "*******",
    "device_type": "dell_os10",
}

net_connect = ConnectHandler(**my_device1)
config_commands = [ 'radius-server retransmit 10',
                    'aaa authentication login default local group radius',
                    'aaa authentication login console local' ]
output = net_connect.send_config_set(config_commands)
print(output)

error
---------------------
Traceback (most recent call last):
  File "C:\Users\kumark35\AppData\Local\Programs\Python\Python38-32\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Users\kumark35\AppData\Local\Programs\Python\Python38-32\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kumark35\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 541, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\Users\kumark35\AppData\Local\Programs\Python\Python38-32\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kumark35\Desktop\PasswordChange.py", line 22, in <module>
    output = net_connect.send_config_set(config_commands)
  File "C:\Users\kumark35\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 1704, in send_config_set
    output = self.config_mode(*cfg_mode_args)
  File "C:\Users\kumark35\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\cisco_base_connection.py", line 40, in config_mode
    return super().config_mode(config_command=config_command, pattern=pattern)
  File "C:\Users\kumark35\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 1598, in config_mode
    output += self.read_until_pattern(pattern=re.escape(config_command.strip()))
  File "C:\Users\kumark35\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 618, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "C:\Users\kumark35\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 551, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.
>>>

**Comment by ktbyers** [comment]
Try setting: `global_cmd_verify: False` in your device dictionary:

```python
my_device1 = {
"host": "10.60.38.67",
"username": "admin",
"password": "*******",
"device_type": "dell_os10",
"global_cmd_verify": False,
}
```

**Comment by ktbyers** [comment]
@kakollu007 Any update on whether the proposed fix worked?

**Comment by ameencp533** [comment]
Thanks @ktbyers , its working for me
