### ISSUE TITLE
error while looping for Cisco devices

### ISSUE THREAD

**Issue by onlywifi** [ktbyers/netmiko#2638]
I've created a script to loop on a list of Cisco devices and perform a change but the loop stops after invoking "net_connect.save_config()", but it works if I remove that line.
This is the error it returns:
```
gbrdcwlcs001
configure terminal
Enter configuration commands, one per line.  End with CNTL/Z.
gbrdcwlcs001(config)#ap 0000.0000.0001
gbrdcwlcs001(config-ap-tag)# poli CORP-BYOD
Associating policy-tag will cause associated AP to reconnect
gbrdcwlcs001(config-ap-tag)#end
gbrdcwlcs001#write mem
Building configuration...
[OK]
Writing gbrdcwlcs001-Feb--1-2022-14-24-27.099-UTC-16
gbrdcwlcs001#
Traceback (most recent call last):
  File "C:\temp\_change_v8.py", line 40, in <module>
    **output += net_connect.save_config()**
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\netmiko\cisco\cisco_ios.py", line 36, in save_config
    return super().save_config(
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\netmiko\cisco_base_connection.py", line 246, in save_config
    output = self.send_command(
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\netmiko\utilities.py", line 500, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\netmiko\base_connection.py", line 1535, in send_command
    raise IOError(
OSError: **Search pattern never detected in send_command: gbrdcwc03\#**
```

This is my script if someone could point me in the right direction:
```
#// Create device config_templates
gbrdcwlcs001 = {"device_type":"cisco_ios","ip":"1.1.1.1","username":"admin","password":"Cisco"}
gbrdcwc03 = {"device_type":"cisco_ios","ip":"2.2.2.2","username":"admin","password":"Cisco"}
wlcList = [gbrdcwlcs001,gbrdcwc03]

# // Send config from file
configFile = Path("C:/temp/wlc_commands_test.txt")
newConfigFile = Path("C:/temp/output/"+date2+Change.txt")
with open(configFile,'rt') as f:
    configTemp=f.read().replace('{guestVar01}','0000.0000.0001')
with open(newConfigFile,'w') as f:
    f.write(configTemp)

try:
    for device in wlcList:
        with ConnectHandler(**device) as net_connect:
            wlc_hostname = net_connect.find_prompt()[:-1]
            output = net_connect.send_config_from_file(newConfigFile)
            output += net_connect.save_config()
            with open('output/'+date2+wlc_hostname+'.txt', "a") as outputfile:
                outputfile.write("Log time: "+date_string+"\r\n")
                outputfile.write(output)
        print(wlc_hostname+'\n'+output)
except NetmikoTimeoutException:
    with open('output/'+date2+'_Error_'+wlc_hostname+'.txt', "a") as outputfile:
        outputfile.write('Connection timed out')
except NetmikoAuthenticationException:
    with open('output/'+date2+'_Error_'+wlc_hostname+'.txt', "a") as outputfile:
        outputfile.write('Authentication failed')
```

**Comment by onlywifi** [comment]
I finally have found the solution here https://github.com/ktbyers/netmiko/issues/2058
This was a timeout during save_config() that is solved adding:
```
            net_connect.fast_cli = False
            output += net_connect.save_config()
            net_connect.fast_cli = True
```
