### ISSUE TITLE
Communication with a Cisco 2960-24TT-L fails over serial line

### ISSUE THREAD

**Issue by cap4096** [ktbyers/netmiko#2641]
When running the example code it seams like netmiko has trouble to find the prompt.
If I run the code many times the it fails after a random number of commands are executed but netmiko fails to find the prompt.

pip list:
```
Package       Version
------------- -------
autopep8      1.6.0
bcrypt        3.2.0
cffi          1.15.0
click         8.0.3
cryptography  36.0.1
Flask         2.0.2
future        0.18.2
itsdangerous  2.0.1
Jinja2        3.0.3
MarkupSafe    2.0.1
netmiko       3.4.0
ntc-templates 3.0.0
paramiko      2.9.2
pip           21.2.4
pycodestyle   2.8.0
pycparser     2.21
PyNaCl        1.5.0
pyserial      3.5
scp           0.14.2
setuptools    58.1.0
six           1.16.0
tenacity      8.0.1
textfsm       1.1.2
toml          0.10.2
Werkzeug      2.0.2
```

Example code:
```
import netmiko
import serial

params = {
    'device_type': "cisco_ios_serial",
    'fast_cli': False,
    'serial_settings': {'port': "/dev/ttyUSB0",
                        'baudrate': 9600,
                        'bytesize': serial.EIGHTBITS,
                        'parity': serial.PARITY_NONE,
                        'stopbits': serial.STOPBITS_ONE},
    'session_log': "log.txt",
}

conn = netmiko.ConnectHandler(**params)
print("Login successful!")

conn.send_config_set([
    'hostname csw10',
    'ip default-gateway 192.168.1.1',
    'ip domain-name X.Y.Z',
    'ip name-server 192.168.1.1'
])

conn.disconnect()
```
Exception when running:
```
Login successful!
Traceback (most recent call last):
  File "/home/malo/projects/ios-proxy/test.py", line 18, in <module>
    conn.send_config_set([
  File "/home/malo/projects/ios-proxy/.venv/lib/python3.10/site-packages/netmiko/base_connection.py", line 1876, in send_config_set
    output += self.config_mode(*cfg_mode_args)
  File "/home/malo/projects/ios-proxy/.venv/lib/python3.10/site-packages/netmiko/cisco_base_connection.py", line 48, in config_mode
    return super().config_mode(
  File "/home/malo/projects/ios-proxy/.venv/lib/python3.10/site-packages/netmiko/base_connection.py", line 1756, in config_mode
    if not self.check_config_mode():
  File "/home/malo/projects/ios-proxy/.venv/lib/python3.10/site-packages/netmiko/cisco/cisco_ios.py", line 32, in check_config_mode
    return super().check_config_mode(check_string=check_string, pattern=pattern)
  File "/home/malo/projects/ios-proxy/.venv/lib/python3.10/site-packages/netmiko/cisco_base_connection.py", line 38, in check_config_mode
    return super().check_config_mode(check_string=check_string, pattern=pattern)
  File "/home/malo/projects/ios-proxy/.venv/lib/python3.10/site-packages/netmiko/base_connection.py", line 1740, in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "/home/malo/projects/ios-proxy/.venv/lib/python3.10/site-packages/netmiko/base_connection.py", line 655, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/home/malo/projects/ios-proxy/.venv/lib/python3.10/site-packages/netmiko/base_connection.py", line 595, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, pattern not found in output: #
```
Log output:

```



         --- System Configuration Dialog ---

Enable secret warning
----------------------------------
In order to access the device manager, an enable secret is required
If you enter the initial configuration dialog, you will be prompted for the enable secret
If you choose not to enter the intial configuration dialog, or if you exit setup without setting the enable secret,
please set an enable secret using the following CLI in configuration mode-
enable secret 0 <cleartext password>
----------------------------------
Would you like to enter the initial configuration dialog? [yes/no]:
% Please answer 'yes' or 'no'.
Would you like to enter the initial configuration dialog? [yes/no]:
% Please answer 'yes' or 'no'.
Would you like to enter the initial configuration dialog? [yes/no]: no
Switch>
Switch>
*Mar  1 00:02:11.801: %LINK-5-CHANGED: Interface Vlan1, changed state to administratively down
Switch>
Switch>terminal width 511
Switch>terminal length 0
Switch>
Switch>
Switch>
```

**Comment by cap4096** [comment]
```
2022-02-06 20:48:37,324 [DEBUG] write_channel: b'\r\n'
2022-02-06 20:48:37,325 [DEBUG] read_channel:
2022-02-06 20:48:38,326 [DEBUG] read_channel:


         -
2022-02-06 20:48:38,328 [DEBUG] read_channel: -
2022-02-06 20:48:38,328 [DEBUG] read_channel: -
2022-02-06 20:48:38,329 [DEBUG] read_channel:
2022-02-06 20:48:38,329 [DEBUG] read_channel:
2022-02-06 20:48:38,329 [DEBUG] read_channel:
2022-02-06 20:48:38,330 [DEBUG] write_channel: b'\r\n'
2022-02-06 20:48:38,831 [DEBUG] read_channel:  System Configuration Dialog ---

Enable secret warning
----------------------------------
In order to access the device manager, an enable secret is required
If you enter the initial configuration dialog, you will be prompted for the enable secret
If you choose not to enter the intial configuration dialog, or if you exit setup without setting the enable secret,
please set an enable secret using the following CLI in configurat
2022-02-06 20:48:38,831 [DEBUG] read_channel:
2022-02-06 20:48:38,832 [DEBUG] read_channel: i
2022-02-06 20:48:38,832 [DEBUG] read_channel:
2022-02-06 20:48:38,832 [DEBUG] read_channel:
2022-02-06 20:48:38,832 [DEBUG] read_channel:
2022-02-06 20:48:38,833 [DEBUG] write_channel: b'\r\n'
2022-02-06 20:48:39,334 [DEBUG] read_channel: on mode-
enable secret 0 <cleartext password>
----------------------------------
Would you like to enter the initial configuration dialog? [yes/no]:
% Please answer 'yes' or 'no'.
Would you like to enter the initial configuration dialog? [yes/no]:
% Please answer 'yes' or 'no'.
Would you like to enter the initial configuration dialog? [yes/no]:
% Please answer 'yes' or 'no'.
Would you like to enter the initial configurati
2022-02-06 20:48:39,335 [DEBUG] write_channel: b'\r'
2022-02-06 20:48:39,836 [DEBUG] read_channel: on dialog? [yes/no]:
% Please answer 'yes' or 'no'.
Would you like to enter the initial configuration dialog? [yes/no]:
% Please answer 'yes' or 'no'.
Would you like to enter the initial configuration dialog? [yes/no]:
% Please answer 'yes' or 'no'.
Would you like to enter the initial configuration dialog? [yes/no]:
2022-02-06 20:48:39,837 [DEBUG] write_channel: b'no\r\n'
2022-02-06 20:48:40,338 [DEBUG] read_channel: no
Switch>

2022-02-06 20:48:42,341 [DEBUG] read_channel: Switch>
2022-02-06 20:48:44,344 [DEBUG] read_channel:
*Mar  1 00:04:51.864: %LINK-5-CHANGED: Interface Vlan1, changed state to administratively down
2022-02-06 20:48:46,347 [DEBUG] read_channel:
2022-02-06 20:48:48,349 [DEBUG] read_channel:
2022-02-06 20:48:50,352 [DEBUG] read_channel:
2022-02-06 20:48:52,355 [DEBUG] read_channel:
2022-02-06 20:48:54,357 [DEBUG] read_channel:
2022-02-06 20:48:56,360 [DEBUG] read_channel:
2022-02-06 20:48:58,363 [DEBUG] read_channel:
2022-02-06 20:49:00,365 [DEBUG] read_channel:
2022-02-06 20:49:02,368 [DEBUG] read_channel:
2022-02-06 20:49:04,371 [DEBUG] read_channel:
2022-02-06 20:49:06,373 [DEBUG] read_channel:
2022-02-06 20:49:08,374 [DEBUG] read_channel:
2022-02-06 20:49:10,377 [DEBUG] read_channel:
2022-02-06 20:49:10,378 [DEBUG] read_channel:
2022-02-06 20:49:10,378 [DEBUG] read_channel:
2022-02-06 20:49:10,378 [DEBUG] read_channel:
2022-02-06 20:49:10,378 [DEBUG] read_channel:
2022-02-06 20:49:10,379 [DEBUG] write_channel: b'\r\n'
2022-02-06 20:49:10,880 [DEBUG] write_channel: b'\r\n'
2022-02-06 20:49:11,382 [DEBUG] read_channel:
Switch>
Switch>
Switch>
Switch>
2022-02-06 20:49:11,383 [DEBUG] write_channel: b'terminal width 511\n'
2022-02-06 20:49:11,383 [DEBUG] Pattern is: terminal width 511
2022-02-06 20:49:11,383 [DEBUG] read_channel:
2022-02-06 20:49:11,484 [DEBUG] read_channel: terminal width 511
Switch>
2022-02-06 20:49:11,484 [DEBUG] Pattern found: terminal width 511 terminal width 511
Switch>
2022-02-06 20:49:11,485 [DEBUG] In disable_paging
2022-02-06 20:49:11,485 [DEBUG] Command: terminal length 0

2022-02-06 20:49:11,486 [DEBUG] write_channel: b'terminal length 0\n'
2022-02-06 20:49:11,486 [DEBUG] Pattern is: terminal\ length\ 0
2022-02-06 20:49:11,486 [DEBUG] read_channel:
2022-02-06 20:49:11,587 [DEBUG] read_channel: terminal length 0
Switch>
2022-02-06 20:49:11,588 [DEBUG] Pattern found: terminal\ length\ 0 terminal length 0
Switch>
2022-02-06 20:49:11,588 [DEBUG] terminal length 0
Switch>
2022-02-06 20:49:11,588 [DEBUG] Exiting disable_paging
2022-02-06 20:49:11,689 [DEBUG] read_channel:
2022-02-06 20:49:11,690 [DEBUG] write_channel: b'\n'
2022-02-06 20:49:11,791 [DEBUG] read_channel:
Switch>
2022-02-06 20:49:11,992 [DEBUG] read_channel:
2022-02-06 20:49:11,993 [DEBUG] [find_prompt()]: prompt is Switch>
2022-02-06 20:49:11,994 [DEBUG] write_channel: b'\n'
2022-02-06 20:49:11,994 [DEBUG] Pattern is: #
2022-02-06 20:49:11,994 [DEBUG] read_channel:
2022-02-06 20:49:12,095 [DEBUG] read_channel:
Switch>
2022-02-06 20:49:12,196 [DEBUG] read_channel:
2022-02-06 20:49:12,297 [DEBUG] read_channel:
2022-02-06 20:49:12,398 [DEBUG] read_channel:
2022-02-06 20:49:12,498 [DEBUG] read_channel:
2022-02-06 20:49:12,599 [DEBUG] read_channel:
2022-02-06 20:49:12,700 [DEBUG] read_channel:
2022-02-06 20:49:12,801 [DEBUG] read_channel:
.
.
.

Traceback (most recent call last):
  File "/home/malo/projects/ios-proxy/test.py", line 29, in <module>
    conn.send_config_set([
  File "/home/malo/projects/ios-proxy/.venv/lib/python3.10/site-packages/netmiko/base_connection.py", line 1876, in send_config_set
    output += self.config_mode(*cfg_mode_args)
  File "/home/malo/projects/ios-proxy/.venv/lib/python3.10/site-packages/netmiko/cisco_base_connection.py", line 48, in config_mode
    return super().config_mode(
  File "/home/malo/projects/ios-proxy/.venv/lib/python3.10/site-packages/netmiko/base_connection.py", line 1756, in config_mode
    if not self.check_config_mode():
  File "/home/malo/projects/ios-proxy/.venv/lib/python3.10/site-packages/netmiko/cisco/cisco_ios.py", line 32, in check_config_mode
    return super().check_config_mode(check_string=check_string, pattern=pattern)
  File "/home/malo/projects/ios-proxy/.venv/lib/python3.10/site-packages/netmiko/cisco_base_connection.py", line 38, in check_config_mode
    return super().check_config_mode(check_string=check_string, pattern=pattern)
  File "/home/malo/projects/ios-proxy/.venv/lib/python3.10/site-packages/netmiko/base_connection.py", line 1740, in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "/home/malo/projects/ios-proxy/.venv/lib/python3.10/site-packages/netmiko/base_connection.py", line 655, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/home/malo/projects/ios-proxy/.venv/lib/python3.10/site-packages/netmiko/base_connection.py", line 595, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, pattern not found in output: #
```

**Comment by cap4096** [comment]
After adding more debug statements i found the following:

```
2022-02-06 22:00:56,018 [DEBUG] read_channel: configure terminal
Enter configuration commands, one per line.  End with CNTL/Z.
csw1
2022-02-06 22:00:56,018 [DEBUG] pattern: configure\ terminal output: configure terminal
Enter configuration commands, one per line.  End with CNTL/Z.
csw1
2022-02-06 22:00:56,018 [DEBUG] Pattern found: configure\ terminal configure terminal
Enter configuration commands, one per line.  End with CNTL/Z.
csw1
2022-02-06 22:00:56,019 [DEBUG] Pattern is: csw10
2022-02-06 22:00:56,019 [DEBUG] read_channel: 0
2022-02-06 22:00:56,019 [DEBUG] pattern: csw10 output: 0
2022-02-06 22:00:56,120 [DEBUG] read_channel: (config)#
2022-02-06 22:00:56,121 [DEBUG] pattern: csw10 output: 0(config)#
2022-02-06 22:00:56,221 [DEBUG] read_channel:
2022-02-06 22:00:56,222 [DEBUG] pattern: csw10 output: 0(config)#
2022-02-06 22:00:56,322 [DEBUG] read_channel:
2022-02-06 22:00:56,323 [DEBUG] pattern: csw10 output: 0(config)#
2022-02-06 22:00:56,423 [DEBUG] read_channel:
2022-02-06 22:00:56,423 [DEBUG] pattern: csw10 output: 0(config)#
2022-02-06 22:00:56,524 [DEBUG] read_channel:
```

It looks to that the verifying of the typed command "configure terminal" is eating up parts of the prompt and making it unrecognizable.

**Comment by cap4096** [comment]
For 3.4.0 this seams to fix the problem:

```
diff --git a/netmiko/base_connection.py b/netmiko/base_connection.py
index 161bcd25..14e1aa27 100644
--- a/netmiko/base_connection.py
+++ b/netmiko/base_connection.py
@@ -1760,6 +1760,7 @@ Device settings: {self.device_type} {self.host}:{self.port}
                 output += self.read_until_pattern(
                     pattern=re.escape(config_command.strip())
                 )
+                self.write_channel('\r\n')
             if not re.search(pattern, output, flags=re_flags):
                 output += self.read_until_pattern(pattern=pattern, re_flags=re_flags)
             if not self.check_config_mode():
```

**Comment by ktbyers** [comment]
Can you show the failing Netmiko log with your last set of Python code (no changes). I.E. I want to see the full log capture when it fails with this last code.

Thanks.

**Comment by cap4096** [comment]
[debug.log](https://github.com/ktbyers/netmiko/files/8017482/debug.log)

**Comment by ktbyers** [comment]
Can you test this with the Netmiko `develop` branch? I think this issue might be fixed there.

Let me know if you still are seeing this issue when you use that (or not).
