### ISSUE TITLE
HP Procurve - Authentication Failure (TELNET)

### ISSUE THREAD

**Issue by FoxMasterTheOne** [ktbyers/netmiko#2676]
Hello to All.

We have HP Procurves from models J9087A and J9089A that we are facing connection issues with Netmiko 3.4.0 (Windows and Linux).

Using the device_type='hp_procurve_telnet', the username and the password are not being sent.

Using the device_type='hp_comware_telnet', the username and the password are being sent, we could see the hostname and the prompt, but the connection is not established.

I attached the files with the each LOG evidence.

Thanks a lot for the help

[Procurve-Evidence_LOG_1647009679.txt](https://github.com/ktbyers/netmiko/files/8233301/Procurve-Evidence_LOG_1647009679.txt)
[Comware-Evidence_LOG_1646944989.txt](https://github.com/ktbyers/netmiko/files/8233299/Comware-Evidence_LOG_1646944989.txt)
.

**Comment by ktbyers** [comment]
@FoxMasterTheOne Can you test this code here and see if it helps (or not)?

https://github.com/ktbyers/netmiko/pull/2677

**Comment by FoxMasterTheOne** [comment]
Hello @ktbyers , how are you?

I updated the code as you requested, but it didn't work.

Take a look on the new LOG evidence. ([Procurve-Evidence_1647187424.txt](https://github.com/ktbyers/netmiko/files/8240078/Procurve-Evidence_1647187424.txt))

On the write_channel: b'\r\n' string, there is no credentials being sent (no "username" and no "password").

If you take a look com the Comware-Evidence_LOG file that I shared before, you will see that the credentials are being sent.

Thanks a lot for the help.

**Comment by ktbyers** [comment]
@FoxMasterTheOne Yes, the question is why though...Netmiko should see the Username pattern and send the username (in the telnet_login method).

Can you send over the exception stack trace and post the relevant section of your code.

**Comment by ktbyers** [comment]
Get rid of your try/except in your "func_PING (code) and then send over the full exception stack trace when it fails.

In other words, the try/except statement is hiding details about the failure (which will be helpful to see).

Which version of Netmiko are you using?

**Comment by FoxMasterTheOne** [comment]
Hello @ktbyers , how are you?

I am working with Netmiko 3.4.0 (Windows and Linux).

This is the code updated as your suggestion:
[Telnet-Procurve-Access_Netmiko_Simple.txt](https://github.com/ktbyers/netmiko/files/8253502/Telnet-Procurve-Access_Netmiko_Simple.txt)

This is the exception stack trace:

C:/Network-Code/python Telnet-Procurve-Access_Netmiko_Simple.py
Traceback (most recent call last):
  File "c:/Network-Code/Telnet-Procurve-Access_Netmiko_Simple.py", line 52, in <module>
    obj_Connection = ConnectHandler(device_type='hp_procurve_telnet', ip=str_Host, username=str_User, password=str_Password, global_delay_factor=4)
  File "C:\Users\rja1521\AppData\Roaming\Python\Python38\site-packages\netmiko\ssh_dispatcher.py", line 326, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\rja1521\AppData\Roaming\Python\Python38\site-packages\netmiko\base_connection.py", line 350, in __init__
    self._open()
  File "C:\Users\rja1521\AppData\Roaming\Python\Python38\site-packages\netmiko\base_connection.py", line 355, in _open
    self.establish_connection()
  File "C:\Users\rja1521\AppData\Roaming\Python\Python38\site-packages\netmiko\base_connection.py", line 925, in establish_connection
    self.telnet_login()
  File "C:\Users\rja1521\AppData\Roaming\Python\Python38\site-packages\netmiko\hp\hp_procurve.py", line 182, in telnet_login
    super().telnet_login(
  File "C:\Users\rja1521\AppData\Roaming\Python\Python38\site-packages\netmiko\cisco_base_connection.py", line 185, in telnet_login
    raise NetmikoAuthenticationException(msg)
netmiko.ssh_exception.NetmikoAuthenticationException: Login failed: 192.168.0.35

Thanks a lot for the help.

**Comment by ktbyers** [comment]
Can you try adding a print statement here:

https://github.com/ktbyers/netmiko/blob/v3.4.0/netmiko/cisco_base_connection.py#L108

So something like:

```python
                    output = self.read_channel()
                    print("-" * 80)
                    print(output)
                    print("-" * 80)
                    return_msg += output
```

**Comment by FoxMasterTheOne** [comment]
Hello @ktbyers , how are you?

As you requested, I added the print statement and the result was this:
[Procurve-Evidence_01.txt](https://github.com/ktbyers/netmiko/files/8256184/Procurve-Evidence_01.txt)

Thanks a lot for the help.

**Comment by ktbyers** [comment]
@FoxMasterTheOne Are you still including this?

https://github.com/ktbyers/netmiko/pull/2677

**Comment by FoxMasterTheOne** [comment]
Hello @ktbyers , how are you?

I found the issue!!!

Comparing the file netmiko/hp/hp_procurve.py (#2677) with the one that I have in my system, I realized that the line 177 on my system was different from yours.

I updated the line and the connection was successful.

Thanks a lot for your patience...

Thanks a lot for the help.

**Comment by ktbyers** [comment]
What did you have on line 177?

Was this a manual edit you had made or a different/older version of Netmiko?


Regards, Kirk
