### ISSUE TITLE
check_config_mode failure on IOSv

### ISSUE THREAD

**Issue by ifunanyajohnson** [ktbyers/netmiko#2683]
My Script:

from netmiko import ConnectHandler

ios_l2 = {'device_type': 'cisco_ios', 'ip': '192.168.122.72', 'username': 'xxxxxxx', 'password': 'yyyyyyyy',}

net_connect = ConnectHandler(**ios_l2)
output = net_connect.send_command('show ip int brief')
print (output)

config_commands = ['int loop 0', 'ip address 1.1.1.1 255.255.255.0']
output = net_connect.send_config_set(config_commands)
print (output)

for n in range (2,21):
    print ("Creating VLAN " + str(n))
    config_commands = ['vlan ' + str(n), 'name Python_VLAN ' + str(n)]
    output = net_connect.send_config_set(config_commands)

I am a beginner in using python to automate network. I ran the above script and then got the error message pasted below.
My goal was to SSH into a cisco switch, create a loopback interface and create vlans inside the switch but script fails after displaying the output of "show ip int brief"

root@NetworkAutomation-1:~# python3 netmiko1.py

Interface              IP-Address      OK? Method Status                Protocol
GigabitEthernet0/0     unassigned      YES unset  up                    up
GigabitEthernet0/1     unassigned      YES unset  up                    up
GigabitEthernet0/2     unassigned      YES unset  down                  down
GigabitEthernet0/3     unassigned      YES unset  down                  down
GigabitEthernet1/0     unassigned      YES unset  down                  down
GigabitEthernet1/1     unassigned      YES unset  down                  down
GigabitEthernet1/2     unassigned      YES unset  down                  down
GigabitEthernet1/3     unassigned      YES unset  down                  down
GigabitEthernet2/0     unassigned      YES unset  down                  down
GigabitEthernet2/1     unassigned      YES unset  down                  down
GigabitEthernet2/2     unassigned      YES unset  down                  down
GigabitEthernet2/3     unassigned      YES unset  down                  down
GigabitEthernet3/0     unassigned      YES unset  down                  down
GigabitEthernet3/1     unassigned      YES unset  down                  down
GigabitEthernet3/2     unassigned      YES unset  down                  down
GigabitEthernet3/3     unassigned      YES unset  down                  down
Vlan1                  192.168.122.72  YES manual up                    up
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.8/dist-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 573, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.8/dist-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "netmiko1.py", line 10, in <module>
    output = net_connect.send_config_set(config_commands, cmd_verify=False)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 1876, in send_config_set
    output += self.config_mode(*cfg_mode_args)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/cisco_base_connection.py", line 48, in config_mode
    return super().config_mode(
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 1756, in config_mode
    if not self.check_config_mode():
  File "/usr/local/lib/python3.8/dist-packages/netmiko/cisco/cisco_ios.py", line 32, in check_config_mode
    return super().check_config_mode(check_string=check_string, pattern=pattern)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/cisco_base_connection.py", line 38, in check_config_mode
    return super().check_config_mode(check_string=check_string, pattern=pattern)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 1740, in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 655, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 583, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

**Comment by ktbyers** [comment]
@ifunanyajohnson Have you tried generating all your configuration commands in a single list and then doing a single `send_config_set()` call?

For some reason it failed on a `check_config_mode` call above (hard to tell why though).

You might want to test it against the Netmiko `develop` branch and see if it still fails using that.

**Comment by ifunanyajohnson** [comment]
I received the same error message still.

**My Script:**

from netmiko import ConnectHandler

ios_l2 = {'device_type': 'cisco_ios', 'ip': '192.168.122.72',
 'username': 'xxxxxx', 'password': 'yyyyyyyy',}
with open('testingFile') as f:
    lines = f.read().splitlines()
print(lines)
net_connect = ConnectHandler(**ios_l2)
output = net_connect.send_config_set(lines)
print (output)


**The Error Message**
root@NetworkAutomation-1:~# python3 netmiko2.py
['vlan 100', ' name data', 'vlan101', ' name voice', 'vlan 102', ' name test']
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.8/dist-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 573, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.8/dist-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "netmiko2.py", line 9, in <module>
    output = net_connect.send_config_set(lines)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 1876, in send_config_set
    output += self.config_mode(*cfg_mode_args)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/cisco_base_connection.py", line 48, in config_mode
    return super().config_mode(
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 1756, in config_mode
    if not self.check_config_mode():
  File "/usr/local/lib/python3.8/dist-packages/netmiko/cisco/cisco_ios.py", line 32, in check_config_mode
    return super().check_config_mode(check_string=check_string, pattern=pattern)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/cisco_base_connection.py", line 38, in check_config_mode
    return super().check_config_mode(check_string=check_string, pattern=pattern)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 1740, in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 655, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 583, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

**Comment by ifunanyajohnson** [comment]
Could it be that the cisco ios version of my devices does not support python script because i could actually ssh manually into the cisco devices?
root@NetworkAutomation-1:~# ssh ifunanya@192.168.122.72

**************************************************************************
* IOSv is strictly limited to use for evaluation, demonstration and IOS  *
* education. IOSv is provided as-is and is not supported by Cisco's      *
* Technical Advisory Center. Any use or disclosure, in whole or in part, *
* of the IOSv Software or Documentation to any third party for any       *
* purposes is expressly prohibited except as otherwise authorized by     *
* Cisco in writing.                                                      *
Password: ****************************************************************

**************************************************************************
* IOSv is strictly limited to use for evaluation, demonstration and IOS  *
* education. IOSv is provided as-is and is not supported by Cisco's      *
* Technical Advisory Center. Any use or disclosure, in whole or in part, *
* of the IOSv Software or Documentation to any third party for any       *
* purposes is expressly prohibited except as otherwise authorized by     *
* Cisco in writing.                                                      *
**************************************************************************
Switch>en
Password:
% Password:  timeout expired!
Password:
Switch#
Switch#exit
Connection to 192.168.122.72 closed.
root@NetworkAutomation-1:~# nano netmiko2.py

**Comment by ktbyers** [comment]
I am going to close as no response to last request. You can just re-open this issue if you still want to work on it.

**Comment by safouat** [comment]
I had the same problem, but I resolved it by configuring the following line: "username XXXX privilege 15 password YYYY."
