### ISSUE TITLE
Nexus -  Incompatible ssh server (no acceptable ciphers)

### ISSUE THREAD

**Issue by websantos** [ktbyers/netmiko#2687]
Hi all,

I have issue  connecting to my Nexus devices.

My script:
---------------------------------------------------------------------------------------------------------------------------------------------------
from netmiko import ConnectHandler
import paramiko

nexus = {"device_type": "cisco_nxos", "host": "10.1.1.1", "port": "22", "username": user, "password": password,}

connection = ConnectHandler(**nexus)
output = connection.send_command('show version')
print(output)

print('Closing connection')
connection.disconnect()
---------------------------------------------------------------------------------------------------------------------------------------------------

When run my script:
---------------------------------------------------------------------------------------------------------------------------------------------------
python3 debug_devices.py 
Traceback (most recent call last):
  File "debug_devices.py", line 20, in <module>
    connection = ConnectHandler(**n1)
  File "/usr/lib/perl5/site-packages/python/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 326, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/lib/perl5/site-packages/python/lib/python3.6/site-packages/netmiko/cisco/cisco_nxos_ssh.py", line 12, in __init__
    return super().__init__(*args, **kwargs)
  File "/usr/lib/perl5/site-packages/python/lib/python3.6/site-packages/netmiko/base_connection.py", line 350, in __init__
    self._open()
  File "/usr/lib/perl5/site-packages/python/lib/python3.6/site-packages/netmiko/base_connection.py", line 355, in _open
    self.establish_connection()
  File "/usr/lib/perl5/site-packages/python/lib/python3.6/site-packages/netmiko/base_connection.py", line 935, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/lib/perl5/site-packages/python/lib/python3.6/site-packages/paramiko/client.py", line 406, in connect
    t.start_client(timeout=timeout)
  File "/usr/lib/perl5/site-packages/python/lib/python3.6/site-packages/paramiko/transport.py", line 698, in start_client
    raise e
  File "/usr/lib/perl5/site-packages/python/lib/python3.6/site-packages/paramiko/transport.py", line 2137, in run
    self._handler_table[ptype](self, m)
  File "/usr/lib/perl5/site-packages/python/lib/python3.6/site-packages/paramiko/transport.py", line 2257, in _negotiate_keys
    self._parse_kex_init(m)
  File "/usr/lib/perl5/site-packages/python/lib/python3.6/site-packages/paramiko/transport.py", line 2511, in _parse_kex_init
    "Incompatible ssh server (no acceptable ciphers)"
paramiko.ssh_exception.IncompatiblePeer: Incompatible ssh server (no acceptable ciphers)
---------------------------------------------------------------------------------------------------------------------------------------------------

DEBUG:
---------------------------------------------------------------------------------------------------------------------------------------------------
DEBUG:paramiko.transport:starting thread (client mode): 0xa23ce2b0
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.9.2
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-OpenSSH_7.2 FIPS
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_7.2)
DEBUG:paramiko.transport:=== Key exchange possibilities ===
DEBUG:paramiko.transport:kex algos: diffie-hellman-group14-sha1, ecdh-sha2-nistp256, ecdh-sha2-nistp384
DEBUG:paramiko.transport:server key: ssh-rsa
DEBUG:paramiko.transport:client encrypt: aes256-gcm@openssh.com
DEBUG:paramiko.transport:server encrypt: aes256-gcm@openssh.com
DEBUG:paramiko.transport:client mac: hmac-sha1
DEBUG:paramiko.transport:server mac: hmac-sha1
DEBUG:paramiko.transport:client compress: none, zlib@openssh.com
DEBUG:paramiko.transport:server compress: none, zlib@openssh.com
DEBUG:paramiko.transport:client lang: <none>
DEBUG:paramiko.transport:server lang: <none>
DEBUG:paramiko.transport:kex follows: False
DEBUG:paramiko.transport:=== Key exchange agreements ===
DEBUG:paramiko.transport:Kex: diffie-hellman-group14-sha1
DEBUG:paramiko.transport:HostKey: ssh-rsa
ERROR:paramiko.transport:Exception (client): Incompatible ssh server (no acceptable ciphers)
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/usr/lib/perl5/site-packages/python/lib/python3.6/site-packages/paramiko/transport.py", line 2137, in run
ERROR:paramiko.transport:    self._handler_table[ptype](self, m)
ERROR:paramiko.transport:  File "/usr/lib/perl5/site-packages/python/lib/python3.6/site-packages/paramiko/transport.py", line 2257, in _negotiate_keys
ERROR:paramiko.transport:    self._parse_kex_init(m)
ERROR:paramiko.transport:  File "/usr/lib/perl5/site-packages/python/lib/python3.6/site-packages/paramiko/transport.py", line 2511, in _parse_kex_init
ERROR:paramiko.transport:    "Incompatible ssh server (no acceptable ciphers)"
ERROR:paramiko.transport:paramiko.ssh_exception.IncompatiblePeer: Incompatible ssh server (no acceptable ciphers)
ERROR:paramiko.transport:
---------------------------------------------------------------------------------------------------------------------------------------------------

On Nexus device have this ciphers:
ssh ciphers aes256-gcm 

 I tried to change the Transport cipher:
paramiko.Transport._preferred_ciphers = ('aes256-gcm@openssh.com', 'aes256-gcm')

but doenst solve the isue:
---------------------------------------------------------------------------------------------------------------------------------------------------
 python3 debug_devices.py 
Traceback (most recent call last):
  File "debug_devices.py", line 21, in <module>
    connection = ConnectHandler(**n1)
  File "/usr/lib/perl5/site-packages/python/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 326, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/lib/perl5/site-packages/python/lib/python3.6/site-packages/netmiko/cisco/cisco_nxos_ssh.py", line 12, in __init__
    return super().__init__(*args, **kwargs)
  File "/usr/lib/perl5/site-packages/python/lib/python3.6/site-packages/netmiko/base_connection.py", line 350, in __init__
    self._open()
  File "/usr/lib/perl5/site-packages/python/lib/python3.6/site-packages/netmiko/base_connection.py", line 355, in _open
    self.establish_connection()
  File "/usr/lib/perl5/site-packages/python/lib/python3.6/site-packages/netmiko/base_connection.py", line 935, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/lib/perl5/site-packages/python/lib/python3.6/site-packages/paramiko/client.py", line 406, in connect
    t.start_client(timeout=timeout)
  File "/usr/lib/perl5/site-packages/python/lib/python3.6/site-packages/paramiko/transport.py", line 698, in start_client
    raise e
  File "/usr/lib/perl5/site-packages/python/lib/python3.6/site-packages/paramiko/transport.py", line 2129, in run
    self.kex_engine.parse_next(ptype, m)
  File "/usr/lib/perl5/site-packages/python/lib/python3.6/site-packages/paramiko/kex_ecdh_nist.py", line 53, in parse_next
    return self._parse_kexecdh_reply(m)
  File "/usr/lib/perl5/site-packages/python/lib/python3.6/site-packages/paramiko/kex_ecdh_nist.py", line 139, in _parse_kexecdh_reply
    self.transport._activate_outbound()
  File "/usr/lib/perl5/site-packages/python/lib/python3.6/site-packages/paramiko/transport.py", line 2640, in _activate_outbound
    block_size = self._cipher_info[self.local_cipher]["block-size"]
KeyError: 'aes256-gcm@openssh.com'
---------------------------------------------------------------------------------------------------------------------------------------------------

but I cannot solve this error...

I just have this issue with Nexus

Do you know how to solve this? Any suggestions?

**Comment by ktbyers** [comment]
Can you try downgrading to Paramiko==2.8.1 and see if that fixes the issue?

**Comment by websantos** [comment]
I'm running this script on a JumpServer and unfortunately I don't have admin rights to downgrading Paramiko.
I could test it on my private GNS3 lab, but I don't have any Nexus Image to GNS3.

**Comment by websantos** [comment]
Also from the JumpServer I can ssh the Nexus without any issue

**Comment by AuthenticAMD** [comment]
@websantos What platform of nexus and version are you running?

**Comment by websantos** [comment]
Nexus 3500 c3548p-10gx version 7.0.3i7.8

**Comment by ktbyers** [comment]
@websantos Can you expand on what you mean:

`I'm running this script on a JumpServer and unfortunately I don't have admin rights`

So your script is running on the JumpServer (i.e. you are not bouncing through the JumpServer, but running there directly)?

Is there some reason, you can't create a Python virtual environment and install the libraries you need.

Alternatively, is there some reason, you can't run your script remotely and bounce through the JumpServer (using SSH Proxy) and once again install what you like.

If none of that works, you can try `disabled_algorithms` setting in Netmiko, but you will need the Netmiko `develop` branch (which also will need to be installed).

**Comment by websantos** [comment]
I cannot downgrading to Paramiko=2.8.1, because I'm not the administrator.

I send my scripts to the jump JumpServer, after I ssh the JumpServer and I run the scripts.
It works to all devices except to the Nexus.

> Is there some reason, you can't create a Python virtual environment and install the libraries you need.
How can I do it?

**Comment by ktbyers** [comment]
You don't need admin privileges to setup a virtual environment. Any user on the system can setup a virtual environment.

The other solution is as per above, but it also will require a virtual environment and ability to install the fix (i.e. the Netmiko `develop` branch).

**Comment by AuthenticAMD** [comment]
I can confirm I see the issue when "ssh ciphers aes256-gcm" is enabled on the switch when running netmiko 4.0.0a4, paramiko 2.9.2, and paramiko 2.7.2.

I tested against a Nexus 9332 running nxos 9.3.9. I suspect this is a paramiko issue in some way.

Do you really need to have "ssh ciphers aes256-gcm" enabled?

**Comment by AuthenticAMD** [comment]
https://github.com/paramiko/paramiko/issues

**Comment by websantos** [comment]
Do you know other way to ssh these devices with cipher aes256-gcm using python?

**Comment by ktbyers** [comment]
Scrapli might be able to solve this since it can use openssh directly on the system. So that might be one alternative for this particular issue.
