### ISSUE TITLE
Netmiko linux device_type exit_config_mode behavior

### ISSUE THREAD

**Issue by govindrathod1987** [ktbyers/netmiko#2694]
netmiko.ssh_exception.NetMikoTimeoutException seen while trying to execute send_config_set

netmiko version for windows: 2.30

code: 

```python
    output = net_connect.send_command_timing(cmd0, delay_factor=5)
    time.sleep(2)
    prompt = net_connect.find_prompt(delay_factor=5)
    print prompt
    output = net_connect.enable() 
```

**Output trace:**
SSH connection established to 172.17.17.66:22
Interactive SSH session established
#
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/NFC1.1/extras/Docker_container_tests_neto.py", line 9025, in <module>
    main()
  File "C:/Users/Administrator/PycharmProjects/NFC1.1/extras/Docker_container_tests_neto.py", line 9021, in main
    container_tests(dockers_json, test_type, report)
  File "C:/Users/Administrator/PycharmProjects/NFC1.1/extras/Docker_container_tests_neto.py", line 8696, in container_tests
    create_DD_NNS(dockers_json, report)
  File "C:/Users/Administrator/PycharmProjects/NFC1.1/extras/Docker_container_tests_neto.py", line 6170, in create_DD_NNS
    if create_dd_dockers(dockers_json, final, report):
  File "C:/Users/Administrator/PycharmProjects/NFC1.1/extras/Docker_container_tests_neto.py", line 4393, in create_dd_dockers
    if create_dd(vlan, vlan_host_members, vlan_tgt_members, dockers_json, total_portals, report):
  File "C:/Users/Administrator/PycharmProjects/NFC1.1/extras/Docker_container_tests_neto.py", line 2382, in create_dd
    output = net_connect.enable()
  File "C:\Python27\lib\site-packages\netmiko\linux\linux_ssh.py", line 78, in enable
    if not self.check_enable_mode():
  File "C:\Python27\lib\site-packages\netmiko\linux\linux_ssh.py", line 60, in check_enable_mode
    return super(LinuxSSH, self).check_enable_mode(check_string=check_string)
  File "C:\Python27\lib\site-packages\netmiko\cisco_base_connection.py", line 14, in check_enable_mode
    return super(CiscoBaseConnection, self).check_enable_mode(check_string=check_string)
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 1272, in check_enable_mode
    output = self.read_until_prompt()
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 538, in read_until_prompt
    return self._read_channel_expect(*args, **kwargs)
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 478, in _read_channel_expect
    raise NetMikoTimeoutException("Timed-out reading channel, data not available.")
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.

**Comment by ktbyers** [comment]
@govindrathod1987 Netmiko 2.30 is very old. You probably would need to see if you can reproduce this behavior on Netmiko 3.4.0.

Regards, Kirk

**Comment by govindrathod1987** [comment]
@ktbyers I updated my environment to python3.x and Netmiko 3.4.0 and i still see the issue.


#
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko-2.10.3-py3.10.egg\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko-2.10.3-py3.10.egg\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko-3.4.0-py3.10.egg\netmiko\base_connection.py", line 573, in _read_channel_expect
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko-2.10.3-py3.10.egg\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\NFC1.1_python3\extras\Docker_container_tests_neto.py", line 9069, in <module>
    main()
  File "C:\Users\Administrator\PycharmProjects\NFC1.1_python3\extras\Docker_container_tests_neto.py", line 9065, in main
    container_tests(dockers_json, test_type, report)
  File "C:\Users\Administrator\PycharmProjects\NFC1.1_python3\extras\Docker_container_tests_neto.py", line 8740, in container_tests
    create_DD_NNS(dockers_json, report)
  File "C:\Users\Administrator\PycharmProjects\NFC1.1_python3\extras\Docker_container_tests_neto.py", line 6211, in create_DD_NNS
    if create_dd_dockers(dockers_json, final, report):
  File "C:\Users\Administrator\PycharmProjects\NFC1.1_python3\extras\Docker_container_tests_neto.py", line 4380, in create_dd_dockers
    if create_dd(vlan, vlan_host_members, vlan_tgt_members, dockers_json, total_portals, report):
  File "C:\Users\Administrator\PycharmProjects\NFC1.1_python3\extras\Docker_container_tests_neto.py", line 2382, in create_dd
    output = net_connect.enable()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko-3.4.0-py3.10.egg\netmiko\linux\linux_ssh.py", line 85, in enable
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko-3.4.0-py3.10.egg\netmiko\linux\linux_ssh.py", line 67, in check_enable_mode
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko-3.4.0-py3.10.egg\netmiko\cisco_base_connection.py", line 14, in check_enable_mode
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko-3.4.0-py3.10.egg\netmiko\base_connection.py", line 1655, in check_enable_mode
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko-3.4.0-py3.10.egg\netmiko\base_connection.py", line 651, in read_until_prompt
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko-3.4.0-py3.10.egg\netmiko\base_connection.py", line 583, in _read_channel_expect
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

Process finished with exit code 1

**Comment by ktbyers** [comment]
Netmiko 4.0.0 has been released. Can you test with that.

Also you probably need to show the Netmiko session_log. You can enable this by adding:

```
session_log: "output.txt"
```

To your device dictionary that you feed into ConnectHandler.

**Comment by govindrathod1987** [comment]
Hi @ktbyers i still see the issue even after updating to Netmiko 4.0.0
below is the session log  contents and console output:

**Netmiko session log** 
Welcome to Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-100-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Mon 28 Mar 2022 05:05:44 AM UTC

  System load:     0.04               IPv4 address for docker0: 172.18.0.1
  Usage of /:      61.6% of 32.35GB   IPv4 address for ens160:  172.17.17.66
  Memory usage:    9%                 IPv4 address for ens161:  100.100.5.254
  Swap usage:      0%                 IPv4 address for ens192:  100.100.2.254
  Processes:       326                IPv4 address for ens224:  100.100.3.254
  Users logged in: 1                  IPv4 address for ens256:  100.100.4.254


57 updates can be applied immediately.
To see these additional updates run: apt list --upgradable


The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Failed to connect to https://changelogs.ubuntu.com/meta-release-lts. Check your Internet connection or proxy settings


Last login: Mon Mar 28 05:05:42 2022 from 172.17.17.240
sfm_admin@ubuntuonprem:~$ 
sfm_admin@ubuntuonprem:~$ docker exec -ti hpe_nfc /bin/sh
# 
# 
# 

**Python script output:**

 File "C:\Users\Administrator\PycharmProjects\NFC1.1_python3\extras\Docker_container_tests_neto.py", line 2383, in create_dd
    output = net_connect.enable()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko-4.0.0-py3.10.egg\netmiko\linux\linux_ssh.py", line 112, in enable
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko-4.0.0-py3.10.egg\netmiko\linux\linux_ssh.py", line 85, in check_enable_mode
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko-4.0.0-py3.10.egg\netmiko\cisco_base_connection.py", line 15, in check_enable_mode
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko-4.0.0-py3.10.egg\netmiko\base_connection.py", line 1863, in check_enable_mode
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko-4.0.0-py3.10.egg\netmiko\base_connection.py", line 734, in read_until_prompt
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko-4.0.0-py3.10.egg\netmiko\base_connection.py", line 651, in read_until_pattern
netmiko.exceptions.ReadTimeout: 

Pattern not detected: 'sfm_admin@ubuntuonprem:\\~.*' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.

**Comment by govindrathod1987** [comment]
@ktbyers Any updates on this issue ?

**Comment by ktbyers** [comment]
@govindrathod1987 Can. you post the relevant Python code? 

Also have you looked at the session_log or the debug log as indicated by the above error message?

**Comment by govindrathod1987** [comment]
@ktbyers here is the sample code and output:

code: 
 linux = {
        'device_type': 'linux',
        'ip': '172.17.17.66',
        'username': 'admin',
        'password': 'admin123',
        'port': 22,
        'verbose': True
    }

net_connect = ConnectHandler(**linux)
time.sleep(2)
output = net_connect.enable()
print("test1")
print(cmd)
output = net_connect.send_config_set(cmd, delay_factor=10)

**output:**

SSH connection established to 172.17.17.66:22
Interactive SSH session established
sfm_admin@ubuntuonprem:~$
2022-04-05_10:52:32 : The NNS server with IP 172.17.17.66 entered by user in dockers_json file is primary NNS server
Creating max 1.0 DD for VLAN vlan-2
SSH connection established to 172.17.17.66:22
Interactive SSH session established
test1
['docker exec -ti hpe_nfc /bin/sh', 'cd /opt/hpe/nns/NVME-OF-Server/nns-cli;./nnsadm -a 100.100.2.254 -r dd -n DD1_vlan-2']
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\NFC1.1_python3\extras\Docker_container_tests_neto.py", line 9078, in <module>
    main()
  File "C:\Users\Administrator\PycharmProjects\NFC1.1_python3\extras\Docker_container_tests_neto.py", line 9074, in main
    container_tests(dockers_json, test_type, report)
  File "C:\Users\Administrator\PycharmProjects\NFC1.1_python3\extras\Docker_container_tests_neto.py", line 8749, in container_tests
    create_DD_NNS(dockers_json, report)
  File "C:\Users\Administrator\PycharmProjects\NFC1.1_python3\extras\Docker_container_tests_neto.py", line 6220, in create_DD_NNS
    if create_dd_dockers(dockers_json, final, report):
  File "C:\Users\Administrator\PycharmProjects\NFC1.1_python3\extras\Docker_container_tests_neto.py", line 4388, in create_dd_dockers
    if create_dd(vlan, vlan_host_members, vlan_tgt_members, dockers_json, total_portals, report):
  File "C:\Users\Administrator\PycharmProjects\NFC1.1_python3\extras\Docker_container_tests_neto.py", line 2398, in create_dd
    output = net_connect.send_config_set(cmd, delay_factor=10)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko-4.0.0-py3.10.egg\netmiko\linux\linux_ssh.py", line 61, in send_config_set
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko-4.0.0-py3.10.egg\netmiko\base_connection.py", line 2179, in send_config_set
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko-4.0.0-py3.10.egg\netmiko\linux\linux_ssh.py", line 81, in exit_config_mode
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko-4.0.0-py3.10.egg\netmiko\linux\linux_ssh.py", line 94, in exit_enable_mode
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko-4.0.0-py3.10.egg\netmiko\linux\linux_ssh.py", line 85, in check_enable_mode
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko-4.0.0-py3.10.egg\netmiko\cisco_base_connection.py", line 15, in check_enable_mode
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko-4.0.0-py3.10.egg\netmiko\base_connection.py", line 1863, in check_enable_mode
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko-4.0.0-py3.10.egg\netmiko\base_connection.py", line 734, in read_until_prompt
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko-4.0.0-py3.10.egg\netmiko\base_connection.py", line 651, in read_until_pattern
netmiko.exceptions.ReadTimeout: 

Pattern not detected: 'root@ubuntuonprem:/home/sfm_admin.*' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.



Process finished with exit code 1

Note: in the same code, if I use "output = net_connect.send_command_timing(cmd0, delay_factor=5)" it works, it is only when i am sending Array of commands, I see not working in Ubuntu Linux.
Help me here, i dont see any issue in the session log.

**Comment by ktbyers** [comment]
It looks like you are sending these three commands. I reformatted it slightly since you were overloading commands by using a semi-colon

```
[
    'docker exec -ti hpe_nfc /bin/sh', 
    'cd /opt/hpe/nns/NVME-OF-Server/nns-cli',
    './nnsadm -a 100.100.2.254 -r dd -n DD1_vlan-2'
]

Netmiko is not going to like that `cd` command since it is going to change the prompt

Basically the issue is send_config_set ultimately tries to exit enable mode ("sudo -s") and when it does this it checks if it is currently in enable_mode and as part of this it tries to read_until_prompt(), but the prompt has changed in the middle of the configuration (so Netmiko fails to identify the prompt).

Near-term fix:

Use the full-path above and don't do a "cd" i.e. change the command to:

```
    '/opt/hpe/nns/NVME-OF-Server/nns-cli/nnsadm -a 100.100.2.254 -r dd -n DD1_vlan-2'
```

Second option:

Just call send_command() three times or use send_multiline() instead of using send_config_set().

Leave this issue open as I don't really like what Netmiko does here.

**Comment by govindrathod1987** [comment]
Hi @ktbyers Thanks :) 
I tried the second option today as suggested by you and worked:

"""
Second option:

Just call send_command() three times or use send_multiline() instead of using send_config_set().

"""
as said by you,  I have left the issue opened for now.

**Comment by ktbyers** [comment]
I think this exit_config_mode issue was probably fixed here:

https://github.com/ktbyers/netmiko/pull/2794
