### ISSUE TITLE
Extreme EXOS read-only account

### ISSUE THREAD

**Issue by kingroudy** [ktbyers/netmiko#2723]
Hi,

It seems netmiko is unable to handle Extreme EXOS when logging in with read-only (user, non-administrative privilege) accounts. The difference be it that admin accounts end their prompt with '#' while read only accounts end their prompt with '>'

example:
            testhost.1 >
            testhost.2 >
            testhost.3 >

Having searched the source code, it seems the '#' is hard coded in extreme_exos.py on line 18:
        self._test_channel_read(pattern=r"#")

I'm looking for a fix that allows either '#' or '>'
Or a fix that allows specifying the pattern.

Here's the full error:

`Traceback (most recent call last):
  File "d:\Git\automation\roudy\netmiko-test.py", line 7, in <module>
    net_connect = ConnectHandler(**soleil11)
  File "C:\Users\relchammas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\netmiko\ssh_dispatcher.py", line 344, in ConnectHandler 
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\relchammas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\netmiko\base_connection.py", line 434, in __init__      
    self._open()
  File "C:\Users\relchammas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\netmiko\base_connection.py", line 440, in _open
    self._try_session_preparation()
  File "C:\Users\relchammas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\netmiko\base_connection.py", line 879, in _try_session_preparation
    self.session_preparation()
  File "C:\Users\relchammas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\netmiko\extreme\extreme_exos.py", line 18, in session_preparation
    self._test_channel_read(pattern=r"#")
  File "C:\Users\relchammas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\netmiko\base_connection.py", line 1119, in _test_channel_read
    return self.read_until_pattern(pattern=pattern, read_timeout=20)
  File "C:\Users\relchammas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\netmiko\base_connection.py", line 651, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout:

Pattern not detected: '#' in output.

Things you might try to fix this:
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.`

**Comment by ktbyers** [comment]
@kingroudy I will try to fix this today.

**Comment by ktbyers** [comment]
Fixed here:

https://github.com/ktbyers/netmiko/pull/2729
