### ISSUE TITLE
cisco_wlc_ssh fails to connect with netmiko4 but works with 3.3.3

### ISSUE THREAD

**Issue by yurividal** [ktbyers/netmiko#2749]
When usign latest version (4.0) my script fails to connect to cisco wlc running version 8.10.162.0 of AIREOS. 
Downgrading to v3.3.3 makes the script work again.
Problem seems to be on the prompt. v4 is waiting for # while wlc gives out >

**Comment by ktbyers** [comment]
@yurividal Can you post the full exception stack trace that you receive? Netmiko should support a prompt with a `>` in it (for the WLC).

**Comment by ktbyers** [comment]
@yurividal Do you have that full exception stack trace?

**Comment by yurividal** [comment]
Hi. Sorry, I wasn't at work for the past couple days.
I will collect a full stack trace tomorrow and upload it here.

Yuri Vidal
📲 +44 7415565606

**Comment by ktbyers** [comment]
Sounds good. Thanks @yurividal

**Comment by yurividal** [comment]
Is there a template of the code snippet I need to run and grab the output?
I might not have too much time to do this at work.

Yuri Vidal
📲 +44 7415565606

**Comment by ktbyers** [comment]
It should just generate the exception as long as you remove any try/except handles from the ConnectHandler call.

In other words, just create a Netmiko connection using ConnectHandler with no try/except statements wrapping it.

**Comment by yurividal** [comment]
@ktbyers here it is. the code i ran and the exception:

Code:
````
from netmiko import ConnectHandler

net_connect = ConnectHandler(device_type='cisco_wlc_ssh', host=IP,
                             username=USER, password=PASSWORD, banner_timeout=10)

net_connect.send_command('config paging disable')
raw_output = net_connect.send_command_expect('show ap summary')

output_lines = raw_output.split('\n')
for line in output_lines:
    print(line)

````
Result:
````
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\wlctest.py", line 4, in <module>
    net_connect = ConnectHandler(device_type='cisco_wlc_ssh', host='192.168.36.9',
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\netmiko\ssh_dispatcher.py", line 344, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\netmiko\cisco\cisco_wlc_ssh.py", line 18, in __init__
    return super().__init__(*args, **kwargs)
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\netmiko\base_connection.py", line 434, in __init__
    self._open()
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\netmiko\base_connection.py", line 440, in _open
    self._try_session_preparation()
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\netmiko\base_connection.py", line 879, in _try_session_preparation
    self.session_preparation()
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\netmiko\cisco\cisco_wlc_ssh.py", line 154, in session_preparation
    self._test_channel_read(pattern=r"[>#]")
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\netmiko\base_connection.py", line 1119, in _test_channel_read
    return self.read_until_pattern(pattern=pattern, read_timeout=20)
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\netmiko\base_connection.py", line 651, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout:

Pattern not detected: '[>#]' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.
````

I have also tried using the following line after the initial statement, but no luck.
````
net_connect.set_base_prompt(
    pri_prompt_terminator=u'>', alt_prompt_terminator=u' >', delay_factor=4)
````

Also tried replacing cisco_wlc_ssh with cisco_wlc
Stil the same problem. Works just fine if i downgrade to netmiko 3.3.3

**Comment by ktbyers** [comment]
So Netmiko is expecting to read either a `>` or a `#` after it completes it login. It is failing on this read.

Can you show what the initial SSH login looks like if you do it manually (including the username and password handling as the WLC does odd things here). You can obscure hide your username/password i.e. just convert them to `admin/admin` or something.

**Comment by yurividal** [comment]
First connection:
````
ssh admin@192.168.36.9
The authenticity of host '192.168.36.9 (192.168.36.9)' can't be established.
ECDSA key fingerprint is SHA256:0tiweKjCuAZ7EaiqhgcMhjf5uUJ6FvW7nrJZ9DZhe2U.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '192.168.36.9' (ECDSA) to the list of known hosts.
admin@192.168.36.9's password:

(Cisco Controller) >
````
Seccond time connecting:
````
ssh admin@192.168.36.9
admin@192.168.36.9's password:

(Cisco Controller) >
````

**Comment by ktbyers** [comment]
Okay, let me try to make a fix for this.

**Comment by thamuppet** [comment]
Hi, I got this issue today as well. Strange part is that it's working in another script with same netmiko version and settings.

The working script:
```
from netmiko import ConnectHandler
from threading import Thread
list = ['wlc1.test.local', 'wlc2.test.local']

threads = []
the_wlc_output = []
def get_from_wlc(wlc, the_output):
    print(wlc)
    ssh = ConnectHandler(**wlc)
    output = ssh.send_command('show ap summary')
    the_output.append(output)
    
while True:
    for host in list:
        wlc = {
            "device_type": "cisco_wlc",
            "host": host,
            "username": "****",
            "password": "****",
            "banner_timeout": 30
        }
        t = Thread(target=get_from_wlc, args=(wlc, the_wlc_output))
        threads.append(t)
    for x in threads:
        x.start()
    for x in threads:
        x.join()

    if len(the_wlc_output) > 0:
        print("\n".join(the_wlc_output))
        break
```

When it comes to the other script it's a bit harder to pull out the part of the script that connects to wlcs
But i'll do my best (very new to Python/Netmiko and being active on forums, forgive me if it's unclear)

This is the python file where the functions for wlc-connection is pulled from:

```
from netmiko import ConnectHandler
import time




def get_wlc_cred(data, site, host):
    wlc = data[site][host]
    return wlc

def get_wlc_output(wlc, wlc_output, host_name):
    print(f'Pulling list of APs from {host_name}')
    ssh_wlc = ConnectHandler(**wlc)
    time.sleep(5)
    ssh_wlc.send_command('\n')
    time.sleep(5)
    out = ssh_wlc.send_command('\n')
    print(out)
    output_wlc = ssh_wlc.send_command('show ap summary')
    wlc_output.append(output_wlc)
```

   
   Here is the part of the main-script that triggers the functions:
   
```
           elif user_choice == "8":
            con_wlc = ['wlc']
            output_wlc = []
            threads_wlc = []
            connect_to_wlc = []
            send_back_faults = []
            return_failed_wlc = []
            for host in list_of_hosts:
                if any(x in host.lower() for x in con_wlc):
                    connect_to_wlc.append(host)
                else:
                    continue
            if len(connect_to_wlc) > 0:
                remove_dup = set(connect_to_wlc)
                print(remove_dup)
                for host in remove_dup:
                    time.sleep(2)
                    wlc = get_wlc_cred(data, site, host)
                    wlc_t = Thread(target=get_wlc_output, args=(wlc, output_wlc, host))
                    threads_wlc.append(wlc_t)
                for x in threads_wlc:
                    x.start()
                for x in threads_wlc:
                    x.join()
            else:
                print('failed')

            print(colored('Looking for APs not found in any WLC', 'yellow'))
            for host in list_of_hosts:
                if host.lower() in avoid_hosts:
                    continue
                else:
                    net_host = get_host_cred(data, site, host)
                    t = Thread(target=get_all_aps, args=(host, net_host, output_wlc, send_back_faults))
                    threads.append(t)
            for x in threads:
                x.start()
            for x in threads:
                x.join()
            if len(send_back_faults) > 0:
                print('\nFollowing APs not found in any WLC')
                print(colored("\n".join(send_back_faults), 'red'))
            else:
                print(colored("Found no APs that wasn't connected to any WLC", 'green'))
```
    
   The output from logging:
```
   DEBUG:paramiko.transport:userauth is OK
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 35000 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 35000 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:read_channel: 
(Cisco Controller) >
DEBUG:netmiko:read_channel: 
(Cisco Controller) >
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
```

I cut the logging here as the read_channel continues for a LONG time. Heres the end:

```
DEBUG:netmiko:write_channel: b'config paging enable\n'
DEBUG:netmiko:write_channel: b'config paging enable\n'
DEBUG:netmiko:read_channel: config paging enable


(Cisco Controller) >
DEBUG:netmiko:read_channel: config paging enable


(Cisco Controller) >
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
(Cisco Controller) >
DEBUG:netmiko:read_channel: 
(Cisco Controller) >
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'logout\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'logout\n'
DEBUG:paramiko.transport:[chan 0] EOF received (0)
DEBUG:paramiko.transport:[chan 0] EOF sent (0)
DEBUG:paramiko.transport:EOF in transport thread
DEBUG:netmiko:read_channel: logout
DEBUG:netmiko:read_channel: logout
```

And the error message in script:
```
Exception in thread Thread-1 (get_wlc_output):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/anton/checky/checky/files/wlc_functions.py", line 12, in get_wlc_output
    ssh_wlc = ConnectHandler(**wlc)
  File "/Users/anton/scripts/fiber-check/venv/lib/python3.10/site-packages/netmiko/ssh_dispatcher.py", line 344, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/Users/anton/scripts/fiber-check/venv/lib/python3.10/site-packages/netmiko/cisco/cisco_wlc_ssh.py", line 18, in __init__
    return super().__init__(*args, **kwargs)
  File "/Users/anton/scripts/fiber-check/venv/lib/python3.10/site-packages/netmiko/base_connection.py", line 434, in __init__
    self._open()
  File "/Users/anton/scripts/fiber-check/venv/lib/python3.10/site-packages/netmiko/base_connection.py", line 440, in _open
    self._try_session_preparation()
  File "/Users/anton/scripts/fiber-check/venv/lib/python3.10/site-packages/netmiko/base_connection.py", line 879, in _try_session_preparation
    self.session_preparation()
  File "/Users/anton/scripts/fiber-check/venv/lib/python3.10/site-packages/netmiko/cisco/cisco_wlc_ssh.py", line 154, in session_preparation
    self._test_channel_read(pattern=r"[>#]")
  File "/Users/anton/scripts/fiber-check/venv/lib/python3.10/site-packages/netmiko/base_connection.py", line 1119, in _test_channel_read
    return self.read_until_pattern(pattern=pattern, read_timeout=20)
  File "/Users/anton/scripts/fiber-check/venv/lib/python3.10/site-packages/netmiko/base_connection.py", line 651, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 

Pattern not detected: '[>#]' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.
```

It's working with netmiko 3.3.0

Not sure if this helps, please reach out if I can be of more help.

**Comment by applericky** [comment]
Hi @ktbyers. I played around with the         self._test_channel_read under the cisco_wlc_ssh.py file. I attempted to do different ways the pattern could be read including even adding the whole hostname and it still is unable to read it. I also tested to loop forever until it times out but it doesn't appear to even read it. I'm guessing the issue might be under the base_connection.py? I would love to try and debug but I wanted to see if you had some place to check first.

**Comment by ktbyers** [comment]
@applericky 

Could you try this proposed fix here:

https://github.com/ktbyers/netmiko/pull/2822

And see if it works or it if still fails?

If it still fails, then it would be good to see the full exception stack-trace. It definitely is not clear to me what is causing the reported failure, error.

**Comment by thamuppet** [comment]
Still got issues with this
Now I get:

_Pattern not detected: '\\(Cisco\\ Controller\\)\\ >' in output._

`  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/netmiko/utilities.py", line 592, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/netmiko/base_connection.py", line 1721, in send_command
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout:
Pattern not detected: '\\(Cisco\\ Controller\\)\\ >' in output.

Things you might try to fix this:
1. Explicitly set your pattern using the expect_string argument.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.`
