### ISSUE TITLE
Execute the multi -line command to report an error

### ISSUE THREAD

**Issue by luweijun1992** [ktbyers/netmiko#2757]
```
commands = '''
display current-configuration
display device
display version
display lldp neighbor brief
'''
net_connect.send_config_set(commands)
```

```
Traceback (most recent call last):
  File "C:\Soft\Python\Python310\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Soft\Python\Python310\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Soft\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 573, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\Soft\Python\Python310\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Work\WorkSpace\Python\net_ssh.py", line 87, in <module>
    ssh_connect(host, username, password, commands)
  File "d:\Work\WorkSpace\Python\net_ssh.py", line 57, in ssh_connect
    net_connect.send_config_set(commands)
  File "C:\Soft\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 1912, in send_config_set
    new_output = self.read_until_pattern(pattern=re.escape(cmd.strip()))
  File "C:\Soft\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 655, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "C:\Soft\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 583, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.
```

**Comment by ktbyers** [comment]
@luweijun1992 `send_config_set` is only intended for configuration commands. It is not intended for `show` commands (so if it works for show commands, that is entirely accidental). If it doesn't work, then I am just going to say...don't do that.

In Netmiko 4.X and later, there are two main ways to do multiple show commands in a row.

`send_multiline()`   (or similarly send_multiline_timing())
`send_command()` and a for-loop.

The particular error above is failing because of `cmd_verify` (so you would need to set `cmd_verify=False`).

**Comment by luweijun1992** [comment]
> @luweijun1992 `send_config_set` is only intended for configuration commands. It is not intended for `show` commands (so if it works for show commands, that is entirely accidental). If it doesn't work, then I am just going to say...don't do that.
> 
> In Netmiko 4.X and later, there are two main ways to do multiple show commands in a row.
> 
> `send_multiline()` (or similarly send_multiline_timing()) `send_command()` and a for-loop.
> 
> The particular error above is failing because of `cmd_verify` (so you would need to set `cmd_verify=False`).

Yes, When I use the following way to execute, normal.
```
commands = '''
display current-configuration
display device
display version
display lldp neighbor brief
'''
net_connect.send_config_set(commands, cmd_verify=False)
```
In addition, I would like to add splitlines().
What is the difference in the final execution.
```
net_connect.send_config_set(commands, cmd_verify=False)
net_connect.send_config_set(commands.splitlines(), cmd_verify=False)
```

**Comment by ktbyers** [comment]
@luweijun1992 Okay, I am going to close this.

As per my original response, you shouldn't use that pattern (i.e. you shouldn't use send_config_set() to execute show commands).
