### ISSUE TITLE
NetMikoAuthenticationException: Telnet login failed when connecting to GNS3 device

### ISSUE THREAD

**Issue by sockduct** [ktbyers/netmiko#276]
@ktbyers - per your request, I am opening an issue on failing to connect to a GNS3 simulated Cisco router.  This is using netmiko v1.0 from PyPI:
```
>>> r1t = dict(device_type='cisco_ios_telnet', ip='192.0.2.253', username='cisco', password='cisco', secret='cisco', port=23, verbose=True)
>>> dev_conn = netmiko.ConnectHandler(**r1t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Apps\Python27\lib\site-packages\netmiko\ssh_dispatcher.py", line 94, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Apps\Python27\lib\site-packages\netmiko\base_connection.py", line 68, in __init__
    self.establish_connection()
  File "C:\Apps\Python27\lib\site-packages\netmiko\base_connection.py", line 340, in establish_connection
    self.telnet_login()
  File "C:\Apps\Python27\lib\site-packages\netmiko\base_connection.py", line 252, in telnet_login
    raise NetMikoAuthenticationException(msg)
netmiko.ssh_exception.NetMikoAuthenticationException: Telnet login failed: 192.0.2.253
```

Note:  I can successfully telnet to the device using putty, but it is painfully slow - taking many seconds to do each step.  I'm not sure fixing this is very helpful, but it is a very good torture test if you want to subject netmiko to very slow response times.  Let me know if you'd like more info.

**Comment by ktbyers** [comment]
@sockduct Does it work if you sent global_delay_factor to 2 or 4 (or something larger). global_delay_factor is an argument that you would include in the r1t dictionary.

**Comment by sockduct** [comment]
@ktbyers - well, setting global_delay_factor to 4 works for authentication.  However, there are problems with sending commands using send_command:
```
>>> print(dev_conn.send_command_timing('sh ip int br'))
Interface                  IP-Address      OK? Method Status                Protocol
FastEthernet0/0            unassigned      YES NVRAM  administratively down down
FastEthernet1/0            172.16.1.1      YES NVRAM  up                    up
FastEthernet1/1            192.0.2.253     YES NVRAM  up                    up
Serial2/0                  unassigned      YES NVRAM  administratively down down
Serial2/1                  unassigned      YES NVRAM  administratively down down
Serial2/2                  unassigned      YES NVRAM  administratively down down
Serial2/3                  unassigned      YES NVRAM  administratively down down
Loopback0                  172.31.255.1    YES NVRAM  up                    up
>>>
>>> print(dev_conn.send_command('sh ip int br'))

>>> print(dev_conn.send_command_expect('sh ip int br'))

>>> netmiko.__version__
'1.0.0'
```
What should I do/provide to troubleshoot why send_command isn't working in this case?

**Comment by ktbyers** [comment]
@sockduct What does it look like when you execute 'sh ip int br' manually and how many seconds does it take for the response to come back (when manual).

You could also turn on debugging in the send_command_expect method...that might provide some clues as to what is happening.

**Comment by sockduct** [comment]
@ktbyers It's super slow, on the order of seconds.  I tried enable debugging in send_command, but the output is pretty terse:
```
Found prompt: R1#
Command is: sh ip int br

Search to stop receiving data is: 'R1\#'
5:
R1#
```

I don't think this is worth the effort because it's so slow.  One thing that might be worth some effort is connecting directly to the port that GNS3/dynamips listens to.  This acts like an unauthenticated reverse telnet port.  However, it doesn't quite work:
```
In telnet_login():
Connected to Dynamips VM "R2" (ID 2, type c7200) - Console port
Press ENTER to get the prompt.
ERVICESK9-M), Version 15.2(4)M5, RELEASE SOFTWARE (fc2)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2013 by Cisco Systems, Inc.
Compiled Fri 13-Sep-13 18:47 by prod_rel_team


This product contains cryptographic features and is subject to United
States and local country laws governing import, export, transfer and
use. Delivery of Cisco cryptographic products does not imply
third-party authority to import, export, distribute or use encryption.
Importers, exporters, distributors and users are responsible for
compliance with U.S. and local country laws. By using this product you
agree to comply with applicable laws and regulations. If you are unable
to comply with U.S. and local laws, return this product immediately.

A summary of U.S. laws governing Cisco cryptographic products may be found at:
http://www.cisco.com/wwl/export/crypto/tool/stqrg.html

If you require further assistance please contact us by sending email to
export@cisco.com.

Cisco 7206VXR (NPE400) processor (revision A) with 491520K/32768K bytes of memory.Installed image archive

Processor board ID 4279256517
R7000 CPU at 150MHz, Implementation 39, Rev 2.1, 256KB L2, 512KB L3 Cache
6 slot VXR midplane, Version 2.1

Last reset from power-on

PCI bus mb0_mb1 (Slots 0, 1, 3 and 5) has a capacity of 600 bandwidth points.
Current configuration on bus mb0_mb1 has a total of 600 bandwidth points.
This configuration is within the PCI bus capacity and is supported.

PCI bus mb2 (Slots 2, 4, 6) has a capacity of 600 bandwidth points.
Current configuration on bus mb2 has a total of 0 bandwidth points
This configuration is within the PCI bus capacity and is supported.

Please refer to the following document "Cisco 7200 Series Port Adaptor
Hardware Configuration Guidelines" on Cisco.com <http://www.cisco.com>
for c7200 bandwidth points oversubscription and usage guidelines.


3 FastEthernet interfaces
125K bytes of NVRAM.

65536K bytes of ATA PCMCIA card at slot 0 (Sector size 512 bytes).
8192K bytes of Flash internal SIMM (Sector size 256K).
% Crashinfo may not be recovered at bootflash:crashinfo
% This file system device reports an error


Press RETURN to get started!


*Sep 22 20:18:48.171: %IFMGR-7-NO_IFINDEX_FILE: Unable to open nvram:/ifIndex-table No such file or directory
*Sep 22 20:19:01.871: %LINEPROTO-5-UPDOWN: Line protocol on Interface VoIP-Null0, changed state to up
*Sep 22 20:19:01.883: %LINK-3-UPDOWN: Interface FastEthernet0/0, changed state to up
*Sep 22 20:19:01.899: %LINK-3-UPDOWN: Interface FastEthernet1/0, changed state to up
*Sep 22 20:19:01.915: %LINK-3-UPDOWN: Interface FastEthernet1/1, changed state to up
*Sep 22 20:19:02.995: %LINEPROTO-5-UPDOWN: Line protocol on Interface FastEthernet0/0, changed state to down
*Sep 22 20:19:03.003: %LINEPROTO-5-UPDOWN: Line protocol on Interface FastEthernet1/0, changed state to up
*Sep 22 20:19:03.011: %LINEPROTO-5-UPDOWN: Line protocol on Interface FastEthernet1/1, changed state to up
*Sep 22 20:19:04.947: %SYS-5-CONFIG_I: Configured from memory by console
*Sep 22 20:19:05.267: %SYS-5-RESTART: System restarted --
Cisco IOS Software, 7200 Software (C7200-ADVIPSERVICESK9-M), Version 15.2(4)M5, RELEASE SOFTWARE (fc2)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2013 by Cisco Systems, Inc.
Compiled Fri 13-Sep-13 18:47 by prod_rel_team
*Sep 22 20:19:05.819: %LINK-5-CHANGED: Interface FastEthernet0/0, changed state to administratively down
*Sep 22 20:19:05.823: %LINEPROTO-5-UPDOWN: Line protocol on Interface Loopback0, changed state to up
*Sep 22 20:19:06.099: %CRYPTO-6-ISAKMP_ON_OFF: ISAKMP is OFF
*Sep 22 20:19:06.099: %CRYPTO-6-GDOI_ON_OFF: GDOI is OFF
*Sep 22 20:19:06.327: %DUAL-5-NBRCHANGE: EIGRP-IPv4 1: Neighbor 172.16.2.2 (FastEthernet1/1) is up: new adjacency
*Sep 22 20:19:06.491: %SNMP-5-COLDSTART: SNMP agent on host R2 is undergoing a cold start
*Sep 22 20:19:08.395: %DUAL-5-NBRCHANGE: EIGRP-IPv4 1: Neighbor 172.16.1.1 (FastEthernet1/0) is up: new adjacency
R2#
R2#
R2#
checkpoint5
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "netmiko\ssh_dispatcher.py", line 94, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "netmiko\base_connection.py", line 68, in __init__
    self.establish_connection()
  File "netmiko\base_connection.py", line 433, in establish_connection
    raise NetMikoTimeoutException("Timed out waiting for data")
netmiko.ssh_exception.NetMikoTimeoutException: Timed out waiting for data
```

I don't want to suck up too much of your time.  If you think this is interesting, suggestions on debugging?  If not, let me know and I'll close it out.

**Comment by ktbyers** [comment]
Yes, I somewhat think the problem is due to it being super slow. If it doesn't matter to you, then we should probably just close it.

**Comment by sockduct** [comment]
Reverse telnet server support (e.g., for terminal servers) may be worth considering in the future.  But for now, I don't really have a practical use case so closing.

**Comment by ktbyers** [comment]
Yeah, reverse telnet (terminal servers) is worth considering improving.

There are also some Cisco devices with an embedded device (like an embedded access-point) that you session into. Which is basically the same use case.

There is an open Netmiko issue on this.
