### ISSUE TITLE
cisco_xr commit() error on IOS 6.x

### ISSUE THREAD

**Issue by bodothebest** [ktbyers/netmiko#2773]
Hi,
I wrote my first netmiko script to send some commands to a bunch of IOS XR routers, but I get an error when I commit the changes with the function commit().
I have two different sets of XR routers (ASR9K): some have 32bit IOS XR 6.x and others have 64bit IOS XR 7.x and the problem is present only on the ones with version 6.x.
This is my script (shortened for readability):

```
from netmiko import ConnectHandler
import getpass
import sys
import time

device = {
    'session_log': 'netmiko_session.log',
    'device_type': 'cisco_xr',
    'ip': '1.1.1.1',
    'username': 'username',
    'password': 'password',
    'secret':'password'
    }

ipfile=open("apparati_mpls_ios_XR.txt")

print ("Inserisci le credenziali per l'accesso SSH agli apparati")
device['username']=input("User name: ")
device['password']=getpass.getpass()
device['secret']=getpass.getpass(prompt='Enable password: ')

config_commands = [
        'no ipv4 access-list ACL',
        'ipv4 access-list ACL',
        'permit ipv4 10.0.0.0 0.0.0.255 any',
        ]

for line in ipfile:

 devname, devip = line.strip("\n").split(':')
 device['ip']=devip
 print("\n\nConnessione a "+devname,"("+devip+")...")

 net_connect = ConnectHandler(**device)
 net_connect.enable()
 time.sleep(2)
 print ("Invio configurazione... ")
 net_connect.send_config_set(config_commands)
 print ("Configurazione terminata, salvo le modifiche...")
 net_connect.commit(read_timeout=20)

ipfile.close()
```

and this is the output:

```
Connessione a XR-6 (X.X.X.X)...
Invio configurazione... 
Configurazione terminata, salvo le modifiche...
Traceback (most recent call last):
  File "netmiko_config_xr.py", line 64, in <module>
    net_connect.commit()
  File "/home/marco/.local/lib/python3.8/site-packages/netmiko/cisco/cisco_xr.py", line 143, in commit
    new_data = self._send_command_str(
  File "/home/marco/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 1716, in _send_command_str
    output = self.send_command(*args, **kwargs)
  File "/home/marco/.local/lib/python3.8/site-packages/netmiko/utilities.py", line 596, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/home/marco/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 1644, in send_command
    new_data = self.command_echo_read(cmd=cmd, read_timeout=10)
  File "/home/marco/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 1369, in command_echo_read
    new_data = self.read_until_pattern(
  File "/home/marco/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 651, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 

Pattern not detected: 'y' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.
```

In fact the commands are executed and committed correctly, but the error breaks the execution of the scripts, so only the first router in the list is processed. This is the log of the session:

```
RP/0/RSP0/CPU0:XR-6#terminal width 511
Fri May  6 18:04:48.679 CEST
RP/0/RSP0/CPU0:XR-6#terminal length 0
Fri May  6 18:04:48.942 CEST
RP/0/RSP0/CPU0:XR-6#
RP/0/RSP0/CPU0:XR-6#
RP/0/RSP0/CPU0:XR-6#
RP/0/RSP0/CPU0:XR-6#configure terminal
Fri May  6 18:04:51.434 CEST
RP/0/RSP0/CPU0:XR-6(config)#
RP/0/RSP0/CPU0:XR-6(config)#no ipv4 access-list ACL
RP/0/RSP0/CPU0:XR-6(config)#ipv4 access-list ACL
RP/0/RSP0/CPU0:XR-6(config-ipv4-acl)#permit ipv4 10.0.0.0 0.0.0.255 any
RP/0/RSP0/CPU0:XR-6(config-ipv4-acl)#
RP/0/RSP0/CPU0:XR-6(config-ipv4-acl)#commit
Fri May  6 18:04:53.114 CEST
This could be a few minutes if your config is large. Confirm? [y/n][confirm]
RP/0/RSP0/CPU0:XR-6(config-ipv4-acl)#
RP/0/RSP0/CPU0:XR-6(config-ipv4-acl)#
```

When the script is executed on a router with IOS XR 7 everything is ok and no exception is thrown. The output is the same, with the difference of this line:

```
RP/0/RSP0/CPU0:XR-7(config-ipv4-acl)#commit
Fri May  6 18:31:52.654 CEST
*** This could be a few minutes if your config is large. Confirm? [y/n][confirm] y ***
RP/0/RSP0/CPU0:XR-7(config-ipv4-acl)#
```

So it looks like the commit() function expects to see the "y" after the "Confirm? [y/n][confirm]", but on IOS 6.x the "y" is not printed (even if I write the command myself in the CLI). Looking at the source code it seems to me that the expected output is the hashtag 
```
if "onfirm" in new_data:
            output += new_data
            new_data = self._send_command_str(
                "y",
                expect_string=r"#",
                strip_prompt=False,
                strip_command=False,
                read_timeout=read_timeout,
            )

```
but the error message says otherwise.

I am running the latest release of netmiko, 4.1.0, with Python 3.8.10
Am I missing something? There are a lot of XR 6.x routers out there, I'd think that someone else would be noticing this, so probably I'm doing something wrong...

**Comment by ktbyers** [comment]
So this is due to Netmiko's cmd_verify feature, basically Netmiko expects commands to be properly echoed in certain contexts (send_command being one of them).

So if you send a "y", Netmiko expects that to be echoed to the screen.

The purpose of cmd_verify is to ensure that Netmiko does not get out-of-sync with respect to the state of the device. In other words, it is easy for Netmiko to get ahead of the device i.e. Netmiko thinks it is doing Y, but the device is still back doing X that happened earlier).

You can probably set: `global_cmd_verify=False` as an argument to cmd_verify.

I will put a fix into Netmiko that disables cmd_verify for this one call (since the "y" is not echoed for some versions of IOS-XR code).

```python
            new_data = self._send_command_str(
                "y",
                expect_string=r"#",
                strip_prompt=False,
                strip_command=False,
                read_timeout=read_timeout,
                cmd_verify=False,
            )
```

**Comment by bodothebest** [comment]
I see, thank you.
That "echo check" is a clever implementation and it does a great deal in terms of reliability of the scripts.
I will wait for the fix, meanwhile thank you for addressing this issue so quickly and for your great job with netmiko!

**Comment by ktbyers** [comment]
Fixed here:

https://github.com/ktbyers/netmiko/pull/2925
