### ISSUE TITLE
Netmiko Disconnects before finishing gathering command output

### ISSUE THREAD

**Issue by m1ndn1nj4** [ktbyers/netmiko#2796]
Hello, I'm trying to run the command `show ap summary` on a Cisco 9800 WLC. This WLC has 1,997 APs on the controller. However netmiko disconnects before it finishes the output of the command. Is there a way to extend this?

```python
def run_verification_commands(devices_list):
    # Create the connection parameters.
    connection_info = {
        "username": device_username.lower(),
        "password": device_password,
        "secret": device_password,
        "banner_timeout": 30,
        "verbose": False,
        "global_delay_factor": 2,
        "timeout": 3,
        "fast_cli": False,
        "ssh_config_file": "~/.ssh/config",
    }
```

**Comment by ktbyers** [comment]
Not enough information here. I need the relevant code and the full exception stack trace.

Try to have the code be as simple as possible that illustrates the problem that you are describing.

**Comment by m1ndn1nj4** [comment]
I don't get a stack trace. It says it completes successfully. But by viewing the Debug log, I can tell you that it only gets through about 30% of the output of the command then it disconnects.

```python
# Run Verification Commands and Log output.
def run_verification_commands(devices_list):
    # Create the connection parameters.
    connection_info = {
        "username": device_username.lower(),
        "password": device_password,
        "secret": device_password,
        "banner_timeout": 30,
        "verbose": False,
        "global_delay_factor": 2,
        "timeout": 3,
        "fast_cli": False,
        "allow_auto_change": False,
        "ssh_config_file": "~/.ssh/config",
    }

    hostname = devices_list["hostname"]
    platform = devices_list["platform"]
    fpath = f"MCM-Verification-Checks/{whid}/{mcm}/{stage}-Checks"
    filename = f"/{hostname}-{mcm}-{stage}-Checks.txt"
    success = f"Verification commands were successfully captured on {hostname}!"

    try:
        with open(f"{fpath}{filename}", "w+", newline="",) as logfile:
            print(f"Connecting to host {hostname}...")
            ssh_connection = ConnectHandler(
                host=hostname,
                device_type=platform,
                **connection_info
            )
            # Run Verification Commands for Wireless Controllers.
            if ....:
            elif "cisco_ios" in platform and (
                    "co-wlc" in hostname
                    or "fc-wlc" in hostname
            ):
                ssh_connection.enable()
                print(f"Running verification commands for host {hostname}...")
                for commands in VERIFICATION_COMMANDS["cisco_ios"][
                    "(co|fabric)-wlc"
                ]:
                    logfile.write(
                        ssh_connection.send_command(
                            commands,
                            strip_command=False,
                            strip_prompt=False,
                        )
                    )
                    sleep(1)
                print(success)
```

**Comment by ktbyers** [comment]
Git rid of all your try/except statements ((as those can hide errors).

What are the commands that you are sending i.e. you don't show the actual commands that you are sending.

**Comment by m1ndn1nj4** [comment]
Commands:
```python
# Verification Commands for each device platform/type.
VERIFICATION_COMMANDS = {
    "cisco_ios": {
        ....
        "(co|fabric)-wlc": [
            "!", "show version ", "!", "show boot", "!", "show ap summary", "!",
            "show ap dot11 5ghz summary | count Up", "!", "show wlan summary",
            "!", "show wireless mobility summary", "!",
            "show ip interface brief | include GigabitEthernet0", "!",
            "show etherchannel summary", "!", "show cdp neighbors", "!",
            "show iox-service", "!", "show telemetry internal connection", "!",
            "show ip interface brief | include Te|Gi", "!",
            "ping vrf Mgmt-intf host.nunya.com df-bit repeat 50", "!",
        ],
        ....
    },
}
```

And this is the output when I run the script on my Linux box:
```
(22-05-23 12:01:08) <0> [~/Documents/Scripts/NetworkDeviceScripts]  
dev-dsk-nunya % python Test1.py
Enter password for nunya: 
Automatically detecting co-wlc-1.nunya.com's platform...
Connecting to host co-wlc-1.amazon.com...
Running verification commands for host co-wlc-1.amazon.com...
The script finished executing in 0 hours 0 minutes and 27 seconds..

(22-05-23 12:01:41) <0> [~/Documents/Scripts/NetworkDeviceScripts]  
dev-dsk-nunya % 
```

**Comment by ktbyers** [comment]
So if you make a much more simplified use case where you just do the following, what happens?

```python
from netmiko import ConnectHandler

device = {
    "username": "username",
    "password": "password",
    "secret": "password",
    "banner_timeout": 30,
    "verbose": False,
    "global_delay_factor": 2,
    # "timeout": 3,         ??? Three seems like probably a bad idea
    "fast_cli": False,
    "allow_auto_change": False,
    "ssh_config_file": "~/.ssh/config",
    "device_type": "cisco_wlc",
    "host": "failing_host"
}

commands = [
    "!",
    "show version ",
    "!",
    "show boot",
    "!",
    "show ap summary",
    "!",
    "show ap dot11 5ghz summary | count Up",
    "!",
    "show wlan summary",
    "!",
    "show wireless mobility summary",
    "!",
    "show ip interface brief | include GigabitEthernet0",
    "!",
    "show etherchannel summary",
    "!",
    "show cdp neighbors",
    "!",
    "show iox-service",
    "!",
    "show telemetry internal connection",
    "!",
    "show ip interface brief | include Te|Gi",
    "!",
    "ping vrf Mgmt-intf host.nunya.com df-bit repeat 50",
    "!",
]
ssh_connection = ConnectHandler(**device)

output = ""
for cmd in commands:
    output += ssh_connection.send_command(cmd, strip_prompt=False, strip_command=False)

print(output)
```


You will have to update some of this to hard-code it to particular values for your environment i.e. username, password, host, etc.

Why do you have all of the exclamation points / comments between commands (is that just for readability of the output)?

**Comment by m1ndn1nj4** [comment]
The exclamation points for for readability of the output. Here's what I get when I run the simplified code on a Windows machine:

```
"C:\Program Files\Python39\python.exe" "C:/Users/<user>/Documents/Visual Studio 2019/Scripts/Python/NetChecks/NC/Test/Test4.py"
Traceback (most recent call last):
  File "C:\Users\<user>\Documents\Visual Studio 2019\Scripts\Python\NetChecks\NC\Test\Test4.py", line 51, in <module>
    output += ssh_connection.send_command(cmd, strip_prompt=False, strip_command=False)
  File "C:\Program Files\Python39\lib\site-packages\netmiko\utilities.py", line 600, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\netmiko\base_connection.py", line 1694, in send_command
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 
Pattern not detected: 'co\\-wlc\\-1>' in output.

Things you might try to fix this:
1. Explicitly set your pattern using the expect_string argument.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.



Process finished with exit code 1
```

On my Linux box, it prints the output up to this:

```cisco
co-wlc-1#!
co-wlc-1#show boot
BOOT variable = bootflash:packages.conf,12;
CONFIG_FILE variable does not exist
BOOTLDR variable does not exist
Configuration register is 0x2102

Standby not ready to show bootvar

co-wlc-1#!
co-wlc-1#
>>> 
```

**Comment by m1ndn1nj4** [comment]
Changing:
```python
output = ""
for cmd in commands:
    output += ssh_connection.send_command(cmd, strip_prompt=False, strip_command=False)

print(output)
```

To:
```python
output = ""
for cmd in commands:
    output += ssh_connection.send_command(cmd, strip_prompt=False, strip_command=False, read_timout=300)

print(output)
```

Fixes it. 

Is there somewhere in the global connection parameters that I can change this to have the same effect, or will I have to do it on every line like this in my script?
```python
                    logfile.write(
                        ssh_connection.send_command(
                            commands,
                            strip_command=False,
                            strip_prompt=False,
                        )
                    )
```

**Comment by ktbyers** [comment]
There is a `read_timeout_override` that you can pass in as an argument to ConnectHandler.

Note, that setting `read_timeout` to that large of a value will imply that it will take 300 seconds for a failure to occur (i.e. it will take 5 minutes before you get an exception in the failing case).

Why was the `show boot` command taking longer than 10 seconds to complete? Is it this slow when you do it manually?

**Comment by m1ndn1nj4** [comment]
It wasn't the `show boot` command, it was the `show ap summary` command.

I used your example I found [here](https://pynet.twb-tech.com/blog/netmiko-read-timeout.html).

```python
from netmiko import ConnectHandler
from datetime import datetime


device = {
    "device_type": "cisco_ios",
    "host": "co-wlc-1.nunya.com",
    "username": "cisco",
    "password": "cisco123",
    "secret": "cisco123",
    "read_timeout_override": 60,
    "fast_cli": False,
}

with ConnectHandler(**device) as net_connect:
    net_connect.enable()
    print(net_connect.find_prompt())
    try:
        start_time = datetime.now()
        output = net_connect.send_command(
            "show ap summary",
        )
    finally:
        end_time = datetime.now()
        print(f"Exec time: {end_time - start_time}")

    # Print just the very beginning of the output
    print("\n".join(output.splitlines()[:3]))
```

Output:
```
"C:\Program Files\Python39\python.exe" "C:/Users/nunya/Documents/Visual Studio 2019/Scripts/Python/NetChecks/NC/Test/Test4.py"
co-wlc-1#
Exec time: 0:00:26.943483
Number of APs: 1997

AP Name                            Slots    AP Model              Ethernet MAC    Radio MAC       Location                          Country     IP Address                                 State         

Process finished with exit code 0
```

It takes around 25 seconds to run the command.
