### ISSUE TITLE
Ruckus switches failing to detect command echo properly

### ISSUE THREAD

**Issue by vongchan** [ktbyers/netmiko#2808]
I try to upgrade os from Ruckus switches, but it gave me an issue every time i run my code. I've attached my code in the txt file in this as well. Thank you all in advance. Looking forward to hearing back from you.

show prompt:
How many switches?: 1
Enter the IP address of the 1:10.23.9.102
What is your username?: super
what is your password?: Password!

You are about to download boot image and boot signature image as well, ARE YOU SURE?(enter 'y' or 'n'): y
Error: Enter y/n  or Y/N for confirmation
Error: Enter y/n  or Y/N for confirmation

Traceback (most recent call last):
  File "C:\Users\VONC\PythonAutomation\SWX-UpgradeOS-ruckus_V2.py", line 85, in <module>
    f.write(Connect_to_Device.send_command(command))
  File "C:\Users\VONC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\netmiko\utilities.py", line 596, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "C:\Users\VONC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\netmiko\base_connection.py", line 1644, in send_command
    new_data = self.command_echo_read(cmd=cmd, read_timeout=10)
  File "C:\Users\VONC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\netmiko\base_connection.py", line 1369, in command_echo_read
    new_data = self.read_until_pattern(
  File "C:\Users\VONC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\netmiko\base_connection.py", line 651, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 

Pattern not detected: 'copy\\ tftp\\ system\\-manifest\\ 20\\.30\\.241\\.200\\ FI08090k_Manifest\\.txt\\ all\\-images\\-primary' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.

Process finished with exit code 1

[new 5.txt](https://github.com/ktbyers/netmiko/files/8825863/new.5.txt)

**Comment by ktbyers** [comment]
Try setting `cmd_verify=False` in your `send_command_timing()` calls and see if that helps.

**Comment by vongchan** [comment]
Hi Kirk,
Thanks for your response. Yes, I did that but it still did not push to the switch. I can send other command or config this switch but not "Y".
**Here is my short codes i try to test it to makes sure the command_send 'y' work:**
`from netmiko import ConnectHandler
from datetime import datetime

List_of_Switches = []
Number_of_switches = int(input("How many switches?: "))

for switch in range(1, Number_of_switches + 1):
    Ask = input("Enter the IP address of the " + str(switch) + ":")
    List_of_Switches.append(Ask)

# get and take the credentails of the admin/switch admin
User = input("What is your username?: ")
Pass = input("what is your password?: ")

for switches in List_of_Switches:
    Network_Device = {
        "host": switches,
        "username": User,
        "password": Pass,
        "device_type": "ruckus_fastiron",
        "global_delay_factor": 4
    }
Connect_to_Device = ConnectHandler(**Network_Device)
Connect_to_Device.enable()

for switches in List_of_Switches:
    Network_Device = {
        "host": switches,
        "username": User,
        "password": Pass,
        "device_type": "ruckus_fastiron",
        "global_delay_factor": 4
    }
    Connect_to_Device = ConnectHandler(**Network_Device)
    Connect_to_Device.enable()

    #Commands send to devices
    List_of_Commands = [
                    #"show flash",
                    "boot system flash primary",
                    ]
    # Edit the candidate configuration
    for command in List_of_Commands:
        start_time = datetime.now()
        output = Connect_to_Device.send_command_timing(
            command,
            cmd_verify=False,
            strip_prompt=False,
            strip_command=False,
            delay_factor=12,
            read_timeout=0,
            #max_loops=1000
        )
        if "Are you sure? (enter 'y' or 'n'):" in output:
            output += Connect_to_Device.send_command_timing(
                command_string="y",
                cmd_verify=False,
                strip_prompt=False,
                strip_command=False,
                delay_factor=1,
                read_timeout=0,
            )
        end_time = datetime.now()
    print(output)
print("\nCompleted")
`


**This is the output:**
How many switches?: 1
Enter the IP address of the 1:20.50.9.106
What is your username?: super
what is your password?: passwd

boot system flash primary

Are you sure? (enter 'y' or 'n'): y
Error: Enter y/n  or Y/N for confirmation
Error: Enter y/n  or Y/N for confirmation


Completed

Process finished with exit code 0

**Comment by ktbyers** [comment]
Why is the device doing this when you sent a `y`?

```
Are you sure? (enter 'y' or 'n'): y
Error: Enter y/n or Y/N for confirmation
Error: Enter y/n or Y/N for confirmation
```

Can you look at the Netmiko session_log and see if you see anything odd there?

The session_log can be enabled by doing the following:

```
    Network_Device = {
        "host": switches,
        "username": User,
        "password": Pass,
        "device_type": "ruckus_fastiron",
        "global_delay_factor": 4,
        "session_log", "output.txt",
    }
```

This will create a file named output.txt in the same directory as your Python script. This should have details on the SSH session.

**Comment by vongchan** [comment]
Thanks, Kirk. I will try it again this Monday and get back to you. I hope I can solve this issue. :)

**Comment by ktbyers** [comment]
Don't know why this wasn't working--on its face looks like it should have worked (i.e. Netmiko properly sent the "y" to the prompt).
