### ISSUE TITLE
connection to the linux server succeeds but throws an exception 

### ISSUE THREAD

**Issue by naahdis** [ktbyers/netmiko#2815]
>>> device = { 'device_type': 'linux', 'host': 'somehost.local, 'username': 'admin', 'password': 'something'}
>>> net_connect = ConnectHandler(**device)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/srajendran/Library/Python/3.8/lib/python/site-packages/netmiko/ssh_dispatcher.py", line 344, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/Users/srajendran/Library/Python/3.8/lib/python/site-packages/netmiko/base_connection.py", line 434, in __init__
    self._open()
  File "/Users/srajendran/Library/Python/3.8/lib/python/site-packages/netmiko/base_connection.py", line 440, in _open
    self._try_session_preparation()
  File "/Users/srajendran/Library/Python/3.8/lib/python/site-packages/netmiko/base_connection.py", line 879, in _try_session_preparation
    self.session_preparation()
  File "/Users/srajendran/Library/Python/3.8/lib/python/site-packages/netmiko/linux/linux_ssh.py", line 23, in session_preparation
    return super().session_preparation()
  File "/Users/srajendran/Library/Python/3.8/lib/python/site-packages/netmiko/base_connection.py", line 898, in session_preparation
    self.set_base_prompt()
  File "/Users/srajendran/Library/Python/3.8/lib/python/site-packages/netmiko/linux/linux_ssh.py", line 45, in set_base_prompt
    return super().set_base_prompt(
  File "/Users/srajendran/Library/Python/3.8/lib/python/site-packages/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/Users/srajendran/Library/Python/3.8/lib/python/site-packages/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/Users/srajendran/Library/Python/3.8/lib/python/site-packages/tenacity/__init__.py", line 360, in iter
    raise retry_exc.reraise()
  File "/Users/srajendran/Library/Python/3.8/lib/python/site-packages/tenacity/__init__.py", line 193, in reraise
    raise self.last_attempt.result()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/srajendran/Library/Python/3.8/lib/python/site-packages/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "/Users/srajendran/Library/Python/3.8/lib/python/site-packages/netmiko/base_connection.py", line 1282, in set_base_prompt
    prompt = self.find_prompt(delay_factor=delay_factor, pattern=pattern)
  File "/Users/srajendran/Library/Python/3.8/lib/python/site-packages/netmiko/base_connection.py", line 1331, in find_prompt
    prompt = prompt.split(self.RESPONSE_RETURN)[-1]
UnboundLocalError: local variable 'prompt' referenced before assignment
>>>

I enabled debug logging and see this in the logs:

DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel:
DEBUG:netmiko:Pattern found: (.*)
DEBUG:netmiko:write_channel: b'exit\n'
DEBUG:paramiko.transport:EOF in transport thread

But I am not able to figure out the failure reason. 

Can I get some help pls?

**Comment by naahdis** [comment]
I am using netmiko in Mac OS:

❯ pip freeze | grep netmiko
netmiko==4.1.0

**Comment by naahdis** [comment]
can I get some help?

**Comment by naahdis** [comment]
Looks like no solution to this...

**Comment by ktbyers** [comment]
@naahdis Can you show what a normal SSH login looks like on this device?

In other words, can you show me the initial prompt and any messages that are displayed on the screen when you manually SSH in.

**Comment by naahdis** [comment]
can you help ?

**Comment by naahdis** [comment]
❯ ssh admin@MASKED
The authenticity of host 'MASKED' can't be established.
ED25519 key fingerprint is SHA256:MASKED
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'MASKED (ED25519) to the list of known hosts.
admin@MASKEDs password:
NSX CLI (Manager, Policy, Controller 4.0.0.1.0.20159694). Press ? for command list or enter: help
blue-mgr-1>

**Comment by ktbyers** [comment]
Try setting this environment variable and making it match your `>` character.

https://github.com/ktbyers/netmiko/blob/develop/netmiko/linux/linux_ssh.py#L12


Regards,

Kirk

**Comment by naahdis** [comment]
apologize for the delayed reply. Here it is..

❯ ssh ***@***.***
The authenticity of host 'MASKED' can't be established.
ED25519 key fingerprint is SHA256:MASKED
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'MASKED (ED25519) to the list of known hosts.
***@***.*** password:
NSX CLI (Manager, Policy, Controller 4.0.0.1.0.20159694). Press ? for
command list or enter: help
blue-mgr-1>

**Comment by ktbyers** [comment]
@naahdis Did you try this?

Try setting this environment variable and making it match your > character.

https://github.com/ktbyers/netmiko/blob/develop/netmiko/linux/linux_ssh.py#L12
