### ISSUE TITLE
netmiko | Telnet log in fails

### ISSUE THREAD

**Issue by marqck** [ktbyers/netmiko#2845]
I'm getting authentication exception and I'm sure that the credentials are correct. I got the session log and it looks like it puts a blank username and the username on the password field.

`net_connect = ConnectHandler(
    device_type = 'cisco_ios_telnet',
    host = ip_address,
    username = creds.username,
    password = creds.password,
    session_log = 'netmiko_session.log'
    )
`

Traceback (most recent call last):
  File "./module1.py", line 93, in <module>
    net_connect = ConnectHandler(
  File "/usr/local/lib/python3.8/dist-packages/netmiko/ssh_dispatcher.py", line 326, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/cisco/cisco_ios.py", line 17, in __init__
    return super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 350, in __init__
    self._open()
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 355, in _open
    self.establish_connection()
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 925, in establish_connection
    self.telnet_login()
  File "/usr/local/lib/python3.8/dist-packages/netmiko/cisco_base_connection.py", line 185, in telnet_login
    raise NetmikoAuthenticationException(msg)
netmiko.ssh_exception.NetmikoAuthenticationException: Login failed: [ipaddress]

'/----------------------------------------------------------------------------\
|                          [banner message]                        |
|  
\----------------------------------------------------------------------------/

User Access Verification

Username:
Username: [username]
Password: %
'

**Comment by ktbyers** [comment]
@marqck Can you try and see what happens using Netmiko version 4.1.1?

**Comment by ktbyers** [comment]
I am going to close this as there was no response. If you are still working on this, let me know.
