### ISSUE TITLE
Unable to install netmiko inside Alpine Linux

### ISSUE THREAD

**Issue by abhi1693** [ktbyers/netmiko#2849]
Textfsm should be pinned to `1.1.2` for now until this issue is resolved. 

The issue is also opened at https://github.com/google/textfsm/issues/105

Here are the error logs
```
Collecting textfsm<2.0.0,>=1.1.0
  Downloading textfsm-1.1.3.tar.gz (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.5/55.5 KB 8.6 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-wheel-8ip9kqvy/textfsm_a6f70795f008490d9a69931703c2fac5/setup.py", line 20, in <module>
          import textfsm
        File "/tmp/pip-wheel-8ip9kqvy/textfsm_a6f70795f008490d9a69931703c2fac5/textfsm/__init__.py", line 11, in <module>
          from textfsm.parser import *
        File "/tmp/pip-wheel-8ip9kqvy/textfsm_a6f70795f008490d9a69931703c2fac5/textfsm/parser.py", line 41, in <module>
          import six
      ModuleNotFoundError: No module named 'six'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

cc @ktbyers

**Comment by ktbyers** [comment]
@abhi1693 Thanks.

Fixed here:

https://github.com/ktbyers/netmiko/pull/2850
