### ISSUE TITLE
Using netmiko with proxy setup from a Windows machine

### ISSUE THREAD

**Issue by mashkoor7675** [ktbyers/netmiko#2855]
Hi

I have read the article: https://pynet.twb-tech.com/blog/netmiko-ssh-proxy-support.html

My scenario is slightly different from the one discussed, in that the source machine I am using to run the script is a Windows machine, and the jumphost I am using as the proxy is a Linux machine. The destination device under management is a Cisco Nexus device. The intermediate server (jumphost) uses GSSAPI authentication only

I have created an SSH config file to be used which looks something like this (sensitive data omitted):
######################
host jumphost
    StrictHostKeyChecking=no
    GSSAPIAuthentication=yes
    User <my_user>
    HostName <my.jumphost.url>

host* !jumphost
    ProxyCommand ssh -F ./ssh-config.proxy -W %h:%p jumphost
######################

Using this ssh config file, I have tested SSH from my Windows machine to the Cisco device using:
ssh -F .\ssh-config.proxy <user>@<dev_ip_address>

... and it works. I get prompted for the device password, after which I am logged in, as expected!

However, when I create a Python script such as this:

######################
import os
from netmiko import ConnectHandler

device = {
    "device_type": "cisco_nxos",
    "host": "<dev_ip_address>",
    "username": "<user"",
    "password": "<dev_password>",
    "ssh_config_file": ".\\ssh-config.proxy",
}

with ConnectHandler(**device) as net_connect:
    output = net_connect.send_command("show users")
    print (output)
######################

When I run this script, I am getting the exception below:

Exception: ProxyCommand("ssh -F ./ssh-config.proxy -W <ommitted>:22 jumphost") returned nonzero exit status: An operation was attempted on something that is not a socket
Traceback (most recent call last):
  File "C:\Users\makhtar6\.conda\envs\python3.9_env\lib\site-packages\paramiko\proxy.py", line 107, in recv
    r, w, x = select([self.process.stdout], [], [], select_timeout)
OSError: [WinError 10038] An operation was attempted on something that is not a socket
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "C:\Users\makhtar6\.conda\envs\python3.9_env\lib\site-packages\paramiko\transport.py", line 2039, in run
    self._check_banner()
  File "C:\Users\makhtar6\.conda\envs\python3.9_env\lib\site-packages\paramiko\transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "C:\Users\makhtar6\.conda\envs\python3.9_env\lib\site-packages\paramiko\packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "C:\Users\makhtar6\.conda\envs\python3.9_env\lib\site-packages\paramiko\packet.py", line 607, in _read_timeout
    x = self.__socket.recv(128)
  File "C:\Users\makhtar6\.conda\envs\python3.9_env\lib\site-packages\paramiko\proxy.py", line 119, in recv
    raise ProxyCommandFailure(" ".join(self.cmd), e.strerror)
paramiko.ssh_exception.ProxyCommandFailure: ProxyCommand("ssh -F ./ssh-config.proxy -W <ommitted>:22 jumphost") returned nonzero exit status: An operation was attempted on something that is not a socket
 
Exception in thread Thread-1:
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\makhtar6\.conda\envs\python3.9_env\lib\site-packages\paramiko\proxy.py", line 107, in recv
  File "C:\Users\makhtar6\.conda\envs\python3.9_env\lib\threading.py", line 973, in _bootstrap_inner
    r, w, x = select([self.process.stdout], [], [], select_timeout)
    self.run()
OSError: [WinError 10038] An operation was attempted on something that is not a socket
  File "C:\Users\makhtar6\.conda\envs\python3.9_env\lib\site-packages\paramiko\transport.py", line 2166, in run
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "C:\Users\makhtar6\.conda\envs\python3.9_env\lib\site-packages\netmiko\base_connection.py", line 1021, in establish_connection
    self.sock.close()
  File "C:\Users\makhtar6\.conda\envs\python3.9_env\lib\site-packages\paramiko\proxy.py", line 122, in close
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "C:\Users\makhtar6\.conda\envs\python3.9_env\lib\site-packages\paramiko\client.py", line 406, in connect
    os.kill(self.process.pid, signal.SIGTERM)
    t.start_client(timeout=timeout)
  File "C:\Users\makhtar6\.conda\envs\python3.9_env\lib\site-packages\paramiko\transport.py", line 660, in start_client
PermissionError: [WinError 5] Access is denied
    raise e
  File "C:\Users\makhtar6\.conda\envs\python3.9_env\lib\site-packages\paramiko\transport.py", line 2039, in run
    self._check_banner()
  File "C:\Users\makhtar6\.conda\envs\python3.9_env\lib\site-packages\paramiko\transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "C:\Users\makhtar6\.conda\envs\python3.9_env\lib\site-packages\paramiko\packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "C:\Users\makhtar6\.conda\envs\python3.9_env\lib\site-packages\paramiko\packet.py", line 607, in _read_timeout
    x = self.__socket.recv(128)
  File "C:\Users\makhtar6\.conda\envs\python3.9_env\lib\site-packages\paramiko\proxy.py", line 119, in recv
    raise ProxyCommandFailure(" ".join(self.cmd), e.strerror)
paramiko.ssh_exception.ProxyCommandFailure: ProxyCommand("ssh -F ./ssh-config.proxy -W <ommitted>:22 jumphost") returned nonzero exit status: An operation was attempted on something that is not a socket
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "M:\Documents\python-scripting\design-analysis\config-files\sample.py", line 43, in <module>
    with ConnectHandler(**device) as net_connect:
  File "C:\Users\makhtar6\.conda\envs\python3.9_env\lib\site-packages\netmiko\ssh_dispatcher.py", line 344, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\makhtar6\.conda\envs\python3.9_env\lib\site-packages\netmiko\base_connection.py", line 434, in __init__
    self._open()
  File "C:\Users\makhtar6\.conda\envs\python3.9_env\lib\site-packages\netmiko\base_connection.py", line 439, in _open
    self.establish_connection()
  File "C:\Users\makhtar6\.conda\envs\python3.9_env\lib\site-packages\netmiko\base_connection.py", line 1074, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.exceptions.NetmikoTimeoutException:
A paramiko SSHException occurred during connection creation:
 
ProxyCommand("ssh -F ./ssh-config.proxy -W <ommitted>:22 jumphost") returned nonzero exit status: An operation was attempted on something that is not a socket

Can someone please advise what is it that I am doing wrong, or what I need to adjust for the scenario described. Thanks.

Regards
Mash

**Comment by ktbyers** [comment]
@mashkoor7675 Can you try this fix?

https://github.com/paramiko/paramiko/pull/1924/files

This is a paramiko change.

**Comment by ktbyers** [comment]
See this issue:

https://github.com/paramiko/paramiko/issues/512

**Comment by mashkoor7675** [comment]
@ktbyers ... Tried this fix, and it has worked. Thank you very much for the guidance. Really appreciate your help.

**Comment by ktbyers** [comment]
Fix is this (unfortunately you have to patch Paramiko)

https://github.com/JulianEberius/paramiko/commit/bb1f795db46891961b6a816df3c59e132de7f211
