### ISSUE TITLE
netmiko issue with pyinstaller 

### ISSUE THREAD

**Issue by Hoaziz** [ktbyers/netmiko#287]
hello,
i created a program that SSH to a serve , it's working normally from idle
using python 3.4 and 3.5

but when converting this program to a standalone exe i get this error
any help!! 

Unknown exception: RSA is not supported by the backend
Traceback (most recent call last):
  File "site-packages\paramiko\transport.py", line 1774, in run
  File "site-packages\paramiko\kex_group1.py", line 75, in parse_next
  File "site-packages\paramiko\kex_group1.py", line 111, in _parse_kexdh_reply
  File "site-packages\paramiko\transport.py", line 1619, in _verify_key
  File "site-packages\paramiko\rsakey.py", line 58, in __init__
  File "site-packages\cryptography\hazmat\primitives\asymmetric\rsa.py", line 337, in public_key
  File "site-packages\cryptography\hazmat\backends\multibackend.py", line 157, in load_rsa_public_numbers
cryptography.exceptions.UnsupportedAlgorithm: RSA is not supported by the backend

Traceback (most recent call last):
  File "ISAM_conf.py", line 17, in <module>
  File "site-packages\netmiko\ssh_dispatcher.py", line 94, in ConnectHandler
  File "site-packages\netmiko\base_connection.py", line 88, in __init__
  File "site-packages\netmiko\base_connection.py", line 364, in establish_connection
  File "site-packages\paramiko\client.py", line 338, in connect
  File "site-packages\paramiko\transport.py", line 493, in start_client
  File "site-packages\paramiko\transport.py", line 1774, in run
  File "site-packages\paramiko\kex_group1.py", line 75, in parse_next
  File "site-packages\paramiko\kex_group1.py", line 111, in _parse_kexdh_reply
  File "site-packages\paramiko\transport.py", line 1619, in _verify_key
  File "site-packages\paramiko\rsakey.py", line 58, in __init__
  File "site-packages\cryptography\hazmat\primitives\asymmetric\rsa.py", line 337, in public_key
  File "site-packages\cryptography\hazmat\backends\multibackend.py", line 157, in load_rsa_public_numbers
cryptography.exceptions.UnsupportedAlgorithm: RSA is not supported by the backend
Failed to execute script ISAM_conf

**Comment by ktbyers** [comment]
@Hoaziz It sounds like you possibly have an install issue with the cryptography library.

Do you have these libraries installed:

```
libssl-dev and libffi-dev 
```

Also what does this give you:

```
>>> from cryptography.hazmat.backends import default_backend
>>> print default_backend()._backends
[<cryptography.hazmat.backends.openssl.backend.Backend object at 0xb6841c8c>]
```

**Comment by ktbyers** [comment]
Going to close as no response. Also doesn't look like a Netmiko issue.

Reopen if you need to.
