### ISSUE TITLE
SCP Transfer works, but OSError is raised afterwards during verify_file

### ISSUE THREAD

**Issue by David00** [ktbyers/netmiko#2897]
## Summary

I am using Netmiko's `file_transfer` function to transfer a rather large IOS image to a Cisco 9300 switch. The `file_transfer` function raises an `OSError: Socket is closed` exception from the `verify_file` function.  The image gets transferred to the switch successfully, but the Netmiko connection seems to close while the native `SCPClient.put()` (in scp.py) method is transferring the file.

I'd be happy to work on a PR if you agree that catching the OSError and re-establishing the Netmiko connection object is a viable solution to this problem.  Specifically, I'm looking at catching the OSError with try/except in lines L131, L144, and L152.

https://github.com/ktbyers/netmiko/blob/e5172291a4915598c784783e016bc5fad672f525/netmiko/scp_functions.py#L122-L157

I'm transferring `cat9k_iosxe.17.03.04.SPA.bin` - an 866 MB image file - to a Cisco 9300 series switch.  If you have a similar Cisco switch that takes large images you can test with, I've prepared a script below for you to reproduce the bug.  If you don't have access to a similar switch, feel free to reach out via the email in my profile and I will set you up with remote access to one.

## Environment:

```
$ pip freeze | grep -E "netmiko|paramiko" ; python3 -V
netmiko==4.1.2
paramiko==2.11.0
Python 3.8.10
```

## Full traceback:

```
Traceback (most recent call last):
  File "file_transfer_test.py", line 38, in <module>
    print(output)
  File "/home/david/test/venv-netmiko_4.1.2/lib/python3.8/site-packages/netmiko/scp_functions.py", line 152, in file_transfer
    if scp_transfer.verify_file():
  File "/home/david/test/venv-netmiko_4.1.2/lib/python3.8/site-packages/netmiko/scp_handler.py", line 413, in verify_file
    return self.compare_md5()
  File "/home/david/test/venv-netmiko_4.1.2/lib/python3.8/site-packages/netmiko/scp_handler.py", line 364, in compare_md5
    remote_md5 = self.remote_md5()
  File "/home/david/test/venv-netmiko_4.1.2/lib/python3.8/site-packages/netmiko/scp_handler.py", line 385, in remote_md5
    dest_md5 = self.ssh_ctl_chan._send_command_str(remote_md5_cmd, read_timeout=300)
  File "/home/david/test/venv-netmiko_4.1.2/lib/python3.8/site-packages/netmiko/base_connection.py", line 1743, in _send_command_str
    output = self.send_command(*args, **kwargs)
  File "/home/david/test/venv-netmiko_4.1.2/lib/python3.8/site-packages/netmiko/utilities.py", line 592, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/home/david/test/venv-netmiko_4.1.2/lib/python3.8/site-packages/netmiko/base_connection.py", line 1659, in send_command
    search_pattern = self._prompt_handler(auto_find_prompt)
  File "/home/david/test/venv-netmiko_4.1.2/lib/python3.8/site-packages/netmiko/base_connection.py", line 1544, in _prompt_handler
    prompt = self.find_prompt()
  File "/home/david/test/venv-netmiko_4.1.2/lib/python3.8/site-packages/netmiko/base_connection.py", line 1335, in find_prompt
    self.write_channel(self.RETURN)
  File "/home/david/test/venv-netmiko_4.1.2/lib/python3.8/site-packages/netmiko/base_connection.py", line 97, in wrapper_decorator
    return_val = func(self, *args, **kwargs)
  File "/home/david/test/venv-netmiko_4.1.2/lib/python3.8/site-packages/netmiko/base_connection.py", line 111, in wrapper_decorator
    func(self, out_data)
  File "/home/david/test/venv-netmiko_4.1.2/lib/python3.8/site-packages/netmiko/base_connection.py", line 537, in write_channel
    self.channel.write_channel(out_data)
  File "/home/david/test/venv-netmiko_4.1.2/lib/python3.8/site-packages/netmiko/channel.py", line 74, in write_channel
    self.remote_conn.sendall(write_bytes(out_data, encoding=self.encoding))
  File "/home/david/test/venv-netmiko_4.1.2/lib/python3.8/site-packages/paramiko/channel.py", line 846, in sendall
    sent = self.send(s)
  File "/home/david/test/venv-netmiko_4.1.2/lib/python3.8/site-packages/paramiko/channel.py", line 801, in send
    return self._send(s, m)
  File "/home/david/test/venv-netmiko_4.1.2/lib/python3.8/site-packages/paramiko/channel.py", line 1198, in _send
    raise socket.error("Socket is closed")
OSError: Socket is closed
```

## Steps to Reproduce

1. Download the attached script and remove the .txt extension
2. `pip install netmiko==4.1.2 python-dotenv`
3. Add your username and password to the script, or in a `.env` file, in the same directory as the script.
4. Set the IP address of your target switch in line 32.
5. Place your image file in the same directory as the script.
6. Update the image file name in line 35.
7. Run the script with `python3 file_transfer_test.py`

[file_transfer_test.py.txt](https://github.com/ktbyers/netmiko/files/9303110/file_transfer_test.py.txt)

Full Debug Log for both netmiko and paramiko:

[netmiko.log](https://github.com/ktbyers/netmiko/files/9303580/netmiko.log)

**Comment by ktbyers** [comment]
@David00 What is your VTY timeout for the SSH connection? You need to make sure the VTY timeout is longer than the SCP transfer time.

I think it would be better to avoid the disconnect, than to try and catch the error and reconnect.

**Comment by David00** [comment]
Thanks @ktbyers, it was the VTY timeout after all.  It was set to default on my switches as these are brand new switches that I'm upgrading and configuring out of the box.  I've increased the VTY timeout to several hours on my base config that the switches pull from from a DHCP option, and the verification works now.

I assumed that the SCP transfer was done over the existing Netmiko connection , but after looking at BaseFileTransfer, I see that the existing Netmiko connection is used as the SCP control connection and another SSH connection is setup using the control connection.  So, I see that the switch was closing the original SSH connection because there was no activity happening while the SCP transfer was occurring. Makes sense now!
