### ISSUE TITLE
netmiko doesn't detect the closed connection immediately

### ISSUE THREAD

**Issue by ashweeja** [ktbyers/netmiko#2911]
Hi,

I am using netmiko to test OneOs device (device_type: oneaccess_oneos) and wanted to simulate a crash. So I have rebooted the device during the execution of command.

I found paramiko raises EOF exception almost immediately after rebooting the device but netmiko could not identify this and continues to execute next command. While sending next command, netmiko identifies channel is closed and throws the exception.

So question is, should netmiko immediately identifies the exception raised by paramiko on losing the connection to device?

2022-08-22 12:06:45,988    DEBUG netmiko - read_channel:
2022-08-22 12:06:45,988    DEBUG netmiko - write_channel: b'show version\r\n'
2022-08-22 12:06:45,988    DEBUG netmiko - Pattern is: show\ version
2022-08-22 12:06:46,136    DEBUG netmiko - _read_channel_expect read_data: show version

2022-08-22 12:06:46,136    DEBUG netmiko - Pattern found: show\ version show version

2022-08-22 12:06:46,337    DEBUG netmiko - read_channel:
2022-08-22 12:06:46,537    DEBUG netmiko - read_channel:
2022-08-22 12:06:46,737    DEBUG netmiko - read_channel: Software version    : OneOS-pCPE-ARM_pi1-6.8.photo124
Software created on : 2021-10-14 13:50:53
commlib-ONE521-DUT#
commlib-ONE521-DUT#
**2022-08-22 12:07:09,617    DEBUG paramiko.transport - EOF in transport thread**
**2022-08-22 12:07:46,851    DEBUG netmiko - read_channel:**
Traceback (most recent call last):
  File "/home/oauser/ASLA///DeviceConnectivity/tests/test_crash.py", line 29, in <module>
    net_connect1.send_command("show version")
  File "/home/oauser/ASLA///lib/python3.9/site-packages/netmiko/utilities.py", line 500, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/home/oauser/ASLA///lib/python3.9/site-packages/netmiko/base_connection.py", line 1475, in send_command
    prompt = self.find_prompt(delay_factor=delay_factor)
  File "/home/oauser/ASLA///lib/python3.9/site-packages/netmiko/base_connection.py", line 1179, in find_prompt
    self.write_channel(self.RETURN)
  File "/home/oauser/ASLA///lib/python3.9/site-packages/netmiko/base_connection.py", line 459, in write_channel
    self._write_channel(out_data)
  File "/home/oauser/ASLA///lib/python3.9/site-packages/netmiko/base_connection.py", line 417, in _write_channel
    self.remote_conn.sendall(write_bytes(out_data, encoding=self.encoding))
  File "/home/oauser/ASLA///lib/python3.9/site-packages/paramiko/channel.py", line 846, in sendall
    sent = self.send(s)
  File "/home/oauser/ASLA///lib/python3.9/site-packages/paramiko/channel.py", line 801, in send
    return self._send(s, m)
  File "/home/oauser/ASLA///lib/python3.9/site-packages/paramiko/channel.py", line 1198, in _send
    raise socket.error("Socket is closed")
OSError: Socket is closed

**Comment by ktbyers** [comment]
@ashweeja Can you show the code that you were using for this test? Also which version of Netmiko are you using?

**Comment by ashweeja** [comment]
@ktbyers netmiko version is 4.0.0a4

Reproducing the issue bit involves manual effort as of now. Steps are to execute a fairly long command and reboot the device in background. 

Here is what I'm doing now,
`
net_connect1 = ConnectHandler(**DEVICE1)
net_connect1.send_command("term len 0")
net_connect1.send_command("show run", read_timeout=20) # While this command is still executing, I'm rebooting the device with reboot af 0
net_connect1.send_command("show version")
`
Below are the logs, you could see paramiko exception within 3 seconds after the command, but netmiko still fails with timeout issue after 20 seconds read_timeout is expired.

commlib-ONE521-DUT#show run
2022-08-23 06:14:03,480    DEBUG netmiko - read_channel:
...
2022-08-23 06:14:06,494    DEBUG netmiko - read_channel:
**2022-08-23 06:14:06,502**    **DEBUG paramiko.transport - EOF in transport thread**
...
2022-08-23 06:14:06,504    DEBUG netmiko - read_channel:
2022-08-23 06:14:23,080    DEBUG netmiko - read_channel:
2022-08-23 06:14:23,090    DEBUG netmiko - read_channel:
**2022-08-23 06:14:23,100**    DEBUG netmiko - read_channel:
Traceback (most recent call last):
  File "/home/oauser/ASLA//DeviceConnectivity/tests/test_crash.py", line 30, in <module>
    net_connect1.send_command("show run", read_timeout=20)
  File "/home/oauser/ASLA//lib/python3.9/site-packages/netmiko-4.0.0a4-py3.9.egg/netmiko/utilities.py", line 600, in wrapper_decorator
  File "/home/oauser/ASLA//lib/python3.9/site-packages/netmiko-4.0.0a4-py3.9.egg/netmiko/base_connection.py", line 1639, in send_command
netmiko.exceptions.ReadTimeout:
Pattern not detected: 'commlib\\-ONE521\\-DUT\\#' in output.

Things you might try to fix this:
1. Explicitly set your pattern using the expect_string argument.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.

**Comment by ktbyers** [comment]
Okay, so it looks like the issue is here (at least on the read_channel() case:

```
---> 82         if self.remote_conn.recv_ready():
     83             outbuf = self.remote_conn.recv(MAX_BUFFER)
```

This is in the read_buffer() code of the channel.py file.

So the check probably should be:

```
❱  82         if self.remote_conn.recv_ready():                                                                          
   83             outbuf = self.remote_conn.recv(MAX_BUFFER)                                                             
   84             if len(outbuf) == 0:                                                                                   
   85                 raise ReadException("Channel stream closed by remote device.")                                     
   86             output += outbuf.decode(self.encoding, "ignore")                                                       
```

Then on line 87 add:

```python
elif not self.remote_conn.transport.is_alive():
    raise SomeException(some_message)
```

Note, there could be buffered data (even if the connection/device is dead). In other words, it could be buffered on our side of the TCP stack. I just tested/verified this.

So we would first have to verify that there was no more data ready to be read (i.e. that recv_ready() was false).

**Comment by ashweeja** [comment]
@ktbyers Thanks, I have updated the channel.py as suggested by you and verified netmiko detects the connection close immediately after paramiko reports it.
