### ISSUE TITLE
Bouncing through intermediate system and having login issues to secondary hosts

### ISSUE THREAD

**Issue by rmbartis** [ktbyers/netmiko#2919]
I have session logging turned on and successfully long into a remote host, Linux-like. I then telnet into various remote hosts, one at a time. Some of the remote hosts do not seem to response to commands sent. For example the log from one of the hosts present a login prompt. The session log contains the correct response but the system does not appear to see it. Any thoughts on how to debug/resolve this issue? The command used to sent the login response to this host is
`interact.send_command('abc123', expect_string=f".*BusyBox.*|\s*#.*")`

Please note when I manually log in, as shown below, the prompt I see is "root@100:~#" . Whereas when I ask NetMiko to find the prompt I receive "#". Is that a clue to the behavior I see?

Session-log
    remote_host_prompt-ACT:~# 
    remote_host_prompt-ACT:~# telnet 100.0.1.3
    Trying 100.0.1.3...
    Connected to 100.0.1.3.
    Escape character is '^]'.
    
    MontaVista(R) Linux(R) Professional Edition 4.0.1 (0502020)
    
    Linux/ppc 2.6.10_mvl402-ml403-ppc_405
    
    
    100.0.1.3 login: abc123
    100.0.1.3 login: 

Manually performing the same steps works fine on this host
    remote_host_prompt-ACT:~# telnet 100.0.1.11
    Trying 100.0.1.11...
    Connected to 100.0.1.11.
    Escape character is '^]'.
    
    Wind River Linux 5.0.1.40 100.0.1.11
    
    100.0.1.11 login: abc123
    Last login: Fri Aug 26 22:26:08 UTC 2022 on pts/1
    root@100:~#

**Comment by ktbyers** [comment]
Try terminating your username with `\r` for the <enter>...some platforms are picky.

```
100.0.1.3 login: abc123
100.0.1.3 login: 
```

That is only for this specific issue.

You will need to write a telnet login handler or re-use Netmiko's telnet_login()

There could be other issues and you probably need to look into Netmiko's `redispatch` as what you are doing is a bit tricky.

**Comment by rmbartis** [comment]
@ktbyers - Thank you for the follow-up. I did not have access to the system recently. I checked today and the use of \r did not help the issue. telnet_login() does not appear to take an IP address and perform a login operation. From the docs what I see is shown below. I did not look at the code, but the docs seem to imply the login is missing a key parameter, namely the telnet host ID? Will take a look at the code. The device type I am using is Linux. Suggestions welcome.


 def telnet_login(self, pri_prompt_terminator: str = '#\\s*$', alt_prompt_terminator: str = '>\\s*$', username_pattern: str = '(?:user:|username|login|user name)', pwd_pattern: str = 'assword', delay_factor: float = 1.0, max_loops: int = 20) ‑> str

    Telnet login. Can be username/password or just password.

    :param pri_prompt_terminator: Primary trailing delimiter for identifying a device prompt

    :param alt_prompt_terminator: Alternate trailing delimiter for identifying a device prompt

    :param username_pattern: Pattern used to identify the username prompt

    :param delay_factor: See init: global_delay_factor

    :param max_loops: Controls the wait time in conjunction with the delay_factor

**Comment by rmbartis** [comment]
@ktbyers 

I am still stuck and looking for possible alternatives. What I do not understand is I am not asking netmiko to support telnet. I am simply asking a netmiko device=linux  using an SSH connection to run a command on the Linux host (root@ssh-host:~#), in this case, the command is telnet. If I look at the session log I can see the SSH host login is successful, its prompt confirms, root@ssh-host:~#, this. I see the telnet command is sent and the login is successful, furthermore, the hostname command that follows the successful telnet on  root@telnet-host:~# yields the expected  XYZ-abc response. It should be noted if I test for read-timout exception during the telnet login I see the timeout. If I ignore the read_timeout exception during the telnet login I see the host command sent and the response showing the telnet login was successful. In effect when I open the telnet session it is successful and commands are sent, received and responded to. Yet the read_timeout continues to be seen.  Read_timeout is set to 60-sec. command response times are <2-secs.

Based on what I observe and logically what seems to make sense the SSH session is correctly sending the requested commands and in fact, the commands are received as well as the responses. Where it appears to fall apart is the channel read_timesout. Setting the expect_prompt string to .*#.* doesn't avoid the read_timeout. Clearly, I am missing something and possibly just too ignorant about the underlying details but it seems what is being asked is fairly straightforward and should work. The logs imply it is and yet I am still stuck. Before I roll a separate driver for telnet is there something I can try to address this? Again, I do not feel I am asking Netmiko to support the telnet protocol, Linux is handling that. I am only asking the SSH session to send and receive I/O from commands sent to the SSH session. 

Last login: Mon Sep 12 14:57:26 2022 from xxx.yyy.zzz.aaa

root@ssh-host:~# 
root@ssh-host:~# date
Mon Sep 12 14:58:00 UTC 2022
root@ssh-host:~# 
root@ssh-host:~# telnet 100.0.2.1
Trying 100.0.2.1...
Connected to 100.0.2.1.
Escape character is '^]'.
Wind River Linux Base 18.44 Update 21 XYZ-abc

XYZ-abc login: root
Password: 
Last login: Fri Sep  9 23:48:26 UTC 2022 from aaa.bbb.ccc.ddd on pts/3
root@telnet-host:~#
root@telnet-host:~#hostname
Telnet Hostname: XYZ-abc
root@telnet-host:~#

**Comment by ktbyers** [comment]
Okay, your original issue indicated the telnet login was not successful on some set of hosts:

```
# From your original reported failure
MontaVista(R) Linux(R) Professional Edition 4.0.1 (0502020)

Linux/ppc 2.6.10_mvl402-ml403-ppc_405


100.0.1.3 login: abc123
100.0.1.3 login: 
```

But not you are reporting a different issue i.e. that you login successfully, but you still get a read-timeout (even though it logged in). Please correct me if I am wrong in my reading of this (as I read the above fairly quickly).

On the new read_timeout issue, I need to see the full Netmiko exception stack trace of the failure. I also need to see the section of your Python code that corresponds to the area where the exception occurs.

**Comment by rmbartis** [comment]
@ktbyers 

Thank you again for your response and my apologies for the confusion. I believe the log-in issue was a red-herring. The problem I see is that even though the login completes, ala the session log, I see a ReadTimeout exception. If I ignore the login Read_Timeout exception and can send commands, again in the session log I see the command sent and TelnetHost response in the session log, but again see the ReadTimeout. I only see this when I telnet. 

In the Code Snippet, Session log, and Exception Trace below I removed the ignore read_Timeout from the login process since it also demonstrates the issue.

Code snippet:
    cmd = f'telnet {telnet_host} -n telnet-trace.txt'
    start_secs = time.monotonic()
    try:
        output = root_shell.send_command(cmd, read_timeout=60.0, expect_string=host_prompt)
        print(f"Found telnet login prompt: {output}")
        output = root_shell.send_command('root', read_timeout=60.0, expect_string=host_prompt)

        print(f"Sent username: {output}")
        if 'Password' in output:
            # If a password prompt is presented send it now
            # Note: we are sending the root password here. Need to confirm that is what is needed
            output = root_shell.send_command(get_password('root'), read_timeout=60.0, expect_string=".*#.*")
            print(f"Found/Sent Password: {output}")
    except ReadTimeout:
        raise
    print(f"Cmd Duration: {round(time.monotonic() - start_secs, 4)}")

    try:
        # Step2 - Verify login success by reading system host name and comparing to telnet_hostname
        #       - Send hostname command
        #       - Verify telnet_hostname is in command response, else raise Telnet_Conn_Failure
        output = root_shell.send_command('hostname', read_timeout=read_timeout, expect_string=PROMPT_STRINGS['telnet'])
        prompt = output.split('\r')[1].strip()
        # Success
        return (True, telnet_host, prompt)
    except ReadTimeout:
        pass

Session Log:
Last login: Mon Sep 12 17:59:15 2022 from 135.244.36.222

root@SSH-Host:~#  
root@SSH-Host:~# date
Mon Sep 12 18:00:29 UTC 2022
root@SSH-Host:~# 
root@SSH-Host:~# telnet 100.0.2.1 -n telnet-trace.txt
Trying 100.0.2.1...
Connected to 100.0.2.1.
Escape character is '^]'.
Wind River Linux Base 18.44 Update 21 TelnetHost-2-1

TelnetHost-2-1 login: root
Password: 
Last login: Mon Sep 12 17:59:17 UTC 2022 from 100.0.81.1 on pts/2
root@TelnetHost-2-1:~# 


Exception trace:
/usr/local/bin/python3 /Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 63668 --file "/Users/bartis/Library/CloudStorage/OneDrive-Nokia/PycharmProjects/NE HealthCheck/shells/telnet.py"
warning: PYDEVD_USE_CYTHON environment variable is set to 'NO'. Frame evaluator will be also disabled because it requires Cython extensions to be enabled in order to operate correctly.
/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py:1844: DeprecationWarning: currentThread() is deprecated, use current_thread() instead
  dummy_thread = threading.currentThread()
Connected to pydev debugger (build 212.5457.59)
Found telnet login prompt: Trying 100.0.2.1...
Connected to 100.0.2.1.
Escape character is '^]'.
Wind River Linux Base 18.44 Update 21 TelnetHost-2-1

TelnetHost-2-1 login: 
Sent username: Password: 
Traceback (most recent call last):
  File "/Users/bartis/Library/CloudStorage/OneDrive-Nokia/PycharmProjects/NE HealthCheck/utils/linux/telnet.py", line 68, in telnet_login
    output = root_shell.send_command(get_password('root'), read_timeout=60.0, expect_string=".*#.*")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/netmiko/utilities.py", line 592, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/netmiko/base_connection.py", line 1671, in send_command
    new_data = self.command_echo_read(cmd=cmd, read_timeout=10)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/netmiko/base_connection.py", line 1396, in command_echo_read
    new_data = self.read_until_pattern(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/netmiko/base_connection.py", line 672, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 

Pattern not detected: 'MyPassword123' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.

**Comment by ktbyers** [comment]
You need to turn cmd_verify off, for at least this command (as the password is not actually echoed).

```python
output = root_shell.send_command(get_password('root'), read_timeout=60.0, expect_string=".#.", cmd_verify=False)
```

Netmiko, by default, will try to ensure what it sends gets properly echoed to the screen for send_command. That doesn't happen here.

**Comment by ktbyers** [comment]
Let me know if that helps (or not).

**Comment by rmbartis** [comment]
The inclusion of cmd_verify=False on an initial check appears to have addressed the problem I was having. Before I close the ticket is there a means, other than the session log to enable a deeper level of logging to gain better insight into the root cause of a failure?

**Comment by ktbyers** [comment]
This error output:

```
new_data = self.command_echo_read(cmd=cmd, read_timeout=10)
File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/netmiko/base_connection.py", line 1396, in command_echo_read
```

Was what gave me clues as to what was failing.

The `command_echo_read` is where Netmiko is expecting to see the command it sent to the CLI echoed to the screen.

I will create an issue to try to improve the readability of that error (i.e. give more assistance when that error happens).

**Comment by rmbartis** [comment]
@ktbyers 

Please let me know if I should open a new issue. I feel like I am back from whence I came, albeit with refinements to support a larger set of Hardware. The changes discussed above allowed for a much broader set of hardware support.  I am back to the original issue with a terminal located at 110.0.1.3. That terminal is unique in that its root Linux shell uses BusyBox VT102 terminal on login. I apologize if my questions are inappropriate but I and stuck on gaining insight into what is happening under the hood to aid in finding possible solutions. 

**Manual Login:**
```
SSH_Host-Terminal~# telnet 100.0.1.3
  Trying 100.0.1.3...
  Connected to 100.0.1.3.
  Escape character is '^]'.
  
  
  MontaVista(R) Linux(R) Professional Edition 4.0.1 (0502020)
  Linux/ppc 2.6.10_mvl402-ml403-ppc_405
  
  100.0.1.3 login: root
  
  
  Welcome to MontaVista(R) Linux(R) Professional Edition 4.0.1 (0502020).
  
  
  
  BusyBox v1.1.0 (2006.10.30-15:01+0000) Built-in shell (ash)
  Enter 'help' for a list of built-in commands.
  
  # tty
  /dev/pts/1
  # env
  USER=root
  LD_LIBRARY_PATH=/ffs/lib
  HOME=/root
  PS1=# 
  LOGNAME=root
  TERM=vt102
  PATH=/ffs/lib:/usr/local/bin:/usr/bin:/bin:/usr/local/dbgtools/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/bin
  SHELL=/bin/ash
  PWD=/root
```

Attempting the same with NetMiko yields a session log that implies the system is receiving the correct user login but not recognizing it.
**Session Log:**
```
SSH_Host-Terminal:~# telnet 100.0.1.3
Trying 100.0.1.3...
Connected to 100.0.1.3.
Escape character is '^]'.



MontaVista(R) Linux(R) Professional Edition 4.0.1 (0502020)

Linux/ppc 2.6.10_mvl402-ml403-ppc_405


100.0.1.3 login: root
100.0.1.3 login: 
```

**NetMiko Trace:**
```
SSH connection established to 135.104.221.65:5122
Interactive SSH session established
Traceback (most recent call last):
  File "/Users/bartis/Library/CloudStorage/OneDrive-Nokia/PycharmProjects/NE HealthCheck/shells/telnet.py", line 98, in <module>
    shell.login(shelf, slot)
  File "/Users/bartis/Library/CloudStorage/OneDrive-Nokia/PycharmProjects/NE HealthCheck/shells/telnet.py", line 67, in login
    self.login_success, self.telnet_host, self.prompt = telnet_login(self.ssh, shelf, slot, read_timeout=self.read_timeout)
  File "/Users/bartis/Library/CloudStorage/OneDrive-Nokia/PycharmProjects/NE HealthCheck/utils/linux/telnet.py", line 71, in telnet_login
    output = root_shell.send_command('root', read_timeout=read_timeout,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/netmiko/utilities.py", line 592, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/netmiko/base_connection.py", line 1721, in send_command
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 
Pattern not detected: '.*#.*|.*Password|.*BusyBox.*' in output.

Things you might try to fix this:
1. Explicitly set your pattern using the expect_string argument.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.


Telnet connection failed-Telnet login failed - Trying 100.0.1.3...
Connected to 100.0.1.3.
Escape character is '^]'.
```

**Code Snippet:**
  ```
  try:
        output = root_shell.send_command(cmd, read_timeout=read_timeout, expect_string=host_prompt, cmd_verify=False)
        # Set cmd_verify to False. By default netMiko checks for the command in the response. Since
        # the password is not Echoed back the send_command will fail with Read_Timeout exception no
        # matter how long we wait without this setting. Set prompt to look for either a root prompt or
        # Password prompt since it varies from Telnet to telnet session
        output = root_shell.send_command('root', read_timeout=read_timeout,
                                         expect_string=f"{PROMPT_STRINGS['telnet']}|.*Password|.*BusyBox.*", cmd_verify=False)
        if 'Password' in output:
            output = root_shell.send_command(get_password('root'), read_timeout=read_timeout,
                                         expect_string=f"{PROMPT_STRINGS['telnet']}|Last login.*", cmd_verify=False)
    except ReadTimeout:
        Telnet_Conn_Failure(root_shell.host, telnet_host, '', f'Telnet login failed - {output}')
        raise

    if re.search('.*Unable to connect to remote host.*', output) is not None:
        Telnet_Conn_Failure(root_shell.host, telnet_host, '', f'Telnet unable to reach client - {output}')
    elif re.search('.*could not resolve.*', output) is not None:
        Telnet_Conn_Failure(root_shell.host, telnet_host, '', f'Telnet unable to resolve address - {output}')
    else:
        # Login Success
        pass
```

**Comment by rmbartis** [comment]
BTW - I have changed the parameter response_return to \r, \n & "\r\n" to no avail.
