### ISSUE TITLE
"show admins" not a valid command for Palo Alto dedicated Log Collectors

### ISSUE THREAD

**Issue by davidwalter81** [ktbyers/netmiko#2934]
When configuring connection to a dedicated log collector (system mode: logger) the command "show admins" returns Invalid syntax when passed causing the module to fail with the following:

```
PS V:\python\python> & C:/Users/user/AppData/Local/Microsoft/WindowsApps/python3.10.exe v:/python/python/lc_ssh_netmiko.py
Traceback (most recent call last):
  File "v:\python\python\lc_ssh_netmiko.py", line 13, in <module>
    net_connect = ConnectHandler(**paloalto_lc)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\netmiko\ssh_dispatcher.py", line 365, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\netmiko\base_connection.py", line 439, in __init__
    self._open()
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\netmiko\base_connection.py", line 445, in _open
    self._try_session_preparation()
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\netmiko\base_connection.py", line 904, in _try_session_preparation
    self.session_preparation()
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\netmiko\paloalto\paloalto_panos.py", line 80, in session_preparation
    self._test_channel_read(pattern=r"Client")
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\netmiko\base_connection.py", line 1144, in _test_channel_read
    return self.read_until_pattern(pattern=pattern, read_timeout=20)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\netmiko\base_connection.py", line 672, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout:

Pattern not detected: 'Client' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.

```
The same module works as intended when connecting to a firewall or panorama appliance.

**Comment by davidwalter81** [comment]
I was able to resolve this issue by modifying paloalto_panos.py line 79-80 as follows:
`self.write_channel("show system info\n")

 self._test_channel_read(pattern=r"operational-mode")`

**Comment by vladanmilosevic73** [comment]
@ktbyers will this be added at some point - considering how small the change is

**Comment by ktbyers** [comment]
@davidwalter81 @vladanmilosevic73 Did anyone write / submit a pull-request on this? I didn't see it.

**Comment by ktbyers** [comment]
Should be fixed in #3535
