### ISSUE TITLE
"split() requires a non-empty pattern match." after writing config with "send_config_from_file()"

### ISSUE THREAD

**Issue by steenert** [ktbyers/netmiko#2936]
Hi,

We are trying to create a program to process bulk actions for our Cisco switches. We can execute show commands using the "send_command()" function just fine. But when we try to configure something with the "send_config_from_file()" function we get the following Value error: "split() requires a non-empty pattern match.".

This is the code:
```
def open_ssh_conn(ip_address,hostname,software,command_list_input,username,password,enable_password,log_dir, mode_text,script_mode):
    log("[-] [INFO] Connecting to device %s (%s)"%(hostname,ip_address)+".....")

    try:
        device_rtsw = {
            "device_type": software,
            "host": ip_address,
            "username": username,
            "password": password,
            "auth_timeout": auth_timeout,
            "secret": enable_password,
            }

        command_file = open(command_list_input, "r")
        command_file.seek(0)
    
        conn = ConnectHandler(**device_rtsw)
        conn.enable()

        file_name = hostname + "_" + current_date + "_" + mode_text +".log"
        log_file = open("log/" + "devices/" + hostname + "/" + file_name, "w+")

        if script_mode == 2:
            conn.send_config_from_file(command_list_input)
            #log_file.write(conn.send_config_from_file(command_list_input))
        else:
            for each_line in command_file.readlines():
                log_file.write("%s#%s\n"%(hostname,each_line))
                
                if re.search("% Invaldig input detected at", conn.send_command(each_line,read_timeout=1000.0)):
                    log('[-] [INFO] Invalid \"%s\" syntax on device %s' %(each_line.replace('',''),hostname))
                else:
                    log_file.write(conn.send_command(each_line,read_timeout=read_timeout))
                
        command_file.close()
        log_file.close()
        conn.disconnect()
```
Full error log:

```Traceback (most recent call last):
  File "/home/username/script1/script1.py", line 247, in <module>
    mode_selection()
  File "/home/username/script1/script1.py", line 214, in mode_selection
    change_execution_mode(script_mode, command_list_input, mode_text, device_list, log_dir, ip_address, hostname)
  File "/home/username/script1/script1.py", line 134, in change_execution_mode
    open_ssh_conn(ip_address,hostname,software,command_list_input,username,password,enable_password,log_dir, mode_text,script_mode)
  File "/home/username/script1/script1.py", line 79, in open_ssh_conn
    conn.send_config_from_file(command_list_input)
  File "/home/username/script1/.venv/lib/python3.6/site-packages/netmiko/base_connection.py", line 2024, in send_config_from_file
    return self.send_config_set(commands, **kwargs)
  File "/home/username/script1/.venv/lib/python3.6/site-packages/netmiko/base_connection.py", line 2167, in send_config_set
    output += self.read_until_pattern(pattern=re.escape(cmd.strip()))
  File "/home/username/script1/.venv/lib/python3.6/site-packages/netmiko/base_connection.py", line 615, in read_until_pattern
    results = re.split(pattern, output, maxsplit=1, flags=re_flags)
  File "/usr/lib/python3.6/re.py", line 212, in split
    return _compile(pattern, flags).split(string, maxsplit)
ValueError: split() requires a non-empty pattern match.
```

At the moment I have no clue what could be causing this. It looks like Netmiko has issues splitting the command set?
The commands executed are the following:

```
interface Gi1/0/42
description test123
```

**Comment by ktbyers** [comment]
Can you try setting `global_cmd_verify=False` as an argument to ConnectHandler?

**Comment by steenert** [comment]
This unfortunately does not seem to fix the issue. I still get the same Value error:
`split() requires a non-empty pattern match.`

**Comment by ktbyers** [comment]
Which version of Netmiko are you using?

**Comment by steenert** [comment]
> Which version of Netmiko are you using?

Version 4.0.0

**Comment by ktbyers** [comment]
What error do you now receive with `global_cmd_verify=False`?

I.e. can you post your new full exception stack (as it should be different than your previous exception).

**Comment by steenert** [comment]
```
Traceback (most recent call last):
  File "/home/username/script1/script1.py", line 248, in <module>
    mode_selection()
  File "/home/username/script1/script1.py", line 215, in mode_selection
    change_execution_mode(script_mode, command_list_input, mode_text, device_list, log_dir, ip_address, hostname)
  File "/home/username/script1/script1.py", line 135, in change_execution_mode
    open_ssh_conn(ip_address,hostname,software,command_list_input,username,password,enable_password,log_dir, mode_text,script_mode)
  File "/home/username/script1/script1.py", line 73, in open_ssh_conn
    conn = ConnectHandler(**device_rtsw)
  File "/home/username/script1/.venv/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 344, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/username/script1/.venv/lib/python3.6/site-packages/netmiko/base_connection.py", line 434, in __init__
    self._open()
  File "/home/username/script1/.venv/lib/python3.6/site-packages/netmiko/base_connection.py", line 440, in _open
    self._try_session_preparation()
  File "/home/username/script1/.venv/lib/python3.6/site-packages/netmiko/base_connection.py", line 879, in _try_session_preparation
    self.session_preparation()
  File "/home/username/script1/.venv/lib/python3.6/site-packages/netmiko/cisco/cisco_ios.py", line 20, in session_preparation
    self.disable_paging()
  File "/home/username/script1/.venv/lib/python3.6/site-packages/netmiko/base_connection.py", line 1202, in disable_paging
    output = self.read_until_prompt()
  File "/home/username/script1/.venv/lib/python3.6/site-packages/netmiko/base_connection.py", line 738, in read_until_prompt
    read_timeout=read_timeout,
  File "/home/username/script1/.venv/lib/python3.6/site-packages/netmiko/base_connection.py", line 615, in read_until_pattern
    results = re.split(pattern, output, maxsplit=1, flags=re_flags)
  File "/usr/lib/python3.6/re.py", line 212, in split
    return _compile(pattern, flags).split(string, maxsplit)
ValueError: split() requires a non-empty pattern match.

**Comment by ktbyers** [comment]
Can you upgrade to newer Netmiko and keep the `global_cmd_verify=False` and see if that fixes the issue?

You will need to use at least Python 3.7, however.

**Comment by steenert** [comment]
> Can you upgrade to newer Netmiko and keep the `global_cmd_verify=False` and see if that fixes the issue?
> 
> You will need to use at least Python 3.7, however.

Unfortunately I do not have sudo permissions on the system where the script is executed. Is there maybe a workaround for this using different Netmiko API commands?

**Comment by ktbyers** [comment]
@steenert Try doing the following:

1. Eliminate the global_cmd_verify=False setting.

2. Add:

            conn.send_config_from_file(command_list_input, cmd_verify=False)


So your device definition should look as follows:

```python
        device_rtsw = {
            "device_type": software,
            "host": ip_address,
            "username": username,
            "password": password,
            "auth_timeout": auth_timeout,
            "secret": enable_password,
            }
```

And then add that one cmd_verify argument.

Let me know if that works.

**Comment by steenert** [comment]
That seemed to do the trick! Thank you very much!
Out of curiosity, what caused the issue?

**Comment by ktbyers** [comment]
Likely the use of old Netmiko code...I think that issue is fixed in newer Netmiko.

I think there was a bug in wrapping of regex patterns in parenthesis

**Comment by steenert** [comment]
Ahh abbreviated commands, that could be it. I will use full commands in the future.
Thank you for taking the time to resolve the issue. Very useful tool!
