### ISSUE TITLE
Problem after issuing 'changeto system' Use ASA Driver

### ISSUE THREAD

**Issue by 2marshall** [ktbyers/netmiko#294]
[asa_cluster_context_download_issues.txt](https://github.com/ktbyers/netmiko/files/528312/asa_cluster_context_download_issues.txt)

```
SSH connection established to 10.84.1.14:22
Interactive SSH session established
Traceback (most recent call last):
  File "asa_cluster_context_download.py", line 80, in <module>
    net_connect.send_command('changeto system')
  File "/usr/local/lib/python2.7/dist-packages/netmiko/cisco/cisco_asa_ssh.py", line 36, in send_command
    output = super(CiscoAsaSSH, self).send_command(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 645, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: STC\-DCFW\/CHD\-01\/ADMIN\#
```

**Comment by ktbyers** [comment]
@2marshall You need to post your script as well.

**Comment by ktbyers** [comment]
Adding code inline:

```
#!/usr/bin/python
##
## Importing Required Modules
##
import getpass 
import sys 
import os 
import re
import time 
import datetime 
import fileinput 
import tftpy 
import paramiko 
import shutil 
from netmiko import ConnectHandler

##
## Prompts for Login credentials and Stores these for later use Mounts crexfs1 drive share to local crexfs1 folder
##

print '!! Enter UserName !!'
username = raw_input("Username: ")
print '!! Enter Tacacs Passwords !!'
tacacspasswd = getpass.getpass()
print '!! Enter Enable Password !!'
enablepasswd = getpass.getpass()
print '!! Enter TFTP Server IP !!'
tftpsrv = raw_input("Enter TFTP Srv IP: ")

##
## Establishing SSH Session to Node
##

with open('/sandbox/scripts/Config_Download/ASA/Cluster/hosts', 'r+') as nodelist:
        nodelistcleaned = [line.rstrip(' \t\r\n') for line in nodelist]
	for nodeip in nodelistcleaned:

		cisco_fw = {
		    'device_type': 'cisco_asa',
		    'ip': nodeip,
		    'username': username,
		    'password': password,
		    'secret': enablepass,
		    'port': 22,
		    'verbose': True,
		}

		net_connect = ConnectHandler(**cisco_fw)
		
		##
		## For Loop Iterating through each Context and Writing the Config to Flash
		##

		
		with open('/sandbox/scripts/Config_Download/ASA/Cluster/contexts', 'r+') as contextlist:
		        contextlistcleaned = [line.rstrip(' \t\r\n') for line in contextlist]
		        for context in contextlistcleaned:

		                net_connect.send_command('changeto context' + context)
				net_connect.send_command_expect('wr')		
				time.sleep(5)


		net_connect.send_command_timing('changeto system')

                with open('/sandbox/scripts/Config_Download/ASA/Cluster/contexts', 'r+') as contextlist:
                	contextlistcleaned = [line.rstrip(' \t\r\n') for line in contextlist]
                        for context in contextlistcleaned:

				##
				## Copying Config to TFTP Server
				##

				net_connect.send_command('copy disk0:/' + context + '.cfg tftp://' + tftpsrv)
				time.sleep(2)
				net_connect.send_command('\n')
                                time.sleep(2)
                                net_connect.send_command('\n')
                                time.sleep(2)
                                net_connect.send_command('\n')
                                time.sleep(2)
                                net_connect.send_command('\n')
                                time.sleep(2)


		##
		## Close SSH Transport
		##

		net_connect.disconnect()
```

**Comment by ktbyers** [comment]
Closing code + error don't match each other.
