### ISSUE TITLE
netmiko, can not connect to an accedian device

### ISSUE THREAD

**Issue by pedroolguin** [ktbyers/netmiko#2953]
Dear Mr. Byers,
I'm unable to find the issue here, works fine for cisco_ios ( with ios commands), but i'm unable to use it with accedian.
Could you please help me out!

Code:

from netmiko import ConnectHandler

```
device = { 
    "device_type": "accedian",
    "host": "",
    "username": "",
    "password": "",
    'global_delay_factor': 4
}

# Show command that we execute.
command = "board show uptime"

with ConnectHandler(**device) as net_connect:
    output = net_connect.send_command(command)

# Automatically cleans-up the output so that only the show output is returned
print()
print(output)
print()
```

```
Traceback (most recent call last):
  File "/home/usr/Desktop/ps/ac2.py", line 14, in <module>
    with ConnectHandler(**device) as net_connect:
  File "/home/usr/.local/lib/python3.8/site-packages/netmiko/ssh_dispatcher.py", line 365, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/usr/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 439, in __init__
    self._open()
  File "/home/usr/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 445, in _open
    self._try_session_preparation()
  File "/home/usr/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 904, in _try_session_preparation
    self.session_preparation()
  File "/home/usr/.local/lib/python3.8/site-packages/netmiko/accedian/accedian_ssh.py", line 9, in session_preparation
    self._test_channel_read(pattern=r"[:#]")
  File "/home/usr/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 1144, in _test_channel_read
    return self.read_until_pattern(pattern=pattern, read_timeout=20)
  File "/home/usr/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 672, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 

Pattern not detected: '[:#]' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.
```

**Comment by ktbyers** [comment]
@pedroolguin Which version of Netmiko are you using?

**Comment by pedroolguin** [comment]
Hi Kirk,

I was using version 4.1.2, I change it for version 3.0.0 and works fine!

Thank you for the highlight. 

Regards,
