### ISSUE TITLE
re.error: bad character range g-c at position 17 when use_textfsm=True

### ISSUE THREAD

**Issue by Whiney12** [ktbyers/netmiko#2962]
Hi,

I have been using Netmiko with TextFSM for years now without issues, but I am scratching my head real hard on this one.  It seems that whenever I use the "use_textfsm" option on any netmiko command, I get the following traceback error:

Python310\lib\site-packages\textfsm\copyable_regex_object.py:29: FutureWarning: Possible nested set at position 3
  self.regex = re.compile(pattern)
Python310\lib\site-packages\textfsm\copyable_regex_object.py:29: FutureWarning: Possible nested set at position 12
  self.regex = re.compile(pattern)
Traceback (most recent call last):
  File "validate_interfaces_monitoring.py", line 172, in <module>
    validate_device_interfaces_monitoring(device['IPAddress'], 'cisco_ios', sw_monitored_interfaces_list)
  File "validate_interfaces_monitoring.py", line 84, in validate_device_interfaces_monitoring
    validate_cdp_neighbors_monitoring(net_connect, netmiko_platform, monitored_interfaces_list)
  File "validate_interfaces_monitoring.py", line 97, in validate_cdp_neighbors_monitoring
    port_channels = netmiko_session.send_command(f"{port_channel_members_command[netmiko_platform]}", use_textfsm=True)
  File "Python310\lib\site-packages\netmiko\utilities.py", line 592, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "Python310\lib\site-packages\netmiko\base_connection.py", line 1729, in send_command
    return_val = structured_data_converter(
  File "Python310\lib\site-packages\netmiko\utilities.py", line 556, in structured_data_converter
    structured_output_tfsm = get_structured_data_textfsm(
  File "Python310\lib\site-packages\netmiko\utilities.py", line 378, in get_structured_data_textfsm
    textfsm_obj = clitable.CliTable(index_file, template_dir)
  File "Python310\lib\site-packages\textfsm\clitable.py", line 190, in Wrapper
    return func(main_obj, *args, **kwargs)  # pylint: disable=E1102
  File "Python310\lib\site-packages\textfsm\clitable.py", line 210, in __init__
    self.ReadIndex(index_file)
  File "Python310\lib\site-packages\textfsm\clitable.py", line 225, in ReadIndex
    self.index = IndexTable(self._PreParse, self._PreCompile, fullpath)
  File "Python310\lib\site-packages\textfsm\clitable.py", line 81, in __init__
    self._ParseIndex(preread, precompile)
  File "Python310\lib\site-packages\textfsm\clitable.py", line 143, in _ParseIndex
    row[col] = copyable_regex_object.CopyableRegexObject(row[col])
  File "Python310\lib\site-packages\textfsm\copyable_regex_object.py", line 29, in __init__
    self.regex = re.compile(pattern)
  File "Python310\lib\re.py", line 251, in compile
    return _compile(pattern, flags)
  File "Python310\lib\re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "Python310\lib\sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "Python310\lib\sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "Python310\lib\sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "Python310\lib\sre_parse.py", line 599, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
re.error: bad character range g-c at position 17

Any idea what might be causing this?  The netmiko send_command output is always correct, and I can work with it just fine if not using TextFSM, and the re.error is always the same range.

I'm running Netmiko 4.1.2 on my computer with the packaged ntc-templates.  I've already tried reinstalling the package and all dependencies, but the issue remains.

Thank you in advance!

**Comment by ktbyers** [comment]
Can you show the actual command that you are using here:

```python
port_channels = netmiko_session.send_command(f"{port_channel_members_command[netmiko_platform]}", use_textfsm=True)
```

i.e. what is the value of `{port_channel_members_command[netmiko_platform]}`

Also which Netmiko Platform are you specifying.

**Comment by Whiney12** [comment]
Hi Kirk,

Here is my variable: port_channel_members_command = {'cisco_ios': 'show etherchannel summary', 'cisco_nxos': 'show port-channel summary'}

No matter the platform, the error I get is the same.  Furthermore, no matter the command, I am always getting that same error.

**Comment by Whiney12** [comment]
Issue resolved.  It seems I had screwed up the first line in the index file in the ntc-templates folder.

**Comment by ktbyers** [comment]
@Whiney12 Glad you worked this out...as you had me a bit stumped on it.
