### ISSUE TITLE
Huawei telnet - getting ReadTimeout, but expect AuthenticationException

### ISSUE THREAD

**Issue by Toxic-Waste-** [ktbyers/netmiko#2986]
Hi guys,

I am not sure if it is related with the previous issue (#2711), but I am getting some unexpected behavior from huawei telnet login.

I was trying to improve my exception handling as sometimes, certain devices in my script will fail the first credentials I try (legacy stuff in our network), but should be able to properly process the second.

However, when I build a simple example with a connectionhandler and wrong credentials to a Huawei Router, I get a netmiko.exceptions.ReadTimeout:

```Traceback (most recent call last):
  File "/home/<snip>/devops/test-development/network/projects/firmware_tool/test.py", line 14, in <module>
    c800_connection = netmiko.ConnectHandler(**router)
  File "/home/<snip>/.local/lib/python3.10/site-packages/netmiko/ssh_dispatcher.py", line 365, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/<snip>/.local/lib/python3.10/site-packages/netmiko/base_connection.py", line 439, in __init__
    self._open()
  File "/home/<snip>/.local/lib/python3.10/site-packages/netmiko/base_connection.py", line 444, in _open
    self.establish_connection()
  File "/home/<snip>/.local/lib/python3.10/site-packages/netmiko/base_connection.py", line 1034, in establish_connection
    self.telnet_login()
  File "/home/<snip>/.local/lib/python3.10/site-packages/netmiko/huawei/huawei.py", line 155, in telnet_login
    output = self.read_until_pattern(pattern=combined_pattern)
  File "/home/<snip>/.local/lib/python3.10/site-packages/netmiko/base_connection.py", line 672, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 

Pattern not detected: "(]\\s*$|>\\s*$|(?:Change now|Please choose 'YES' or 'NO').+)" in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.
```
However, checking the session_log from the device, you can clearly see the authentication failed, so I expect this should raise the proper exception?

```
Login authentication


Username:<snip>
Password:
Error: Authentication failed.

  Error:Logged Fail!

  Please retry after 5 seconds.

Username:
```
So am I looking at this the wrong way, did I implement it the wrong way?
OS: Ubuntu 22.04.1 LTS
Netmiko: 4.1.2

Any help is appreciated :)

**Comment by Toxic-Waste-** [comment]
when I tried this same class, but changed device_type to cisco_ios_telnet and repeated the wrong credentials thing, I get the correct NetmikoAuthenticationException, so that does seem to confirm it's a problem with the Huawei telnet class?

**Comment by ktbyers** [comment]
@Toxic-Waste- Okay, yeah that is a bug, the Huawei telnet logic code is not handing the failed login correct (i.e. it should keep trying a few times and then give up with a NetmikoAuthenticationException

Basically it fails here:

[NetmikoAuthenticationException](https://github.com/ktbyers/netmiko/blob/v4.1.2/netmiko/huawei/huawei.py#L155)

And it is looking for Network OS prompt or the password change string...so when you receive `Username` again, it fails that read.

**Comment by Toxic-Waste-** [comment]
hi @ktbyers , thanks for confirming that I did it correct :) 

I'm not a good enough programmer to help solve this one, but if you need someone to test, I have plenty of huawei devices at my disposal for testing this one ^^ 

So let me know if I can help :)
