### ISSUE TITLE
Netmiko device_type for  ProCurve J4900B Switch 2626 (telnet)

### ISSUE THREAD

**Issue by ferberat** [ktbyers/netmiko#3031]
I have a Problem with ProCurve J4900B Switches. I am not able to successfully connect to Device. 
I tried some device_types: hp_procurve_telnet,aruba_procurve_telnet,cisco_ios_telnet..........
But none of them work.

Netmiko Logs: 

 _net_connect = ConnectHandler(device_type="hp_procurve_telnet", ip=ipaddr, username=var_username, password=var_password)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/share/python-venv/beispielscrips/venv/lib64/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 326, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/share/python-venv/beispielscrips/venv/lib64/python3.6/site-packages/netmiko/base_connection.py", line 350, in __init__
    self._open()
  File "/share/python-venv/beispielscrips/venv/lib64/python3.6/site-packages/netmiko/base_connection.py", line 355, in _open
    self.establish_connection()
  File "/share/python-venv/beispielscrips/venv/lib64/python3.6/site-packages/netmiko/base_connection.py", line 925, in establish_connection
    self.telnet_login()
  File "/share/python-venv/beispielscrips/venv/lib64/python3.6/site-packages/netmiko/hp/hp_procurve.py", line 188, in telnet_login
    max_loops=max_loops,
  File "/share/python-venv/beispielscrips/venv/lib64/python3.6/site-packages/netmiko/cisco_base_connection.py", line 185, in telnet_login
    raise NetmikoAuthenticationException(msg)
netmiko.ssh_exception.NetmikoAuthenticationException: Login failed: 172.19.244.98_

#########################################################
Telnet login logs:

executing command -> telnet -l {{username}} 172.19.244.98
Trying 172.19.244.98...
Connected to 172.19.244.98.
Escape character is '^]'.
ProCurve J4900B Switch 2626
Software revision H.10.119

Copyright (C) 1991-2016 Hewlett-Packard Co.  All Rights Reserved.

                           RESTRICTED RIGHTS LEGEND

 Use, duplication, or disclosure by the Government is subject to restrictions
 as set forth in subdivision (b) (3) (ii) of the Rights in Technical Data and
 Computer Software clause at 52.227-7013.

         HEWLETT-PACKARD COMPANY, 3000 Hanover St., Palo Alto, CA 94303

We'd like to keep you up to date about:
  * Software feature updates
  * New product announcements
  * Special events

Please register your products now at:  www.ProCurve.com

Press any key to continue

########   Enter   pressed      

Connecting to Tacacs server
Username:_

**Comment by ktbyers** [comment]
hp_procurve_telnet is probably the right type. It looks like the `telnet_login()` function/method is probably not handling your case for some reason.

What happens if you try:

```python
_net_connect = ConnectHandler(device_type="hp_procurve_telnet", ip=ipaddr, username=var_username, password=var_password, fast_cli=False, global_delay_factor=4)
```

**Comment by ferberat** [comment]
>>> ConnectHandler(device_type="hp_procurve_telnet", ip=ipaddr, username=var_username, password=var_password, fast_cli=False, global_delay_factor=4, session_log='netmiko_session.log')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/share/python-venv/beispielscrips/venv/lib64/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 326, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/share/python-venv/beispielscrips/venv/lib64/python3.6/site-packages/netmiko/base_connection.py", line 350, in __init__
    self._open()
  File "/share/python-venv/beispielscrips/venv/lib64/python3.6/site-packages/netmiko/base_connection.py", line 355, in _open
    self.establish_connection()
  File "/share/python-venv/beispielscrips/venv/lib64/python3.6/site-packages/netmiko/base_connection.py", line 925, in establish_connection
    self.telnet_login()
  File "/share/python-venv/beispielscrips/venv/lib64/python3.6/site-packages/netmiko/hp/hp_procurve.py", line 188, in telnet_login
    max_loops=max_loops,
  File "/share/python-venv/beispielscrips/venv/lib64/python3.6/site-packages/netmiko/cisco_base_connection.py", line 185, in telnet_login
    raise NetmikoAuthenticationException(msg)
netmiko.ssh_exception.NetmikoAuthenticationException: Login failed: 172.19.244.98

**Comment by ferberat** [comment]
[ferb@sqader009 ~]$ cat netmiko_session.log 
Software revision R.11.122















Connecting to Tacacs server
Username: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
Connecting to Tacacs server
Username: 
DEBUG:netmiko:read_channel: 






    Session Terminated, unable to login.

**Comment by ktbyers** [comment]
@ferberat Is there anything before this?

**Comment by ferberat** [comment]
Session Log:

[ferber@sqadocker009 ~]$ 
Software revision R.11.122





















    Session Terminated, unable to login.














[ferber@sqadocker009 ~]$
