### ISSUE TITLE
mac_table = net_connect.send_command("show mac address-table", use_textfsm=True) didn't work correctly

### ISSUE THREAD

**Issue by hiendinh114** [ktbyers/netmiko#3035]
Hi guys,
I am trying to export mac address table from Cisco IOS to Excel File format.
My code works with 9/10 Cisco C2960 Switches. All of model, firmware are the same. @@
Could anyone check my code? Many thank.

###My Code
import pandas as pd
from netmiko import Netmiko
from getpass import getpass
from openpyxl import load_workbook

net_connect = Netmiko(host= '10.0.10.191', username= 'admin', password= 'Cisco@123', device_type='cisco_ios')
mac_table = net_connect.send_command("show mac address-table", use_textfsm=True)
mac_data = {'mac':  [entry['destination_address'] for entry in mac_table],
            'interface': [entry['destination_port'] for entry in mac_table],
            'type': [entry['type'] for entry in mac_table],
            'vlan': [entry['vlan'] for entry in mac_table]
            }
df = pd.DataFrame(mac_data, columns=list(mac_data.keys()))

writer = pd.ExcelWriter('mac_table_v1.xlsx', engine='xlsxwriter')
df.to_excel(writer, '10.0.10.191')
writer.save()

###Error 
Traceback (most recent call last):
  File "F:\Practice\Khao sat thiet bi mang\show_mac_v1.py", line 15, in <module>
    mac_table = net_connect.send_command("show mac address-table", use_textfsm=True)
  File "P:\Python\lib\site-packages\netmiko\utilities.py", line 592, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "P:\Python\lib\site-packages\netmiko\base_connection.py", line 1729, in send_command
    return_val = structured_data_converter(
  File "P:\Python\lib\site-packages\netmiko\utilities.py", line 556, in structured_data_converter
    structured_output_tfsm = get_structured_data_textfsm(
  File "P:\Python\lib\site-packages\netmiko\utilities.py", line 379, in get_structured_data_textfsm
    output = _textfsm_parse(textfsm_obj, raw_output, attrs)
  File "P:\Python\lib\site-packages\netmiko\utilities.py", line 343, in _textfsm_parse
    tfsm_parse(raw_output, attrs)
  File "P:\Python\lib\site-packages\textfsm\clitable.py", line 282, in ParseCmd
    self.table = self._ParseCmdItem(self.raw, template_file=template_files[0])
  File "P:\Python\lib\site-packages\textfsm\clitable.py", line 315, in _ParseCmdItem
    for record in fsm.ParseText(cmd_input):
  File "P:\Python\lib\site-packages\textfsm\parser.py", line 897, in ParseText
    self._CheckLine(line)
  File "P:\Python\lib\site-packages\textfsm\parser.py", line 946, in _CheckLine
    if self._Operations(rule, line):
  File "P:\Python\lib\site-packages\textfsm\parser.py", line 1026, in _Operations
    raise TextFSMError('State Error raised. Rule Line: %s. Input Line: %s'
textfsm.parser.TextFSMError: State Error raised. Rule Line: 77. Input Line:   12    1c69.7a0d.f4e4    STATIC      Gi0/36 
[Finished in 4.1s]

**Comment by hiendinh114** [comment]
Duplicate with #3040
