### ISSUE TITLE
Hi Guys,,,I am facing issues while doing ssh connection to F5 through netmiko...

### ISSUE THREAD

**Issue by unustayyab123** [ktbyers/netmiko#3041]
Traceback (most recent call last):
  File "C:\Users\younus\PycharmProjects\unuspython\F5-connnection.py", line 9, in <module>
    ssh123 = ConnectHandler(**Device)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\younus\PycharmProjects\unuspython\venv\Lib\site-packages\netmiko\ssh_dispatcher.py", line 365, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\younus\PycharmProjects\unuspython\venv\Lib\site-packages\netmiko\base_connection.py", line 439, in __init__
    self._open()
  File "C:\Users\younus\PycharmProjects\unuspython\venv\Lib\site-packages\netmiko\base_connection.py", line 445, in _open
    self._try_session_preparation()
  File "C:\Users\younus\PycharmProjects\unuspython\venv\Lib\site-packages\netmiko\base_connection.py", line 904, in _try_session_preparation
    self.session_preparation()
  File "C:\Users\younus\PycharmProjects\unuspython\venv\Lib\site-packages\netmiko\linux\linux_ssh.py", line 23, in session_preparation
    self._test_channel_read(pattern=self.prompt_pattern)
  File "C:\Users\younus\PycharmProjects\unuspython\venv\Lib\site-packages\netmiko\base_connection.py", line 1144, in _test_channel_read
    return self.read_until_pattern(pattern=pattern, read_timeout=20)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\younus\PycharmProjects\unuspython\venv\Lib\site-packages\netmiko\base_connection.py", line 672, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 

Pattern not detected: '[\\$\\#]' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.

Need ur support to fix as i am still new to this...

**Comment by unustayyab123** [comment]
i changed to user to root and then it works..
