### ISSUE TITLE
TCP connection to device failed

### ISSUE THREAD

**Issue by Vish9729** [ktbyers/netmiko#3046]
Hi Team

I just run my program in Vs Code and i am facing error when i am going to execute it. Can you suggest me any solution for this?

My program

from napalm import get_network_driver

driver = get_network_driver("ios")
R1 = driver("192.158.59.2", "cisco", "cisco")
R1.open()

output = R1.get_facts()
print(output)
R1.close()

Got Error after execute above

PS C:\Users\vnandal\OneDrive - Cisco\Desktop\GNS\GNS_Py_Practice\Blank Project\Scripting> & "C:/Program Files/Python311/python.exe" "c:/Users/vnandal/OneDrive - Cisco/Desktop/GNS/GNS_Py_Practice/Blank Project/Scripting/ssh_8_napalm_4.py"
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\netmiko\base_connection.py", line 1046, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "C:\Program Files\Python311\Lib\site-packages\paramiko\client.py", line 349, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "C:\Program Files\Python311\Lib\site-packages\paramiko\util.py", line 279, in retry_on_signal
    return function()
           ^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\paramiko\client.py", line 349, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
                            ^^^^^^^^^^^^^^^^^^
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vnandal\AppData\Roaming\Python\Python311\site-packages\napalm\base\base.py", line 113, in _netmiko_open
    self._netmiko_device = ConnectHandler(
                           ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\netmiko\ssh_dispatcher.py", line 365, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\netmiko\base_connection.py", line 439, in __init__
    self._open()
  File "C:\Program Files\Python311\Lib\site-packages\netmiko\base_connection.py", line 444, in _open
    self.establish_connection()
  File "C:\Program Files\Python311\Lib\site-packages\netmiko\base_connection.py", line 1068, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.exceptions.NetmikoTimeoutException: TCP connection to device failed.

Common causes of this problem are:
1. Incorrect hostname or IP address.
2. Wrong TCP port.
3. Intermediate firewall blocking access.

Device settings: cisco_ios 192.158.59.2:22

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\vnandal\OneDrive - Cisco\Desktop\GNS\GNS_Py_Practice\Blank Project\Scripting\ssh_8_napalm_4.py", line 5, in <module>    R1.open()
  File "C:\Users\vnandal\AppData\Roaming\Python\Python311\site-packages\napalm\ios\ios.py", line 170, in open
    self.device = self._netmiko_open(
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vnandal\AppData\Roaming\Python\Python311\site-packages\napalm\base\base.py", line 122, in _netmiko_open
    raise ConnectionException("Cannot connect to {}".format(self.hostname))
napalm.base.exceptions.ConnectionException: Cannot connect to 192.158.59.2
PS C:\Users\vnandal\OneDrive - Cisco\Desktop\GNS\GNS_Py_Practice\Blank Project\Scripting>

Device is also pinging from my command prompt so i dont think so it is Reachability issue

C:\Users\vnandal>ping 192.168.59.2

Pinging 192.168.59.2 with 32 bytes of data:
Reply from 192.168.59.2: bytes=32 time=1ms TTL=255
Reply from 192.168.59.2: bytes=32 time=6ms TTL=255
Reply from 192.168.59.2: bytes=32 time=1ms TTL=255
Reply from 192.168.59.2: bytes=32 time=1ms TTL=255

Ping statistics for 192.168.59.2:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 1ms, Maximum = 6ms, Average = 2ms

C:\Users\vnandal>

**Comment by ktbyers** [comment]
This just looks like the SSH port is not reachable on: `192.158.59.2`

**Comment by ktbyers** [comment]
Have you verified that the SSH port is reachable from your automation machine?
