### ISSUE TITLE
OSError: Socket is closed at start of file transfer (.tar file)

### ISSUE THREAD

**Issue by 9000cats** [ktbyers/netmiko#305]
I'm building a script to upgrade IOS devices. It's a fairly heavily modified version of your asa_upgrade.py program. I will upload a .bin file without any issues (c3750e-universalk9-mz.150-2.SE10.bin), but when I try to upload a .tar file (c3750e-universalk9-tar.150-2.SE7.tar) it will error out immediately with "OSError: Socket is Closed".

```
Traceback (most recent call last):
  File "C:/Users/****/PycharmProjects/IOS Upgrade/ios_upgrade.py", line 124, in main
    scp_transfer.transfer_file()
  File "C:\Users\****\AppData\Local\Programs\Python\Python35-32\lib\site-packages\netmiko\scp_handler.py", line 179, in transfer_file
    self.scp_conn.scp_transfer_file(self.source_file, destination)
  File "C:\Users\****\AppData\Local\Programs\Python\Python35-32\lib\site-packages\netmiko\scp_handler.py", line 49, in scp_transfer_file
    self.scp_client.put(source_file, dest_file)
  File "C:\Users\****\AppData\Local\Programs\Python\Python35-32\lib\site-packages\scp.py", line 154, in put
    self._send_files(files)
  File "C:\Users\****\AppData\Local\Programs\Python\Python35-32\lib\site-packages\scp.py", line 249, in _send_files
    chan.sendall(file_hdl.read(buff_size))
  File "C:\Users\****\AppData\Local\Programs\Python\Python35-32\lib\site-packages\paramiko\channel.py", line 761, in sendall
    sent = self.send(s)
  File "C:\Users\****\AppData\Local\Programs\Python\Python35-32\lib\site-packages\paramiko\channel.py", line 715, in send
    return self._send(s, m)
  File "C:\Users\****\AppData\Local\Programs\Python\Python35-32\lib\site-packages\paramiko\channel.py", line 1075, in _send
    raise socket.error('Socket is closed')
OSError: Socket is closed
```
I've manually verified that there is enough space on the device. Is this a bug with Netmiko or SCP with handling .tar files? I'm kind of at a loss as to why bin files upload without any issues but this tar file fails.

**Comment by ktbyers** [comment]
@9000cats Can you post the relevant section of your Python code (i.e. 20 or so lines around line 124).

**Comment by 9000cats** [comment]
This is the block of code that contains line 124. It's still a work in progress. I just took the asa_upgrade code and added to it so you can handle insufficient space (delete files) and continue with the upgrade using a crude menu.

```
    # Check if file exists, check if there is enough space on the device, enable SCP, upload file, disable SCP
    with FileTransfer(ssh_conn, source_file=source_file, dest_file=dest_file,
                      file_system=dest_file_system) as scp_transfer:

        if not scp_transfer.check_file_exists():
            if not scp_transfer.verify_space_available():
                # Here we will handle insufficient space
                # We will loop and let user delete files until there is enough space
                while True:
                    output = ssh_conn.send_command("dir {0}".format(dest_file_system))
                    files = re.findall(regex_dir_w_d, output)

                    print(Fore.YELLOW + Style.BRIGHT + "Insufficient space on remote device. Choose file to delete:" + Style.RESET_ALL)

                    print("0   Don't delete any files")
                    for counter, file in enumerate(files):
                        size_MB = int(file[1]) / 1024000
                        file_name = file[2]
                        if file[0] == '-':
                            dir = ''
                        else:
                            dir = 'directory'
                        spaces = ' ' * (50 - len(file[2]) + 3)
                        print("{0}   {1}{2}{3}MB    {4}".format(counter + 1, file_name, spaces, round(size_MB, 2), dir))

                    while True:
                        option = int(input(Fore.CYAN + "Please choose an option: " + Style.RESET_ALL))
                        # Check if the option chosen is between 1 and length of files list + 1 (due to len coming up 1 short)
                        # print(list(range(1, len(files) + 1)))
                        if option in list(range(1, len(files) + 1)):
                            # Use recursive if file is a directory
                            if files[(option - 1)][0] == 'd':
                                cmd = "del /force /recursive {0}/{1}".format(dest_file_system, files[(option - 1)][2])
                            else:
                                cmd = "del /force {0}/{1}".format(dest_file_system, files[(option - 1)][2])
                            # Ask the user if they really want to delete the file
                            run_cmd = input(Fore.CYAN + "Run command: '{0}' (y/n): ".format(cmd) + Style.RESET_ALL)
                            if run_cmd == 'y':
                                output = ssh_conn.send_command(cmd)
                                print(output)
                                break
                            else:
                                # If user declines to run command to delete file then prompt for another file
                                pass
                        # If user enters 0 (don't delete any files) then raise error
                        elif option == 0:
                            raise ValueError(Fore.RED + Style.BRIGHT + "Insufficient space available on remote device" + Style.RESET_ALL)
                        else:
                            print(Fore.RED + Style.BRIGHT + "Please choose a valid option." + Style.RESET_ALL)

                    # We have gone through the menu loop and deleted a file, check space again
                    # If we have enough space the break out of loop, else check file system again and re-prompt user
                    if scp_transfer.verify_space_available():
                        break

            print(Fore.BLUE + Style.BRIGHT + "Enabling SCP" + Style.RESET_ALL)
            output = scp_handler(ssh_conn, mode='enable')
            print(output)

            print(Fore.BLUE + Style.BRIGHT + "Transferring file" + Style.RESET_ALL)
            scp_transfer.transfer_file()

            print(Fore.BLUE + Style.BRIGHT + "Disabling SCP" + Style.RESET_ALL)
            output = scp_handler(ssh_conn, mode='disable')
            print(output)

        # Verify the MD5 hash. If file already exists we will skip upload but still verify MD5.
        print(Fore.BLUE + Style.BRIGHT + "Verifying file" + Style.RESET_ALL)
        if scp_transfer.verify_file():
            print(Fore.GREEN + Style.BRIGHT + "Source and destination MD5 matches" + Style.RESET_ALL)
        else:
            raise ValueError("MD5 failure between source and destination files")
```

**Comment by ktbyers** [comment]
@9000cats I think you need to simplify your code (as a test) and just try to transfer the file. The above error indicates the SCP socket connection is closed. 

So I would try to get the SCP transfer largely by itself to work. Once you have this code working, you can start to add in your glue code.

**Comment by ktbyers** [comment]
@9000cats I am going to close this as I didn't see a response. If there is still an issue, just let me know.

**Comment by 9000cats** [comment]
This is still an issue. I noticed I can upload IOS .tar files to Cisco 3850 switches but I get the OSError Socket is Closed when uploading to Cisco 3750 switches. So this might be a hardware platform issue, or an issue with the version of IOS we're running on our 3750 switch stacks.
