### ISSUE TITLE
ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.

### ISSUE THREAD

**Issue by nimishb98** [ktbyers/netmiko#3060]
Hello,

I have two cisco routers and running an automation tool on them, I'm getting a Timed-out error intermittently on one of my routers. I have read through [#212](https://github.com/ktbyers/netmiko/issues/212) and [#1151](https://github.com/ktbyers/netmiko/issues/1151). I am not changing the hostname (however configuring the same hostname again).

**Note:** I am using Netmiko 2.1.1 Release. 

**Error Stack:**
-Fail-----2022-12-20T17-31-18.678[MainThread][star_trig_general]> Failed to load the config on Router : router1 - Timed-out reading channel, data not available.
Traceback (most recent call last):
  File "/lib/python3.6/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/lib/python3.6/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/lib/python3.6/site-packages/netmiko/base_connection.py", line 446, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/lib/python3.6/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/triggers/trig_general.py", line 253, in execute
    pxe_user_name, pxe_password, replace_config=False)
  File "/infra/utils.py", line 442, in load_config
    new_prompt='.*#', commit_str=commit_str)
  File "/devices/device.py", line 2685, in config
    return_data = self._config(cmd_list=cmd_list, handle=handle, *args, **kwargs)
  File "/devices/device.py", line 2571, in _config
    data = handle.config(cmd_list=cmd_list, *args, **kwargs)
  File "/connection/connection.py", line 999, in config
    self._end_config(**kwargs)
  File "/connection/connection.py", line 920, in _end_config
    nm_handle.exit_config_mode(exit_config=config_end_cmd, skip_check=skip_check)
  File "/lib/python3.6/site-packages/netmiko/cisco/cisco_xr.py", line 246, in exit_config_mode
    if self.check_config_mode():
  File "/lib/python3.6/site-packages/netmiko/cisco/cisco_xr.py", line 227, in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "/lib/python3.6/site-packages/netmiko/base_connection.py", line 518, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/lib/python3.6/site-packages/netmiko/base_connection.py", line 454, in _read_channel_expect
    raise NetMikoTimeoutException("Timed-out reading channel, data not available.")
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.

Can anyone please help me? Please let me know if you need more information.

Thanks

**Comment by nimishb98** [comment]
Creating a discussion topic, closing the issue.
