### ISSUE TITLE
Problems to connect a cisco xr device with netmiko in python

### ISSUE THREAD

**Issue by botarga198** [ktbyers/netmiko#3090]
Hi guys.

I already try to connect to a cisco  ios xr device my code here:

from netmiko import *

iosxr_device = {
    "device_type": "cisco_xr",
    "host": "192.168.126.123",
    "username": "x.x.x.x",
    "password": "x.x.x.x",
}

net_connect = ConnectHandler(**iosxr_device)

output = net_connect.send_command("show version")

print(output)

net_connect.disconnect()

I just have the next error I´ve been looking for a solution but I cant find it, hope you can help me.

This is the error after I  ran the script:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 931, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/local/lib/python3.8/dist-packages/paramiko/client.py", line 368, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 192.168.126.123

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "netxr.py", line 12, in <module>
    net_connect = ConnectHandler(**iosxr_device)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/ssh_dispatcher.py", line 315, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/cisco/cisco_xr.py", line 10, in __init__
    return super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 346, in __init__
    self._open()
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 351, in _open
    self.establish_connection()
  File "/usr/local/lib/python3.8/dist-packages/netmiko/cisco/cisco_xr.py", line 14, in establish_connection
    super().establish_connection(width=511, height=511)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 953, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.ssh_exception.NetmikoTimeoutException: TCP connection to device failed.

Common causes of this problem are:
1. Incorrect hostname or IP address.
2. Wrong TCP port.
3. Intermediate firewall blocking access.

Device settings: cisco_xr 192.168.126.123:22

**Comment by ktbyers** [comment]
The error above indicates the given IP address and corresponding TCP port was not reachable:

```
cisco_xr 192.168.126.123:22
```

Have you tested/verified the reachability of that SSH port on 192.168.126.123 (from your automation server)?

On its face, this doesn't look like a Netmiko issue.

**Comment by ktbyers** [comment]
I am going to close this, just let me know if you verify your connectivity to the remote device.
