### ISSUE TITLE
Palo Alto - Issue During Session Prep After Upgrade to 4.1.2

### ISSUE THREAD

**Issue by amalmborg97** [ktbyers/netmiko#3098]
Hey!

I'm working with a script that grabs some output from a Palo Alto firewall. After upgrading to 4.1.2, there seems to be an issue during session preparation and netmiko returns a NoneType object. I have confirmed that version 4.1.1 does not have this issue. 

I will go ahead and provide my code (apologies if it looks like garbage) and the netmiko_global.log file. Let me know if I can provide any more detail and/or information.

Thanks!

(Edit: the netmiko_global.log file displays operations for versions 4.1.1 and 4.1.2, in that order)

[netmiko_global.log](https://github.com/ktbyers/netmiko/files/10543790/netmiko_global.log)

```
import netmiko, re, logging

def runner(ip, device_type, credentials, commands, device_name):
    logging.basicConfig(filename="netmiko_global.log", level=logging.DEBUG)
    logger = logging.getLogger("netmiko")
    output = []
    try:
        net_connect = netmiko.ConnectHandler(
            device_type=device_type,
            host=ip,
            username=credentials[0],
            password=credentials[1],
            session_log="output.txt",
        )
        
        # Had to use regex for Palo, there has to be a better way to do this
        if device_type == "paloalto_panos":
            result = re.search("@(.*)>", net_connect.find_prompt())
            find_hostname = result.group(1)
        else:
            find_hostname = net_connect.find_prompt().replace("#", "")

        for command in commands:
            output.append(net_connect.send_command(command))
            net_connect.find_prompt()

        net_connect.disconnect()
        return output, find_hostname

    except Exception as e:
        e
```

**Comment by ktbyers** [comment]
Can you remove your try/except block and just let the exception happen (and post the full exception stack trace here):

```python
    try:
        # main code
    except Exception as e:
        e
```

So remove that try/except block and just keep the main code (so I can see the underlying stack trace). Thanks.

**Comment by amalmborg97** [comment]
Hello!

Here's the stack trace.

```
Traceback (most recent call last):
  File "c:\Users\Austin\Desktop\Python_Fun\netrun\netrun.py", line 194, in <module>
    netrun.scan("10.128.254.1", 'paloalto_panos')
  File "c:\Users\Austin\Desktop\Python_Fun\netrun\netrun.py", line 79, in scan
    raise e
  File "c:\Users\Austin\Desktop\Python_Fun\netrun\netrun.py", line 74, in scan
    results, hostname = runner.runner(device_ip, device_type, credentials, [device_version, device_model], device_name)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Austin\Desktop\Python_Fun\netrun\runner.py", line 8, in runner
    net_connect = netmiko.ConnectHandler(device_type=device_type, host=ip, username=credentials[0], password=credentials[1])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\AppData\Local\Programs\Python\Python311\Lib\site-packages\netmiko\ssh_dispatcher.py", line 365, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\AppData\Local\Programs\Python\Python311\Lib\site-packages\netmiko\base_connection.py", line 439, in __init__
    self._open()
  File "C:\Users\Austin\AppData\Local\Programs\Python\Python311\Lib\site-packages\netmiko\base_connection.py", line 445, in _open
    self._try_session_preparation()
  File "C:\Users\Austin\AppData\Local\Programs\Python\Python311\Lib\site-packages\netmiko\base_connection.py", line 904, in _try_session_preparation
    self.session_preparation()
  File "C:\Users\Austin\AppData\Local\Programs\Python\Python311\Lib\site-packages\netmiko\paloalto\paloalto_panos.py", line 72, in session_preparation
    self.set_terminal_width(
  File "C:\Users\Austin\AppData\Local\Programs\Python\Python311\Lib\site-packages\netmiko\base_connection.py", line 1260, in set_terminal_width
    output = self.read_until_pattern(pattern=pattern)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\AppData\Local\Programs\Python\Python311\Lib\site-packages\netmiko\base_connection.py", line 672, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout:

Pattern not detected: 'set cli terminal width 500' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.
```

**Comment by ktbyers** [comment]
@amalmborg97 What happens when you  execute the below command on your device:

```
set cli terminal width 500
```

Make sure you use the same permissions that you use to login.

Also can you include your session log file?

```
    session_log="output.txt",
```

**Comment by amalmborg97** [comment]
Verified permissions, here's the output:

```
Last login: Tue Jan 31 23:05:42 2023 from 10.212.212.28



Number of failed attempts since last successful login: 0


user@firewall> set cli terminal width 500
user@firewall>
```

Additionally, here's the output file from netmiko:
[output.txt](https://github.com/ktbyers/netmiko/files/10553780/output.txt)

Let me know if I can do anything else!

**Comment by ktbyers** [comment]
@amalmborg97 Can you test this fix here?

https://github.com/ktbyers/netmiko/pull/3101

**Comment by amalmborg97** [comment]
That worked like a charm!

**Comment by ktbyers** [comment]
@amalmborg97 Okay, I merged that PR so it should now be in the `develop` branch and will be included in the next Netmiko release.
