### ISSUE TITLE
IOError and slow response with send_command()

### ISSUE THREAD

**Issue by zeepi222** [ktbyers/netmiko#310]
Hi,

This symptom looks similar to #300 

I am using netmiko version 1.0.0 to configure interface parameters on a Cisco 3750 switch. 

I have no issues when using the send_config_set() method, however when using the send_command_expect() method there is a huge delay (approximately 1.5 minutes) which also results in an IOError. Based on the switch prompt, the command does appear to execute successfully.

```
>>> from netmiko import ConnectHandler
>>> ssh_session = ConnectHandler(device_type='cisco_ios', ip='192.168.96.11', username=SwLogin, password=SwPassword)
>>> ssh_session.config_mode()
u'config term\r\nEnter configuration commands, one per line.  End with CNTL/Z.\r\n3750-EXT-SW01(config)#'
>>> ssh_session.find_prompt()
u'3750-EXT-SW01(config)#'
>>> ssh_session.send_command_expect('interface Loopback0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/netmiko/base_connection.py", line 681, in send_command_expect
    return self.send_command(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/netmiko/base_connection.py", line 673, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: 3750\-EXT\-SW01\(config\)\#
>>> ssh_session.find_prompt()
u'3750-EXT-SW01(config-if)#'
>>> ssh_session.send_command('end')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/netmiko/base_connection.py", line 673, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: 3750\-EXT\-SW01\(config\-if\)\#
>>> ssh_session.find_prompt()
u'3750-EXT-SW01#'
>>> 
```

**Comment by ktbyers** [comment]
Yes, should either use send_config_set() or send_command_timing() here. The issue is that the prompt is changing when you go into interface config mode.


Kirk
