### ISSUE TITLE
Huawei VRP telnet not work

### ISSUE THREAD

**Issue by aztec102** [ktbyers/netmiko#3120]
Hello!
For almost a year now, Telnet connection on Huawei switches has been broken
```
[user@serv]$ pip3 list | grep netmiko
netmiko                      4.1.2
[user@serv]$ python -V
Python 3.10.9
```

```
ip = "10.10.10.10"
checking_device = {
            "device_type": "huawei_telnet",
            "ip": ip,
            "username": "login",
            "password": "pass",
            "port": 23,
            "verbose": True,
            "global_delay_factor": 1,
}
from netmiko import ConnectHandler
import logging
logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")
net_connect = ConnectHandler(**checking_device)
output3 = net_connect.send_command("display device")
print(output3)
```

```
/home/mikholap/.local/lib/python3.10/site-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Traceback (most recent call last):
  File "/home/mikholap/Рабочий стол/my-projects/mikholap-scripts/core and aggregation/napalm_huawei.py", line 28, in <module>
    net_connect = ConnectHandler(**checking_device)
  File "/home/mikholap/.local/lib/python3.10/site-packages/netmiko/ssh_dispatcher.py", line 365, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/mikholap/.local/lib/python3.10/site-packages/netmiko/base_connection.py", line 439, in __init__
    self._open()
  File "/home/mikholap/.local/lib/python3.10/site-packages/netmiko/base_connection.py", line 444, in _open
    self.establish_connection()
  File "/home/mikholap/.local/lib/python3.10/site-packages/netmiko/base_connection.py", line 1034, in establish_connection
    self.telnet_login()
  File "/home/mikholap/.local/lib/python3.10/site-packages/netmiko/huawei/huawei.py", line 155, in telnet_login
    output = self.read_until_pattern(pattern=combined_pattern)
  File "/home/mikholap/.local/lib/python3.10/site-packages/netmiko/base_connection.py", line 652, in read_until_pattern
    raise ReadException(msg)
netmiko.exceptions.ReadException: Unable to successfully split output based on pattern:
pattern=(]\s*$|>\s*$|(Change now|Please choose 'YES' or 'NO').+)
output=':\nInfo: The max number of VTY users is 10, and the number\n      of current VTY users on line is 1.\n      The current login time is 2023-02-17 19:48:02+07:00.\n<psw01.pnd>'
results=[':\nInfo: The max number of VTY users is 10, and the number\n      of current VTY users on line is 1.\n      The current login time is 2023-02-17 19:48:02+07:00.\n<psw01.pnd', '>', None, '']
```

**Comment by aztec102** [comment]
Hello @ktbyers.
Please take a look, I'm sure the problem is easy and lies in the regular expression. Thank you for your time.

**Comment by ktbyers** [comment]
@aztec102 Have you tried the Netmiko `develop` branch.

This PR here might be relevant to your issue (it is included in the `develop` branch)

https://github.com/ktbyers/netmiko/pull/2935

**Comment by aztec102** [comment]
@ktbyers Thank you very much for your reply and your time. I will put the develop branch - and if everything is fine there, I will close the issue itself

**Comment by aztec102** [comment]
Сlose, everything works
