### ISSUE TITLE
SNMP autodetect is broken if you feed a hostname into it.

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#3144]
Traceback (most recent call last):
  File "/home/kbyers/netmiko_course/class10/collateral/snmp_detect.py", line 9, in <module>
    my_snmp = SNMPDetect(
  File "/home/kbyers/VENV/py3_venv/src/netmiko/netmiko/snmp_autodetect.py", line 248, in __init__
    if ipaddress.ip_address(self.hostname).version == 6:
  File "/usr/local/lib/python3.9/ipaddress.py", line 53, in ip_address
    raise ValueError('%r does not appear to be an IPv4 or IPv6 address' %
ValueError: 'cisco1.lasthop.io' does not appear to be an IPv4 or IPv6 address

ipaddress.ip_address does not support a hostname here.

**Comment by ktbyers** [comment]
Relevant change that broke this:

https://github.com/ktbyers/netmiko/pull/3028

**Comment by ktbyers** [comment]
Need better testing for snmp_autodetect (would this have been caught in my standard release process)?

**Comment by kacem-expereo** [comment]
Sorry about this, indeed i actually never use hostnames when using netmiko haha..
Having a look

**Comment by kacem-expereo** [comment]
@ktbyers  sure, i will proceed with some testing on my side and move forward with a PR :)

**Comment by kacem-expereo** [comment]
It's done @ktbyers ,sorry for the delay! waiting for your comments
Kindly,

**Comment by ktbyers** [comment]
Should be fixed in this PR:

https://github.com/ktbyers/netmiko/pull/3230
