### ISSUE TITLE
send_multiline() Pattern not detected: in output.

### ISSUE THREAD

**Issue by netzen86** [ktbyers/netmiko#3152]
I'm trying to process this command with send_multiline() on the huawei ar1000v router
```shell
super password level 15 cipher
Enter Password(<8-16>):
Confirm password:
``` 
I use command set:
```python
[["super password level 15 cipher", r"<8-16>"],
 [f"{ENABLE}", r"Confirm password:"],
 [f"{ENABLE}", ""], ],
``` 
And get error:
`Pattern not detected: 'p@S\\$w0rd777' in output.`

debug output:
```shell
ThreadPoolExecutor-0_0 netmiko DEBUG: Pattern found: (super\ password\ level\ 15\ cipher) super password level 15 cipher
ThreadPoolExecutor-0_0 netmiko DEBUG: read_channel: 
Enter Password(<8-16>):
ThreadPoolExecutor-0_0 netmiko DEBUG: write_channel: b'p@S$w0rd777\n'
ThreadPoolExecutor-0_0 netmiko DEBUG: read_channel: 
ThreadPoolExecutor-0_0 netmiko DEBUG: read_channel: 
ThreadPoolExecutor-0_0 netmiko DEBUG: read_channel: 
ThreadPoolExecutor-0_0 netmiko DEBUG: read_channel: 
Confirm password:
ThreadPoolExecutor-0_0 netmiko DEBUG: read_channel: 
``` 
send_multiline() not catching "Confirm password:"

**Comment by ktbyers** [comment]
Two items--these may or may not help you:

1. You need to escape this:

```
r"<8-16>"
```

i.e. this should be 

```python
>>> print(re.escape(r"<8-16>"))
<8\-16>
```

Also you probably shouldn't use a null-string here:

```
 [f"{ENABLE}", ""], ],
```

I would hard-code something from the prompt that happens after you send the password confirmation here. Technically it probably works, but it depends on other things in your code (that you haven't shown).

**Comment by netzen86** [comment]
> 

```shell
ThreadPoolExecutor-0_0 root INFO: ===> 21:56:06.552352 Connection: 172.16.133.11 ar6120
Thread-1 paramiko.transport INFO: Connected (version 2.0, client HUAWEI-1.5)
Thread-1 paramiko.transport INFO: Authentication (password) successful!
ThreadPoolExecutor-0_0 root INFO: in if list [['super password level 15 cipher', '<8-16>'], ['p@S$w0rd777', 'Confirm password:'], ['p@S$w0rd777', '']]
Traceback (most recent call last):
  File "/Users/netzen/study/BulkConfTool/send_cmd.py", line 121, in <module>
    run_parallel_session(
  File "/Users/netzen/study/BulkConfTool/send_cmd.py", line 86, in run_parallel_session
    f.writelines(result)
  File "/Users/netzen/.pyenv/versions/3.10.8/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/Users/netzen/.pyenv/versions/3.10.8/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/Users/netzen/.pyenv/versions/3.10.8/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/Users/netzen/.pyenv/versions/3.10.8/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/netzen/.pyenv/versions/3.10.8/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/netzen/study/BulkConfTool/send_cmd.py", line 42, in send_cmd
    net_connect.send_multiline(cmd)
  File "/Users/netzen/study/BulkConfTool/netmiko/netmiko/base_connection.py", line 1848, in send_multiline
    output += self._send_command_str(
  File "/Users/netzen/study/BulkConfTool/netmiko/netmiko/base_connection.py", line 1788, in _send_command_str
    output = self.send_command(*args, **kwargs)
  File "/Users/netzen/study/BulkConfTool/netmiko/netmiko/utilities.py", line 592, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/Users/netzen/study/BulkConfTool/netmiko/netmiko/base_connection.py", line 1716, in send_command
    new_data = self.command_echo_read(cmd=cmd, read_timeout=10)
  File "/Users/netzen/study/BulkConfTool/netmiko/netmiko/base_connection.py", line 1428, in command_echo_read
    new_data = self.read_until_pattern(
  File "/Users/netzen/study/BulkConfTool/netmiko/netmiko/base_connection.py", line 690, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 

Pattern not detected: 'p@S\\$w0rd777' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.
``` 

All output when i run script.

**Comment by ktbyers** [comment]
Try passing in the argument: `cmd_verify=False`
