### ISSUE TITLE
Issue with Cisco XR and output in json

### ISSUE THREAD

**Issue by viperbmw** [ktbyers/netmiko#3157]
```
net_connect=ConnectHandler(device_type='cisco_xr', ip=IP, username=user, password=passwd,global_delay_factor=5) 
output_xr_str=net_connect.send_command('show running-config | json')
```
when I send the cmdraw='show running-config | json' I get the error below on the output from the XR saying 'Building Configuration....'

```
Traceback (most recent call last):
  File "/home/cwdavis/scripts/proxy_net_show/testing.py", line 76, in <module>
    output=show_output(device='10.44.131.202',cmdraw='show running-config | json',nos='cisco_xr',user=myuser,passwd=mypasswd)
  File "/home/cwdavis/scripts/proxy_net_show/testing.py", line 57, in show_output
    output_xr_dict=ast.literal_eval(output_xr_str)
  File "/usr/lib/python3.8/ast.py", line 59, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 3
    Building configuration...
             ^
SyntaxError: invalid syntax

```

Im not sure how to get this to work for a show run. If I specific a feature in the command such as 'show running policy-map | json' it works fine.

**Comment by viperbmw** [comment]
My Mistake
