### ISSUE TITLE
Python 3.6.8 netmiko 2.3.3 Unable to import ConnectHandler from Netmiko

### ISSUE THREAD

**Issue by RepotSirc** [ktbyers/netmiko#3182]
Please help as I am unsure what is causing this, I have downloaded the correct Netmiko version for the Python version that is allowed within my company.

**Command history**
  868  python3 -m venv venv
  869  ls
  870  source venv/bin/activate
  871  python
  872  pip install netmiko==2.3.3
  873  pip install --upgrade pip
  874  pip install netmiko==2.3.3

**(venv) [domain\user@host proj_001]$ pip list**
Package      Version
bcrypt       4.0.1
cffi         1.15.1
cryptography 40.0.2
future       0.18.3
**netmiko      2.3.3**
paramiko     3.1.0
pip          21.3.1
pycparser    2.21
PyNaCl       1.5.0
pyserial     3.5
PyYAML       6.0
scp          0.14.5
setuptools   39.2.0
six          1.16.0
textfsm      1.1.3
(venv) [domain\user@host proj_001]$ 

**(venv) [domain\user@host proj_001]$ python**
**Python 3.6.8** (default, Aug 13 2020, 07:46:32) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> 
>>> **from netmiko import ConnectHandler**
/home/domain/user/python_scripts/proj_001/venv/lib64/python3.6/site-packages/paramiko/transport.py:32: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  from cryptography.hazmat.backends import default_backend
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/domain/user/python_scripts/proj_001/venv/lib64/python3.6/site-packages/netmiko/__init__.py", line 8, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "/home/domain/user/python_scripts/proj_001/venv/lib64/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 4, in <module>
    from netmiko.a10 import A10SSH
  File "/home/domain/user/python_scripts/proj_001/venv/lib64/python3.6/site-packages/netmiko/a10/__init__.py", line 2, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "/home/domain/user/python_scripts/proj_001/venv/lib64/python3.6/site-packages/netmiko/a10/a10_ssh.py", line 4, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "/home/domain/user/python_scripts/proj_001/venv/lib64/python3.6/site-packages/netmiko/cisco_base_connection.py", line 3, in <module>
    from netmiko.base_connection import BaseConnection
  File "/home/domain/user/python_scripts/proj_001/venv/lib64/python3.6/site-packages/netmiko/base_connection.py", line 32, in <module>
    from netmiko.utilities import write_bytes, check_serial_port, get_structured_data
  File "/home/domain/user/python_scripts/proj_001/venv/lib64/python3.6/site-packages/netmiko/utilities.py", line 9, in <module>
    from netmiko._textfsm import _clitable as clitable
  File "/home/domain/user/python_scripts/proj_001/venv/lib64/python3.6/site-packages/netmiko/_textfsm/__init__.py", line 3, in <module>
    from netmiko._textfsm import _clitable
  File "/home/domain/user/python_scripts/proj_001/venv/lib64/python3.6/site-packages/netmiko/_textfsm/_clitable.py", line 34, in <module>
    import copyable_regex_object
**ModuleNotFoundError: No module named 'copyable_regex_object'**
>>> 

**I tried to install copyable_regex_object via PIP but no good**

(venv) [NBNCO\christophermendoza@SVNTF0000112EE proj_001]$ pip install copyable_regex_object
**ERROR: Could not find a version that satisfies the requirement copyable_regex_object (from versions: none)
ERROR: No matching distribution found for copyable_regex_object**
(venv) [NBNCO\christophermendoza@SVNTF0000112EE proj_001]$

**Comment by RepotSirc** [comment]
I think I got it working by **pip install textfsm==0.4.1**

**Comment by ktbyers** [comment]
@RepotSirc You really need to upgrade Netmiko. That version is crazy old and will start breaking more across time.

FYI, your Python version is end-of-lifed.

**Comment by Felipe-Dias-Mendes** [comment]
> I think I got it working by **pip install textfsm==0.4.1**

After install this, the netmiko for Python3.6.9 works. Thanks.
