### ISSUE TITLE
in _join_lingering_threads thr.stop_thread()

### ISSUE THREAD

**Issue by youngbobnetwork** [ktbyers/netmiko#3195]
netmiko==3.4.0

So I was initially having the same issue as #2855 & #2695 with using a jumpserver to SSH. This issue was resolved for me as I can now get the intended output such as 
```
show int status
``` 
However, I am getting unexpected exceptions at the end.

This is the output I get:

```
Gi1/0/1                         notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/2                         notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/3                         notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/4                         notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/5                         notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/6                         notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/7                         notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/8                         notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/9                         notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/10                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/11                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/12                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/13                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/14                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/15                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/16                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/17                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/18                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/19                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/20                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/21                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/22                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/23                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/24                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/25                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/26                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/27                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/28                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/29                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/30                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/31                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/32                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/33                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/34                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/35                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/36                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/37                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/38                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/39                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/40                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/41                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/42                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/43                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/44                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/45                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/46                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/47                        notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/48                        notconnect   1            auto   auto 10/100/1000BaseTX
Twe1/1/2                        notconnect   1            auto   auto unknown
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
Exception in thread Thread-1:
  File "C:\Users\user\Anaconda3\lib\site-packages\paramiko\transport.py", line 121, in _join_lingering_threads
Traceback (most recent call last):
    thr.stop_thread()
  File "C:\Users\user\Anaconda3\lib\site-packages\paramiko\transport.py", line 1791, in stop_thread
  File "C:\Users\user\Anaconda3\lib\threading.py", line 980, in _bootstrap_inner
    self.packetizer.close()
  File "C:\Users\user\Anaconda3\lib\site-packages\paramiko\packet.py", line 207, in close
    self.run()
    self.__socket.close()
  File "C:\Users\user\Anaconda3\lib\site-packages\paramiko\transport.py", line 2166, in run
  File "C:\Users\user\Anaconda3\lib\site-packages\paramiko\proxy.py", line 125, in close
    self.sock.close()
    os.kill(self.process.pid, signal.SIGTERM)
  File "C:\Users\user\Anaconda3\lib\site-packages\paramiko\proxy.py", line 125, in close
PermissionError: [WinError 5] Access is denied
    os.kill(self.process.pid, signal.SIGTERM)
Fatal Python error: _enter_buffered_busy: could not acquire lock for <_io.BufferedWriter name='<stderr>'> at interpreter shutdown, possibly due to daemon threads
Python runtime state: finalizing (tstate=00000199EBA163A0)

Current thread 0x0000552c (most recent call first):
<no Python frame>
```

It appears to be a threading issue? But not entirely sure.. any help would be appreciated

**Comment by ktbyers** [comment]
It doesn't look like a Netmiko issue.

**Comment by dboubeta** [comment]
It is indeed an issue in proxy.py when used in Windows. I fixed it following this post:
https://github.com/paramiko/paramiko/issues/674
