### ISSUE TITLE
netmiko ssh login issues to Cisco devices

### ISSUE THREAD

**Issue by francisjes** [ktbyers/netmiko#320]
unbale to SSH cisco devices through netmiko

>>>
>>> from netmiko import ConnectHandler
>>>
>>> Cisco_Test = {
...       'device_type': 'cisco_ios',
...       'ip': 'XXXXX',
...       'username': 'XXXX',
...       'password': 'password',
...     }
>>>
>>>
>>> net_connect = ConnectHandler(**Cisco_Test)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/netmiko/ssh_dispatcher.py", line 96, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 89, in __init__
    self.establish_connection()
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 396, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios X.X.X.X:22
>>>

**Comment by ktbyers** [comment]
@francisjes Yes, this looks like there is no device there. Did you double check by manually doing an SSH from the same box as you are running the script from?

**Comment by francisjes** [comment]
Yes am able to login the device by directly ssh into it. I just hide the IP and username in the output here.

**Comment by francisjes** [comment]
Issue been fixed. Thanks
