### ISSUE TITLE
error with netmiko and paloalto connection

### ISSUE THREAD

**Issue by esferoscar** [ktbyers/netmiko#3205]
hi guys, i am trying to run a command into paloalto fw but i get an error and skip the process. below the code i am using.

from netmiko import ConnectHandler

firewall = {
    "device_type": "paloalto_panos",
    "host": "192.168.18.8",
    "username": "admin",
    "password": "password"
}

logging.basicConfig(level=logging.DEBUG)
connection = ConnectHandler(**firewall) # unpacking the dictionary
connection.config_mode()
output = connection.send_config_set("clear session all filter application capwap")
connection.disconnect()

print(output)

in the debug i got the follow error 

DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'exit\n'
DEBUG:paramiko.transport:EOF in transport thread
Traceback (most recent call last):
  File "C:\Users\oguevara\OneDrive - Ajover S.A\Documents\conexion_pa_mad.py", line 32, in <module>
    connection = ConnectHandler(**firewall) # unpacking the dictionary
  File "C:\Users\oguevara\AppData\Local\Programs\Python\Python311\Lib\site-packages\netmiko\ssh_dispatcher.py", line 365, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\oguevara\AppData\Local\Programs\Python\Python311\Lib\site-packages\netmiko\base_connection.py", line 439, in __init__
    self._open()
  File "C:\Users\oguevara\AppData\Local\Programs\Python\Python311\Lib\site-packages\netmiko\base_connection.py", line 445, in _open
    self._try_session_preparation()
  File "C:\Users\oguevara\AppData\Local\Programs\Python\Python311\Lib\site-packages\netmiko\base_connection.py", line 904, in _try_session_preparation
    self.session_preparation()
  File "C:\Users\oguevara\AppData\Local\Programs\Python\Python311\Lib\site-packages\netmiko\paloalto\paloalto_panos.py", line 68, in session_preparation
    self._test_channel_read(pattern=r"[>#]")
  File "C:\Users\oguevara\AppData\Local\Programs\Python\Python311\Lib\site-packages\netmiko\base_connection.py", line 1144, in _test_channel_read
    return self.read_until_pattern(pattern=pattern, read_timeout=20)
  File "C:\Users\oguevara\AppData\Local\Programs\Python\Python311\Lib\site-packages\netmiko\base_connection.py", line 672, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 

Pattern not detected: '[>#]' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.

could you have any idea to fix it?

**Comment by ktbyers** [comment]
@esferoscar If you run this command from the command-line on the PA device, what does it look like?

```
clear session all filter application capwap
```

Also how long (roughly) does it take to run?

**Comment by esferoscar** [comment]
it show the answer "all session cleared"

**Comment by ktbyers** [comment]
Please show the CLI of the command (post it here):

```
Also how long (roughly) does it take to run?
```

**Comment by esferoscar** [comment]
it's right away

Using username "admin".
Last login: Tue May  9 11:33:11 2023 from 10.10.120.38

Number of failed attempts since last successful login: 0

admin@FW_CHILE> clear session all filter application capwap

sessions cleared
admin@FW_CHILE>

**Comment by ktbyers** [comment]
Try adding `fast_cli=False` to your ConnectHandler arguments and see if that helps.

**Comment by esferoscar** [comment]
already did an not changes were done, the error remains

**Comment by ktbyers** [comment]
Okay, how about both fast_cli=False and global_delay_factor=4?

And please post your updated code and updated error message.

**Comment by ktbyers** [comment]
Also which version of Netmiko are you using. You should be using Netmiko 4.2.0.
