### ISSUE TITLE
I've installed netmiko, but it looks like I can only use it with Python 2, not Python 3.

### ISSUE THREAD

**Issue by searching12** [ktbyers/netmiko#3206]
I've installed netmiko, but it looks like I can only use it with Python 2, not Python 3. 

How can I import netmiko in Python3?

~]$ python2
Python 2.7.5 (default, Apr  2 2020, 13:16:51) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import netmiko
>>> 

~]$ python3.6
Python 3.6.8 (default, Apr  2 2020, 13:34:55) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import netmiko
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'netmiko'

**Comment by searching12** [comment]
I tried to use the below syntax to install netmiko but failed.

~]$ python3.6 -m pip install netmiko 
Collecting netmiko
  Using cached https://files.pythonhosted.org/packages/14/8f/0301558593a278188b1edeabbf082b7a16d73c1bf672cf8b856068152fb6/netmiko-4.1.2-py3-none-any.whl
Collecting pyserial (from netmiko)
  Using cached https://files.pythonhosted.org/packages/07/bc/587a445451b253b285629263eb51c2d8e9bcea4fc97826266d186f96f558/pyserial-3.5-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=38.4.0 in /usr/lib/python3.6/site-packages (from netmiko)
Collecting pyyaml>=5.3 (from netmiko)
  Using cached https://files.pythonhosted.org/packages/b3/85/79b9e5b4e8d3c0ac657f4e8617713cca8408f6cdc65d2ee6554217cedff1/PyYAML-6.0-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
Collecting scp>=0.13.3 (from netmiko)
  Using cached https://files.pythonhosted.org/packages/7f/04/4bcc504e6c2fdcfee7d74a6d14a49db0f129baf2cfa19f61148f333e96b9/scp-0.14.5-py2.py3-none-any.whl
Collecting textfsm==1.1.2 (from netmiko)
  Using cached https://files.pythonhosted.org/packages/8e/74/e4f66bf3b3829e063b30501b586b1a489bd664b9066bf74650845e4c6352/textfsm-1.1.2-py2.py3-none-any.whl
Collecting ntc-templates>=2.0.0 (from netmiko)
  Using cached https://files.pythonhosted.org/packages/ba/2f/3a6b79786c45366f1207120fe493285bbcb9fb781904da855a9791a8c8d3/ntc_templates-3.1.0-py3-none-any.whl
Collecting paramiko>=2.7.2 (from netmiko)
  Using cached https://files.pythonhosted.org/packages/56/7c/9dd558ec0869fcecb661765d0a2504978dbfe85de24cbcccc847aa9b58e4/paramiko-3.1.0-py3-none-any.whl
Collecting tenacity (from netmiko)
  Using cached https://files.pythonhosted.org/packages/e7/b0/c23bd61e1b32c9b96fbca996c87784e196a812da8d621d8d04851f6c8181/tenacity-8.2.2-py3-none-any.whl
Collecting future (from textfsm==1.1.2->netmiko)
  Using cached https://files.pythonhosted.org/packages/8f/2e/cf6accf7415237d6faeeebdc7832023c90e0282aa16fd3263db0eb4715ec/future-0.18.3.tar.gz
Collecting six (from textfsm==1.1.2->netmiko)
  Using cached https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl
Collecting bcrypt>=3.2 (from paramiko>=2.7.2->netmiko)
  Using cached https://files.pythonhosted.org/packages/8c/ae/3af7d006aacf513975fd1948a6b4d6f8b4a307f8a244e1a3d3774b297aad/bcrypt-4.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    
            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install bcrypt:
    
            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-30f1iu8x/bcrypt/setup.py", line 11, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-30f1iu8x/bcrypt/

**Comment by searching12** [comment]
sudo python3 -m pip install -U pip
sudo python3 -m pip install -U setuptools

i use this solved it
