### ISSUE TITLE
exit_config_mode does not work on IOSXR with netmiko >=4.0.0

### ISSUE THREAD

**Issue by kderynski** [ktbyers/netmiko#3235]
Hello,

I have noticed recently that `exit_config_mode()` stopped working for IOSXR devices since `4.0.0` release (tested it also on newest release, last working version is `3.4.0`, all library versions tested on IOSXR `7.2.1`). During tests I have used following code snippet:

```py
commands = [
    'interface GigabitEthernet0/0/0/95',
    'shutdown',
]
with ConnectHandler(**device) as net_connect:
    output = net_connect.send_config_set(commands)
    net_connect.exit_config_mode()
```

netmiko throws an exception (debug log below):

```
DEBUG:netmiko:read_channel: RP/0/RP0/CPU0:cfr1.lab5(config)#
DEBUG:netmiko:Pattern found: (RP/0/RP0/CPU0:cfr1\.lab5.*)

Thu Jun 15 11:51:59.128 UTC
RP/0/RP0/CPU0:cfr1.lab5(config)#
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:

RP/0/RP0/CPU0:cfr1.lab5(config)#
DEBUG:netmiko:Pattern found: ([#\$])

RP/0/RP0/CPU0:cfr1.lab5(config)#
DEBUG:netmiko:write_channel: b'interface GigabitEthernet0/0/0/95\n'
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel: interface GigabitEthernet0/0/0/95


DEBUG:netmiko:Pattern found: (interface\ GigabitEthernet0/0/0/95) interface GigabitEthernet0/0/0/95
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel: RP/0/RP0/CPU0:cfr1.lab5(config-if)#
DEBUG:netmiko:Pattern found: ((?:RP/0/RP0/CPU0:cfr1\.lab5.*$|#.*$))

RP/0/RP0/CPU0:cfr1.lab5(config-if)#
DEBUG:netmiko:write_channel: b'shutdown\n'
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel: shutdown

RP/0/RP0/CPU0:cfr1.lab5(config-if)#
DEBUG:netmiko:Pattern found: (shutdown) shutdown
DEBUG:netmiko:read_channel:
DEBUG:netmiko:Pattern found: ((?:RP/0/RP0/CPU0:cfr1\.lab5.*$|#.*$))

RP/0/RP0/CPU0:cfr1.lab5(config-if)#
DEBUG:netmiko:configure terminal

Thu Jun 15 11:51:59.128 UTC
RP/0/RP0/CPU0:cfr1.lab5(config)#interface GigabitEthernet0/0/0/95

RP/0/RP0/CPU0:cfr1.lab5(config-if)#shutdown

RP/0/RP0/CPU0:cfr1.lab5(config-if)#
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:

RP/0/RP0/CPU0:cfr1.lab5(config-if)#
DEBUG:netmiko:Pattern found: ([#\$])

RP/0/RP0/CPU0:cfr1.lab5(config-if)#
DEBUG:netmiko:write_channel: b'end\n'
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel: end

Uncommitted changes found, commit them before exiting(yes/no/cancel)? [cancel]:
DEBUG:netmiko:Pattern found: (end) end
DEBUG:netmiko:read_channel:
DEBUG:netmiko:Pattern found: (Uncommitted|#$)

Uncommitted
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:


DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel: RP/0/RP0/CPU0:cfr1.lab5(config)#
DEBUG:netmiko:Pattern found: ([#\$])  changes found, commit them before exiting(yes/no/cancel)? [cancel]:

RP/0/RP0/CPU0:cfr1.lab5(config)#
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel:
DEBUG:netmiko:Pattern found: ()
DEBUG:netmiko:write_channel: b'exit\n'
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    net_connect.exit_config_mode()
  File "/home/kamild/netmiko_test/venv_4_0_0/lib/python3.7/site-packages/netmiko/cisco/cisco_xr.py", line 175, in exit_config_mode
DEBUG:paramiko.transport:EOF in transport thread
    raise ValueError("Failed to exit configuration mode")
ValueError: Failed to exit configuration mode
```
It seems that there is an easy fix for that (on listing below) however not sure if it is ok or rather `read_until_pattern` should be improved as `exit_config_mode` has not been changed for IOSXR between working version `3.4.0` and `4.0.0+`

```diff
--- a/netmiko/cisco/cisco_xr.py
+++ b/netmiko/cisco/cisco_xr.py
@@ -191,7 +191,7 @@ class CiscoXrBase(CiscoBaseConnection):
             # Read until we detect either an Uncommitted change or the end prompt
             if not re.search(r"(Uncommitted|#$)", output):
                 output += self.read_until_pattern(pattern=r"(Uncommitted|#$)")
-            if "Uncommitted changes found" in output:
+            if "Uncommitted" in output:
                 self.write_channel(self.normalize_cmd("no\n"))
                 output += self.read_until_pattern(pattern=r"[>#]")
             if not re.search(pattern, output, flags=re.M):
```
Please let me know what do you think.

Thanks!

**Comment by ktbyers** [comment]
Shouldn't you call `commit`  before you call `exit_config_mode`?
