### ISSUE TITLE
hp_procurve: Can't connect when usernames for SSH and enable differ (Failed to enter enable mode)

### ISSUE THREAD

**Issue by uhroc** [ktbyers/netmiko#3238]
To connect to my HPE ProCurve devices, I have to use different sets of username/password for the SSH connection (authenticated via radius) and the enable command (authenticated locally on the switch, username "manager"). 

When connecting to a hp_procurve device, netmiko will invoke `enable()` from `session_preparation()` in order to disable output paging. Since 55ac0b1 `enable()` defaults to the username given to ConnectHandler() instead of "manager".

While I can call `connection.enable(default_username="manager")` when enabling manually, I can't seem to influence the username used for enable in session_preparation()

The connection therefore fails as shown below:
```
Traceback (most recent call last):
  File "./test.py", line 13, in <module>
    net_connect = ConnectHandler(**dev1)
  File "/home/myusername/.local/lib/python3.8/site-packages/netmiko/ssh_dispatcher.py", line 388, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/myusername/.local/lib/python3.8/site-packages/netmiko/hp/hp_procurve.py", line 26, in __init__
    super().__init__(*args, **kwargs)
  File "/home/myusername/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 462, in __init__
    self._open()
  File "/home/myusername/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 468, in _open
    self._try_session_preparation()
  File "/home/myusername/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 963, in _try_session_preparation
    self.session_preparation()
  File "/home/myusername/.local/lib/python3.8/site-packages/netmiko/hp/hp_procurve.py", line 60, in session_preparation
    self.enable()
  File "/home/myusername/.local/lib/python3.8/site-packages/netmiko/hp/hp_procurve.py", line 132, in enable
    raise ValueError(msg)
ValueError: Failed to enter enable mode. Please ensure you pass the 'secret' argument to ConnectHandler.
```

**Comment by ktbyers** [comment]
Possible fix for this--do:

```python
try:
        # ProCurve requires elevated privileges to disable output paging :-(
        self.enable()
        self.set_terminal_width(command="terminal width 511", pattern="terminal")
        command = "no page"
        self.disable_paging(command=command)
except ValueError:
        # Log message that indicates failed to enter enable()
        pass
```

Negative is that it hides the error / the fact it didn't go into enable mode...so maybe a different pattern would be better i.e. where error happens, but there is a workaround that could be employed for people that wanted to work around it.

**Comment by uhroc** [comment]
Sorry for the late response, I kind of forgot about this after implementing a workaround (default_username="manager") for my environment on my machine and just ran into this again after switching to a new device 🤦

Your proposed solution seems to be working fine for me, would love to see this implemented.
