### ISSUE TITLE
HP Procurve enable Login failed with Radius

### ISSUE THREAD

**Issue by neodolly** [ktbyers/netmiko#3256]
Hello,
i can't connect to our HP Switch with netmiko using Radius Login. The Normal login on the Switch Works but the enable authentication failes. It works when i use local Login.

```
self.hp_switch_radius = {
               'device_type': 'hp_procurve',
                'host':  ip ,
                'username': 'user',
                'password': 'pswd',
                'port' : 22,
                'secret': 'pswd', 
            }

```

```
print(self.hp_switch_radius)
net_connect = ConnectHandler(**self.hp_switch_radius)
output = net_connect.send_command('show run',read_timeout=30)

print(str(output))
                
net_connect.disconnect()

```

DEBUG:netmiko:read_channel: HP J9627A E2620-48-PoEP Switch

DEBUG:netmiko:Pattern found: (.*opyright) HP J9627A E2620-48-PoEP Switch
Software revision RA.15.08.0009

Copyright
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: Press any key to continueVKH07SW01_10.2.65.2> 
DEBUG:netmiko:
Parenthesis found in pattern.

pattern: (any key to continue|[>#])

This can be problemtic when used in read_until_pattern().

You should ensure that you use either non-capture groups i.e. '(?:' or that the
parenthesis completely wrap the pattern '(pattern)'

DEBUG:netmiko:Pattern found: (any key to continue|[>#])  (C) 1991-2012 Hewlett-Packard Development Company, L.P.

Press any key to continue
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:Pattern found: ([>#]) VKH07SW01_10.2.65.2>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:Clear buffer detects data in the channel
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
VKH07SW01_10.2.65.2> 
DEBUG:netmiko:
Parenthesis found in pattern.

pattern: (\#|>)

This can be problemtic when used in read_until_pattern().

You should ensure that you use either non-capture groups i.e. '(?:' or that the
parenthesis completely wrap the pattern '(pattern)'
DEBUG:netmiko:Pattern found: (\#|>) 
VKH07SW01_10.2.65.2>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:Clear buffer detects data in the channel
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is VKH07SW01_10.2.65.2>
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
VKH07SW01_10.2.65.2> 
DEBUG:netmiko:Pattern found: (VKH07SW01_10\.2\.65\.2.*) 
VKH07SW01_10.2.65.2> 
DEBUG:netmiko:write_channel: b'enable\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
VKH07SW01_10.2.65.2> 
DEBUG:netmiko:
Parenthesis found in pattern.

pattern: (username|login|user name|password|[>#])

This can be problemtic when used in read_until_pattern().

You should ensure that you use either non-capture groups i.e. '(?:' or that the
parenthesis completely wrap the pattern '(pattern)'
DEBUG:netmiko:Pattern found: (username|login|user name|password|[>#]) 
VKH07SW01_10.2.65.2>
DEBUG:netmiko:
VKH07SW01_10.2.65.2>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:Clear buffer detects data in the channel
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: enable
Please Enter Login Name: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
...
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
Unable to verify password
VKH07SW01_10.2.65.2> 
DEBUG:netmiko:Pattern found: ([>#]) 
Unable to verify password
VKH07SW01_10.2.65.2>
DEBUG:netmiko:write_channel: b'logout\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: logout
Do you want to log out [y/n]? 
DEBUG:netmiko:Pattern found: (Do you want.*)  logout
Do you want to log out [y/n]? 
DEBUG:netmiko:write_channel: b'y\n'
DEBUG:paramiko.transport:EOF in transport thread

**Comment by neodolly** [comment]
Yes its because i use Radius, if change the authentication method on the switch to local it works just fine. 
It occurs on 
`net_connect = ConnectHandler(**self.hp_switch_radius)`

**Comment by ktbyers** [comment]
@neodolly Do you get an exception? Can you post your exception stack trace here?

**Comment by neodolly** [comment]
Yes i get an exception, i hope this is what you meant with the stack trace.

Traceback (most recent call last):
  File "C:\Apache24\htdocs\Testsite\Python\SSH.py", line 544, in check_test
    net_connect = ConnectHandler(**self.hp_switch_radius)
  File "C:\Program Files\Python310\lib\site-packages\netmiko\ssh_dispatcher.py", line 388, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\netmiko\hp\hp_procurve.py", line 26, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\netmiko\base_connection.py", line 462, in __init__
    self._open()
  File "C:\Program Files\Python310\lib\site-packages\netmiko\base_connection.py", line 468, in _open
    self._try_session_preparation()
  File "C:\Program Files\Python310\lib\site-packages\netmiko\base_connection.py", line 963, in _try_session_preparation
    self.session_preparation()
  File "C:\Program Files\Python310\lib\site-packages\netmiko\hp\hp_procurve.py", line 60, in session_preparation
    self.enable()
  File "C:\Program Files\Python310\lib\site-packages\netmiko\hp\hp_procurve.py", line 131, in enable
    if not self.check_enable_mode():
  File "C:\Program Files\Python310\lib\site-packages\netmiko\cisco_base_connection.py", line 15, in check_enable_mode
    return super().check_enable_mode(check_string=check_string)
  File "C:\Program Files\Python310\lib\site-packages\netmiko\base_connection.py", line 1959, in check_enable_mode
    output = self.read_until_prompt(read_entire_line=True)
  File "C:\Program Files\Python310\lib\site-packages\netmiko\base_connection.py", line 812, in read_until_prompt
    return self.read_until_pattern(
  File "C:\Program Files\Python310\lib\site-packages\netmiko\base_connection.py", line 721, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 

Pattern not detected: 'VKH07SW01_10\\.2\\.65\\.2.*' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.

**Comment by ktbyers** [comment]
@neodolly Yep, that is what I was looking for...let me look into it.

**Comment by ahewittbell** [comment]
Just bumping this one as was looking to use netmiko in a recent project.

Switch models: 2930F / M
Version 16.10.0020

Tested using radius authentication and got the exact same error. Tried python version(s) 3.8, 3.9, 3.11 on both linux & windows and was able to repeat this error on all.

Key parts from the debug:

```
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Auth banner: b'BANNER HERE'
DEBUG:paramiko.transport:EOF in transport thread
```

Traceback:

```
Traceback (most recent call last):
  File "/DIR/testing/311testing/lib64/python3.11/site-packages/netmiko/base_connection.py", line 1137, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/DIR/testing/311testing/lib64/python3.11/site-packages/paramiko/client.py", line 485, in connect
    self._auth(
  File "/DIR/testing/311testing/lib64/python3.11/site-packages/paramiko/client.py", line 818, in _auth
    raise saved_exception
  File "/DIR/testing/311testing/lib64/python3.11/site-packages/paramiko/client.py", line 805, in _auth
    self._transport.auth_password(username, password)
  File "/DIR/testing/311testing/lib64/python3.11/site-packages/paramiko/transport.py", line 1603, in auth_password
    return self.auth_handler.wait_for_response(my_event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/DIR/testing/311testing/lib64/python3.11/site-packages/paramiko/auth_handler.py", line 248, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed: transport shut down or saw EOF


Common causes of this problem are:
1. Invalid username and password
2. Incorrect SSH-key file
3. Connecting to the wrong device

Device settings: hp_procurve <ip>:22
```

Working example without radius:

```
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Auth banner: b'BANNER HERE'
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
```

**Comment by ktbyers** [comment]
On @neodolly issue, I don't really see why Netmiko does not send the username, the code looks correct (looking at). Would probably need more details, if he still wants to work on it.

**Comment by ktbyers** [comment]
@ahewittbell Your issue looks like a different issue, you should create a separate issue for it and include your full debug log and stack trace in the issue.

**Comment by uhroc** [comment]
I ran into what I believe is the same issue today:
```
Traceback (most recent call last):
  File "/home/me/my_file.py", line 26, in <module>
    connection_1 = ConnectHandler(**device)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/netmiko/ssh_dispatcher.py", line 399, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/netmiko/hp/hp_procurve.py", line 26, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/netmiko/base_connection.py", line 488, in __init__
    self._open()
  File "/usr/lib/python3/dist-packages/netmiko/base_connection.py", line 494, in _open
    self._try_session_preparation()
  File "/usr/lib/python3/dist-packages/netmiko/base_connection.py", line 988, in _try_session_preparation
    self.session_preparation()
  File "/usr/lib/python3/dist-packages/netmiko/hp/hp_procurve.py", line 62, in session_preparation
    self.enable(default_username="manager")
  File "/usr/lib/python3/dist-packages/netmiko/hp/hp_procurve.py", line 133, in enable
    if not self.check_enable_mode():
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/netmiko/cisco_base_connection.py", line 15, in check_enable_mode
    return super().check_enable_mode(check_string=check_string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/netmiko/base_connection.py", line 1993, in check_enable_mode
    output = self.read_until_prompt(read_entire_line=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/netmiko/base_connection.py", line 837, in read_until_prompt
    return self.read_until_pattern(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/netmiko/base_connection.py", line 746, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout:

Pattern not detected: 'switch\\-hostname\\-redacted.*' in output.
```

After some troubleshooting I found the problem to be that the read buffer contains a not-yet-read `devicename>` prompt before the `Username:` when [hp_procurve.py line 103](https://github.com/ktbyers/netmiko/blob/ae10899fc037c45b237cebeb73a37d2098b26ef9/netmiko/hp/hp_procurve.py#L103) is executed. So it's effectively setting `new_output="devicename>"`, `re.search(username_pattern, new_output [...])` in line 108 evaluates to false and the if-block sending the user name is never executed.

Adding `self.clear_buffer(delay_factor=0.2)` at line 100 fixed this for me (delay_factor not set or delay_factor=0.1 did not work, so maybe 0.3 or 0.5 might be better to account for slight timing differences).
