### ISSUE TITLE
Dell OS10 v. 10.5.4.4 Pattern not detected: 'show lldp neighbors interface ethernet 1/1/10 detail' in output

### ISSUE THREAD

**Issue by marcelo-lopez** [ktbyers/netmiko#3262]
Hi, I am having this issue only with Dell OS10 10.5.4.4 in a script where I send
conn.send_command("show lldp neighbors interface ethernet 1/1/13 detail | grep \"Remote System Name\"")
and it fails with: 

conn.send_command("show lldp neighbors interface ethernet 1/1/25 detail", read_timeout=60)
Traceback (most recent call last):
  File "<pyshell#24>", line 1, in <module>
    conn.send_command("show lldp neighbors interface ethernet 1/1/25 detail", read_timeout=60)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\utilities.py", line 592, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 1671, in send_command
    new_data = self.command_echo_read(cmd=cmd, read_timeout=10)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 1396, in command_echo_read
    new_data = self.read_until_pattern(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 672, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 

Pattern not detected: 'show\\ lldp\\ neighbors\\ interface\\ ethernet\\ 1/1/25\\ detail' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.

--------------------------------------------------------------------------------------------------------
I have tried with send_config_set and send_command_expect as someone suggested.

conn.send_command("show lldp neighbors interface ethernet 1/1/13 detail | grep \"Remote System Name\"")
It works just fine with every other flavor of the OS10, as far as I can tell. 

If I type the command directly in the switch's console it also works correctly.

Any help will be greatly appreciated.

Name: netmiko
Version: 4.1.2

Dell EMC Networking OS10 Enterprise
OS Version: 10.5.4.4
Build Version: 10.5.4.4.193

P.S. I updated to Netmiko 4.2.0 with the same result.

from netmiko import ConnectHandler; conn = ConnectHandler(device_type="autodetect",ip="10.143.26.146", username="admin", password="admin")
conn.send_command("show lldp neighbors interface ethernet 1/1/12 detail | grep \"Remote System Name\"")
Traceback (most recent call last):
  File "<pyshell#32>", line 1, in <module>
    conn.send_command("show lldp neighbors interface ethernet 1/1/12 detail | grep \"Remote System Name\"")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\utilities.py", line 592, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 1671, in send_command
    :param cmd_verify: Verify command echo before proceeding (default: True).
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 1396, in command_echo_read
    # Initial read
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 672, in read_until_pattern
netmiko.exceptions.ReadTimeout: 

Pattern not detected: 'show\\ lldp\\ neighbors\\ interface\\ ethernet\\ 1/1/12\\ detail\\ \\|\\ grep\\ "Remote\\ System\\ Name"' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.

**Comment by marcelo-lopez** [comment]
I replaced "send_command" for "send_command_timing" and it is working now.  :)
