### ISSUE TITLE
Netmiko ciena issue

### ISSUE THREAD

**Issue by maximegy** [ktbyers/netmiko#3268]
Hello All,
We are currently writing a script with netmiko to connect to ciena saos devices and send a bunch of commands.
Normally we connect with the command `ssh -o PubKeyAuthentication=no user@ciena`

We wrote this code :
```
from netmiko import (
ciena,
)
cpeIp = "ciena"
cpePassword = "ertyuiop123"

cpeSshSession = ciena.CienaSaosSSH(
  device_type="ciena_saos",
  ip=cpeIp,
  username="user",
  password=cpePassword,
  global_delay_factor= 3,
  timeout= 20,
  ssh_config_file= False,
  allow_agent= False,
  use_keys= False,
  verbose=True,
  default_enter= '\n',
)
try:
  output = cpeSshSession.find_prompt()
  output += cpeSshSession.send_command("port show status") print(output)
except: 
  print("ça marche pas poto")
cpeSshSession.disconnect()
```

But, this is not working, we have the following output :
```
SSH connection established to ciena:22
Interactive SSH session established Traceback (most recent call last): File "/home/./ciena.py", line 46, in <module> cpeSshSession = ciena.CienaSaosSSH( File "/home/.env/lib/python3.9/site-packages/netmiko/base_connection.py", line 462, in init self._open() File "/home/.env/lib/python3.9/site-packages/netmiko/base_connection.py", line 468, in _open self._try_session_preparation() File "/home/.env/lib/python3.9/site-packages/netmiko/base_connection.py", line 963, in _try_session_preparation self.session_preparation() File "/home/.env/lib/python3.9/site-packages/netmiko/ciena/ciena_saos.py", line 39, in session_preparation self.set_base_prompt() File "/home/.env/lib/python3.9/site-packages/netmiko/ciena/ciena_saos.py", line 32, in set_base_prompt raise ValueError(f"Router prompt not found: {repr(prompt)}") ValueError: Router prompt not found: 'CIENA-XXXXX>'
```

Anybody can help ?
Thanks a lot.

**Comment by ktbyers** [comment]
I didn't see any Ciena specific changes between 4.1.2 and 4.2.0.

What happens if you try the below code?

```python
from netmiko import ConnectHandler

cpeIp = "ciena"
cpePassword = password

cpeSshSession = ConnectHandler(
  device_type="ciena_saos",
  ip=cpeIp,
  username="user",
  password=cpePassword,
)

output = cpeSshSession.find_prompt()
output += cpeSshSession.send_command("port show status") 
print(output)
```

**Comment by ktbyers** [comment]
@maximegy Can you add a session_log and post its contents here (for the failing code you just posted):

```
cpeSshSession = ConnectHandler(
  device_type="ciena_saos",
  ip=cpeIp,
  username="user",
  password=cpePassword,
  session_log="output.txt",          # add this line--this will create a file named "output.txt" in current directory.
)
```

**Comment by Rikharms1972** [comment]
Hello, I have the same issue with Ciena, but not with other vendors.

>>> cpeSshSession = ConnectHandler(
...   device_type="ciena_saos",
...   ip="CIENAHOST",
...   username="rharms",
...   password="PASSWORD",
...   session_log="output.txt"
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rharms/.local/lib/python3.8/site-packages/netmiko/ssh_dispatcher.py", line 388, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/rharms/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 462, in __init__
    self._open()
  File "/home/rharms/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 468, in _open
    self._try_session_preparation()
  File "/home/rharms/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 963, in _try_session_preparation
    self.session_preparation()
  File "/home/rharms/.local/lib/python3.8/site-packages/netmiko/ciena/ciena_saos.py", line 39, in session_preparation
    self.set_base_prompt()
  File "/home/rharms/.local/lib/python3.8/site-packages/netmiko/ciena/ciena_saos.py", line 32, in set_base_prompt
    raise ValueError(f"Router prompt not found: {repr(prompt)}")
ValueError: Router prompt not found: 'CIENAHOST>'

I tested the above and the log shows:

SAOS is True Carrier Ethernet TM software.

Welcome to the shell.
CIENAHOST> 
CIENAHOST> 
CIENAHOST>

also, a debug shows:

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
SAOS is True Carrier Ethernet TM software.

Welcome to the shell.

DEBUG:netmiko:read_channel: CIENAHOST> 
CIENAHOST> 
DEBUG:netmiko:Pattern found: ([>#$]) 

SAOS is True Carrier Ethernet TM software.

Welcome to the shell.
CIENAHOST>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:Clear buffer detects data in the channel
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
MND-RC0002-DS519> 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is CIENAHOST>
DEBUG:paramiko.transport:EOF in transport thread

Downgraded to 4.1.2 and all works fine again.

**Comment by ktbyers** [comment]
@Rikharms1972 

In your above log the prompt is sometimes:

`CIENAHOST>` 

and then sometimes:

`MND-RC0002-DS519>`

why did it change (or is the log just not correct)?

**Comment by ullasdewan** [comment]
Hello
Was able to trace issue in line 31 of the file
 /usr/local/lib/python3.10/dist-packages/netmiko/ciena/ciena_saos.py
It should be as follows
if re.search(pattern, prompt) == None:

Post that issue was resolved. 
@ktbyers may be this change needs to be checked in

**Comment by dodgerbluetx** [comment]
> Hello Was able to trace issue in line 31 of the file /usr/local/lib/python3.10/dist-packages/netmiko/ciena/ciena_saos.py It should be as follows if re.search(pattern, prompt) == None:
> 
> Post that issue was resolved. @ktbyers may be this change needs to be checked in

Any update on a fix? I am experiencing the same issue. The proposed fix in the comment from @ullasdewan works in my case.

**Comment by ktbyers** [comment]
@dodgerbluetx Do you want to submit a pull request on it.

**Comment by PaperbagLife** [comment]
Seems like this is fixed by #3214 ? Can close the issue?
