### ISSUE TITLE
nornir netmiko.exceptions.ReadTimeout

### ISSUE THREAD

**Issue by kielmoreland** [ktbyers/netmiko#3277]
Good afternoon,

Python version: 3.10.12
Nornir version: 3.3.0
Netmiko version: 4.1.2
Napalm version: 4.1.0

Back in April 2022, an issues was reported, [cisco_ios - device hostname > 20 characters causes ReadTimeout exception](https://github.com/ktbyers/netmiko/issues/2718). While I see the above post that this should have been fixed [#2720](https://github.com/ktbyers/netmiko/pull/2720), the reason I ask is that I am getting a very similar Netmiko error when I am attempting to execute a Nornir runbook:

```
from nornir import InitNornir
from nornir_utils.plugins.functions import print_result
from nornir_napalm.plugins.tasks import napalm_get

nr = InitNornir (
    config_file="config.yml", dry_run=True
)

results = nr.run (
    task=napalm_get, getters=["facts"]
)

print_result(results)
```
When I execute this runbook against my physical infrastructure, I receive the following error:

```
(nornir) kielmoreland@kielmoreland-Aspire-R5-571T:~/Desktop/nornir$ python nornir_get_facts.py
napalm_get**********************************************************************
* Moreland-2960X-Core-sw1 ** changed : False ***********************************
vvvv napalm_get ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv ERROR
Traceback (most recent call last):
  File "/home/kielmoreland/Desktop/nornir/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/kielmoreland/Desktop/nornir/lib/python3.10/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "/home/kielmoreland/Desktop/nornir/lib/python3.10/site-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/home/kielmoreland/Desktop/nornir/lib/python3.10/site-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/home/kielmoreland/Desktop/nornir/lib/python3.10/site-packages/nornir_napalm/plugins/connections/__init__.py", line 57, in open
    connection.open()
  File "/home/kielmoreland/Desktop/nornir/lib/python3.10/site-packages/napalm/ios/ios.py", line 172, in open
    self.device = self._netmiko_open(
  File "/home/kielmoreland/Desktop/nornir/lib/python3.10/site-packages/napalm/base/base.py", line 129, in _netmiko_open
    self._netmiko_device.enable()
  File "/home/kielmoreland/Desktop/nornir/lib/python3.10/site-packages/netmiko/cisco_base_connection.py", line 26, in enable
    return super().enable(
  File "/home/kielmoreland/Desktop/nornir/lib/python3.10/site-packages/netmiko/base_connection.py", line 2008, in enable
    output += self.read_until_prompt()
  File "/home/kielmoreland/Desktop/nornir/lib/python3.10/site-packages/netmiko/base_connection.py", line 812, in read_until_prompt
    return self.read_until_pattern(
  File "/home/kielmoreland/Desktop/nornir/lib/python3.10/site-packages/netmiko/base_connection.py", line 721, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 

Pattern not detected: 'Moreland\\-2960X\\-C' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.



^^^^ END napalm_get ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
* Moreland-LVR-sw1 ** changed : False ******************************************
vvvv napalm_get ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv ERROR
Traceback (most recent call last):
  File "/home/kielmoreland/Desktop/nornir/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/kielmoreland/Desktop/nornir/lib/python3.10/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "/home/kielmoreland/Desktop/nornir/lib/python3.10/site-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/home/kielmoreland/Desktop/nornir/lib/python3.10/site-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/home/kielmoreland/Desktop/nornir/lib/python3.10/site-packages/nornir_napalm/plugins/connections/__init__.py", line 57, in open
    connection.open()
  File "/home/kielmoreland/Desktop/nornir/lib/python3.10/site-packages/napalm/ios/ios.py", line 172, in open
    self.device = self._netmiko_open(
  File "/home/kielmoreland/Desktop/nornir/lib/python3.10/site-packages/napalm/base/base.py", line 129, in _netmiko_open
    self._netmiko_device.enable()
  File "/home/kielmoreland/Desktop/nornir/lib/python3.10/site-packages/netmiko/cisco_base_connection.py", line 26, in enable
    return super().enable(
  File "/home/kielmoreland/Desktop/nornir/lib/python3.10/site-packages/netmiko/base_connection.py", line 2008, in enable
    output += self.read_until_prompt()
  File "/home/kielmoreland/Desktop/nornir/lib/python3.10/site-packages/netmiko/base_connection.py", line 812, in read_until_prompt
    return self.read_until_pattern(
  File "/home/kielmoreland/Desktop/nornir/lib/python3.10/site-packages/netmiko/base_connection.py", line 721, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 

Pattern not detected: 'Moreland\\-LVR\\-sw1' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.



^^^^ END napalm_get ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(nornir) kielmoreland@kielmoreland-Aspire-R5-571T:~/Desktop/nornir$ ^C
```
I have seen some individuals suggesting that giving "false" to `fast_cli` in the `groups.yml` file and I have done so:

```
# Nornir groups file
---
moreland_network:
  platform: ios
  connection_options:
    napalm:
      extras:
        optional_args:
          fast_cli: False
```
Therefore, I am at a bit of a loss, and any assistance that may be rendered would be appreciated.

**Comment by ktbyers** [comment]
@kielmoreland The error indicates you are failing to go into `enable` mode.

You potentially need to add a `secret` argument:

```yaml
my_group:
  platform: nxos
  connection_options:
    napalm:
      extras:
        optional_args:
          fast_cli: False
          secret: my_secret
```

**Comment by kielmoreland** [comment]
Good afternoon, @ktbyers ,

Thank you for the quick response concerning this issue.

Pay dirt.  That did the trick.  I would not have guessed that, but it is working.

Now I am going to start working on having it prompt for username, SSH password, and enable password because (1) for security reasons I do not like embedded passwords in my config files/scripts in general, and (2) my organization greatly (greatly) frowns upon it.  While I've been using Ansible, it's my hope to start using Nornir as well.
