### ISSUE TITLE
how to set value "self._test_channel_read(pattern=r"[>#]")"

### ISSUE THREAD

**Issue by Jayzhang1995** [ktbyers/netmiko#3349]
### Description of Issue/Question

Just for backup device configuration in everyday，use superuser is insecure，I create one readonly  users。

Use privilege is readonly user login the  ruijie Firewalls，command line output is **”RG-WALL $ “**（superuser is **”RG-WALL #**），“ but  the default pattern is  "**self._test_channel_read(pattern=r"[>#]")** "  in ruijie_os.py .

 How to customize pattern value in ” **ConnectHandler(**self.value)**“ ？

### Netmiko version
 
```
netmiko               4.2.0
```

### Netmiko device_type (if relevant to the issue)
(Paste `device_type` between quotes below)

```
ruijie_os
```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
RG-WALL $ 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'exit\n'
Traceback (most recent call last):
  File "/Users/jay/Documents/Worker/Gitlab/switch_backup/device_backup.py", line 91, in <module>
    raise e
  File "/Users/jay/Documents/Worker/Gitlab/switch_backup/device_backup.py", line 89, in <module>
    devs_bak.backup()
  File "/Users/jay/Documents/Worker/Gitlab/switch_backup/device_backup.py", line 72, in backup
    self.connect()
  File "/Users/jay/Documents/Worker/Gitlab/switch_backup/device_backup.py", line 42, in connect
    conn =  ConnectHandler(**self.value).read_until_prompt_or_pattern(pattern=r"[>#]")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jay/Documents/Worker/Gitlab/switch_backup/.venv/lib/python3.11/site-packages/netmiko/ssh_dispatcher.py", line 388, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jay/Documents/Worker/Gitlab/switch_backup/.venv/lib/python3.11/site-packages/netmiko/base_connection.py", line 462, in __init__
    self._open()
  File "/Users/jay/Documents/Worker/Gitlab/switch_backup/.venv/lib/python3.11/site-packages/netmiko/base_connection.py", line 468, in _open
    self._try_session_preparation()
  File "/Users/jay/Documents/Worker/Gitlab/switch_backup/.venv/lib/python3.11/site-packages/netmiko/base_connection.py", line 964, in _try_session_preparation
    self.session_preparation()
  File "/Users/jay/Documents/Worker/Gitlab/switch_backup/.venv/lib/python3.11/site-packages/netmiko/ruijie/ruijie_os.py", line 11, in session_preparation
    self._test_channel_read(pattern=r"[>#]")
  File "/Users/jay/Documents/Worker/Gitlab/switch_backup/.venv/lib/python3.11/site-packages/netmiko/base_connection.py", line 1203, in _test_channel_read
    return self.read_until_pattern(pattern=pattern, read_timeout=20)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jay/Documents/Worker/Gitlab/switch_backup/.venv/lib/python3.11/site-packages/netmiko/base_connection.py", line 722, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 

Pattern not detected: '[>#]' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.
```

### Relevant Python code
(Please try to essentialize your Python code to the minimum code needed to reproduce the issue)
(Paste the code between the quotes below)

```
python3.11.4

```

**Comment by ktbyers** [comment]
@Jayzhang1995 Is there something unusual about your setup or the `$` normal for ruijie_os.py.

Your output somewhat looks like a Linux shell--is that correct (or is this just the network operating system)?

**Comment by Jayzhang1995** [comment]
> @Jayzhang1995 Is there something unusual about your setup or the `$` normal for ruijie_os.py.
> 
> Your output somewhat looks like a Linux shell--is that correct (or is this just the network operating system)?

1. Device model is `RG-WALL 1600 X8600` ，if login as admin is `RG-WALL #` ,else `RG-WALL $`,I think is Developed based on linux。
2. I setup  `$` for ruijie_os.py， result in below, I can't find this key `(\\#|>)` 

<img width="1046" alt="image" src="https://github.com/ktbyers/netmiko/assets/24266745/ba51f48a-bb3e-449d-968b-ce5ee7609d58">
<img width="716" alt="image" src="https://github.com/ktbyers/netmiko/assets/24266745/9a468edd-0ff5-4921-9dd1-9f23febc6812">
<img width="988" alt="image" src="https://github.com/ktbyers/netmiko/assets/24266745/c7cabce4-9329-4bcb-9608-7ebabcbfa5be">

3. Change device_type to  `linux`, can't parse mutil paging , how to change the code ?
<img width="1101" alt="image" src="https://github.com/ktbyers/netmiko/assets/24266745/c5ecddca-664a-4173-bd78-f040363946d4">
<img width="582" alt="image" src="https://github.com/ktbyers/netmiko/assets/24266745/7934c90b-df34-4440-9041-f391bb7e5708">

**Comment by Jayzhang1995** [comment]
1.` send_command` change to ` send_command_timing` function 
2. `RG-WALL 1600 X8600` device_type chose `linux`
is work for me,  close issue
