### ISSUE TITLE
TypeError: getaddrinfo() argument 1 must be string or None

### ISSUE THREAD

**Issue by ahmedaljawad** [ktbyers/netmiko#336]
Trying a simple code below , and getting the error( please see below ) . any idea please ? 

######
mport netmiko
import json

Devices='''
192.168.80.10
192.168.80.10
'''.strip().splitlines()
device_type = 'cisco_ios'
username = 'admin'
password = 'auto'

for device in Devices:
    connection = netmiko.ConnectHandler(ip=Devices, device_type=device_type, username=username, password=password)
    print(connection.send_command('show ip int br'))
    print(connection.send_command('sh clock'))
#########

Getting the error below 

C:\Python27\python.exe C:/Users/JAWADAHM/PycharmProjects/Automate/Comand_loader.py
Traceback (most recent call last):
  File "C:/Users/JAWADAHM/PycharmProjects/Automate/Comand_loader.py", line 13, in <module>
    connection = netmiko.ConnectHandler(ip=Devices, device_type=device_type, username=username, password=password)
  File "C:\Python27\lib\site-packages\netmiko\ssh_dispatcher.py", line 96, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 89, in __init__
    self.establish_connection()
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 392, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "C:\Python27\lib\site-packages\paramiko\client.py", line 296, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "C:\Python27\lib\site-packages\paramiko\client.py", line 200, in _families_and_addresses
    addrinfos = socket.getaddrinfo(hostname, port, socket.AF_UNSPEC, socket.SOCK_STREAM)
TypeError: getaddrinfo() argument 1 must be string or None

Process finished with exit code 1

**Comment by ktbyers** [comment]
@ahmedaljawad 
You passed in the list 'Devices' and not the individual 'device'.

```
for device in Devices:
    connection = netmiko.ConnectHandler(ip=Devices, device_type=device_type, username=username, password=password)
```

**Comment by ahmedaljawad** [comment]
Thank you ! yes you are right . I notice that after i posted this . all good thank you for your reply
