### ISSUE TITLE
Mrv ConnectHandler enable passwrd Error

### ISSUE THREAD

**Issue by Workasis** [ktbyers/netmiko#3368]
### Description of Issue/Question
```
The switch is protected with a password when entering enable mode but the "secret" variable is not working.
The same emabel password works when I try manually.

This result in session_log file:
SWITCHMRV> enable
Password:
Password:
Password: exit

```
### Netmiko version

```
netmiko==3.1.1
```

### Netmiko device_type

```
mrv_optiswitch
```

### Error Traceback

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mrv.py", line 72, in <module>
    guesser = ConnectHandler(**host)
  File "/usr/local/lib/python3.8/site-packages/netmiko/ssh_dispatcher.py", line 266, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 327, in __init__
    self._open()
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 333, in _open
    self._try_session_preparation()
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 756, in _try_session_preparation
    self.session_preparation()
  File "/usr/local/lib/python3.8/site-packages/netmiko/mrv/mrv_ssh.py", line 15, in session_preparation
    self.enable()
  File "/usr/local/lib/python3.8/site-packages/netmiko/mrv/mrv_ssh.py", line 30, in enable
    if not self.check_enable_mode():
  File "/usr/local/lib/python3.8/site-packages/netmiko/cisco_base_connection.py", line 14, in check_enable_mode
    return super().check_enable_mode(check_string=check_string)
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 1544, in check_enable_mode
    output = self.read_until_prompt()
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 623, in read_until_prompt
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 560, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

```

### Relevant Python code

```python
host = {
    'device_type': 'mrv_optiswitch',
    'ip': ip, 
    'username': user, 
    'password': passwd,
    "secret": enable_passwd,
    'port': 22,
    'session_log': 'output.txt',
}

con = ConnectHandler(**host)
print(con.send_command("show version"))
```

**Comment by Workasis** [comment]
Not need
