### ISSUE TITLE
Incompatible ssh peer (no acceptable host key)

### ISSUE THREAD

**Issue by SeasLiV** [ktbyers/netmiko#3381]
### Description

I'm facing "Incompatible ssh peer (no acceptable host key)" while trying to reach a network device (cisco 9800).
As far as I can see at the device level, the only SSH host key algorithm available are sha2-256 and -512.

I've been trying to use global_delay_factor or disabled_algorithms but I still don't get how can I "force" the algorithm ? Is such thing possible ?

### Netmiko version

```
4.3.0
```

### Netmiko device_type

```
autodetect
```

### Error Traceback

```
Exception: Incompatible ssh peer (no acceptable host key)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/paramiko/transport.py", line 2083, in run
    self._handler_table[ptype](self, m)
  File "/usr/local/lib/python3.8/site-packages/paramiko/transport.py", line 2198, in _negotiate_keys
    self._parse_kex_init(m)
  File "/usr/local/lib/python3.8/site-packages/paramiko/transport.py", line 2377, in _parse_kex_init
    raise SSHException(
paramiko.ssh_exception.SSHException: Incompatible ssh peer (no acceptable host key)
```

### Relevant Python code
Here is the minimal version of my script. I've been trying multiple combinaison without any luck.

```python
    remote_device = {'device_type': 'autodetect', 'host': ip, 'username': username, 'password': password, 'conn_timeout': 45, "banner_timeout": 30, 'global_delay_factor': 2 }
    guesser = SSHDetect(**remote_device)
    best_match = guesser.autodetect()
    print(best_match)
```

also tried that

```python
remote_device = {'device_type': 'autodetect', 'host': ip, 'username': username, 'password': password, 'conn_timeout': 45, "banner_timeout": 30, "disabled_algorithms": {'pubkeys': ['ssh-rsa', 'ssh-ed25519', 'ecdsa-sha2-nistp521', 'ecdsa-sha2-nistp384', 'ecdsa-sha2-nistp256']}}
```

I know this is more or less related to paramiko (obviously) but is there anything I can do at the netmiko configuration level ? This is driving me crazy !

Thanks in advance,

**Comment by ktbyers** [comment]
For future people that find this issue:

Add the following to your device dictionary:

```python
"disable_sha2_fix": True,
```

This should implement the Paramiko disabled algorithms fix.

**Comment by jhuttie** [comment]
I had this happen to me too on a Dell Powerconnect 5548. Turns out, there was no rsa key generated on the switch. Once I generate a key for it, I no longer had that error
