### ISSUE TITLE
netmiko.exceptions.NetmikoTimeoutException: Paramiko: 'No existing session' error: try increasing 'conn_timeout' to 15 seconds or larger.

### ISSUE THREAD

**Issue by SaeedFazlollahzadeh** [ktbyers/netmiko#3386]
### Description of Issue/Question

*Note*: Please check https://guides.github.com/features/mastering-markdown/
to see how to properly format your request.

### Netmiko version
(Paste verbatim output from `pip freeze | grep netmiko` between quotes below)

```
netmiko==4.3.0
```

### Netmiko device_type (if relevant to the issue)
(Paste `device_type` between quotes below)

There's no issue with `device_type`.

### Steps to Reproduce the Issue

1. This is my python code if I use password authentication:
```
from netmiko import ConnectHandler

cisco1 = {
    "device_type": "cisco_ios",
    "host": "192.168.1.1",
    "username": "myUserName",
    'password': 'myPassword',
    'timeout': 60
}

with ConnectHandler(**cisco1) as net_connect:
    output = net_connect.send_command("show ip arp")

print(output)
```
Output:
```
Protocol  Address          Age (min)  Hardware Addr   Type   Interface
Internet  192.168.2.2           14    aaaa.aaaa.aaaa  ARPA   GigabitEthernet1/0/1
Internet  192.168.2.1            -    bbbb.bbbb.bbbb  ARPA   GigabitEthernet1/0/1
```
But this is my code if I use key authentication:
```
from netmiko import ConnectHandler

key_file = "/root/.ssh/id_rsa"
cisco1 = {
    "device_type": "cisco_ios",
    "host": "192.168.1.1",
    "username": "myUserName",
    "use_keys": True,
    "key_file": key_file,
    'timeout': 60
}

with ConnectHandler(**cisco1) as net_connect:
    output = net_connect.send_command("show ip arp")
```
But I can SSH via bash CLI with no issue and it works fine.

This is my `/root/.ssh/confg` file:
```
Host switch
    HostName 192.168.1.1
    User myUserName
    IdentityFile /root/.ssh/id_rsa
    KexAlgorithms +diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
    Ciphers aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc
```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
Traceback (most recent call last):
  File "/home/python3.10/venv/lib/python3.10/site-packages/netmiko/base_connection.py", line 1137, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/python3.10/venv/lib/python3.10/site-packages/paramiko/client.py", line 485, in connect
    self._auth(
  File "/home/python3.10/venv/lib/python3.10/site-packages/paramiko/client.py", line 818, in _auth
    raise saved_exception
  File "/home/python3.10/venv/lib/python3.10/site-packages/paramiko/client.py", line 794, in _auth
    self._transport.auth_publickey(username, key)
  File "/home/python3.10/venv/lib/python3.10/site-packages/paramiko/transport.py", line 1664, in auth_publickey
    raise SSHException("No existing session")
paramiko.ssh_exception.SSHException: No existing session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/python3.10/venv/lib/python3.10/site-packages/netmiko/ssh_dispatcher.py", line 399, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/python3.10/venv/lib/python3.10/site-packages/netmiko/base_connection.py", line 488, in __init__
    self._open()
  File "/home/python3.10/venv/lib/python3.10/site-packages/netmiko/base_connection.py", line 493, in _open
    self.establish_connection()
  File "/home/python3.10/venv/lib/python3.10/site-packages/netmiko/base_connection.py", line 1182, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.exceptions.NetmikoTimeoutException: Paramiko: 'No existing session' error: try increasing 'conn_timeout' to 15 seconds or larger.
```

### Relevant Python code
(Please try to essentialize your Python code to the minimum code needed to reproduce the issue)
(Paste the code between the quotes below)

```python
from netmiko import ConnectHandler

key_file = "/root/.ssh/id_rsa"
cisco1 = {
    "device_type": "cisco_ios",
    "host": "192.168.1.1",
    "username": "myUserName",
    "use_keys": True,
    "key_file": key_file,
    'timeout': 60
}

with ConnectHandler(**cisco1) as net_connect:
    output = net_connect.send_command("show ip arp")
```
How can I connect to my Cisco switch while I have no issue in the bash?

**Comment by ktbyers** [comment]
Netmiko doesn't use any of this by default (it doesn't use openSSH). 


```
Host switch
    HostName 192.168.1.1
    User myUserName
    IdentityFile /root/.ssh/id_rsa
    KexAlgorithms +diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
    Ciphers aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc
```

SSH config file processing is very limited in Netmiko and mostly for what is needed for SSH proxy support.

You probably would need to look at the Netmiko log file and see what is failing the SSH key authentication process.

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md

**Comment by chrisinmtown** [comment]
I'm joining the conversation here trying to get ideas how to cope with this failure. I'm using Python 3.12 and Netmiko v4.7.0. This failure happens *occasionally* on a Juniper router, I have not found a way to reproduce it. My little app connects 10 times perfectly and then fails, connects another 10 times perfectly then fails; you get the idea.

My code passes a connect timeout of 15 seconds to Netmiko. My code has a retry loop that makes 3 attempts, with a 2-second delay between the first and second attempts, and a 4-second delay between the second and third attempts. I see the connection attempt start, then absolutely nothing happens for 15 seconds, then Paramiko's `_read_timeout ` function raises `EOFError` which then is caught and re-raised as `SSHException`.

I've experimented with basic ssh at the command line, running it repeatedly to see if *that* fails to connect, or takes a 15 second delay in showing the banner. That *never happens*. 

Is it possible that there is some subtlety in the SSH negotiation deep in Paramiko, something different from your basic ssh client? If so, then there's probably nothing to be done in Netmiko. But I gotta start somewhere.

Please comment.

**Comment by ktbyers** [comment]
@chrisinmtown Can you post the full exception stack trace? Also can you show what your ConnectHandler call looks like including devices_params you are passing in (obviously, you can hide/obscure the real values), I just want to see the arguments that are being used.

**Comment by chrisinmtown** [comment]
Thanks @ktbyers for the quick reply. The behavior seems to be very simple: the router presents no banner text at all, it just doesn't get started.  My code sends these parameters to the `JuniperSSH` class constructor: host, username, password and conn_timeout. The context is a tiny Docker container, so I'm confident there is no local SSH agent and no collection of "id_rsa" files anywhere. Here's a partial stack trace:
```
DEBUG:paramiko.transport:starting thread (client mode): 0x91d30da0
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_4.0.0
WARNING:my.component:Paramiko: 'No existing session' error: try increasing 'conn_timeout' to 15 seconds or larger.
```
In a successful session, the "Local version" line is followed immediately by a "Remote version" line and so much more.

Actually was able to reproduce the problem this morning, and I'm starting to think the particular Juniper router box is not healthy, because similar routers respond perfectly when I attempt connections.

**Comment by ktbyers** [comment]
@chrisinmtown Full exception stack trace please (or it didn't happen) :-)

So Paramiko 4.0.0, there is an odd threading thing Paramiko does right at the location you are referencing. I used to have issues with it a long time ago (in fact somewhere deep in my memory, I remember fixing an issue by hacking paramiko and inserting a short sleep right near where the thread started).

**Comment by ktbyers** [comment]
Have you tried increasing the `banner_timeout` to something like 30s. Maybe set both `banner_timeout` and `conn_timeout` to 30 (at least as an experiment).

**Comment by chrisinmtown** [comment]
I hope this isn't digressing too far .. the router team got back to me and said, that router has more than the configured number of SSH sessions active. I think they're trying to tell me that explains the connect failure, that the router thinks it is defending itself.

That got me thinking, maybe my client app is not *closing out* its sessions correctly, which leads to lingering open sessions, which leads to connection errors. It's a theory anyhow.

Please say, what's the recommended way to end a router session opened with Netmiko? I read that my client app must *not* send an explicit `exit` command as the last step. Will review this: https://github.com/ktbyers/netmiko/issues/1353

**Comment by ktbyers** [comment]
@chrisinmtown You should either use a Context Manager (with statement) or explicitly call disconnect().

You should be able to test/validate whether the SSH session is properly being exited. You can also look at the session_log which should pretty much tell you.

**Comment by chrisinmtown** [comment]
Thanks Kirk. I checked and my app's code is definitely calling `disconnect()`.  So next week I'll add more logging statements and run more tests, hope to get further insights. I would appreciate all tips on validating that the SSH session is being exited properly!

**Comment by ktbyers** [comment]
Sounds good...let me know on what you find.

**Comment by chrisinmtown** [comment]
Hello again, today I watched the Netmiko and Paramiko logs to see what happens when my app calls `disconnect()` at the end of an SSH session at a Juniper router. I saw these log entries which look perfect to me:
```
DEBUG:netmiko:write_channel: b'exit\n'
DEBUG:paramiko.transport:[chan 0] EOF sent (0)
```
However, when I check the Juniper router using command `show system connections` I see a connection still exists from my test. For what it's worth, that report has these columns:
```
Active Internet connections (including servers)
Proto Recv-Q Send-Q  Local Address           Foreign Address                       (state)
```
For the connections that are hanging around, the "Send-Q" column has a non-zero number in it, always the same - 304, and the state is ESTABLISHED. I wonder if the non-zero send-q number is a clue? The cloud tells me this about that value:
>  the Send-Q (Send Queue) column represents the number of data bytes that have been sent by the application but are still waiting to be processed and sent out by the network protocol layer (or acknowledged by the remote host).

Eventually the Juniper router closes these sessions and they vanish from the "connections" report; however, that takes many minutes.

So I have confirmed that this is a problem on Juniper: session lingers after disconnect. For comparison, I checked the Netmiko+Paramiko behavior on Cisco and there an SSH session is closed exactly as expected. That says to me, there's something special about Juniper.

Please suggest further things to try.

**Comment by chrisinmtown** [comment]
Moving this conversation to #3883.
