### ISSUE TITLE
ruckus_fastiron - getting this error for most basic command - TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by TPSreports2020** [ktbyers/netmiko#3390]
### Description of Issue/Question
I have some super basic code that used to work and now it always returns "TypeError: can only concatenate str (not "NoneType") to str" - I have tried adding longer read_timeout values and explicitly adding expect_string=r"#", but I understand that this is already set for ruckus_fastiron?

### Netmiko version

```
netmiko==4.2.0
```

### Netmiko device_type (if relevant to the issue)
(Paste `device_type` between quotes below)

```
ruckus_fastiron
```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
mymachine Scripts % python3 ruckusICX.py
Traceback (most recent call last):
  File "/Users/tannersears/Scripts/ruckusICX.py", line 16, in <module>
    with ConnectHandler(**ruckus_fastiron) as net_connect:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/netmiko/ssh_dispatcher.py", line 388, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/netmiko/base_connection.py", line 462, in __init__
    self._open()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/netmiko/base_connection.py", line 468, in _open
    self._try_session_preparation()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/netmiko/base_connection.py", line 963, in _try_session_preparation
    self.session_preparation()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/netmiko/ruckus/ruckus_fastiron.py", line 17, in session_preparation
    self.enable()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/netmiko/ruckus/ruckus_fastiron.py", line 46, in enable
    new_data = self.read_until_prompt_or_pattern(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/netmiko/base_connection.py", line 835, in read_until_prompt_or_pattern
    return self.read_until_pattern(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/netmiko/base_connection.py", line 706, in read_until_pattern
    output = output + match_str
             ~~~~~~~^~~~~~~~~~~
```

### Relevant Python code
(Please try to essentialize your Python code to the minimum code needed to reproduce the issue)
(Paste the code between the quotes below)

```python
from netmiko import ConnectHandler

ruckus_fastiron = {
    "device_type": "ruckus_fastiron",
    "host": "192.168.0.69",
    "username": "super",
    "password": "password"
}


# Show command that we execute.
command = "show version"


with ConnectHandler(**ruckus_fastiron) as net_connect:
    # Enable mode
    # net_connect.enable()
    # print(net_connect.find_prompt())

    output = net_connect.send_command(command)
    

# Automatically cleans-up the output so that only the show output is returned
print()
print(output)
print()
```

I also get the same output if I just run :

```
from netmiko import ConnectHandler

ruckus_fastiron = {
    "device_type": "ruckus_fastiron",
    "host": "192.168.0.69",
    "username": "super",
    "password": "password"
}

with ConnectHandler(**ruckus_fastiron) as net_connect:
    print(net_connect.find_prompt())
```

**Comment by TPSreports2020** [comment]
I upgraded to 4.3.0 and still get same output

**Comment by tkapica** [comment]
The same issue with my ruckus access point
dirty hack to make it work (I removed set_base_prompt from session_preparation and made enable method to brute force login (I retry it in case help is not shown))

from retry import retry

class RuckusSHH(RuckusFastironSSH):
    def session_preparation(self) -> None:
        """FastIron requires to be enable mode to disable paging."""
        self._test_channel_read()
        self.enable()
        self.disable_paging(command="skip-page-display")
        # Clear the read buffer
        time.sleep(0.3 * self.global_delay_factor)
        self.clear_buffer()
        
    @retry(Exception, tries=5)
    def enable(
            self,
            cmd: str = "enable",
            pattern: str = "",
            enable_pattern: Optional[str] = None,
            check_state: bool = True,
            re_flags: int = re.IGNORECASE,
    ) -> str:
        self.read_until_prompt_or_pattern(
            pattern="Please login:", re_flags=re_flags, read_entire_line=True, read_timeout=1)
        self.write_channel(self.normalize_cmd(self.username))
        time.sleep(1)
        self.read_until_prompt_or_pattern(
            pattern="password:", re_flags=re_flags, read_entire_line=True, read_timeout=1)
        self.write_channel(self.normalize_cmd(self.secret))
        time.sleep(1)
        return self.send_command("help", read_timeout=1)
        
       Maybe it will be helpful until netmiko creates proper fix.

**Comment by ktbyers** [comment]
@TPSreports2020 It looks like Netmiko is failing on this `enable()` call here:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/ruckus/ruckus_fastiron.py#L17

I would probably try turning on Netmiko logging and see if that gives us more clues.

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

Either that or enable the Netmiko session_log.

The None Type concatenation error just means None was returned in a context when a string was expected, but we need to figure out why that happened.

Is this a FastIron switch or is this an access-point?

It is possible that Netmiko is failing to properly identify the `base_prompt` and this is causing a failure later on.

**Comment by TPSreports2020** [comment]
I found that if I keep running it, sometimes it works, but not sure why.. Here are the log files for a time where it worked and a time it failed.

[icx-miko-fail.log](https://github.com/ktbyers/netmiko/files/14643198/icx-miko-fail.log)
[icx-miko-test-working.log](https://github.com/ktbyers/netmiko/files/14643199/icx-miko-test-working.log)

**Comment by semirke** [comment]
Same randomly appearing issue here, too, with fastiron.

**Comment by ktbyers** [comment]
The failing logs from @TPSreports2020 have this:

```
DEBUG:netmiko:read_channel: SSH@TOP-ICX7150-48PF>enable


DEBUG:netmiko:read_channel: No password has been assigned yet...

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: SSH@TOP-ICX7150-48PF#
SSH@TOP-ICX7150-48PF#
```

i.e. no enable password and netmiko is expecting one--so it fails.

**Comment by ktbyers** [comment]
Hopefully this PR fixes/improves most of the issues referenced here:

https://github.com/ktbyers/netmiko/pull/3658
