### ISSUE TITLE
Linux Ubuntu 22.04.4 LTS, "Pattern not detected: '[\\$\\#]' in output." in version 4.3.0 and above

### ISSUE THREAD

**Issue by Abdellah5836** [ktbyers/netmiko#3391]
Hello!

An error appears when connecting to Linux Ubuntu 22.04.4 LTS using Netmiko:

Code:

```

from netmiko import Netmiko

device = {
    'device_type': 'linux',
    'host': '192.168.240.134',
    'username': 'cory',
    'password': 'ubuntu/*abdo'
}

net_connect = Netmiko(**device)

output = net_connect.send_command("uname -n", strip_command=False)
net_connect.disconnect()

print(f"--- {device['host']} --- {output}")
```

Error:

```
Traceback (most recent call last):
  File "c:\Users\pc\Desktop\python_programmability\llpyAuto01\autoPy04\linuxLogs01.py", line 12, in <module>
    net_connect = Netmiko(**device)
  File "C:\Users\pc\Desktop\python_programmability\llpyAuto01\lib\site-packages\netmiko\ssh_dispatcher.py", line 399, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\pc\Desktop\python_programmability\llpyAuto01\lib\site-packages\netmiko\base_connection.py", line 488, in __init__
    self._open()
  File "C:\Users\pc\Desktop\python_programmability\llpyAuto01\lib\site-packages\netmiko\base_connection.py", line 494, in _open
    self._try_session_preparation()
  File "C:\Users\pc\Desktop\python_programmability\llpyAuto01\lib\site-packages\netmiko\base_connection.py", line 988, in _try_session_preparation 
    self.session_preparation()
  File "C:\Users\pc\Desktop\python_programmability\llpyAuto01\lib\site-packages\netmiko\linux\linux_ssh.py", line 23, in session_preparation       
    self._test_channel_read(pattern=self.prompt_pattern)
  File "C:\Users\pc\Desktop\python_programmability\llpyAuto01\lib\site-packages\netmiko\base_connection.py", line 1235, in _test_channel_read      
    return self.read_until_pattern(pattern=pattern, read_timeout=20)
  File "C:\Users\pc\Desktop\python_programmability\llpyAuto01\lib\site-packages\netmiko\base_connection.py", line 746, in read_until_pattern       
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout:

Pattern not detected: '[\\$\\#]' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.
```

Ubuntu Info:
```

PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by ktbyers** [comment]
What is the device using for a prompt?

Netmiko is searching for a prompt that contains eiterh `$` or `#` (this can be overridden via environment variables for Linux, but that is what Netmiko defaults to looking for).
