### ISSUE TITLE
Problem with Catalyst 1300 - random detect pattern and noting more.

### ISSUE THREAD

**Issue by iniagolov** [ktbyers/netmiko#3474]
### Description of Issue/Question

*Note*: Please check https://guides.github.com/features/mastering-markdown/
to see how to properly format your request.

### Netmiko version
(Paste verbatim output from `pip freeze | grep netmiko` between quotes below)

```
netmiko==4.4.0
```

### Netmiko device_type (if relevant to the issue)
(Paste `device_type` between quotes below)

```
cisco_xr
```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```

```

### Relevant Python code
(Please try to essentialize your Python code to the minimum code needed to reproduce the issue)
(Paste the code between the quotes below)

```python
from netmiko import ConnectHandler
import logging
logging.basicConfig(filename="test.log", level=logging.DEBUG)
logger = logging.getLogger("netmiko")
net_connect = ConnectHandler(host="192.168.10.1", username="username", password="password", device_type="cisco_xr", secret="", port=22, default_enter='\r\n')
```

```
cat test.log
DEBUG:paramiko.transport:starting thread (client mode): 0xf6409890
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_3.4.0
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-OpenSSH_7.3p1.RL
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_7.3p1.RL)
DEBUG:paramiko.transport:=== Key exchange possibilities ===
DEBUG:paramiko.transport:kex algos: diffie-hellman-group16-sha512, diffie-hellman-group14-sha1
DEBUG:paramiko.transport:server key: rsa-sha2-512, rsa-sha2-256, ssh-rsa, ssh-dss
DEBUG:paramiko.transport:client encrypt: aes128-ctr, aes192-ctr, aes256-ctr, chacha20-poly1305@openssh.com, aes128-gcm@openssh.com, aes256-gcm@openssh.com
DEBUG:paramiko.transport:server encrypt: aes128-ctr, aes192-ctr, aes256-ctr, chacha20-poly1305@openssh.com, aes128-gcm@openssh.com, aes256-gcm@openssh.com
DEBUG:paramiko.transport:client mac: hmac-sha2-256, hmac-sha2-512, hmac-sha1
DEBUG:paramiko.transport:server mac: hmac-sha2-256, hmac-sha2-512, hmac-sha1
DEBUG:paramiko.transport:client compress: none
DEBUG:paramiko.transport:server compress: none
DEBUG:paramiko.transport:client lang: <none>
DEBUG:paramiko.transport:server lang: <none>
DEBUG:paramiko.transport:kex follows: False
DEBUG:paramiko.transport:=== Key exchange agreements ===
DEBUG:paramiko.transport:Kex: diffie-hellman-group16-sha512
DEBUG:paramiko.transport:HostKey: rsa-sha2-512
DEBUG:paramiko.transport:Cipher: aes128-ctr
DEBUG:paramiko.transport:MAC: hmac-sha2-256
DEBUG:paramiko.transport:Compression: none
DEBUG:paramiko.transport:=== End of kex handshake ===
DEBUG:paramiko.transport:kex engine KexGroup16SHA512 specified hash_algo <built-in function openssl_sha512>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for 192.168.10.1: b'4ff6f5c57f4c093a942519d34b17ae3d'
DEBUG:paramiko.transport:Got EXT_INFO: {'server-sig-algs': b'rsa-sha2-256,rsa-sha2-512'}
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 



ciskoS1#
DEBUG:netmiko:Pattern found: ([>#]) 



ciskoS1#
DEBUG:netmiko:write_channel: b'terminal width 511\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 

DEBUG:netmiko:read_channel: 

ciskoS1#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: termi
DEBUG:netmiko:read_channel: nal widt
DEBUG:netmiko:read_channel: h 511

ciskoS1#
DEBUG:netmiko:Pattern found: (terminal width 511) 


ciskoS1#terminal width 511
DEBUG:netmiko:In disable_paging
DEBUG:netmiko:Command: terminal length 0

DEBUG:netmiko:write_channel: b'terminal length 0\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: t
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: erminal length 0

% Unrecognized command

DEBUG:netmiko:Pattern found: (terminal\ length\ 0) 

ciskoS1#terminal length 0
DEBUG:netmiko:

ciskoS1#terminal length 0
DEBUG:netmiko:Exiting disable_paging
DEBUG:netmiko:read_channel: ciskoS1#
DEBUG:netmiko:Pattern found: ([>#]) 

% Unrecognized command
ciskoS1#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 

ciskoS1#
DEBUG:netmiko:
Parenthesis found in pattern.

pattern: (\#|>)


This can be problemtic when used in read_until_pattern().

You should ensure that you use either non-capture groups i.e. '(?:' or that the
parenthesis completely wrap the pattern '(pattern)'
DEBUG:netmiko:Pattern found: (\#|>) 


ciskoS1#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is ciskoS1#
```

```
Litle info from switch
ciskoS1#show version 
Active-image: flash://system/images/image_c1300_4.1.3.36_official_key.bin
  Version: 4.1.3.36
  MD5 Digest: 90803a985c9110cef9aa4d576206b629
  Date: 19-May-2024
  Time: 08:17:26
Inactive-image: flash://system/images/_image_c1300_4.1.3.36_official_key.bin
  Version: 4.1.3.36
  MD5 Digest: 90803a985c9110cef9aa4d576206b629
  Date: 19-May-2024
  Time: 08:17:26
ciskoS1#

```

**Comment by ktbyers** [comment]
That is not "ios_xr" i.e. your device_type is wrong.

Also disabling of output paging is not working and there are ANSI escape codes are in the output?

It is a bit unclear what the actual operating system of the catalyst 1300 is? You can try "cisco_ios", but you will need to figure out why `terminal length 0` is not working.

Also you probably need to disable the output paging, from looking at the CLI manual for Cat 1300, it looks like `Example
The following example dumps all output immediately after entering a show command.

`terminal datadump` 

Also need to set:

`net_connect.ansi_escape_codes = True`

So your code should become:

```python
from netmiko import ConnectHandler
import logging
logging.basicConfig(filename="test.log", level=logging.DEBUG)
logger = logging.getLogger("netmiko")
net_connect = ConnectHandler(
    host="192.168.10.1", 
    username="username", 
    password="password", 
    device_type="cisco_ios",   # Note change
    secret="", port=22,
)

net_connect.send_command("terminal datadump", expect_string=r"#")
net_connect.ansi_escape_codes = True

# Then try your "show" command using the "send_command" method.
```

Let me know if this works and we can build a driver for this platform.

Reference to notes on Operating System for Catalyst 1200 (and assume 1300):

https://www.reddit.com/r/Cisco/comments/185xmg0/os_used_in_the_catalyst_1200/

**Comment by iniagolov** [comment]
Code: 
```python
from netmiko import ConnectHandler
import logging
logging.basicConfig(filename="test.log", level=logging.DEBUG)
logger = logging.getLogger("netmiko")
net_connect = ConnectHandler(host="192.168.10.1", username="username", password="password", device_type="cisco_ios", secret="", port=22, )
net_connect.send_command("terminal datadump", expect_string=r"#")
net_connect.ansi_escape_codes = True
net_connect.send_command("show ver")
net_connect.send_command("show interface status")
net_connect.disconnect()
```
Debug result
```
[test.log](https://github.com/user-attachments/files/16552782/test.log)

```

**Comment by ktbyers** [comment]
@iniagolov Did that all work properly from an end-user perspective?

**Comment by iniagolov** [comment]
That doesn't work either

```python
from netmiko import ConnectHandler
import logging
logging.basicConfig(filename="test.log", level=logging.DEBUG)
logger = logging.getLogger("netmiko")
net_connect = ConnectHandler(host="192.168.10.1", username="networkmanager", password="N@Man390erp", device_type="cisco_ios", secret="", port=22, )
net_connect.send_command("terminal datadump", expect_string=r"#")
net_connect.ansi_escape_codes = True

net_connect.send_config_set('int gi1/0/3,no shutdown')

net_connect.disconnect()
```

Result
```
>>> net_connect.send_config_set('int gi1/0/3,no shutdown')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/www/networkmanager.tss.bg/.venv/lib/python3.11/site-packages/netmiko/base_connection.py", line 111, in wrapper_decorator
    return_val = func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/networkmanager.tss.bg/.venv/lib/python3.11/site-packages/netmiko/base_connection.py", line 2289, in send_config_set
    output += self.config_mode()
              ^^^^^^^^^^^^^^^^^^
  File "/var/www/networkmanager.tss.bg/.venv/lib/python3.11/site-packages/netmiko/cisco_base_connection.py", line 53, in config_mode
    return super().config_mode(
           ^^^^^^^^^^^^^^^^^^^^
  File "/var/www/networkmanager.tss.bg/.venv/lib/python3.11/site-packages/netmiko/base_connection.py", line 2124, in config_mode
    output += self.read_until_prompt(read_entire_line=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/networkmanager.tss.bg/.venv/lib/python3.11/site-packages/netmiko/base_connection.py", line 839, in read_until_prompt
    return self.read_until_pattern(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/networkmanager.tss.bg/.venv/lib/python3.11/site-packages/netmiko/base_connection.py", line 748, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 

Pattern not detected: '\x1b\\[KciscoS1.*' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.

>>> 

```

Debug
[test.log](https://github.com/user-attachments/files/16553273/test.log)

**Comment by ktbyers** [comment]
TextFSM likely won't wors as Catalyst 1300 is not really IOS so parsing will fail.

**Comment by ktbyers** [comment]
This is not valid syntactically:

```
 net_connect.send_config_set('int gi1/0/3,no shutdown')
```

You need to provide a list of commands i.e.

```python
cmds = ['int gi1/0/3', 'no shutdown']
net_connect.send_config_set(cmds)
 ```
