### ISSUE TITLE
Linux - error when disconnecting

### ISSUE THREAD

**Issue by bulyhome** [ktbyers/netmiko#348]
I am using Windows 7 (64 bit) and Python 3.5 (64 bit) with Paramiko 2.1.1 and Netmiko 1.1.0
I need to connect to multiple Linux hosts using ssh, run several commands there and then disconnect.
When trying to disconnect, I get error:

Traceback (most recent call last):
  File "script_v5.py", line 17, in <module>
    device.disconnect()
  File "C:\Program Files\Python35\lib\site-packages\netmiko\base_connection.py", line 885, in disconnect
    self.cleanup()
  File "C:\Program Files\Python35\lib\site-packages\netmiko\cisco_base_connection.py", line 52, in cleanup
    self.exit_config_mode()
  File "C:\Program Files\Python35\lib\site-packages\netmiko\linux\linux_ssh.py", line 40, in exit_config_mode
    return self.exit_enable_mode(exit_command=exit_config)
  File "C:\Program Files\Python35\lib\site-packages\netmiko\linux\linux_ssh.py", line 53, in exit_enable_mode
    self.set_base_prompt()
  File "C:\Program Files\Python35\lib\site-packages\netmiko\linux\linux_ssh.py", line 21, in set_base_prompt
    delay_factor=delay_factor)
  File "C:\Program Files\Python35\lib\site-packages\netmiko\base_connection.py", line 504, in set_base_prompt
    prompt = self.find_prompt(delay_factor=delay_factor)
  File "C:\Program Files\Python35\lib\site-packages\netmiko\base_connection.py", line 516, in find_prompt
    self.write_channel("\n")
  File "C:\Program Files\Python35\lib\site-packages\netmiko\base_connection.py", line 99, in write_channel
    self.remote_conn.sendall(write_bytes(out_data))
  File "C:\Program Files\Python35\lib\site-packages\paramiko\channel.py", line 813, in sendall
    sent = self.send(s)
  File "C:\Program Files\Python35\lib\site-packages\paramiko\channel.py", line 767, in send
    return self._send(s, m)
  File "C:\Program Files\Python35\lib\site-packages\paramiko\channel.py", line 1133, in _send
    raise socket.error('Socket is closed')
OSError: Socket is closed

Here is my code:

from netmiko import ConnectHandler

platform = 'linux'
host='***'
username='root'
password='***'

device = ConnectHandler(device_type=platform, ip=host, username=username, password=password)
command = "pwd"
output = device.send_command(command)
print(output)
device.disconnect()

**Comment by ktbyers** [comment]
@bulyhome So does everything work properly and it only fails on disconnect?

**Comment by bulyhome** [comment]
Yes, that's the case, everything is ok except the disconnect. I will try 'exit' command as a workaround.

**Comment by ktbyers** [comment]
I think this was fixed here:

https://github.com/ktbyers/netmiko/commit/59a4f3f18e0b269623b2b8698af32ee33e47ef62
