### ISSUE TITLE
Cisco_asa 9.2(4)5

### ISSUE THREAD

**Issue by bambam82** [ktbyers/netmiko#354]
Code to set up the connection.
```
from netmiko import ConnectHandler
ip = '10.202.24.100'
acsuser = "ACSUSER"
acspass = "ACSPASS"
acsenable = "ACSENABLE"

device = {
    'device_type': 'cisco_asa',
    'ip': ip,
    'username': acsuser,
    'password': acspass,
    'secret': acsenable,
    'verbose': True,
    'timeout': 10,
    'global_delay_factor': 3,
}

net_connect = ConnectHandler(**device)

```

This will give the following output:
```
>>> net_connect = ConnectHandler(**device)
SSH connection established to 10.202.24.100:22
Interactive SSH session established
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/paramiko/channel.py", line 665, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.4/dist-packages/paramiko/buffered_pipe.py", line 160, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/netmiko/base_connection.py", line 147, in _read_channel_expect
    output += self.remote_conn.recv(MAX_BUFFER).decode('utf-8', 'ignore')
  File "/usr/local/lib/python3.4/dist-packages/paramiko/channel.py", line 667, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/netmiko/ssh_dispatcher.py", line 96, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/netmiko/base_connection.py", line 90, in __init__
    self.session_preparation()
  File "/usr/local/lib/python3.4/dist-packages/netmiko/cisco/cisco_asa_ssh.py", line 13, in session_preparation
    self.enable()
  File "/usr/local/lib/python3.4/dist-packages/netmiko/cisco_base_connection.py", line 15, in enable
    return super(CiscoBaseConnection, self).enable(cmd=cmd, pattern=pattern, re_flags=re_flags)
  File "/usr/local/lib/python3.4/dist-packages/netmiko/base_connection.py", line 737, in enable
    output += self.read_until_prompt()
  File "/usr/local/lib/python3.4/dist-packages/netmiko/base_connection.py", line 192, in read_until_prompt
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/netmiko/base_connection.py", line 149, in _read_channel_expect
    raise NetMikoTimeoutException("Timed-out reading channel, data not available.")
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.

```

Firewall is running in multi-mode with the following SSH parameters:
ssh stricthostkeycheck
ssh timeout 20
ssh version 2
ssh key-exchange group dh-group1-sha1

Hope you are able to help out. 
PS. Love your product!

**Comment by ktbyers** [comment]
It looks like it failed going into enable mode on the ASA.

Can you post the CLI output of a login and going into enable mode for this device...remove any sensitive information.

Thanks...

**Comment by bambam82** [comment]
Hi Kirk, thanks for the swift response.
It seems that i provided the 'other' enable password I use for the switches. (feeling silly).
thanks anyway.
