### ISSUE TITLE
Another timed out reading channel (cisco 5525)

### ISSUE THREAD

**Issue by keefbaker** [ktbyers/netmiko#358]
Hi, 

First of all thanks for your great work with netmiko. However I have a cisco ASA 5525 that doesn't appear to be connecting properly.

First of all versions:
```
Python 2.7.5 (default, Nov 20 2015, 02:00:19)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import paramiko
>>> paramiko.__version__
'2.1.1'
>>> import netmiko
>>> netmiko.__version__
'1.2.5'
```

The error is as follows:

```
Traceback (most recent call last):
  File "tinytest.py", line 13, in <module>
    net_connect = ConnectHandler(**my_device)
  File "/usr/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 100, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 145, in __init__
    self.session_preparation()
  File "/usr/lib/python2.7/site-packages/netmiko/cisco/cisco_asa_ssh.py", line 13, in session_preparation
    self.enable()
  File "/usr/lib/python2.7/site-packages/netmiko/cisco_base_connection.py", line 15, in enable
    return super(CiscoBaseConnection, self).enable(cmd=cmd, pattern=pattern, re_flags=re_flags)
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 825, in enable
    output += self.read_until_prompt()
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 262, in read_until_prompt
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 219, in _read_channel_expect
    raise NetMikoTimeoutException("Timed-out reading channel, data not available.")
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.
```

When turning the logging on in paramiko I can see that it does in fact get as far as logging in:

```
DEBUG:my_log:This message should go to the log file
DEBUG:paramiko.transport:starting thread (client mode): 0x3132190L
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.1.1
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-Cisco-1.25
INFO:paramiko.transport:Connected (version 2.0, client Cisco-1.25)
DEBUG:paramiko.transport:kex algos:[u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa'] client encrypt:[u'aes128-cbc', u'3des-cbc', u'aes192-cbc', u'aes256-cbc', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr'] server encrypt:[u'aes128-cbc', u'3des-cbc', u'aes192-cbc', u'aes256-cbc', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr'] client mac:[u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5', u'hmac-md5-96'] server mac:[u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5', u'hmac-md5-96'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group1-sha1
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-md5
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for REDACTED: REDACTED
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Auth banner: ******************************************************************************
           This is a private system operated by TTTT
*****************************************************************************

INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 4096 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:read_channel: ******************************************************************************^M
           This is a private system operated by TTTT^M
*****************************************************************************^M
******************************************************************************^M
           This is a private system operated by TTTT^M
*****************************************************************************^M
Type help or '?' for a list of available commands.^M
^Mooofw01/ooofw01>
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel:

DEBUG:netmiko:read_channel: ^M
^Mooofw01/ooofw01>
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel:

DEBUG:netmiko:_read_channel_expect read_data: ^M
^Mooofw01/ooofw01>
DEBUG:netmiko:write_channel: enable

DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
<ad infinitum>
```

But it doesn't get any further.

The small snippet of code I have (as I trimmed it to a very small test program) is:

```python
from netmiko import ConnectHandler
import logging
logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("my_log")
logger.debug('This message should go to the log file')
my_device = {
        'device_type' : 'cisco_asa_ssh',
        'ip' : REDACTED,
        'username' : REDACTED,
        'password' : REDACTED,
        'global_delay_factor': 2
}
net_connect = ConnectHandler(**my_device)
output = net_connect.send_command('show version')
print(output)
```
I also tried it with a delay factor of 4.

**Comment by ktbyers** [comment]
You need to a 'secret'. ASA with Netmiko always requires a secret.

```
my_device = {
        'device_type' : 'cisco_asa_ssh',
        'ip' : REDACTED,
        'username' : REDACTED,
        'password' : REDACTED,
        'secret': 'something',              # Add this
        'global_delay_factor': 2
}
```
