### ISSUE TITLE
Exception Thrown when linux prompt end with other special characters other than $ or #.

### ISSUE THREAD

**Issue by duraipandi** [ktbyers/netmiko#359]
>>> cisco_conf = {
... 'device_type':'ovs_linux',
... 'ip':'bgl-xdm-100',
... 'username':'dsoundra',
... 'password':'Kalaiselvi9751$'
... }
>>>
>>> net_connect=ConnectHandler(**cisco_conf)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\dsoundra\AppData\Local\Programs\Python\Python35\lib\site-packages\netmiko\ssh_dispatcher.py", line 100, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\dsoundra\AppData\Local\Programs\Python\Python35\lib\site-packages\netmiko\base_connection.py", line 145, in __init__
    self.session_preparation()
  File "C:\Users\dsoundra\AppData\Local\Programs\Python\Python35\lib\site-packages\netmiko\base_connection.py", line 381, in session_preparation
    self.set_base_prompt()
  File "C:\Users\dsoundra\AppData\Local\Programs\Python\Python35\lib\site-packages\netmiko\linux\linux_ssh.py", line 21, in set_base_prompt
    delay_factor=delay_factor)
  File "C:\Users\dsoundra\AppData\Local\Programs\Python\Python35\lib\site-packages\netmiko\base_connection.py", line 593, in set_base_prompt
    raise ValueError("Router prompt not found: {0}".format(prompt))
ValueError: Router prompt not found: bgl-xdm-100:~ >

**Comment by ktbyers** [comment]
It is expecting your prompt to either terminate in '$' or in '#'.

**Comment by ktbyers** [comment]
Why do you need your prompt to terminate in a special character?

**Comment by duraipandi** [comment]
it is up to user to set  linux prompt .

temp-linux-100:~ >

**Comment by ktbyers** [comment]
@duraipandi I didn't understand? Is this a question?

Screen scraping has to make certain assumptions, one of them being what the prompt looks like.

**Comment by cramphal** [comment]
@duraipandi & @ktbyers did you ever figure this one out? I also have a linux server with the router prompt that ends in the ">" character. I tried to change the expect character in the linux ssh dispatcher file from 'S' to '>' but I still get the prompt not found error. 

    raise ValueError("Router prompt not found: {0}".format(repr(prompt)))
ValueError: Router prompt not found: u'\x1b[0m\x1b[m\x1b[m\x1b[Jtampaccess:~> \x1b[K\x1b[63C 0\x1b[65D

**Comment by ktbyers** [comment]
@cramphal What version of Netmiko are you using? Also what Netmiko "device_type" are you using?

**Comment by cramphal** [comment]
@ktbyers Hey Kirk! hope all is well. I'm using Netmiko version 1.4.3 on python 2.7 (sorry).   I'm calling the 'linux' device type.

**Comment by ktbyers** [comment]
Your problem looks to be due to ANSI escape codes in the output which should be fixed in any recently new version of Netmiko.
