### ISSUE TITLE
Need  an info : how do we ssh to the linux machine 

### ISSUE THREAD

**Issue by Rashmi-Nuviso** [ktbyers/netmiko#361]
Hi Kirk ,

I have tried to ssh to the linux machine using the below python script ,

####Trial 1#####
from  netmiko import ConnectHandler
cisco_260 = {'device_type': "linux",'ip':'10.100.x.x',  'username': "root",  'password': "Test123$"}
net_connect = ConnectHandler(**cisco_260)
output = net_connect.send_command("ls -lrt")
print output

Traceback (most recent call last):
  File "login.py", line 3, in <module>
    net_connect = ConnectHandler(**cisco_260)
  File "/usr/local/lib/python2.7/dist-packages/netmiko-0.2.5-py2.7.egg/netmiko/ssh_dispatcher.py", line 53, in ConnectHandler
  File "/usr/local/lib/python2.7/dist-packages/netmiko-0.2.5-py2.7.egg/netmiko/ssh_dispatcher.py", line 62, in ssh_dispatcher
KeyError: 'linux'

####Trial 2#####
from  netmiko import ConnectHandler
cisco_260 = {'device_type': "Linux",'ip':'10.48.x.x',  'username': "root",  'password': "Test123$"}
net_connect = ConnectHandler(**cisco_260)
output = net_connect.send_command("ls -lrt")
print output

  File "login.py", line 3, in <module>
    net_connect = ConnectHandler(**cisco_260)
  File "/usr/local/lib/python2.7/dist-packages/netmiko-0.2.5-py2.7.egg/netmiko/ssh_dispatcher.py", line 53, in ConnectHandler
  File "/usr/local/lib/python2.7/dist-packages/netmiko-0.2.5-py2.7.egg/netmiko/ssh_dispatcher.py", line 62, in ssh_dispatcher
KeyError: 'Linux'

####Trial 3#####
from  netmiko import ConnectHandler
cisco_260 = {'device_type': "LinuxSSH",'ip':'10.48.x.x',  'username': "root",  'password': "Test123$"}
net_connect = ConnectHandler(**cisco_260)
output = net_connect.send_command("ls -lrt")
print output

  File "login.py", line 3, in <module>
    net_connect = ConnectHandler(**cisco_260)
  File "/usr/local/lib/python2.7/dist-packages/netmiko-0.2.5-py2.7.egg/netmiko/ssh_dispatcher.py", line 53, in ConnectHandler
  File "/usr/local/lib/python2.7/dist-packages/netmiko-0.2.5-py2.7.egg/netmiko/ssh_dispatcher.py", line 62, in ssh_dispatcher
KeyError: 'LinuxSSH'

i could see the following error . 

Please suggest if there are any solution to this problem .

**Comment by ebeahan** [comment]
@Rashmi-Nuviso Looks like you're using a quite old version (0.2.5) of netmiko. Can you try installing the latest release (1.2.5) and see if that fixes your issue?

**Comment by Rashmi-Nuviso** [comment]
have installed the latest Netmiko . As suggested here and as well as in the netmiko slack channel . Thanks for the clarification . hence closing this item here .
