### ISSUE TITLE
Module List

### ISSUE THREAD

**Issue by networkguy22** [ktbyers/netmiko#391]
Please forgive me Kirk Byrnes and others, but you have inspired me to indoctrinate python into my networking career.

However since i'm still very early on in my learning, I was wondering if you would be able to teach a man to proverbially fish. You could do this by describing where in most github documentation and more specifically in netmiko I go to display the various methods available to be called and what they do generally. 

For example:

 ssh_connection = **ConnectHandler(** 
or
result = ssh_connection.**find_prompt()**

I think this would help alot of newbies who are not strong in the coding background.

Thank you, Adam

P.S since there is no private messaging I wasn't sure where to put this, sorry in advance if it is in the wrong section.

**Comment by ktbyers** [comment]
@networkguy22 Until I improve the documentation, you can do this:

```
$ python
Python 2.7.12 (default, Sep  1 2016, 22:14:06) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import netmiko
>>> dir(netmiko)
['CNTL_SHIFT_6', 'ConnectHandler', 'FileTransfer', 'InLineTransfer', 'NetMikoAuthenticationException', 'NetMikoTimeoutException', 'NetmikoAuthError', 'NetmikoTimeoutError', 'SCPConn', '__all__', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '__version__', 'a10', 'alcatel', 'arista', 'aruba', 'avaya', 'base_connection', 'brocade', 'ciena', 'cisco', 'cisco_base_connection', 'dell', 'eltex', 'enterasys', 'extreme', 'f5', 'fortinet', 'hp', 'huawei', 'juniper', 'linux', 'log', 'logging', 'netmiko_globals', 'ovs', 'paloalto', 'platforms', 'quanta', 'scp_handler', 'ssh_dispatcher', 'ssh_exception', 'ubiquiti', 'unicode_literals', 'utilities', 'vyos']
>>> 
>>> 
>>> from pprint import pprint
>>> pprint(dir(netmiko))
['CNTL_SHIFT_6',
 'ConnectHandler',
 'FileTransfer',
 'InLineTransfer',
 'NetMikoAuthenticationException',
 'NetMikoTimeoutException',
 'NetmikoAuthError',
 'NetmikoTimeoutError',
 'SCPConn',
 '__all__',
 '__builtins__',
 '__doc__',
 '__file__',
 '__name__',
 '__package__',
 '__path__',
 '__version__',
 'a10',
 'alcatel',
 'arista',
 'aruba',
 'avaya',
 'base_connection',
 'brocade',
 'ciena',
 'cisco',
 'cisco_base_connection',
 'dell',
 'eltex',
 'enterasys',
 'extreme',
 'f5',
 'fortinet',
 'hp',
 'huawei',
 'juniper',
 'linux',
 'log',
 'logging',
 'netmiko_globals',
 'ovs',
 'paloalto',
 'platforms',
 'quanta',
 'scp_handler',
 'ssh_dispatcher',
 'ssh_exception',
 'ubiquiti',
 'unicode_literals',
 'utilities',
 'vyos']
>>> 
>>> 
>>> help(netmiko.send_command)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'send_command'
>>> help(netmiko.ssh_dispatcher.CiscoIosSSH)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'function' object has no attribute 'CiscoIosSSH'
>>> help(base_connection.BaseConnection)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'base_connection' is not defined
>>> help(netmiko.base_connection.BaseConnection)

**Comment by ktbyers** [comment]
Also check out this article.

https://pynet.twb-tech.com/blog/automation/netmiko.html

**Comment by ktbyers** [comment]
Just re-open if you have other questions.

**Comment by mmihir82** [comment]
After ssh to switch, I would like to fetch few information, then disconnect using function. 
For example: 
```
def switchconnect (switchip, user):
    cisco1 = {
        'host': switchip,
        'username': user,
        'password': getpass(),
        'device_type': 'cisco_ios',
    }
    switch = Netmiko(**cisco1)
    print(switch.find_prompt())
    return switch

def switchdisconnect (switchip):
    return switchip.disconnect()

run = switchconnect(switchip,user)
switchdisconnect(run)
```
It works with first switch, but doesn't work continuous with seconds swtich.
I get time-out error:
```
Password:
Traceback (most recent call last):
  File "phase4.py", line 174, in <module>
    run = switchconnect(switchip,user)
  File "phase4.py", line 17, in switchconnect
    switch = Netmiko(**cisco1)
  File "/usr/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 178, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 207, in __init__
    self.establish_connection()
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 693, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios testdevice:22
```
