### ISSUE TITLE
discard_config and merge_config operations fail on cisco IOS

### ISSUE THREAD

**Issue by Badgerpoo** [ktbyers/netmiko#413]
#### Server: 
CentOS Linux release 7.3.1611 (Core)

##### PIP installed packages:
```
(env)[ansible@ansible-p0 tests]$ pip list --format=columns
Package           Version
----------------- -------
ansible           2.2.1.0
ansible-lint      3.4.11 
appdirs           1.4.3  
bnclient          0.3    
cffi              1.9.1  
cryptography      1.7.2  
enum34            1.1.6  
future            0.16.0 
idna              2.5    
ipaddress         1.0.18 
Jinja2            2.8.1  
jtextfsm          0.3.1  
junos-eznc        2.0.1  
lxml              3.7.3  
MarkupSafe        1.0    
napalm            1.1.0  
napalm-base       0.23.0 
napalm-eos        0.5.5  
napalm-fortios    0.3.1  
napalm-ibm        0.1.7  
napalm-ios        0.6.1  
napalm-iosxr      0.4.8  
napalm-junos      0.6.4  
napalm-nxos       0.5.1  
napalm-panos      0.4.0  
napalm-pluribus   0.5.1  
ncclient          0.5.3  
netaddr           0.7.19 
netmiko           1.2.8  
packaging         16.8   
pan-python        0.10.0 
paramiko          2.1.2  
pip               9.0.1  
pyasn1            0.2.3  
pycparser         2.17   
pycrypto          2.6.1  
pyeapi            0.7.0  
pyfg              0.48   
pyIOSXR           0.41   
pynxos            0.0.3  
pyparsing         2.2.0  
pyPluribus        0.3.1  
pyserial          3.3    
PyYAML            3.12   
requests          2.13.0 
requests-toolbelt 0.7.1  
scp               0.10.2 
setuptools        34.3.2 
six               1.10.0 
xmltodict         0.10.2 
```
Utilising a python virtual environment in /usr/local/projects/ansible/env

### Switch
Hostname: "ansibletest2"
Model: 2960X-48TS-L
Software: c2960x-universalk9-mz.152-2.E3.bin

### Testing get_facts():
```python
#!/usr/local/projects/ansible/env/bin/python

from napalm_base import get_network_driver
ios = get_network_driver("ios")
hostname = "ansibletest2"
user = "ansible"
password = "Secret1"
device = ios(hostname, user, password)
device.open()
print(device.get_facts())
device.close()
```
#### Results:
```
(env)[ansible@ansible-p0 tests]$ ./debug3.py
{u'os_version': u'C2960X Software (C2960X-UNIVERSALK9-M), Version 15.2(2)E3, RELEASE SOFTWARE (fc3)', u'uptime': 362760, u'interface_list': [u'Vlan1', u'FastEthernet0', u'GigabitEthernet1/0/1', u'GigabitEthernet1/0/2', u'GigabitEthernet1/0/3', u'GigabitEthernet1/0/4', u'GigabitEthernet1/0/5', u'GigabitEthernet1/0/6', u'GigabitEthernet1/0/7', u'GigabitEthernet1/0/8', u'GigabitEthernet1/0/9', u'GigabitEthernet1/0/10', u'GigabitEthernet1/0/11', u'GigabitEthernet1/0/12', u'GigabitEthernet1/0/13', u'GigabitEthernet1/0/14', u'GigabitEthernet1/0/15', u'GigabitEthernet1/0/16', u'GigabitEthernet1/0/17', u'GigabitEthernet1/0/18', u'GigabitEthernet1/0/19', u'GigabitEthernet1/0/20', u'GigabitEthernet1/0/21', u'GigabitEthernet1/0/22', u'GigabitEthernet1/0/23', u'GigabitEthernet1/0/24', u'GigabitEthernet1/0/25', u'GigabitEthernet1/0/26', u'GigabitEthernet1/0/27', u'GigabitEthernet1/0/28', u'GigabitEthernet1/0/29', u'GigabitEthernet1/0/30', u'GigabitEthernet1/0/31', u'GigabitEthernet1/0/32', u'GigabitEthernet1/0/33', u'GigabitEthernet1/0/34', u'GigabitEthernet1/0/35', u'GigabitEthernet1/0/36', u'GigabitEthernet1/0/37', u'GigabitEthernet1/0/38', u'GigabitEthernet1/0/39', u'GigabitEthernet1/0/40', u'GigabitEthernet1/0/41', u'GigabitEthernet1/0/42', u'GigabitEthernet1/0/43', u'GigabitEthernet1/0/44', u'GigabitEthernet1/0/45', u'GigabitEthernet1/0/46', u'GigabitEthernet1/0/47', u'GigabitEthernet1/0/48', u'GigabitEthernet1/0/49', u'GigabitEthernet1/0/50', u'GigabitEthernet1/0/51', u'GigabitEthernet1/0/52'], u'vendor': u'Cisco', u'serial_number': u'FOC2015Z4E2', u'model': u'WS-C2960X-48TS-L', u'hostname': u'ansibletest2', u'fqdn': u'ansibletest2.nwbld.bris.ac.uk'}
```

### Testing commit_config():
```python
#!/usr/local/projects/ansible/env/bin/python

from napalm_base import get_network_driver
ios = get_network_driver("ios")
hostname = "ansibletest2"
user = "ansible"
password = "Secret1"
path_to_file = "config3.txt"
device = ios(hostname, user, password)
device.open()
device.load_merge_candidate(filename=path_to_file)
print("Compare Config:")
print(device.compare_config())
print("Commit Config:")
device.commit_config()
device.close()
```
#### Results:
```
(env)[ansible@ansible-p0 tests]$ ./debug4.py
Compare Config:
+interface GigabitEthernet1/0/3
+ description test3
Commit Config:
Traceback (most recent call last):
  File "./debug4.py", line 15, in <module>
    device.commit_config()
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/napalm_ios/ios.py", line 347, in commit_config
    self._gen_rollback_cfg()
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/napalm_ios/ios.py", line 506, in _gen_rollback_cfg
    self._enable_confirm()
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/napalm_ios/ios.py", line 484, in _enable_confirm
    self.device.send_config_set([cmd])
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/netmiko/base_connection.py", line 913, in send_config_set
    output = self.config_mode()
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/netmiko/cisco_base_connection.py", line 41, in config_mode
    pattern=pattern)
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/netmiko/base_connection.py", line 863, in config_mode
    if not self.check_config_mode():
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/netmiko/cisco_base_connection.py", line 30, in check_config_mode
    pattern=pattern)
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/netmiko/base_connection.py", line 855, in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/netmiko/base_connection.py", line 266, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/netmiko/base_connection.py", line 219, in _read_channel_expect
    raise NetMikoTimeoutException("Timed-out reading channel, data not available.")
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.
```
files created on switch:
flash:/merge_config.txt
```
interface GigabitEthernet1/0/3
 description test3
end
```
flash:/rollback_config.txt
```
!
! Last configuration change at 16:17:33 UTC Tue Mar 14 2017 by ansible
! NVRAM config last updated at 16:17:14 UTC Tue Mar 14 2017
!
version 15.2
no service pad
service timestamps debug datetime msec
service timestamps log datetime msec
no service password-encryption
!
hostname ansibletest2
!
boot-start-marker
boot-end-marker
!
enable secret 5 $1$vBx8$vwgd2VutWCvKPx4R/ODdt/
!
username ansible privilege 15 secret 5 $1$lUgr$jI408s56L.rqVq3Isusi10
username ansible2 secret 5 $1$lUgr$jI408s56L.rqVq3Isusi10
no aaa new-model
switch 1 provision ws-c2960x-48ts-l
!
!
!         
!
!
!
!
!
!
crypto pki trustpoint TP-self-signed-2250413440
 enrollment selfsigned
 subject-name cn=IOS-Self-Signed-Certificate-2250413440
 revocation-check none
 rsakeypair TP-self-signed-2250413440
!
!
crypto pki certificate chain TP-self-signed-2250413440
 certificate self-signed 01
  3082022B 30820194 A0030201 02020101 300D0609 2A864886 F70D0101 05050030 
  31312F30 2D060355 04031326 494F532D 53656C66 2D536967 6E65642D 43657274 
  69666963 6174652D 32323530 34313334 3430301E 170D3137 30333134 31333436 
  30325A17 0D323030 31303130 30303030 305A3031 312F302D 06035504 03132649 
  4F532D53 656C662D 5369676E 65642D43 65727469 66696361 74652D32 32353034 
  31333434 3030819F 300D0609 2A864886 F70D0101 01050003 818D0030 81890281 
  8100B3AA 7F6BB35B 17AC07AA 0B1D14BF 5CEF9AAF 04C8AFF8 19EA03CC 92794900 
  9055AF81 3F5FEAFC 602FFFAC 03E4ECEC CDF8C7C0 4F5AFA75 65E12333 1CE75EFA 
  702AC96C 99CF2EB1 18A83368 EE8E4061 DE231B69 45C69A44 E027A127 DE07BE8B 
  C207E954 057C3F60 0ACBB826 C225A84F 7FCDECA2 A6BB3C82 DE7A3F1B 2D5332F5 
  02310203 010001A3 53305130 0F060355 1D130101 FF040530 030101FF 301F0603 
  551D2304 18301680 145D31F3 8A0F4B85 4F568366 93BCDF3E E43ADE5A 37301D06 
  03551D0E 04160414 5D31F38A 0F4B854F 56836693 BCDF3EE4 3ADE5A37 300D0609 
  2A864886 F70D0101 05050003 81810030 5249E156 2AC536E8 CB412888 32470BC5 
  8C86E2C8 E6212EA6 0A85B4AC 3E5ED21D 23628DEE FF8DEB28 78117955 7403B1D1 
  2E3760E7 5B9A0827 52D796EA 6C915093 6CE48B14 D477E72D 31CAB18C 0146BD35 
  3C85F672 6BAF997B 3C662494 4C6EC068 A6616E57 040F0C5B B87B27D5 B958F964 
  035FE141 BA4C2849 BBBA827B 04949F
        quit
file prompt quiet
spanning-tree mode pvst
spanning-tree extend system-id
!
!
!
!
vlan internal allocation policy ascending
!
!
! 
!         
!
!
!
!
!
!
!
interface FastEthernet0
 no ip address
 shutdown
!
interface GigabitEthernet1/0/1
 description test1
!
interface GigabitEthernet1/0/2
 description test2
!
interface GigabitEthernet1/0/3
!
interface GigabitEthernet1/0/4
!
interface GigabitEthernet1/0/5
!         
interface GigabitEthernet1/0/6
!
interface GigabitEthernet1/0/7
!
interface GigabitEthernet1/0/8
!
interface GigabitEthernet1/0/9
!
interface GigabitEthernet1/0/10
!
interface GigabitEthernet1/0/11
!
interface GigabitEthernet1/0/12
!
interface GigabitEthernet1/0/13
!
interface GigabitEthernet1/0/14
!
interface GigabitEthernet1/0/15
!
interface GigabitEthernet1/0/16
!
interface GigabitEthernet1/0/17
!
interface GigabitEthernet1/0/18
!
interface GigabitEthernet1/0/19
!
interface GigabitEthernet1/0/20
!
interface GigabitEthernet1/0/21
!
interface GigabitEthernet1/0/22
!
interface GigabitEthernet1/0/23
!
interface GigabitEthernet1/0/24
!
interface GigabitEthernet1/0/25
!
interface GigabitEthernet1/0/26
!
interface GigabitEthernet1/0/27
!
interface GigabitEthernet1/0/28
!         
interface GigabitEthernet1/0/29
!
interface GigabitEthernet1/0/30
!
interface GigabitEthernet1/0/31
!
interface GigabitEthernet1/0/32
!
interface GigabitEthernet1/0/33
!
interface GigabitEthernet1/0/34
!
interface GigabitEthernet1/0/35
!
interface GigabitEthernet1/0/36
!
interface GigabitEthernet1/0/37
!
interface GigabitEthernet1/0/38
!
interface GigabitEthernet1/0/39
!
interface GigabitEthernet1/0/40
!
interface GigabitEthernet1/0/41
!
interface GigabitEthernet1/0/42
!
interface GigabitEthernet1/0/43
!
interface GigabitEthernet1/0/44
!
interface GigabitEthernet1/0/45
!
interface GigabitEthernet1/0/46
!
interface GigabitEthernet1/0/47
!
interface GigabitEthernet1/0/48
!
interface GigabitEthernet1/0/49
!
interface GigabitEthernet1/0/50
!
interface GigabitEthernet1/0/51
!         
interface GigabitEthernet1/0/52
!
interface Vlan1
 ip address dhcp
!
ip http server
ip http secure-server
!
ip ssh version 2
ip scp server enable
!
!
!
!
line con 0
line vty 0 4
 login local
 transport input ssh
line vty 5 15
 login
!
end       
```

### Testing discard_config():
```python
#!/usr/local/projects/ansible/env/bin/python

from napalm_base import get_network_driver
ios = get_network_driver("ios")
hostname = "ansibletest2"
user = "ansible"
password = "Secret1"
path_to_file = "config3.txt"
device = ios(hostname, user, password)
device.open()
device.load_merge_candidate(filename=path_to_file)
print("Compare Config:")
print(device.compare_config())
print("Discard Config:")
device.discard_config()
device.close()
```
#### Results:
```
(env)[ansible@ansible-p0 tests]$ ./debug4.py
Compare Config:
+interface GigabitEthernet1/0/3
+ description test3
Discard Config:
Traceback (most recent call last):
  File "./debug4.py", line 17, in <module>
    device.discard_config()
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/napalm_ios/ios.py", line 390, in discard_config
    self.device.send_command_expect(discard_merge)
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/netmiko/base_connection.py", line 778, in send_command_expect
    return self.send_command(*args, **kwargs)
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/netmiko/base_connection.py", line 770, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: ansibletest2
```

**Comment by ktbyers** [comment]
@Badgerpoo On your commit_config() failure, the first failure. Does this happen consistent i.e. if you repeat this process 3 times on this same code and same device, do you get the same error every time?

In your first issue, the commit_config failure, what happens if you add this:

```
# add right after your password
optional_args = {}
optional_args['global_delay_factor'] = 4

# change your call to NAPALM to this (i.e. pass in the optional arguments
device = ios(hostname, user, password, optional_args=optional_args)
```

**Comment by Badgerpoo** [comment]
@ktbyers 
#### Attempt 1:
```
(env)[ansible@ansible-p0 tests]$ ./debug4.py
Compare Config:
+interface GigabitEthernet1/0/3
+ description test3
Commit Config:
Traceback (most recent call last):
  File "./debug4.py", line 15, in <module>
    device.commit_config()
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/napalm_ios/ios.py", line 370, in commit_config
    if not self._check_file_exists(cfg_file):
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/napalm_ios/ios.py", line 524, in _check_file_exists
    output = self.device.send_command_expect(cmd)
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/netmiko/base_connection.py", line 778, in send_command_expect
    return self.send_command(*args, **kwargs)
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/netmiko/base_connection.py", line 770, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: ansibletest2\#
```
New files on switch: rollback_config.txt

#### Attempt 2:
```
(env)[ansible@ansible-p0 tests]$ ./debug4.py
Compare Config:
+interface GigabitEthernet1/0/3
+ description test3
Commit Config:
Traceback (most recent call last):
  File "./debug4.py", line 15, in <module>
    device.commit_config()
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/napalm_ios/ios.py", line 347, in commit_config
    self._gen_rollback_cfg()
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/napalm_ios/ios.py", line 505, in _gen_rollback_cfg
    self.device.send_command_expect(cmd)
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/netmiko/base_connection.py", line 778, in send_command_expect
    return self.send_command(*args, **kwargs)
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/netmiko/base_connection.py", line 770, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: ansibletest2\#
```
New files on switch: rollback_config.txt, merge_config.txt

#### Attempt 3:
```
(env)[ansible@ansible-p0 tests]$ ./debug4.py
Compare Config:
+interface GigabitEthernet1/0/3
+ description test3
Commit Config:
Traceback (most recent call last):
  File "./debug4.py", line 15, in <module>
    device.commit_config()
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/napalm_ios/ios.py", line 347, in commit_config
    self._gen_rollback_cfg()
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/napalm_ios/ios.py", line 506, in _gen_rollback_cfg
    self._enable_confirm()
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/napalm_ios/ios.py", line 484, in _enable_confirm
    self.device.send_config_set([cmd])
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/netmiko/base_connection.py", line 913, in send_config_set
    output = self.config_mode()
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/netmiko/cisco_base_connection.py", line 41, in config_mode
    pattern=pattern)
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/netmiko/base_connection.py", line 863, in config_mode
    if not self.check_config_mode():
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/netmiko/cisco_base_connection.py", line 30, in check_config_mode
    pattern=pattern)
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/netmiko/base_connection.py", line 855, in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/netmiko/base_connection.py", line 266, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/netmiko/base_connection.py", line 219, in _read_channel_expect
    raise NetMikoTimeoutException("Timed-out reading channel, data not available.")
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.
```
New files on switch: rollback_config.txt, merge_config.txt

#### After adding suggested code:
```
(env)[ansible@ansible-p0 tests]$ ./debug5.py
Compare Config:
+interface GigabitEthernet1/0/3
+ description test3
Commit Config:
Traceback (most recent call last):
  File "./debug5.py", line 17, in <module>
    device.commit_config()
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/napalm_ios/ios.py", line 347, in commit_config
    self._gen_rollback_cfg()
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/napalm_ios/ios.py", line 506, in _gen_rollback_cfg
    self._enable_confirm()
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/napalm_ios/ios.py", line 484, in _enable_confirm
    self.device.send_config_set([cmd])
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/netmiko/base_connection.py", line 921, in send_config_set
    output += self.exit_config_mode()
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/netmiko/cisco_base_connection.py", line 48, in exit_config_mode
    pattern=pattern)
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/netmiko/base_connection.py", line 874, in exit_config_mode
    if self.check_config_mode():
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/netmiko/cisco_base_connection.py", line 30, in check_config_mode
    pattern=pattern)
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/netmiko/base_connection.py", line 855, in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/netmiko/base_connection.py", line 266, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/projects/ansible/env/lib/python2.7/site-packages/netmiko/base_connection.py", line 219, in _read_channel_expect
    raise NetMikoTimeoutException("Timed-out reading channel, data not available.")
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.
```
New files on switch: rollback_config.txt, merge_config.txt

**Comment by ktbyers** [comment]
@Badgerpoo Your issue is still very strange, particularly that the error keeps changing which indicates there is some sort of a timing issue:

Let's try even simpler Netmiko code (you will need to update username and potentially other arguments in `device` to work in your environment.

```
from netmiko import ConnectHandler
from getpass import getpass

ip_addr = raw_input("Enter IP Address: ")

device = { 
    'device_type': 'cisco_ios',
    'ip': ip_addr,
    'username': 'admin',
    'password': getpass(),
} 

net_connect = ConnectHandler(**device)
print(net_connect.find_prompt())
print(net_connect.find_prompt())
print(net_connect.find_prompt())
print(net_connect.find_prompt())
```

**Comment by ktbyers** [comment]
Here is what it looks like when I run the above code on one of my routers:

```
$ python test2.py 
Enter IP Address: 184.105.247.70
Password: 
pynet-rtr1#
pynet-rtr1#
pynet-rtr1#
pynet-rtr1#
pynet-rtr1#
False
False
False
False
False
```

**Comment by Badgerpoo** [comment]
Same result here, I edited python to hardcode IP, password etc:

```
(env)[ansible@ansible-p0 tests]$ ./debug7.py 
ansibletest2#
ansibletest2#
ansibletest2#
ansibletest2#
ansibletest2#
False
False
False
False
False
```

**Comment by ktbyers** [comment]
Okay, let me know what you see when you do the following manually (merge file can have whatever contents are appropriate for your environment...just make a simple change, however).

```
pynet-rtr1#more flash:/merge_config.txt
ip route 1.1.99.1 255.255.255.255 10.220.88.1

pynet-rtr1#copy flash:/merge_config.txt system:/running-config 
Destination filename [running-config]? 
46 bytes copied in 0.008 secs (5750 bytes/sec)
```

**Comment by Badgerpoo** [comment]
I used a slightly different example but should be much the same:

```
ansibletest2#sh run int gi1/0/3
Building configuration...

Current configuration : 38 bytes
!
interface GigabitEthernet1/0/3
end

ansibletest2#more config3.txt
interface GigabitEthernet1/0/3
 description test3
end
ansibletest2#copy flash:/config3.txt system:/running-config
53 bytes copied in 0.007 secs (7571 bytes/sec)
ansibletest2#sh run int gi1/0/3
Building configuration...

Current configuration : 57 bytes
!
interface GigabitEthernet1/0/3
 description test3
end

ansibletest2#
```

**Comment by ktbyers** [comment]
@Badgerpoo Okay, let's try this code. This reproduces the section of the code that failed in NAPALM above.

```
from netmiko import ConnectHandler
from getpass import getpass

ip_addr = raw_input("Enter IP Address: ")

device = { 
    'device_type': 'cisco_ios',
    'ip': ip_addr,
    'username': 'pyclass',
    'password': getpass(),
} 

net_connect = ConnectHandler(**device)
# Should show router prompt 5 times
for i in range(5):
    print(net_connect.find_prompt())

# Should show False 5 times
for i in range(5):
    print(net_connect.check_config_mode())

cmd = 'file prompt quiet'
output = net_connect.send_config_set([cmd])
print(output)

cfg_file = 'flash:/rollback_config.txt'
cmd = 'copy running-config {}'.format(cfg_file)
output = net_connect.send_command_expect(cmd)
print(output)

cmd = 'no file prompt quiet'
output = net_connect.send_config_set([cmd])
print(output)
```

**Comment by ktbyers** [comment]
Closed needed more information from user.

**Comment by Badgerpoo** [comment]
New environment with more up to date software:

```
(env)[ansible@ansible-d0 tests]$ pip list --format=columns
Package           Version
----------------- -------
ansible           2.3.0.0
ansible-lint      3.4.13
appdirs           1.4.3
bnclient          0.3
cffi              1.10.0
chainmap          1.0.2
cryptography      1.7.2
enum34            1.1.6
future            0.16.0
idna              2.5
ipaddress         1.0.18
Jinja2            2.8.1
jtextfsm          0.3.1
junos-eznc        2.1.2
jxmlease          1.0.1
librouteros       1.0.2
lxml              3.7.3
MarkupSafe        1.0
napalm            1.2.0
napalm-base       0.23.3
napalm-eos        0.5.6
napalm-fortios    0.4.0
napalm-ibm        0.1.7
napalm-ios        0.6.2
napalm-iosxr      0.4.8
napalm-junos      0.6.6
napalm-nxos       0.5.2
napalm-panos      0.4.0
napalm-pluribus   0.5.1
napalm-ros        0.2.2
napalm-vyos       0.1.3
ncclient          0.5.3
netaddr           0.7.19
netmiko           1.4.0
packaging         16.8
pan-python        0.11.0
paramiko          2.1.2
pip               9.0.1
pyasn1            0.2.3
pycparser         2.17
pycrypto          2.6.1
pyeapi            0.8.0
pyfg              0.50
pyIOSXR           0.41
pynxos            0.0.3
pyparsing         2.2.0
pyPluribus        0.3.1
pyserial          3.3
PyYAML            3.12
requests          2.14.2
requests-toolbelt 0.7.1
scp               0.10.2
setuptools        35.0.2
six               1.10.0
VyattaConfParser  0.5.1
xmltodict         0.11.0
```

I ran the above code with the following, apparently successful result:

```
(env)[ansible@ansible-d0 tests]$ ./debug8.py
tests4#
tests4#
tests4#
tests4#
tests4#
False
False
False
False
False
config term
Enter configuration commands, one per line.  End with CNTL/Z.
tests4(config)#file prompt quiet
tests4(config)#end
tests4#
18570 bytes copied in 2.651 secs (7005 bytes/sec)
config term
Enter configuration commands, one per line.  End with CNTL/Z.
tests4(config)#no file prompt quiet
tests4(config)#end
tests4#
```

**Comment by Badgerpoo** [comment]
I just tested using the same versions of everything, and the same python environment, on a debian 8 physical machine against the same switches, and it works perfectly. 

Seems to be something about the Centos VM I'm running from? It's on Hyper-V if that makes any difference.

**Comment by Badgerpoo** [comment]
Further testing reveals that the debug scripts work on physical centos7, and fail on Hyper-V centos 7. Something about how Hyper-V VMs work seems to be breaking it?

**Comment by Badgerpoo** [comment]
Extensive testing has revealed the problem lies in the network and/or f5 somewhere. Closing this issue!
