### ISSUE TITLE
Error reading SSH protocol banner  Nexus Vblock device

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#416]
```cli.start_cli_session              : ?  SSH auth error to 10.20.253.11 using e0003498, My
Exception: Error reading SSH protocol banner
Traceback (most recent call last):
  File "C:\Users\Wyko\AppData\Local\Programs\Python\Python36-32\lib\site-packages\paramiko\transport.py", line 1893, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "C:\Users\Wyko\AppData\Local\Programs\Python\Python36-32\lib\site-packages\paramiko\packet.py", line 331, in readline
    buf += self._read_timeout(timeout)
  File "C:\Users\Wyko\AppData\Local\Programs\Python\Python36-32\lib\site-packages\paramiko\packet.py", line 487, in _read_timeout
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wyko\AppData\Local\Programs\Python\Python36-32\lib\site-packages\paramiko\transport.py", line 1749, in run
    self._check_banner()
  File "C:\Users\Wyko\AppData\Local\Programs\Python\Python36-32\lib\site-packages\paramiko\transport.py", line 1897, in _check_banner
    raise SSHException('Error reading SSH protocol banner' + str(e))
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

                                   : #4 SSH to [10.20.253.11] failed due to [SSHException] error: [Error reading SSH protocol banner]
```

[10:07]  
 ```[Wyko.DESKTOP-O0P45FT] ➤ ssh -v 10.20.253.11
OpenSSH_7.1p2, OpenSSL 1.0.2k  26 Jan 2017
debug1: Reading configuration data /etc/ssh_config
debug1: Connecting to 10.20.253.11 [10.20.253.11] port 22.
debug1: Connection established.
debug1: key_load_public: No such file or directory
debug1: identity file /home/mobaxterm/.ssh/id_rsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/mobaxterm/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/mobaxterm/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/mobaxterm/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/mobaxterm/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/mobaxterm/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/mobaxterm/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/mobaxterm/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.1
ssh_exchange_identification: Connection closed by remote host```

**Comment by Wyko** [comment]
Cisco NX-OS(tm) n9000, Software (n9000-dk9), Version 7.0(3)I1(3), RELEASE SOFTWARE Copyright (c) 2002-2013 by Cisco Systems, Inc. Compiled 8/21/2015 2:00:00

**Comment by ktbyers** [comment]
@Wyko I left this for a very long time. 

Anyone available to work on this, try to troubleshoot, get more data?

Otherwise, I will probably close it.

**Comment by carlniger** [comment]
inactive. closing.
