### ISSUE TITLE
cannot connect to device using netmiko

### ISSUE THREAD

**Issue by aditya-ast** [ktbyers/netmiko#445]
Hello Mr. Byers,
I've checked existing issues in here, but couldn't find a solution to my problem. Please help me out.
When I run:
>>> cisco_881 = {
...     'device_type': 'cisco_ios',
...     'ip':   '10.10.10.10',
...     'username': 'test',
...     'password': 'password',
... }
>>> 
>>> net_connect = ConnectHandler(**cisco_881)

The error shows:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/netmiko/ssh_dispatcher.py", line 120, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 151, in __init__
    self.establish_connection()
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 505, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios 10.10.10.10:22

I've been trying to figure out the problem, but I can't get it. Please help me out!!

**Comment by ktbyers** [comment]
@ast-vi It looks like you are trying to connect to an IP address that isn't running SSH.

From the same box as you run your script, are you able to manually SSH to that IP?

**Comment by iqbalkanayal** [comment]
@ktbyers Kirk Byers, I also have a similar error. I try to ssh to the router. It's working fine. But I am not able to connect to ssh using a python script. I need suggestions from you. Thanks

**Comment by iqbalkanayal** [comment]
@ktbyers thanks for your quick reply.
code:
from netmiko import ConnectHandler

cisco_ios_xrv = {
    'device_type': 'cisco_xe',
    'ip':   'x.x.x.x',
    'username': '',
    'password': '',
    'global_delay_factor': 4
    
}

try:
    
    net_connect = ConnectHandler(**cisco_ios_xrv)
except SSHException:
    print('SSH is not enabled for this device.')
    sys.exit()
    
output = net_connect.send_command('show ip int brief')
print(output)




Exceptions:

Traceback (most recent call last):
  File "C:\Users\-Nayyar-\AppData\Local\Programs\Python\Python36-32\lib\site-packages\netmiko-1.3.1-py3.6.egg\netmiko\base_connection.py", line 490, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "C:\Users\-Nayyar-\AppData\Local\Programs\Python\Python36-32\lib\site-packages\paramiko\client.py", line 305, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "C:\Users\-Nayyar-\AppData\Local\Programs\Python\Python36-32\lib\site-packages\paramiko\util.py", line 269, in retry_on_signal
    return function()
  File "C:\Users\-Nayyar-\AppData\Local\Programs\Python\Python36-32\lib\site-packages\paramiko\client.py", line 305, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\-Nayyar-\AppData\Local\Programs\Python\Python36-32\t2.py", line 15, in <module>
    net_connect = ConnectHandler(**cisco_ios_xrv)
  File "C:\Users\-Nayyar-\AppData\Local\Programs\Python\Python36-32\lib\site-packages\netmiko-1.3.1-py3.6.egg\netmiko\ssh_dispatcher.py", line 120, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\-Nayyar-\AppData\Local\Programs\Python\Python36-32\lib\site-packages\netmiko-1.3.1-py3.6.egg\netmiko\base_connection.py", line 144, in __init__
    self.establish_connection()
  File "C:\Users\-Nayyar-\AppData\Local\Programs\Python\Python36-32\lib\site-packages\netmiko-1.3.1-py3.6.egg\netmiko\base_connection.py", line 494, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_xe 172.16.2.240:22

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\-Nayyar-\AppData\Local\Programs\Python\Python36-32\t2.py", line 16, in <module>
    except SSHException:
NameError: name 'SSHException' is not defined

**Comment by ktbyers** [comment]
You might want to try Python 3.5 and see if it works. 

Let me know if you see the same issue or not (with Python 3.5).

**Comment by chocokalamay** [comment]
Hi @ktbyers ,

i tried to run this following command. can you help me on this?

>>> from netmiko import ConnectHandler
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\lester.parcon\AppData\Local\Programs\Python\Python35\netmiko\__init__.py", line 8, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "C:\Users\lester.parcon\AppData\Local\Programs\Python\Python35\netmiko\ssh_dispatcher.py", line 3, in <module>
    from netmiko.cisco import CiscoIosBase
  File "C:\Users\lester.parcon\AppData\Local\Programs\Python\Python35\netmiko\cisco\__init__.py", line 2, in <module>
    from netmiko.cisco.cisco_ios import CiscoIosBase, CiscoIosSSH, CiscoIosTelnet
  File "C:\Users\lester.parcon\AppData\Local\Programs\Python\Python35\netmiko\cisco\cisco_ios.py", line 3, in <module>
    from netmiko.cisco_base_connection import CiscoBaseConnection
  File "C:\Users\lester.parcon\AppData\Local\Programs\Python\Python35\netmiko\cisco_base_connection.py", line 3, in <module>
    from netmiko.base_connection import BaseConnection
  File "C:\Users\lester.parcon\AppData\Local\Programs\Python\Python35\netmiko\base_connection.py", line 13, in <module>
    import paramiko
ImportError: No module named 'paramiko'

**Comment by ktbyers** [comment]
@chocokalamay It doesn't look like you have paramiko installed correctly. Probably try:

```
python -m pip install netmiko
```

**Comment by chocokalamay** [comment]
@ktbyers 
im trying to execute your command but it gives me error when downloading the package.


C:\Users\lester.parcon>python -m pip install netmiko
Collecting netmiko
  Using cached netmiko-1.3.0.tar.gz
Collecting paramiko>=1.13.0 (from netmiko)
  Using cached paramiko-2.1.2-py2.py3-none-any.whl
Collecting scp>=0.10.0 (from netmiko)
  Using cached scp-0.10.2-py2.py3-none-any.whl
Collecting pyyaml (from netmiko)
  Using cached PyYAML-3.12.tar.gz
Collecting cryptography>=1.1 (from paramiko>=1.13.0->netmiko)
  Using cached cryptography-1.8.1.tar.gz
Collecting pyasn1>=0.1.7 (from paramiko>=1.13.0->netmiko)
  Using cached pyasn1-0.2.3-py2.py3-none-any.whl
Collecting idna>=2.1 (from cryptography>=1.1->paramiko>=1.13.0->netmiko)
  Using cached idna-2.5-py2.py3-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography>=1.1->paramiko>=1.13.0->netmiko)
  Using cached asn1crypto-0.22.0-py2.py3-none-any.whl
Collecting packaging (from cryptography>=1.1->paramiko>=1.13.0->netmiko)
  Using cached packaging-16.8-py2.py3-none-any.whl
Collecting six>=1.4.1 (from cryptography>=1.1->paramiko>=1.13.0->netmiko)
  Using cached six-1.10.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools>=11.3 in c:\users\lester.parcon\appdata\local\programs\python\python35\lib\site-packages (from cryptography>=1.1->paramiko>=1.13.0->netmiko)
Collecting cffi>=1.4.1 (from cryptography>=1.1->paramiko>=1.13.0->netmiko)
  Using cached cffi-1.10.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\LESTER~1.PAR\AppData\Local\Temp\pip-build-0k2bad4y\cffi\setup.py", line 113, in <module>
        if sys.platform == 'win32' and uses_msvc():
      File "C:\Users\LESTER~1.PAR\AppData\Local\Temp\pip-build-0k2bad4y\cffi\setup.py", line 91, in uses_msvc
        return config.try_compile('#ifndef _MSC_VER\n#error "not MSVC"\n#endif')
      File "C:\Users\lester.parcon\AppData\Local\Programs\Python\Python35\lib\distutils\command\config.py", line 227, in try_compile
        self._compile(body, headers, include_dirs, lang)
      File "C:\Users\lester.parcon\AppData\Local\Programs\Python\Python35\lib\distutils\command\config.py", line 133, in _compile
        self.compiler.compile([src], include_dirs=include_dirs)
      File "C:\Users\lester.parcon\AppData\Local\Programs\Python\Python35\lib\distutils\_msvccompiler.py", line 315, in compile
        self.initialize()
      File "C:\Users\lester.parcon\AppData\Local\Programs\Python\Python35\lib\distutils\_msvccompiler.py", line 208, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "C:\Users\lester.parcon\AppData\Local\Programs\Python\Python35\lib\distutils\_msvccompiler.py", line 81, in _get_vc_env
        vcvarsall, vcruntime = _find_vcvarsall(plat_spec)
      File "C:\Users\lester.parcon\AppData\Local\Programs\Python\Python35\lib\distutils\_msvccompiler.py", line 34, in _find_vcvarsall
        access=winreg.KEY_READ | winreg.KEY_WOW64_32KEY
    FileNotFoundError: [WinError 2] The system cannot find the file specified

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\LESTER~1.PAR\AppData\Local\Temp\pip-build-0k2bad4y\cffi
You are using pip version 7.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by ktbyers** [comment]
Looks like you have an issue installing the cryptography library (which is a dependency of the paramiko library). 

You might want to look here and see if it helps:

https://cryptography.io/en/latest/installation/

You also might want to try the install in a clean virtual environment

**Comment by manishrawat221** [comment]
not able to connect  to device below is my code :--


from netmiko import ConnectHandler
from getpass import getpass
import sys

f = open("IP_Add")
for line in f:
   print "Configuring in Device having IP " + (line)
   HOST = line

   iosv_l2 = {
       'device_type': 'cisco_ios',
       'ip': 'HOST',
       'username': raw_input("Enter username: "),
       'password': getpass(),
   }
   net_connect = ConnectHandler(**iosv_l2)
   output = net_connect.send_command('show ip int brief')
   print output

   config_commands = ['int loop 10', 'ip address 10.1.1.1 255.255.255.0', 'end'
, 'wr' ]
   output = net_connect.send_config_set(config_commands)
   print output

**Comment by sandeepkhera** [comment]
> not able to connect to device below is my code :--
> 
> from netmiko import ConnectHandler
> from getpass import getpass
> import sys
> 
> f = open("IP_Add")
> for line in f:
> print "Configuring in Device having IP " + (line)
> HOST = line
> 
> iosv_l2 = {
> 'device_type': 'cisco_ios',
> 'ip': 'HOST',
> 'username': raw_input("Enter username: "),
> 'password': getpass(),
> }
> net_connect = ConnectHandler(**iosv_l2)
> output = net_connect.send_command('show ip int brief')
> print output
> 
> config_commands = ['int loop 10', 'ip address 10.1.1.1 255.255.255.0', 'end'
> , 'wr' ]
> output = net_connect.send_config_set(config_commands)
> print output
> 
> and below is the error coming when running code after it prompt for password
> 
> Enter username: cisco
> Password:
> Traceback (most recent call last):
> File "test2", line 18, in
> net_connect = ConnectHandler(**iosv_l2)
> File "/usr/local/lib/python2.7/dist-packages/netmiko/ssh_dispatcher.py", line 218, in ConnectHandler
> return ConnectionClass(*args, **kwargs)
> File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 270, in **init**
> self.establish_connection()
> File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 787, in establish_connection
> raise NetMikoTimeoutException(msg)
> netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios HOST:22

Is this solved for you. I am getting same error on Windows....
With same Python and Netmiko version the code works fine on Linux.

**Comment by ShaifulShaon** [comment]
I am having this problem for my python code. I have tried for many solutions but all in vain .Please help me in this case


 Traceback (most recent call last):
 File "C:\Users\shaif\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\netmiko\base_connection.py", line 1137, in establish_connection
  self.remote_conn_pre.connect(**ssh_connect_params)
 File "C:\Users\shaif\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\paramiko\client.py", line 386, in connect
  sock.connect(addr)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "E:\Python codes\lab2.py", line 25, in <module>
  connection=ConnectHandler(**device)
        ^^^^^^^^^^^^^^^^^^^^^^^^
 File "C:\Users\shaif\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\netmiko\ssh_dispatcher.py", line 399, in ConnectHandler
  return ConnectionClass(*args, **kwargs)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "C:\Users\shaif\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\netmiko\base_connection.py", line 488, in __init__
  self._open()
 File "C:\Users\shaif\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\netmiko\base_connection.py", line 493, in _open
  self.establish_connection()
 File "C:\Users\shaif\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\netmiko\base_connection.py", line 1159, in establish_connection
  raise NetmikoTimeoutException(msg)

Common causes of this problem are:
1. Incorrect hostname or IP address.
2. Wrong TCP port.
3. Intermediate firewall blocking access.

Device settings: cisco_ios 192.168.20.8:22

**Comment by ktbyers** [comment]
@ShaifulShaon 

Here:

```python
iosv_l2 = {
'device_type': 'cisco_ios',
'ip': 'HOST',
'username': raw_input("Enter username: "),
'password': getpass(),
}
```

Here, you are using 'HOST' just as a string and you are not actually using the HOST variable.
