### ISSUE TITLE
Authentication failure: unable to connect cisco_ios [ip] ('Bad authentication type', ['']) (allowed_types=[''])

### ISSUE THREAD

**Issue by NedySuprianto** [ktbyers/netmiko#450]
hii kirk, i still got a same issue here.

_**code :**_ 
from netmiko import ConnectHandler

device = {
    'device_type': 'cisco_s300',
    'ip': '10.10.10.10',
    'username': 'username',
    'password': 'password',
}
net_connect = ConnectHandler(**device)
output = net_connect.send_command_expect("show run")
print(output)

_**error :**_ 

Traceback (most recent call last):
  File "C:\Users\Nedy Suprianto\python\lib\site-packages\netmiko\base_connection.py", line 501, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "C:\Users\Nedy Suprianto\python\lib\site-packages\paramiko\client.py", line 381, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "C:\Users\Nedy Suprianto\python\lib\site-packages\paramiko\client.py", line 622, in _auth
    raise saved_exception
  File "C:\Users\Nedy Suprianto\python\lib\site-packages\paramiko\client.py", line 609, in _auth
    self._transport.auth_password(username, password)
  File "C:\Users\Nedy Suprianto\python\lib\site-packages\paramiko\transport.py", line 1276, in auth_password
    return self.auth_handler.wait_for_response(my_event)
  File "C:\Users\Nedy Suprianto\python\lib\site-packages\paramiko\auth_handler.py", line 208, in wait_for_response
    raise e
paramiko.ssh_exception.BadAuthenticationType: ('Bad authentication type', ['']) (allowed_types=[''])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Nedy Suprianto/PycharmProjects/project/switch_s300.py", line 10, in <module>
    net_connect = ConnectHandler(**device)
  File "C:\Users\Nedy Suprianto\python\lib\site-packages\netmiko\ssh_dispatcher.py", line 120, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\Nedy Suprianto\python\lib\site-packages\netmiko\base_connection.py", line 151, in __init__
    self.establish_connection()
  File "C:\Users\Nedy Suprianto\python\lib\site-packages\netmiko\base_connection.py", line 510, in establish_connection
    raise NetMikoAuthenticationException(msg)
netmiko.ssh_exception.NetMikoAuthenticationException: Authentication failure: unable to connect cisco_s300 192.168.100.100:22
('Bad authentication type', ['']) (allowed_types=[''])

**_login ssh using Putty :_** 

**login as:** admin  // i confused with this part, in code i just have username and password variable, that leads to 'User Name' and 'Password' for user login. should i add new argument in device variabel?

****User Name:**nedy
**Password:************

switch9bd4b4#

**Comment by ktbyers** [comment]
@NedySuprianto Did you configure this on the switch (needs manually configured):

```
ip ssh password-auth
```

Basically, that extra `login as` is messing things up and configuring that should make it go away.

**Comment by NedySuprianto** [comment]
now its work :), but i also want to ask you somethings kirk, its about send_command() method, i have nexus 700 cisco switch witch is the core switch i want to grab all the 'show tech'  using send_commnd_expect('show tech') and i got a error message. i try use send_command() and same error should i use send_commnad_timing() and add the delay_factor to grab all show tech?
i already used putty to get all show tech and the size of the file is about 300mb

**_code_**

from netmiko import ConnectHandler
device = dict(device_type='cisco_nxos',
              ip='10.10.10.10',
              username='admin',
              password='password',
              )

net_connect = ConnectHandler(**device)
output = net_connect.send_command_expect('show tech')
print(output)

**_error_** 

Traceback (most recent call last):
  File "C:/Users/Nedy Suprianto/PycharmProjects/project/switch_s300.py", line 10, in <module>
    output = net_connect.send_command_expect('show tech')
  File "C:\Users\Nedy Suprianto\python\lib\site-packages\netmiko\base_connection.py", line 820, in send_command_expect
    return self.send_command(*args, **kwargs)
  File "C:\Users\Nedy Suprianto\python\lib\site-packages\netmiko\base_connection.py", line 812, in send_command
    search_pattern))
OSError: Search pattern never detected in send_command_expect: SW_DC\-NEW_Nexus_01\#

**Comment by ktbyers** [comment]
@NedySuprianto You probably need to keep increasing delay_factor until send_command_expect works.

`show tech` takes a long time to execute.

Try something like.

```
net_connect.send_command_expect('show tech', delay_factor=4)
```

Keep doubling delay_factor until it works. By default send_command_expect will wait for about 90 seconds before it gives up.
