### ISSUE TITLE
Cant load netmiko

### ISSUE THREAD

**Issue by networkguy22** [ktbyers/netmiko#458]
```
>>> import netmiko
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build\bdist.win32\egg\netmiko\__init__.py", line 8, in <module>
  File "build\bdist.win32\egg\netmiko\ssh_dispatcher.py", line 3, in <module>
  File "build\bdist.win32\egg\netmiko\cisco\__init__.py", line 2, in <module>
  File "build\bdist.win32\egg\netmiko\cisco\cisco_ios.py", line 3, in <module>
  File "build\bdist.win32\egg\netmiko\cisco_base_connection.py", line 3, in <module>
  File "build\bdist.win32\egg\netmiko\base_connection.py", line 13, in <module>
  File "build\bdist.win32\egg\paramiko\__init__.py", line 30, in <module>
  File "build\bdist.win32\egg\paramiko\transport.py", line 33, in <module>
ImportError: No module named cryptography.hazmat.backends
```

Any suggestions on how to resolve? The files are located in my C:\Python27 dir.

**Comment by ktbyers** [comment]
@networkguy22 I would probably try the following from the Windows prompt:

```
python -m pip install cryptography==1.8.1
```

Then try to import netmiko again and see what happens.

Just re-open this issue again if you still have issues.

**Comment by networkguy22** [comment]
For future readers this worked. Thank you as always for the help Kirk.
