### ISSUE TITLE
device type = cisco_ios_telnet - reverse telnet

### ISSUE THREAD

**Issue by jdimstrnate** [ktbyers/netmiko#496]
I am newer to python and have read the documentation but can't identify how to make netmiko enter credentials more than once when prompts are seen.  

trying to telnet to a Terminal Server to validate console ports via script.  
ranging from telnet ports 2051-2063   Only trying one port at the moment.
Error shows **actively refused** however I tested connection from same box using telnet and it works.  

====================================================

import netmiko
import json
device = input('Please input device IP:  ')
device_type = 'cisco_ios'
user = 'uuuuuuuu'
pw = 'xxxxxxxx!'

SSH = netmiko.ConnectHandler(ip='10.232.7.194', device_type='cisco_ios_telnet', username='uuuuuuuu',password='xxxxxxxx!')
SSH.read_channel()

print('########################################################################################')
print('Connecting to port: ', ports2051 , 'on device: ', device)
print('########################################################################################')
SSH.send_command_expect('username:',user)
SSH.send_command_expect('password:',pw)
SSH.send_command('\n')
SSH.send_command_expect('username:',user)
SSH.send_command_expect('password:',pw)
print(SSH.send_command('show ip int br'))

========================================================
ERROR SHOWN BELOW
========================================================
Traceback (most recent call last):
  File "C:/Users/v-nademe.REDMOND/Netmiko_Training/__init__.py", line 40, in <module>
    SSH = netmiko.ConnectHandler(ip='10.232.7.194', device_type='cisco_ios_telnet', username='UUUUUUUU',password='XXXXXXX!')
  File "C:\Python36-32\lib\site-packages\netmiko\ssh_dispatcher.py", line 124, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Python36-32\lib\site-packages\netmiko\base_connection.py", line 128, in __init__
    self.establish_connection()
  File "C:\Python36-32\lib\site-packages\netmiko\base_connection.py", line 494, in establish_connection
    self.remote_conn = telnetlib.Telnet(self.host, port=self.port, timeout=self.timeout)
  File "C:\Python36-32\lib\telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "C:\Python36-32\lib\telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "C:\Python36-32\lib\socket.py", line 722, in create_connection
    raise err
  File "C:\Python36-32\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

Process finished with exit code 1

========================================================
EXPECTED PROMPTS SEEN
========================================================

username: UUUU
password:  XXXXXX
  
NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE  
  
This is a private network device.  If you are not authorized to  
access this device, disconnect at once!  Actual or attempted use,  
access, examination, or configuration change by an unauthorized  
person external to the Corporation will result in criminal and civil  
prosecution to the fullest extent of the law. Unauthorized login  
attempts by internal personnel will be reported immediately to the  
violator's management and may result in disciplinary action.  
  
NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE  
  

User Access Verification

Password:

**Comment by ktbyers** [comment]
@jdimstrnate You probably need to add the `port` into the connection (otherwise Netmiko will assume port 23)

```
SSH = netmiko.ConnectHandler(ip='10.232.7.194', device_type='cisco_ios_telnet', 
                                                     port=2051, username='uuuuuuuu',password='xxxxxxxx!')
```

Let me know if that works?

**Comment by laurentlgm** [comment]
I'm trying to reverse telnet directly to the serial port of a cisco router that is connected to a juniper console port. 
In the example above would be the equivalent to "telnet 10.232.7.194 2051"
To do that I get two user/password prompts in sequence: First from the cisco that is acting as a terminal server then from the Juniper that is controlling who gets access to its console.

I've tried using netmiko with the the generic_termserver device type but it didn't work as I believe it is still looking for a router prompt after the first authentication.
The debug logs show that it goes in a loop when it gets hit by the juniper login banner.
My workaround was to first telnet to the cisco router on port 23 and then telnet again to the serial port with expect commands.
I need to do that in hundreds of devices...is there a better/quicker way to do reverse telnet with netmiko?
here's my workaround code:


logging.basicConfig(filename='/tmp/netmiko.log', level=logging.DEBUG)
logger = logging.getLogger('netmiko')


def termserv(user, pwd, enablepw, ip, port):
    output = 'error'
    device_tmpl = {
            'device_type': 'generic_termserver_telnet',
             'ip': '',
             'username': 'test',
             'password': 'password',
             'port': 23,
             'secret': 'secret',
             'verbose': False,
    }
    try:
        device_tmpl['ip'] = ip
        session = connect(device_tmpl, user, pwd, enablepw)
        print('logging into ts...')
        session.send_command_expect('telnet ' + ip + ' ' + port, 'name:')
        session.send_command_expect(user, 'assword:')
        session.write_channel(pwd)
        session.write_channel('\n')
        time.sleep(1)
        prompt = session.read_channel()
        print(prompt)
        if 'ogin:' in prompt:
            print('junos login prompt...')
            session.send_command_expect('moraes','assword:')
            session.write_channel('Cheetara01\n')
            time.sleep(1)
        #redispatch(session, device_type='juniper') --> that breaks it in a way I can't get the output
        output = session.send_command('show config | match host-name')
        output = output + '\n' + session.send_command('show lldp nei')
        session.disconnect() #--> this keeps the Juniper connection open  which is a security risk but it 
                                           # I send "exit" then I fall back to the login prompt and netmiko hangs.
    except Exception as err:
        print(' Error --> ' + str(err))
    return output

**Comment by laurentlgm** [comment]
I think I'm never hitting this: https://github.com/ktbyers/netmiko/blob/develop/netmiko/base_connection.py#L381

After entering the password for the first time, netmiko is expecting to get either '#' or '>' but instead it gets the huge banner that is setup on the Juniper device. 
From the log:

```
DEBUG:netmiko:read_channel: ***********************

/folder/env/Shift/bin/shift juniper-device-name 
************************************

This is a Management device, to perform traffic failover do the following:

Fail Away:
************************************************************

shift juniper-device-name --away

************************************************************

Fail Back:
************************************************************

shift juniper-device-name --back

*************************************

This is a Management device, to perform traffic failover do the following:

Fail Away:
************************************************************

shift juniper-device-name --away

************************************************************

Fail Back:
************************************************************

-device-name --back
```

The huge banner finishes with a "login:" prompt but netmiko never gets to that part...maybe because it is sending TELNET_RETURN faster than the banner can finish loading?
Seems like it loops the 60 times and then finishes by raising "Telnet login failed: <ip>" message.
I'll try to maybe change the user regex to r"sername|ogin" and the delay factor to 5...

**Comment by laurentlgm** [comment]
Yep, that worked like a charm. Added .5 to the delay_factor and "ogin" to the user pattern:
```
    def telnet_login(self, pri_prompt_terminator='#', alt_prompt_terminator='>',
                     username_pattern=r"sername|ogin", pwd_pattern=r"assword",
                     delay_factor=1.5, max_loops=60)
```

Here's the new code that does reverse telnet directly to the Juniper device (as long as the same user/pass can be used for both the cisco terminal server and Juniper target device):
```
def termserv(user, pwd, enablepw, ip, port):
    output = 'error'
    device_tmpl = {
            'device_type': 'generic_termserver_telnet',
             'ip': '',
             'username': 'test',
             'password': 'password',
             'port': 23,
             'secret': 'secret',
             'verbose': False,
    }
    try:
        device_tmpl['ip'] = ip
        session = connect(device_tmpl, user, pwd, enablepw)
        output = session.send_command('show config | match host-name')
        output = output + '\n' + session.send_command('show lldp nei')
        session.disconnect() #--> this keeps the Juniper connection open  which is a security risk but if 
         # I send "exit" then I fall back to the login prompt and netmiko hangs.
    except Exception as err:
        print(' Error --> ' + str(err))
    return output
```
I'm still leaving the user logged as I get out...I there a way to fix logout before disconnecting?
Plus, it seems that I'm delaying everything by .5 on the base_connection... it would be good to have this delay_factor as part of the device template maybe?

**Comment by ktbyers** [comment]
@laurentlgm 
You could probably do something like this:

```
output += session.send_command_timing('exit')
```

That will cause you to exit and not hang. 

Note, this is not closing your terminal server connection so that terminal server line is not in use. If you want to exit from that, you will have to manually handle it (i.e. send the special sequence to break out of that terminal server connection).

**Comment by laurentlgm** [comment]
@ktbyers
I had tried 'exit' but it hangs for 500 loop cycles because it goes back to the juniper login screen where netemiko does not find the prompt: https://github.com/ktbyers/netmiko/blob/develop/netmiko/base_connection.py#L785

Log:
```
[...]
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
[...]
```
It then finally fails out after the 500 read cycles with "Search pattern never detected in send_command_expect: user\@device >"

Tried the ctrl + ] escape sequence as '\x1d' but it seems to type that on the Juniper prompt which just returns "unknown command."

I though about using send_command_timing after setting a max_loop = 1 but I guess I didn't do it right because it complained of max_loop in the device template. Also, it would still get me the ""Search pattern..." exception message.

I feel I might not be sending the '\x1d' break sequence correctly but that also will not give me a prompt. 
Is there a way to skip the prompt check maybe?
(Awesome module btw)

**Comment by ktbyers** [comment]
@laurentlgm Adding some notes to this discussion mostly for future reference.

For this pattern you should use the `generic_termserver_telnet` and then manually handle the telnet login (and then redispatch). 

I made this change to the `generic_termserver` so that by default the terminal server telnet driver does NOT log you into the device:

https://github.com/ktbyers/netmiko/commit/2b273764fe5cf262571049c03c361201ed9c9c11 search for terminal_server.

After that change is made, you will need to either manually call `net_connect.std_login()` (where net_connect is the Netmiko connection object) or manually handle the telnet login. In both cases you should `redispatch` after done.

I will probably integrate your PR in for the default telnet login (PR #524) in. It is somewhat of an accidental artifact that this code actually logs you in. In other words, it is not intentionally designed to handle multiple levels of authentication.
