### ISSUE TITLE
device_type dell_force10 results in kwargs['device_type'] not in platforms

### ISSUE THREAD

**Issue by ebmarquez** [ktbyers/netmiko#532]
Hello, I'm attempting to use a ConnectHandler() with a **dell_force10** in json input and it results in the following error:

```
from netmiko import ConnectHandler
dell = {
 'device_type': 'dell_force10',
 'ip': '192.168.0.10',
 'username': 'admin',
 'password': 'P@ssw0rd1'
 }

net_connect = ConnectHandler(dell)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/netmiko/ssh_dispatcher.py", line 127, in ConnectHandler
    if kwargs['device_type'] not in platforms:
KeyError: u'device_type'

```
I checked my python dest-packages/netmiko/ssh_dispatcher.py file and I do see the device type of 'dell_force10' in the list.  Any suggestions to get past this error.

```
Python Version: Python 2.7.12 (default, Nov 19 2016, 06:48:10)
Packages:
['ansible==2.3.0.0', 'ecdsa==0.13', 'httplib2==0.9.1', 'ipaddr==2.1.11', 'ipaddress==1.0.18', 'jinja2==2.8', 'markupsafe==0.23', 'netmiko==1.4.2', 'paramiko==1.16.0', 'pip==9.0.1', 'pycrypto==2.6.1', 'pyyaml==3.11', 'scp==0.10.2', 'setuptools==20.7.0', 'six==1.10.0', 'wheel==0.29.0']

```
Linux Version:

```
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Comment by ebmarquez** [comment]
figured out why it failed, I needed to put the ** with the ConnectHandler(**dell).

**Comment by seetharambeereddy** [comment]
instead of giving dell .try with dell_3.40(as device model)
