### ISSUE TITLE
netmiko use send_config_set configuration huawei device  and save it 

### ISSUE THREAD

**Issue by 191801737** [ktbyers/netmiko#538]
there is my code by python
```
def switch_config(ip):
    huawei_switch = {
        'device_type': 'huawei',
        'ip':   ip,
        'username': 'huawei',
        'password': 'huawei5720',
    }
    net_connect = ConnectHandler(**huawei_switch)
    config_commands = ['ntp-service unicast-server 10.14.32.249',
                       'info-center loghost 10.100.18.57'
                       ]
    output = net_connect.send_config_set(config_commands)
    net_connect.disconnect()
    return output

print(switch_config('10.106.0.106'))


system-view
Enter system view, return user view with Ctrl+Z.
[huawei5720]ntp-service unicast-server 10.14.32.249
[huawei5720]info-center loghost 10.100.18.57
Warning: There is security risk as this operation enables a non secure syslog protocol.
[huawei5720]return
<huawei5720>

Process finished with exit code 0
```

when i want to save the device configuration  but it not work well 
```
def switch_config(ip):
    huawei_switch = {
        'device_type': 'huawei',
        'ip':   ip,
        'username': 'huawei',
        'password': 'huawei5720',
    }
    net_connect = ConnectHandler(**huawei_switch)
    config_commands = ['ntp-service unicast-server 10.14.32.249',
                       'info-center loghost 10.100.18.57',
                       'return',
                       'save'
                       ]
    output = net_connect.send_config_set(config_commands)
    net_connect.disconnect()
    return output

print(switch_config('10.106.0.106'))


```Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/paramiko/channel.py", line 683, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/buffered_pipe.py", line 160, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 282, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/channel.py", line 685, in recv
    raise socket.timeout()
socket.timeout
etc...

**Comment by ktbyers** [comment]
@191801737 Netmiko will automatically do the return.

...so don't do the `return` or the `save` inside the `send_config_set`

Do the `save` using the `send_command` method separately.

**Comment by 191801737** [comment]
ths i will try it ..
