### ISSUE TITLE
how to change the cisco switch hostname 

### ISSUE THREAD

**Issue by 191801737** [ktbyers/netmiko#540]
there  is my python code  
```
        cisco_ios = {
            'device_type': 'cisco_ios',
            'ip': ip,
            'username': username,
            'password': password,
        }
        net_connect = ConnectHandler(**cisco_ios)
        output = net_connect.send_config_set('hostname cc2999')
        net_connect.disconnect()
        return output
```
when i run the code  the cisco switch hostname has changed 
but the code return something 
```

`Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/paramiko/channel.py", line 683, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/buffered_pipe.py", line 160, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 282, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/channel.py", line 685, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wl30564/ITSuper-Portal/server/ping01.py", line 34, in <module>
    print(config_mode('10.101.24.241', 'cisco', 'cisco2960'))
  File "/home/wl30564/ITSuper-Portal/server/ping01.py", line 20, in config_mode
    output = net_connect.send_config_set('hostname cc2999')
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 969, in send_config_set
    output += self.exit_config_mode()
  File "/usr/local/lib/python3.5/dist-packages/netmiko/cisco_base_connection.py", line 50, in exit_config_mode
    pattern=pattern)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 919, in exit_config_mode
    if self.check_config_mode():
  File "/usr/local/lib/python3.5/dist-packages/netmiko/cisco_base_connection.py", line 32, in check_config_mode
    pattern=pattern)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 900, in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 338, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 289, in _read_channel_expect
    raise NetMikoTimeoutException("Timed-out reading channel, data not available.")
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.
`

```

**Comment by ktbyers** [comment]
@191801737 Try (exit_config_mode=False)

```
        cisco_ios = {
            'device_type': 'cisco_ios',
            'ip': ip,
            'username': username,
            'password': password,
        }
        net_connect = ConnectHandler(**cisco_ios)
        output = net_connect.send_config_set('hostname cc2999', exit_config_mode=False)
        output += net_connect.send_command_timing('end')
        net_connect.disconnect()
        return output
```

**Comment by ktbyers** [comment]
Re-open if the above doesn't work.
