### ISSUE TITLE
RequirementParseError & net_connect.enable() timing error?

### ISSUE THREAD

**Issue by superloopnetwork** [ktbyers/netmiko#541]
Hi All,

I'm a bit lost as to what the issue is.. It's intermittent.. Sometimes it works (barely) and most times it fails so I suspect it may have something to do with timing in how fast the program processes vs the remote SSH device... When it fails, I get this message... 

`<Thread(Thread-1, started 140234025518848)>
No handlers could be found for logger "paramiko.transport"
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "ntw_auto_tools.py", line 155, in config_backup
    self.net_connect = ConnectHandler(self.ip,self.hostname,self.username,self.decrypt_password,self.sfo_secret,device_type=self.device_call())
  File "/usr/local/lib/python2.7/dist-packages/netmiko/ssh_dispatcher.py", line 131, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 150, in __init__
    self.establish_connection()
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 502, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 338, in connect
    t.start_client()
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 493, in start_client
    raise e
RequirementParseError: Invalid requirement, parse error at "''"`

I do get another error at times (intermittent on Arista and Cisco because they both need to access the enable mode), and this is what I receive as a message:

`Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "ntw_auto_tools.py.clean.py", line 163, in config_backup
    output = self.net_connect.enable()
  File "/usr/local/lib/python2.7/dist-packages/netmiko/cisco_base_connection.py", line 17, in enable
    return super(CiscoBaseConnection, self).enable(cmd=cmd, pattern=pattern, re_flags=re_flags)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 874, in enable
    self.write_channel(self.normalize_cmd(self.secret))
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 855, in normalize_cmd
    command = command.rstrip("\n")
AttributeError: 'function' object has no attribute 'rstrip'`

Here is my class for Arista and the class for Cisco is the same..

`class AristaPlatform(BasePlatform):

        def config_backup(self):

                self.connect()
                print()
                print('#' * 80)
                output = self.net_connect.enable()       # <------------- LINE 163
                output = self.net_connect.send_command_expect("show running-config")
                print output
                f.write(output)
                f.close()
                print('#' * 80)
                self.net_connect.disconnect()
                print()`

Have anyone came across this error message before?

Thanks!

**Comment by superloopnetwork** [comment]
I think this issue may be related to https://github.com/ktbyers/netmiko/issues/386

**Comment by ktbyers** [comment]
On issue # 1, are you passing in your arguments as named arguments or positional arguments:

```
ConnectHandler(self.ip, self.hostname, self.username, 
 self.decrypt_password, self.sfo_secret, device_type=self.device_call() )
```

Don't use positional arguments, only use named arguments. Also you should have either `ip` or `hostname` not both?

Can you reproduce the issue without threads?


On issue # 2, I would make sure you are passing in a secret using a named argument `secret="secret"`. It looks like something is happening and you are no longer passing in a string in a certain context (i.e. a function is being passed in instead)?

I am going to remove the link to issue 386 as I don't think that it is helpful.
