### ISSUE TITLE
Reload Commands Not Working

### ISSUE THREAD

**Issue by aponteju** [ktbyers/netmiko#544]
I am using the asa_upgrade script provided here (https://github.com/ktbyers/netmiko/blob/master/examples/asa_upgrade.py). I modified this to perform upgrades on HA pairs. I first tried issuing "failover reload-standby" from the active firewall, but nothing seemed to happen. I then changed it to adding a second connection to the standby firewall and issuing a reload from that connection. This also didn't have any effect on the firewall (I had a separate SSH connection going at the same time to monitor activity).

I also tried issuing commands from the python CLI and they did not take. The "output = conn.send_command('reload')" line never returned anything, it hung until I hit CTRL+C. Interestingly enough, I then reconnected to the device and tried to issue a "show boot", at which point the firewall started rebooting itself. Time between was about 15-20 minutes. Is there a delay in issuing this command at all? I wouldn't think so.

After hitting CTRL+C, I get the following traceback:

`^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/netmiko/cisco/cisco_asa_ssh.py", line 51, in send_command
    output = super(CiscoAsaSSH, self).send_command(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/netmiko/base_connection.py", line 807, in send_command
    time.sleep(delay_factor * .2)
`

**Comment by aponteju** [comment]
I should also mention that I am using Python 3.5, in case that matters.

**Comment by aponteju** [comment]
Another trace

`Traceback (most recent call last):`
`  File "asa_upgrade.py", line 87, in <module>`
`    main()`
`  File "asa_upgrade.py", line 79, in main`
`    output += ssh_conn.send_command('reload')`
`  File "/usr/local/lib/python3.5/site-packages/netmiko/cisco/cisco_asa_ssh.py", line 51, in send_command`
`    output = super(CiscoAsaSSH, self).send_command(*args, **kwargs)`
`  File "/usr/local/lib/python3.5/site-packages/netmiko/base_connection.py", line 811, in send_command`
`    search_pattern))`
`OSError: Search pattern never detected in send_command_expect: ciscoasa\#`

**Comment by aponteju** [comment]
@ktbyers I actually solved this by changing the `reload` and `y` commands to `send_command_timing`.
