### ISSUE TITLE
How to define a function that takes netmiko.ConnectHandler object as an argument

### ISSUE THREAD

**Issue by amangoel6** [ktbyers/netmiko#565]
I want to create two files. One file for my main function where I will open an ssh connection to my devices and in another file I want to create supporting functions that should  take netmiko.ConnectHandler object as an argument so that I can use it to send command to the devices and return some value to my main function in another file when I call it.
Secondly, where can I see the source code for netmiko functions/methods. please.
If possible please give me a small example.

**Comment by ktbyers** [comment]
Answered via email.

**Comment by mrosiNTS** [comment]
@ktbyers may you kindly share here in this thread your answer at the previous message? 

I've the same problem, i'd like to have a function that has the only task of open the SSH sessions with some devices, and then in the main or into other functions use those SSH sessions to send commands, configure device, avoiding to open each time a session via netmiko.ConnectHandler per each access in read/write to a device.

Many thanks,
Mario

**Comment by ktbyers** [comment]
```python
def my_function(net_connect):
    print(net_connect.find_prompt())
```

The print statement is just showing you an example of using the already open connection. `net_connect` is the Netmiko connection object.

**Comment by mrosiNTS** [comment]
Thanks @ktbyers
 
the problem is that using this code below (just a part of it, the rest re-propose the same problems), i don't know what, but something is not working once used the parallelization framework; if i don't use the parallelization instead, everything is fine.

def clean_interface_config (remote_conn):

    intf = 0
    num_max_interfaces = 2

    for intf in range(num_max_interfaces):
        Interface_commands = ['default interface gigabitEthernet 0/{0}'.format(intf), 'exit']
        remote_conn.send_config_set(Interface_commands)

def main():

    start_time = datetime.now()
    
    processes = []
    procs = []
    a_device = []
    i = 0

# open multiple SSH sessions

    remote_connection = []
    a_device = []

    for a_device in all_devices:
        remote_conn = ConnectHandler(**a_device)
        remote_connection.append(remote_conn)

# config cleaning (interfaces and OSPF)

    for a_device in all_devices:
        my_proc = Process(target=clean_interface_config, args=(remote_connection[i],))
        i +=1
        my_proc.start()
        procs.append(my_proc)

from the log from routers i get:

ROUTER1#
*Sep 24 17:12:33.523: %SSH-3-BAD_PACK_LEN: Bad packet length -1098871223

...and from python:

...
Process Process-5:
Process Process-4:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "./Netmiko3_Parallel.py", line 45, in clean_interface_config
    remote_conn.send_config_set(Interface_commands)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netmiko/base_connection.py", line 1292, in send_config_set
    output = self.config_mode(*cfg_mode_args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netmiko/cisco_base_connection.py", line 42, in config_mode
    pattern=pattern)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netmiko/base_connection.py", line 1207, in config_mode
    self.write_channel(self.normalize_cmd(config_command))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netmiko/base_connection.py", line 290, in write_channel
    self._write_channel(out_data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netmiko/base_connection.py", line 268, in _write_channel
    self.remote_conn.sendall(write_bytes(out_data))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/channel.py", line 831, in sendall
    sent = self.send(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/channel.py", line 785, in send
    return self._send(s, m)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/channel.py", line 1180, in _send
    self.transport._send_user_message(m)
  File "./Netmiko3_Parallel.py", line 45, in clean_interface_config
    remote_conn.send_config_set(Interface_commands)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/transport.py", line 1727, in _send_user_message
    self._send_message(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/transport.py", line 1707, in _send_message
    self.packetizer.send_message(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netmiko/base_connection.py", line 1292, in send_config_set
    output = self.config_mode(*cfg_mode_args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/packet.py", line 398, in send_message
    self.write_all(out)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netmiko/cisco_base_connection.py", line 42, in config_mode
    pattern=pattern)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/packet.py", line 340, in write_all
    raise EOFError()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netmiko/base_connection.py", line 1207, in config_mode
    self.write_channel(self.normalize_cmd(config_command))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netmiko/base_connection.py", line 290, in write_channel
    self._write_channel(out_data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netmiko/base_connection.py", line 268, in _write_channel
    self.remote_conn.sendall(write_bytes(out_data))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/channel.py", line 831, in sendall
    sent = self.send(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/channel.py", line 785, in send
    return self._send(s, m)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/channel.py", line 1180, in _send
    self.transport._send_user_message(m)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/transport.py", line 1727, in _send_user_message
    self._send_message(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/transport.py", line 1707, in _send_message
    self.packetizer.send_message(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/packet.py", line 398, in send_message
    self.write_all(out)
EOFError
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/packet.py", line 340, in write_all
    raise EOFError()
EOFError
Process Process-7:
Process Process-8:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
...

Do you have any ideas about the root cause of that behavior?

many thanks,
Mario

**Comment by ktbyers** [comment]
@mrosiNTS You probably should look into Nornir if you are interested in doing concurrency with Netmiko.
