### ISSUE TITLE
Issues getting netmiko to run

### ISSUE THREAD

**Issue by RushTalz** [ktbyers/netmiko#581]
I'm trying to get NetMiko installed and running my linux system (Linux Mint, release 18).  I followed the instructions from the install instructions here:  https://pynet.twb-tech.com/blog/automation/netmiko-tools.html

However, I hit a snag when I tried to run the last command: 

rush@Minty-VM ~ $ netmiko-show --list-devices
Traceback (most recent call last):
  File "/home/rush/netmiko_tools/netmiko_tools/netmiko-show", line 181, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/rush/netmiko_tools/netmiko_tools/netmiko-show", line 93, in main
    my_devices = load_devices()
  File "/usr/local/lib/python2.7/dist-packages/netmiko/utilities.py", line 58, in load_devices
    yaml_devices_file = find_cfg_file(file_name)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/utilities.py", line 74, in find_cfg_file
    raise IOError("{}: file not found in current dir or home dir.".format(base_file))
IOError: .netmiko.yml: file not found in current dir or home dir.

Any help with what I missed or did wrong?

**Comment by ktbyers** [comment]
You need to create a file in your home directory named .netmiko.yml.

See the inventory section in this article:

https://pynet.twb-tech.com/blog/automation/netmiko-grep.html

**Comment by RushTalz** [comment]
Hey Kirk - 

thank you much for the response, really appreciated.  Got the file created with a couple devices in my network, looking much better :)
