### ISSUE TITLE
SSH to PAN-OS 8.0

### ISSUE THREAD

**Issue by mathewfer** [ktbyers/netmiko#583]
Hi 

Can someone please share a working SSH script to PAN-OS 8.0 to go to "configure" mode?

Mathewfer

**Comment by ktbyers** [comment]
@mathewfer What happens when you try to use the `send_config_set` method?

```
from netmiko import ConnectHandler

p_alto = {
    'device_type': 'paloalto_panos',
    'ip':   '10.10.10.10',
    'username': 'test',
    'password': 'password',
    'port' : 22,          # optional, defaults to 22
}

net_connect = ConnectHandler(**p_alto)
config_cmd = 'some config command'
output = net_connect.send_config_set(config_cmd)
```

**Comment by PANW-ANZ** [comment]
@ktbyers got the below error when I run the script 
>>> net_connect = ConnectHandler(**pa220)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "netmiko/ssh_dispatcher.py", line 218, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "netmiko/base_connection.py", line 271, in __init__
    self._try_session_preparation()
  File "netmiko/base_connection.py", line 650, in _try_session_preparation
    self.session_preparation()
  File "netmiko/paloalto/paloalto_panos.py", line 22, in session_preparation
    self.set_base_prompt(delay_factor=20)
  File "netmiko/base_connection.py", line 959, in set_base_prompt
    raise ValueError("Router prompt not found: {0}".format(repr(prompt)))
ValueError: Router prompt not found: u'Number of failed attempts since last successful login: 0'

**Comment by ktbyers** [comment]
@bartoqid Can you show what a manual SSH-CLI session to this device looks like?

The below message from the device looks like it is causing an issue?
```
Number of failed attempts since last successful login: 0
```

**Comment by wuwenhao2000** [comment]
I have the same problem
net_connect = ConnectHandler(device_type='paloalto_panos', ip='10.34.15.1'', username=setting['user'], password= setting['pwd'], verbose=True)
output = net_connect.send_command("show vpn flow")

Traceback (most recent call last):
  File "panos_test.py", line 11, in <module>
    net_connect = ConnectHandler(device_type='paloalto_panos', ip='10.34.15.1', username=setting['user'], password= setting['pwd'], verbose=True)
  File "/Users/wewu/Documents/auto_net/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 228, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/Users/wewu/Documents/auto_net/lib/python2.7/site-packages/netmiko/base_connection.py", line 313, in __init__
    self._try_session_preparation()
  File "/Users/wewu/Documents/auto_net/lib/python2.7/site-packages/netmiko/base_connection.py", line 723, in _try_session_preparation
    self.session_preparation()
  File "/Users/wewu/Documents/auto_net/lib/python2.7/site-packages/netmiko/paloalto/paloalto_panos.py", line 23, in session_preparation
    self.set_base_prompt(delay_factor=20)
  File "/Users/wewu/Documents/auto_net/lib/python2.7/site-packages/netmiko/base_connection.py", line 1042, in set_base_prompt
    raise ValueError("Router prompt not found: {0}".format(repr(prompt)))
ValueError: Router prompt not found: u'Number of failed attempts since last successful login: 0'

**Comment by carlmontanari** [comment]
I believe this is pretty old and has been sorted! Closing.

**Comment by lospinoj** [comment]
Hello, Do you recall exactly how this problem was solved? J-

**Comment by ktbyers** [comment]
@lospinoj You probably need to create a new issue if you are still running into a problem here.


Kirk
