### ISSUE TITLE
unable to import Netmiko in RHEL

### ISSUE THREAD

**Issue by richc2012** [ktbyers/netmiko#632]
I have used Netmiko with a lot of success from Ubuntu and Windows but now I am trying to set up the RHEL box that our Linux admin set up for me but I am getting the below error when I try to import ConnectHandler, I used pip to install netmiko. any help would be appreciated.

Python 2.7.5 (default, Aug  2 2016, 04:20:16)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from netmiko import ConnectHandler
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/netmiko/__init__.py", line 8, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "/usr/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 4, in <module>
    from netmiko.a10 import A10SSH
  File "/usr/lib/python2.7/site-packages/netmiko/a10/__init__.py", line 2, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "/usr/lib/python2.7/site-packages/netmiko/a10/a10_ssh.py", line 3, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "/usr/lib/python2.7/site-packages/netmiko/cisco_base_connection.py", line 3, in <module>
    from netmiko.base_connection import BaseConnection
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 13, in <module>
    import paramiko
  File "/usr/lib/python2.7/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 38, in <module>
    from paramiko.auth_handler import AuthHandler
  File "/usr/lib/python2.7/site-packages/paramiko/auth_handler.py", line 48, in <module>
    from paramiko.ssh_gss import GSSAuth, GSS_EXCEPTIONS
  File "/usr/lib/python2.7/site-packages/paramiko/ssh_gss.py", line 54, in <module>
    GSS_EXCEPTIONS = (gssapi.GSSException,)
AttributeError: 'module' object has no attribute 'GSSException'
>>>

**Comment by ktbyers** [comment]
It is a paramiko issue, see:

https://github.com/paramiko/paramiko/issues/1069

I would try to upgrade your paramiko installation and see if that fixes it.

```
pip install paramiko==2.4.0
```

**Comment by richc2012** [comment]
paramiko was already at 2.4 but i reinstalled anyway, didn't fix, skimming through #1069 it looks like its better to just not have gssapi installed, I used pip uninstall gssapi and now I can import connecthandler with no errors, do you forsee this causing me any issues down the road?

**Comment by ktbyers** [comment]
Probably not...I assume Paramiko will fix it in the not to distant future.

**Comment by richc2012** [comment]
cool, thanks! btw I want to take the moment to thank you for all of your work on network Automation, I work in an environment of nearly 3000 network devices (routers and switches, not counting phones AP's or anything else) with a few months practice I have been able to make changes as simple as adding vlans to rectifying things like telnet on devices, hitting thousands off devices at a time. ive used in large part much of your publications and it has saved me countless man hours! thank you!

**Comment by ktbyers** [comment]
@richc2012 That is great!
