### ISSUE TITLE
File transfer fails on dir() command on IOS

### ISSUE THREAD

**Issue by mjuenema** [ktbyers/netmiko#647]
I am still in the process of researching this but at least on Cisco IOS 15.x the `CiscoBaseConnection._autodetect_()` method fails because the `dir` command is not working in "EXEC" mode. 
```
router1>dir
Translating "dir"
% Unknown command or computer name, or unable to find computer address

router1>enable
Password: 
router1#dir
Directory of flash:/

    2  -rwx        1076   Mar 1 1993 13:35:15 +10:00  config.recover
    4  -rwx        4069   Dec 6 2017 12:24:11 +10:00  config.text
  750  -rwx        3824   Dec 6 2017 12:24:11 +10:00  private-config.text
    5  -rwx        3096   Dec 6 2017 12:24:11 +10:00  multiple-fs
    6  drwx        1024   Mar 1 1993 10:00:37 +10:00  ies-ipservicesk9-mz.150-2.EY3

64094208 bytes total (38810624 bytes free)
```

**Comment by ktbyers** [comment]
@mjuenema Can you show me Python your stack trace?

Is this a file transfer issue or an auto-detection issue (or both)

**Comment by mjuenema** [comment]
I am going to provide more detail when I have access to my development environment again, which won't be until in about six(!) weeks time.

**Comment by ktbyers** [comment]
@mjuenema Any update on this?

**Comment by mjuenema** [comment]
Not, I didn't get to it yet.

**Comment by mjuenema** [comment]
**Example**

The script below...

```
from netmiko import ConnectHandler, FileTransfer

config = {
  'device_type': 'cisco_ios',
  'ip':   '10.1.1.26',
  'username': 'admin',
  'password': 'password',
  'port' : 22,          # optional, defaults to 22
  'secret': 'enable',     # optional, defaults to ''
  'verbose': False,       # optional, defaults to False
}

ssh_conn = ConnectHandler(**config)

with FileTransfer(ssh_conn, 'somefile', 'somefile') as scp_transfer:
    print scp_transfer.check_file_exists()
```

...will give the following output.

```
Traceback (most recent call last):
  File "example1.py", line 17, in <module>
    with FileTransfer(ssh_conn, 'somefile', 'somefile') as scp_transfer:
  File "/home/mjuenemann/.virtualenvs/netmiko_issue_647/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 199, in FileTransfer
    return FileTransferClass(*args, **kwargs)
  File "/home/mjuenemann/.virtualenvs/netmiko_issue_647/lib/python2.7/site-packages/netmiko/scp_handler.py", line 63, in __init__
    self.file_system = self.ssh_ctl_chan._autodetect_fs()
  File "/home/mjuenemann/.virtualenvs/netmiko_issue_647/lib/python2.7/site-packages/netmiko/cisco_base_connection.py", line 163, in _autodetect_fs
    "system: {} {}".format(cmd, output))
ValueError: An error occurred in dynamically determining remote file system: dir Translating "dir"
% Unknown command or computer name, or unable to find computer address
```
But if I add an explicit `enable`...
```
from netmiko import ConnectHandler, FileTransfer                                          
                                                                                          
config = {                                                                                
  'device_type': 'cisco_ios',                                                             
  'ip':   '10.1.1.26',                                                                    
  'username': 'admin',                                                                    
  'password': 'password',                                                                 
  'port' : 22,          # optional, defaults to 22                                        
  'secret': 'enable',     # optional, defaults to ''                                      
  'verbose': False,       # optional, defaults to False                                   
}                                                                                         
                                                                                          
ssh_conn = ConnectHandler(**config)                                                       
ssh_conn.enable()       # <=======                                                        
                                                                                          
with FileTransfer(ssh_conn, 'somefile', 'somefile') as scp_transfer:                      
    print scp_transfer.check_file_exists()  
```
...it will work fine.
```
False
```
Of course, in the end that's really a user privilege issue. Cisco seemed to have changed that between IOS 12.x and 15.x.

**Comment by ktbyers** [comment]
Yes, SCP will always require enable mode both for the dir and for the actual secure copy file transfer. 

I guess we could add an error check on the FileTransfer method that will generate an exception if you aren't already in enable mode (and a clear message).

Do you want to submit a PR on this?

**Comment by mjuenema** [comment]
No worries, I'll have a go at it later this week.

**Comment by mjuenema** [comment]
`NetMikoAuthenticationException` or `NetMikoAuthError`? Which one is the more appropriate exception?

**Comment by ktbyers** [comment]
There is no `NetMikoAuthError`???

So `NetMikoAuthenticationException` is the more appropriate.
