### ISSUE TITLE
Issue with using .enable() with Arista devices

### ISSUE THREAD

**Issue by BigPat** [ktbyers/netmiko#650]
I am having an issue with using the .enable() function with Arista devices.   For example when I use my net_connect variable as my connection handler I will then use "net_connect.enable()" and it fails every time.  

I tried using "arista_eos" and "cisco_ios" as the device types, it works with both to connect to the devices but they cannot enter privileged mode with the net_connect.enable() command.  When I use typical cisco IOS and IOS-XE devices the net_connect.enable() works without any issues.

Note that the "net_connect.send_command" function works perfect as well.  

I have searched everywhere for a good example or someone else with this issue and cannot find anything close.  

I reviewed your guide and tutorials to no avail.  Any help would be great!

**CODE STARTS HERE**

```
import netmiko
import sys
import xlsxwriter  # Used for Output Excel file
from datetime import datetime

ios_ver = 'arista_eos'  # I usually use a pop-up button box for this
hostname = input('Enter your Username') # I use a popup box for this
password = input('Enter your Password') # I use a popup box for this
secret1 = password
hostlist = open(file=hostfile, mode='r')  # Reads in list of IP Addresses (hosts file)

print('-------------------')

for ipaddress in hostlist:
    ipaddress = ipaddress.strip()`

    try:  
        print('Device Check Started:', datetime.now().time())
        net_connect = netmiko.ConnectHandler(device_type=ios_ver, ip=ipaddress, username=username,
                                             password=password, port=22, secret=secret1, verbose=False)

    except netmiko.NetMikoAuthenticationException:
        print('Invalid Credentials: ', ipaddress)
        print('--- ')
        out_worksheet1.write(row, 0, ipaddress, failed_format)
        out_worksheet1.write(row, 1, 'Invalid Credentials: Connection Failed ', failed_format)

        row += 1
        time.sleep(0.25)
        continue

    except netmiko.NetMikoTimeoutException:
        print('SSH Error: Connection Failed: ', ipaddress)
        print('--- ')
        out_worksheet1.write(row, 0, ipaddress, failed_format)
        out_worksheet1.write(row, 1, 'SSH Connection Error', failed_format)
        row += 1
        time.sleep(0.25)
        continue

    except:
        print('Connection Failed For Unknown Reason: ', ipaddress)
        print('--- ')
        out_worksheet1.write(row, 0, ipaddress, failed_format)
        out_worksheet1.write(row, 1, 'Connection Failed: Unknown Reason Reference Log', failed_format)
        row += 1
        time.sleep(0.25)
        continue
    else:
        print('Connection to', ipaddress, 'established:', datetime.now().time())

    if net_connect.is_alive() == True:
        print('SSH Connection Validated:', datetime.now().time())
        try:
            net_connect.enable()  # THIS IS FAILING EVERY TIME

        except:
            print('')
            print('Unable to Enter Privileged Mode for', ipaddress)
            print('')

        out_worksheet1.write(row, 0, ipaddress, normal_format2)

        hostname = net_connect.send_command('show hostname | inc Hostname', delay_factor=2)
        hostname = hostname[10:]
        out_worksheet1.write_string(row, 1, hostname, normal_format2)
        host_timestamp(hostname, 'Started')  # This is a timstamp function from the top of the program

        commandlist2 = open(file=cmdfile, mode='r')

        for command in commandlist2: 
            command = command.strip()

            if 'copy' in command:
                try:
                    output2 = net_connect.send_command(command, delay_factor=2)
                    out_worksheet1.write(row, col, output2, normal_format)
                    print(command, 'Entered at:', datetime.now().time())
                    time.sleep(1)
                    print('---')
                    col += 1
                except:
                    print('Command Failed: Check Command File Syntax')
                    out_worksheet1.write(row, col, 'Command Failed to Run', failed_format)
                    time.sleep(1)
                    print('---')
                    col += 1
                    continue

            elif 'write' in command:
                try:
                    output2 = net_connect.send_command(command, delay_factor=2)
                    out_worksheet1.write(row, col, output2, normal_format)
                    print(command, 'Entered at:', datetime.now().time())
                    time.sleep(1)
                    print('---')
                    col += 1
                except:
                    print('Command Failed: Check Command File Syntax')
                    out_worksheet1.write(row, col, 'Command Failed to Run', failed_format)
                    time.sleep(1)
                    print('---')
                    col += 1
                    continue

            elif 'show' in command:
                try:
                    output2 = net_connect.send_command(command, delay_factor=2)
                    out_worksheet1.write(row, col, output2, normal_format)
                    print(command, 'Entered at:', datetime.now().time())
                    time.sleep(1)
                    print('---')
                    col += 1
                except:
                    print('Command Failed: Check Command File Syntax')
                    out_worksheet1.write(row, col, 'Command Failed to Run', failed_format)
                    time.sleep(1)
                    print('---')
                    col += 1
                    continue

            else:
                try:
                    print('Entered Configure Terminal for', command)
                    net_connect.config_mode()  # Enters configuration mode
                    print(net_connect.check_config_mode())  # prints if in config mode
                    output1 = net_connect.send_command(command, delay_factor=2)  # Sends change command
                    out_worksheet1.write(row, col, output1, configt_format)
                    net_connect.send_command('exit', delay_factor=2)  # Exits configuration mode
                    net_connect.check_enable_mode()  # Checks to see if back in enable mode
                    print(command, 'Entered at:', datetime.now().time())
                    time.sleep(1)
                    print('---')
                    col += 1

                except:
                    print('Command Failed: Check Command File Syntax')
                    out_worksheet1.write(row, col, 'Command Failed to Run', failed_format)
                    time.sleep(1)
                    print('---')
                    col += 1
                    continue

        col = 2  # Resets the column for the next host back to column 0 (or column A) Do NOT move this

    else:
        print('Connection Error', ipaddress)

    host_timestamp(hostname, 'Completed')  # This is a timestamp function from the top of the program
    print('-------------------')

    net_connect.disconnect() 
    row += 1  # Adds row to excel spreadsheet after previous device finishes having commands outputed
```

**Comment by ktbyers** [comment]
@BigPat Can you post the exception that happens when you try to go into .enable()

Note, you will have to probably get rid of your `try / except` so that the actual exception occurs.

```
        try:
            net_connect.enable()  # THIS IS FAILING EVERY TIME

        except:
            print('')
            print('Unable to Enter Privileged Mode for', ipaddress)
            print('')
```

**Comment by BigPat** [comment]
@ktbyers I removed the try statement and below is all of the returned error lines, I bolded exceptions and things that I thought may be related possibly.  

```
-------------------
Device Check Started: 19:34:50.321182
Connection to _x.x.x.x_ established: 19:35:11.696504
SSH Connection Validated: 19:35:11.696504

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\channel.py", line 665, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\buffered_pipe.py", line 160, in read
    raise PipeTimeout()
**paramiko.buffered_pipe.PipeTimeout**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\netmiko\base_connection.py", line 313, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\channel.py", line 667, in recv
    raise socket.timeout()
**socket.timeout**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/user/PycharmProjects/HygieneAutomation/ComplexConfigProgramv1.0/Dev Testing Program/devarista.py", line 371, in <module>
    net_connect.enable()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\netmiko\cisco_base_connection.py", line 17, in enable
    return super(CiscoBaseConnection, self).enable(cmd=cmd, pattern=pattern, re_flags=re_flags)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\netmiko\base_connection.py", line 887, in enable
    if not self.check_enable_mode():
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\netmiko\cisco_base_connection.py", line 13, in check_enable_mode
    return super(CiscoBaseConnection, self).check_enable_mode(check_string=check_string)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\netmiko\base_connection.py", line 880, in check_enable_mode
    output = self.read_until_prompt()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\netmiko\base_connection.py", line 364, in read_until_prompt
    return self._read_channel_expect(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\netmiko\base_connection.py", line 320, in _read_channel_expect
    raise **NetMikoTimeoutException**("Timed-out reading channel, data not available.")
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.
Exception ignored in: <bound method Workbook.__del__ of <xlsxwriter.workbook.Workbook object at 0x0000017D5BBBE908>>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\xlsxwriter\workbook.py", line 153, in __del__
Exception: Exception caught in workbook destructor. Explicit close() may be required for workbook.
```

**Comment by BigPat** [comment]
@ktbyers  Note that I also tried adding "global_delay_factor=2" to my net_connect connect handler and "session_preparation()" and I still get the same exceptions.  I have triple checked my code and tested it on cisco_ios with other cisco devices and it works just fine.  

```
        net_connect = netmiko.ConnectHandler(device_type=ios_ver, ip=ipaddress, username=username,
                                             password=password, port=22, secret=secret1, verbose=False,
                                             global_delay_factor=2)
        net_connect.session_preparation()
```

**Comment by BigPat** [comment]
@ktbyers I found the solution.  Kind of odd solution but I had to move the net_connect.enable() under the connectHandler.  Take a look at the code below you will see where I moved it to and where I moved it from.  

That combined with the global_delay_factor=2 could have done it.  Either way it works now, I just hope that it works with the rest of my script.  We will see!!

Thanks for the help!

```
for ipaddress in hostlist:
    ipaddress = ipaddress.strip()

    try:  # Ignore the errors shown for ios_ver and username, this is because they are not defined yet
        print('Device Check Started:', datetime.now().time())
        net_connect = netmiko.ConnectHandler(device_type=ios_ver, ip=ipaddress, username=username,
                                             password=password, port=22, secret=secret1, verbose=False,
                                             global_delay_factor=2)
        net_connect.session_preparation()
        net_connect.enable()  #MOVED net_connect.enable() TO HERE, FIXED ISSUE

    except netmiko.NetMikoAuthenticationException:
        print('Invalid Credentials: ', ipaddress)
        print('--- ')
        out_worksheet1.write(row, 0, ipaddress, failed_format)
        out_worksheet1.write(row, 1, 'Invalid Credentials: Connection Failed ', failed_format)

        row += 1
        time.sleep(0.25)
        continue

    except netmiko.NetMikoTimeoutException:
        print('SSH Error: Connection Failed: ', ipaddress)
        print('--- ')
        out_worksheet1.write(row, 0, ipaddress, failed_format)
        out_worksheet1.write(row, 1, 'SSH Connection Error', failed_format)
        row += 1
        time.sleep(0.25)
        continue

    except:
        print('Connection Failed For Unknown Reason: ', ipaddress)
        print('--- ')
        out_worksheet1.write(row, 0, ipaddress, failed_format)
        out_worksheet1.write(row, 1, 'Connection Failed: Unknown Reason Reference Log', failed_format)
        row += 1
        time.sleep(0.25)
        continue
    else:
        print('Connection to', ipaddress, 'established:', datetime.now().time())

    # This is where the Connection is validated and commands begin to be entered
    if net_connect.is_alive() == True:

        print('SSH Connection Validated:', datetime.now().time())
        # MOVED net_connect.enable() FROM HERE 

```
