### ISSUE TITLE
Issue with connecting to Huawei devices

### ISSUE THREAD

**Issue by ogenstad** [ktbyers/netmiko#652]
Opening this to remember myself. I'm seeing some issues when using Netmiko from Brigade against Huawei devices.

```
Traceback (most recent call last):
  File "/home/paog01/.virtualenvs/scratch27/lib/python2.7/site-packages/brigade/core/__init__.py", line 146, in run_task
    r = task._start(host=host, brigade=brigade, dry_run=brigade.dry_run)
  File "/home/paog01/.virtualenvs/scratch27/lib/python2.7/site-packages/brigade/core/task.py", line 39, in _start
    return self.task(self, **self.params)
  File "<stdin>", line 5, in collect
  File "/home/paog01/.virtualenvs/scratch27/lib/python2.7/site-packages/brigade/plugins/tasks/networking/netmiko_run.py", line 38, in netmiko_run
    with ConnectHandler(**parameters) as net_connect:
  File "/home/paog01/.virtualenvs/scratch27/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 131, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/paog01/.virtualenvs/scratch27/lib/python2.7/site-packages/netmiko/base_connection.py", line 152, in __init__
    self.session_preparation()
  File "/home/paog01/.virtualenvs/scratch27/lib/python2.7/site-packages/netmiko/huawei/huawei_ssh.py", line 14, in session_preparation
    self.set_base_prompt()
  File "/home/paog01/.virtualenvs/scratch27/lib/python2.7/site-packages/netmiko/huawei/huawei_ssh.py", line 67, in set_base_prompt
    if not prompt[-1] in (pri_prompt_terminator, alt_prompt_terminator):
IndexError: string index out of range
```

I typically get this against 20 or so devices out of 2500, and not the same 20 on each run. Might be some timing issue. Probably the `prompt` is "".

**Comment by ktbyers** [comment]
So it is failing on set.base_prompt(). Netmiko is expecting the last character to be either '>' or '#'.

Yes, the prompt must be coming back as a null string for some reason.

It sounds like probably a timing issue (as you mentioned).

**Comment by igormartymov** [comment]
Expiriencing the same issue. Is there a workaround? Maybe to set_base_prompt() manually before executing command?

**Comment by ktbyers** [comment]
I am going to close this...if someone sees this again please comment here and we can re-open.

**Comment by lutfisan** [comment]
```
Traceback (most recent call last):
  File "/home/cacti/miniconda3/envs/ipam/lib/python3.7/site-packages/nornir/core/task.py", line 85, in start
    r = self.task(self, **self.params)
  File "/home/cacti/miniconda3/envs/ipam/lib/python3.7/site-packages/nornir/plugins/tasks/networking/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection("netmiko", task.nornir.config)
  File "/home/cacti/miniconda3/envs/ipam/lib/python3.7/site-packages/nornir/core/inventory.py", line 302, in get_connection
    extras=conn.extras,
  File "/home/cacti/miniconda3/envs/ipam/lib/python3.7/site-packages/nornir/core/inventory.py", line 352, in open_connection
    configuration=configuration,
  File "/home/cacti/miniconda3/envs/ipam/lib/python3.7/site-packages/nornir/plugins/connections/netmiko.py", line 58, in open
    self.connection = ConnectHandler(**parameters)
  File "/home/cacti/miniconda3/envs/ipam/lib/python3.7/site-packages/netmiko/ssh_dispatcher.py", line 246, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/cacti/miniconda3/envs/ipam/lib/python3.7/site-packages/netmiko/base_connection.py", line 317, in __init__
    self._open()
  File "/home/cacti/miniconda3/envs/ipam/lib/python3.7/site-packages/netmiko/base_connection.py", line 323, in _open
    self._try_session_preparation()
  File "/home/cacti/miniconda3/envs/ipam/lib/python3.7/site-packages/netmiko/base_connection.py", line 738, in _try_session_preparation
    self.session_preparation()
  File "/home/cacti/miniconda3/envs/ipam/lib/python3.7/site-packages/netmiko/huawei/huawei.py", line 14, in session_preparation
    self.set_base_prompt()
  File "/home/cacti/miniconda3/envs/ipam/lib/python3.7/site-packages/netmiko/huawei/huawei.py", line 73, in set_base_prompt
    if not prompt[-1] in (pri_prompt_terminator, alt_prompt_terminator):
IndexError: string index out of range
```
@ktbyers hi I get this issue

**Comment by ktbyers** [comment]
@lutfisan What is your router/switch prompt (i.e. what does it your router prompt look like  from the CLI)?
