### ISSUE TITLE
Unable to SSH to device

### ISSUE THREAD

**Issue by Swandip** [ktbyers/netmiko#655]
@ktbyers 

I am trying to access the file IPAddressList and create new file for every ip in the list with few 'show outputs'

I am trying the below script:

from __future__ import print_function
from netmiko import ConnectHandler
import sys
import time
import select
import paramiko
import re
import getpass

  
platform = 'cisco_nxos'
username = 'admin' # edit to reflect
password = getpass.getpass()

ip_add_file = open('IPAddressList','r') # a simple list of IP addresses you want to connect to each one on a new line

base='/Users/admin/Desktop/123/'
for host in ip_add_file:
    host = host.strip()
    wh=open(base+host+".txt",'w')
    device = ConnectHandler(device_type=platform, ip=host, username=username, password=password)
    output = device.send_command('terminal length 0')
    wh.write('##############################################################\n')
    wh.write('...................CISCO COMMAND SHOW RUN OUTPUT......................\n')
    output = device.send_command('sh run')
    wh.write(output)
    wh.write('##############################################################\n')
    wh.write('...................CISCO COMMAND SHOW IP INT BR OUTPUT......................\n')
    output = device.send_command('sh ip int br')
    wh.write(output) 
    wh.write('##############################################################\n')
    wh.close()

ip_add_file.close()

IPAddressList have three IP inside it :
10.1.1.1
10.2.2.2
10.3.3.3

when I am running the command it works for 1st ip from the list and create the file successfully but from the second ip it starts failing because it doesn't prompt for inputing the password again 

macOS:Desktop$ python script\ for\ show.py 
Password:        <<<<<< It prompts for the 1st Ip password.
Traceback (most recent call last):
  File "script for show.py", line 22, in <module>
    device = ConnectHandler(device_type=platform, ip=host, username=username, password=password)
  File "/Library/Python/2.7/site-packages/netmiko/ssh_dispatcher.py", line 131, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/netmiko/base_connection.py", line 151, in __init__
    self.establish_connection()
  File "/Library/Python/2.7/site-packages/netmiko/base_connection.py", line 541, in establish_connection
    raise NetMikoAuthenticationException(msg)
netmiko.ssh_exception.NetMikoAuthenticationException: Authentication failure: unable to connect cisco_nxos 10.2.2.2:22
Authentication failed.-macOS:Desktop$ 

Thanks a ton in advance.

**Comment by Swandip** [comment]
I got the solution thank you....
