### ISSUE TITLE
Error Importing ConnectHandler

### ISSUE THREAD

**Issue by malbaqari** [ktbyers/netmiko#667]
Hello,

I am using python 3.5.2. When running my script, I am getting the follow trace.

Traceback (most recent call last):
  File "C:\Users\mohammed.baqari\workspace\Test_lab\Testing_Coding.py", line 1, in <module>
    from netmiko import ConnectHandler
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\netmiko\__init__.py", line 8, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\netmiko\ssh_dispatcher.py", line 4, in <module>
    from netmiko.a10 import A10SSH
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\netmiko\a10\__init__.py", line 2, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\netmiko\a10\a10_ssh.py", line 4, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\netmiko\cisco_base_connection.py", line 3, in <module>
    from netmiko.base_connection import BaseConnection
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\netmiko\base_connection.py", line 24, in <module>
    from netmiko.utilities import write_bytes, check_serial_port, get_structured_data
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\netmiko\utilities.py", line 9, in <module>
    import clitable
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\clitable.py", line 34, in <module>
    import texttable
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\texttable.py", line 34, in <module>
    import terminal
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\terminal.py", line 28, in <module>
    import fcntl
ImportError: No module named 'fcntl'

**Comment by ktbyers** [comment]
https://github.com/ktbyers/netmiko/issues/659

I will try to get a new release out shortly.
