### ISSUE TITLE
Importing Netmiko

### ISSUE THREAD

**Issue by tugaba** [ktbyers/netmiko#733]
Hi Experts,

I read the previous posts about importing netmiko but none of the solutions have worked for me as such. I am a Network Security Professional and like many, trying hands on python. So in short new to programming. After going thru some basics of python I am trying to orchestrate changes in my simulated GNS network. My Virtual Adapters can talk to the GNS Routers/ASAs. 

Now I did an install of the Python 3.6, have interpreter and idle installed. have access to python form cmd(windows 7). I have netmiko downloaded as a zip and I have extracted the ZIP. Where should one be saving the extracted files? I have them in my default C

When I run the command 

```
>>> pip install netmiko
  File "<stdin>", line 1
    pip install netmiko
              ^
SyntaxError: invalid syntax
>>> python -m pip install cryptography==1.8.1
  File "<stdin>", line 1
    python -m pip install cryptography==1.8.1
                ^
SyntaxError: invalid syntax
>>> import netmiko
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'netmiko'
>>> from netmiko import ConnectHandler
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'netmiko'

```

**Comment by tugaba** [comment]
This is after I copied/pasted the extracted netmiko files in the Python folder

>>> python -m pip install cryptography==1.8.1
  File "<stdin>", line 1
    python -m pip install cryptography==1.8.1
                ^
SyntaxError: invalid syntax
>>> import netmiko
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Cisco\AppData\Local\Programs\Python\Python36-32\netmiko\__init_
_.py", line 8, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "C:\Users\Cisco\AppData\Local\Programs\Python\Python36-32\netmiko\ssh_dis
patcher.py", line 4, in <module>
    from netmiko.a10 import A10SSH
  File "C:\Users\Cisco\AppData\Local\Programs\Python\Python36-32\netmiko\a10\__i
nit__.py", line 2, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "C:\Users\Cisco\AppData\Local\Programs\Python\Python36-32\netmiko\a10\a10
_ssh.py", line 4, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "C:\Users\Cisco\AppData\Local\Programs\Python\Python36-32\netmiko\cisco_b
ase_connection.py", line 3, in <module>
    from netmiko.base_connection import BaseConnection
  File "C:\Users\Cisco\AppData\Local\Programs\Python\Python36-32\netmiko\base_co
nnection.py", line 13, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
>>>

**Comment by tugaba** [comment]
>>> from netmiko import ConnectHandler
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Cisco\AppData\Local\Programs\Python\Python36-32\netmiko\__init_
_.py", line 8, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "C:\Users\Cisco\AppData\Local\Programs\Python\Python36-32\netmiko\ssh_dis
patcher.py", line 4, in <module>
    from netmiko.a10 import A10SSH
  File "C:\Users\Cisco\AppData\Local\Programs\Python\Python36-32\netmiko\a10\__i
nit__.py", line 2, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "C:\Users\Cisco\AppData\Local\Programs\Python\Python36-32\netmiko\a10\a10
_ssh.py", line 4, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "C:\Users\Cisco\AppData\Local\Programs\Python\Python36-32\netmiko\cisco_b
ase_connection.py", line 3, in <module>
    from netmiko.base_connection import BaseConnection
  File "C:\Users\Cisco\AppData\Local\Programs\Python\Python36-32\netmiko\base_co
nnection.py", line 13, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'

**Comment by tugaba** [comment]
More you try you end up doing something about it || Thump Rule of being a TAC engineer in the past.

This is where I have reached now..

>>> import netmiko
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Cisco\AppData\Local\Programs\Python\Python36-32\netmiko\__init_
_.py", line 8, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "C:\Users\Cisco\AppData\Local\Programs\Python\Python36-32\netmiko\ssh_dis
patcher.py", line 4, in <module>
    from netmiko.a10 import A10SSH
  File "C:\Users\Cisco\AppData\Local\Programs\Python\Python36-32\netmiko\a10\__i
nit__.py", line 2, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "C:\Users\Cisco\AppData\Local\Programs\Python\Python36-32\netmiko\a10\a10
_ssh.py", line 4, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "C:\Users\Cisco\AppData\Local\Programs\Python\Python36-32\netmiko\cisco_b
ase_connection.py", line 3, in <module>
    from netmiko.base_connection import BaseConnection
  File "C:\Users\Cisco\AppData\Local\Programs\Python\Python36-32\netmiko\base_co
nnection.py", line 13, in <module>
    import paramiko
  File "C:\Users\Cisco\AppData\Local\Programs\Python\Python36-32\paramiko\__init
__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "C:\Users\Cisco\AppData\Local\Programs\Python\Python36-32\paramiko\transp
ort.py", line 33, in <module>
    from cryptography.hazmat.backends import default_backend
ModuleNotFoundError: No module named 'cryptography'
>>> import cryptography
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cryptography'

**Comment by tugaba** [comment]
Downloaded different cryptographic modules, still failing with same error.

**Comment by tugaba** [comment]
Getting further :)
ModuleNotFoundError: No module named 'pyasn1'

**Comment by tugaba** [comment]
Another one now

  File "C:\Users\Cisco\AppData\Local\Programs\Python\Python36-32\paramiko\ed2551
9key.py", line 22, in <module>
    import nacl.signing
ModuleNotFoundError: No module named 'nacl'
>>> ^Z


C:\>pip install nacl
Collecting nacl
  Could not find a version that satisfies the requirement nacl (from versions: )

No matching distribution found for nacl

**Comment by ktbyers** [comment]
@tugaba What happens when you do a:

```
python -m pip install netmiko
```

From the windows command prompt (you cannot be inside the Python shell when you do this).

**Comment by tugaba** [comment]
You gotta be kidding me right, invested 10 hours on this and you cracked it in few seconds. I want to learn more now. Do you have a course offering to not only understand python more but also explore more and more from the Networks perspective. Currently working on Cisco SDA Solution where a lot of Pxgrid, APIs are involved.

![image](https://user-images.githubusercontent.com/37069911/37017257-f4d48b7e-2135-11e8-9dda-5df2fd5ebc9f.png)

**Comment by tugaba** [comment]
Also one thing, it works but what was I missing before, why those errors before? Just for better self understanding.

**Comment by ktbyers** [comment]
@tugaba Yes, I have this course starting next week https://pynet.twb-tech.com/class.html

**Comment by ktbyers** [comment]
When you say "those errors", do you have a specific error in mind?

**Comment by ejm110** [comment]
Hi, I am on windows and tried 
`python -m pip install netmiko`
`pip install netmiko'

I get this error

> Command "c:\users\%username%\appdata\local\programs\python\python37\pyt
hon.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\%username%\\Ap
pData\\Local\\Temp\\pip-install-iq56f836\\bcrypt\\setup.py';f=getattr(tokenize,
'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compi
le(code, __file__, 'exec'))" install --record C:\Users\%username%\AppData\Loca
l\Temp\pip-record-4ghug293\install-record.txt --single-version-externally-manage
d --compile" failed with error code 1 in C:\Users\%username%\AppData\Local\Tem
p\pip-install-iq56f836\bcrypt\

**Comment by MahmoudAshoor** [comment]
Hello

I've the same problem in Ubuntu 16.04, whatever I do, I cannot import netmiko in python3.7 (it is working for 2.7) :
:~$ python3
Python 3.7.0 (default, Jul 30 2018, 12:25:40) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import netmiko
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'netmiko'

In Python 2.7 : 
~$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import netmiko
>>> 

I've tried to update, remove, reinstall with no luck. I appreciate if someone could help

Regards

**Comment by ktbyers** [comment]
The error indicates, you don't have Netmiko installed.

```
python3 -m pip install netmiko
```

Then try it again.

**Comment by e-thibault** [comment]
Hello I have the exact same situation in ubuntu 16.04
I have issued :
python3 -m pip install netmiko
I had the reply :
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-za4f6yn5/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-o9fehnkx-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-za4f6yn5/cryptography/

and also :
You are using pip version 8.1.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

I upgraded pip using : pip install --upgrade pip
the upgrade work but after I still have the same message :
You are using pip version 8.1.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

and when I want to check If I have netmiko for python3 I get :

thibault@R2D2compact:~$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from netmiko import ConnectHandler
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'netmiko'
>>> 

what should I do then  to have netmiko for python3 ?

**Comment by rawatkuldeep23** [comment]
i ran the script:

from netmiko import Netmiko

connection = Netmiko(host='10.223.128.23', port ='23', username = 'admin, password = 'Password@123', device_type = 'cisco_ios')

and getting below output:

C:\Users\200845\PycharmProjects\My_Project\venv\Scripts\python.exe C:/Users/200845/PycharmProjects/My_Project/sonu.py
Traceback (most recent call last):
  File "C:/Users/200845/PycharmProjects/My_Project/sonu.py", line 1, in <module>
    from netmiko import Netmiko
  File "C:\Users\200845\PycharmProjects\My_Project\venv\lib\site-packages\netmiko\__init__.py", line 7, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "C:\Users\200845\PycharmProjects\My_Project\venv\lib\site-packages\netmiko\ssh_dispatcher.py", line 2, in <module>
    from netmiko.a10 import A10SSH
  File "C:\Users\200845\PycharmProjects\My_Project\venv\lib\site-packages\netmiko\a10\__init__.py", line 1, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "C:\Users\200845\PycharmProjects\My_Project\venv\lib\site-packages\netmiko\a10\a10_ssh.py", line 3, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "C:\Users\200845\PycharmProjects\My_Project\venv\lib\site-packages\netmiko\cisco_base_connection.py", line 2, in <module>
    from netmiko.base_connection import BaseConnection
  File "C:\Users\200845\PycharmProjects\My_Project\venv\lib\site-packages\netmiko\base_connection.py", line 18, in <module>
    import paramiko
  File "C:\Users\200845\PycharmProjects\My_Project\venv\lib\site-packages\paramiko\__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "C:\Users\200845\PycharmProjects\My_Project\venv\lib\site-packages\paramiko\transport.py", line 89, in <module>
    from paramiko.dsskey import DSSKey
  File "C:\Users\200845\PycharmProjects\My_Project\venv\lib\site-packages\paramiko\dsskey.py", line 37, in <module>
    from paramiko.pkey import PKey
  File "C:\Users\200845\PycharmProjects\My_Project\venv\lib\site-packages\paramiko\pkey.py", line 31, in <module>
    import bcrypt
  File "C:\Users\200845\PycharmProjects\My_Project\venv\lib\site-packages\bcrypt\__init__.py", line 25, in <module>
    from . import _bcrypt
ImportError: cannot import name '_bcrypt'

Process finished with exit code 1


Can @ktbyers someone please help me to understand the errors and help in fixing these errors.

Thanks..!!
