### ISSUE TITLE
Script doesn't work

### ISSUE THREAD

**Issue by RamVic** [ktbyers/netmiko#739]
Hello , I have an scipt to make a Bkp FW , Today I saw that the script dont execute , I install python3.6 and netmiko again with

>  python3.6 -m pip install netmiko

When I try to run the script I am seeing this,
root@ardc1svpla020:/ # python3.6 /tmp/Config_Routers/bkpfw.py
  File "/tmp/Config_Routers/bkpfw.py", line 19
    print host
             ^
SyntaxError: Missing parentheses in call to 'print'

And before that work without parentheses  , I think there is an issue with netmiko

My code is 

#!/usr/local/bin/python3.6
from netmiko import ConnectHandler

archivo = open('/dat/code','r')
contenido = archivo.read(9)

archiv = open('/dat/name','r')
nombre = archiv.read(8)

platform = 'cisco_asa'
host = 'xxxxxxxxxxx'
username = nombre
password = contenido
secret = contenido

print host

net_connect = ConnectHandler(device_type=platform, ip=host,username=username,password=password ,secret=secret )

hostname=net_connect.send_command_timing("show hostname")
output=net_connect.send_command_timing("copy startup-config tftp://10.54.248.56")

if 'Address or name of remote host' in output:
    output += net_connect.send_command_timing("\n")
if 'Destination filename' in output:
    output += net_connect.send_command_timing(hostname)

print output

**Comment by RamVic** [comment]
> root@ardc1svpla020:/ # python3.6
> Python 3.6.2 (default, Dec 10 2017, 01:15:24)
> [GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)] on freebsd10
> Type "help", "copyright", "credits" or "license" for more information.
> >>> #!/usr/local/bin/python
> ...
> >>> from netmiko import ConnectHandler
> >>>
> >>> archivo = open('/dat/code','r')
> >>> contenido = archivo.read(9)
> >>>
> >>> archiv = open('/dat/name','r')
> >>> nombre = archiv.read(8)
> >>>
> >>>
> ...
> >>> platform = 'cisco_asa'
> >>> host = 'xxxxxxxxxxx'
> >>> username = nombre
> >>> password = contenido
> >>> secret = contenido
> >>>
> >>>
> >>> #print host
> ...
> >>> print host
>   File "<stdin>", line 1
>     print host
>              ^
> SyntaxError: Missing parentheses in call to 'print'
> >>> print(host)
> 10.54.116.248
> >>> net_connect = ConnectHandler(device_type=platform, ip=host,username=username,password=password ,secret=secret )
> >>> hostname=net_connect.send_command_timing("show hostname")
> >>> print(hostname)
> ARDC1FW000003-Internet
> 
> 
> >>> output=net_connect.send_command_timing("copy startup-config tftp://10.54.248.56")
> >>>
> >>> if 'Address or name of remote host' in output:
> ...     output += net_connect.send_command_timing("\n")
> ... if 'Destination filename' in output:
>   File "<stdin>", line 3
>     if 'Destination filename' in output:
>      ^
> SyntaxError: invalid syntax
> >>>     output += net_connect.send_command_timing(hostname)
>   File "<stdin>", line 1
>     output += net_connect.send_command_timing(hostname)
>     ^
> IndentationError: unexpected indent
> 


I dont know what change , because before working and now not.

**Comment by tonypnode** [comment]
print(output) instead of print output

**Comment by tonypnode** [comment]
And print(host)

**Comment by RamVic** [comment]
Yes , I did it , but the command 
output=net_connect.send_command_timing("copy startup-config tftp://10.54.248.56")

if 'Address or name of remote host' in output:
... output += net_connect.send_command_timing("\n")
... if 'Destination filename' in output:
File "", line 3
if 'Destination filename' in output:
^
SyntaxError: invalid syntax
output += net_connect.send_command_timing(hostname)
File "", line 1
output += net_connect.send_command_timing(hostname)
^
IndentationError: unexpected indent


Is not working

**Comment by tonypnode** [comment]
@RamVic It's a little difficult to determine where the indent error is. Can you paste your script with markdown? (wrap your code in the comment box...) i.e. 
` ` `python (minus the spaces) 
your code here
` ` ` (minus the spaces) 

it will make the comment look like this

```python
def a_thing(some_super_cool_var):
    print(some_super_cool_var)
```

**Comment by tonypnode** [comment]
@RamVic sorry haha.. the explanation didn't print out right

put 3 ` (back ticks) followed by the language identifier "python"

take a look at https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
and look at the section on code and syntax highlighting

**Comment by RamVic** [comment]
>>> net_connect = ConnectHandler(device_type=platform, ip=host,username=username,password=password ,secret=secret )
>>> output=net_connect.send__command_timing("copy startup-config tftp://10.54.248.56")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'CiscoAsaSSH' object has no attribute 'send__command_timing'
>>>

Whyyyy say AttributeErrorrr????

**Comment by tonypnode** [comment]
@RamVic, it's difficult to assist you without seeing the code as you have written it (see my previous comment). And you also seem to have change the issue. 

I would like to recommend that you check out the netmiko slack channel, found here: https://networktocode.slack.com/messages/C0L3D8G76/

It's a perfect place to get assistance with a specific implementation

**Comment by ktbyers** [comment]
@RamVic It looks like you misspelled `send_command_timing`. It looks like you have two underscores there and not one.

It needs to be:

```
output=net_connect.send_command_timing("copy startup-config tftp://10.54.248.56")
```
