### ISSUE TITLE
paramiko signing issue

### ISSUE THREAD

**Issue by bgile** [ktbyers/netmiko#747]
I was just using netmiko a couple weeks ago with no issue, but today went to go test some stuff and nacl is having an issue in the signing process for paramiko.  All my libs are up to date, not sure what to make of this stack trace honestly, couldn't find anything solid.  Anyone have input?   Much appreciated!

Traceback (most recent call last):
  File "./get_running-config.py", line 5, in <module>
    from netmiko import ConnectHandler
  File "/usr/local/lib/python3.4/dist-packages/netmiko/__init__.py", line 8, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "/usr/local/lib/python3.4/dist-packages/netmiko/ssh_dispatcher.py", line 4, in <module>
    from netmiko.a10 import A10SSH
  File "/usr/local/lib/python3.4/dist-packages/netmiko/a10/__init__.py", line 2, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "/usr/local/lib/python3.4/dist-packages/netmiko/a10/a10_ssh.py", line 4, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "/usr/local/lib/python3.4/dist-packages/netmiko/cisco_base_connection.py", line 3, in <module>
    from netmiko.base_connection import BaseConnection
  File "/usr/local/lib/python3.4/dist-packages/netmiko/base_connection.py", line 13, in <module>
    import paramiko
  File "/usr/local/lib/python3.4/dist-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/local/lib/python3.4/dist-packages/paramiko/transport.py", line 57, in <module>
    from paramiko.ed25519key import Ed25519Key
  File "/usr/local/lib/python3.4/dist-packages/paramiko/ed25519key.py", line 22, in <module>
    import nacl.signing
  File "/usr/local/lib/python3.4/dist-packages/nacl/signing.py", line 19, in <module>
    import nacl.bindings
  File "/usr/local/lib/python3.4/dist-packages/nacl/bindings/__init__.py", line 17, in <module>
    from nacl.bindings.crypto_box import (
  File "/usr/local/lib/python3.4/dist-packages/nacl/bindings/crypto_box.py", line 27, in <module>
    crypto_box_SEEDBYTES = lib.crypto_box_seedbytes()
AttributeError: cffi library '_sodium' has no function, constant or global variable named 'crypto_box_seedbytes'

**Comment by ktbyers** [comment]
I would upgrade your `paramiko` and possibly your `cryptography` library

**Comment by bgile** [comment]
After much back and forth upgrading and reinstalling.. it was easier to just start fresh with new library installs of netmiko etc...  Still a mystery what happened but  everything is working fine now.

Thanks
