### ISSUE TITLE
ValueError: Failed to exit configuration mode

### ISSUE THREAD

**Issue by LongBeachHXC** [ktbyers/netmiko#762]
Not sure why I am receiving the above error. I receive this error after the third iteration or before the fourth iteration of the loop.

I'm not sure where or why I am receive the error and I'm not sure on how to troubleshoot this. The script worked flawlessly on the first three iterations and I have probably 50 devices to loop through. 

``` python
from getpass import getpass
from netmiko import ConnectHandler
from netmiko.ssh_exception import NetMikoTimeoutException
from paramiko.ssh_exception import SSHException
from netmiko.ssh_exception import AuthenticationException


def Split(arr, size):
     arrs = []
     while len(arr) > size:
         pice = arr[:size]
         arrs.append(pice)
         arr   = arr[size:]
     arrs.append(arr)
     return arrs


username = input('Enter your SSH username: ')
password = getpass()

with open('devices_file') as f:
    devices_list = f.read().splitlines()

for devices in devices_list:
    print ('Connecting to device ' + devices)
    ip_address_of_device = devices
    ios_device = {
        'device_type': 'cisco_ios',
        'ip': ip_address_of_device,
        'username': username,
        'password': password,
}

    try:
        net_connect = ConnectHandler(**ios_device)
    except (AuthenticationException):
        print ('Authentication failure: ' + ip_address_of_device)
        continue
    except (NetMikoTimeoutException):
        print ('Timeout to device: ' + ip_address_of_device)
        continue
    except (EOFError):
        print ("End of file while attempting device " + ip_address_of_device)
        continue
    except (SSHException):
        print ('SSH Issue. Are you sure SSH is enabled? ' + ip_address_of_device)
        continue
    except Exception as unknown_error:
        print ('Some other error: ' + str(unknown_error))
        continue

    show_int = net_connect.send_command_expect('show int status')

		# Here we save data from 'show_int' var to file 'test.txt'
    with open(devices +'-show-int.txt', 'w') as f: f.write(show_int)
		# Here we read the output within file to a list, then strip the extra spacing
    config_list = [elt.strip() for elt in open(devices +'-show-int.txt', 'r').readlines()]
		# Then we interate through the list looking for all 'not_connected' lines
    filterOutVlan31 = [elt for elt in config_list if ' 31 ' not in elt]
    filterOutTrunk = [elt for elt in filterOutVlan31 if 'trunk' not in elt]
		# Then you covert the found lines into a string
    interface_search = str(filterOutTrunk).split(',')

    gigabitInterface = [elt for elt in interface_search if 'Gi' in elt]

        # Here we interate through the string to find the interface using the index method
    interfacelist = [elt[2:10] for elt in gigabitInterface]
    rangeobjectlist = Split(interfacelist,8)
    for i in range(0, len(rangeobjectlist)):
        rangeCommandString = ','.join(rangeobjectlist[i])
        interfaceConfigured = 'interface group => ' + rangeCommandString
        print('Configuring interface group => ' + rangeCommandString)
        with open(devices + '-ports-configured.txt', 'a') as z: z.write(f'{interfaceConfigured}\n')
        command_set = [
            'interface range ' + rangeCommandString + '\n',
            'switchport port-security\n',
            'switchport port-security max 3\n',
            'switchport port-security violation restrict\n',
            'switchport port-security aging type inactivity\n',
            'switchport port-security aging time 2\n'
        ]
        net_connect.send_config_set(command_set)

    net_connect.disconnect()
```
for reference:

Traceback (most recent call last):
  File "interfaceportsecurity.py", line 88, in <module>
    net_connect.send_config_set(command_set)
  File "/mnt/c/Users/forwein/linuxFileFolder/venv/westfield/cenc/cencFinalInterfaceStandardization/lib/python3.6/site-packages/netmiko/base_connection.py", line 1135, in send_config_set
    output += self.exit_config_mode()
  File "/mnt/c/Users/forwein/linuxFileFolder/venv/westfield/cenc/cencFinalInterfaceStandardization/lib/python3.6/site-packages/netmiko/cisco_base_connection.py", line 49, in exit_config_mode
    pattern=pattern)
  File "/mnt/c/Users/forwein/linuxFileFolder/venv/westfield/cenc/cencFinalInterfaceStandardization/lib/python3.6/site-packages/netmiko/base_connection.py", line 1089, in exit_config_mode
    raise ValueError("Failed to exit configuration mode")

**Comment by LongBeachHXC** [comment]
Just as an update. The script failed one other time iterating through 40 devices or so. In summary, the script failed twice with the above error at different moments during the run time.

**Comment by ktbyers** [comment]
Is it always the same device that it fails on?

**Comment by LongBeachHXC** [comment]
The first time it failed...Yes. I rant the script multiple different times and it failed every time after the 3rd and before the 4th device. The 3rd device appeared to receive all of the configurations with no issue.

The second time it failed I did not test it to see if it was going to fail again so I'm not sure if it was going to fail multiple times.

**Comment by ktbyers** [comment]
@LongBeachHXC Okay, I would run your script against only the device that failed and see if it works or fails for that device.
