### ISSUE TITLE
Channel closed while connecting to Huawei CE switch

### ISSUE THREAD

**Issue by yman45** [ktbyers/netmiko#764]
Hello!
I have a problem connecting to some Huawei CE switches. Most of the time it works fine, but on some devices my script can't connect with paramiko exception "Channel closed". For example, not working one:
```
>>> connecton = ConnectHandler(ip='sw1.company.net', device_type='huawei', username='darkyman', password='somepassword', verbose=True)
DEBUG:paramiko.transport:starting thread (client mode): 0x471d8c88
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.4.1
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0--
INFO:paramiko.transport:Connected (version 2.0, client -)
DEBUG:paramiko.transport:kex algos:['diffie-hellman-group-exchange-sha256', 'diffie-hellman-group1-sha1', 'ecdh-sha2-nistp521', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp256', 'diffie-hellman-group-exchange-sha1', 'sm2kep-sha2-nistp256'] server key:['ssh-dss', 'ssh-rsa', 'ecdsa-sha2-nistp521'] client encrypt:['aes256-ctr', 'aes128-ctr', 'aes256-cbc', 'aes128-cbc', 'arcfour256', 'arcfour128', '3des-cbc'] server encrypt:['aes256-ctr', 'aes128-ctr', 'aes256-cbc', 'aes128-cbc', 'arcfour256', 'arcfour128', '3des-cbc'] client mac:['hmac-sha2-256', 'hmac-sha2-256-96', 'hmac-sha1', 'hmac-sha1-96', 'hmac-md5', 'hmac-md5-96'] server mac:['hmac-sha2-256', 'hmac-sha2-256-96', 'hmac-sha1', 'hmac-sha1-96', 'hmac-md5', 'hmac-md5-96'] client compress:['none', 'zlib'] server compress:['none', 'zlib'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: ecdh-sha2-nistp256
DEBUG:paramiko.transport:HostKey agreed: ecdsa-sha2-nistp521
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ecdsa-sha2-nistp521 host key for sw1.company.net: b'bb92cb0c94753c3abec520d794b9267e'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Auth banner: b'\r\nsw1\r\n'
INFO:paramiko.transport:Authentication (password) successful!
SSH connection established to sw1.company.net:22
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] EOF sent (0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
INFO:paramiko.transport:Disconnect (code 2): The connection is closed by SSH Server

  File "/home/darkyman/projects/huawei_set_new_soft/virtualenv/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 174, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/darkyman/projects/huawei_set_new_soft/virtualenv/lib/python3.6/site-packages/netmiko/base_connection.py", line 187, in __init__
    self.establish_connection()
  File "/home/darkyman/projects/huawei_set_new_soft/virtualenv/lib/python3.6/site-packages/netmiko/base_connection.py", line 669, in establish_connection
    self.remote_conn = self.remote_conn_pre.invoke_shell()
  File "/home/darkyman/projects/huawei_set_new_soft/virtualenv/lib/python3.6/site-packages/paramiko/client.py", line 512, in invoke_shell
    chan.invoke_shell()
  File "/home/darkyman/projects/huawei_set_new_soft/virtualenv/lib/python3.6/site-packages/paramiko/channel.py", line 63, in _check
    return func(self, *args, **kwds)
  File "/home/darkyman/projects/huawei_set_new_soft/virtualenv/lib/python3.6/site-packages/paramiko/channel.py", line 214, in invoke_shell
    self._wait_for_event()
  File "/home/darkyman/projects/huawei_set_new_soft/virtualenv/lib/python3.6/site-packages/paramiko/channel.py", line 1198, in _wait_for_event
    raise e
paramiko.ssh_exception.SSHException: Channel closed.
```
And working one:
```
>>> connecton = ConnectHandler(ip='sw2.company.net', device_type='huawei', username='darkyman', password='somepassword', verbose=True)
DEBUG:paramiko.transport:starting thread (client mode): 0x471ef198
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.4.1
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0--
INFO:paramiko.transport:Connected (version 2.0, client -)
DEBUG:paramiko.transport:kex algos:['diffie-hellman-group-exchange-sha256', 'diffie-hellman-group1-sha1', 'ecdh-sha2-nistp521', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp256', 'diffie-hellman-group-exchange-sha1', 'sm2kep-sha2-nistp256'] server key:['ssh-dss', 'ssh-rsa', 'ecdsa-sha2-nistp521'] client encrypt:['aes256-ctr', 'aes128-ctr', 'aes256-cbc', 'aes128-cbc', 'arcfour256', 'arcfour128', '3des-cbc'] server encrypt:['aes256-ctr', 'aes128-ctr', 'aes256-cbc', 'aes128-cbc', 'arcfour256', 'arcfour128', '3des-cbc'] client mac:['hmac-sha2-256', 'hmac-sha2-256-96', 'hmac-sha1', 'hmac-sha1-96', 'hmac-md5', 'hmac-md5-96'] server mac:['hmac-sha2-256', 'hmac-sha2-256-96', 'hmac-sha1', 'hmac-sha1-96', 'hmac-md5', 'hmac-md5-96'] client compress:['none', 'zlib'] server compress:['none', 'zlib'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: ecdh-sha2-nistp256
DEBUG:paramiko.transport:HostKey agreed: ecdsa-sha2-nistp521
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ecdsa-sha2-nistp521 host key for sw2.company.net: b'320640a59ccb28d02ead6cdf6695375e'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Auth banner: b'\r\nsw2\r\n'
INFO:paramiko.transport:Authentication (password) successful!
SSH connection established to sw2.company.net:22
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
Interactive SSH session established
DEBUG:netmiko:read_channel: 
Info: The max number of VTY users is 8, the number of current VTY users online is 1, and total number of terminal users online is 1.
      The current login time is 2018-03-29 04:10:37+03:00.
      The last login time is 2018-03-29 03:49:19+03:00 from 192.168.15.2 through SSH.
<sw2>
DEBUG:netmiko:read_channel: 
cDEBUG:netmiko:read_channel: 
DEBUG:netmiko:In set_base_prompt
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
oDEBUG:netmiko:read_channel: 
<sw2>
DEBUG:netmiko:prompt: sw2
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:In disable_paging
DEBUG:netmiko:Command: screen-length 0 temporary

DEBUG:netmiko:write_channel: b'screen-length 0 temporary\n'
DEBUG:netmiko:Pattern is: sw2
DEBUG:netmiko:_read_channel_expect read_data: screen-length 0 temporary

DEBUG:netmiko:_read_channel_expect read_data: Info: The configuration takes effect on the current user terminal interface only.
<sw2>
DEBUG:netmiko:Pattern found: sw2 screen-length 0 temporary
Info: The configuration takes effect on the current user terminal interface only.
<sw2>
DEBUG:netmiko:screen-length 0 temporary
Info: The configuration takes effect on the current user terminal interface only.
<sw2>
DEBUG:netmiko:Exiting disable_paging
DEBUG:netmiko:read_channel: 
```
Switches identical in hardware, software and SSH server configuration. I tried both 'huawei' and 'huawei_vrpv8' type with no luck. I walking through hundreds of Huawei CE switches and found approx. 1 out of 20 with such behavior.
Can you point me in right direction to dig further, please?

**Comment by yman45** [comment]
Yes, if I can access a switch, I always can do it. If I can't, same thing applies.
I use Netmiko to upload new software on them (through FTP), and even after software update problem still persist. I tried login with paramiko only and got same results. Maybe it's problem on switches side. Will look if i can debug something out of them.

**Comment by ktbyers** [comment]
@yman45 So the switch is terminating the SSH session for some reason.

Does debugging SSH on the switch give you any clues?

So you see have two switches that are the same hardware, OS version, and configuration and one will work and one will fail?

**Comment by yman45** [comment]
> Does debugging SSH on the switch give you any clues?

Didn't done it yet unfortunately, I think I will have some results at the end of that week.

> So you see have two switches that are the same hardware, OS version, and configuration and one will work and one will fail?

Sounds strange, but yes. They undergo software update right now, but recent software doesn't change that behavior. Maybe I miss something. Normal SSH connection always works perfect.

**Comment by yman45** [comment]
I'm confused. Today I iterate again through all switches and there no single connection error.
So I don't think there's a problem with Netmiko.

**Comment by ktbyers** [comment]
Okay, I am going to close this. If there is still an issue...just re-open it.
