### ISSUE TITLE
Unable to SSH to linux host from Windows host

### ISSUE THREAD

**Issue by shaarrky** [ktbyers/netmiko#768]
Hello fam,

Python newbie here! 

I'm trying to SSH onto a Linux host from a Windows host running Visual Studio with no luck.
Here is the configuration I've got in place (Note: I've replaced the IP/username/password temporarily)

### Paramiko/Netmiko - Device Login

from netmiko import ConnectHandler
linux = {
    'device_type': 'linux',
    'ip': 'a.b.c.d',
    'username': 'x',
    'password': 'y',
    }
net_connect = ConnectHandler(**linux)

When running the script I get the following messages:

**d:\python_work>linux.py
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\netmiko-2.0.2-py3.6.egg\netmiko\base_connection.py", line 650, in establish_connection
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\paramiko\client.py", line 424, in connect
    passphrase,
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\paramiko\client.py", line 714, in _auth
    raise saved_exception
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\paramiko\client.py", line 701, in _auth
    self._transport.auth_password(username, password)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\paramiko\transport.py", line 1381, in auth_password
    return self.auth_handler.wait_for_response(my_event)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\paramiko\auth_handler.py", line 226, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python_work\linux.py", line 12, in <module>
    net_connect = ConnectHandler(**linux)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\netmiko-2.0.2-py3.6.egg\netmiko\ssh_dispatcher.py", line 173, in ConnectHandler
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\netmiko-2.0.2-py3.6.egg\netmiko\base_connection.py", line 187, in __init__
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\netmiko-2.0.2-py3.6.egg\netmiko\base_connection.py", line 659, in establish_connection
netmiko.ssh_exception.NetMikoAuthenticationException: Authentication failure: unable to connect linux a.b.c.d:22
Authentication failed.**

From the same windows host, I can use Putty and connect to the Linux without any issues.
Any assistance would be greatly appreciated.

Thanks,
Sharky

**Comment by ktbyers** [comment]
@shaarrky It is probably complaining that the username/password is wrong (basically it is complaining that it failed authentication).

You can turn on logging and see if that gives you more clues:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by shaarrky** [comment]
Hi ktbyers,

Here's the log output:

DEBUG:paramiko.transport:starting thread (client mode): 0x3151dd0
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.4.0
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-Sun_SSH_1.1.3
INFO:paramiko.transport:Connected (version 2.0, client Sun_SSH_1.1.3)
DEBUG:paramiko.transport:kex algos:['gss-group1-sha1-toWM5Slw5Ew8Mqkay+al2g==', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group1-sha1'] server key:['ssh-rsa', 'ssh-dss'] client encrypt:['aes128-ctr', 'aes128-cbc', 'arcfour', '3des-cbc', 'blowfish-cbc', 'aes192-ctr', 'aes192-cbc', 'aes256-ctr', 'aes256-cbc'] server encrypt:['aes128-ctr', 'aes128-cbc', 'arcfour', '3des-cbc', 'blowfish-cbc', 'aes192-ctr', 'aes192-cbc', 'aes256-ctr', 'aes256-cbc'] client mac:['hmac-md5', 'hmac-sha1', 'hmac-sha1-96', 'hmac-md5-96'] server mac:['hmac-md5', 'hmac-sha1', 'hmac-sha1-96', 'hmac-md5-96'] client compress:['none', 'zlib'] server compress:['none', 'zlib'] client lang:['en-CA', 'es-MX', 'en-US', 'es', 'fr', 'fr-CA', 'i-default'] server lang:['en-CA', 'es-MX', 'en-US', 'es', 'fr', 'fr-CA', 'i-default'] kex follows?False
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group-exchange-sha1
DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha1
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:Got server p (4095 bits)
DEBUG:paramiko.transport:kex engine KexGex specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for a.b.c.d: b'f1b5269556b64c6428b1f46eaeab6c1e'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) failed.
DEBUG:paramiko.transport:EOF in transport thread

As mentioned, I can connect to the Linux host using the same username/password I've put in the configuration above with Putty.

**Comment by ktbyers** [comment]
That error is just complaining about the username/password being wrong (so that is where I would start).

I would re-input both the username and password and double check the IP address/hostname is right.
