### ISSUE TITLE
When access to Multiple Switch Access w/error

### ISSUE THREAD

**Issue by mmihir82** [ktbyers/netmiko#810]
After ssh to switch, I would like to fetch few information, then disconnect using function.
For example:
```
def switchconnect (switchip, user):
    cisco1 = {
        'host': switchip,
        'username': user,
        'password': getpass(),
        'device_type': 'cisco_ios',
    }
    switch = Netmiko(**cisco1)
    print(switch.find_prompt())
    return switch

def switchdisconnect (switchip):
    return switchip.disconnect()

run = switchconnect(switchip,user)
switchdisconnect(run)
```
It works with first switch, but doesn't work continuous with seconds swtich.
I get time-out error:
```
Password:
Traceback (most recent call last):
  File "phase4.py", line 174, in <module>
    run = switchconnect(switchip,user)
  File "phase4.py", line 17, in switchconnect
    switch = Netmiko(**cisco1)
  File "/usr/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 178, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 207, in __init__
    self.establish_connection()
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 693, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios testdevice:22
```

**Comment by ktbyers** [comment]
Where is `testdevice` coming from? Does that resolve in DNS?

This failure is basically saying it couldn't connect to anything on testdevice:22

Can you post a bigger section of code (i.e. include where the IP addresses are coming from).
