### ISSUE TITLE
OSError: Search pattern never detected in send_command_expect: 

### ISSUE THREAD

**Issue by diditonf** [ktbyers/netmiko#811]
Hi,

I`m trying to use edit command on IOS_XR to edit a prefix-set but when i send a command becuase i can`t use config mode because this prefix-set is already created so i have to edit that, when py sent the command the output ask for yes/no but when getting this error when i try sent yes.

The command:
` python3.6 exec_commands_xr.py -c 'edit prefix-set CUSTOMER:AS263526_v4_pfxset inline add "168.227.136.0/22 ge 22 le 24"'`

The code:
```
import argparse
from netmiko import ConnectHandler

cisco_ios_xrv = {
    'device_type': 'cisco_xr',
    'ip':   '',
    'username': 'rodrigo',
    'password': '',
    'port' : 22,          # optional, defaults to 22
    'secret': '',     # optional, defaults to ''
    'verbose': False,       # optional, defaults to False
}

net_connect = ConnectHandler(**cisco_ios_xrv)
parser = argparse.ArgumentParser()
parser.add_argument('-c')
args = parser.parse_args()

output = net_connect.send_command(args.c)
output2 = net_connect.send_command_expect('yes', expect_string=r"Proceed with commmit (yes/no)? [yes]:")

print (output)
print (output2)

```
Error:

```
Traceback (most recent call last):
  File "exec_commands_xr.py", line 19, in <module>
    output = net_connect.send_command(args.c)
  File "/usr/local/lib/python3.6/site-packages/netmiko-2.1.1-py3.6.egg/netmiko/base_connection.py", line 1051, in send_command
OSError: Search pattern never detected in send_command_expect: RP\/0\/RSP0\/CPU0\:ARC\-RJO_TLP\.2\#

```

**Comment by ktbyers** [comment]
@diditonf What does it look like on the IOS-XR CLI when you do this?

In other words, can you post a manual SSH session where you do:

```
edit prefix-set CUSTOMER:AS263526_v4_pfxset inline add "168.227.136.0/22 ge 22 le 24"
```
