### ISSUE TITLE
coriant router login failed with error

### ISSUE THREAD

**Issue by SaranS007** [ktbyers/netmiko#828]
Hallo team,

Could you please support me. I am trying to login to coriant router using netmiko but failed with below error:

[root@tthcentos07 ~]# python
Python 2.7.5 (default, Apr 11 2018, 07:36:10)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from __future__ import print_function
>>> import netmiko
>>> from getpass import getpass
>>> connection = netmiko.ConnectHandler(ip='192.168.1.15',device_type='coriant',username='admin',password=getpass('Enter a password for the Router:\n'))
Enter a password for the Router:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/netmiko/ssh_dispatcher.py", line 184, in ConnectHandler
  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 208, in __init__
  File "build/bdist.linux-x86_64/egg/netmiko/coriant/coriant_ssh.py", line 9, in session_preparation
  File "build/bdist.linux-x86_64/egg/netmiko/coriant/coriant_ssh.py", line 37, in set_base_prompt
  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 854, in set_base_prompt
  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 895, in find_prompt
ValueError: Unable to find prompt:
>>>

Could some one help to solve the above issue? Thank You

**Comment by SaranS007** [comment]
I  could see some banner during login to router may cause the issue..think so... and its shown below-
Escape character is '^]'.
******************************************************************
*                                                                                                  *
*                  Coriant 8609 Network Element                               *
*                                                                                                  *
******************************************************************
user name:
---------**----

I tried with some timer but then also the comment  failed with same error.

**Comment by ktbyers** [comment]
@SaranS007 Did you ever look at the logging (for additional information)?

**Comment by carlniger** [comment]
Going to close this as its quite old -- please reopen and provide some log output if its still an issue!
