### ISSUE TITLE
Unable to connect to F5-LTM recieving "Router prompt not found"

### ISSUE THREAD

**Issue by akilbmtc** [ktbyers/netmiko#832]
Hi,
I have Physical and virtual edition of F5 installed and i write a script for Automating the iso image upgrade similar to your ASA script.The issue is most of the time i am getting Router prompt not found error.All the other code is working fine.

Connection to Device:  x.x.x.x
Device Failed  x.x.x.x Router prompt not found: 'root@(Hostname'

Device Type i am using is "f5_ltm"

**Comment by akilbmtc** [comment]
I referred other Users issues in this Git and also configured time.sleep(2) in Base_connect.py but still no luck.

**Comment by akilbmtc** [comment]
File "C:\Users\kak1sgp\AppData\Local\Programs\Python\Python36-32\lib\site-packages\netmiko\f5\f5_ltm_ssh.py", line 15, in session_preparation
    self.set_base_prompt()
  File "C:\Users\kak1sgp\AppData\Local\Programs\Python\Python36-32\lib\site-packages\netmiko\base_connection.py", line 857, in set_base_prompt
    raise ValueError("Router prompt not found: {0}".format(repr(prompt)))
ValueError: Router prompt not found: 'root@(SI-'

**Comment by akilbmtc** [comment]
I think root@( is creating the issue

**Comment by ktbyers** [comment]
@akilbmtc Please post your code (you can obfuscate any confidential information). Also please post what a manual SSH looks like (for SSHing into the device on the CLI).



Kirk

**Comment by akilbmtc** [comment]
Sure I will post by next week.

Thanks for the support

**Comment by akilbmtc** [comment]
Hello there,

I just signed the petition "Indian Supreme court: HOME LOAN EMI SHOULD BE
STOPPED FOR DELAYED PROJECTS. BUYERS HAVE LOST FULL LIFE SAVINGS" and
wanted to see if you could help by adding your name.

Our goal is to reach 25,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/hhdMJRNQvf

Thanks!
akhilesh

**Comment by superloopnetworks** [comment]
Hi @ktbyers , I'm facing the same issue as well..

Device type is set to: **f5_tmsh** is not working. Not sure what shell that is suppose to be because f5_linux is bash and f5_ltm is within tmos...

```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/wailitloi/superloop/lib/objects/basenode.py", line 76, in exec_command
    self.connect()
  File "/Users/wailitloi/superloop/lib/objects/basenode.py", line 26, in connect
    self.net_connect = ConnectHandler(self.ip,self.hostname,self.username,self.password_decrypt,self.get_secret(),device_type=self.get_device())
  File "/Users/wailitloi/Library/Python/2.7/lib/python/site-packages/netmiko/ssh_dispatcher.py", line 246, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/Users/wailitloi/Library/Python/2.7/lib/python/site-packages/netmiko/base_connection.py", line 317, in __init__
    self._open()
  File "/Users/wailitloi/Library/Python/2.7/lib/python/site-packages/netmiko/base_connection.py", line 323, in _open
    self._try_session_preparation()
  File "/Users/wailitloi/Library/Python/2.7/lib/python/site-packages/netmiko/base_connection.py", line 738, in _try_session_preparation
    self.session_preparation()
  File "/Users/wailitloi/Library/Python/2.7/lib/python/site-packages/netmiko/f5/f5_tmsh_ssh.py", line 12, in session_preparation
    self.set_base_prompt()
  File "/Users/wailitloi/Library/Python/2.7/lib/python/site-packages/netmiko/base_connection.py", line 1068, in set_base_prompt
    raise ValueError("Router prompt not found: {0}".format(repr(prompt)))
ValueError: Router prompt not found: u'admin@(f5-'

``` 

Regular SSH via shell looks like this:

```
ssh admin@10.x.x.x
Password: 
Last login: Thu Jun 18 13:14:37 2020 from 10.1.14.159
[admin@f5-big-ip:Active:In Sync] ~ # 
```

Device type **f5_linux** and **f5_ltm** works and it lands me in shell and tmsh of the F5.

**Comment by superloopnetworks** [comment]
@ktbyers It looks like **f5_ltm** sometimes work, but most times it doesn't...

**Comment by ktbyers** [comment]
@superloopnetworks Can you re-test with the latest version of Netmiko? Also you will need to upgrade to at least Python 3.6 (as newer versions of Netmiko require that).

Kirk

**Comment by superloopnetworks** [comment]
Hi Kirk,

Same deal.. I've upgraded netmiko to the latest and python as well:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/wailitloi/superloop/lib/objects/basenode.py", line 107, in pull_cfgs
    output = self.net_connect.send_command_expect(command)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/netmiko/base_connection.py", line 1471, in send_command_expect
    return self.send_command(*args, **kwargs)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/netmiko/utilities.py", line 347, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/netmiko/base_connection.py", line 1431, in send_command
    search_pattern
OSError: Search pattern never detected in send_command_expect: admin@\(f5\-big\-ip\)\(cfg\-sync\ In\ Sync\)\(Standby\)\(/Common\)\(tmos\)\#\ run\ /util\ bash\ \-c\ "stty\ cols\ 255"
```

**Comment by ktbyers** [comment]
Please include your code and the Netmiko logging output:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel


Regards, Kirk

**Comment by dpaneels-delhaize** [comment]
Hi Kirk, all,


Same issue here, has this ever been solved ? 

Same results with f5_ltm / f5_tmsh / f5_linux


Traceback (most recent call last):
  File "c:\Users\DPANEE\Documents\NetworkScripts\venvs\F5\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "c:\Users\DPANEE\Documents\NetworkScripts\venvs\F5\lib\site-packages\nornir_netmiko\tasks\netmiko_send_command.py", line 32, in netmiko_send_command
    result = net_connect.send_command(command_string, **kwargs)
  File "c:\Users\DPANEE\Documents\NetworkScripts\venvs\F5\lib\site-packages\netmiko\utilities.py", line 500, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "c:\Users\DPANEE\Documents\NetworkScripts\venvs\F5\lib\site-packages\netmiko\base_connection.py", line 1535, in send_command
    raise IOError(
OSError: Search pattern never detected in send_command: f5admin@\(be93a0302\-cld\)\(cfg\-sync\ Standalone\)\(Active\)\(/Common\)\(tmos\)\#



Greets,



David

**Comment by sindhujit1** [comment]
Facing same issue. Error:
`<html>
<body>


Exception Type: | NetmikoTimeoutException
-- | --
Timed-out reading channel, data not available.


</body>
</html>`

Can anyone help on this ?

**Comment by ktbyers** [comment]
@sindhujit1 Can you open a new issue and put in your code and your full exception stack-trace.

Commenting on closed issues generally just leads to issues getting lost.
