### ISSUE TITLE
unable to SSH router using netmiko -centos7

### ISSUE THREAD

**Issue by smaheshggn** [ktbyers/netmiko#870]
Hello Kirk

I am using centos7 and using the below code to SSH router but getting the error mentioned below

from netmiko import ConnectHandler

cisco_881 = {
    'device_type': 'cisco_ios',
    'ip':   '192.168.33.5',
    'username': 'cisco',
    'password': 'cisco',
}

net_connect = ConnectHandler(**cisco_881)
output = net_connect.send_command('show ip int brief')
print output

>>>>>>>>>>>error
Traceback (most recent call last):
  File "routerssh1.py", line 1, in <module>
    from netmiko import ConnectHandler
  File "/usr/lib/python2.7/site-packages/netmiko/__init__.py", line 8, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "/usr/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 4, in <module>
    from netmiko.a10 import A10SSH
  File "/usr/lib/python2.7/site-packages/netmiko/a10/__init__.py", line 2, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "/usr/lib/python2.7/site-packages/netmiko/a10/a10_ssh.py", line 4, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "/usr/lib/python2.7/site-packages/netmiko/cisco_base_connection.py", line 3, in <module>
    from netmiko.base_connection import BaseConnection
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 13, in <module>
    import paramiko
  File "/usr/lib/python2.7/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 38, in <module>
    from paramiko.auth_handler import AuthHandler
  File "/usr/lib/python2.7/site-packages/paramiko/auth_handler.py", line 48, in <module>
    from paramiko.ssh_gss import GSSAuth, GSS_EXCEPTIONS
  File "/usr/lib/python2.7/site-packages/paramiko/ssh_gss.py", line 54, in <module>
    GSS_EXCEPTIONS = (gssapi.GSSException,)
AttributeError: 'module' object has no attribute 'GSSException'

**Comment by smaheshggn** [comment]
Hello KTByers

I have removed the below packages and it works now.
    cyrus-sasl-gssapi
    python-gssapi

Thanks
