### ISSUE TITLE
Netmiko to 3725 on GNS3: OSError: Search pattern never detected in send_command_expect

### ISSUE THREAD

**Issue by Collisio-Adolebitque** [ktbyers/netmiko#872]
I'm trying to perform some legacy style config on a 3725 image in GNS3.  The config should run as follows:

```
IOS-SW1#vlan database
IOS-SW1(vlan)#vlan 2 name PYTHON_VLAN_2
VLAN 2 added:
    Name: PYTHON_VLAN_2
IOS-SW1(vlan)#vlan 3 name PYTHON_VLAN_3
VLAN 3 added:
    Name: PYTHON_VLAN_3
...
IOS-SW1(vlan)#exit
APPLY completed.
Exiting....
```

The script is as follows:

```
import getpass
from netmiko import ConnectHandler
 
 
def main():
    user = input("Enter your remote account: ")
    password = getpass.getpass()
 
    ios_sw1 = {
        'device_type': 'cisco_ios',
        'ip': '172.16.39.150',
        'username': user,
        'password': password,
    }
 
    for vlan_id in range(2, 33):
        print("Creating VLAN " + str(vlan_id) + ".")
        output = [net_connect.send_command('vlan database\n', expect_string='#'),
                  net_connect.send_command('vlan ' + str(vlan_id) + ' name PYTHON_VLAN_' + str(vlan_id) + '\n',
                                           expect_string='#'),
                  net_connect.send_command('exit\n')]
        print(output)
 
    output = net_connect.send_command('show vlan-switch brief')
    print(output)
 
 
if __name__ == '__main__':
    main()
```

The script seems to create 2 of the 32 VLANs required, however, it then fails:

```
root@NetAutomate-1:~/scripts/P3FNE_Lab1# python3 programIOS_SW_Netmiko.py
Enter your remote account: admin
Password:
IOS-SW1#
Creating VLAN 2.
['', 'VLAN 2 modified:\n    Name: PYTHON_VLAN_2', 'SW1(vlan)#\nIOS-SW1(vlan)#\nIOS-SW1(vlan)#']
Creating VLAN 3.
Traceback (most recent call last):
  File "programIOS_SW_Netmiko.py", line 38, in <module>
    main()
  File "programIOS_SW_Netmiko.py", line 30, in main
    net_connect.send_command('exit\n')]
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 1051, in send_command
    search_pattern))
OSError: Search pattern never detected in send_command_expect: IOS\-SW1\(vlan\)\#
```

View from the switch:

```
IOS-SW1#sh vlan-s br

VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
1    default                          active    Fa2/0, Fa2/1, Fa2/2, Fa2/3
                                                Fa2/4, Fa2/5, Fa2/6, Fa2/7
                                                Fa2/8, Fa2/9, Fa2/10, Fa2/11
                                                Fa2/12, Fa2/13, Fa2/14, Fa2/15
2    PYTHON_VLAN_2                    active
3    PYTHON_VLAN_3                    active
1002 fddi-default                     active
1003 token-ring-default               active
1004 fddinet-default                  active
1005 trnet-default                    active 
```

The performance of the script is extremely slow as well.  Any ideas (free support, best effort understood and appreciated)?

**Comment by Collisio-Adolebitque** [comment]
I think I've got it.  It doesn't like the `vlan database` prompts, script updated accordingly:

```
import getpass
from netmiko import ConnectHandler


def main():
    user = input("Enter your remote account: ")
    password = getpass.getpass()

    ios_sw1 = {
        'device_type': 'cisco_ios',
        'ip': '172.16.39.150',
        'username': user,
        'password': password,
    }

    net_connect = ConnectHandler(**ios_sw1)

    output = net_connect.send_command('vlan database', expect_string='#')
    print(output)

    for vlan_id in range(2, 33):
        print("Creating VLAN " + str(vlan_id) + ".")
        output = net_connect.send_command('vlan ' + str(vlan_id) + ' name PYTHON_VLAN_' + str(vlan_id),
                                          expect_string='#')
        print(output)

    output = [net_connect.send_command('exit', expect_string='#'),
              net_connect.send_command('terminal length 0'),
              net_connect.send_command('show vlan-switch brief')]
    print(output)


if __name__ == '__main__':
    main()
```

Also, performance was significantly improved by moving the `vlan database` and `exit` commands out of the for loop (although the `show vlan-switch brief` output was kinda ugly).

```
root@NetAutomate-1:~/scripts/P3FNE_Lab1# python3 programIOS_SW_Netmiko.py
Enter your remote account: admin
Password:
Creating VLAN 2.
VLAN 2 added:
    Name: PYTHON_VLAN_2
Creating VLAN 3.
VLAN 3 added:
    Name: PYTHON_VLAN_3
Creating VLAN 4.
VLAN 4 added:
    Name: PYTHON_VLAN_4
Creating VLAN 5.
VLAN 5 added:
    Name: PYTHON_VLAN_5
Creating VLAN 6.
VLAN 6 added:
    Name: PYTHON_VLAN_6
Creating VLAN 7.
VLAN 7 added:
    Name: PYTHON_VLAN_7
Creating VLAN 8.
VLAN 8 added:
    Name: PYTHON_VLAN_8
Creating VLAN 9.
VLAN 9 added:
    Name: PYTHON_VLAN_9
Creating VLAN 10.
VLAN 10 added:
    Name: PYTHON_VLAN_10
Creating VLAN 11.
VLAN 11 added:
    Name: PYTHON_VLAN_11
Creating VLAN 12.
VLAN 12 added:
    Name: PYTHON_VLAN_12
Creating VLAN 13.
VLAN 13 added:
    Name: PYTHON_VLAN_13
Creating VLAN 14.
VLAN 14 added:
    Name: PYTHON_VLAN_14
Creating VLAN 15.
VLAN 15 added:
    Name: PYTHON_VLAN_15
Creating VLAN 16.
VLAN 16 added:
    Name: PYTHON_VLAN_16
Creating VLAN 17.
VLAN 17 added:
    Name: PYTHON_VLAN_17
Creating VLAN 18.
VLAN 18 added:
    Name: PYTHON_VLAN_18
Creating VLAN 19.
VLAN 19 added:
    Name: PYTHON_VLAN_19
Creating VLAN 20.
VLAN 20 added:
    Name: PYTHON_VLAN_20
Creating VLAN 21.
VLAN 21 added:
    Name: PYTHON_VLAN_21
Creating VLAN 22.
VLAN 22 added:
    Name: PYTHON_VLAN_22
Creating VLAN 23.
VLAN 23 added:
    Name: PYTHON_VLAN_23
Creating VLAN 24.
VLAN 24 added:
    Name: PYTHON_VLAN_24
Creating VLAN 25.
VLAN 25 added:
    Name: PYTHON_VLAN_25
Creating VLAN 26.
VLAN 26 added:
    Name: PYTHON_VLAN_26
Creating VLAN 27.
VLAN 27 added:
    Name: PYTHON_VLAN_27
Creating VLAN 28.
VLAN 28 added:
    Name: PYTHON_VLAN_28
Creating VLAN 29.
VLAN 29 added:
    Name: PYTHON_VLAN_29
Creating VLAN 30.
VLAN 30 added:
    Name: PYTHON_VLAN_30
Creating VLAN 31.
VLAN 31 added:
    Name: PYTHON_VLAN_31
Creating VLAN 32.
VLAN 32 added:
    Name: PYTHON_VLAN_32
['APPLY completed.\nExiting....', '', '\nVLAN Name                             Status    Ports\n---- -------------------------------- --------- -------------------------------\n1    default                          active    Fa2/0, Fa2/1, Fa2/2, Fa2/3, Fa2/4, Fa2/5, Fa2/6, Fa2/7, Fa2/8, Fa2/9, Fa2/10, Fa2/11, Fa2/12, Fa2/13, Fa2/14, Fa2/15\n2    PYTHON_VLAN_2                    active    \n3    PYTHON_VLAN_3                    active    \n4    PYTHON_VLAN_4                    active    \n5    PYTHON_VLAN_5                    active    \n6    PYTHON_VLAN_6
                active    \n7    PYTHON_VLAN_7                    active    \n8    PYTHON_VLAN_8
   active    \n9    PYTHON_VLAN_9                    active    \n10   PYTHON_VLAN_10                   active
\n11   PYTHON_VLAN_11                   active    \n12   PYTHON_VLAN_12                   active    \n13   PYTHON_VLAN_13                   active    \n14   PYTHON_VLAN_14                   active    \n15   PYTHON_VLAN_15
              active    \n16   PYTHON_VLAN_16                   active    \n17   PYTHON_VLAN_17
 active    \n18   PYTHON_VLAN_18                   active    \n19   PYTHON_VLAN_19                   active    \n20   PYTHON_VLAN_20                   active    \n21   PYTHON_VLAN_21                   active    \n22   PYTHON_VLAN_22                   active    \n23   PYTHON_VLAN_23                   active    \n24   PYTHON_VLAN_24
            active    \n25   PYTHON_VLAN_25                   active    \n26   PYTHON_VLAN_26                   active    \n27   PYTHON_VLAN_27                   active    \n28   PYTHON_VLAN_28                   active    \n29   PYTHON_VLAN_29                   active    \n30   PYTHON_VLAN_30                   active    \n31   PYTHON_VLAN_31                   active    \n32   PYTHON_VLAN_32                   active    \n1002 fddi-default
          active    \n1003 token-ring-default               active    \n1004 fddinet-default                  active    \n1005 trnet-default                    active    ']
root@NetAutomate-1:~/scripts/P3FNE_Lab1#
```
