### ISSUE TITLE
How to connect trough proxy with "'allow_agent': True"

### ISSUE THREAD

**Issue by Muadiv** [ktbyers/netmiko#874]
Hi, I'm trying to connect trough a jumpserver that with this code I can connect and execute commands: 

```
device = {
    'host': '192.168.1.10',
    'username': 'admin',
    'allow_agent': True,
    'device_type': 'autodetect',
}
```
Now, I need to use this linux server as jumpserver, and trying with the code that you suggest and also with the sshconfig file, I can't (btw, the script computer is Windows 7). 
this is the code that I'm using now

```
from netmiko import ConnectHandler
from getpass import getpass

ciscodevice = "192.168.1.11"
password = getpass()

cisco = {
    'device_type': 'cisco_ios',
    'ip': ciscodevice,
    'username': 'cisco',
    'password': password,
    'ssh_config_file': 'sshconfig.txt',
    'verbose': False,
}

net_connect = ConnectHandler(**cisco)
output = net_connect.send_command('show version')
print(output)
print(net_connect.find_prompt())
```

And the config file: 
```
host jumphost                   # Intermediate server
  IdentityFile c:\privatekey.ppk
  user admin
  hostname 192.168.1.10

host 192.168.1.11
  user cisco
  hostname 192.168.1.11
  Port 22
  ProxyCommand ssh jumphost
```
Whit this code, I'm receiving this error: 

```
>>> net_connect = ConnectHandler(**cisco)
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\netmiko\base_connection.py", line 689, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\paramiko\client.py", line 329, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\paramiko\client.py", line 200, in _families_and_addresses
    hostname, port, socket.AF_UNSPEC, socket.SOCK_STREAM)
  File "C:\Program Files (x86)\Python36-32\lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#17>", line 1, in <module>
    net_connect = ConnectHandler(**cisco)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\netmiko\ssh_dispatcher.py", line 178, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\netmiko\base_connection.py", line 207, in __init__
    self.establish_connection()
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\netmiko\base_connection.py", line 693, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios 192.168.1.11:22
```

_Anyway_, there is **any** way to config the jumpserver directly on the python code? something like: 

```
cisco = {
    'device_type': 'cisco_ios',
    'ip': '192.168.1.11',
    'username': 'cisco',
    'password': password,
    'jump_config_host': '192.168.1.10',
    'jump_username': 'admin',
    'jump_allow_agent': True,
    'jump_device_type': 'autodetect',
    'verbose': False,
}
```

Thanks in advance. 
Muadiv.

**Comment by yyjkt** [comment]
did u solve it ?  me face same issue . how to easy to use proxy to connect NE. thanks.
