### ISSUE TITLE
Nexus 7000 VDC support

### ISSUE THREAD

**Issue by ChristopherJHart** [ktbyers/netmiko#882]
Currently, cisco_nxos_ssh.py does not easily support switching between VDCs on Nexus 7000 devices, which involves changing the base prompt as shown below:

```
N7K-A-Admin# show version | i Nexus7000
  cisco Nexus7000 C7004 (4 Slot) Chassis ("Supervisor Module-2")
N7K-A-Admin# show vdc

Switchwide mode is m1 f1 m1xl f2 m2xl f2e f3 

vdc_id  vdc_name                          state               mac                 type        lc      
------  --------                          -----               ----------          ---------   ------  
1       N7K-A-Admin                       active              84:78:ac:0c:7b:41   Admin       None    
2       RTP-AGG1                          active              84:78:ac:0c:7b:42   Ethernet    f2      
3       RTP-OTV1                          active              84:78:ac:0c:7b:43   Ethernet    m2xl    
4       SJ-AGG1                           active              84:78:ac:0c:7b:44   Ethernet    f2      
5       SJ-OTV1                           active              84:78:ac:0c:7b:45   Ethernet    m2xl    
6       SPINE-1                           active              84:78:ac:0c:7b:46   Ethernet    f2      
7       LEAF-10                           active              84:78:ac:0c:7b:47   Ethernet    f2      

N7K-A-Admin# switchto vdc RTP-AGG1
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (c) 2002-2017, Cisco Systems, Inc. All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under
license. Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or the GNU
Lesser General Public License (LGPL) Version 2.1. A copy of each
such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://www.opensource.org/licenses/lgpl-2.1.php
RTP-AGG1# 
```

Because the base prompt changes, netmiko errors out when switching VDCs:

```
C:\Users\chart2>python
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from netmiko import ConnectHandler
>>> nx_device = {"device_type": "cisco_nxos", "ip": "10.122.140.84", "username": "admin", "password": "cisco!123"}
>>> target_con = ConnectHandler(**nx_device)
>>> target_con.send_command("switchto vdc RTP-AGG1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\chart2\AppData\Local\Programs\Python\Python36-32\lib\site-packages\netmiko\base_connection.py", line 967, in send_command
    search_pattern))
OSError: Search pattern never detected in send_command_expect: N7K\-A\-Admin\#
```

At the moment, this can be handled by the user using the `expect_string` parameter of BaseConnection.send_command() or BaseConnection.send_command_expect() when sending either `switchto vdc VDC_NAME` or `switchback`, as shown below.

```
>>> target_con.send_command("switchto vdc RTP-AGG1", expect_string="RTP-AGG1#")
'Cisco Nexus Operating System (NX-OS) Software\nTAC support: http://www.cisco.com/tac\nCopyright (c) 2002-2017, Cisco Systems, Inc. All rights reserved.\nThe copyrights to certain works contained in this software are\nowned by other third parties and used and distributed under\nlicense. Certain components of this software are licensed under\nthe GNU General Public License (GPL) version 2.0 or the GNU\nLesser General Public License (LGPL) Version 2.1. A copy of each\nsuch license is available at\nhttp://www.opensource.org/licenses/gpl-2.0.php and\nhttp://www.opensource.org/licenses/lgpl-2.1.php\nRTP-AGG1# '
>>> target_con.send_command("switchback", expect_string="N7K-A-Admin#")
''
```

However, precedent for changing the base prompt on Cisco devices where necessary has been set by cisco_asa_ssh.py for ASA devices configured in multi-context mode. There should be a similar implementation for handling VDCs on NX-OS devices.

**Comment by ktbyers** [comment]
@ChristopherJHart You should be able to do the following:

```
target_con.send_command_timing("switchto vdc RTP-AGG1")
```

Or alternatively:

```
target_con.send_command("switchto vdc RTP-AGG1", expect_string=r'#')
```

**Comment by ktbyers** [comment]
@ChristopherJHart 

```
However, precedent for changing the base prompt on Cisco devices where 
necessary has been set by cisco_asa_ssh.py for ASA devices configured in 
multi-context mode. There should be a similar implementation for handling 
VDCs on NX-OS devices.
```

This is probably more of an argument to remove that code from the ASA, if possible (i.e. it is better to have a more general, flexible solution than to need to add special handlers for each platform).

Is there some reason the `expect_string` solution doesn't work on Nexus?

**Comment by ChristopherJHart** [comment]
@ktbyers The `expect_string` solution works on Nexus without an issue, as well as the other solutions you posted. I opened up this issue so I could implement the special handlers for VDCs on NX-OS the same way we handle multi-context mode on ASAs within the next few hours.

I agree that removing the special handlers from the ASA code would result in a more flexible, consistent solution across all Cisco platforms. If you're okay with me removing that handler code alongside all other unit tests, I'll gladly do so!

**Comment by ktbyers** [comment]
Main issue that needs thought about some more is that it is probably going to break existing code (which is not good). Probably needs to be in a Netmiko major release (i.e. Netmiko 3.X.X).

I probably shouldn't have implemented that ASA code originally (i.e. it is generally not consistent with how Netmiko behaves).

**Comment by ChristopherJHart** [comment]
I agree that such a change would most likely break existing code.

What if we did something similar to this?

```
    def send_command(self, *args, **kwargs):
        """
        If the ASA is in multi-context mode, then the base_prompt needs to be
        updated after each context change.
        """
        if len(args) >= 1:
            command_string = args[0]
        else:
            command_string = kwargs['command_string']

        # If changeto in command, look for '#' to determine command is done
        if "changeto" in command_string:
            import warnings
            warnings.warn("Utilizing `changeto` in CiscoAsaSSH.send_command() is deprecated. This function will no longer natively support multi-context mode and will require an expect_string parameter in order to match current functionality. Current functionality will be removed in Netmiko 3.X.X", DeprecationWarning)
            if len(args) <= 1:
                expect_string = kwargs.get('expect_string', '#')
                kwargs['expect_string'] = expect_string
        output = super(CiscoAsaSSH, self).send_command(*args, **kwargs)

        if "changeto" in command_string:
            self.set_base_prompt()

        return output
```

If my research on warnings.warn is correct, DeprecationWarning won't appear in the Python interpreter unless specific flags are used. However, it might be picked up by IDEs and push people towards doing it the way we want.

**Comment by carlmontanari** [comment]
Going to close this as its pretty old and it sounds like its enough of a departure from "normal" that it isn't something we'd want to support. I think the "fix" is using the send_command_timing or expect string as has been pointed out here!
