### ISSUE TITLE
Cisco Catalyst 4500: Illegal info request from server

### ISSUE THREAD

**Issue by rbeumer** [ktbyers/netmiko#904]
I can login via SSH manually, but when I try to use Netmiko:

```
2018-08-08 11:38:47,343 DEBUG:starting thread (client mode): 0xfe9c1f60
2018-08-08 11:38:47,343 DEBUG:Local version/idstring: SSH-2.0-paramiko_2.4.1
2018-08-08 11:38:47,343 DEBUG:Remote version/idstring: SSH-2.0-Cisco-1.25
2018-08-08 11:38:47,343 INFO:Connected (version 2.0, client Cisco-1.25)
2018-08-08 11:38:47,346 DEBUG:kex algos:['diffie-hellman-group-exchange-sha1', 'diffie-hellman-group14-sha1', 'diffie-hellman-group1-sha1'] server key:['ssh-rsa'] client encrypt:['aes128-cbc', '3des-cbc', 'aes192-cbc', 'aes256-cbc'] server encrypt:['aes128-cbc', '3des-cbc', 'aes192-cbc', 'aes256-cbc'] client mac:['hmac-sha1', 'hmac-sha1-96', 'hmac-md5', 'hmac-md5-96'] server mac:['hmac-sha1', 'hmac-sha1-96', 'hmac-md5', 'hmac-md5-96'] client compress:['none'] server compress:['none'] client lang:[''] server lang:[''] kex follows?False
2018-08-08 11:38:47,346 DEBUG:Kex agreed: diffie-hellman-group-exchange-sha1
2018-08-08 11:38:47,346 DEBUG:HostKey agreed: ssh-rsa
2018-08-08 11:38:47,346 DEBUG:Cipher agreed: aes128-cbc
2018-08-08 11:38:47,347 DEBUG:MAC agreed: hmac-sha1
2018-08-08 11:38:47,347 DEBUG:Compression agreed: none
2018-08-08 11:38:47,550 DEBUG:Got server p (2048 bits)
2018-08-08 11:38:48,151 DEBUG:kex engine KexGex specified hash_algo <built-in function openssl_sha1>
2018-08-08 11:38:48,152 DEBUG:Switch to new keys ...
2018-08-08 11:38:48,153 DEBUG:Adding ssh-rsa host key for [redacted-ip] b'49ad87fe4d118f6ae351c300d9532fe7'
2018-08-08 11:38:48,350 DEBUG:userauth is OK
2018-08-08 11:38:48,350 INFO:Auth banner: b'\r\n+----------------------------------------------------------------------+\r\n|                                                                      |\r\n|         You are entering a restricted area.                          |\r\n|                                                                      |\r\n|    Do not try to login if you are not authorized.                    |\r\n|                                                                      |\r\n+----------------------------------------------------------------------+\r\n'
2018-08-08 11:38:48,399 ERROR:Exception: Illegal info request from server
2018-08-08 11:38:48,403 ERROR:Traceback (most recent call last):
2018-08-08 11:38:48,404 ERROR:  File "/usr/lib/python3.6/site-packages/paramiko/transport.py", line 1949, in run
2018-08-08 11:38:48,404 ERROR:    handler(self.auth_handler, m)
2018-08-08 11:38:48,404 ERROR:  File "/usr/lib/python3.6/site-packages/paramiko/auth_handler.py", line 622, in _parse_userauth_info_request
2018-08-08 11:38:48,404 ERROR:    raise SSHException('Illegal info request from server')
2018-08-08 11:38:48,404 ERROR:paramiko.ssh_exception.SSHException: Illegal info request from server
```

So authentication seems to be working (userauth is OK).

My code:

```
from netmiko import ConnectHandler

def getsshoverpasswd(ip, username, password, device_type):
node = {
'device_type': device_type,
'ip': ip,
'username': username,
'password': password,
'timeout': 8,
}
ssh = ConnectHandler(**node)

return(ssh)

s = netmiko.getsshoverpasswd(locations[location]['ipv4'], ssh.ssh_user, passwd, "cisco_xe")
trunk_vlans = s.send_command("show vlan")
```

Python 3.6.4
Netmiko 2.1.1

**Comment by ktbyers** [comment]
@rbeumer Which version of Paramiko do you have installed? Want to look at their source code and knowing this will make it easier for me to use the stack trace.


Kirk

**Comment by rbeumer** [comment]
@ktbyers paramiko version 2.4.1

**Comment by rbeumer** [comment]
@ktbyers any luck?

**Comment by ktbyers** [comment]
I will have to look at it more. This is an error that happens with Cisco IOS in certain contexts, but I will have to dig into it more. From past experience, it is probably going to be hard to solve.

Especially since I can't reproduce the problem.

**Comment by carlniger** [comment]
Curious if this is still a problem/reproducible on Paramiko 2.4.2 and netmiko 2.3.3? Going to close as this is pretty old, but please re-open and let us know if its still happening on the newer versions. Not sure there will be a ton to do since it will be hard to figure out w/out being able to reproduce, but at least we'll all know :)
