### ISSUE TITLE
Commit hostname change on Juniper switch errors

### ISSUE THREAD

**Issue by DerrickTJ** [ktbyers/netmiko#905]
I have a script that goes through a switch and applies quite a few changes. However I believe it is hanging up on the hostname changed when I commit. The switch does commit the changes, but what netmiko expects to be returned has changed.

Old Hostname: 9026Switch_247
New Hostname: 9026-BACK-SW-001

The pattern it expects back in the prompt has changed so it just errors with the output below. How should I overcome this error?

```
Traceback (most recent call last):
  File "C:\Users\username\Desktop\Python Test\JuniperHostname.py", line 220, in <module>
    Connection = JuniperConnect(SwitchOctetsInt=Misc3SwitchOctetsInt, Name="MISC", SWNum="3")
  File "C:\Users\username\Desktop\Python Test\JuniperHostname.py", line 187, in JuniperConnect
    Connection.commit()
  File "C:\Users\username\AppData\Local\Programs\Python\Python36-32\lib\site-packages\netmiko\juniper\juniper_ssh.py", line 148, in commit
    strip_command=False, delay_factor=delay_factor)
  File "C:\Users\username\AppData\Local\Programs\Python\Python36-32\lib\site-packages\netmiko\base_connection.py", line 985, in send_command_expect
    return self.send_command(*args, **kwargs)
  File "C:\Users\username\AppData\Local\Programs\Python\Python36-32\lib\site-packages\netmiko\base_connection.py", line 967, in send_command
    search_pattern))
OSError: Search pattern never detected in send_command_expect: admin\@**9026Switch_247**\#
```

This is my code that applies the config. I cut out 95% of the stuff it does as the hostname should be the only thing that matters I believe.
```
NewConfig = [
                "set system host-name "+SInput+"-"+Name+"-SW-00"+SWNum,
                'set snmp location "sfas dfaf"',
            ]
            NewConfigRawOutput = Connection.send_config_set(NewConfig)
            print ("Saving Configuration...")
            Connection.commit()
            Connection.exit_config_mode()
```

**Comment by DerrickTJ** [comment]
Guess this happens with any device type obviously. Started changing hostnames on cisco devices as well but the error is much longer once the name is changed.

**Comment by DerrickTJ** [comment]
Found my answer after digging around for different solutions on the matter.

`send_command_timing()` ignores the prompt and just applies the config.
