### ISSUE TITLE
Issue when changing hostname on IOS device

### ISSUE THREAD

**Issue by superloopnetwork** [ktbyers/netmiko#941]
I receive the following error message when I try and change the hostname of a Cisco IOS device:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/staging/superloop/lib/objects/basenode.py", line 61, in push_config
    output = self.net_connect.send_config_set(commands)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 965, in send_config_set
    output += self.exit_config_mode()
  File "/usr/local/lib/python2.7/dist-packages/netmiko/cisco_base_connection.py", line 50, in exit_config_mode
    pattern=pattern)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 915, in exit_config_mode
    if self.check_config_mode():
  File "/usr/local/lib/python2.7/dist-packages/netmiko/cisco_base_connection.py", line 32, in check_config_mode
    pattern=pattern)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 896, in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 338, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 289, in _read_channel_expect
    raise NetMikoTimeoutException("Timed-out reading channel, data not available.")
NetMikoTimeoutException: Timed-out reading channel, data not available
```
The strange part is, it does complete the change of the new hostname but then my program halts after the next run (loop).

Any ideas? Other commands work just fine... hostname <new_hostname> seems to throw it off... I'm feeding the commands via 'send_config_set'..

**Comment by ktbyers** [comment]
Can you show me your code? 

Also what version of Netmiko are you using?


Kirk

**Comment by superloopnetwork** [comment]
Hi Kirk,

Below is my code... How do I check which version of netmiko I'm using? And how do I update if required?
```
        def push_config(self,commands):
                self.connect()
                print('#' * 86)
                output = self.net_connect.send_config_set(commands)
                print ("{}".format(output))
                print('#' * 86)
                self.net_connect.disconnect()
```

Thanks!

**Comment by ktbyers** [comment]
Yes and what does `commands` contain?

Also, what version of netmiko are you running.

```python
import netmiko
netmiko.__version__
```

**Comment by superloopnetwork** [comment]
Commands is a list of command(s). But in this particular case where it doesn't work, I have just a 'hostname blah'

commands = ['hostname blah']

*Other commands work perfectly without any errors..

Here is the version:

>>> netmiko.__version__
u'1.4.2'

**Comment by ktbyers** [comment]
You need to upgrade to Netmiko 2.2. Generally the process to do this is:

```
pip install netmiko==2.2.2
```

I am going to close this issue as I think the problem doesn't exist on recent versions of Netmiko.

**Comment by superloopnetwork** [comment]
Thanks Kirk!!

**Comment by superloopnetwork** [comment]
Yup, that definitely fixed it! :) Thanks!
