### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'recv_ready'

### ISSUE THREAD

**Issue by kristoferus75** [ktbyers/netmiko#946]
Hi !

After update to python3.7 i get now this error if i start my netmiko python script:

```
Traceback (most recent call last):
  File "inv6.py", line 172, in <module>
    receive_config()
  File "inv6.py", line 104, in receive_config
    output = net_connect.send_command('show inventory | i PID')
  File "/usr/lib/python3.7/site-packages/netmiko/base_connection.py", line 1068, in send_command
    prompt = self.find_prompt(delay_factor=delay_factor)
  File "/usr/lib/python3.7/site-packages/netmiko/base_connection.py", line 927, in find_prompt
    self.clear_buffer()
  File "/usr/lib/python3.7/site-packages/netmiko/base_connection.py", line 961, in clear_buffer
    self.read_channel()
  File "/usr/lib/python3.7/site-packages/netmiko/base_connection.py", line 395, in read_channel
    output = self._read_channel()
  File "/usr/lib/python3.7/site-packages/netmiko/base_connection.py", line 373, in _read_channel
    if self.remote_conn.recv_ready():
AttributeError: 'NoneType' object has no attribute 'recv_ready'
```

**Comment by ktbyers** [comment]
That message indicates that `self.remote_conn` has a value of None.

You might want to look at the Netmiko session_log or at Netmiko logging and see if that gives you more ideas as to what happened.
