### ISSUE TITLE
netmiko_file_transfer for large files succeeds but as socket is closed and Nornir  subtask fails

### ISSUE THREAD

**Issue by Sh4mSh4m** [ktbyers/netmiko#948]
Hi,

**Context**
I'm using netmiko plugins for Nornir and in the context of transferring IOS .bin files to a switch.
To that end I use the netmiko_file_transfer method:

````python
start_time = time.time()
nr = InitNornir()
print(nr.inventory.hosts)
print(f"Connection initiated at {time.time() - start_time} seconds")

file = "c2960x-universalk9-mz.152-2.E3.bin"
play_chg_upload_file = nr.run(task=chg_upload_file, start_time=start_time, file=file)
print_result(play_chg_upload_file)


def chg_upload_file(task, file, start_time):
    """
    Upload files to stack
    """
    task.run(
        task=netmiko_file_transfer,
        source_file=file,
        dest_file=file,
        direction='put',
    )
    print(f"Uploaded {file} at: {time.time() - start_time} seconds")
````

**Result**
Everything works as file is transferred to the switch. However the Nornir task fails and return, and print_result of the task shows the following:

```shell
Uploaded c2960x-universalk9-mz.152-2.E3.bin at: 853.6508374214172 seconds
chg_upload_file*****************************************************************
* labfpr ** changed : False ****************************************************
vvvv chg_upload_file ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv ERROR
Subtask: netmiko_file_transfer (failed)

---- netmiko_file_transfer ** changed : False ---------------------------------- ERROR
Traceback (most recent call last):
  File "/home/hieu.truong/.local/share/virtualenvs/unity_rm_platform-9N8saghV/lib/python3.6/site-packages/nornir/core/task.py", line 62, in start
    r = self.task(self, **self.params)
  File "/home/hieu.truong/.local/share/virtualenvs/unity_rm_platform-9N8saghV/lib/python3.6/site-packages/nornir/plugins/tasks/networking/netmiko_file_transfer.py", line 24, in netmiko_file_transfer
    net_connect, source_file=source_file, dest_file=dest_file, **kwargs
  File "/home/hieu.truong/.local/share/virtualenvs/unity_rm_platform-9N8saghV/lib/python3.6/site-packages/netmiko/scp_functions.py", line 97, in file_transfer
    if scp_transfer.compare_md5():
  File "/home/hieu.truong/.local/share/virtualenvs/unity_rm_platform-9N8saghV/lib/python3.6/site-packages/netmiko/scp_handler.py", line 255, in compare_md5
    remote_md5 = self.remote_md5()
  File "/home/hieu.truong/.local/share/virtualenvs/unity_rm_platform-9N8saghV/lib/python3.6/site-packages/netmiko/scp_handler.py", line 272, in remote_md5
    dest_md5 = self.ssh_ctl_chan.send_command(remote_md5_cmd, max_loops=1500)
  File "/home/hieu.truong/.local/share/virtualenvs/unity_rm_platform-9N8saghV/lib/python3.6/site-packages/netmiko/base_connection.py", line 1068, in send_command
    prompt = self.find_prompt(delay_factor=delay_factor)
  File "/home/hieu.truong/.local/share/virtualenvs/unity_rm_platform-9N8saghV/lib/python3.6/site-packages/netmiko/base_connection.py", line 928, in find_prompt
    self.write_channel(self.RETURN)
  File "/home/hieu.truong/.local/share/virtualenvs/unity_rm_platform-9N8saghV/lib/python3.6/site-packages/netmiko/base_connection.py", line 335, in write_channel
    self._write_channel(out_data)
  File "/home/hieu.truong/.local/share/virtualenvs/unity_rm_platform-9N8saghV/lib/python3.6/site-packages/netmiko/base_connection.py", line 306, in _write_channel
    self.remote_conn.sendall(write_bytes(out_data))
  File "/home/hieu.truong/.local/share/virtualenvs/unity_rm_platform-9N8saghV/lib/python3.6/site-packages/paramiko/channel.py", line 831, in sendall
    sent = self.send(s)
  File "/home/hieu.truong/.local/share/virtualenvs/unity_rm_platform-9N8saghV/lib/python3.6/site-packages/paramiko/channel.py", line 785, in send
    return self._send(s, m)
  File "/home/hieu.truong/.local/share/virtualenvs/unity_rm_platform-9N8saghV/lib/python3.6/site-packages/paramiko/channel.py", line 1170, in _send
    raise socket.error('Socket is closed')
OSError: Socket is closed

^^^^ END chg_upload_file ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
END GAME AT : 853.7029922008514 seconds
```

**Expected**
Well indeed I except the file to be transferred but with the task being successful so I can go on with my "playbook" and have the remaining tasks running on the host.

**Work around**
I'm guessing I can run following tasks by reinitializing the host in the Nornir inventory

**Question**
My initial thought was that it was required to play on the delay_factor and max_loops to extend the timeout for the connection, but setting those is not expected for the function. As you can see, task too more than 10 minutes to upload a 10MB file.
I think I remember reading that netmiko_file_transfer uses two ssh_connections, one actually doing the transfer with SCP while the other is the connection to the device and performing md5 checks for instance. Is that correct ? Could it be this one failing at the end ?

Thanks, 

Hieu

**Comment by Sh4mSh4m** [comment]
Thanks for the work around. It works. 
Thanks again for the super quick feedback !

**Comment by edurguti** [comment]
@Sh4mSh4m  which settings did you change on vty?

**Comment by ktbyers** [comment]
In `line vty 0 4` change the exec-timeout. I would probably set it to this:

```
line vty 0 4
  exec-timeout 60 0
```

That is 60 minutes...you have to judge the total required time based on your file transfer requirements.

**Comment by edurguti** [comment]
That did it, thanks!

**Comment by tsasank007** [comment]
I have this already in place on the device: 

```
line vty 0 4
 exec-timeout 15 0
 logging synchronous
 transport input ssh
 transport output all
line vty 5 15
 exec-timeout 15 0
 logging synchronous
 transport input ssh
```

even then it doesn't work for me .. i get exception  `"here is the exception : Socket is closed  ` immediately I dont think this is trying at-all


My code for reff:

```
def transfer_file(session, file):
    session.enable()
    my_transfer = file_transfer(
        session,
        source_file = file,
        dest_file = file,
        file_system=None,
        direction= 'put',
    )


def main():

    try:
        for node in nodes:   #I have a list of nodes 
            if match:
                hostname = match[0]
                connection = {
                    'device_type': 'cisco_ios',
                    'ip': hostname,
                    'username': creds['username'],
                    'password': creds['password'],
                    'verbose': False
                }
                session = netmiko.ConnectHandler(**connection)
                # Removes terminal length for parsing.
                session.send_command('terminal length 0\n')
                model = get_interface_by_model(session)
                print(f'the host name is {node} and the model is {model}')

                if model in config:
                    image = config[model]['image']
                    # print(f"Uploading {image} to {hostname}")
                    transfer_file(session, image)

```

**Comment by Codaxi** [comment]
Hello @ktbyers. I have scoured the net and documentations to try and figure this one out, but this post is the closest to helping me. 

I am also using file_transfer to send a .bin file to remote device (721MB in size taking about 2 hours to complete). 

I have changed my virtual lines on the device to be 10 hours long, but i am still getting the socket closed error. 

I also tried changing the socket_timeout to 18000 (i am not sure what unit it uses, i assumed seconds so i changed it to 5 hours) and this still didn't stop the socket from closing.  What do you think I am doing wrong?


**Socket Timeout set to 18000:**
```
transfer_dict = file_transfer(
                    ssh_conn,
                    source_file=source_file,
                    dest_file=dest_file,
                    file_system=file_system,
                    direction=direction,
                    socket_timeout=18000
                    )
```


**Virtual Lines set to 600 1**
```
cisco_iosxe#show line vty 2
   Tty Line Typ     Tx/Rx    A Modem  Roty AccO AccI  Uses  Noise Overruns  Int 
    868  868 VTY              -    -      -    -    -     5      0    0/0      -

Line 868, Location: "", Type: ""
Length: 24 lines, Width: 80 columns
Baud rate (TX/RX) is 9600/9600
Status: Ready, No Exit Banner
Capabilities: none
Modem state: Ready
Special Chars: Escape  Hold  Stop  Start  Disconnect  Activation
                ^^x    none   -     -       none
**********BELOW LINE SHOWS THE TIMEOUT OF 10 HOURS***************************
Timeouts:      Idle EXEC    Idle Session   Modem Answer  Session   Dispatch 
               10:00:01        never                        none     not set**
****************************************************************************************
                            Idle Session Disconnect Warning
                              never
                            Login-sequence User Response
                             00:00:30
                            Autoselect Initial Wait
                              not set
Modem type is unknown.
Session limit is not set.
Time since activation: never
Editing is enabled.
History is enabled, history size is 10.
DNS resolution in show commands is enabled
Full user help is disabled
Allowed input transports are ssh.
Allowed output transports are ssh.
Preferred transport is telnet.
Automatically execute command "menu devices"
Shell: enabled
Shell trace: off
No output characters are padded
No special data dispatching characters
```

After reading your reply I remembered that there were 2 ssh sessions (1st being control and 2nd being scp) when checking the active ssh connections: 
- Control Session was disconnected
- SCP session was still connected 

I hope this question reaches you.

**Comment by ktbyers** [comment]
@Sh4mSh4m Can you post the error that you receive when the connection is closed.

Can you post the configuration of your VTY lines?

Is there any firewall between you and the network device that you are transferring to? 

How long does it take before the disconnect happens.

**Comment by Codaxi** [comment]
@ktbyers 

Note: Cisco device is a terminal server which I am sending the file to. I use "cisco_xe" as the device type, not sure if you think this will be an issue?

```
    cisco = {
        'device_type': 'cisco_xe',
        'host': device,
        'username': USERNAME,
        'password': PASSWORD
        'port': 22,
        'verbose':True,
        'file_system': 'bootflash:',
        'session_log': f'logs\\netmiko_session_logs\\netmiko_session_{device}_{time.time():.2f}.log',
    }
```

I don't have the exact error as I catch it in my exception clause. It just says "socket is closed":


**VTY Config:** 
```
line vty 0 4
 exec-timeout 600 0
 privilege level 15
 transport input ssh
 transport output ssh
line vty 5 15
 exec-timeout 600 0
 privilege level 15
 transport input ssh
 transport output ssh
```

Firewall; there is definitely firewall between host and end device. 

The file itself takes about 2 hours to transfer over, it successfully gets transferred over, but then when the "file_transfer" function wants to verify the file, that is when I get the error that the socket got closed. I am not entirely sure when it actually closes.

**Comment by ktbyers** [comment]
`socket got closed` probably means something on your side closed it (if you include the full exception stack trace, might have more we could look at, but yes you would need to remove your exception handling).

If the transfer works, you could also just catch the exception and re-run the MD5 to verify the hash (or even re-run the file_transfer since Netmiko should see the file already exists and will just run the MD5 on it).

**Comment by Codaxi** [comment]
Hey, I just ran the code, but forgot to remove some exception blocks. I will run it again and get back to you soon. 

I also turned on netmiko logging - I saw in your other answers, hopefully that helps.

**Comment by Codaxi** [comment]
Here is the crash report: 

```
Progress on x.x.x.x: 100.0%

Traceback (most recent call last):
  File "C:\..\test.py", line 504, in <module>
    multi_transfer(device_dict_list)
  File "C:\..\test.py", line 454, in multi_transfer
    transfer_dict = file_transfer(
                    ^^^^^^^^^^^^^^
  File "C:\..\Lib\site-packages\netmiko\scp_functions.py", line 152, in file_transfer
    if scp_transfer.verify_file():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\..\Lib\site-packages\netmiko\scp_handler.py", line 414, in verify_file
    return self.compare_md5()
           ^^^^^^^^^^^^^^^^^^
  File "C:\..\Lib\site-packages\netmiko\scp_handler.py", line 365, in compare_md5
    remote_md5 = self.remote_md5()
                 ^^^^^^^^^^^^^^^^^
  File "C:\..\Lib\site-packages\netmiko\scp_handler.py", line 386, in remote_md5
    dest_md5 = self.ssh_ctl_chan._send_command_str(remote_md5_cmd, read_timeout=300)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\..\Lib\site-packages\netmiko\base_connection.py", line 1846, in _send_command_str
    output = self.send_command(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\..\Lib\site-packages\netmiko\base_connection.py", line 110, in wrapper_decorator
    return_val = func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\..\Lib\site-packages\netmiko\utilities.py", line 595, in wrapper_decorator
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\..\Lib\site-packages\netmiko\base_connection.py", line 1762, in send_command
    search_pattern = self._prompt_handler(auto_find_prompt)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\..\Lib\site-packages\netmiko\base_connection.py", line 1641, in _prompt_handler
    prompt = self.find_prompt()
             ^^^^^^^^^^^^^^^^^^
  File "C:\..\Lib\site-packages\netmiko\base_connection.py", line 1424, in find_prompt
    self.write_channel(self.RETURN)
  File "C:\..\Lib\site-packages\netmiko\base_connection.py", line 97, in wrapper_decorator
    return_val = func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\..\Lib\site-packages\netmiko\base_connection.py", line 125, in wrapper_decorator
    func(self, out_data)
  File "C:\..\Lib\site-packages\netmiko\base_connection.py", line 586, in write_channel
    self.channel.write_channel(out_data)
  File "C:\..\Lib\site-packages\netmiko\channel.py", line 74, in write_channel
    self.remote_conn.sendall(write_bytes(out_data, encoding=self.encoding))
  File "C:\..\Lib\site-packages\paramiko\channel.py", line 844, in 
sendall
    sent = self.send(s)
           ^^^^^^^^^^^^
  File "C:\..\Lib\site-packages\paramiko\channel.py", line 799, in 
send
    return self._send(s, m)
           ^^^^^^^^^^^^^^^^
  File "C:\..\Lib\site-packages\paramiko\channel.py", line 1196, in _send
    raise socket.error("Socket is closed")
OSError: Socket is closed
```

**Comment by ktbyers** [comment]
Okay, pretty clearly looks like something on the network closed the socket (either device or intermediate firewall). It is failing at the point the SSH control channel is used again.

I guess you could try to enable SSH keepalives.

Alternatively, you can probably just catch the exception and re-run the file transfer. On the second attempt Netmiko will see the file already exists and the hashes match (so it won't re-transfer it).

**Comment by Codaxi** [comment]
Is there a way to send keep alives using netmiko (i feel like this would be a cleaner way to handle it)? 

Otherwise I will just catch the exception and re-run it.

**Comment by ktbyers** [comment]
@Codaxi

```
        :param keepalive: Send SSH keepalive packets at a specific interval, in seconds.
                Currently defaults to 0, for backwards compatibility (it will not attempt
                to keep the connection alive).
```
