### ISSUE TITLE
2nd device timing out, even with delay_factor, first device not returning any output.

### ISSUE THREAD

**Issue by maughanc** [ktbyers/netmiko#987]
```python
#!/usr/local/bin/python3.6

import netmiko
from netmiko import ConnectHandler
import getpass
from getpass import getpass
exceptions = (netmiko.ssh_exception.NetMikoTimeoutException, netmiko.ssh_exception.NetMikoAuthenticationException)

     router = {
    'device_type': 'cisco_ios',
    'ip': '10.1.1.1',
    'username': 'admin',
    'password': getpass(),
    'secret': getpass("Enable: "),
}

      switch = {
    'device_type': 'cisco_ios',
    'ip': '10.1.1.2',
    'username': 'admin',
    'password': getpass(),
    'secret': getpass("Enable: "),
    'global_delay_factor': 8,
}

list_of_devices = [router, switch]
for devices in list_of_devices:
    connector = ConnectHandler(**devices)
    connector.enable()

output = connector.send_command("show arp", delay_factor=8)
print(output)



connector.disconnect()
```

_______________

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 689, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 338, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/local/lib/python3.6/site-packages/paramiko/util.py", line 279, in retry_on_signal
    return function()
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 338, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MultipleShow.py", line 28, in <module>
    connector = ConnectHandler(**devices)
  File "/usr/local/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 178, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 207, in __init__
    self.establish_connection()
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 693, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios 10.1.1.2:22

**Comment by ktbyers** [comment]
Netmiko couldn't reach this device for SSH:

Connection to device timed-out: cisco_ios 10.1.1.2:22


Your code is a bit hard to read in GitHub (I added the formatting backticks to it):

But if it is like this:

```python
list_of_devices = [router, switch]
for devices in list_of_devices:
    connector = ConnectHandler(**devices)
    connector.enable()

output = connector.send_command("show arp", delay_factor=8)
print(output)
```

Then your send_command call is outside the for loop (so it won't do anything for the first device besides establish the connection and go into enable mode).
